### ISSUE TITLE
Pre-copy in CRIU

### ISSUE THREAD

**Issue by 123toorc** [checkpoint-restore/criu#1004]
Hi, I successfully implement the pre-dump, it did reduce the dump frozen and mem_dump time. Since I dumped a Redis server, sometimes the Page.img will be extremely big, which lets the image copy part causes a significant delay. 
I can't find any reference regarding the use pre-copy in CRIU. I checked the link: https://www.redhat.com/en/blog/container-migration-around-world. Which uses a RunC Container to do the pre-copy migrations. Is there any command for CRIU to do like it? 
Because I have tried the incremental dump, the dump image size still big. And wiki also mentioned pre-dump is not for later restore, refer: https://criu.org/Memory_changes_tracking.  
How can I accomplish it?  
Thanks.

**Comment by adrianreber** [comment]
If you tell us the exact commands you are using, I am sure we can help you.

> https://www.redhat.com/en/blog/container-migration-around-world. Which uses a RunC Container to do the pre-copy migrations. Is there any command for CRIU to do like it?

The runc interface is more or less the same as the CRIU CLI interface.

Just list all the commands you are using and this should be solvable.

**Comment by 123toorc** [comment]
This is the commands I use for the incremental dump(shorter to two dumps as an example):
I first I added some fake data into the Redis server
Then I did:
$criu dump -t 12345 --images-dir ./dump1/ --track-mem -shell-job --tcp-established --leave-running 
Then I did the second dump after a small change or even no change to Redis server:
$criu dump -t 12345 --images-dir ./dump2/ --track-mem -shell-job --tcp-established --prev-images-dir ../dump1/
For pre-dump, I just change the first one to pre-dump and remove the leave-running
What should I do to implement the pre-copy? For example, if I do dump twice and there is no memory change, the second dumped page image should be small.

**Comment by adrianreber** [comment]
Please list the exact the command sequence you are using for your pre-dump migration. Do not describe what you do, just the list of commands you are using. The following works for me:

```
# criu pre-dump --track-mem -t 10585 -D /tmp/first-dump/
# criu dump -t 10585 -D /tmp/second-dump/ --prev-images-dir ../first-dump --track-mem
# du -hs /tmp/first-dump/ /tmp/second-dump/
1.1G	/tmp/first-dump/
60K	/tmp/second-dump/
# ls -la /tmp/first-dump/
total 1048760
drwxr-xr-x.  2 root root       4096 Mar 28 09:54 .
drwxrwxrwt. 11 root root      36864 Mar 28 09:56 ..
-rw-r--r--.  1 root root         17 Mar 28 09:54 inventory.img
-rw-r--r--.  1 root root          8 Mar 28 09:54 irmap-cache
-rw-r--r--.  1 root root       8898 Mar 28 09:54 pagemap-10585.img
-rw-r--r--.  1 root root 1073852416 Mar 28 09:54 pages-1.img
-rw-------.  1 root root         94 Mar 28 09:54 runc-criu-log-gTJfQY.log
-rw-r--r--.  1 root root         56 Mar 28 09:54 stats-dump
# ls -la /tmp/second-dump/
total 100
drwxr-xr-x.  2 root root  4096 Mar 28 09:54 .
drwxrwxrwt. 11 root root 36864 Mar 28 09:56 ..
-rw-r--r--.  1 root root  1883 Mar 28 09:54 core-10585.img
-rw-r--r--.  1 root root   262 Mar 28 09:54 files.img
-rw-r--r--.  1 root root    18 Mar 28 09:54 fs-10585.img
-rw-r--r--.  1 root root    34 Mar 28 09:54 ids-10585.img
-rw-r--r--.  1 root root   911 Mar 28 09:54 mm-10585.img
-rw-r--r--.  1 root root   276 Mar 28 09:54 pagemap-10585.img
-rw-r--r--.  1 root root 24576 Mar 28 09:54 pages-1.img
lrwxrwxrwx.  1 root root    13 Mar 28 09:54 parent -> ../first-dump
-rw-------.  1 root root   248 Mar 28 09:54 runc-criu-log-gTJfQY.log
-rw-r--r--.  1 root root    12 Mar 28 09:54 seccomp.img
```
Which version of CRIU are you using and on which architecture are you running. Not all architectures (aarch64 for example) support memory tracking.

**Comment by 123toorc** [comment]
Thank you, I will close the issue, the problem is the benchmark I'm using, it will rewrite the memory, which cause the problem.
