### ISSUE TITLE
The shmid of the same file mapping VMA entry is different in parent&child's mm.img

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1006]
This is kind of an implementation design question.

Say I have a simple program, which opened a file, mmap 8K region, and then do fork(). So we have a parent process and child process almost at same states here.

Then I dump it. I found an interesting result, that the ```shmid``` of the same VMA entry in mm-pid.img is different in parent&child processes.

I found there are 2 almost same entries in files.img:
```
        {
            "type": "REG",
            "id": 4,
            "reg": {
                "id": 4,
                "flags": "",
                "pos": 0,
                "fown": {
                    "uid": 0,
                    "euid": 0,
                    "signum": 0,
                    "pid_type": 0,
                    "pid": 0
                },
                "name": "/root/criu_test/maps00_file-07",
                "size": 8192,
                "mode": 33152
            }
        },
        {
            "type": "REG",
            "id": 22,
            "reg": {
                "id": 22,
                "flags": "O_RDWR | O_LARGEFILE",
                "pos": 8192,
                "fown": {
                    "uid": 0,
                    "euid": 0,
                    "signum": 0,
                    "pid_type": 0,
                    "pid": 0
                },
                "name": "/root/criu_test/maps00_file-07",
                "size": 8192,
                "mode": 33152
            }
        },
```

I looked into the code, the first entry is actually generated when dumping mmap, in file ```criu/proc_parse.c``` function ```parse_smaps```
The second entry is generated when dumping open files, in file ```criu/files-reg.c``` function ```dump_one_reg_file```.

And CRIU also maintained a ```fd_id_cache``` in ```criu/file-ids.c```, which is basically a hash table with conflict linked list. And for those two entries, I mentioned above, have exactly the same ```stat.st_dev, stat.st_ino and mnt_id```, the only difference is the internal id(4 vs 22)

The interesting part is in the mm-pid.img.

In parent's mm-pid.img, here is what the VMA entry looks like:
```
                {
                    "start": "0x7fb3477dc000",
                    "end": "0x7fb3477de000",
                    "pgoff": 0,
                    "shmid": 4,--------------------> point to first entry in files.
                    "prot": "PROT_READ | PROT_WRITE | PROT_EXEC",
                    "flags": "MAP_SHARED",
                    "status": "VMA_AREA_REGULAR | VMA_FILE_SHARED",
                    "fd": -1,
                    "fdflags": "0x2"
                },
```

But in child's mm-pid.img, the **shmid** is different in the same mapping:
```
                {
                    "start": "0x7fb3477dc000",
                    "end": "0x7fb3477de000",
                    "pgoff": 0,
                    "shmid": 22,   ---------------->second entry in files
                    "prot": "PROT_READ | PROT_WRITE | PROT_EXEC",
                    "flags": "MAP_SHARED",
                    "status": "VMA_AREA_REGULAR | VMA_FILE_SHARED",
                    "fd": -1,
                    "fdflags": "0x2"
                },
```

The reason for this is that when dumping VMAs in the second process, the ```fd_id_cache``` is there, so it will just look for the file entry in the cache and hit the second one, since their ```stat.st_dev, stat.st_ino and mnt_id``` are the same as I mentioned before.

I'm not sure it is correct behavior, or just by design, it happened worked well for a regular file mapping.

It causes a problem for me because, in my application, I have a mapping over a special character device. I did a little hack and wrote an external file plugin to make CRIU support dumping&restore it. You will still see two same entries in files.img like above, the only difference is my second entry will be marked **EXT** instead of **REG**.
And when it forked another process, restore will be failed due to CRIU can't restore mapping for child process. Since the VMA entry is pointing to the second entry in files which marked as **EXT** while ```collect_special_file``` only looking for **REG** file.

I can make another hack here, to say ```collect_special_file``` also looking for EXT file. But trace back to the root cause, shall we not to let the VMA entry in child process pointing to the second entry in files.img? I think CRIU should have a consistent result for both parent&child processes have same mapping.

**Comment by avagin** [comment]
What criu version do you use? 
Could you attach your test program?

I have tried to reproduce this issue with this test:
```
#include "zdtmtst.h"
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

const char *test_doc    = "Create a lot of file vma-s";
const char *test_author = "Andrei Vagin <avagin@openvz.org>";

char *filename;
TEST_OPTION(filename, string, "file name", 1);

int main(int argc, char ** argv)
{
        void *addr;
        int fd;
        int ps = sysconf(_SC_PAGESIZE);
        pid_t pid;

        test_init(argc, argv);

        fd = open(filename, O_RDWR | O_CREAT, 0666);
        if (fd < 0)
                return 1;

        ftruncate(fd, ps);

        addr = mmap(NULL, ps,
                        PROT_READ | PROT_WRITE,
                        MAP_SHARED | MAP_FILE, fd, 0);
        if (addr == MAP_FAILED)
                return 1;

        close(fd);
        pid = fork();
        if (pid == 0) {
                while (1)
                        sleep(1);
                return 1;
        }

        test_daemon();

        test_waitsig();


        pass();

        return 0;
}
```

But in my case, shmid is the same for both processes.

```
$ ./crit/crit show ./crit/crit show test/dump/zdtm/static/maps06/44/1/mm-44.img
...
                {
                    "start": "0x7fba72478000", 
                    "end": "0x7fba72479000", 
                    "pgoff": 0, 
                    "shmid": 3, 
                    "prot": "PROT_READ | PROT_WRITE", 
                    "flags": "MAP_SHARED", 
                    "status": "VMA_AREA_REGULAR | VMA_FILE_SHARED", 
                    "fd": -1, 
                    "fdflags": "0x2"
                },
...
$ ./crit/crit show test/dump/zdtm/static/maps06/44/1/mm-45.img
                {
                    "start": "0x7fba72478000", 
                    "end": "0x7fba72479000", 
                    "pgoff": 0, 
                    "shmid": 3, 
                    "prot": "PROT_READ | PROT_WRITE", 
                    "flags": "MAP_SHARED", 
                    "status": "VMA_AREA_REGULAR | VMA_FILE_SHARED", 
                    "fd": -1, 
                    "fdflags": "0x2"
                }, 
$ ./crit/crit show test/dump/zdtm/static/maps06/44/1/files.img
        {
            "type": "REG", 
            "id": 3, 
            "reg": {
                "id": 3, 
                "flags": "", 
                "pos": 0, 
                "fown": {
                    "uid": 0, 
                    "euid": 0, 
                    "signum": 0, 
                    "pid_type": 0, 
                    "pid": 0
                }, 
                "name": "/root/git/main/criu/test/zdtm/static/maps06.test", 
                "size": 4096, 
                "mode": 33188
            }
        }, 
```

**Comment by geminijun** [comment]
Thanks for your response!
I'm using 3.13 and the reason you didn't see this issue is because you closed the file before dumping the process.

I just tried your program and just moved ```close(fd)``` before return. Then you will see the issue.

In my application, we have some requirements to keep the file open. And I think it's a valid usage, isn't it?

**Comment by avagin** [comment]
```
diff --git a/criu/cr-dump.c b/criu/cr-dump.c
index 6aa114c2d..a42d69aca 100644
--- a/criu/cr-dump.c
+++ b/criu/cr-dump.c
@@ -1241,7 +1241,7 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
        if (ret < 0)
                goto err;
 
-       ret = collect_mappings(pid, &vmas, dump_filemap);
+       ret = collect_mappings(pid, &vmas, NULL);
        if (ret) {
                pr_err("Collect mappings (pid: %d) failed with %d\n", pid, ret);
                goto err;
@@ -1281,6 +1281,26 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
                goto err;
        }
 
+       if (dfds) {
+               ret = dump_task_files_seized(parasite_ctl, item, dfds);
+               if (ret) {
+                       pr_err("Dump files (pid: %d) failed with %d\n", pid, ret);
+                       goto err_cure;
+               }
+               ret = flush_eventpoll_dinfo_queue();
+               if (ret) {
+                       pr_err("Dump eventpoll (pid: %d) failed with %d\n", pid, ret);
+                       goto err_cure;
+               }
+       }
+
+       vm_area_list_init(&vmas);
+       ret = collect_mappings(pid, &vmas, dump_filemap);
+       if (ret) {
+               pr_err("Collect mappings (pid: %d) failed with %d\n", pid, ret);
+               goto err;
+       }
+
        if (fault_injected(FI_DUMP_EARLY)) {
                pr_info("fault: CRIU sudden detach\n");
                kill(getpid(), SIGKILL);
@@ -1341,19 +1361,6 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
                goto err_cure;
        }
 
-       if (dfds) {
-               ret = dump_task_files_seized(parasite_ctl, item, dfds);
-               if (ret) {
-                       pr_err("Dump files (pid: %d) failed with %d\n", pid, ret);
-                       goto err_cure;
-               }
-               ret = flush_eventpoll_dinfo_queue();
-               if (ret) {
-                       pr_err("Dump eventpoll (pid: %d) failed with %d\n", pid, ret);
-                       goto err_cure;
-               }
-       }
-
        mdc.pre_dump = false;
        mdc.lazy = opts.lazy_pages;
        mdc.stat = &pps_buf;
```

**Comment by avagin** [comment]
diff --git a/criu/cr-dump.c b/criu/cr-dump.c
index 6aa114c2d..a42d69aca 100644
--- a/criu/cr-dump.c
+++ b/criu/cr-dump.c
@@ -1241,7 +1241,7 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
        if (ret < 0)
                goto err;
 
-       ret = collect_mappings(pid, &vmas, dump_filemap);
+       ret = collect_mappings(pid, &vmas, NULL);
        if (ret) {
                pr_err("Collect mappings (pid: %d) failed with %d\n", pid, ret);
                goto err;
@@ -1281,6 +1281,26 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
                goto err;
        }
 
+       if (dfds) {
+               ret = dump_task_files_seized(parasite_ctl, item, dfds);
+               if (ret) {
+                       pr_err("Dump files (pid: %d) failed with %d\n", pid, ret);
+                       goto err_cure;
+               }
+               ret = flush_eventpoll_dinfo_queue();
+               if (ret) {
+                       pr_err("Dump eventpoll (pid: %d) failed with %d\n", pid, ret);
+                       goto err_cure;
+               }
+       }
+
+       vm_area_list_init(&vmas);
+       ret = collect_mappings(pid, &vmas, dump_filemap);
+       if (ret) {
+               pr_err("Collect mappings (pid: %d) failed with %d\n", pid, ret);
+               goto err;
+       }
+
        if (fault_injected(FI_DUMP_EARLY)) {
                pr_info("fault: CRIU sudden detach\n");
                kill(getpid(), SIGKILL);
@@ -1341,19 +1361,6 @@ static int dump_one_task(struct pstree_item *item, InventoryEntry *parent_ie)
                goto err_cure;
        }
 
-       if (dfds) {
-               ret = dump_task_files_seized(parasite_ctl, item, dfds);
-               if (ret) {
-                       pr_err("Dump files (pid: %d) failed with %d\n", pid, ret);
-                       goto err_cure;
-               }
-               ret = flush_eventpoll_dinfo_queue();
-               if (ret) {
-                       pr_err("Dump eventpoll (pid: %d) failed with %d\n", pid, ret);
-                       goto err_cure;
-               }
-       }
-
        mdc.pre_dump = false;
        mdc.lazy = opts.lazy_pages;
        mdc.stat = &pps_buf;
```

**Comment by jungan** [comment]
Hi Andrei,

After applied your path, I got the following error:
```
(00.034087) Dumping shared memory 3469639
(00.034105) Error (criu/shmem.c:762): Can't open 19653/map_files/7f8bce79f000-7f8bce7af000 on procfs: No such file or directory
(00.034197) Unlock network
(00.034206) Unfreezing tasks into 1
(00.034208)     Unseizing 19652 into 1
(00.034211)     Unseizing 19653 into 1
(00.034215) Error (criu/cr-dump.c:1750): Dumping FAILED.
```

What I guess is that this mapping is the parasite code blob.
```
(00.016131) Set up parasite blob using memfd
(00.016136) Putting parasite blob into 0x7f40fab4d000->0x7f8bce79f000
```

```
(00.017421) 0x7f8bce79f000-0x7f8bce7af000 (64K) prot 0x7 flags 0x21 fdflags 02 st 0x101 off 0 reg as  shmid: 0x34f0ed
```

**Comment by geminijun** [comment]
Hi Andrei,

After applied your path, I got the following error:
```
(00.034087) Dumping shared memory 3469639
(00.034105) Error (criu/shmem.c:762): Can't open 19653/map_files/7f8bce79f000-7f8bce7af000 on procfs: No such file or directory
(00.034197) Unlock network
(00.034206) Unfreezing tasks into 1
(00.034208)     Unseizing 19652 into 1
(00.034211)     Unseizing 19653 into 1
(00.034215) Error (criu/cr-dump.c:1750): Dumping FAILED.
```

What I guess is that this mapping is the parasite code blob.
```
(00.016131) Set up parasite blob using memfd
(00.016136) Putting parasite blob into 0x7f40fab4d000->0x7f8bce79f000
```

```
(00.017421) 0x7f8bce79f000-0x7f8bce7af000 (64K) prot 0x7 flags 0x21 fdflags 02 st 0x101 off 0 reg as  shmid: 0x34f0ed
```
