### ISSUE TITLE
[Docker] On restore, the container starts from the beginning

### ISSUE THREAD

**Issue by anagainaru** [checkpoint-restore/criu#1024]
I am trying to run the simple docker example from here: https://criu.org/Docker
and when I restore, the container started counting from 0 and not from the expected, checkpointed state.

```
> uname -a
Linux PadmaLab 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> criu --version
Version: 3.13
> criu check
Can't check shutdown state of inet socket
Looks good.
> docker --version
Docker version 19.03.6, build 369ce74a3c
```
I also tried the travis test here: https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/travis/docker-test.sh
and I have the same problem.

When I try the `--checkpoint-dir` option:
```
> docker start --checkpoint-dir=/tmp --checkpoint=checkpoint2 looper-clone
Error response from daemon: custom checkpointdir is not supported
```

I couldn't find another open issue with my problem. Not sure how to proceed.
Thanks

**Comment by adrianreber** [comment]
Never used docker's checkpoint/restore support myself, but I worked on Podman's checkpoint/restore support: https://criu.org/Podman

Not sure if this would help you, but maybe it does.

**Comment by anagainaru** [comment]
Thanks I'll take a look. Not sure I can get rid of docker since so many of our applications are already using it, but it's at least worth seeing if the simple example would work on my system configuration.

**Comment by anagainaru** [comment]
The simple example works with Podman. 
If all docker images are compatible with the format used by Podman, I should be able to run my applications. Thank you for the help.
