### ISSUE TITLE
How does criu dump MPI master/slave process?

### ISSUE THREAD

**Issue by ghostplant** [checkpoint-restore/criu#1028]
Is there any example to explain the command line for a program executed with `mpiexec -n 2 ./program`?

**Comment by adrianreber** [comment]
No. Maybe 8 years ago I tried to get CRIU support into Open MPI to allow Open MPI to checkpoint its child processes. So controlled and driven by `mpiexec`/`mpirun`. A bit different than what you ask. It worked and checkpointing support was merged upstream Open MPI. Restore support unfortunately never. All the code has been removed from Open MPI in its current version.

Have you tried checkpointing the command you specified. If it is running on a single host it could work. Any errors?

**Comment by rst0git** [comment]
There are some example scripts published in
https://github.com/magnusbrattlof/Distributed-Checkpointing-with-Docker-Containers-in-High-Performance-Computing

**Comment by ghostplant** [comment]
@rst0git Is it for OpenMPI?

**Comment by rst0git** [comment]
As far as I know they have used MPICH: [Evaluating Distributed MPI Checkpoint and Restore Using Docker Containers and CRIU](https://github.com/checkpoint-restore/criu/files/4492335/2019_Evaluating_Distributed_Mpi_Checkpoint_And_Restore_Using_Docker_Containers_And_Criu.pdf)

**Comment by adrianreber** [comment]
@ghostplant If you are running it in a container, it should not matter which MPI implementation.

**Comment by adrianreber** [comment]
I am closing this as @rst0git provided some examples. Let us know if you have been successful or not.
