### ISSUE TITLE
Fedora crash report

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1029]
Just a got a Fedora crash overview report https://retrace.fedoraproject.org/faf/reports/bthash/ec3bdafb2026d6e26fc33fbcac334c1ceb498580/

It seems CRIU is sometimes crashing in RPC mode in criu/cr-service.c (line 271): `setup_opts_from_req()`

Line 270 to 272 in CRIU 3.13 seems to be:
```
                char *tmp_output = opts.output;
                char *tmp_work = opts.work_dir;
                char *tmp_imgs = opts.imgs_dir;
```
Not sure how accurate the crash reports are. Maybe it was on another line. Probably my fault as this code is from my configuration file work.

Any ideas what might be wrong here: https://github.com/checkpoint-restore/criu/blob/v3.13/criu/cr-service.c#L271

**Comment by avagin** [comment]
On Thu, Apr 16, 2020 at 9:27 AM Adrian Reber <notifications@github.com> wrote:
>
> Just a got a Fedora crash overview report https://retrace.fedoraproject.org/faf/reports/bthash/ec3bdafb2026d6e26fc33fbcac334c1ceb498580/
>
> It seems CRIU is sometimes crashing in RPC mode:

Frame # Function Binary Source or offset Line
1 setup_opts_from_req /usr/sbin/criu criu/cr-service.c 271
2 cr_service_work /usr/sbin/criu 0x4bb12
Build id: eb9cfd36581ad8bb70f49e1efa9f3cb5ca5e4e41 -
3 main /usr/sbin/criu criu/crtools.c 111

I tried to look at this report and I found that line numbers are
strange, are not they?

**Comment by adrianreber** [comment]
Yes, the line number must be somehow not accurate.

**Comment by adrianreber** [comment]
I am closing this again. I would like to get it fixed, but the line numbers just make no sense.
