### ISSUE TITLE
Second checkpoint using cgroup2 freezer fails

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1034]
I am mainly looking for some additional input or ideas why the following is happening.

I am currently trying to switch crun in combination with Podman to use the freezer to stop processes in the container: `criu_set_freeze_cgroup()`.

I am able checkpoint and restore a Java (Wildfly) based container multiple times without a problem without using the freezer cgroup.

If I use the freezer I can checkpoint the container only once. The second checkpoint of a previously restored container fails with:
```
(00.000504) Detected cgroup V2 freezer
(00.000507) freezing processes: 100000 attempts with 100 ms steps
(00.000562) cgroup.freeze=0
(00.000577) cgroup.freeze=1
(00.100902) cgroup.freeze=1
(00.101099) freezing processes: 1 attempts done
(00.101265) SEIZE 15459: success (-> shell script PID 1 in the container)
(00.102551) Seized task 15459, state 1
(00.102590) seccomp: Collected tid_real 15459 mode 0x2
(00.102697) Collected (0 attempts, 0 in_progress)
(00.102827) Seized task 15481, state 0 (-> JVM started by the above shell script)
(00.103098) Error (compel/src/lib/infect.c:235): Unseizable non-zombie 15481 found, state S, err -1/10
(00.103210) Seized task 15481, state 0
(00.103334) Error (compel/src/lib/infect.c:235): Unseizable non-zombie 15481 found, state S, err -1/10
(00.103397) Collected (-1 attempts, 1 in_progress)
(00.103433) Unlock network
(00.103444) Unfreezing tasks into 1
(00.103451) 	Unseizing 15459 into 1
(00.103534) Error (criu/cr-dump.c:1776): Dumping FAILED.
```
Any ideas why using the cgroup2 freezer fails with a process which has been restored in contrast of the process has been started by the container? Any ideas what the compel error means?

**Comment by adrianreber** [comment]
@avagin who could help me with this? Who knows compel the best?

**Comment by avagin** [comment]
I am sorry for the late response. Could you explain how to reproduce this?

**Comment by avagin** [comment]
I was able to reproduce this issue. First of all, I want to mention that zdtm.py --freezecg doesn't work with the cgroup v2. This means that we don't test this in travis, Jenkins, etc. If something isn't tested, it doesn't work or will be broken soon. This case is another proof of the previous sentence. Please, please, please, write tests for all features.

**Comment by avagin** [comment]
I think the root cause of this issue is that processes are restored in a wrong cgroup, so the second dump doesn't freeze dumped processes.
You can try to read /proc/PID/cgroup for a container init process before dump and after restore.

**Comment by avagin** [comment]
@adrianreber here is an early draft version of the cgroup v2 support:
https://github.com/avagin/criu/tree/cgroup-v2

I did it just to understand how much work there and now we can see that there is not so much work, but I don't have time to implement this properly right now.

Let me know if you have time and a wish to work on this.

**Comment by adrianreber** [comment]
@avagin Thanks a lot. I will take your patches and continue to work on it.

**Comment by adrianreber** [comment]
This is fixed
