### ISSUE TITLE
tty: Unable to open dev/pts/ptmx with specified index 3

### ISSUE THREAD

**Issue by dirkpetersen** [checkpoint-restore/criu#1040]
I saw #102 and I am having the same issue. On a shared system with other users logged on I am getting this on `criu restore`

```
 69481: Error (criu/tty.c:632): tty: Unable to open dev/pts/ptmx with specified index 3
 69481: Error (criu/tty.c:1033): tty: Can't open master pty 0xc (index 3)
 69481: Error (criu/files.c:1196): Unable to open fd=0 id=0xc

```
Has there been a different workaround since 2016 other than using namespaces ?  I am not sure if they are supported in my environment.

**Comment by avagin** [comment]
You can use crit to change pty indexes in image files. Will this work for you?

**Comment by aqjune** [comment]
Hi, I am seeing this error as well.
```
$ sudo criu dump -t 707203 --shell-job
$ sudo criu restore --shell-job
707203: Error (criu/tty.c:625): tty: Unable to open dev/ptmx with specified index 0
707203: Error (criu/tty.c:1074): tty: Can't open master pty 0xc (index 0)
707203: Error (criu/files.c:1200): Unable to open fd=3 id=0xc
Error (criu/cr-restore.c:2447): Restoring FAILED.
Error (criu/cr-restore.c:1480): 707203 killed by signal 9: Killed
```
 The dumped process was a Python-like interpreter that interacts via bash. It is Ubuntu 22.04 and an ARM machine. Any help will be appreciated.

**Comment by Speclkle** [comment]
> Hi, I am seeing this error as well.
> 
> ```
> $ sudo criu dump -t 707203 --shell-job
> $ sudo criu restore --shell-job
> 707203: Error (criu/tty.c:625): tty: Unable to open dev/ptmx with specified index 0
> 707203: Error (criu/tty.c:1074): tty: Can't open master pty 0xc (index 0)
> 707203: Error (criu/files.c:1200): Unable to open fd=3 id=0xc
> Error (criu/cr-restore.c:2447): Restoring FAILED.
> Error (criu/cr-restore.c:1480): 707203 killed by signal 9: Killed
> ```
> 
> The dumped process was a Python-like interpreter that interacts via bash. It is Ubuntu 22.04 and an ARM machine. Any help will be appreciated.

Well, do you fix this error afterwards? How can i fix it?by crit?anyone can help?
