### ISSUE TITLE
Restored app does not resume execution

### ISSUE THREAD

**Issue by ashu-mehra** [checkpoint-restore/criu#1042]
I am using criu to checkpoint and restore application on the same system (not a live migration use-case). criu is used directly on bare-metal system to checkpoint and restore a process which not running in container.
However, the application fails to come up after restore is completed. The logs indicate dumping and restoring has completed successfully but still the application fails to resume.
Even the [simple loop](https://criu.org/Simple_loop) bash script fails to resume. If I use a java application, then JVM crashes immediately after restore.

```
# criu -V
Version: 3.12

# uname -s -r
Linux 3.10.0-693.el7.x86_64

# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)
```

Attached are logs: 
[dump.log](https://github.com/checkpoint-restore/criu/files/4526299/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/4526300/restore.log)

When I rollback to version 3.10, then criu is able to restore the application properly. Using binary search I narrowed down the last passing commit to dd4c0c6b22d3e3ede23cff9ac43786f5f00948ec. From next commit b99be2741a94174f4823e5d84cd24e750ba4f5dc criu fails to even dump the application. From 9166f90e5813b06d96296416215de5f3beeb67b7 onwards it is able to dump but fails to restore as I mentioned before.

**Comment by adrianreber** [comment]
Both logs are saying you are using CRIU 3.13 from git. To run on RHEL you need one additional CRIU patch: https://git.centos.org/rpms/criu/blob/c7/f/SOURCES/aio-fix.patch

Or use CRIU from RHEL. It is packaged and ready to use.

Not sure if this solves your problem, but at least that is a known problem.

**Comment by ashu-mehra** [comment]
@adrianreber Looks like I uploaded logs which were generated when I was playing around with previous versions to narrow down the issue.
I started using CRIU that comes packaged with RHEL, but it suffers from the same problem that I explained earlier, which prompted me to compile previous version from the sources to check if that resolves the issue.
Anyway, here are the logs for CRIU from RHEL:

[dump.log](https://github.com/checkpoint-restore/criu/files/4529235/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/4529237/restore.log)

These logs are for the following sample C application:
```
#include <stdio.h>

int main(void) {
	int i = 0;
	for (i = 0; i < 1000; i++) {
		printf("i: %d\n", i);
		sleep(5);
	}
	return 0;
}
```
I have seen same behaviour with the sample bash script as well.

Sorry for the confusion regarding the logs.

**Comment by adrianreber** [comment]
Just tried it on an up to date RHEL 7 system and it works:
```
# /usr/sbin/criu dump -t `pidof test` -j -D /tmp
#️  /usr/sbin/criu restore -D /tmp -j
i: 4
i: 5
i: 6
```
For completeness: I have SELinux enabled, but CRIU in RHEL 7 is not linked against SELinux.

I have a simple VM with 4 CPUs. On which system are you using it? Something unusual?

**Comment by ashu-mehra** [comment]
I have another RHEL 7 system where criu works fine. Only on this particular system I am getting this problem.

> Something unusual?

I am not sure what to look for. I would gladly provide details if you can be a bit more specific.
With respect to CPUs:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-3,28-55,84-111
Off-line CPU(s) list:  4-27,56-83
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req
```

As I mentioned earlier, if I rollback to v3.10 then it works fine. So probably some change has gone in later which is not handling this system's characteristics properly.

**Comment by adrianreber** [comment]
Lots of CPUs. Can you try with RHEL 8 or something else. Not sure if it makes sense to dive too deep into RHEL 7 problems.

Is CRIU's behaviour different if all CPUs are online?

**Comment by adrianreber** [comment]
Just tried to enable and disable CPUs and the restore always works.

Any messages in the log files or dmesg when the process is not correctly restored?

**Comment by ashu-mehra** [comment]
`/var/log/messages` has following entries:
```
Apr 24 13:46:06 animal kernel: cgroup: new mount options do not match the existing superblock, will be ignored
Apr 24 13:46:06 animal kernel: test[115538] bad frame in rt_sigreturn frame:00007fc14d6fa000 ip:7fc14d1d8830 sp:7ffc54d08e78 orax:ffffffffffffffff in libc-2.17.so[7fc14d113000+1c3000]
Apr 24 13:46:17 animal kernel: cgroup: new mount options do not match the existing superblock, will be ignored
Apr 24 13:46:17 animal kernel: test[115538] bad frame in rt_sigreturn frame:0000000000022080 ip:7fc14d1d8830 sp:7ffc54d08e78 orax:ffffffffffffffff in libc-2.17.so[7fc14d113000+1c3000]
```

This system is used for performance work and won't be possible to move it to RHEL 8 anytime in near future.

**Comment by ashu-mehra** [comment]
I think I have found the issue. Looks like the code for restoring extended processor state in `restore_fpu` is not calculating `xstate_size` properly if one or more features are not supported. 
In this particular system `XFEATURE_BNDREGS` is not present.

I instrumented the code to display offset and size for each feature during dump and restore operations which gives me following result:

```
# criu dump -t 146275 -j -v3 -o dump.log
XFEATURE_YMM offset: 576, size: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, size: 64
XFEATURE_OPMASK offset: 1088, size: 64
XFEATURE_ZMM_Hi256 offset: 1152, size: 512
XFEATURE_Hi16_ZMM offset: 1664, size: 1024
XFEATURE_PKRU offset: 2688, size: 8
XFEATURE_YMM offset: 576, xsize: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, xsize: 64
XFEATURE_OPMASK offset: 1088, xsize: 64
XFEATURE_ZMM_Hi256 offset: 1152, xsize: 512
XFEATURE_Hi16_ZMM offset: 1664, xsize: 1024
XFEATURE_PKRU offset: 2688, xsize: 8
xstate_size: 2504

# criu restore -j -v3 -o restore.log
XFEATURE_YMM offset: 576, xsize: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, xsize: 64
XFEATURE_OPMASK offset: 1088, xsize: 64
XFEATURE_ZMM_Hi256 offset: 1152, xsize: 512
XFEATURE_Hi16_ZMM offset: 1664, xsize: 1024
XFEATURE_PKRU offset: 2688, xsize: 8
xstate_size: 2504
```
Output also shows `XFEATURE_BNDREGS` is not present.
During restore `xstate_size` was calculated as 2504, but it should have been `2696 (=2688+8)`.
With the incorrect calculation the magic value `FP_XSTATE_MAGIC2`, suppose to be written at the end of xsave area, is written somewhere inside the xsave area, which likely causes problems later when the application resumes.

If I change the calculation of `xstate_size` on line criu/arch/x86/crtools.c:455 as:
```
-                       xstate_size += xsize;                                           \
+                       xstate_size = off + xsize;                                      \
```
then the `xstate_size` is correctly computed to `2696` as the output indicates:
```
# criu dump -t 145219 -j -v3 -o dump.log
XFEATURE_YMM offset: 576, size: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, size: 64
XFEATURE_OPMASK offset: 1088, size: 64
XFEATURE_ZMM_Hi256 offset: 1152, size: 512
XFEATURE_Hi16_ZMM offset: 1664, size: 1024
XFEATURE_PKRU offset: 2688, size: 8
XFEATURE_YMM offset: 576, xsize: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, xsize: 64
XFEATURE_OPMASK offset: 1088, xsize: 64
XFEATURE_ZMM_Hi256 offset: 1152, xsize: 512
XFEATURE_Hi16_ZMM offset: 1664, xsize: 1024
XFEATURE_PKRU offset: 2688, xsize: 8
xstate_size: 2696

# criu restore -j -v3 -o restore.log
XFEATURE_YMM offset: 576, xsize: 256
XFEATURE_BNDREGS not present
XFEATURE_BNDCSR offset: 1024, xsize: 64
XFEATURE_OPMASK offset: 1088, xsize: 64
XFEATURE_ZMM_Hi256 offset: 1152, xsize: 512
XFEATURE_Hi16_ZMM offset: 1664, xsize: 1024
XFEATURE_PKRU offset: 2688, xsize: 8
xstate_size: 2696
```

and the application also resumes properly.

Here is the complete patch with debug statements for showing offsets and size:
```
diff --git a/criu/arch/x86/crtools.c b/criu/arch/x86/crtools.c
index 9c8beee..0b7a462 100644
--- a/criu/arch/x86/crtools.c
+++ b/criu/arch/x86/crtools.c
@@ -30,12 +30,15 @@ int save_task_regs(void *x, user_regs_struct_t *regs, user_fpregs_struct_t *fpre
                        void *from = &area[off];                                        \
                        size_t size = pb_repeated_size(xsave, member);                  \
                        size_t xsize = (size_t)compel_fpu_feature_size(feature);        \
+                       fprintf(stdout, "%s offset: %u, size: %zu\n", # feature, off, xsize);           \
                        if (xsize != size) {                                            \
                                pr_err("%s reported %zu bytes (expecting %zu)\n",       \
                                        # feature, xsize, size);                        \
                                return -1;                                              \
                        }                                                               \
                        memcpy(xsave->member, from, size);                              \
+               } else {                                                                \
+                       fprintf(stdout, "%s not present\n", # feature);                 \
                }                                                                       \
        } while (0)
 
@@ -437,6 +440,7 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
                        void *from = xsave->member;                                     \
                        size_t size = pb_repeated_size(xsave, member);                  \
                        size_t xsize = (size_t)compel_fpu_feature_size(feature);        \
+                       fprintf(stdout, "%s offset: %u, xsize: %zu\n", # feature, off, xsize);          \
                        if (xsize != size) {                                            \
                                if (size) {                                             \
                                        pr_err("%s reported %zu bytes (expecting %zu)\n",\
@@ -448,8 +452,10 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
                                }                                                       \
                        }                                                               \
                        xstate_bv |= (1UL << feature);                                  \
-                       xstate_size += xsize;                                           \
+                       xstate_size = off + xsize;                                      \
                        memcpy(to, from, size);                                         \
+               } else {                                                                \
+                       fprintf(stdout, "%s not present\n", # feature);                 \
                }                                                                       \
        } while (0)
 
@@ -504,6 +510,7 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
                /*
                 * This should be at the end of xsave frame.
                 */
+               fprintf(stdout, "xstate_size: %zu\n", xstate_size);
                magic2 = (void *)x + xstate_size;
                *(u32 *)magic2 = FP_XSTATE_MAGIC2;
        }
```

If the fix looks reasonable, I would be happy to open a PR.

**Comment by mihalicyn** [comment]
@ashu-mehra great job!
Of course, It will be cool if you make PR with a good description of the problem (you have already provided a lot of details). Looks like your CPU `Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz` is very rare. What do you think, is it possible to emulate this situation with QEMU `-cpu` parameter. It will be great If we manage to reproduce this problem on the QEMU VM.

Thank you.
Regards, Alex

**Comment by Snorch** [comment]
>If the fix looks reasonable, I would be happy to open a PR.
Looks reasonable.

Maybe even:
```
xstate_size = max(xstate_size, off + xsize);
```
To be safe if features will end up reordered...

**Comment by cyrillos** [comment]
The features should not be reordered I think. From glance we should account `off` as well. I'll take a closer look once time permit.

**Comment by ashu-mehra** [comment]
> What do you think, is it possible to emulate this situation with QEMU -cpu parameter.

I have not used QEMU for emulation, won't be able to comment on this.

**Comment by cyrillos** [comment]
The problem is a bit more complex: the userspace in linux operates that named uncompacted format, where each entry sits at known offset with some entry size. Thus the summary size should accumulate entries which are not present in cpu features.

If I get spare time on this week I'll try to provide a patch, but will need some help for testing.

**Comment by cyrillos** [comment]
```
diff --git a/criu/arch/x86/crtools.c b/criu/arch/x86/crtools.c
index 9c8beeedddf0..bc80225358ff 100644
--- a/criu/arch/x86/crtools.c
+++ b/criu/arch/x86/crtools.c
@@ -437,6 +437,7 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
 			void *from = xsave->member;					\
 			size_t size = pb_repeated_size(xsave, member);			\
 			size_t xsize = (size_t)compel_fpu_feature_size(feature);	\
+			size_t xstate_size_next = off + xsize;				\
 			if (xsize != size) {						\
 				if (size) {						\
 					pr_err("%s reported %zu bytes (expecting %zu)\n",\
@@ -448,7 +449,8 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
 				}							\
 			}								\
 			xstate_bv |= (1UL << feature);					\
-			xstate_size += xsize;						\
+			BUG_ON(xstate_size > xstate_size_next);				\
+			xstate_size = xstate_size_next;					\
 			memcpy(to, from, size);						\
 		}									\
 	} while (0)
@@ -485,6 +487,11 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
 			UserX86XsaveEntry *xsave = core->thread_info->fpregs->xsave;
 			uint8_t *extended_state_area = (void *)x;
 
+			/*
+			 * Note the order does matter here and bound
+			 * to the increasing offsets of XFEATURE_x
+			 * inside memory layout (xstate_size calculation).
+			 */
 			assign_xsave(XFEATURE_YMM,	xsave, ymmh_space,	extended_state_area);
 			assign_xsave(XFEATURE_BNDREGS,	xsave, bndreg_state,	extended_state_area);
 			assign_xsave(XFEATURE_BNDCSR,	xsave, bndcsr_state,	extended_state_area);

```

**Comment by cyrillos** [comment]
@ashu-mehra Could you please give it a shot?

**Comment by ashu-mehra** [comment]
@cyrillos I applied your changes and the test program is able to resume after restore on that particular system. Thanks for fixing the issue.

**Comment by cyrillos** [comment]
@ashu-mehra thanks for testing! i'll prepare the patch and send it.

**Comment by avagin** [comment]
The patch has been merged.
