### ISSUE TITLE
open file handles on nfs or shared storage 

### ISSUE THREAD

**Issue by dirkpetersen** [checkpoint-restore/criu#1043]
I read in #60 that nfs mount points do not migrate.  I suppose this is true for any open file handles in distributed storage ?

This code works fine, I was able to checkpoint and restart it more than 1600 times with no errors (Ubuntu 18.04.4 and criu 3.13). The output file looper.txt worked on NFS and other distributed storage systems 

```python                                                                                          
#! /usr/bin/env python3  
import os, time, socket
cnt=0
while cnt<=10000:
    pid = os.getpid()
    ppid = os.getppid()
    cnt+=1
    line="%s  node:%s  pid:%s  parent-pid:%s" % (str(cnt),socket.gethostname(),pid,ppid)
    fh=open('looper.txt', 'a')
    fh.write(line+'\n')
    fh.close()
    print(line)
    time.sleep(1)
```

however this one did not, and I was not getting any error messages either, the file just stayed at 0 byte size. 

```python                                                                                          
#! /usr/bin/env python3  
import os, time, socket
cnt=0
fh=open('looper.txt', 'a')
while cnt<=10000:
    pid = os.getpid()
    ppid = os.getppid()
    cnt+=1
    line="%s  node:%s  pid:%s  parent-pid:%s" % (str(cnt),socket.gethostname(),pid,ppid)
    fh.write(line+'\n')
    print(line)
    time.sleep(1)
fh.close()
```

are there any workarounds for this ?

**Comment by Snorch** [comment]
Yet open files on nfs mount migration is only supported in Virtuozzo containers.

One can port this functionality for other containers as @mihalicyn mentioned in https://github.com/checkpoint-restore/criu/issues/60 but it is rather a hard work to do.

As a workaround you can make nfs mount external (read about --external type[id]:value), having nfs mount on host you only provide its bind-mount to CT.

Other option is to kill all processes which have open file descriptors on nfs for the time of migration, but I'm not sure that you don't face other problems here.
