### ISSUE TITLE
Failed to restore on docker (NFS)

### ISSUE THREAD

**Issue by mobdogg** [checkpoint-restore/criu#1045]
hello I'm new on CRIU and docker. i follow [this](https://github.com/ZhuangweiKang/Docker-CRIU-Live-Migration) step to live migration on docker and it is run perfectly when i using virtual box. Then i tried to do the same step with 2 laptops, its success to create a checkpoint but when I restore it failed, the container won't start.

this is the restore.logs file
[restore.log](https://github.com/checkpoint-restore/criu/files/4536929/restore.log)

**Comment by avagin** [comment]
> (00.908805) Restore finished successfully. Resuming tasks.

We need more info about what's going on on your host. In the log, we see that all processes have been restored successfully. 

And you can look at our scripts which we use to test C/R of docker containers in travis: https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/travis/docker-test.sh

**Comment by mobdogg** [comment]
Thank you for answering my question, what kind of info you need to know?
For the server, I run it on virtual box ubuntu 16.04 LTS (windows), docker version 17.03, criu 3.7
For the client, I run it on ubuntu 16.04 LTS, docker version 17.03, criu 3.7

**Comment by mobdogg** [comment]
something wrong with the NFS. I use ssh to migrate the checkpoint folder to another laptop and it's working, the docker starts to restore.
