### ISSUE TITLE
Error when restoring from chroot.

### ISSUE THREAD

**Issue by Stokel** [checkpoint-restore/criu#105]
When trying to restore a checkpoint in a chroot environment I get the following error:
Error (mount.c:368): mnt: No root found for mountpoint 185 (@./proc)

[restore.txt](https://github.com/xemul/criu/files/91715/restore.txt)

**Comment by xemul** [comment]
Cc @avagin . The problem is that /proc/pid/mountinfo doesn't show the root mount entry in this case.
