### ISSUE TITLE
snapshot error--un-dumpable network

### ISSUE THREAD

**Issue by gianmarco995** [checkpoint-restore/criu#1052]
HI, I'm trying to perform the migration between to VMs (with Xubuntu inside) hosted by Virtualbox. At the beginning I was doing it with LXD "move" but only cold migration worked. So I tried to make a snapshot and this is what I got. 

```
lxc snapshot prova1 sn --stateful
lxc stop prova1 --stateful
lxc start prova1
Error: Migrate: Failed to run: /snap/lxd/current/bin/lxd forkmigrate prova1 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/prova1/lxc.conf /var/snap/lxd/common/lxd/containers/prova1/state true: 
Try lxc info --show-log prova1 for more info
```
Then, lxc info --show-log prova1:

```

Name: prova1
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/05/04 08:56 UTC
Status: Stopped
Type: container
Profiles: default
Snapshots:
  sn (taken at 2020/05/04 09:17 UTC) (stateful)

Log:

lxc prova1 20200504091833.905 ERROR    criu - criu.c:criu_ok:872 - Found un-dumpable network: phys (eth0)

```
Since at I did was only install the latest versions of snap, lxd and criu. And launch the container prova1 from an Alpine Image, I really don't know how manage this kind of error, because a let all as default.
Thanks in advance for your help

**Comment by adrianreber** [comment]
We had a similar report about LXC/LXD just last week or so (#1011). It seems LXC/LXD has changed the way how they set up network namespaces. It seems to be new that there is a physical network device in the network namespace and CRIU cannot handle that.

We need some input from LXC/LXD (@brauner) if this is actually true and if it is true LXC needs to use CRIU differently to dump the container.

**Comment by brauner** [comment]
> We had a similar report about LXC/LXD just last week or so (#1011). It seems LXC/LXD has changed the way how they set up network namespaces. It seems to be new that there is a physical network device in the network namespace and CRIU cannot handle that.
> 
> We need some input from LXC/LXD (@brauner) if this is actually true and if it is true LXC needs to use CRIU differently to dump the container.

LXC/LXD allows to move physical network devices across network namespaces, i.e. you could move your physical ethernet device into a container. Similar for sr-iov capable devices. Is that a problem for criu?

**Comment by brauner** [comment]
But users need to explicitly request this of course.

**Comment by adrianreber** [comment]
> LXC/LXD allows to move physical network devices across network namespaces, i.e. you could move your physical ethernet device into a container. Similar for sr-iov capable devices. Is that a problem for criu?

Yes, if CRIU, as in the case of LXC, also tries to handle the network namespace. In Podman/runc/crun we tell CRIU to ignore the network namespace and on restore we tell CRIU to restore the container into an existing network namespace.

> But users need to explicitly request this of course.

That is also what I would expect, but this is already the second report about the following line:
```
lxc prova1 20200504091833.905 ERROR    criu - criu.c:criu_ok:872 - Found un-dumpable network: phys (eth0)
```
Which is something users have not reporting before (https://github.com/lxc/lxc/blob/master/src/lxc/criu.c#L872).

Somehow LXC aborts the checkpoint before calling out to CRIU.

**Comment by brauner** [comment]
Oh, I misunderstood this. So yeah, LXD uses the "phys" type since it pre-creates the veth devices for the container on the host and then tells LXC to move them into the container on startup.
