### ISSUE TITLE
cannot restore complex process tree in HPC use case

### ISSUE THREAD

**Issue by dirkpetersen** [checkpoint-restore/criu#1062]
I am trying to restore a complex process tree (criu 3.13 , Ubuntu 18.04.4) . This is an R application that spawns multiple java processes.

```
k24:/fh/scratch/delete10/_HDC/SciComp/.checkpointer/petersen/47565344/0# ls
core-8076.img  core-8246.img  core-8296.img  core-8360.img  fs-8182.img    pagemap-8076.img
core-8127.img  core-8247.img  core-8297.img  core-8361.img  fs-8184.img    pagemap-8172.img
core-8128.img  core-8248.img  core-8298.img  core-8362.img  fs-8186.img    pagemap-8174.img
core-8129.img  core-8249.img  core-8299.img  core-8363.img  fs-8188.img    pagemap-8176.img
core-8133.img  core-8250.img  core-8300.img  core-8374.img  fs-8190.img    pagemap-8178.img
core-8134.img  core-8251.img  core-8315.img  core-8375.img  ids-8076.img   pagemap-8180.img
core-8137.img  core-8259.img  core-8316.img  core-8376.img  ids-8172.img   pagemap-8182.img
core-8139.img  core-8260.img  core-8317.img  core-8377.img  ids-8174.img   pagemap-8184.img
core-8140.img  core-8261.img  core-8318.img  core-8378.img  ids-8176.img   pagemap-8186.img
core-8143.img  core-8262.img  core-8319.img  core-8379.img  ids-8178.img   pagemap-8188.img
core-8144.img  core-8263.img  core-8320.img  core-8380.img  ids-8180.img   pagemap-8190.img
core-8145.img  core-8264.img  core-8321.img  fdinfo-10.img  ids-8182.img   pages-10.img
core-8147.img  core-8265.img  core-8329.img  fdinfo-11.img  ids-8184.img   pages-11.img
core-8154.img  core-8266.img  core-8330.img  fdinfo-12.img  ids-8186.img   pages-1.img
core-8155.img  core-8267.img  core-8331.img  fdinfo-2.img   ids-8188.img   pages-2.img
core-8158.img  core-8268.img  core-8332.img  fdinfo-3.img   ids-8190.img   pages-3.img
core-8162.img  core-8269.img  core-8333.img  fdinfo-4.img   inventory.img  pages-4.img
core-8163.img  core-8270.img  core-8334.img  fdinfo-5.img   local-scratch  pages-5.img
core-8172.img  core-8271.img  core-8335.img  fdinfo-6.img   mm-8076.img    pages-6.img
core-8174.img  core-8272.img  core-8336.img  fdinfo-7.img   mm-8172.img    pages-7.img
core-8176.img  core-8287.img  core-8337.img  fdinfo-8.img   mm-8174.img    pages-8.img
core-8178.img  core-8288.img  core-8338.img  fdinfo-9.img   mm-8176.img    pages-9.img
core-8180.img  core-8289.img  core-8339.img  files.img      mm-8178.img    pipes-data.img
core-8182.img  core-8290.img  core-8340.img  fs-8076.img    mm-8180.img    pstree.img
core-8184.img  core-8291.img  core-8341.img  fs-8172.img    mm-8182.img    seccomp.img
core-8186.img  core-8292.img  core-8342.img  fs-8174.img    mm-8184.img    stats-dump
core-8188.img  core-8293.img  core-8357.img  fs-8176.img    mm-8186.img    stats-restore
core-8190.img  core-8294.img  core-8358.img  fs-8178.img    mm-8188.img
core-8245.img  core-8295.img  core-8359.img  fs-8180.img    mm-8190.img

criu restore --shell-job
pie: 8184: Error (criu/pie/restorer.c:1811): Unable to create a thread: 8435
pie: 8435: Error (criu/pie/restorer.c:585): Thread pid mismatch 8435/8374
pie: 8435: Error (criu/pie/restorer.c:639): Restorer abnormal termination for 8184
Error (criu/cr-restore.c:2333): Restoring FAILED.

criu restore --shell-job
pie: 8182: Error (criu/pie/restorer.c:1811): Unable to create a thread: 8353
pie: 8182: Error (criu/pie/restorer.c:1951): Restorer fail 8182
```

It seems there is always some pid conflict especially on a multi-user system. I read about criu-ns at https://criu.org/CR_in_namespace but that does not seem to be packaged with your Ubuntu packages 

is criu-ns still supported ?

**Comment by adrianreber** [comment]
You are hitting a common problem: a PID collision. Every process is restored with the PID it had during checkpointing. If one of the PIDs exist the restore fails.

One solution seen with containers is the use of the PID namespace.

The `criu-ns` script can be found in our development branch: https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/criu-ns

> is criu-ns still supported ?

It still exists and you can use it :wink:

Or you can try to figure out how to work with PID namespaces

**Comment by dirkpetersen** [comment]
Thanks Adrian, I will give this a try. I will have to launch criu-ns from our suid wrapper https://github.com/FredHutch/slurm-examples/blob/master/checkpointer/lib/checkpointer/checkpointer-suid.c .   

Are there any limitations with network storage (e.g. NFS) or local files? I noticed that I need to upload all my /tmp files as java will otherwise not restore (e.g. /tmp/hsperfdata_[username])

```
tmpUpload() {
  local targ=$1
  local me=$(whoami)
  mkdir -p "${targ}"
  mytmplist=$(find /tmp -user ${me} -maxdepth 1)
  for item in $mytmplist; do
    cp -r "${item}" "${targ}"
  done
}

```

**Comment by dirkpetersen** [comment]
Also, do you think it would be possible to add criu-ns to ubuntu package next time you make a change? No python dependency check needed as python3 should be on every ubuntu box these days

**Comment by adrianreber** [comment]
> Are there any limitations with network storage (e.g. NFS) or local files?

What do you exactly mean?

>  I noticed that I need to upload all my /tmp files as java will otherwise not restore (e.g. /tmp/hsperfdata_[username])

Yes, those are common files Java creates and which need to be re-created on restore.

> Also, do you think it would be possible to add criu-ns to ubuntu package next time you make a change? No python dependency check needed as python3 should be on every ubuntu box these days

Hmm, as it is not part of the release tarball I guess I will not add it. Not sure why we do not have it on the master branch. Maybe we can move it to the master branch for the next release.

**Comment by adrianreber** [comment]
@dirkpetersen I think my PR #1056 could help you to checkpoint a process out of a PID namespace and restore into another PID namespace. If that is merged you should be able to do it without the help of `criu-ns`.
