### ISSUE TITLE
NetBSD support

### ISSUE THREAD

**Issue by krytarowski** [checkpoint-restore/criu#1072]
Hello,

I'm researching a port of criu to NetBSD, however I have got a few questions and I need some help here.

1. The NetBSD kernel does not have each feature needed by criu today, like setting pid of a newborn process or thread ID of each thread. This is just start of the features that are needed to be added upfront.

2. I don't intend to add first class syscalls for `snapshot(pid, path)` + `restore(path)`, as this approach is super complex and error-prone. It was also rejected in the Linux world.

3. As I need to add the kernel features for creating a process and tune its properties almost from scratch, what would be your dream kernel interface for this purpose? The Linux approach with ptrace and combination of other APIs is a little bit hacky, so I prefer to design something that is reliable, safe, elegant and featured.

If you would start over and dream about a new kernel interface with fine-grained syscall primitives to create an unborn process and restore it from a snapshot. What would be your dream API design?

I discussed with @adrianreber on IRC, but I was redirected to a wider audience.

Thank you in advance,

**Comment by xemul** [comment]
My dream interface was an enhanced proc filesystem that could be read from and written to. When read it would show you everything about the processes, open files, memory, pipes, networking, signals, etc. When written (mkdired, linked and symlinked as well) to it would create the needed objects in the kernel.

Dumping processes would then be just

    tar cf snap.tar /proc/$pid_to_dump

and restore just

    tar xf snap.tar -C /proc

:)

**Comment by krytarowski** [comment]
Good starting point.

`tar cf snap.tar` and `tar xf snap.tar -C` have to be replaced with an auxiliary tool, like `criu snap`, `criu unsnap`.

However as `/proc` is tied to its traditional purposes and kept in NetBSD mainly for Linux compat, we have some problems to rearrange it now... unless you think otherwise?

Recently linux introduced `pidfd_open(2)` that can be used to send signals to a process. I think we can go with something inspired to it, but elaborated to be similar to traversing an imagined `/proc/#/` tree that is used like a state machine.

So we need a syscall to create a process descriptor, like:

`int fd = procdesc(RPOCDESC_OPEN, (pid_t)100);`.

And parse it like XML SAX or DOM, dumping into a snapshot file?

Is the complete tree of attributes used by criu/Linux in criu/image/*.proto?
