### ISSUE TITLE
Checkpointing a process present in separate mount namespace

### ISSUE THREAD

**Issue by alakyadav** [checkpoint-restore/criu#1081]
I'm new to namespaces and CRIU and have been experimenting to understand the C/R process.

I created a C program that does following:
1) unshare-s to new namespaces (CLONE_NEWUSER | CLONE_NEWPID | CLONE_NEWNS)
2) writes to uid_map and gid_map
3) mount("proc", "/proc", "proc", 0, NULL)
4) Goes into a while loop, prints an integer and then sleeps for 2 seconds, every iteration.

The program itself is executed with the command: ``setsid ./ns_test < /dev/null &> output.log``

I am trying to do a diskless dump with a few pre-dump rounds, so I set up the tmpfs  mounts and start the page server on the target side. Then I started checkpointing the forked process. The pre-dumps finish successfully, but the dump fails. Relevant log entries:

``
(00.002948) mnt: Inspecting sharing on 718 shared_id 0 master_id 200 (@./home/alakyadav/dump)
``
``
(00.002950) Error (criu/mount.c:938): mnt: Mount 718 ./home/alakyadav/dump (master_id: 200 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
``
where ~/dump is the tmpfs directory.

I suspected CRIU needs to be in the namespace of the process tree it is dumping. So I try:

``
nsenter -a -t $pid criu dump -vvvv -o dump.log --tree 1 --images-dir ...
``
The mount points are collected now, but another problem arises:
``
(00.015475) Error (criu/cr-dump.c:1332): A session leader of 1(1) is outside of its pid namespace
``
This probably referring to the process that called unshare() in the first place.

I am sorry if this question is not directly related to CRIU or this isn't the right place for asking this. I just want to know what would be the right way to checkpoint and restore (on another system) a process like this with its own namespaces.

**Comment by adrianreber** [comment]
> I suspected CRIU needs to be in the namespace of the process tree it is dumping.

No, when used in container context CRIU is always running on the outside of all namespaces. So that should not be a problem.

Can you try to unmount mounts in your  mount namespace that you do not need. Like `/home/alakyadav/dump`?

**Comment by alakyadav** [comment]
It seems it isn't possible to do this from inside the new mount namespace. Trying to unmount something inherited from the root mount namespace gives the error:
`umount: /home/alakyadav/dump: not mounted`, even when it is visible in /proc/<pid>/mountinfo.
Mounting /home/alakyadav/dump with `--make-private` in root namespace did not work either.

To check, I unmounted the tmpfs created for diskless migration and attempted a normal dump. This brought back the error with the next inherited mountpoint:
`mnt: Mount 672 ./var/lib/lxcfs (master_id: 177 shared_id: 0) has unreachable sharing.`

Unmounting this in the root mount namespace just shifted the error to the next one:
`mnt: Mount 644 ./snap/core/9066 (master_id: 29 shared_id: 0) has unreachable sharing.`
or 
`mnt: Mount 671 ./boot (master_id: 30 shared_id: 0) has unreachable sharing.`

The man page for mount_namespaces(7) says:
> Mounts  that come as a single unit from more privileged mount are locked together and may not
          be separated in a less privileged mount namespace.   (The  unshare(2)  CLONE_NEWNS  operation
          brings  across  all of the mounts from the original mount namespace as a single unit, and re‐
          cursive mounts that propagate between mount namespaces propagate as a single unit.)
 
AFAIU we can't unmount points from this unit.

**Comment by adrianreber** [comment]
Can you share the source code for ns_test. Then I could try it locally.

**Comment by alakyadav** [comment]
Here: https://gist.github.com/alakyadav/7bc160d8b5e0b3fa5fa1000b1b657951

**Comment by Snorch** [comment]
```umount: /home/alakyadav/dump: not mounted```

When you unshare User and Mount namespace at the same time, all mounts copied from your host Mount namespace become MNT_LOCKED, it means you can't umount them.

If your purpose is just to test how c/r works, just skip User namspace, your life would become much easier.

If you still want to overcome this problem with User namespace and still want to get rid of those moutns, you should dig deeper in the direction of pivot_root.

**Comment by alakyadav** [comment]
Thanks so much!

> When you unshare User and Mount namespace at the same time, all mounts copied from your host Mount namespace become MNT_LOCKED, it means you can't umount them.

Is this documented somewhere so I can better understand the behaviour?

I think I now understand that to do the checkpoint like I want to, it is necessary to unmount the mount points inherited from the parent mount namespace, and if you're also in a new user namespace, that can only be done by moving the current root through pivot_root and then unmounting it there. I'll try that out. Thank you for all the help, I'll close this now.

**Comment by Snorch** [comment]
@alakyadav Sorry I didn't find any piece of documentation about this. But you can refer directly to the linux kernel, please see https://github.com/torvalds/linux/commit/5ff9d8a65ce80efb509ce4e8051394e9ed2cd942, sadly it does not say much more than I've already sad.

**Comment by alakyadav** [comment]
@Snorch Many thanks!
