### ISSUE TITLE
Checkpoing a graphic process on CentOS 7.8 gnome desktop.

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1082]
I originally tried to checkpoint maya, and I met same problem checkpoint a simple application like xterm.

I followed this doc: https://criu.org/VNC

My test environment:  CentOS 7.8 with stock kernel 3.10.0, and gnome desktop environment.

CRIU version: 3.14

I launched xterm like this:
```
# setsid unshare -i ./vnc_server.sh xterm
# ps axf
 16314 ?        Ss     0:00 /bin/bash ./vnc_server.sh xterm
 16320 ?        Sl     0:00  \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
 16353 ?        S      0:00  \_ xterm
 16355 pts/4    Ss+    0:00      \_ bash
```

Form lsof and ss, I can see it connects to **@/tmp/.ICE-unix/15119** and it's **gnome-session-b** on the other end.
```
# lsof -p 16353
COMMAND   PID USER   FD   TYPE             DEVICE  SIZE/OFF      NODE NAME
..............
xterm   16353 root    3u  unix 0xffff972c81d0ee80       0t0    155258 socket
xterm   16353 root    4u  unix 0xffff972c81d0f700       0t0    155259 socket
xterm   16353 root    5u   CHR                5,2       0t0     12415 /dev/ptmx

# ss --unix -a -p
u_str  ESTAB      0      0      @/tmp/.ICE-unix/15119  41542                 * 155259                users:(("gnome-session-b",pid=15119,fd=19))
```

I have to use **--external unix[155259]** when dump and **--ext-unix-sk** when restore to make CRIU happy. But got ICE error right after CRIU said it was successfully restored:

```
# ./criu restore -D xterm/ -o restore.log -v4 --shell-job --ext-unix-sk

ICE error:  Offending minor opcode    = 0 ()
            Offending sequence number = 1
            Error class               = BadState
            Severity                  = FatalToConnection
```

I feel like it's pretty standard for a graphic application running on gnome desktop environment? Is there any way for CRIU to dump&restore it?

Really appreciate if anyone can help!

Thanks
Jun Gan

**Comment by adrianreber** [comment]
Like discussed on the mailing list, I tried it and it works for me. I am using Fedora 32, however, but also Gnome. Much newer, though. Can you try another desktop environment. Something that is not gnome. Or try it on Fedora 32 because that worked for me.

**Comment by geminijun** [comment]
> Like discussed on the mailing list, I tried it and it works for me. I am using Fedora 32, however, but also Gnome. Much newer, though. Can you try another desktop environment. Something that is not gnome. Or try it on Fedora 32 because that worked for me.

Thanks for your suggestion. Finally, I found what makes the difference is the user I used to log in.

Previously, I always use **root**. If I use a normal user and sudo, then it will be like this:
```
# sudo setsid unshare -i ./vnc_server.sh xterm
```
```
# ps axf
 57012 pts/4    Ss     0:00  \_ bash
 57226 pts/4    S+     0:00  |   \_ sudo setsid unshare -i ./vnc_server.sh xterm
 57230 ?        Ss     0:00  |       \_ /bin/bash ./vnc_server.sh xterm
 57231 ?        Sl     0:00  |           \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0
 57250 ?        S      0:00  |           \_ xterm
 57252 pts/7    Ss+    0:00  |               \_ bash
```
Now you can see that unlike the process tree I post last time, it has a parent(sudo setsid unshare -i ./vnc_server.sh xterm) and a grandparent(bash)
And also, I cannot found the **unix socket** connected to **gnome-session-b** via /tmp/.ICE-unix any more.
```
# lsof -p 57250
xterm   57250 root    0u   CHR              136,4       0t0           7 /dev/pts/4
xterm   57250 root    1u   CHR              136,4       0t0           7 /dev/pts/4
xterm   57250 root    2u   CHR              136,4       0t0           7 /dev/pts/4
xterm   57250 root    3u  unix 0xffff972c0c143300       0t0      436378 socket
xterm   57250 root    4u   CHR                5,2       0t0       12415 /dev/ptmx
```

Then with no surprise, I can successfully dump & restore it by executing(Just have to add ```--shell-job```)
```
# criu dump -t 57230 -D xterm/ -o dump.log -v4 --shell-job
# criu restore -D xterm/ -o restore.log -v4 --shell-job -d
# ps axf
 57230 ?        Ss     0:00 /bin/bash ./vnc_server.sh xterm
 57231 ?        Sl     0:00  \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
 57250 ?        S      0:00  \_ xterm
 57252 pts/7    Ss+    0:00      \_ bash
```

I'm not familiar with vnc and gnome, have no idea why the login user makes a difference here. Especially I have to use **sudo** (because permission required by ```unshare```) anyway.

**Comment by adrianreber** [comment]
Nice to hear that it works. Does it now also work with maya?

**Comment by geminijun** [comment]
> Nice to hear that it works. Does it now also work with maya?

Unfortunately, no.
I found when I launched maya, there will be another two processes also be launched(not sure by maya or system, but they are not in the same process tree of maya)

It's a **dbus-launch** process which has two connections with **Xvnc** via **/tmp/.X11-unix/X25**

And also a **/usr/bin/dbus-daemon** process, which **AdskLicensingAg** is using it via socket **/tmp/dbus-uKzLh10Irz**

```
# lsof
 58866 ?        Sl     0:00 /usr/libexec/gnome-terminal-server
 58873 ?        S      0:00  \_ gnome-pty-helper
 58874 pts/0    Ss     0:00  \_ bash
 59119 pts/0    S+     0:00      \_ sudo setsid unshare -i ./vnc_server.sh /usr/local/bin/maya
 59120 ?        Ss     0:00          \_ /bin/bash ./vnc_server.sh /usr/local/bin/maya
 59121 ?        Sl     0:00              \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
 59140 ?        S      0:00              \_ /bin/bash -f /usr/local/bin/maya
 59154 ?        Sl     0:08                  \_ /usr/autodesk/maya2020/bin/maya.bin
 59159 ?        Sl     0:01                      \_ /opt/Autodesk/AdskLicensing/9.2.1.2399/AdskLicensingAgent/Ad
 59172 ?        S      0:00 dbus-launch --autolaunch a76fe76cc185404dae35c5e78caf6044 --binary-syntax --close-st
 59173 ?        Ss     0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
```
```
u_str  ESTAB      0      0       * 523150                * 506145                users:(("dbus-launch",pid=59172,fd=3))
u_str  ESTAB      0      0       * 516299                * 506147                users:(("dbus-launch",pid=59172,fd=4))
```
```
u_str  ESTAB      0      0      @/tmp/dbus-uKzLh10Irz 521427                * 503362                users:(("dbus-daemon",pid=59173,fd=11))
u_str  ESTAB      0      0       * 503362                * 521427                users:(("AdskLicensingAg",pid=59159,fd=26))
```

Although I can dump it by using **--external unix**
```
# criu dump -t 59120 -D maya_jungan/ -o dump.log -v4 --tcp-established --shell-job --external unix[506145] --external unix[506147] --external unix[503362]
```

When restoring with **--ext-unix-sk**, I got this error:
```
(00.084448)  59159: Error (criu/sk-unix.c:1324): unix: Can't connect 503362 socket: Connection refused
(00.084459)  59159: Error (criu/files.c:1196): Unable to open fd=26 id=0x1e7
```

Actually, I found after checkpointing, those two processes disappeared(I think it's because of the maya exit).

I don't know what does **dbus** do, I guess in order to dump it, we have to put those two processes also in the process tree to be checkpointed? Any idea how can I do it?

**Comment by adrianreber** [comment]
Can you add `dbus-launch` to `/usr/local/bin/maya`? Does that start dbus as a child process to vnc?

**Comment by geminijun** [comment]
> Can you add `dbus-launch` to `/usr/local/bin/maya`? Does that start dbus as a child process to vnc?

Unfortunately, no, I tried just execute ```dbus-launch``` and also ```dbus-launch --autolaunch a76fe76cc185404dae35c5e78caf6044 --binary-syntax --close-stderr``` in ```/usr/local/bin/maya``` and none of them worked.

I also tried a few more commands, and found some behaviors I cannot explain.

1. Like I mentioned before in the email list, ```maya``` crashed when I tried use ```newns.c``` in https://criu.org/VNC. Do you have any idea why is that? I tried same thing with ```xterm``` and it worked well, not sure what special thing maya is doing here. Here is a little more detail:

```
$ sudo ./newns ./vnc_server.sh /usr/local/bin/maya
$
Xvnc TigerVNC 1.8.0 - built Apr  1 2020 04:46:00
Copyright (C) 1999-2017 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12004000, The X.Org Foundation


Wed May 27 15:10:05 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on 0.0.0.0 interface(s), port 5925
 vncext:      created VNC server for screen 0

$
$ QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/var/tmp/runtime-root'
Graphic device does not support OpenGL Core Profile, fallback to OpenGL renderer.

Stack trace:
  OGS::Objects::KString::IsOK() const
  OGS::Objects::KString::KString(OGS::Objects::KString const&)
  OGSRenderer::initializeOGSDevice(OGS::Objects::UString*, int)
  OGSMayaRenderer::initialize(OGSRenderer::DeviceAPI, int, void*, void*, void*, bool)
  OGSMayaBridge::CreateOGSRenderer()
  OGSMayaBaseRenderer::initialize()
  /usr/autodesk/maya2020/lib/libOGSMayaBridge.so(+0x1be5fa) [0x7f93f1d4c5fa]
  OGSMayaBridge::Create3DViewportRenderer()
  /usr/autodesk/maya2020/bin/maya.bin() [0x41617c]
  Tapplication::start()
  /usr/autodesk/maya2020/bin/maya.bin() [0x40eed9]
  /usr/autodesk/maya2020/bin/maya.bin() [0x40d476]
  __libc_start_main
  /usr/autodesk/maya2020/bin/maya.bin() [0x40d8ba]
1
```

I also found same crash when I use command ```sudo setsid unshare -i -p -f ./vnc_server.sh /usr/local/bin/maya```

Actaully, in this case, I found the ```dbus-launch``` and ```dbus-daemon``` are children of ```/bin/bash ./vnc_server.sh /usr/local/bin/maya```

```
 15684 pts/1    S+     0:00  |           \_ sudo setsid unshare -i -p -f ./vnc_server.sh /usr/local/bin/maya
 15685 ?        Ss     0:00  |               \_ unshare -i -p -f ./vnc_server.sh /usr/local/bin/maya
 15686 ?        S      0:00  |                   \_ /bin/bash ./vnc_server.sh /usr/local/bin/maya
 15687 ?        Sl     0:00  |                       \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
 15709 ?        S      0:00  |                       \_ /bin/bash -f /usr/local/bin/maya
 15723 ?        Sl     0:05  |                       |   \_ /usr/autodesk/maya2020/bin/maya.bin
 15734 ?        Sl     0:01  |                       |       \_ /opt/Autodesk/AdskLicensing/9.2.1.2399/AdskLicensingAgent/AdskLicensingAgent -i 65e48020-e416-458e-718f-af5b62d07932
 15748 ?        S      0:00  |                       \_ dbus-launch --autolaunch a76fe76cc185404dae35c5e78caf6044 --binary-syntax --close-stderr
 15749 ?        Ss     0:00  |                       \_ /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
```


2. I found maya can be successfully launched if I also add new mount namespace: ```sudo setsid unshare -i -p -f --mount-proc ./vnc_server.sh /usr/local/bin/maya```, but this time ```criu dump``` failed because of my system has nfs&xfs mount point, why is that?

This time, maya was successfully launched, and the process tree looks good:
```
 16353 pts/1    S+     0:00  |           \_ sudo setsid unshare -i -p -f --mount-proc ./vnc_server.sh /usr/local/bin/maya
 16354 ?        Ss     0:00  |               \_ unshare -i -p -f --mount-proc ./vnc_server.sh /usr/local/bin/maya
 16355 ?        S      0:00  |                   \_ /bin/bash ./vnc_server.sh /usr/local/bin/maya
 16356 ?        Sl     0:00  |                       \_ Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
 16596 ?        S      0:00  |                       \_ /bin/bash -f /usr/local/bin/maya
 16610 ?        Sl     0:08  |                       |   \_ /usr/autodesk/maya2020/bin/maya.bin
 16626 ?        Sl     0:01  |                       |       \_ /opt/Autodesk/AdskLicensing/9.2.1.2399/AdskLicensingAgent/AdskLicensingAgent -i bc3d68b2-6f10-4263-41f0-2718704c353f
 16639 ?        S      0:00  |                       \_ dbus-launch --autolaunch a76fe76cc185404dae35c5e78caf6044 --binary-syntax --close-stderr
 16640 ?        Ss     0:00  |                       \_ /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
```

However, when I dumped the process by command:
```
# criu dump -t 16355 -D imgs/ -o dump.log -v4 --tcp-established --shell-job
```
It failed because of something like this:
```
(00.016230) Error (criu/mount.c:632): mnt: FS mnt ./home dev 0xfd00002 root / unsupported id 409
```
I reported some ```nfs``` mount point before and I umount them to avoid the problem, now it complains ```xfs``` which I cannot, because my system root is using xfs.

```
/dev/mapper/centos-root on / type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdb1 on /boot type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/centos-home on /home type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/centos-root on /var/lib/docker/containers type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/centos-root on /var/lib/docker/overlay2 type xfs (rw,relatime,attr2,inode64,noquota)
```

So my question is why CRIU cares about all the system mount points, the target process aren't using it. And why xfs&nfs cannot be supported, when the process launched in a new mount namespace?

**Comment by adrianreber** [comment]
Just in the ticket before this one (#1081) @Snorch was able to give a good explanation how it works with all the mounts.

@Snorch any recommendations what @geminijun  needs to do to set this up correctly?

**Comment by geminijun** [comment]
> Just in the ticket before this one (#1081) @Snorch was able to give a good explanation how it works with all the mounts.
> 
> @Snorch any recommendations what @geminijun needs to do to set this up correctly?

Thanks Adrian, although I don't think our problem are exactly the same. It did give me more hints, do you mean I should execute criu in the same mount namespace with the target process?

If I use:
```
nsenter -t 24614 -m /root/jungan/criu dump -t 24614 -o dump.log -D /root/jungan/maya_unshare_pid_ipc_mount/ -v4 --tcp-established --shell-job
```

I got this error:
```
(00.000432) Error (criu/util.c:392): Can't open self: No such file or directory
(00.000455) Error (criu/vdso.c:316): vdso: Can't open 0/maps on procfs: No such file or directory
(00.000462) Error (criu/vdso.c:560): vdso: Failed reading self/maps for filling vdso/vvar bounds
(00.000480) Unlock network
(00.000505) Unfreezing tasks into 1
(00.000512)     Unseizing 24614 into 1
(00.000526) Error (compel/src/lib/infect.c:346): Unable to detach from 24614: No such process
(00.000560) Error (criu/cr-dump.c:1764): Dumping FAILED.
```

If I use which you said may not necessary.
```
nsenter -t 24614 -m -p /root/jungan/criu dump -t 1 -o dump.log -D /root/jungan/maya_unshare_pid_ipc_mount/ -v4 --tcp-established --shell-job
```

I got this error:
```
(00.036203) Error (criu/cr-dump.c:1331): A session leader of 1(1) is outside of its pid namespace
```

I also tried to use ```criu-ns``` mentioned here https://criu.org/CR_in_namespace. And it reported same error as above.

```
# nsenter -a -t 84590 ps axf
  PID TTY      STAT   TIME COMMAND
  242 pts/5    R+     0:00 ps axf
    1 ?        S      0:00 /bin/bash ./vnc_server.sh /usr/local/bin/maya
    2 ?        Sl     0:00 Xvnc :25 -v -geometry 800x600 -interface 0.0.0.0 -SecurityTypes none
   21 ?        S      0:00 /bin/bash -f /usr/local/bin/maya
   35 ?        Sl     0:13  \_ /usr/autodesk/maya2020/bin/maya.bin
   40 ?        Sl     0:00      \_ /opt/Autodesk/AdskLicensing/9.2.1.2399/AdskLicensingAgent/AdskLicensingAgent -i ae5c0533-adcb-4051-7c7e-2ff9684af5a3
```

**Comment by jungan** [comment]
> @geminijun Sorry for a late response. Let me explain how I understand your problem.
> 
> 1. Unshare -p creates new pid namespace, this is needed because you wan't to put all daemons in same subtree. But to correctly access those new pids received from clone and fork syscalls you need to remount /proc.
> 2. Unshare --mount-proc implies -m, so you have mount namespace different from host.
> 3. If mount namespace of process is different from CRIU mount namespace, CRIU desides to dump this mount namespace.
> 4. Dumping mount namespace is done as a whole. You can't dump some mounts and not dump another ones. But if you just unshare mount namespace you copy all mounts from host.
> 5. Some mounts/filesystem types are not supported by criu, you can't dump them. You can manually mark them as external mounts so that they are bind-mounted from host on restore, but it's hard with all random mounts you copied from your host...
> 
> * You can try replacing pidns on step (1) with PR_SET_CHILD_SUBREAPER on the "root" proces to catch daemons when reparenting. This way you may overcome 2,3,4,5. But there is no guaranty that you did not face something else. Containers is what you need. Let me quote myself [#1017 (comment)](https://github.com/checkpoint-restore/criu/issues/1017#issuecomment-612067090):
> 
> > My opinion is that migration with "container" is much easier because the container implicitly removes a lot of external dependencies (for which criu needs user assistance by design). Without the "container" you need to manually investigate each external dependency for each application and it can be a pain. That's why we are concentrating on "container"s mostly...
> 
> * You can try unmounting all mounts you don't need manually or cut the root with pivot_root in (5) and try to setup all mounts and files you need there instead. But it's also the hard way.

Hi Snorch, thank you so much for your explanation, learned a lot, I agree that if it needs so much effort to remove the external dependency, maybe using a container is the way to go.

BTW, I found that on CentOS 8, I don't need to use new PID namespace in order to dump maya. Using the following cmd to launch maya:
```
setpid unshare -i ./vnc_server maya
```
Then I can successfully dump & restore it without a problem.

Thanks!

**Comment by geminijun** [comment]
Hi Snorch, thank you so much for your explanation, learned a lot, I agree that if it needs so much effort to remove the external dependency, maybe using a container is the way to go.

BTW, I found that on CentOS 8, I don't need to use new PID namespace in order to dump maya. Using the following cmd to launch maya:
```
setpid unshare -i ./vnc_server maya
```

Then I can successfully dump & restore it without a problem.

Thanks!
