### ISSUE TITLE
Change IP addresses on Establieshed sockets

### ISSUE THREAD

**Issue by Namron2000** [checkpoint-restore/criu#1085]
Hello,
I have 2 VM's and a established ip address between them, like it is given in the example https://criu.org/Simple_TCP_pair.  Now i want to change both IP addresses like:
VM 1: 192.168.1.3 to 192.168.1.4
VM 1: 192.168.1.10 to 192.168.1.11
So i dump both like in the example. Then i change the IP's in the files.img with:
`sudo crit decode --pretty -i files.img|sed s/old_ips/new_ips/g | crit encode > files.img.new`
`mv files.img.new files.img`
I change the IP's of the VM's. After this i restore them like in the example but with no success. 

I already read https://criu.org/Change_IP_address.
Is there any workaround, that the peer will accept the new IP Address ?
Is it possible to solve this problem with CRIU ? 

Thank you in advance.

**Comment by avagin** [comment]
> I change the IP's of the VM's. After this i restore them like in the example but with no success.

What do you mean? Does criu fail? Could you attach logs? When criu dumps a tcp socket, it adds iptables rules to block network traffic of the socket. If you change IP's, you need to update iptables rules too.
