### ISSUE TITLE
Restore Mechanism

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu#1088]
I am going through the restore procedure:

How does the actual copying of pages into address space happen?
 Does it happen in restorer blob.  function:( __export_restore_task )
How we write it to process address space 

Where do we read the pages.img file in code

**Comment by rppt** [comment]
The copying of the pages happens after the process that will become the restored process is forked, but before criu releases control of it.
Part of the copying is done in `restore_priv_vma_content()`   and another part is happening in `__export_restore_task()`.
