### ISSUE TITLE
CRIU Image Cache/Proxy

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu#1091]
I didn't find much documentation about it.
How it actual works?
How it Optimizes total migration time ?
And how it is different from diskless migration / page server?

**Comment by adrianreber** [comment]
> I didn't find much documentation about it.
> How it actual works?
> How it Optimizes total migration time ?

It was never merged in our release branch (`master`) which means it was always seen as not ready or experimental. There is actually one pull request open to remove it: #1087 It has been replaced with: https://github.com/checkpoint-restore/criu-image-streamer

> And how it is different from diskless migration / page server?

The page server is only responsible for the memory pages during migration, all other checkpoint/restore information is still written to disk without the image cache/proxy.

**Comment by shubham95** [comment]
thanks @adrianreber

In CRIU is there something where the restorer starts and start building process on the fly .
Like you are sending pages from page-server and restorer starts building process on the fly.
So that we don't have to wait for complete transfer before running CRIU restore.?

**Comment by adrianreber** [comment]
> In CRIU is there something where the restorer starts and start building process on the fly .
> Like you are sending pages from page-server and restorer starts building process on the fly.
> So that we don't have to wait for complete transfer before running CRIU restore.?

Kind of. If you are looking at memory pages, then yes. Lazy restore (post-copy migration) does that, but it still needs all the other information from a checkpoint besides the memory pages which can be transferred after a restore.

So, something like this:

1. Dump everything besides memory pages
2. Transfer this dump (without memory pages) to the destination
3. Restore process and fetch missing memory pages from source via post-copy/lazy migration feature

Looking at a dump. The biggest part of it, by far, are the memory pages. So you only have to transfer a few KB for a restore if you use lazy migration.

Lazy migration will, however, take a very long time as it will do a lot of network requests from the destination to the source to fetch the missing memory pages.

Best thing to do, is to combine post-copy and pre-copy migration to copy most of the memory pages before the actual migration.

**Comment by shubham95** [comment]
Great approach :) 

But In case of pre-copy, 
After 1 pre-dump can we start CRIU Restore on destination and it will keep updating the address space of process for subsequent pre-dump so that it will save restore time.

**Comment by rst0git** [comment]
> In CRIU is there something where the restorer starts and start building process on the fly.

As Adrian mentioned, post-copy migration can be used to achieve this -- https://criu.org/Lazy_migration

> Lazy migration will, however, take a very long time as it will do a lot of network requests from the destination to the source to fetch the missing memory pages.

I think it is important to point out that the total migration time will be higher but the down-time will be lower.

> After 1 pre-dump can we start CRIU 

No, pre-dump includes only memory pages, which is not sufficient to restore the process tree.

**Comment by shubham95** [comment]
Thanks @rst0git @adrianreber

**Comment by rst0git** [comment]
@shubham95 https://lisas.de/%7Eadrian/posts/2016-Oct-14-combining-pre-copy-and-post-copy-migration.html

**Comment by shubham95** [comment]
Yeah This blog is awesome i didn't know about it thanks @rst0git
