### ISSUE TITLE
Checkpointing 32b processes or mixed 64b/32b

### ISSUE THREAD

**Issue by lepommosaure** [checkpoint-restore/criu#1092]
Hi, 
I'm very new to this project and I find the idea of checkpointing/restarting anything amazing, but sorry if it's not the right place to ask
However I tried quite naively to checkpoint an application which is a 64b python script launching a 32b GUI application, and got this immediate answer:
```
(00.058659) Error (compel/arch/x86/src/lib/infect.c:410): Can't dump task 19053 running in 32-bit mode
(00.058664) Error (criu/cr-dump.c:1283): Can't infect (pid: 19053) with parasite
```
I read the FAQ and the wiki regarding 32b applications, and found the [Issue 43](https://github.com/checkpoint-restore/criu/issues/43), which is now closed, but to me the current status is not clear, I suspect a lot of things can go wrong:

1. Is it possible to checkpoint a 64b script running a 32b application?
2. Is it possible to checkpoint a 32b GUI?

My kernel is **5.3.0-53-generic** and I'm using criu **v3.6**

Thanks a lot!

**Comment by avagin** [comment]
Could you show the output of "criu check --all"?

**Comment by avagin** [comment]
Could you try to update the criu package? The current version is 3.14.

**Comment by avagin** [comment]
Cc: @0x7f454c46

**Comment by 0x7f454c46** [comment]
64-bit CRIU can be built without ia32 support (if compiler doesn't support multilib, no ia32 libraries).
I guess this is the case.

**Comment by lepommosaure** [comment]
You were exactly on point! 
```
> sudo criu check --all
Warn  (criu/cr-check.c:1029): CRIU built without CONFIG_COMPAT - can't C/R ia32
```

I just installed the 3.14 and now I have other warnings/errors:

sudo criu check --all
Warn  (criu/kerndat.c:845): Stale /run/criu.kdat file
Warn  (criu/cr-check.c:1230): clone3() with set_tid not supported
Error (criu/cr-check.c:1272): Time namespaces are not supported

Thanks for the help, I'm trying again now

**Comment by lepommosaure** [comment]
Okay, 

now a different issue:
`Warn  (compel/arch/x86/src/lib/infect.c:281): Will restore 17741 with interrupted system call
Error (criu/cr-dump.c:434): Task 17952 with SysVIPC shmem map @f725c000 doesn't live in IPC ns
Error (criu/cr-dump.c:1418): Dump mappings (pid: 17952) failed with -1
Error (criu/cr-dump.c:1764): Dumping FAILED.
`

If I understand correctly it may be linked to _[SysVIPC memory segment w/o IPC namespace](https://www.criu.org/What_cannot_be_checkpointed)_ ?

**Comment by Snorch** [comment]
If you know that your app is _not_ actually sharing this ipc shmem with anybody, you can try running it with unshare -i <your_app> before dumping it. It can help to workaround this problem. 

<details>
<summary>Or you can ...</summary>

Or you can run you app in a container, which will handle all external resources for you.
</details>
