### ISSUE TITLE
Where does actual page restoring from pages-1.img file happenps ?

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu#1102]
Where does actual page restoring from pages-1.img file happenps ?

In function prepare_mappings():
After getting fds of both pagemap and page file in function open_page_read():
we call restore_priv_vma_content()
In this function we put request into pagemap_enqueue_iovec()
i am not able to follow where we are reading pages and mapping to address file?

**Comment by avagin** [comment]
pr->read_pages()->....->read_local_page()

**Comment by shubham95** [comment]
Ok, But i still didn't able to find from where it is called ?

**Comment by avagin** [comment]
restore_priv_vma_content
 pr->read_pages = read_pagemap_page()
  pr->maybe_read_page = maybe_read_page_local
   read_local_page

**Comment by shubham95** [comment]
But In my case this function(read_local_page) is still not doing actual read 
beacuse the debug statememt in fuction is not printed in debug log
can you clarify this

**Comment by rppt** [comment]
The pages contents is filled in the restorer blob top optimize away multiple remappings of private vmas:
commit 91388fce03
