### ISSUE TITLE
Update .proto files to accomodate golang pb bindings options

### ISSUE THREAD

**Issue by mm-git01** [checkpoint-restore/criu#1104]
To port crit to go the `pb.go` bindings need to be generated. For bindings to be in a single package to avoid explicit import of all the `pb.go` files. 

To achieve this `option go_package = "/package-name";` need to be added to the `.proto` files.

for more information [google protobuf golang basics](https://developers.google.com/protocol-buffers/docs/gotutorial#defining-your-protocol-format) explains why the option is needed.

**Comment by Pac23** [comment]
#1105
