### ISSUE TITLE
CRIU RESTORE  vma_remap() to correct location

### ISSUE THREAD

**Issue by shubham95** [checkpoint-restore/criu#1117]
pieok =false
Means we restore the pages before restorer blob

In restorer.c : __export_restore_task()
when we call
vma_remap() 
In this function we remmap the vma to its correct loaction
_But how we are sure that at target location there is no other premmaped vma sitting or we are not overriding anything ?_

**Comment by Snorch** [comment]
At the moment of __export_restore_task we have only premaped vmas and restorer blob which is not intersecting with destinations of our remaps ( source [1] e1e103478 ("restorer: rework unmaping old VMA-s (v3)") and [2] 85adb7867 ("restore: Allocate task and threads args from rst-malloc") ).

So we don't care about restore blob as it's place was chosen properly. We only need to move premaped regions which are already sorted by address [1].

I don't fully understand all checks in "Shift private vma-s to the left" and "Shift private vma-s to the right" but I would assume that if last vma's offset is < it's target offset we just remap it to the right and next remap previous vma and so on. Else where we should instead start from the first vma and remap to the left. There is no chance of intersection in this simple algorithm.
Next if your last vma is before it's target position you remap from the end
