### ISSUE TITLE
Unable to run criu

### ISSUE THREAD

**Issue by Hari-Guhan-s** [checkpoint-restore/criu#1119]
hi i installed criu by apt-get isntall criu

i am getting the following error while runnig criu in terminal:
Warn  (criu/kerndat.c:659): Can't load /run/criu.kdat
Error (criu/util.c:714): exited, status=1
Error (criu/util.c:714): exited, status=1
Write 4294967295 to /proc/self/loginuid failed: Operation not permittedError (criu/uffd.c:231): uffd: Lazy pages are not available: Operation not permitted
Error (criu/kerndat.c:744): Lazy pages are not available

**Comment by rppt** [comment]
Hi @Hari-Guhan-s,

What distro are you using?
What is the kernel version?
What is the criu version?

**Comment by Hari-Guhan-s** [comment]
Sorry it's dependency issue got solved it with proper installation thanks
