### ISSUE TITLE
criu failed: type NOTIFY errno 0

### ISSUE THREAD

**Issue by zhoufann9188** [checkpoint-restore/criu#1127]
Hi , It's failed when i run "docker checkpoint create containter XX",

the notice is :
"Error response from daemon: Cannot checkpoint container jupyter-mybi: runc did not terminate sucessfully: criu failed: type NOTIFY errno 0"

My log is :
(00.000000) Unable to get $HOME directory, local configuration file will not be used.(00.000166) Warn  (criu/log.c:203): The early log isn't empty
(00.000188) Version: 3.12 (gitid 0)
(00.000198) Running on localhost.localdomain Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64
(00.000203) Overwriting RPC settings with values from /etc/criu/runc.conf
(00.000220) File /run/criu/criu.kdat does not exist
(00.000856) sockets: Probing sock diag modules
(00.113856) sockets: Done probing
(00.122020) Pagemap is fully functional
(00.122583) Found anon-shmem device at 4
(00.122609) Reset 11986's dirty tracking
(00.122719)  ... done
(00.122768) Dirty track supported on kernel
(00.122965) Found task size of 7ffffffff000
(00.383766) Warn  (criu/net.c:2910): Unable to get socket network namespace
(00.384045) Warn  (criu/net.c:2910): Unable to get tun network namespace
(00.384090) Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
(00.389290) Restoring netdev veth idx 10
(00.389914) Dumping netns links
(00.390006)     LD: Got link 1, type 772
(00.390015)     LD: Got link 10, type 1
(00.391363) vdso: Parsing at 7ffe50512000 7ffe50514000
(00.391387) vdso: PT_LOAD p_vaddr: ffffffffff700000
(00.391392) vdso: DT_HASH: ffffffffff700120
(00.391396) vdso: DT_STRTAB: ffffffffff700250
(00.391400) vdso: DT_SYMTAB: ffffffffff700160
(00.391404) vdso: DT_STRSZ: 5e
(00.391407) vdso: DT_SYMENT: 18
(00.391411) vdso: nbucket 3 nchain a bucket 7ffe50512128 chain 7ffe50512134
(00.391431) vdso: rt [vdso] 7ffe50512000-7ffe50514000 [vvar] ffffffffffffffff-fffffffffffffffe
(00.392107) Warn  (criu/net.c:2910): Unable to get socket network namespace
(00.392190) cpu: x86_family 6 x86_vendor_id GenuineIntel x86_model_id Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
(00.392203) cpu: fpu: x87 FPU will use FXSAVE
(00.392567) Adjust mmap_min_addr 0x1000 -> 0x10000
(00.392582) Found mmap_min_addr 0x10000
(00.392831) files stat: fs/file-max 13070409, fs/nr_open 1048576
(00.392993) ========================================
(00.393005) Dumping processes (pid: 11658)
(00.393009) ========================================
(00.393020) rlimit: RLIMIT_NOFILE unlimited for self
(00.393028) Running pre-dump scripts
(00.393033)     RPC
(00.393278) irmap: Searching irmap cache in work dir
(00.393305) No irmap-cache image
(00.393311) irmap: Searching irmap cache in parent
(00.393320) irmap: No irmap cache
(00.393325) cpu: fpu:1 fxsr:1 xsave:0 xsaveopt:0 xsavec:0 xgetbv1:0 xsaves:0
(00.393524) cg-prop: Parsing controller "cpu"
(00.393540) cg-prop:    Strategy "replace"
(00.393548) cg-prop:    Property "cpu.shares"
(00.393555) cg-prop:    Property "cpu.cfs_period_us"
(00.393560) cg-prop:    Property "cpu.cfs_quota_us"
(00.393568) cg-prop:    Property "cpu.rt_period_us"
(00.393573) cg-prop:    Property "cpu.rt_runtime_us"
(00.393577) cg-prop: Parsing controller "memory"
(00.393581) cg-prop:    Strategy "replace"
(00.393586) cg-prop:    Property "memory.limit_in_bytes"
(00.393590) cg-prop:    Property "memory.memsw.limit_in_bytes"
(00.393594) cg-prop:    Property "memory.swappiness"
(00.393598) cg-prop:    Property "memory.soft_limit_in_bytes"
(00.393602) cg-prop:    Property "memory.move_charge_at_immigrate"
(00.393606) cg-prop:    Property "memory.oom_control"
(00.393610) cg-prop:    Property "memory.use_hierarchy"
(00.393614) cg-prop:    Property "memory.kmem.limit_in_bytes"
(00.393618) cg-prop:    Property "memory.kmem.tcp.limit_in_bytes"
(00.393622) cg-prop: Parsing controller "cpuset"
(00.393626) cg-prop:    Strategy "replace"
(00.393631) cg-prop:    Property "cpuset.cpus"
(00.393635) cg-prop:    Property "cpuset.mems"
(00.393639) cg-prop:    Property "cpuset.memory_migrate"
(00.393643) cg-prop:    Property "cpuset.cpu_exclusive"
(00.393647) cg-prop:    Property "cpuset.mem_exclusive"
(00.393650) cg-prop:    Property "cpuset.mem_hardwall"
(00.393654) cg-prop:    Property "cpuset.memory_spread_page"
(00.393658) cg-prop:    Property "cpuset.memory_spread_slab"
(00.393662) cg-prop:    Property "cpuset.sched_load_balance"
(00.393666) cg-prop:    Property "cpuset.sched_relax_domain_level"
(00.393670) cg-prop: Parsing controller "blkio"
(00.393684) cg-prop:    Strategy "replace"
(00.393689) cg-prop:    Property "blkio.weight"
(00.393694) cg-prop: Parsing controller "freezer"
(00.393698) cg-prop:    Strategy "replace"
(00.393702) cg-prop: Parsing controller "perf_event"
(00.393706) cg-prop:    Strategy "replace"
(00.393711) cg-prop: Parsing controller "net_cls"
(00.393715) cg-prop:    Strategy "replace"
(00.393719) cg-prop:    Property "net_cls.classid"
(00.393723) cg-prop: Parsing controller "net_prio"
(00.393727) cg-prop:    Strategy "replace"
(00.393732) cg-prop:    Property "net_prio.ifpriomap"
(00.393736) cg-prop: Parsing controller "pids"
(00.393740) cg-prop:    Strategy "replace"
(00.393744) cg-prop:    Property "pids.max"
(00.393748) cg-prop: Parsing controller "devices"
(00.393752) cg-prop:    Strategy "replace"
(00.393756) cg-prop:    Property "devices.list"
(00.393840) Perparing image inventory (version 1)
(00.393902) Add pid ns 1 pid 11986
(00.393918) Add net ns 2 pid 11986
(00.393941) Add ipc ns 3 pid 11986
(00.393961) Add uts ns 4 pid 11986
(00.393978) Add mnt ns 5 pid 11986
(00.393996) Add user ns 6 pid 11986
(00.394005) Add cgroup ns 7 pid 11986
(00.394010) cg: Dumping cgroups for 11986
(00.394065) cg:  `- New css ID 1
(00.394071) cg:     `- [blkio] -> [/system.slice/containerd.service] [0]
(00.394076) cg:     `- [cpuacct,cpu] -> [/system.slice/containerd.service] [0]
(00.394080) cg:     `- [cpuset] -> [/] [0]
(00.394083) cg:     `- [devices] -> [/system.slice/containerd.service] [0]
(00.394087) cg:     `- [freezer] -> [/] [0]
(00.394091) cg:     `- [hugetlb] -> [/] [0]
(00.394095) cg:     `- [memory] -> [/system.slice/containerd.service] [0]
(00.394099) cg:     `- [name=systemd] -> [/system.slice/containerd.service] [0]
(00.394103) cg:     `- [net_prio,net_cls] -> [/] [0]
(00.394106) cg:     `- [perf_event] -> [/] [0]
(00.394110) cg:     `- [pids] -> [/system.slice/containerd.service] [0]
(00.394114) cg: Set 1 is criu one
(00.394136) freezing processes: 100000 attempts with 100 ms steps
(00.394275) freezer.state=FROZEN
(00.394360) SEIZE 11658: success
(00.394372) SEIZE 11717: success
(00.394381) SEIZE 11730: success
(00.394388) SEIZE 11731: success
(00.394398) SEIZE 11732: success
(00.394409) SEIZE 11733: success
(00.394418) SEIZE 11734: success
(00.394451) SEIZE 11735: success
(00.394463) SEIZE 11736: success
(00.394475) SEIZE 11801: success
(00.394484) SEIZE 11815: success
(00.394494) SEIZE 11840: success
(00.394504) SEIZE 11841: success
(00.394513) SEIZE 11845: success
(00.394521) SEIZE 11846: success
(00.394529) SEIZE 11847: success
(00.394536) SEIZE 11853: success
(00.394544) SEIZE 11854: success
(00.394552) SEIZE 11855: success
(00.394561) SEIZE 11856: success
(00.394569) SEIZE 11857: success
(00.394576) SEIZE 11858: success
(00.394585) SEIZE 11859: success
(00.394593) SEIZE 11860: success
(00.394601) SEIZE 11870: success
(00.394609) SEIZE 11871: success
(00.394617) SEIZE 11872: success
(00.394624) SEIZE 11878: success
(00.394632) SEIZE 11879: success
(00.394640) SEIZE 11880: success
(00.394649) SEIZE 11881: success
(00.394657) SEIZE 11882: success
(00.394665) SEIZE 11883: success
(00.394675) SEIZE 11884: success
(00.394685) SEIZE 11885: success
(00.395054) Error (compel/src/lib/ptrace.c:27): suspending seccomp failed: Invalid argument
(00.395128) Unlock network
(00.395183) Unfreezing tasks into 1
(00.395189)     Unseizing 11658 into 1
(00.395194) Error (compel/src/lib/infect.c:343): Unable to detach from 11658: No such process
(00.395218) Error (criu/cr-dump.c:1742): Dumping FAILED.

My system:
Centos 7.6

My linux kernel core:
Linux 3.10.0-957.el7.x86_64

I can't downgrade my linux kernel core because its a pro server

Cloud authors help me please? Thanks!

**Comment by amoonmm** [comment]
----------------------------------------------------------------------

**Comment by YangdaXing** [comment]
@zhoufann9188 hello, I have met the same error when I used the `checkpoint` option to migration my container based on Podman. Have you ever solve the problem? Thanks

**Comment by Snorch** [comment]
@YangdaXing Please paste your actual criu errors. Because from the first glance on you message it is not clear which exact (same) error you talk about. As far as I know Podman c/r should be working quiet fine though i'm not experienced in this field =)

**Comment by adrianreber** [comment]
The CentOS/RHEL 7 kernel used here does not support suspending seccomp and thus it fails. You need something like `--security-opt=seccomp=unconfined`.
