### ISSUE TITLE
how about UDP sockets checkpoint-restore ?

### ISSUE THREAD

**Issue by sequoiar** [checkpoint-restore/criu#1130]
Libsoccr seems only for TCP socket. Is there any plan support UDP socket ?

**Comment by rst0git** [comment]
CRIU supports checkpoint/restore of UDP sockets. Libsoccr is used to solve a specific problem, i.e., save/restore state of a TCP connection. In contrast to TCP, UDP is a connection-less communication protocol and the UDP layer retains no state.

**Comment by sequoiar** [comment]
yes, UDP retains no connection state, but still buffered data in kernel. if missing these buffered data, UDP-based transport like UDT/QUIC may need to be re-transmit without connection-broken.

**Comment by avagin** [comment]
@sequoiar currently the kernel doesn't support restoring receive queue data for UDP sockets. If we want to restore  buffered data, we need to extend the kernel API.
