### ISSUE TITLE
How can I build criu for android devices?

### ISSUE THREAD

**Issue by xy815661276** [checkpoint-restore/criu#1132]
I've tried to build criu for my android devices,but I don't konw how to build it with android NDK,can you give me some help?thank you very much.

**Comment by adrianreber** [comment]
Do you get any errors? Building CRIU should be basically just `make`.

**Comment by xy815661276** [comment]
I used android NDK to build criu with debian 9,but get the error:
`ld: cannot find -lnl-3
images/Makefile:112: recipe for target 'images/built-in.o' failed
make[1]: *** [images/built-in.o] Error 1
Makefile:216: recipe for target 'images/built-in.o' failed
make: *** [images/built-in.o] Error 2`
I don't know what happend.

**Comment by sunny868** [comment]
maybe it means not find  libnl-3.so

**Comment by xy815661276** [comment]
Thanks,I build it success with v3.12 by using android ndk.

**Comment by xy815661276** [comment]
> maybe it means not find libnl-3.so . do you want to run criu on android platform?

yes,I want to run criu on android-x86 platform,but I get some problems,It needs libc.so.6,ld-linux-x86-64.so.2,libnet.so.I copy these files to /system/lib64/,then run criu,but get the error:
`segmentation fault`

**Comment by sunny868** [comment]
I am not sure criu can run on android platform . But you can run "criu check" first to make sure kernel is ready.
you can refer to link [https://criu.org/Linux_kernel]
