### ISSUE TITLE
Feature Request: Ready to Run Docker 

### ISSUE THREAD

**Issue by sinamoeini** [checkpoint-restore/criu#1133]
Hi,

Thank you for such an amazing project. Is it possible to provide a docker in the repository that can run criu. I tried to build such an image myself, but every time after installation I get errors.

Thanks,
Sina

**Comment by adrianreber** [comment]
Can you a bit more specific what you mean? What kind of image do you mean?

**Comment by sinamoeini** [comment]
Like a Dockerfile that you can run and use criu out of the box. Like the one below (which doesnt work btw. I get error running `criu check`). 

FROM ubuntu:18.04
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    sudo \
    gawk \
    iptables \
    jq \
    pkg-config \
    libaio-dev \
    libcap-dev \
    libprotobuf-dev \
    libprotobuf-c0-dev \
    libnl-3-dev \
    libnet-dev \
    libseccomp2 \
    libseccomp-dev \
    protobuf-c-compiler \
    protobuf-compiler \
    python-minimal \
    uidmap \
    kmod \
    criu \
    && apt-get clean

**Comment by adrianreber** [comment]
Thanks for making it clearer. The use case of CRIU in a container is, however, not really clear. The `make check` might fail as CRIU needs a lot of privileges. So you need to run your container with `--privileged`. I would also recommend to use Fedora as the base of the container, as that is a distribution which always has the latest CRIU version. From what I have seen Ubuntu does not really update CRIU. There is a PPA from the CRIU project with the latest CRIU version.

**Comment by sinamoeini** [comment]
I see! Thank you for the explanation

**Comment by sinamoeini** [comment]
I am going to go ahead and close this issue. This feature already exists. The docker image can be built by executing 

`make docker-build`
