### ISSUE TITLE
Plugin support for device mapped files

### ISSUE THREAD

**Issue by muraj** [checkpoint-restore/criu#1136]
Hi,
I was wondering if it was considered / on the roadmap for plugins to support handling mmapped device file checkpointing?  For example, if an kernel module just exposed PROT_READ only memory available via device map for accessing streaming data without syscalls from user mode, not having this would make the process unsupported by criu due to the following lines.  If there was a way for a library to save / restore such mappings itself, that would allow such application to still be supported under CRIU.

https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/proc_parse.c#L603

**Comment by avagin** [comment]
Feel free to introduce a plugin hook to handle this case.
