### ISSUE TITLE
restoring process tree

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1137]
CRIU moderators, can you please explain how the restorer code is restoring the process tree? please provide a detailed explanation of that particular code as I'm unable to understand it.

**Comment by sunny868** [comment]
Maybe you can refer to  [https://criu.org/Checkpoint/Restore](url)

**Comment by ashwani29** [comment]
@sunny868 I did go through that, The problem is with the code. 
anyway do you know how to set up the criu code on a system and work with it? I mean to say, if I insert some printf statements how should I build and run the criu code to see debugging outputs? @adrianreber  pls help here.
