### ISSUE TITLE
CRIU failes to take stateful snapshot of container

### ISSUE THREAD

**Issue by mouri11** [checkpoint-restore/criu#1138]
I am running an AWS instance of ubuntu 18.04 LTS arm64. It has an ubuntu 18.04 aarch64 container running on it. I try to take a snapshot with the following command:
```
lxc snapshot --stateful  mycontainer snap1
```
I face the following error:
```
Error: snapshot dump failed
(00.275797) Error (criu/mount.c:1062): mnt: The file system 0x39 0x39 (0x42) btrfs ./run/systemd/unit-root is inaccessible
(00.275811) Error (criu/fsnotify.c:209): fsnotify: Mount root for 0x000039 not found
(00.275821) Warn  (criu/fsnotify.c:283): fsnotify: 	Handle 0x39:0x1ca cannot be opened
(00.310935) Error (criu/irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.310948) Error (criu/fsnotify.c:286): fsnotify: 	Can't dump that handle
(00.310991) Error (criu/cr-dump.c:1352): Dump files (pid: 1813) failed with -1
(00.380634) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
I don't know what's causing this. Any help will be appreciated. Thanks.

**Comment by adrianreber** [comment]
I think this is related to btrfs. CRIU cannot handle btrfs: https://criu.org/Filesystems_pecularities

**Comment by mouri11** [comment]
Hi. I used the dir storage filesystem to run a new container. I faced the following error:
```
Error: snapshot dump failed
(00.391160) Error (criu/sk-inet.c:113): Unsupported proto 58 for socket 94c8
(00.391196) Error (criu/cr-dump.c:1352): Dump files (pid: 4033) failed with -1
(00.462146) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
Face the following error while using lvm:
```
Error: snapshot dump failed
(00.439130) Error (criu/sk-inet.c:113): Unsupported proto 58 for socket bb7b
(00.439160) Error (criu/cr-dump.c:1352): Dump files (pid: 5462) failed with -1
(00.508699) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
Is there any other storage system that can prevent this error? Please let me know.

**Comment by adrianreber** [comment]
> `(00.439130) Error (criu/sk-inet.c:113): Unsupported proto 58 for socket bb7b`

This now not FS related but you have process open with proto 58 which should be ICMP for IPv6. What is running in your container using ICMP for IPv6?

**Comment by mouri11** [comment]
Anyway to check what is using ICMP in my container? I don't have anything specifically running in it. Not even a ping. Also, I launched a container using ZFS. I received the following error:
```
Error: snapshot dump failed
(00.113215) Error (criu/namespaces.c:408): Can't dump nested net namespace for 16645
(00.113244) Error (criu/namespaces.c:626): Can't make netns id
(00.147239) Error (criu/util.c:714): exited, status=1
(00.181322) Error (criu/util.c:714): exited, status=1
(00.182451) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

**Comment by mouri11** [comment]
Ok. So I found a crude way to know what is using ICMP. I used the following command:
```
sudo lsof -n | grep "st=07"
```
Output:
```
systemd-n 162     systemd-network   18u     raw6                         0t0 87616 00000000000000000000000000000000:003A->00000000000000000000000000000000:0000 st=07
```
Is CRIU failing because of this?

**Comment by adrianreber** [comment]
So, running systemd in a container will always be challenging for CRIU to handle. Try to run a container without systemd. Or at least without systemd-network.

**Comment by mouri11** [comment]
Hey. It worked!! Thanks a lot. I was actually trying to perform live migration of the stateful snapshots using LXD, but was facing this problem for a long time. Thanks for your patience.

**Comment by adrianreber** [comment]
Nice. Good to hear. Closing this, as it seems your questions has been solved.

**Comment by mouri11** [comment]
Hi. Sorry to bother, but I am facing a new error. I stopped systemd-network, and a small script is running inside the container.
```
Error: snapshot dump failed
(01.778857) Error (criu/files-reg.c:1281): Can't lookup mount=28 for fd=0 path=/dev/pts/2
(01.778931) Error (criu/cr-dump.c:1352): Dump files (pid: 22144) failed with -1
(01.850943) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

**Comment by adrianreber** [comment]
How do you start that script?

**Comment by mouri11** [comment]
Well, I did ```chmod +x compu.sh```, then started it using ```./compu.sh 10895 &```.

**Comment by adrianreber** [comment]
But how do you make it run in your container?

**Comment by mouri11** [comment]
I used ```lxc exec mycontainer -- sudo --login --user ubuntu``` to get into the container shell, and simply started the script as mentioned above. Then I exit from the container shell, and try to take a stateful snapshot.

**Comment by adrianreber** [comment]
I guess stdout/stderr is connected to the outside of the container. Maybe. Try closing stdout/stderr with `>/dev/null 2>&1`

**Comment by mouri11** [comment]
Ok. I restarted the script inside as ```./compu.sh 10895 & > /dev/null 2>&1```. Same error.
```
(01.828059) Error (criu/files-reg.c:1281): Can't lookup mount=28 for fd=0 path=/dev/pts/2
(01.828129) Error (criu/cr-dump.c:1352): Dump files (pid: 29595) failed with -1
(01.898874) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

**Comment by adrianreber** [comment]
Not sure. Things started manually after the container is running is always a bit tricky. Can't you automatically start the script when the container starts?

I am sure there is another way to do it, but I do not know how lxc works to give you a solution. You to try different ways of starting it.

If you look at https://criu.org/Simple_loop there is an example how to start a shell script with setsid. Not sure if that helps with lxc.

In the case above it would be interesting to know which process is `pid: 29595`? Probably not your script.

**Comment by mouri11** [comment]
Sorry about the late reply. The process which belongs to this pid seems to be the script itself. Except that this script is running inside the host instead of the container. Is it the containerized script itself, which has an instance running inside the host? I tried again taking a stateful snapshot with the script running. I got a pid in the error similar to the one above, and this is what I found in the host.
```
101000   12052  0.0  0.0   6564  2096 ?        S    04:42   0:00 /bin/bash ./compu.sh 10895
```
I'll try to automate the script, and let you know.

**Comment by mouri11** [comment]
Automating the script worked. I used the following script:
```
#!/bin/bash

lxc stop mycontainer
lxc delete mycontainer
lxc launch ubuntu:arm64 mycontainer
# lxc exec mycontainer -- sudo reboot
lxc exec mycontainer -- bash -c 'while [ "$(systemctl is-system-running 2>/dev/null)" != "running" ] && [ "$(systemctl is-system-running 2>/dev/null)" != "degraded" ]; do :; done'
lxc file push compu.sh mycontainer/home/ubuntu/
lxc exec mycontainer -- sudo service systemd-networkd stop
lxc exec mycontainer -- bash /home/ubuntu/compu.sh 10895 &
```
There is an excellent article on how to run a script after detecting startup in the container. Thanks for your help. :-)
