### ISSUE TITLE
Criu fails after first Pre-dump

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1141]
I've read that the first pre-dump will dump the whole container state and subsequent pre-dumps will only dump memory changes(i.e. dirty pages). So why does restore just after the first pre-dump doesn't work?

**Comment by adrianreber** [comment]
> I've read that the first pre-dump will dump the whole container state and subsequent pre-dumps will only dump memory changes

This is wrong. A pre-dump will basically only dump the memory and reset the soft-dirty memory bit. It is not a complete dump.

> So why does restore just after the first pre-dump doesn't work?

Because it is a pre-dump and not a full dump.
