### ISSUE TITLE
Problems installing CRIU in the Amazon Cloud

### ISSUE THREAD

**Issue by bethven** [checkpoint-restore/criu#1146]
Hello,
I am trying to install CRIU in on a virtual machine with UBUNTU 13.04 in the Amazon Cloud. I have run to install the Dockerfiles dependencies https://github.com/checkpoint-restore/criu/tree/master/scripts/build (Dockerfile.openj9-ubuntu ). But I get the following errors. Please how could I solve it.

Here are some of the errors that appear:
Err http://us-east-1.ec2.archive.ubuntu.com raring/main Sources                                                        
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring/universe Sources                                                    
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring/main amd64 Packages                           
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring/universe amd64 Packages                       
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring-updates/main Sources                          
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring-updates/universe Sources                      
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring-updates/main amd64 Packages                   
  404  Not Found [IP: 52.207.133.243 80]
Err http://us-east-1.ec2.archive.ubuntu.com raring-updates/universe amd64 Packages               
  404  Not Found [IP: 52.207.133.243 80]
Err http://security.ubuntu.com raring-security/main Sources                
  404  Not Found [IP: 91.189.91.39 80]
Err http://security.ubuntu.com raring-security/universe Sources            
  404  Not Found [IP: 91.189.91.39 80]
Err http://security.ubuntu.com raring-security/main amd64 Packages         
  404  Not Found [IP: 91.189.91.39 80]
Err http://security.ubuntu.com raring-security/universe amd64 Packages     
  404  Not Found [IP: 91.189.91.39 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring/main/source/Sources  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring/universe/source/Sources  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring/main/binary-amd64/Packages  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring/universe/binary-amd64/Packages  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring-updates/main/source/Sources  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring-updates/universe/source/Sources  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring-updates/main/binary-amd64/Packages  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://us-east-1.ec2.archive.ubuntu.com/ubuntu/dists/raring-updates/universe/binary-amd64/Packages  404  Not Found [IP: 52.207.133.243 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/raring-security/main/source/Sources  404  Not Found [IP: 91.189.91.39 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/raring-security/universe/source/Sources  404  Not Found [IP: 91.189.91.39 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/raring-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.39 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/raring-security/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.91.39 80]
W: Failed to fetch http://ppa.launchpad.net/criu/ppa/ubuntu/dists/raring/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]

So since I have not been able to install the dependencies, when I try to build the CRIU, errors like the following appear:
PBCC     images/timens.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/fown.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/macvlan.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/autofs.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/sysctl.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/time.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/binfmt-misc.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/seccomp.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/userns.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/cgroup.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/rpc.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/siginfo.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/rlimit.pb-c.c
make[1]: protoc-c: Command not found
  PBCC     images/file-lock.pb-c.c

Thank you
Regards,
Beth.

**Comment by rst0git** [comment]
> make[1]: protoc-c: Command not found

It looks like `protobuf-c` is not installed. A list of dependencies and installation instructions is available in https://criu.org/Installation

> I am trying to install CRIU in on a virtual machine with UBUNTU 13.04 in the Amazon Cloud.

Note that CRIU relies on interfaces that may not be available in old kernel versions ([Upstream kernel commits](https://criu.org/Upstream_kernel_commits)).

**Comment by rppt** [comment]
Ubuntu 13.04 is long ago EOL. Even if all the dependencies can be installed (which I doubt), the kernel is too old to run CRIU:
https://criu.org/Check_the_kernel

**Comment by bethven** [comment]
Thank you very much! I will install a newer version of ubuntu.
Regards.
Beth
