### ISSUE TITLE
Update netfilter.c to use libnftables?

### ISSUE THREAD

**Issue by acidghost** [checkpoint-restore/criu#1150]
Hi there.

https://github.com/checkpoint-restore/criu/blob/90bc4590b65425fa6abab2f8fb63c96bae5acb32/criu/netfilter.c#L21-L22

Would there be any interest in using nftables for the netfilter.c module? Does it need to support xtables too for legacy reasons?

I'm doing some performance profiling and looks like the numerous calls to `system()` to lock / unlock network put a dent into performance.

**Comment by adrianreber** [comment]
Not an expert in this area, but I would say there is nothing against it.

We had a GSoC proposal for replacing calls to iptables with ebpf code:

https://criu.org/Google_Summer_of_Code_Ideas

I talked with someone some time ago why we were not using a library and I think it was just easier calling iptables. Not relying on external tool sounds good, especially as we had problems with the different iptables implementations and versions.

**Comment by acidghost** [comment]
Thanks for the quick pointer! I'll look into eBPF and report back in this issue.

**Comment by Snorch** [comment]
@acidghost You can also take a look on this https://src.openvz.org/projects/OVZ/repos/criu/commits/7ff54a419fa7ca7c1d4def2add9162fe38605224 as a temporary solution. We've temporary switched to nft in Virtuozzo criu to work on top of Centos 8 which does not have iptables-save-legacy.

**Comment by adrianreber** [comment]
@Snorch Interesting link. I do not see any problems using CRIU with iptables (iptables v1.8.4 (nf_tables)) on RHEL or CentOS 8.

Do I miss things which are no longer working and I just have not seen it yet?

**Comment by Snorch** [comment]
Ah, it looks like nft works well but our network_unlock_internal didn't work even on legacy iptables for me:

```
[root@snorch criu]# unshare -n
[root@snorch criu]# iptables-save
[root@snorch criu]# cat /tmp/iptables
*filter
:CRIU - [0:0]
-I INPUT -j CRIU
-I OUTPUT -j CRIU
-A CRIU -m mark --mark "0xC114" -j ACCEPT
-A CRIU -j DROP
COMMIT
[root@snorch criu]# iptables-restore /tmp/iptables
[root@snorch criu]# iptables-save
# Generated by iptables-save v1.8.3 on Fri Jul 24 11:40:30 2020
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:CRIU - [0:0]
-A INPUT -j CRIU
-A OUTPUT -j CRIU
-A CRIU -m mark --mark 0xc114 -j ACCEPT
-A CRIU -j DROP
COMMIT
# Completed on Fri Jul 24 11:40:30 2020
[root@snorch criu]# cat /tmp/iptables-unlock 
*filter
:CRIU - [0:0]
-D INPUT -j CRIU
-D OUTPUT -j CRIU
-X CRIU
COMMIT;
[root@snorch criu]# iptables-restore /tmp/iptables-unlock 
iptables-restore: line 3 failed
```

So I misunderstood the problem and though that iptables-to-nft conversion was guilty and reworked it in nft. Just hope this draft patch may be useful to anybody.

Another problem is that if we have no iptables-restore-legacy binary on Centos8 and continaer has iptables(legacy) rules inside we don't have a way to dump them. More over dump_iptables and dump_nftables both work with nftables and this can bring some messup because we restore nft twice in this case.
