### ISSUE TITLE
make error on building criu

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1153]
I've run make command in criu source directory.
It is giving the following errors:
`make[1]: *** [/home/ashna/criu-3.8.1/scripts/nmk/scripts/build.mk:209: compel/plugins/std/infect.o] Error 1`
`make: *** [Makefile.compel:52: compel/plugins/std.lib.a] Error 2`

**Comment by 0x7f454c46** [comment]
Please, provide the whole log - somewhere above should be the compiler/linker error that describes why gnu/make thinks the build has errored.
