### ISSUE TITLE
CRIU Restore failed: Async I/O Event Error

### ISSUE THREAD

**Issue by ShunmugaPriyaR** [checkpoint-restore/criu#1156]
Hello,

CRIU version: v3.12-175-g3953b33
Ubuntu Kernel version: 4.15.0-112-generic

I am trying to restore a docker container and getting the following error in CRIU during restore process:

Error (criu/pie/restorer.c:739): wrong aio: tail=0x0 head=0x0 req=0xbe old_nr=0x17f new_nr=0x2ff expect=0x17f

I have restored this application successfully in other platforms. Please help me to understand the nature of the problem and how to resolve it. Thank you.

Regards,
Priya.

**Comment by adrianreber** [comment]
I am not familiar with the AIO code paths, but

> I have restored this application successfully in other platforms. Please help me to understand the nature of the problem and how to resolve it. Thank you.

The application uses AIO (https://man7.org/linux/man-pages/man7/aio.7.html) and it seems you are trying to restore it in a state that CRIU cannot handle. Not sure there is an easy way to solve it besides fixing CRIU to correctly handle it.

Do you always get that error? Is it a one time thing? Does it only happen on this combination of kernel and CRIU?

> I have restored this application successfully in other platforms.

What is your definition of a platform?

**Comment by ShunmugaPriyaR** [comment]
Hi Adrian,

Thank you  for your response.

I am always getting the same error when tried from the same servers .
But selecting another server of the same ubuntu distribution and the
kernel  version makes the CRIU work successfully.

For further debugging, in the problematic testbed, I run the same docker
container application with the swapping of source server and destination
server. And restore happened successfully.

I built the custom kernel in the original source server and I created the
kernel image from it. In the destination server, I used that custom kernel
image. I doubted whether this AIO error has some link to the Kernel changes
done. So I went back to the linux mainline Kernel version in both the
servers. But the same problem is repeated if the Source and destination
servers are not swapped.

I wish to understand the nature of the problem.  Thank you.

Regards,
Priya.

**Comment by adrianreber** [comment]
Do your systems all have the same number of CPUs? Maybe AIO restore does not work if the number of CPUs is different. Just a wild guess. Can you list the hardware configuration of your servers and in which direction the migration fails.
