### ISSUE TITLE
Problem of restore by RPC

### ISSUE THREAD

**Issue by jchaosun** [checkpoint-restore/criu#1160]
I'm trying to restore a checkpoint by RPC, and got the error message as follows,
+++++++++++++++++++++++++++++++++++++++++++++++++++++
(00.018045)  33670: Opening fdinfo-s
(00.018048)  33670: tty: open driver pts id 0xc8 index 3 (master 0 sid
11261 pgrp 33670 inherit 1)
(00.018051)  33670: Error: tty: Don't have tty to inherit session from,
aborting
(00.018060)  33670: Error: Unable to open fd=0 id=0xc8
(00.022727) Error: 33670 killed by signal 9: Killed
(00.022767) Unlink remap dev/shm/mvm-zb.cr.1.ghost
(00.022780) Unlink remap tmp/#102696195.cr.2.ghost
(00.022808) Error: Restoring FAILED.
+++++++++++++++++++++++++++++++++++++++++++++++++++++

I'm running CRIU (v3.14) as a daemon service ( criu service --daemon -o xxx.log -v4 --address /var/run/criu_service.socket) and receiving RPC from client to checkpoint and restore. Checkpoint works well, but restore got no luck. The error is related to the following code, where STDIN_FILENO is not considered as a tty.

```
int tty_prep_fds(void)
{
    if (!opts.shell_job)
        return 0;

    if (!isatty(STDIN_FILENO))
        pr_info("Standard stream is not a terminal, may fail later\n");
    else
        stdin_isatty = true;

    self_stdin_fdid = fdstore_add(STDIN_FILENO);
    if (self_stdin_fdid < 0) {
        pr_err("Can't place stdin fd to fdstore\n");
        return -1;
    }

    return 0;
}

```
My understanding is that when using criu cmd to restore, it inherits the tty/pts of the criu cmd, so there should be no problem to get tty/pts and input/output will be in whatever pts you are running criu restore cmd. However, when criu is running as a daemon process, it does not have tty/pts, and does not have tty to inherit from.

I tried to use external option during snapshot and/or inherit-fd option during restore to specify fd[1]:tty[xxxx:xx], however, still does not work, got error message:
Error: tty: Don't have tty to inherit session from, aborting
or 
Error: tty: Can't set tty params on 0xc8: Inappropriate ioctl for device

Thanks!

**Comment by sdimovv** [comment]
Hi,

Did you manage to solve this? I have the exact same problem. I am using criu 3.17.1

**Comment by rst0git** [comment]
> My understanding is that when using criu cmd to restore, it inherits the tty/pts of the criu cmd, so there should be no problem to get tty/pts and input/output will be in whatever pts you are running criu restore cmd. However, when criu is running as a daemon process, it does not have tty/pts, and does not have tty to inherit from.

I believe the `orphan-pts-master` hook was introduced as a solution for this problem. The following commit message contains more information about this feature: https://github.com/checkpoint-restore/criu/commit/6afe523d97d59e6bf29621b8aa0e6a4332f710fc

**Comment by sdimovv** [comment]
Interesting. Just checked the docs regarding this (https://criu.org/Action_scripts). But I am not sure how to use it. Would you be able to provide an example?

**Comment by rst0git** [comment]
> Would you be able to provide an example?

The runc [^1] and crun [^2] implementations are good examples.

[^1]: https://github.com/opencontainers/runc/pull/1355/commits/1c43d091a18a2f2dd73b46d49c678c265cf1ace3
[^2]: https://github.com/containers/crun/pull/480/commits/a15a72428571debaf6cb87c1fb318f4442d96602
