### ISSUE TITLE
ERRO[0000] read unixpacket @->@: EOF

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1161]
I've put a debug statement in __get_service_fd(), see below:
```
static int __get_service_fd(enum sfd_type type, int service_fd_id)
{
	pr_debug("FUNC __GET_SERVICE_FD================================\n");
	pr_debug("SERVICE_FD_BASE IS %d, TYPE IS %d, SERVICE_FD_MAX_IS %d, SERVICE_FD_ID IS %d\n", service_fd_base, type, SERVICE_FD_MAX, service_fd_id);
	return service_fd_base - type - SERVICE_FD_MAX * service_fd_id;
}
```
on running restore, it is giving the following error :
`ERRO[0000] read unixpacket @->@: EOF`

**Restore log**:

```
(00.000000) sfd: FUNC GET_SERVICE_FD====================================
(00.000000) FUNC TEST_BIT==========================================
(00.000000) sfd: FUNC GET_SERVICE_FD====================================
(00.000000) FUNC TEST_BIT==========================================
(00.000000) FUNC RECV_CRIU_MSG===============================
(00.000000) sfd: FUNC INSTALL_SERVICE_FD===============================
(00.000000) sfd: FUNC __GET_SERVICE_FD================================
(00.000000) sfd: SERVICE_FD_BASE IS 0, TYPE IS 2, SERVICE_FD_MAX_IS 13, SERVICE_FD_ID IS 0
(00.000000) FUNC TEST_BIT==========================================
(00.000000) FUNC SET_BIT===========================================
(00.000000) sfd: FUNC INSTALL_SERVICE_FD===============================
(00.000000) sfd: FUNC __GET_SERVICE_FD================================
(00.000000) sfd: SERVICE_FD_BASE IS 0, TYPE IS 1, SERVICE_FD_M\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
```

**Comment by avagin** [comment]
Could you add more details? What do you run? What version of criu is used? What problem do you try to solve?

**Comment by ashwani29** [comment]
i was having a  state of already checkpointed container. and then after putting some debugging statements in the restore process tree hierarchy to see which functions are actually called while restoring, i got this error.

```
Version: 3.12
GitID: v3.12-175-g3953b333
```

command used to restore : `sudo runc restore --work-path tmp5/ ctr`

ctr itself is  container id.

**Comment by 0x7f454c46** [comment]
What was the original issue you've tried to debug with those statements?
Please, attach logs of the original problem, not something introduced with the patch.

**Comment by ashwani29** [comment]
I've to understand the criu code. So i was putting debug statements in the functions.

**Comment by ashwani29** [comment]
I've to understand the criu code. So i was putting debug statements in the functions.

**Comment by avagin** [comment]
Does criu restore work without your changes? Could you attach a patch with all your changes?

**Comment by ashwani29** [comment]
Yes it was working before the changes. and for now i've commented all the changes i made and step by step uncommented again and restoring the container state to see at which point it was giving the error. hence leaving some of the debugging statements commented and all works fine now.

what do you mean by this? there is no patch I made, its just `pr_debug` statements.
> Could you attach a patch with all your changes?

**Comment by Snorch** [comment]
>>    Could you attach a patch with all your changes?
>
>what do you mean by this? there is no patch I made, its just pr_debug statements.

You should probably learn git and github to at least be able to publish a patch with your changes first.

**Comment by ashwani29** [comment]
@Snorch  yes sure, but when did I say i want to submit a patch. I think the discussion got diverted from the topic :-).
