### ISSUE TITLE
Can't open 0/pagemap on procfs: Operation not permitted

### ISSUE THREAD

**Issue by DreamTexX** [checkpoint-restore/criu#1164]
If i try running `criu check` i get this error 
```Error (criu/kerndat.c:377): Can't open 0/pagemap on procfs: Operation not permitted```
Server is running Debian 10 buster and Kernel is Linux 4.9.0

**Comment by adrianreber** [comment]
Are you running criu as root or non-root? Currently criu only works as root.

**Comment by DreamTexX** [comment]
Yeah, sorry forget telling that, i run it as root

**Comment by DreamTexX** [comment]
Also i run this on an virutal server but i dont think that this is important

**Comment by adrianreber** [comment]
I would say this is solved. Run CRIU as root and it will work. Re-open if you still have problems as root.

**Comment by DreamTexX** [comment]
Tf? I told you that i run it as root, but the error is still there

**Comment by adrianreber** [comment]
Ah, misunderstood that. What kind of virtual server is that. I see something like this on one that I am using:
```
localhost systemd[1]: Detected virtualization kvm.
```

**Comment by DreamTexX** [comment]
`hostnamectl` is telling me that the virtualization is `openvz`

**Comment by adrianreber** [comment]
@checkpoint-restore/maintainers : Is it possible to use CRIU inside of OpenVZ?

**Comment by DreamTexX** [comment]
On kvm it is working?

**Comment by adrianreber** [comment]
Yes, on KVM it is working. I know that it does not work on LXD like provided by Travis for aarch64, ppc64le, s390x, because those are unprivileged containers. It could be that OpenVZ does not export all necessary interfaces for CRIU into your container.

The interesting thing about your question is, that CRIU was developed by OpenVZ to migrate OpenVZ containers. Never having used OpenVZ myself, I unfortunately do not know if it works in a OpenVZ based container.

**Comment by rppt** [comment]
@Snorch @mihalicyn 
comments?

**Comment by Snorch** [comment]
Hi, all!

Pagemap is obviously not readable in our Virtuozzo(OpenVZ) containers:

```
CT-8cb52209-37b8-4f00-adb5-6813b3689e4f criu# strace -e open cat /proc/self/pagemap 
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/proc/self/pagemap", O_RDONLY)    = -1 EPERM (Operation not permitted)
cat: /proc/self/pagemap: Operation not permitted
+++ exited with 1 +++
```
https://src.openvz.org/projects/OVZ/repos/vzkernel/browse/fs/proc/task_mmu.c#1384

Virtuozzo did not checked or tested if CRIU can be run in Container. But If you still want to run CRIU there, you need to revert this kernel patch https://src.openvz.org/projects/OVZ/repos/vzkernel/commits/55186bf6ecfe7335821844e6567149e07530b998 to fix pagemap problem. Probably you would face some more problems, but I will be glad to help.

We plan to check and possibly fix running CRIU inside VZ Containers, but it would take some time.
