### ISSUE TITLE
Project On Windows

### ISSUE THREAD

**Issue by SiyerBOBO** [checkpoint-restore/criu#1170]
Can this project be ported to windows? I have consulted a lot of materials, but I haven't got the answer. Is there any hope of saving and restoring the running state of applications on windows?

**Comment by adrianreber** [comment]
> Can this project be ported to windows?

Short answer: no

> I have consulted a lot of materials, but I haven't got the answer.

I would say it is pretty obvious that CRIU is Linux only. The first sentence on https://criu.org is "Welcome to CRIU, a project to implement checkpoint/restore functionality for Linux. "

> Is there any hope of saving and restoring the running state of applications on windows?

Depends how much work you put into it :wink:. I guess it is technically doable if you have a lot of resources to put into such an project and if you have the possibility to extend Windows in case required interfaces are missing. But that is probably not what you have been asking.

**Comment by SiyerBOBO** [comment]
Thank you for your serious reply, and I look forward to such a product in the future~❤
