### ISSUE TITLE
How criu parses .img file such as pstree.img in c

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1173]
I've to collect `pid` and `ppids` from `pstree.img` file. It's information is present in `JSON` format so how `criu` parses it in c language and get the values of it's variables.

**Comment by adrianreber** [comment]
Almost all image files are using protobuf. The *proto files are compiled for the target language using the protobuf compiler. These language bindings are then used to access the image files.

**Comment by ashwani29** [comment]
I migrated the checkpointed files from source to destination, then on the destination, I'm making a program to collect these attribute's values.
`pstree-pb-c.c`, `pstree-pb-c.h`, have comments on top that they are generated from pstree.proto, Does `pstree-pb-c.c`  will give this values? 
can you give a simple pseudo like program/steps on how can I read those values from pstree.img?

**Comment by adrianreber** [comment]
These are default protobuf operations. Just have a look at the protobuf documentation.

**Comment by ashwani29** [comment]
I did go through this link: [https://developers.google.com/protocol-buffers/docs/cpptutorial](https://developers.google.com/protocol-buffers/docs/cpptutorial)
 as in this documentation under section writing a message and reading a message, the example shown there is using a file, so this file can be in any format?  I can use the same method to read and write from/into files of .img format too?

**Comment by adrianreber** [comment]
CRIU's image files are described here: https://criu.org/Images

**Comment by ashwani29** [comment]
Ok will look at this, just one another question- How does CRIU trace process tree of the container?

**Comment by Snorch** [comment]
> How does CRIU collect process tree
https://criu.org/Checkpoint/Restore#Collect_process_tree_and_freeze_it

**Comment by ashwani29** [comment]
Thanks
