### ISSUE TITLE
criu doesn't create /var/lib/criu after installation

### ISSUE THREAD

**Issue by rajbhar** [checkpoint-restore/criu#1177]
I built criu from sources and did make && sudo make install. I dont see /var/lib/criu directory created by default which is supposed to be the default directory for plugins. How does the env variable "CRIU_LIBS_DIR" gets set? i see it empty upon default installation. I am not sure if i missed any step for properly installing criu.

**Comment by adrianreber** [comment]
Do you actually need /var/lib/criu?

According to https://criu.org/Environment_variables it is the location for Plugins. Are you actually using plugins? If you are using plugins just create this directory. As far as we know plugins are not really used and we have been discussing multiple times if the whole plugins infrastructure should be removed.

**Comment by rajbhar** [comment]
i am trying to checkpoint my application that opens up a fd to a gpu device so i think i do need plugin to support that. Please let me know if there is a way to do that alternatively.  The reason i opened up this issue is that at least one warning at https://github.com/checkpoint-restore/criu/blob/be2ded15ee1cff6c0bd5733dda57bb17ea85bcd9/criu/plugin.c#L215 should be added if criu make install doesn't have any script to create the default lookup directory. I can send a patch if that makes sense.

**Comment by 0x7f454c46** [comment]
@rajbhar, please send the patch (open a Pull Request) - it's quite hard to tell if a particular change makes sense without looking what's being changed and the reasons in a commit description
