### ISSUE TITLE
How to run cpp or python code in runc container?

### ISSUE THREAD

**Issue by gitsvm** [checkpoint-restore/criu#1184]
I don't know what to add in `args` parameter in `config.json` file to be able to run my code in `cpp` or `python`?  file is present in root inside `rootfs` folder.

currently my args parameter is this:
```
`		"args": [
			"sh",
			"-c",
			"hello.cpp"
		],`
```
it is giving following error on running the container using `sudo runc run <cid>`: 
 `ERRO[0000] invalid character '/' looking for beginning of value`

This is my cpp file:
```
#include <iostream.h>
//#include <stdio.h>


using namespace std;

int main(int argc, char const *argv[])
{
	cout<<"Hello world\n";
	/* code */
	return 0;
}
```

**Comment by adrianreber** [comment]
I will close this as this has nothing to do with CRIU. Please ask your runc questions somewhere else.
