### ISSUE TITLE
config.json settings to run cpp or python file in the conatiner

### ISSUE THREAD

**Issue by gitsvm** [checkpoint-restore/criu#1185]
How should `args` parameter will look like if i want to run a cpp file my container?
currently my args section of the `config.json` file is this:

```
		"args": [
			"sh"
		],
```

**Comment by adrianreber** [comment]
Please do not open the same issue I just closed with the same, non-criu related, question. Your question has again nothing to do with CRIU. Closing just as #1184

**Comment by gitsvm** [comment]
Those guys aren't replying, that's why i asked here. no issue anyway.
