### ISSUE TITLE
Examples using seccomp=unconfined

### ISSUE THREAD

**Issue by gitisz** [checkpoint-restore/criu#1186]
Looking at the documentation provided, I see the examples depend on `--security-opt seccomp:unconfined`

docker run -d --name looper --security-opt seccomp:unconfined busybox  \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

When running on a cloud platform, this may not be a secure solution.  When performing checkpoint w/o the above I receive the error:  

> runc did not terminate sucessfully: criu failed: type NOTIFY errno 0  

_Note: spelling typo in log output._

Is there a shortlist or way I can infer what actual seccomp are required, without opening up the container to no protection?

CRIU is a bit new to me, so any pointers are welcome!

**Comment by gitisz** [comment]
Looking further I see this may not be due to a un-whitelisted seccomp option, but more likely due to kernel version.

```
criu check --all
Error (criu/cr-check.c:625): Kernel doesn't support PTRACE_O_SUSPEND_SECCOMP
```

The documentation further suggests an upgrade to Kernel version is required, but doesn't state which:
> SeccompEdit
> You'll notice that all of the above examples disable Docker's default seccomp support. In order to use seccomp, you'll need > a newer version of the Kernel. **Update Needed with Exact Version**

Looking for a path forward as `seccomp=unconfined` is not a viable option.

**Comment by adrianreber** [comment]
I thought I commented here already yesterday, but somehow my comment is gone. Sorry.

On all systems I am using (Fedora and RHEL/CentOS 8) I am using Podman without the default seccomp profile. So newer kernels work with the default seccomp profile. If you look at our Podman based Travis test (https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/travis/podman-test.sh) it just works.

In you second comment you already found the same solution. You need a kernel that supports `PTRACE_O_SUSPEND_SECCOMP`. Once you have that CRIU can checkpoint and restore your container.

**Comment by adrianreber** [comment]
After a quick look at the kernel sources it seems that you should at least hast kernel version 4.3. Which kernel do you use?

**Comment by gitisz** [comment]
Looks like I am having 3.10 on el7.  I'll see what course I can follow getting to 4.3+... thank you, that is a great help!

**Comment by adrianreber** [comment]
Ah, CentOS/RHEL 7. Yes, that unfortunately needs `seccomp=unconfined`. If you use RHEL/CentOS 8 it will just work.
