### ISSUE TITLE
mapping of pids from host to container & vice-versa

### ISSUE THREAD

**Issue by gitsvm** [checkpoint-restore/criu#1188]
How can I get the mapping of pids from host view to the container restored i.e what pid from host is what pid in that container?

**Comment by adrianreber** [comment]
I don't think that is possible. Maybe using pidfd?

**Comment by brauner** [comment]
That depends on what you already know:
1. You already know the pid on the host and you want to know the pid in a container using pid namespaces
If that's what you're talking about then you can simply look at:
```
brauner@wittgenstein|~
> cat /proc/489666/status | grep NSpid
NSpid:  489666  1
```

This field contains the value of the pid in each descendant pid namespace starting from the initial pid namespace in the procfs instance you're look at it.

2. You know the pid in the container's pid namespace and you want to know the pid in the host's pid namespace
2.1 Send yourself a ucred message from one pid namespace to the other setting the si_pid field to the pid you want to translate.
2.2 Get yourself a pidfd from inside to the container, sent it outside and look at it's fdinfo file

**Comment by brauner** [comment]
I have patches to use the ioctl_ns() to translate pids.

**Comment by gitsvm** [comment]
@brauner Please share it, and tell me how to use this `ioctl_ns()`.

**Comment by brauner** [comment]
It's not in the upstream kernel yet so you can't use it anywhere.

**Comment by gitsvm** [comment]
Ok so by translation you mean pid in host to pid in namespace ryt?
