### ISSUE TITLE
License of libsoccr

### ISSUE THREAD

**Issue by touisteur** [checkpoint-restore/criu#1198]
Hi,

I'm a big fan of the CRIU work.

I'm finding libsoccr very useful, but I'd like to make sure I understand its license status.

The readme page says : The project is licensed under GPLv2 (though files sitting in the lib/ directory are LGPLv2.1).

I just wanted to make sure that it means that libsoccr is GPLv2.

In this case, IIUC I can't use (either through .o aggregation & direct call, or through static or dynamic link) this code with a proprietary application. Am I understanding correctly ? Even dynamic linking is off-limits, right ?

Thanks for your help.

**Comment by adrianreber** [comment]
CRIU is GPLv2, correct. Only the content in lib/ is LGPLv2.1 as described in the README.

> In this case, IIUC I can't use (either through .o aggregation & direct call, or through static or dynamic link) this code with a proprietary application. Am I understanding correctly ? Even dynamic linking is off-limits, right ?

I am not a layer, but this is also how I understand it.

**Comment by adrianreber** [comment]
I am closing this. Please reopen if you have further questions.
