### ISSUE TITLE
Checkpoint and restore a process has established unix domain socket connection.

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1200]
I'm using CRIU to checkpoint and restore "redis-server", which has a "redis-cli" connected to it via a unix domain socket. I cannot just use `--ext-unix-sk`, as it sets the socket type to STREAM. Here is the command I used for dump:

```
criu dump -t 23253 -D criu_imgs/ -o dump.log --shell-job -v4 --external unix[2940132]
```

And here is the command I used for restore:
```
criu restore -D criu_imgs/ -o restore_.log --shell-job -v4 --ext-unix-sk --tcp-close
```

Then I found I got segv in the restore log:
```
(00.014810)  23253: unix: Opening standalone (stage 0 id 0x10 ino 2940132
peer 2940131)
(00.014823)  23253:             Create fd for 8
(00.014826)  23253: unix: Opening standalone (stage 1 id 0x10 ino 2940132
peer 2940131)
(00.014829)  23253: unix:       Connect 2940132 to 2940131
(00.015683) Error (criu/cr-restore.c:1417): 23253 killed by signal 11:
Segmentation fault
(00.015780) Error (criu/cr-restore.c:2293): Restoring FAILED.
```

Checking the code, I found that CRIU will still try to restore this socket by connecting it back to the original peer, which may not be available anymore. Is there any option to let criu bypass restoring this socket and leave it close just like what "--tcp-close" does for established TCP connection? In my case, I don't need it to be restored, it's fine to ask client re-connect.

**Comment by adrianreber** [comment]
As far as I know there is no option for UDP which does the same as `--tcp-close`. We would be happy to take your patch for that.
