### ISSUE TITLE
[question] Multiple page_pipe_buf-s in a page_pipe

### ISSUE THREAD

**Issue by alakyadav** [checkpoint-restore/criu#1202]
Hello, I am having some trouble understanding the implementation of pipe structures used to keep track of memory that the parasite fills in.
I understand that each linux pipe (the one created with using pipe() syscall) is represented using a `struct page_pipe` and that each `page_pipe_buf` stores the fds to those pipes, the offset (where the buffer begins in pipe) and the length of the buffer. Each buffer is a contiguous region in pipe but it may store multiple segments, each being [vaddr, vaddr + vlen) of container process's memory, and each segment is represented by an element in the `iov` array of `struct iovec`

My question is: what is the need of having multiple `page_pipe_buf`s in a single pipe? Given that the array `iov` does not have a fixed size and can be grown, it should be sufficient to have one `page_pipe_buf` in each pipe with any number of memory segments represented by `struct iovec`s stored in the array.

To ask this another way, under what circumstances would we not be able to just grow the current 'page_pipe_buf` and need another one to be added to the pipe, such that multiple of these buffers share the same pipe?

**Comment by rst0git** [comment]
A `page_pipe` is used to accumulate memory pages. It consists of a list of `page_pipe_buf` objects each associated with a pipe (buffer). An array of iovec-s is used to describe the pages' locations. There is a limit for the maximum pipe buffer size (`PIPE_MAX_SIZE`) and new pipes are created on demand. I hope this answers your question.

(See commit https://github.com/checkpoint-restore/criu/commit/960694e96f23c34b492c0d88e4ccf1e37ba47876)

**Comment by avagin** [comment]
If you look at try_add_page_to, you will find that it create a new page_pipe_buf if flags are not match. Otherwise we will have one page_pipe_buf per pipe.  The only flag that we have is PPB_LAZY, so Mike (@rppt) should know more about this.
