### ISSUE TITLE
Assembler warning message

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1217]
I see following warnings when compiling CRIU on Fedora 33:
```
include/common/asm/bitops.h: Assembler messages:
include/common/asm/bitops.h:37: Warning: no instruction mnemonic suffix given and no register operands; using default for `bt'
include/common/asm/bitops.h: Assembler messages:
include/common/asm/bitops.h:63: Warning: no instruction mnemonic suffix given and no register operands; using default for `bts'
```

**Comment by adrianreber** [comment]
I see @cyrillos and @tkhai as authors. Any ideas how this could be fixed?

**Comment by cyrillos** [comment]
They have been taken from linux kernel code mostly. Take a look please into kernel x86 code, should be fixed there.

**Comment by tkhai** [comment]
Yes, commit 919df37c2

"bits: Add test_and_set_bit()
    
Borrowed from Linux Kernel".

I have no a better idea than borrow a new version of this functions from kernel, if this helps.

**Comment by adrianreber** [comment]
Thanks. I had a look but the linux kernel code has become much more complicated than the versions we have.

I tried to add `q` (64bit values) at the end of both assembler statements and that fails. Adding a `l` (32bit values) seems to work. Which probably makes sense as we are not dealing with 64bit values in both functions. Both are using `int`.

I will open a PR to see what CI things about it.

**Comment by rppt** [comment]
On Wed, Oct 7, 2020 at 4:34 PM Adrian Reber <notifications@github.com> wrote:
>
> Thanks. I had a look but the linux kernel code has become much more complicated than the versions we have.
>
> I tried to add q (64bit values) at the end of both assembler statements and that fails. Adding a l (32bit values) seems to work. Which probably makes sense as we are not dealing with 64bit values in both functions. Both are using int.

We are dealing with 64-bit values for the first argument of `bt` and `bts`, so I'd expect q suffix to work :/

I've tried to adopt the latest version from Linux and it compiles fine
on f31. Can you please check if f33 would be happy with this?

diff --git a/include/common/arch/x86/asm/bitops.h b/include/common/arch/x86/asm/bitops.h
index b60ead7fa..8a0bc5807 100644
--- a/include/common/arch/x86/asm/bitops.h
+++ b/include/common/arch/x86/asm/bitops.h
@@ -1,9 +1,18 @@
 #ifndef __CR_BITOPS_H__
 #define __CR_BITOPS_H__
 
+#include <stdbool.h>
 #include "common/arch/x86/asm/cmpxchg.h"
 #include "common/asm/bitsperlong.h"
 
+#ifdef __GCC_ASM_FLAG_OUTPUTS__
+# define CC_SET(c) "\n\t/* output condition code " #c "*/\n"
+# define CC_OUT(c) "=@cc" #c
+#else
+# define CC_SET(c) "\n\tset" #c " %[_cc_" #c "]\n"
+# define CC_OUT(c) [_cc_ ## c] "=qm"
+#endif
+
 #define DIV_ROUND_UP(n,d)	(((n) + (d) - 1) / (d))
 #define BITS_TO_LONGS(nr)	DIV_ROUND_UP(nr, BITS_PER_LONG)
 
@@ -30,14 +39,14 @@ static inline void change_bit(int nr, volatile unsigned long *addr)
 	asm volatile("btcl %1,%0" : ADDR : "Ir" (nr));
 }
 
-static inline int test_bit(int nr, volatile const unsigned long *addr)
+static inline bool test_bit(long nr, volatile const unsigned long *addr)
 {
-	int oldbit;
+	bool oldbit;
 
-	asm volatile("bt %2,%1\n\t"
-		     "sbb %0,%0"
-		     : "=r" (oldbit)
-		     : "m" (*(unsigned long *)addr), "Ir" (nr));
+	asm volatile("btq %2,%1"
+		     CC_SET(c)
+		     : CC_OUT(c) (oldbit)
+		     : "m" (*(unsigned long *)addr), "Ir" (nr) : "memory");
 
 	return oldbit;
 }
@@ -55,13 +64,14 @@ static inline void clear_bit(int nr, volatile unsigned long *addr)
  * This operation is atomic and cannot be reordered.
  * It also implies a memory barrier.
  */
-static inline int test_and_set_bit(int nr, volatile unsigned long *addr)
+static inline bool test_and_set_bit(int nr, volatile unsigned long *addr)
 {
-	int oldbit;
-
-	asm volatile(LOCK_PREFIX "bts %2,%1\n\t"
-		     "sbb %0,%0" : "=r" (oldbit), ADDR : "Ir" (nr) : "memory");
+	bool oldbit;
 
+	asm("btsq %2,%1"
+	    CC_SET(c)
+	    : CC_OUT(c) (oldbit), ADDR
+	    : "Ir" (nr) : "memory");
 	return oldbit;
 }
 

> I will open a PR to see what CI things about it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
Sincerely yours,
Mike.

**Comment by cyrillos** [comment]
I don't have fc33, but on fc32 it builds just fine, thanks!

**Comment by adrianreber** [comment]
@rppt That compiles without errors. Thanks. Will you submit the PR?
