### ISSUE TITLE
Gcov doesn't handle fork()-s

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#123]
It's seen, in particular, in namespaces.c check_user_ns()

**Comment by avagin** [comment]
Gcov handles fork()-s. I think the problem with permissions
[root@zdtm CRIU-x86_64-coverage]# ls -ld test/var/lib/jenkins/workspace/CRIU-x86_64-coverage/criu/
drwxr-xr-x. 4 root root 8192 Mar  4 03:22 test/var/lib/jenkins/workspace/CRIU-x86_64-coverage/criu/

A process from userns doesn't have enough permissions to write into this directory

**Comment by avagin** [comment]
We need to call umask 0000 before executing tests

**Comment by xemul** [comment]
It's not only about check_user_ns(). I'll revisit and get back with more examples.

**Comment by avagin** [comment]
Pls, use this link to find other examples:
https://ci.openvz.org/job/CRIU-coverage/ws/gcov/html/index.html
