### ISSUE TITLE
when trying to dump a program in a docker,i get some errors

### ISSUE THREAD

**Issue by z760284582** [checkpoint-restore/criu#1231]
command: ./criu/criu/criu dump -t `pidof hello` -D ch/ --shell-job
Error (criu/util.c:624): exited, status=3
Error (criu/util.c:624): exited, status=3
Warn  (criu/net.c:3166): Unable to get tun network namespace
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Error (criu/libnetlink.c:55): -45 reported by netlink: Operation not supported
Error (criu/net.c:3482): Unable to create a veth pair: -45
Warn  (criu/net.c:3508): NSID isn't reported for network links
Warn  (criu/net.c:3166): Unable to get socket network namespace
Warn  (criu/kerndat.c:877): Can't keep kdat cache on non-tempfs

**Comment by adrianreber** [comment]
How do you start your container and does the checkpointing actually work?

**Comment by z760284582** [comment]
docker run --runtime kata-runtime -it --device=/dev/net --cap-add=all --cap-add=NET_ADMIN zou:v2 /bin/bash

**Comment by z760284582** [comment]
the program is killed and Files (.img)are generated under the folder,but i'm not sure whether the files are generated completely, maybe i can compare with the normal files which are generated under the physical machine.

**Comment by adrianreber** [comment]
So it seems to work if you have image files. Just try to restore it.

The warnings and errors you see do not look fatal, but are more from the start of CRIU where it tries to test what your environment enables it to do.

If it would be a 'normal' container (not kata) I would say, run it with `--tmpfs  /run` to mount a tmpfs at /run which would enable CRIU to save its temporary file and most of the messages you see should go away.

**Comment by rppt** [comment]
We cannot checkpoint a kata container because it uses KVM and saving/restoring KVM state is not implemented in CRIU

**Comment by z760284582** [comment]
Running restore directly will report the following error, regardless of the same error as the previous dump report, does this seem to have no permissions? How can I give it permission to write... 

command: ./criu/criu/criu restore  -D ch/ --shell-job
Error (criu/util.c:624): exited, status=3
Error (criu/util.c:624): exited, status=3
Warn  (criu/net.c:3166): Unable to get tun network namespace
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Error (criu/libnetlink.c:55): -45 reported by netlink: Operation not supported
Error (criu/net.c:3482): Unable to create a veth pair: -45
Warn  (criu/net.c:3508): NSID isn't reported for network links
Warn  (criu/net.c:3166): Unable to get socket network namespace
Warn  (criu/kerndat.c:877): Can't keep kdat cache on non-tempfs
Error (criu/cr-restore.c:1352): Can't open -1/sys/kernel/ns_last_pid on procfs: Read-only file system
Error (criu/cr-restore.c:1477): Setting PID failedError (criu/cr-restore.c:2525): Restoring FAILED.

**Comment by z760284582** [comment]
not checkpoint a kata container but  use criu to save/restore program in the kata container, does it work?

> We cannot checkpoint a kata container because it uses KVM and saving/restoring KVM state is not implemented in CRIU

**Comment by adrianreber** [comment]
Using docker with `runc` instead of `kata-runtime` requires the flag `--privileged` to be able to run CRIU in the container. Does that also work with `kata-runtime`?

**Comment by z760284582** [comment]
like:docker run --runtime runc -it --privileged zou:v2 /bin/bash
it can save/restore normally, with a warn Warn (criu/kerndat.c:877): Can't keep kdat cache on non-tempfs.
so It's still the problem of kata.... 
Is there any way to add that permission to write...? maybe then it can restore ...

**Comment by adrianreber** [comment]
But that sounds like a problem you need to solve in kata. You need to figure what is necessary to let kata write to /proc/sys/kernel/ns_last_pid.

As this is not a CRIU problem I am closing this issue. There is nothing wrong with CRIU at this point.
