### ISSUE TITLE
Can't use --manage-cgroups option while dump

### ISSUE THREAD

**Issue by ashish-billore** [checkpoint-restore/criu#1236]
I am trying to use: --manage-cgroups full option during dump, like this:

`$ criu dump --manage-cgroups full -t 30985`

 However, I keep getting error:
`Error (criu/crtools.c:146): excessive parameter for command dump`

Setup Details:
$criu --version
Version: 3.14

$ runc --version
runc version spec: 1.0.1-dev

$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:    18.04
Codename:    bionic

$ uname -a
Linux sctpdev 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Context:

I am trying to use CGroups options mentioned here (It would be great if there were examples of how to use it on this page): 

https://criu.org/CGroups

for same scenario as suggested by @xemul here: https://github.com/checkpoint-restore/criu/issues/389#issuecomment-331156495

If I omit this option, I get different error like this:

$ criu dump -t 30985 
Error (criu/mount.c:938): mnt: Mount 405 ./sys/fs/cgroup/cpuset (master_id: 24 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
Error (criu/cr-dump.c:1764): Dumping FAILED.

Detailed log:
[Dump_log.txt](https://github.com/checkpoint-restore/criu/files/5384510/Dump_log.txt)

Can some body please suggest how to get past this error?

**Comment by adrianreber** [comment]
Are you trying to checkpoint a process out of a container. It looks like it from your log-file. That is not easily possible,

**Comment by ashish-billore** [comment]
@adrianreber Thanks for reverting back.
So, here's what I did:
1. Created a runc bundle, config.json is: 
[config.json.zip](https://github.com/checkpoint-restore/criu/files/5388714/config.json.zip)

2. rootfs and config.json were generated using a previous docker container, as suggested [here](http://crunchtools.com/getting-ninja-runc/)

3. Then checkpointing is attempted, by following commands (with output and logs), unfortunately, none succeeded:

With runc:

$ runc list
ID          PID         STATUS      BUNDLE            CREATED                          OWNER
tstserv1    30985       running     /root/criu_test   2020-10-15T10:18:53.032111514Z   root

$ runc checkpoint tstserv1
ERRO[0000] container is not destroyed                   
ERRO[0000] criu failed: type NOTIFY errno 0
log file: /run/runc/tstserv1/criu.work/dump.log 
criu failed: type NOTIFY errno 0
log file: /run/runc/tstserv1/criu.work/dump.log
$ 
log file is: 
[dump.log](https://github.com/checkpoint-restore/criu/files/5388764/dump.log)


$ runc --manage-cgroups-mode full checkpoint tstserv1
Incorrect Usage. flag provided but not defined: -manage-cgroups-mode
ERRO[0000] flag provided but not defined: -manage-cgroups-mode 
flag provided but not defined: -manage-cgroups-mode
--------
With criu:
Details as [above](https://github.com/checkpoint-restore/criu/issues/1236#issue-722256845)

---------
For reference here is the Dockerfile to create the docker image using which the runc bundle was created (I had to rename it, before attaching, to 'Dockerfile.txt' to get past github's file attachment restrictions):

[Dockerfile.txt](https://github.com/checkpoint-restore/criu/files/5388782/Dockerfile.txt)

---------

So, in short, here's what I trying:
1. checkpoint and restore a docker container with a userspace application which uses a raw socket. This app is [userspace sctp lib](https://github.com/sctplab/usrsctp) which I assume does not matter from criu perspective.

2. Using only [docker checkpoint ](https://criu.org/Docker) it checkpoints and restores fine and even the raw socket is restored. But it does not retain the traffic to connected clients on child or client sockets. I assumed this is due to some left out cgroup data which checkpoint as suggested by @xemul [here](https://github.com/checkpoint-restore/criu/issues/389#issuecomment-331156495)

3. So, in order to have the fine grained control over CGroups during checkpoint and restore, I tried using runc an criu directly as docker checkpoint does not provide these detailed command options, and while trying it with runc and criu I ran into above issue.

I'll glad to provide any more details, logs or info to help resolve this issue.

Thanks again for all the help!

**Comment by adrianreber** [comment]
I would say, from looking at your log-file, the problem is how you start your container with runc. stdout, stdin and stderr need to be disconnected from your processes and the checkpoint fails because of this: 
```(00.109167) Error (criu/files-reg.c:1372): Can't lookup mount=25 for fd=0 path=/dev/pts/5```

If trying to checkpoint on the runc level I am starting containers like this:
```runc run rhel7-httpd -b /runc/containers/rhel7-httpd/ -d &> /dev/null  < /dev/null```

Please retry it with the same input/output redirection.

**Comment by ashish-billore** [comment]
@adrianreber thanks for looking into it.

I used your recommendation: launching runc with `-d &> /dev/null < /dev/null` 
I also simplified the config.json to remove stuff which docker puts in and not needed.

With these changes, finally it worked :)

I am wondering if there any way to tell runc not to associate a terminal with the container or pass ` /dev/null ` in it's config.json, to avoid such issue, something like additional args:

```

"args": [
                        "sctplb_trial/testserver1"
                ],
```

I also referred to [runc terminal guide](https://github.com/opencontainers/runc/blob/master/docs/terminals.md), however, could not figure it out.

In case you may be aware of any such way to not associate terminal with runc container, please suggest.

Thanks again for all your help!

**Comment by adrianreber** [comment]
I am not aware of how to do it differently. It probably it is possible, but I do not know how. Good that it works. Can we close this ticket?

**Comment by ashish-billore** [comment]
Sure, not associate `stdout, stdin and stderr` with runc container is a separate issue, so I am closing this ticket.
Thanks!

**Comment by Snorch** [comment]
Side note about cgroups:

Using "--manage-cgroups" solely without also setting "--cgroup-root"-s and probably "--cgroup-dump-controller"-s to dump a container can sometimes bring unexpected results of processes moving to other cgroups. So please be careful with those.
