### ISSUE TITLE
criu docker checkpoint error 

### ISSUE THREAD

**Issue by z760284582** [checkpoint-restore/criu#1239]
Hi, when i'm using criu to run the  looper container example, i get some error 
host:ubuntu 18.04 , docker version 17.06.2-ce,criu version 3.12

docker run -d --name looper --security-opt seccomp:unconfined busybox  \
> /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 10); sleep 1; done'
docker checkpoint create looper checkpoint1

Error response from daemon: Cannot checkpoint container looper: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/65b0a5640cc6093bfd0a0aab5fe47a2b79be2fc5a9ee5c4c5dc85730265caf2a/checkpoints/checkpoint1/criu.work/dump.log\n"

dump.log:
(00.027986) Warn  (criu/image.c:134): Failed to open parent directory
(00.027990) ========================================
(00.027992) Dumping task (pid: 90916)
(00.027994) ========================================
(00.027996) Obtaining task stat ...
(00.028022)
(00.028025) Collecting mappings (pid: 90916)
(00.028027) ----------------------------------------
(00.028172) Error (criu/files-reg.c:1294): Can't lookup mount=819 for fd=-3 path=/bin/sh
(00.028185) Error (criu/cr-dump.c:1243): Collect mappings (pid: 90916) failed with -1
(00.028229) Unlock network
(00.028231) Running network-unlock scripts
(00.028233)     RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.036477) Unfreezing tasks into 1
(00.036496)     Unseizing 90916 into 1
(00.036514)     Unseizing 90963 into 1
(00.036544) Error (criu/cr-dump.c:1742): Dumping FAILED.
                                                                                                     
Thanks in advance!

**Comment by adrianreber** [comment]
This sounds a lot like https://github.com/checkpoint-restore/criu/issues/860. This is a Ubuntu kernel bug which is a result of carrying non-upstream kernel changes. Please complain at: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1857257

Possible solutions are to not use Ubuntu, use some other Linux distribution or switch to another graphdriver (devicemapper) like we do for our CI tests: https://github.com/checkpoint-restore/criu/blob/master/scripts/travis/Makefile#L22
