### ISSUE TITLE
cannot checkpoint a container running in different network namespace

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1245]
I'm trying to checkpoint a container running in a different network namespace, by creating a veth-pair in the host.

But criu fails to checkpoint the container.

[config.json](https://drive.google.com/file/d/1VdjTsLgEPOPX24MsgDrS6t1eXHYLzA9x/view?usp=sharing)
[dump.txt](https://drive.google.com/file/d/1r31fA9obZ9p9DYGjSTcHx2jSjjUVW-BE/view?usp=sharing)

**Comment by adrianreber** [comment]
This failure has nothing to do with networking:
```
(00.111199) Error (criu/mount.c:945): mnt: Mount 1811 ./sys/fs/fuse/connections (master_id: 32 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
```
Try to unmount that directory before starting the container and/or unload the `fuse` module.

**Comment by ashwani29** [comment]
and how to unmount this? If I remove the below section, it will unmount whole `/sys/` directory
```
		{
			"destination": "/sys",
			"type": "none",
			"source": "/sys",
			"options": [
				"rbind",
				"nosuid",
				"noexec",
				"nodev",
				"ro"
			]
		}
```

**Comment by adrianreber** [comment]
You have to remove `"rbind"` to not bind mount `/sys` from the host but use a `/sys` which is independent of the host.

**Comment by ashwani29** [comment]
It throws below error, but there is `sys` directory present inside `rootfs`
`ERRO[0000] container_linux.go:353: starting container process caused: process_linux.go:437: container init caused: rootfs_linux.go:58: mounting "/sys" to rootfs at "/home/user/FRC/rootfs/sys" caused: no such device`

**Comment by ashwani29** [comment]
changed `type` and `source` to `sysfs` then it thrown an error and suggested to use `--tcp-established`, did that too and now the error is this:
```
(00.340643) unix: Dumping external sockets
(00.340657) Error (criu/tty.c:2322): tty: ctty inheritance detected sid/pgrp 1, no PTY peer with sid/pgrp needed
(00.340992) FUNC NETWORK_UNLOCK============================(00.341009) Unlock network
(00.341048) FUNC RUNC SCRIPTS============================
(00.341057) Running network-unlock scripts
(00.341067) SCRIPTS MODE 2
(00.341075) ACTION IS network-unlock(00.341084) 	RPC
(00.341092) ACT IS 5(00.341362) FUNC SWITCH_NS=================================(00.341428) PID PROC IS 31037(00.341441) PID IS 31037, PROC_SELF IS 0, OPEN_PROC_PID IS 31037(00.341452) FD FOR GIVEN PID 31037 IS -1(00.341491) sfd: FUNC INSTALL_SERVICE_FD===============================
(00.341518) sfd: FUNC INSTALL_SERVICE_FD===============================
(00.341545) PID PROC IS 0(00.341554) PID IS 0, PROC_SELF IS 0, OPEN_PROC_PID IS 31037(00.341564) FD FOR GIVEN PID 0 IS -1(00.349580) Unfreezing tasks into 1
(00.349634) 	Unseizing 31037 into 1
(00.349663) 	Unseizing 31127 into 1
(00.349746) Error (criu/cr-dump.c:1753): Dumping FAILED.
```

**Comment by adrianreber** [comment]
Looking at your `config.json` it seems you are running an interactive shell in your container. That does not sound like a good idea to be used in combination with checkpoint and restore. Please run something else in your container. sleep for example. You also have to redirect stdin, stderr and stdout to /dev/null when using runc if you want to checkpoint and restore the container.
