### ISSUE TITLE
how to criu a socket connection to another container?

### ISSUE THREAD

**Issue by Jerrymarck** [checkpoint-restore/criu#1246]
I use a phone use socket build a connection with a container, but I want to criu the docker server froms host A to host B.
How can i  realize this migration?
I will be appreciated if I could get a little help.

**Comment by adrianreber** [comment]
Can you please rephrase. I am not sure I understand what you are trying to do? Did you already try something which failed. Can you share the commands you were using?

**Comment by Jerrymarck** [comment]
@adrianreber thanks for your apply
I build a video container based on nginx image, the user can connect the container and play the video.and I want to migrate the video container from PC A to PC B, but A and B hold different IP address, and the user should not be aware of migration. But the PC A and PC B hold different IP address ,so the migration is failed, I wonder how to fix this problem.
The execution environment are  Ubuntu16.04, docker version 19.03.13,  criu version 3.6, image nginx tag is latest.

**Comment by adrianreber** [comment]
IP addresses have to be the same for a working migration with established TCP connections.

This really depends on your container setup. The IP in the container can easily stay the same, but this still does not mean it will work if you do not have the correct IP setup before the container (bridges, NAT, whatever you do).
