### ISSUE TITLE
CRIU restore App with  openmpi  error 

### ISSUE THREAD

**Issue by Qinghe12** [checkpoint-restore/criu#1247]
#  ./criu restore  -j -D ./graph500-ckpt/  --tcp-established
 21713: Error (criu/files-reg.c:1831): Can't open file tmp/ompi.localhost.0/pid.21713/hwloc.sm on restore: No such file or directory
 21713: Error (criu/files-reg.c:1767): Can't open file tmp/ompi.localhost.0/pid.21713/hwloc.sm: No such file or directory
 21713: Error (criu/files.c:1210): Unable to open fd=20 id=0x58

Restore failed with log above！
It's looks like that the  file tmp/ompi.localhost.0/pid.21713/xxx would disappeared  when the process is over, which cause restore failed.

So How can i restore again successfully? Or is there any other suggestion to work around ?

**Comment by adrianreber** [comment]
To restore a process all files the process opened need to exist on the destination system or else the restore, like in your case, will fail. CRIU does not handle files during checkpoint/restore/migration. It is your responsibility to make sure the destination file-system has all files the process needs to run. In the simplest case you need to copy all open files from the checkpointed process to the same location during restore.

**Comment by Qinghe12** [comment]
@adrianreber  thanks for your replay 

Yes ,I can  backup omp/ompi.localhost.0/pid.21713 to destination file-system，while  new issue  happened with log following 
./criu restore  -j -D ./graph500-ckpt/  --tcp-established -d
 21823: Error (criu/files-reg.c:1831): Can't open file dev/shm/vader_segment.localhost.85ba0001.0 on restore: No such file or directory
 21823: Error (criu/files-reg.c:1767): Can't open file dev/shm/vader_segment.localhost.85ba0001.0: No such file or directory
 21823: Error (criu/mem.c:1383): `- Can't open vma
 21824: Error (criu/files-reg.c:1831): Can't open file dev/shm/vader_segment.localhost.85ba0001.1 on restore: No such file or directory
 21824: Error (criu/files-reg.c:1767): Can't open file dev/shm/vader_segment.localhost.85ba0001.1: No such file or directory

Ok.It's about shm,   So is it  possible  to get the file list for restoring process? then I can move to them to destination file-system in once.

**Comment by adrianreber** [comment]
You must understand how Open MPI works if you want to checkpoint Open MPI processes. What Open MPI does, it starts one main process and this process forks the actual copies (ranks) of the program you are trying to run. To be able to do MPI communication between the processes Open MPI sets up communication channels depending on your environment. Shared memory for processes on the same host or TCP or InfiniBand or whatever you have.

You cannot, without the help of Open MPI, checkpoint single ranks away from a running Open MPI process (easily). The main problem is, that all the communication channels need to be re-established after restore and the restored ranks need to be part of the Open MPI process tree again. That just as some background.

>  So is it possible to get the file list for restoring process?

You can look with `lsof` at all open files of the processes you want to migrate, but I doubt that this will work.

My recommendation would be to tell Open MPI to only use TCP for communication (`--mca btl ^self`) on the same host and not shared memory. That way you do not have to deal with problems about copying shared memory files. I am not sure that copying /dev/shm files from one host to another can work. No idea. You could try to copy all files from /dev/shm to the destination host.

Another solution would be to use a container. With Podman you can export a container with all its file-system changes from one host and import it on another host and thus it should be possible to easily migrate a complete Open MPI process tree.

**Comment by Qinghe12** [comment]
Thanks again,  i have tried it.
Copying /dev/shm files can solve the last problem.

New problem happend as following:

./criu restore  -j -D ./graph500-ckpt/  --tcp-established -d
 22595: Error (criu/cr-restore.c:1724): Pid 22677 do not match expected 22674
 22595: Error (criu/cr-restore.c:1477): 22677 exited, status=1
Error (criu/cr-restore.c:1479): 22595 killed by signal 9: Killed
Error (criu/cr-restore.c:2397): Restoring FAILED

PID collision , I have other issue about  this, I wonder whether criu-ns can fix this in a Physical Machine with os but  a container

**Comment by adrianreber** [comment]
I got an email with a new comment from you, but I do not see it here. Did you delete your comment? If the problem is solved, please close the ticket.

**Comment by Qinghe12** [comment]
yes, I have tried to copy all file it need ,and it works for me. It can restored  many time successfully in a same Physical Machine

While when migrating to Virtual Machine—qemu in the same Physical Machine ，another problem happened as following.. 

Could  you tell me what happened ? module missing in qemu？

-bash-4.3# ./criu-ns  restore  -j -D ./graph500-ckpt/ --tcp-established
['./criu-ns', 'restore', '-j', '-D', './graph500-ckpt/', '--tcp-established']
Error (criu/sockets.c:223): sockets: Diag module missing (-2)
Error (criu/sockets.c:223): sockets: Diag module missing (-2)
Error (criu/sockets.c:223): sockets: Diag module missing (-2)
Error (criu/util.c:618): exited, status=3
Error (criu/util.c:618): exited, status=3
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Error (criu/libnetlink.c:55): -95 reported by netlink: Operation not supported
Error (criu/net.c:3453): Unable to create a veth pair: -95

**Comment by adrianreber** [comment]
Running `podman container checkpoint` on a VM I see following diag modules being loaded:
```
raw_diag               16384  0
udp_diag               16384  0
tcp_diag               16384  0
inet_diag              24576  3 tcp_diag,raw_diag,udp_diag
netlink_diag           16384  0
af_packet_diag         16384  0
unix_diag              16384  0
```
