### ISSUE TITLE
Checkpoint fails in dind: Can't dump tmpfs content

### ISSUE THREAD

**Issue by ashish-billore** [checkpoint-restore/criu#1249]
Background:

I have prepared a [dind](https://hub.docker.com/_/docker) container ([version 20.10-rc](https://github.com/docker-library/docker/blob/b1d2628005e12e79079c025c3653cba248d6f264/20.10-rc/dind/Dockerfile)) with criu and verified the[ loop script example ](https://criu.org/Simple_loop)works fine:

```
~ # criu check
Error (criu/util.c:618): exited, status=1
Warn  (criu/net.c:3137): Unable to get tun network namespace
Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
Looks good.
~ #
~ # cat > test.sh <<-EOF
> #!/bin/sh
> while :; do
>     sleep 1
>     date
> done
> EOF
~ # chmod +x test.sh
~ # setsid ./test.sh  < /dev/null &> test.log &
~ # ps -ef | grep test.sh
14233 root      0:00 {test.sh} /bin/sh ./test.sh
14444 root      0:00 grep test.sh
~ # criu dump -t 14233 -vvv -o dump.log && echo OK
OK
~ #
```

-------------------------------------------------------------------------------
Version Info:
```
~/criubbx # runc --version
runc version 1.0.0-rc10
commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
spec: 1.0.1-dev
~/criubbx # criu --version
Version: 3.14
~/criubbx # uname -a
Linux sctpdev 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 Linux
~/criubbx #
```

------------------------------------------------------------------------------------
Now, I am trying to do Checkpoint and restore of a simple BusyBox container, inside this dind container, using runc which fails as:

```
~/criubbx # docker export $(docker create busybox) | tar -C rootfs -xvf -

~/criubbx # runc run criubbxtst -d &> /dev/null < /dev/null

~/criubbx # runc list
ID                    PID         STATUS      BUNDLE           CREATED                          OWNER
criubbxtst            0           stopped     /root/criubbx    2020-10-29T08:22:42.703854817Z   root
~/criubbx # 

~/criubbx # runc checkpoint --manage-cgroups-mode full --work-path . criubbxtst
ERRO[0000] container is not destroyed                   
ERRO[0000] criu failed: type NOTIFY errno 0
log file: dump.log 
criu failed: type NOTIFY errno 0
log file: dump.log
~/criubbx # 
```

Checkpoint logs indicate several errors:

```
(00.008067) Error (criu/util.c:618): exited, status=1
...
tar: unrecognized option: no-unquote
BusyBox v1.31.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file
...
(00.062828) Error (criu/util.c:618): exited, status=1
(00.062839) Error (criu/filesystems.c:435): Can't dump tmpfs content
(00.062893) Unlock network
(00.062899) Running network-unlock scripts
(00.062901) 	RPC
(00.068409) Unfreezing tasks into 1


(00.068418) 	Unseizing 11149 into 1
(00.068434) Error (criu/cr-dump.c:1764): Dumping FAILED.
```

Attached are the config and log files:

[config_json.txt](https://github.com/checkpoint-restore/criu/files/5457449/config_json.txt)

[dump_log.txt.zip](https://github.com/checkpoint-restore/criu/files/5457457/dump_log.txt.zip)

--------------------------------------------------------------------

Anyone clues to resolve this issue are welcome!

**Comment by adrianreber** [comment]
The tar executable in your setup from busybox cannot handle CRIU options. You need a real tar and not the one from busybox.

**Comment by ashish-billore** [comment]
@adrianreber Thanks for the info, I'll update that.
I am also curious about these errors and warnings from `criu check`:

```
~ # criu check
Error (criu/util.c:618): exited, status=1
Warn  (criu/net.c:3137): Unable to get tun network namespace
Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
Looks good.
~ #
```

I wonder if these may result in issues with restore or more complex container checkpoint/restore like dealing with sockets etc.
Any thought how I could resolve these check errors and warnings in dind?

**Comment by adrianreber** [comment]
The criu check messages do not sound problematic. Probably. I am not familiar with dind, so it might be a problem at some point. Not sure.

**Comment by rst0git** [comment]
@ashish-billore [moby](https://github.com/moby/moby) has a [Dockerfile](https://github.com/moby/moby/blob/bb23f1bf61cb49c5aa3f7df934d79c305afb7c8c/Dockerfile#L21) with pre-installed CRIU that is used as a [development environment](https://github.com/moby/moby/blob/87e7930892e5d0b3b5d3c17ad1fad793ed6e1c0e/docs/contributing/set-up-dev-env.md#task-2-start-a-development-container).
Docker-in-Docker with CRIU might be something similar.

**Comment by ashish-billore** [comment]
> The tar executable in your setup from busybox cannot handle CRIU options. You need a real tar and not the one from busybox.
@adrianreber 
Indeed the issue was with the default tar package in dind's Alpine base image. After updating it, things worked fine :+1: 
I'll close this issue. thank!

@rst0git Thanks for the useful info, I'll create my custom image with the moby's Dockerfile as reference.

**Comment by MihaelBercic** [comment]
@ashish-billore could you perhaps help me understand how exactly did you update / replace it?

Thank you.

**Comment by MihaelBercic** [comment]
> The tar executable in your setup from busybox cannot handle CRIU options. You need a real tar and not the one from busybox.

@adrianreber may i ask for some tips in regards how to obtain and replace it?

Thank you

**Comment by adrianreber** [comment]
> > The tar executable in your setup from busybox cannot handle CRIU options. You need a real tar and not the one from busybox.
> 
> @adrianreber may i ask for some tips in regards how to obtain and replace it?
> 
> Thank you

No idea. That depends on your distribution. Just install tar so that not the one from busybox is used.

**Comment by MihaelBercic** [comment]
> > > The tar executable in your setup from busybox cannot handle CRIU options. You need a real tar and not the one from busybox.
> > 
> > @adrianreber may i ask for some tips in regards how to obtain and replace it?
> > 
> > Thank you
> 
> No idea. That depends on your distribution. Just install tar so that not the one from busybox is used.

Okay thank you.
And we're talking about criu tar right?

I'm a little bit confused so clarification is very much appreciated.

Thank you

**Comment by adrianreber** [comment]
No. You need a version of tar. CRIU uses it to  archive mounted tmpfs. Just the default tar.

**Comment by MihaelBercic** [comment]
> No. You need a version of tar. CRIU uses it to archive mounted tmpfs. Just the default tar.

Thank you very very much, you helped me understand and fix a very important issue.

**Comment by adrianreber** [comment]
> > No. You need a version of tar. CRIU uses it to archive mounted tmpfs. Just the default tar.
> 
> Thank you very very much, you helped me understand and fix a very important issue.

If you have any more questions please open a new issue and we can help you there.
