### ISSUE TITLE
Restore fails because output file is bigger than when checkpoint taken

### ISSUE THREAD

**Issue by efluder** [checkpoint-restore/criu#1258]
Ran into this problem on restore of a test LSF job:
455439: Error (criu/files-reg.c:1702): File hpc/users/fludee01/TEST_PGMS/checkpoint/serial/myout.txt has bad size 25195 (expect 16965)
455439: Error (criu/files.c:1196): Unable to open fd=3 id=0x7

myout.txt is an output file and was added to by the program after the checkpoint was taken. I expected it to just be rolled back to the point of the checkpoint and then for the program to continue on from there recomputing the lost output.
I feel there is an option needed but I can't seem to find it. I see similar problems but they are with Docker and involve the binary program file.
Any help?
Thanks
Gene

**Comment by adrianreber** [comment]
CRIU does not touch any of the files involved. It is your responsibility to make sure the files during restore are **exactly** the same as during checkpointing. If any file does not have the same size and mode CRIU will not do the restore. In the case of log-files, like you have here, it would probably not hurt to just continue writing to the file even if the size has changed. But usually, if a file size has changed, and the process wants to read something from it, it should be the same file.

So, no there is nothing you can do about it. You could, maybe, have a look at the checkpoint image file, figure out the size of the file, and recreate the file with the size CRIU expects.

**Comment by adrianreber** [comment]
Closing this as it is expected behaviour. Please re-open if you have additional questions.

**Comment by Snorch** [comment]
Note probably docker (overlay) should provide kind of fs-checkpoints, and you should use them along side with criu. Note: to have criu dump consistent with fs snapshots you should create them on paused container, it should be posible via freezer cgroup.
