### ISSUE TITLE
Failed Dependency Installing from Source

### ISSUE THREAD

**Issue by bindatype** [checkpoint-restore/criu#1259]
I'm attempting to install CRIU-3.14 from source and built the latest branch of protobuf but protoc-c and protoc-gen-c are not in the resulting bin directory. I'm sure I'm missing something simple but not sure what that is. Any guidance would be greatly appreciated.

**Comment by adrianreber** [comment]
This sounds more like a protobuf-c problem. Not really sure how to help you.

**Comment by 0x7f454c46** [comment]
protoc is a separate from protobuf project: https://github.com/protobuf-c/protobuf-c

**Comment by rst0git** [comment]
https://criu.org/Installation#Installing_build_dependencies

**Comment by adrianreber** [comment]
I am closing this as it does not seem like a CRIU problem. Please re-open if necessary.
