### ISSUE TITLE
restoring client's connection on backup side.

### ISSUE THREAD

**Issue by ashwani29** [checkpoint-restore/criu#1260]
I have a server running in a `runc` container, and the client is connected to that server.  I can successfully checkpoint the running container and migrate it to the backup destination, but when I'm restoring it, it doesn't successfully restore. It throws the below error (shown some part from last):

```
(00.403586)      1: Restoring resources
(00.403596)      1: Opening fdinfo-s
(00.403604)      1: tty: open driver pts id 0x7 index 0 (master 0 sid 1 pgrp 1 inherit 1)
(00.403608)      1: tty: Allocating fake descriptor for 0x7 (reg_d 0x7ff990abc828)
(00.403624)      1: 	RPC
(00.403936)      1: 		Create fd for 0
(00.403946)      1: 			Going to dup 0 into 1
(00.403951)      1: 			Going to dup 0 into 2
(00.403954)      1: 			Going to dup 0 into 1020
(00.403959)      1: 	Receive fd for 1
(00.403962)      1: 	Receive fd for 2
(00.403974)      1: 	Restore: family 2 type 1 proto 6 port 8092 state 10 src_addr 0.0.0.0
(00.404125)      1: 3 restore sndbuf 16384 rcv buf 131072
(00.404138)      1: 	restore priority 0 for socket
(00.404142)      1: 	restore rcvlowat 1 for socket
(00.404146)      1: 	restore mark 0 for socket
(00.404153)      1: 		Create fd for 3
(00.404159)      1: 	Restore: family 2 type 1 proto 6 port 8092 state 1 src_addr 192.168.10.1
(00.404177)      1: Restoring TCP connection
(00.404187)      1: Restoring TCP connection id a ino 2f220
(00.404283)      1: Error (criu/files.c:1191): Unable to open fd=4 id=0xa
(00.423793) mnt: Switching to new ns to clean ghosts
(00.424058) Error (criu/cr-restore.c:2171): Restoring FAILED.
```
command i used for restoring container: `sudo runc restore --tcp-established --work-path log/ FRC`
After the source container fails, the client's connection is closed on the source, so how will I make sure that the client's connection is restored at the destination side from the committed state, i.e. checkpointed state?

**Comment by ashwani29** [comment]
UPD: The server is running in a different network namespace. 
and @adrianreber  did you got prompted for password input when trying to `rsync` the checkpoint to the destination I this script: https://people.redhat.com/areber/criu/migrate
because the checkpoint folder contains `descriptor.json` file which is permission protected so when I use `rsync` without `sudo` it throws error of permission denied.

**Comment by adrianreber** [comment]
I was running everything as root and never used sudo.

**Comment by ashwani29** [comment]
So you have never had to enter the destination password too while rsyncing?

**Comment by adrianreber** [comment]
No, you just need to exchange ssh keys also for the root user and it will work.

**Comment by ashwani29** [comment]
I've a custom client of request and a simple text-based response, the basic idea to keep the client connected is just to move the IP address of the server to the destination and of course, the client should not close once the server at source fails, it will retry until the destination server starts right? that's what the basic idea is behind keeping alive xonotic's client connection?

**Comment by adrianreber** [comment]
> I've a custom client of request and a simple text-based response, the basic idea to keep the client connected is just to move the IP address of the server to the destination and of course, the client should not close once the server at source fails, it will retry until the destination server starts right? that's what the basic idea is behind keeping alive xonotic's client connection?

Not sure I understand your setup, but if your client tries to connect to the server IP while the process is being moved and if it is TCP, you might get a reset from the server if the process has not been restored. You can use iptables to drop any incoming packets during the migration to make sure your connection is not reset during the migration downtime.

**Comment by ashwani29** [comment]
Ok, thanks, now I've corrected it (now I'm able to `rsync` `descriptors.josn` file without prompting for password input, I used a passwordless `sudo` script). can you please look into why the above restore is not working?

**Comment by rst0git** [comment]
@ashwani29 could you please share the full restore log file?

**Comment by ashwani29** [comment]
yes sure @rst0git, [restore.txt](https://drive.google.com/file/d/1KdJCnM-EnZtT3Qs6d6ArcoFWJJCOVAko/view?usp=sharing)

**Comment by rst0git** [comment]
Hi @ashwani29, the logs correspond to CRIU version 3.8.1 or earlier. It might be worth trying with a more recent version of CRIU.

**Comment by ashwani29** [comment]
On my system it is showing 3.14

**Comment by rst0git** [comment]
Hmm, inferred (guessed) the version based on the line numbers showed in logs:

[`Error (criu/files.c:1191): Unable to open fd=4 id=0xa`](https://github.com/checkpoint-restore/criu/blob/086df7e5709f5c09c79647abced914388c80de2b/criu/files.c#L1191)

[`Error (criu/cr-restore.c:2171): Restoring FAILED.`](https://github.com/checkpoint-restore/criu/blob/086df7e5709f5c09c79647abced914388c80de2b/criu/cr-restore.c#L2171)

In 3.14, these error messages have different lines in the source code.

**Comment by ashwani29** [comment]
Deeply sorry for this, I'm restoring the container on a VM and I didn't check the version on VM, 3.14 is on the host from which I'm sending the files to VM. let me check and run a  recent version on that VM.

**Comment by ashwani29** [comment]
whenever i' running make for criu version 3.14 it throws the error of :
```
In file included from criu/cgroup.c:29:0:
criu/include/linux/mount.h:8:10: fatal error: linux/mount.h: No such file or directory
 #include <linux/mount.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

I've checked multiple times this file is present in `criu/include/linux/` directory, still, it is giving the same error again and again. 
Some help here pls.

**Comment by ashwani29** [comment]
Hi @rst0git I updated the criu version to 3.14 on my VM. the problem was actually the mount.h file was not present in the Linux directory in the kernel so I copied the host's one to the VM. 
the new restore logs are here, 

[restore.log](https://github.com/checkpoint-restore/criu/files/5507931/restore.log)

**Comment by ashwani29** [comment]
found anything?

**Comment by adrianreber** [comment]
That seems to be another error:
```
(00.099231)      1: Error (criu/sk-inet.c:849): inet: Connected TCP socket in image
```
Looking at the code this message should be seen when running without `--tcp-established`.

**Comment by ashwani29** [comment]
Sorry again, i'm making so many mistakes right now :) . let me try it with correct command.

**Comment by ashwani29** [comment]
Restore log after running command `sudo runc restore --tcp-established --work-path log/ <container_name>`


[restore.txt](https://github.com/checkpoint-restore/criu/files/5513006/restore.txt)

**Comment by rst0git** [comment]
```
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
```
You should be able to fix this by updating iptables to 1.6.2+

**Comment by ashwani29** [comment]
Still same error, i updated the `iptables` to version `1.6.2`, now it is not showing such statement in the logs. but it throws error for
 the same line. :
`(01.012320) Error (criu/cr-restore.c:1480): 11953 killed by signal 127: Unknown signal 127`

[restore.txt](https://github.com/checkpoint-restore/criu/files/5515099/restore.txt)

**Comment by ashwani29** [comment]
I still couldn't figure out. @adrianreber help here.

**Comment by rst0git** [comment]
```
(01.011889) pie: 1: vdso: Parsing at 0x7ffef8976000 0x7ffef8977000
(01.011901) pie: 1: vdso: PT_LOAD p_vaddr: 0x0
(01.011912) pie: 1: vdso: DT_HASH: 0x120
(01.011922) pie: 1: vdso: DT_STRTAB: 0x2d8
(01.011932) pie: 1: vdso: DT_SYMTAB: 0x1b8
(01.011941) pie: 1: vdso: DT_STRSZ: 0x72
(01.011987) pie: 1: vdso: DT_SYMENT: 0x18
(01.011997) pie: 1: vdso: nbucket 0x3 nchain 0xc bucket 0x7ffef8976128 chain 0x7ffef8976134
(01.012013) pie: 1: vdso: image [vdso] 0x7ffef8976000-0x7ffef8977000 [vvar] 0x7ffef8973000-0x7ffef8976000
(01.012320) Error (criu/cr-restore.c:1480): 11953 killed by signal 127: Unknown signal 127
(01.039276) mnt: Switching to new ns to clean ghosts
(01.041873) Error (criu/cr-restore.c:2397): Restoring FAILED.
```

@0x7f454c46 any ideas what could be the reason for this error?

**Comment by ashwani29** [comment]
@rst0git Some information about the scenario, might help @0x7f454c46 . I'm running the container in a network namespace on source host, this container is hosting a simple CPP server application, taken a checkpoint and migrated to another host, on destination host the network namespace is available and so is defined in the `config.json` of the container to be restored. 
But on restore it fails.

**Comment by ashwani29** [comment]
One more update, **restoring on the same host is working**, I mean on restore server is successfully running and if I start the client again, it is able to send requests and receive responses but from the initial state again. so how to make sure that the client's connection is restored from the state where it was disrupted.

**Comment by adrianreber** [comment]
Just a guess as the last message is about vdso, what Kernel versions are running on both hosts? Please share the checkpoint log file as well.

**Comment by ashwani29** [comment]
Sure here it is, 
[dump.txt](https://github.com/checkpoint-restore/criu/files/5519832/dump.txt)

**Comment by adrianreber** [comment]
If it is a VDSO problem @0x7f454c46 should probably now. One thing you can try, is to run the same version of the kernel on both systems.

**Comment by ashwani29** [comment]
Ok trying now, and any idea about how to preserve the client's connection after migrating to the destination, i.e. its state should also be restored from where it was disrupted.  right now the client connection closes once I kill the container on the source host.

**Comment by rst0git** [comment]
@ashwani29 the error may occur because you're migrating a container from an older kernel (`5.3.0-64-generic`) to a newer one (`5.4.0-52-generic`).

**Comment by 0x7f454c46** [comment]
Yeah, I'm not sure yet the problem here is in vdso. It can be, but let's see.
`Error (criu/cr-restore.c:1480): 11953 killed by signal 127: Unknown signal 127`
from
```
               exit = WIFEXITED(status);
               status = exit ? WEXITSTATUS(status) : WTERMSIG(status);
```
where `#define	__WTERMSIG(status)	((status) & 0x7f)`
`127` is `0x7f`, so the actual thing that happened was:
`#define	__WIFSTOPPED(status)	(((status) & 0xff) == 0x7f)`
The root task was stopped by received signal `WSTOPSIG()`.
Unfortunately, from the log it's impossible to tell which signal stopped the root task.
@ashwani29, could you apply and run the same restore with this patch?
https://github.com/0x7f454c46/criu/commit/914cb97aab7be5c45789ca4f826161478dedfd63
It will show what signal stopped the root task that's being restored.
It can be vdso issue or it just received a signal while restoring it.
Vdso image seems to match on restore, so it seems to be pretty simple restore that we test a lot.

**Comment by ashwani29** [comment]
Hi, sorry for late reply, was busy in something. I tried building the same kernel on the destination side too, restore still failing, this is the log file : 
[restore_changed_kernel.txt](https://github.com/checkpoint-restore/criu/files/5525625/restore_changed_kernel.txt) 

I tried the patch too as suggested by @0x7f454c46 this is the log file : [restore_patched.txt](https://github.com/checkpoint-restore/criu/files/5525633/restore_patched.txt)

**Comment by adrianreber** [comment]
```
(00.458736)      1: Error (criu/mount.c:2012): mnt: Unable to mount tmpfs /tmp/.criu.mntns.OhP8BG/13-0000000000/proc/asound (id=1973): No such file or directory
(00.458763)      1: Error (criu/mount.c:2077): mnt: Can't mount at /tmp/.criu.mntns.OhP8BG/13-0000000000/proc/asound: No such file or directory
```
Now you have problems because on one machine the also modules are loaded and not on the other. See #1240 for the same error. Possible solutions are unloading the corresponding modules or removing the masked path from `config.json`.

**Comment by ashwani29** [comment]
Now giving segmentation fault: 
[restore.log](https://github.com/checkpoint-restore/criu/files/5526274/restore.log)

**Comment by 0x7f454c46** [comment]
@ashwani29 yes, that's better.
Could you run with this debugging patch on the top to have some more logs?
https://github.com/0x7f454c46/criu/commit/60dd13351fe945ec09b0430644367d11050ba611
Thanks!

**Comment by ashwani29** [comment]
Hi, your last patch contained a header `image-streamer.h`, so when I replaced the `criu_restore.c` file with the file which contained the patch, it was giving make errors, for the above header file. So when you say, apply the patch do you mean that just change code statements where there are changes?. Only then it worked last time.

**Comment by 0x7f454c46** [comment]
I've rebased those two commits on the criu v3.14 that you use:
https://github.com/0x7f454c46/criu/commits/issue/1260

**Comment by 0x7f454c46** [comment]
You can do:
```
git add remote dima https://github.com/0x7f454c46/criu.git
git fetch dima
git cherry-pick v3.14..dima/issue/1260
```
To take those changes into your current git branch.

**Comment by ashwani29** [comment]
[restore.log](https://github.com/checkpoint-restore/criu/files/5526592/restore.log) after applying the vdso patch

**Comment by 0x7f454c46** [comment]
Yes, that what I've suspected.
I think, you can cherry-pick the last patch, it should help:
https://github.com/0x7f454c46/criu/commits/issue/1260

**Comment by ashwani29** [comment]
still same error: 
[Uploading restore.log…]()

**Comment by 0x7f454c46** [comment]
Hmm, are you sure that you have rebuilt criu after applying the patch?
If so, you can run with this: https://github.com/0x7f454c46/criu/commit/645015d54e28037ddb472f01fc58a8148f5a4b16
But I'm pretty sure the last one should have solved it for you..

**Comment by ashwani29** [comment]
yes i did, `make clean`, `make` and `sudo make install`.
New [restore.log](https://github.com/checkpoint-restore/criu/files/5526951/restore.log)

**Comment by 0x7f454c46** [comment]
Thanks!
I reproduced it by moving printing. It seems there is an issue in compel logger..
Please, run with this patch instead, it should help:
https://github.com/0x7f454c46/criu/commit/aece1286f808ca0552ffaa08bbc5ef742dbd6c08
while I'll fix it properly in logger.

**Comment by 0x7f454c46** [comment]
A proper fix for this in https://github.com/checkpoint-restore/criu/pull/1271

**Comment by ashwani29** [comment]
Sorry for the late reply. very very thanks @0x7f454c46  finally it worked.

**Comment by ashwani29** [comment]
closing this issue and thanks to everyone.

**Comment by gitsvm** [comment]
> I was running everything as root and never used sudo.

@adrianreber  do you mean you were running rootless container?
