### ISSUE TITLE
pid_reuse.c:107: Task 11235 died with exit status 100 (errno = 9 (Bad file descriptor))

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#1266]
```
# python test/zdtm.py run -t zdtm/transition/pid_reuse --pre 1 -f h
mem_dirty_track is supported
userns is supported
=== Run 1/1 ================ zdtm/transition/pid_reuse
====================== Run zdtm/transition/pid_reuse in h ======================
Start test
Test is SUID
./pid_reuse --pidfile=pid_reuse.pid --outfile=pid_reuse.out
Run criu pre-dump
Send pre-dump notify to 48
Wait pre-dump notify reply
Completed pre-dump notify with 0
Run criu dump
=[log]=> dump/zdtm/transition/pid_reuse/48/2/dump.log
------------------------ grep Error ------------------------
b'(00.003708) Dumping memfd:/dev/zero contents (id 0x1, shmid: 0xda, size: 4096)'
b'(00.003716) page-pipe: Create page pipe for 1 segs'
b'(00.003721) page-pipe: Will grow page pipe (iov off is 0)'
b'(00.003788) No pagemap-shmem-218.img image'
b'(00.003799) Error (criu/page-xfer.c:401): page-xfer: No parent image found, though parent directory is set: No such file or directory'
------------------------ ERROR OVER ------------------------
Run criu restore
Send the 15 signal to  48
Wait for zdtm/transition/pid_reuse(48) to die for 0.100000
############# Test zdtm/transition/pid_reuse FAIL at result check ##############
Test output: ================================
23:34:25.643:    48: ERR: test.c:378: pre-dump
23:34:25.644:    48: ERR: test.c:392: pre-dump-ack
23:34:25.684: 11235: ERR: pid_reuse.c:74: Wrong value in a variable after restore
23:34:25.685:    48: FAIL: pid_reuse.c:107: Task 11235 died with exit status 100 (errno = 9 (Bad file descriptor))

 <<< ================================
##################################### FAIL #####################################

```

**Comment by avagin** [comment]
This is due to time namespaces. /proc/uptime is taking into account a time namespace offset, but start_time in /proc/pid/stat isn't.

**Comment by avagin** [comment]
I think it will be fixed by https://lkml.org/lkml/2020/10/27/3740

**Comment by Snorch** [comment]
Thanks for assigning! I will take a look!

ps: sorry for a late responce but for 3 last weeks I was too deep in rebasing vzcriu to v3.15.

**Comment by Snorch** [comment]
> This is due to time namespaces. /proc/uptime is taking into account a time namespace offset, but start_time in /proc/pid/stat isn't.

Why do we run criu in time-namespace in the first place? Probably some tricky tests to simulate big time intervals between checkpoint and restore? Can you please remind me.

Pid-reuse detection technic relies on the fact that starttime and uptime we read from criu context are consistent between each other. So if they are not consistent all is bad...

**Comment by Snorch** [comment]
The commit which introduced running criu in time namespace:
0d8c0562f ("zdtm_ct: run each test in a new time namespace")
Note that fixup is needed to actually reproduce:
c83a0aae2 ("proc: parse clock symbolic names in /proc/pid/timens_offsets")

Before this commit we have (note: pstree needs additional patch to show timens difference with "-S" https://gitlab.com/psmisc/psmisc/-/merge_requests/25/commits):
```
pstree -Spl 710059
python(710059)───zdtm_ct(718016,ipc,mnt,net)───python(718017,pid)─┬─pid_reuse(718061)───pid_reuse(718062)
                                                                  └─python(718020)───criu(718063)
```

After this commit criu runs from time namespace:

```
pstree -Spl 688968
python(688968)───zdtm_ct(688979,ipc,mnt,net)───python(688980,pid,time)─┬─pid_reuse(689023)───pid_reuse(689024)
                                                                       └─python(688982)───criu(689025)
```

**Comment by avagin** [comment]
@Snorch I reassigned it to you before I've investigated it. It should be okay to run CRIU in a time namespace and we need to do that to catch this sort of bugs.
