### ISSUE TITLE
Restore error for lsm profile

### ISSUE THREAD

**Issue by Qinghe12** [checkpoint-restore/criu#1267]
Restore error for lsm profile....

Is it necessary to check this？ Or how to work around? thanks

(14.067330) 47750: Opening 0x00fffface42000-0x00ffffad243000 0000000000000000 (81) vma
(14.067469) 47737: sockets: restore priority 0 for socket
(14.067795) 47745: Opening 0x00ffff8807d000-0x00ffff8807e000 0x00000000016000 (41) vma
(14.068220) 47751: Opening 0x00ffff9aeb7000-0x00ffff9aeb8000 0x0000000001e000 (41) vma
(14.068759) 47748: Error (criu/lsm.c:279): mismatched lsm types and lsm profile specified
(14.069061) 47752: Opening 0x00ffff996fb000-0x00ffff996fc000 0x00000000002000 (41) vma
(14.069471) 47746: Opening 0x00ffffa5068000-0x00ffffa506a000 0x0000000001e000 (41) vma

**Comment by adrianreber** [comment]
And now we need to know what you are exactly trying to do. CRIU claims `mismatched lsm types and lsm profile specified`. Did you specify a LSM profile. It this a SELinux or AppArmor system. If you open a ticket you need to give us some more information than just a few lines of output.

**Comment by Qinghe12** [comment]
I'm trying to restore a mpi application (graph500) in qemu with a  exist checkpoint dump as following：

./criu dump -D ./graph500-ckpt/ -j --tcp-established -t  ${PID}
./criu restore -D ./graph500-ckpt/ -j --tcp-established

I  did not specify LSM profile .  
SELINUX has been disabled in kernel  with "CONFIG_SECURITY_SELINUX is not set"

Could you tell  how to debug or any other information  you need?  thanks

**Comment by adrianreber** [comment]
So, this is strange and requires more information. Which kernel? Which distribution? We also need to see full log files.

If you do `crit show core-PID.img` you should see if some LSM information is included in the checkpoint. On a SELinux system I see: `"lsm_profile": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023"`

**Comment by Qinghe12** [comment]
I have unified the filesystem in physical machine and qemu，

**Comment by rahulk789** [comment]
@Qinghe12 May I know what fixed this issue?
