### ISSUE TITLE
Pid do not match expected, but clone3 support

### ISSUE THREAD

**Issue by mwerensteijn** [checkpoint-restore/criu#1268]
Hi all,

I have cross compiled CRIU for arm64 Linux and it survives all checks and dumps a process succesfully.
When I try to restore a checkpoint it fails to get the proper pid:
```
$ ../criu restore --shell-job -v4
(00.000646) Version: 3.14 (gitid v3.14-18-g1763a2fb)
(00.001655) Running on buildroot Linux 5.5.0-g5973cd5de-dirty #10 SMP PREEMPT Mon Nov 9 15:32:45 CET 2020 aarch64
(00.003491) Loaded kdat cache from /run/criu.kdat
(00.004110) rlimit: RLIMIT_NOFILE unlimited for self
(00.021583) kernel pid_max=32768
(00.039959) Reading image tree
(00.067149) Add mnt ns 6 pid 302
(00.067690) Add net ns 2 pid 302
(00.068914) pstree pid_max=302
(00.069594) Migrating process tree (SID 291->291)
(00.070727) Will restore in 0 namespaces
(00.071286) NS mask to use 0
(00.072867) Collecting 49/56 (flags 3)
(00.073850) No memfd.img image
(00.086368)  `- ... done
(00.086734) Collecting 39/54 (flags 2)
(00.088376) Collected [tmp/loop2] ID 0x1
(00.089043) Collected [dev/ttyAMA0] ID 0x3
(00.090437) Collected [tmp/test] ID 0x4
(00.092359) Collected [.] ID 0x5
(00.094791)  `- ... done
(00.096294) Collecting 45/62 (flags 0)
(00.110403) No remap-fpath.img image
(00.110931)  `- ... done
(00.112142) No cgroup.img image
(00.113940) Running pre-restore scripts
(00.128871) Forking task with 302 pid (flags 0x0)
(00.140143) Creating process using clone3()
(00.218202) PID: real 302 virt 302
(00.221390) Error (criu/cr-restore.c:1724): Pid 329 do not match expected 302
(00.262508) Error (criu/cr-restore.c:1477): 302 exited, status=1
(00.280335) Error (criu/cr-restore.c:2397): Restoring FAILED.
```

I have compiled the linux kernel with the correct CONFIG parameters so clone3 is available. 
I cannot seem to find out why it cannot get the correct pid.
I have tried to manually set the pid - 1 in /proc/sys/kernel/ns_last_pid, but then the output is:
```
$ ../criu restore --shell-job -v4
(00.000569) Version: 3.14 (gitid v3.14-18-g1763a2fb)
(00.007773) Running on buildroot Linux 5.5.0-g5973cd5de-dirty #10 SMP PREEMPT Mon Nov 9 15:32:45 CET 2020 aarch64
(00.042176) Loaded kdat cache from /run/criu.kdat
(00.047362) rlimit: RLIMIT_NOFILE unlimited for self
(00.077630) kernel pid_max=32768
(00.084568) Reading image tree
(00.091698) Add mnt ns 6 pid 302
(00.094321) Add net ns 2 pid 302
(00.103867) pstree pid_max=302
(00.107230) Migrating process tree (SID 291->291)
(00.110089) Will restore in 0 namespaces
(00.111942) NS mask to use 0
(00.115393) Collecting 49/56 (flags 3)
(00.118160) No memfd.img image
(00.119737)  `- ... done
(00.122079) Collecting 39/54 (flags 2)
(00.153444) Collected [tmp/loop2] ID 0x1
(00.154056) Collected [dev/ttyAMA0] ID 0x3
(00.154937) Collected [tmp/test] ID 0x4
(00.155429) Collected [.] ID 0x5
(00.158703)  `- ... done
(00.160040) Collecting 45/62 (flags 0)
(00.167821) No remap-fpath.img image
(00.170375)  `- ... done
(00.172531) No cgroup.img image
(00.176526) Running pre-restore scripts
(00.188663) Forking task with 302 pid (flags 0x0)
(00.192884) Creating process using clone3()
(00.232601) Error (criu/cr-restore.c:1433): Can't fork for 302: File exists
(00.242795) Error (criu/cr-restore.c:2397): Restoring FAILED.
```

It is a very bare version of the linux kernel in QEMU so I do not have python to test criu-ns.
But from my understanding criu-ns does not do anything differently than modifying ns_last_pid.

Does anybody have an idea where to look?

Kind regards,
Mitchell Werensteijn

**Comment by adrianreber** [comment]
Interesting. Especially the first case. The second log, looks like the process with the PID 302 already exists and CRIU just stops. That seems correct. The first log is the interesting one, because the expectation is that clone3() just fails if the PID is already in use and create a process with a wrong PID (329).

I do not understand:
> I have tried to manually set the pid - 1 in /proc/sys/kernel/ns_last_pid, but then the output is:

This does not change anything because CRIU still uses clone3() in your case.

Anyway, is the PID 302 available when you try to restore the process?

**Comment by mwerensteijn** [comment]
In the first case PID 302 is available. 

In the second case the PID is also available but I manually set ns_last_pid to 301 so that the next PID when I call ../criu restore will be 302. I think that is expected then as Criu itself will have PID 302 and its child should get that PID.

**Comment by mwerensteijn** [comment]
Will do! Thanks for all the help sofar

**Comment by mwerensteijn** [comment]
Thanks so much @adrianreber , version 3.15 is working like a charm!
Been bumping my head on this all day, but I can succesfully restore now.

Thanks for your help and time!
