### ISSUE TITLE
target process failed to start after  criu-ns restore  with “-d” 

### ISSUE THREAD

**Issue by Qinghe12** [checkpoint-restore/criu#1278]
I used criu-ns to restore with "-d", while target process didnot restart  after criu detach  as  follwing log.

#./criu-ns  restore  -j -D ./graph500-ckpt/ --tcp-established -d -v4

Whether criu-ns  cannot work with "-d"?

(01.380027) 73655 (native) is going to execute the syscall 215, required is 215
(01.380061) 73655 was stopped
(01.380087) 73647 was trapped
(01.380092) 73647 (native) is going to execute the syscall 215, required is 215
(01.380127) 73647 was stopped
(01.380153) 73636 was trapped
(01.380159) 73636 (native) is going to execute the syscall 215, required is 215
(01.380192) 73636 was stopped
(01.380218) 73625 was trapped
(01.380223) 73625 (native) is going to execute the syscall 215, required is 215
(01.380256) 73625 was stopped
(01.380282) 73615 was trapped
(01.380288) 73615 (native) is going to execute the syscall 215, required is 215
(01.380319) 73615 was stopped
(01.380345) 73607 was trapped
(01.380350) 73607 (native) is going to execute the syscall 215, required is 215
(01.380384) 73607 was stopped
(01.380408) 73605 was trapped
(01.380414) 73605 (native) is going to execute the syscall 215, required is 215
(01.380456) 73605 was stopped
(01.380481) 73601 was trapped
(01.380487) 73601 (native) is going to execute the syscall 215, required is 215
(01.380520) 73601 was stopped
(01.380528) Running pre-resume scripts
(01.381344) Restore finished successfully. Tasks resumed.
(01.381354) Writing stats
(01.381672) Running post-resume scripts

**Comment by avagin** [comment]
@rst0git could you help with this?

**Comment by rst0git** [comment]
@avagin yes, I can look into this later today.

**Comment by rst0git** [comment]
@Qinghe12 as a workaround, until the issue is resolved, you can use the version of `criu-ns` before commit 265569a40f04326dc2b310eb5ddbac9c1cb989e3:

https://raw.githubusercontent.com/checkpoint-restore/criu/e18017285b69bf465f27a6ad46c17c70913e51d7/scripts/criu-ns

**Comment by Qinghe12** [comment]
@rst0git  yes,  the previous version works for me !!
