### ISSUE TITLE
About the RPC option orphan-pts-master

### ISSUE THREAD

**Issue by yimin-zhao** [checkpoint-restore/criu#1279]
Hi there,

I am playing with podman's checkpoint/restore functionality, and I found there is one RPC option `orphan-pts-master` that only handled in `cr-service.c`, I have a few guesses, but I would like to ask the contributors/maintainers to know why? Are there more reasons about this?

Thanks.

**Comment by adrianreber** [comment]
Not sure, but probably no one needed it yet via CLI. Why are you asking? Podman uses runc/crun and the communication to CRIU is always going through RPC.

**Comment by yimin-zhao** [comment]
I am doing some investigating on "checkpoint/restore inside container", and curious about if the way of RPC communication is equivalent to calling CRIU in the command line. I found some options seems only appears in RPC mode (or swrk mode, specifically). I digged the git history, `orphan-pts-master` was once introduced (runc#814) by the reason of pts salve needs to be handled specially inside the container namespaces that created by docker/podman. So I guess it's it? Simply because no one needed it yet via cli?

**Comment by adrianreber** [comment]
> I am doing some investigatings on "checkpoint/restore inside container", and curious about if the way of RPC communication is equivalent to calling CRIU in the command line. 

We try to expose every feature through CLI and RPC. But sometimes we forget. So maybe we just forgot and no one needed it until now.

> So I guess that's it? Simply because no one needed it yet via cli?

Probably.

If that is all, please close the ticket.

**Comment by yimin-zhao** [comment]
Thank you for the clarification.
