### ISSUE TITLE
Restore fails because output file is bigger than when checkpoint taken redux

### ISSUE THREAD

**Issue by davidguichard** [checkpoint-restore/criu#1282]
Issue #1258 was closed because this "is expected behaviour", but that is not helpful--it doesn't really address the question. I have a similar issue. 

I have a program expected to run for some time. I would like to occasionally checkpoint the process so that if the machine goes down I can restart it without losing the entire run. It is producing one output file (with real content, not just a log file), so in the event that I have to restore the process, I would need to roll back the output file to match the checkpoint. This sadly appears not to be a feature of criu, but it's still a valid goal.

The man page says (referring to the --leave-running option):

           Note if task is about to run after been checkpointed, it can modify
           TCP  connections,  delete  files  and  do  other dangerous actions.
           Therefore, criu can not guarantee that the next restore action will
           succeed. Most likely if this option is used, at least the file sys‐
           tem snapshot must be made with the help of post-dump action script.

So this is clearly something that has been anticipated. I can find no further explanation of what exactly I need to do to make this work. I presume I need the referenced action script to save a copy of the output file as it exists at checkpoint time, and then before doing the restore, move it back into position, but this leaves a number of questions. 

1. Is there an example of such a script, or a template for a generic action script?
2. Is it sufficient to copy the file at checkpoint time and then copy it back, or will this not succeed? The copy of the file will presumably have a new inode--will this prevent the restored program from working? 

It seems like this ought to be a common enough task that there's an answer out there somewhere, or someone here who can help.

Thanks,
David

**Comment by davidguichard** [comment]
Hah!

https://src.openvz.org/projects/OVZ/repos/criu/browse/scripts/tmp-files.sh

**Comment by adrianreber** [comment]
Just adding the github link of the action script here: https://github.com/checkpoint-restore/criu/blob/master/scripts/tmp-files.sh

It seems you found a solution yourself. I am closing this. Please re-open if you have further questions.

Another way to avoid this is to use containers. Podman, for example, includes all file system changes in its checkpoint archive.
