### ISSUE TITLE
Usage: criu with iterative checkpoint and restoring

### ISSUE THREAD

**Issue by ashish-billore** [checkpoint-restore/criu#1292]
Please Note: this issue is more of a query, so please feel free to close it accordingly.

I am referring to [criu's iterative checkpoint and then finally restore.](https://criu.org/Iterative_migration)
My queries are:
1. What is the max limit to create iterative checkpoints?
2. I assume restore time will be proportional to number of checkpoints, for example restoring from 50 checkpoints will take much longer than restoring from for example 2 checkpoints. Is this assumption right?
3. My assumption is, for restoring on the destination system, all the checkpoints need to be transferred and not just the last one, is this right?
4. Is it fully supported with runc, including with [page_server](https://criu.org/Page_server) option?

Also, I referred to [this example](https://www.redhat.com/en/blog/container-migration-around-world), and there is a link for source host for [migrate](https://people.redhat.com/areber/criu/migrate), however, I could not locate the script meant to run on the destination host for restoring.

Thanks for the help!

**Comment by adrianreber** [comment]
>     1. What is the max limit to create iterative checkpoints?

Not sure, but each pre-dump references one pre-dump. So it is a list of pre-dumps which could be really long. Have you seen any limits so far?

>     2. I assume restore time will be proportional to number of checkpoints, for example restoring from 50 checkpoints will take much longer than restoring from for example 2 checkpoints. Is this assumption right?

Yes, because CRIU needs to open all checkpoints and figure out which memory page it should use from which checkpoint. The actual time to restore the process (minus analyzing the checkpoint files) should be almost the same, but the whole restore will take longer. Although restoring from 50 checkpoints will not require 50 times longer.

>     3. My assumption is, for restoring on the destination system, all the checkpoints need to be transferred and not just the last one, is this right?

Yes. As described above, CRIU needs to open all checkpoints to see which memory page should be used.

>     4. Is it fully supported with runc, including with [page_server](https://criu.org/Page_server) option?

Not sure. You need to try it out. As far as I know, there are not many users of the pre-dump runc integration. You need to try it out.

> Also, I referred to [this example](https://www.redhat.com/en/blog/container-migration-around-world), and there is a link for source host for [migrate](https://people.redhat.com/areber/criu/migrate), however, I could not locate the script meant to run on the destination host for restoring.

It should be mentioned in the article: https://people.redhat.com/areber/criu/migrate-server.py

**Comment by ashish-billore** [comment]
Thanks @adrianreber for the clarifications and links, this is really helpful.

So, about this query:

> > 1. What is the max limit to create iterative checkpoints?
> 
> Not sure, but each pre-dump references one pre-dump. So it is a list of pre-dumps which could be really long. Have you seen any limits so far?
> 

my usecase is: 
- I have a sctp socket based server application running with a lot of state data in memory, such as connected clients, their connection status etc, and this data is changing frequently. Let's call it primary node.
- To provide high availability, it is run behind a keepalived with VIP, and a node (can be host, VM or container) is kept in standby to spin up instance of this server application.
- Now in order to failover the client connection to this new server instance (on standby node), I need to have the most updated checkpoint of the primary node's server application. 
- To achieve this, one approach is to take periodic incremental checkpoints and make it available on the standby node. But it may not be predictable how many such incremental checkpoints might exists as failure of the primary node cannot be predicted.

So, I was thinking of taking these incremental checkpoints within the Max limits and once it is reached, start all over again by taking a pre-dump and subsequent incremental checkpoints off it. 
Thus, the query is what is the max limit for incremental checkpoints?  
And I'll try to derive an optimal value considering trade-off with the restoration time, within this max limit.

**Comment by adrianreber** [comment]
I had a quick look at the source code and the pre-dump restore handling seems to be a linked list without any limits.

But you should just try it out to see if it works for the number of pre-dumps you want to make.

**Comment by ashish-billore** [comment]
Thanks @adrianreber for the info. I'll close this query-issue.
