### ISSUE TITLE
compilling with rpmbuild default flags can fail

### ISSUE THREAD

**Issue by Snorch** [checkpoint-restore/criu#1301]
If I run (options are taken from default rpmbuild `%{optflags}` on VZ7 which should be the same to Centos7):
```
CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection" make V=1 WERROR=0 -j5
```

I get (fedora 32):
```
ld  -r -z noexecstack -T ./compel/arch/x86/scripts/compel-pack.lds.S  -o criu/pie/parasite.built-in.o  criu/pie/parasite.o criu/pie/pie.lib.a ./compel/plugins/std.lib.a
./compel/compel-host hgen -f criu/pie/parasite.built-in.o -o criu/pie/parasite-blob.h
Error (compel/src/lib/handle-elf-host.c:216): Unexpected precalculated address of section (section .rodata addr 0x80 expected 0x5080)
make[2]: *** [criu/pie/Makefile:58: criu/pie/parasite-blob.h] Error 255
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [criu/Makefile:59: pie] Error 2
make: *** [Makefile:259: criu] Error 2
```

Short reproduce:
```
CFLAGS="-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1" make -j5
```

And a criu/pie/parasite.built-in.o file actually has addres 0x80 after linking:
```
[snorch@snorch criu]$ readelf -WS criu/pie/parasite.built-in.o
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 1] .text             PROGBITS        0000000000000000 000040 00400a 00  AX  0   0 16
  [87] .data             PROGBITS        0000000000000000 005000 000068 00  WA  0   0 4096
  [88] .rodata           PROGBITS        0000000000000080 005080 001016 00   A  0   0 32
```

Probably introduced by 749eb33a9 ("compel: Calculate sh_addr if not provided by linker"), cc @devdri.

W/a: If I remove "annobin" cflag the problem is no longer triggered.

The fix I have in mind is to skip erroring with "Unexpected precalculated address of section" and just rewrite sh_addr. But I would like to hear more opinions here.

cc @cyrillos @0x7f454c46

**Comment by adrianreber** [comment]
For the RHEL and Fedora package I am disabling annobin because when it was introduced it breaks the parasite.

https://src.fedoraproject.org/rpms/criu/blob/master/f/criu.spec#_9

I introduced it for CRIU 3.10: https://src.fedoraproject.org/rpms/criu/c/f643faef2e6d96a94d64f1ea7ffea0c193e42951

**Comment by Snorch** [comment]
Yes I understand that disabling this flag helps, but probably there is still a problem worth fixing if we can't handle parasite object file compiled with this flag.

**Comment by adrianreber** [comment]
Yes, a fix would be good. I thought it might be related to annobin adding additional sections to the parasite which makes it too big. But I never looked closer why it fails.

**Comment by Snorch** [comment]
Close as fixed.
