### ISSUE TITLE
Failed to dump FUSE (Filesystem in Userspace) based file system process

### ISSUE THREAD

**Issue by Yifei-Liu** [checkpoint-restore/criu#1305]
I want to dump/checkpoint a fuse file system, called `fuse-cpp-ramfs`, which runs as a user process once it's mounted. I used the ordinary way to dump this process by `criu dump -t $(pgrep fuse-cpp-ramfs) -v4 -o dump_fuse_cpp_ramfs.log && echo OK` and it turned out the dumping process failed with error messages below in the dump log (`dump_fuse_cpp_ramfs.log`).
```
(00.026778) Error (criu/files-ext.c:95): Can't dump file 3 of that type [20666] (chr 10:229)
(00.026791) ----------------------------------------
(00.026829) Error (criu/cr-dump.c:1351): Dump files (pid: 151969) failed with -1
(00.026899) Waiting for 151969 to trap
(00.026912) Daemon 151969 exited trapping
(00.026929) Sent msg to daemon 3 0 0
(00.026946) Force no-breakpoints restore
(00.026973) 151969 was trapped
(00.026984) 151969 (native) is going to execute the syscall 45, required is 15
(00.027010) 151969 was trapped
(00.027018) `- Expecting exit
(00.027038) 151969 was trapped
(00.027048) 151969 (native) is going to execute the syscall 186, required is 15
(00.027066) 151969 was trapped
(00.027074) `- Expecting exit
(00.027094) 151969 was trapped
(00.027104) 151969 (native) is going to execute the syscall 1, required is 15
pie: 151969: __fetched msg: 3 0 0
(00.027128) 151969 was trapped
(00.027135) `- Expecting exit
(00.027155) 151969 was trapped
(00.027165) 151969 (native) is going to execute the syscall 186, required is 15
(00.027183) 151969 was trapped
(00.027191) `- Expecting exit
(00.027210) 151969 was trapped
(00.027219) 151969 (native) is going to execute the syscall 186, required is 15
(00.027237) 151969 was trapped
(00.027244) `- Expecting exit
(00.027265) 151969 was trapped
(00.027275) 151969 (native) is going to execute the syscall 1, required is 15
pie: 151969: 151969: new_sp=0x7f5a53fb0d48 ip 0x7f5a54267140
(00.027299) 151969 was trapped
(00.027307) `- Expecting exit
(00.027326) 151969 was trapped
(00.027336) 151969 (native) is going to execute the syscall 3, required is 15
(00.027372) 151969 was trapped
(00.027388) `- Expecting exit
(00.027423) 151969 was trapped
(00.027440) 151969 (native) is going to execute the syscall 3, required is 15
(00.027461) 151969 was trapped
(00.027469) `- Expecting exit
(00.027488) 151969 was trapped
(00.027498) 151969 (native) is going to execute the syscall 15, required is 15
(00.027536) 151969 was stopped
(00.027793) Unlock network
(00.027809) Unfreezing tasks into 1
(00.027817) 	Unseizing 151969 into 1
(00.027856) Error (criu/cr-dump.c:1768): Dumping FAILED.
```
It said **Error (criu/files-ext.c:95): Can't dump file 3 of that type [20666] (chr 10:229)**, so I checked the character device with major:minor=10:229, and this character device is `/dev/fuse` which is used by the fuse-based filesystem to communicate with the kernel. If I ran `lsof -p $(pgrep fuse-cpp-ramfs)`, I got the following line of output:
```
fuse-cpp- 151969 myusername    3u   CHR 10,229      0t0      87 /dev/fuse
```
This clue showed `fuse-cpp-ramfs` process actually opened files, but what I want to dump is the `fuse-cpp-ramfs` process and is not the `/dev/fuse` virtual device. As per https://criu.org/What_cannot_be_checkpointed#Devices and issue #1124 , does it mean this `fuse-cpp-ramfs` process cannot be dumped? Is there any workaround to achieve the dumping for fuse-based filesystem process? for example, is it possible to have an exception list that includes device can be dumped (like `/dev/null`, `/dev/zero` which can be dumped as the documentation)? Under what circumstances can we dump a userspace file system process?

Thanks for the help in advance!

**Environment:**
OS:  Ubuntu 20.04.1 LTS
CRIU version: 3.15
File system process: `fuse-cpp-ramfs` which is a FUSE-based RAM file system and open-source on Github

**Comment by avagin** [comment]
@Yifei-Liu you can create a plugin to dump or just ignore /dev/fuse. You can look at the rtc test:
https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm/static/criu-rtc.c
https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm/static/Makefile#L604

**Comment by Yifei-Liu** [comment]
@avagin Thanks for your reply! I have checked `criu-rtc.c` and `Makefile` and it seems that these functions implement dump and restore for `/dev/rtc` device file. The hooks (https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/plugin.c#L51:L52) attach `cr_plugin_dump_file` and `cr_plugin_restore_file` functions so that CRIU will be able to dump and restore `/dev/rtc` (which is a character device), correct? If so, does it mean I need to implement similar `cr_plugin_dump_file` and `cr_plugin_restore_file` functions for `/dev/fuse` and change the hooks to my functions?

I wonder if there have some easy solutions, **like just ignore /dev/fuse**, because I would like to modify and/or add codes for CRIU as few as possible and thus lead to dump/restore `fuse-cpp-ramfs` process successfully. Any advice and comment are much appreciated!

**Comment by mihalicyn** [comment]
Problem here is that if you have some processes inside your container which has some files opened from fuse filesystem then ignoring will not work. Easiest solution with ignoring `/dev/fuse` possible only if you can organize your processes to close all fuse file descriptors just before C/R.

Another way: if your fuse filesystem is really just ramfs-like (not use network to retrieve data) then you can implement solution which will be specific for your fuse-cpp-ramfs filesystem only. You should detect fuse mount of fuse-cpp-ramfs fs and dump it without error, then on restore mount your fuse filesystem and then CRIU will reopen files. But there is a problem - you need to modify CRIU code in order to ignore your fuse daemon process on dump. Because if CRIU will dump this process it will try to rerun your fuse daemon during pstree restore and we get a problem.

--- Too hard:
More universal way here is to use SPFS (https://github.com/skinsbursky/spfs).
Idea is to "dump" all fuse files as "empty" files (just to save fd flags, attributes), then on restore mount special "proxy" filesystem which will allow to recreate all opened files as a new files, and just before releasing processes on restore change "proxy" mode to "stub" mode, and replace SPFS mount by your fuse mount.
