### ISSUE TITLE
jenkins: pid_reuse failures

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1322]
Looking at Jenkins results I see a lot of failures related to pid_reuse:
```
09:11:15.046: 11235: ERR: pid_reuse.c:74: Wrong value in a variable after restore
09:11:15.048:     4: FAIL: pid_reuse.c:107: Task 11235 died with exit status 100 (errno = 9 (Bad file descriptor))
```

For example in https://ci.openvz.org/job/CRIU/job/CRIU-lazy-remote/job/criu-dev/4059/consoleFull but it seems a couple of Jenkins tests are failing because of this.

@Snorch, as you are the author of that test, any ideas what is going on? Is that the expected result? Should the test fail, because in the commit message a similar error message is listed.

I something broken in CRIU or do we need to exclude the test for lazy pages?

**Comment by avagin** [comment]
dup of #1266
