### ISSUE TITLE
criu dump error for in-flight connections

### ISSUE THREAD

**Issue by gtrani** [checkpoint-restore/criu#1324]
The dump.log suggests to use `--skip-in-flight` option so that `criu` will ignore those connections and can proceed.

I want to know, once the dump is initiated, if its possible for `criu` to wait for the connection to successfully establish and then dump.?

Dump.log: [dump.txt](https://github.com/checkpoint-restore/criu/files/5750116/dump.txt)

**Comment by adrianreber** [comment]
> I want to know, once the dump is initiated, if its possible for `criu` to wait for the connection to successfully establish and then dump.?

Nothing like that exists currently. I am closing this ticket, but please re-open if you have further questions.

**Comment by gtrani** [comment]
yes, Can you please look at the log file uploaded, and tell if I'm correct to understand that the dump is failing only due to in flight connection and can be resolved by adding the suggested option?

**Comment by adrianreber** [comment]
> yes, Can you please look at the log file uploaded, and tell if I'm correct to understand that the dump is failing only due to in flight connection and can be resolved by adding the suggested option?

I would say adding `--skip-in-flight` should work. The connection is listed as being in `LISTEN` which should be easy for CRIU to handle. Without looking at the code right now I would trust CRIU here that `--skip-in-flight` should work. If CRIU suggest that it means that the is currently a SYN, SYN-ACK or ACK package in flight.

**Comment by gtrani** [comment]
thanks.

**Comment by gtrani** [comment]
Hi again, I made a script which repeatedly checkpoints a running container periodically, added the above `--skip-in-flight` option and it was working correctly, but after interrupting the script, which obviously means interrupting the dump procedure in worst case, the client cannot connect to the server now. always getting timeout error which is shocking as server is up in the container. 

Is it a known issue that repeatedly checkpointing can create a situation like this?

**Comment by avagin** [comment]
No, it isn't a known issue. We need criu logs to investigate this. And you need to look at a server process with strace and gdb. We need to know whether it is stuck in the parasite code or there is something else.
