### ISSUE TITLE
Collecting and Dumping sockets

### ISSUE THREAD

**Issue by gtrani** [checkpoint-restore/criu#1331]
Which part  in the  `criu` code does the task of collecting and dumping network-connections/sockets? 
Please link the file here.

**Comment by avagin** [comment]
https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/sockets.c#L839
https://github.com/checkpoint-restore/criu/blob/318fea8f737616e005bbf59bdf56ee6b8384a946/criu/sk-inet.c#L447

**Comment by gtrani** [comment]
Got it after digging into code further.
