### ISSUE TITLE
Fail to compile libcompel examples

### ISSUE THREAD

**Issue by LiuChangFreeman** [checkpoint-restore/criu#1333]
The tutorial says:

> `Clone the repo, build the project by running make, then go to compel/test/$test_name directory and run make there. Running spy bynary runs the example.`

Running `make` succeed under criu/ as I installed the dependcies on my Ubuntu 18.04. But I got errors bellow when I tried to run `make` under compel/test/fdspy: 

> root@DESKTOP-SCDP791:/mnt/c/tools/criu/compel/test/fdspy# make
gcc -O2 -g -Wall -Werror -c -Wstrict-prototypes -fno-stack-protector -nostdlib -fomit-frame-pointer -ffreestanding -fpie -I ../../../compel/include/uapi -o parasite.o parasite.c
In file included from parasite.c:3:0:
../../../compel/include/uapi/compel/plugins/plugin-fds.h:4:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before fds_send_fd’
 extern int __must_check fds_send_fd(int fd);
                         ^~~~~~~~~~~
In file included from parasite.c:4:0:
../../../compel/include/uapi/compel/infect-rpc.h:9:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_sync’
 extern int __must_check compel_rpc_sync(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~
../../../compel/include/uapi/compel/infect-rpc.h:10:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_call’
 extern int __must_check compel_rpc_call(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~
../../../compel/include/uapi/compel/infect-rpc.h:11:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_call_sync’
 extern int __must_check compel_rpc_call_sync(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~~~~~~
parasite.c: In function ‘parasite_daemon_cmd’:
parasite.c:18:3: error: implicit declaration of function ‘fds_send_fd’; did you mean ‘fds_recv_fd’? [-Werror=implicit-function-declaration]
   fds_send_fd(2);
   ^~~~~~~~~~~
   fds_recv_fd
cc1: all warnings being treated as errors
Makefile:28: recipe for target 'parasite.o' failed
make: *** [parasite.o] Error 1

Could anyone figure out what happens?

**Comment by LiuChangFreeman** [comment]
I think these examples can't be compiled successfully, duing to the missing headers. There are no `compel` headers in the `compel/test/rsys/spy.c`.
![20210109150411](https://user-images.githubusercontent.com/20047907/104085716-85e1d100-528c-11eb-85b6-3912a3edb92b.png)
Waiting for an official answer.

**Comment by rst0git** [comment]
Hi @LiuChangFreeman, thank you for reporting this issue. I've opened a pull request (https://github.com/checkpoint-restore/criu/pull/1335) with a fix.
