### ISSUE TITLE
confusion with mulitple files of pagemap and pages.

### ISSUE THREAD

**Issue by gtrani** [checkpoint-restore/criu#1337]
There are two files of pagemap and page images are created on dump:
```

gt@vm:~/mp/checkpoints/18$ ls -lh page*
-rw-r--r-- 1 root root  329 Jan 12 12:34 pagemap-1.img
-rw-r--r-- 1 root root 4.2K Jan 12 12:34 pagemap-45.img
-rw-r--r-- 1 root root 284K Jan 12 12:34 pages-1.img
-rw-r--r-- 1 root root 209M Jan 12 12:34 pages-2.img
```
Please explain below queries with a little detail.
are pagemap-1 and pagemap-45 are related and how? 
are pagemap-1 and pages-1.img are related and how? 
are pages-1.img and pages-2.img are related and how?

Quoted exactly from criu webpage: 
**Pages**
`    This is the plain set of 4k entries -- each one is a full page with data.`

This seems to be a confusing statement. What i understand from this is the pages.img contains exactly 4k entries where each entry has full page data in it, this means that, this should always be of constant size `4k*4k`.  second 4k for the page size.

**Comment by adrianreber** [comment]
If you do a `crit show pagemap-1.img` it should point to pages-1.img if you do a `crit show pagemap-45.img` it should point to pages-2.img.

**Comment by adrianreber** [comment]
> This seems to be a confusing statement. What i understand from this is the pages.img contains exactly 4k entries where each entry has full page data in it, this means that, this should always be of constant size `4k*4k`. second 4k for the page size.

No, it contains a multiple of complete pages. But each page is 4K (or page size of that architecture).

**Comment by gtrani** [comment]
Yes, seen it but then what's the difference between pagemap-1 and pagemap-2? there's huge size difference between them.
> If you do a `crit show pagemap-1.img` it should point to pages-1.img if you do a `crit show pagemap-45.img` it should point to pages-2.img.

**Comment by adrianreber** [comment]
> Yes, seen it but then what's the difference between pagemap-1 and pagemap-2? there's huge size difference between them.

You mean pages-1.img and pages-2.img. `pagemap-PID.img` is created for each checkpointed process and points to a different `pages-ID.img`. The size of the `pages-ID.img` depends on the used memory of the dumped PID.

**Comment by gtrani** [comment]
Thanks, Now it's clear. so no. of `pagemaps` depends on the no. of checkpointed process.
