### ISSUE TITLE
ZDTM rpc unexpected behavior 

### ISSUE THREAD

**Issue by ZeyadYasser** [checkpoint-restore/criu#1339]
I was working on this issue https://github.com/checkpoint-restore/criu/issues/717.

I followed the approach suggested by @Snorch of opening a socket pair to transfer pidfds between pre-dump/dump iterations for pidfd based pid reuse detection.
I got the idea that I could open the socket pair implicitly in service mode right before the pre-dump loop https://github.com/checkpoint-restore/criu/blob/0e7321c2fcc5626b45266290b17d9e690d526479/criu/cr-service.c#L874 since CRIU forces the pre-dump to go through the pre-dump loop until the last dump.
I tried this approach with P.Haul and it worked as expected without adding new options for the sockets fds to be passed which was a welcomed plus as I didn't have to change anything in P.Haul.

When running the ZDTM pre-dump rpc test, it failed.
```test/zdtm.py run -t zdtm/static/env00 --rpc --pre 2```

This got me digging into ZDTM, PyCriu and the pre-dump logs.
It turns out that when ZDTM runs in rpc mode, it opens CRIU in SWRK mode, sends the request and then closes the socket directly and opens CRIU in SWRK mode for next pre-dump and so on unlike P.Haul https://github.com/checkpoint-restore/criu/blob/0e7321c2fcc5626b45266290b17d9e690d526479/lib/py/criu.py#L228 which causes CRIU to crash the service worker due to closing the socket in the middle of the pre-dump loop https://github.com/checkpoint-restore/criu/blob/0e7321c2fcc5626b45266290b17d9e690d526479/criu/cr-service.c#L882 and not continue the pre-dump loop.

This caused the side effect that the initialization of the socket pair I did just before the pre-dump loop starts does not persist between pre-dump iterations in the ZDTM rpc tests.

Is this the expected behavior? Should CRIU support pre-dumps in service mode that are not part of the same pre-dump loop?

If this behavior is expected I think I should go with @Snorch 's suggestion of passing the socket pair fds as an option to CRIU instead of the implicit initialization when running in service mode, but this would lead to adding a new option to CRIU, the rpc protobuf definition and updating P.Haul to pass the socket pair when preparing CRIU .

Thank you

**Comment by adrianreber** [comment]
> Is this the expected behavior? Should CRIU support pre-dumps in service mode that are not part of the same pre-dump loop?

I am not sure I understood your question, but it is not required for a CRIU client to stay connected to CRIU during a pre-dump loop. Or using the CRIU internal pre-dump loop logic. Using `runc` for example, each pre-dump is a new connection from runc to CRIU using go-criu. The user is free to let as much time pass between pre-dumps as the user wants.

It sounds like to right thing to do to implicitly pass the FDs to CRIU.

**Comment by ZeyadYasser** [comment]
Thank you so much, That explains a lot.
