### ISSUE TITLE
Failed to restore a process by calling CRIU in shell scripts

### ISSUE THREAD

**Issue by SpereShelde** [checkpoint-restore/criu#1340]
I'm doing a lab trying to checkpoint/restore a process using CRIU. 

I compiled a C++ program having four groups of jobs in four threads. The program has one additional thread determining the whole system's events: setting checkpoints, and restoring at some certain timepoints.

Since a C++ program cannot restore itself, I made the fifth thread to send the system's status to a pipe and used a shell script to read the pipe and call CRIU commands in corresponding statuses.

The C++ is good to run till the end, tested by the shell script below, (the pipe is listened by a separate shell script to prevent blocking the C++ process):
```
setsid ./tasksWithPipe.out < /dev/null &
pid=$!
echo "PID: $pid"

sleep 5
criu dump -v2 -D cp0 -j -R -t "$pid" -o d.log
sleep 5
kill -9 "$pid"
sleep 5
criu restore -v2 -D cp0 -j -o r.log
```

However, when it comes to the shell listening to the pipe, it doesn't work. 
```
setsid ./tasksWithPipe.out < /dev/null &
pid=$!
echo "PID: $pid"

pipe=thePipe
while true
do
    if read line < $pipe; then
        cmd=$(echo "$line" | cut -c 1-4)
        arg=$(echo "$line" | cut -c 6-)
        if [[ "$cmd" == 'exit' ]]; then
            echo "Exit" && exit
        elif [[ "$cmd" == 'save' ]]; then
            echo "Save $arg"
            criu dump -v2 -D "$arg" -R -j -t "$pid" -o d.log
        elif [[ "$cmd" == 'rest' ]]; then
            echo "Restore $arg"
            kill -9 "$pid"
            criu restore -v2 -D "$arg" -j -o r.log
        fi
    fi
done

```

The output in the terminal:
```
PID: 18443
Save cp0
Restore cp0
pipeRestore.sh: line 22: 18443 Killed                  setsid ./tasksWithPipe.out < /dev/null
```

The d.log is good however the r.log is empty.

I cannot see the critical difference between the two shell scripts. Why the CRIU doesn't work in a while loop with pipe? Can anyone help me out?

**Comment by adrianreber** [comment]
Can you be a bit more specific what your problem is. You give us the output of your shell script which says `18443 Killed`. Is that your problem? And which is line 22? Counting your script 22 seems to be `done`. Can you paste the complete shell script with shebang and if you are using any `set`?

**Comment by SpereShelde** [comment]
Sure, thank you for replying. I've uploaded all my code to the repo: [https://github.com/SpereShelde/CRIU_Lab](https://github.com/SpereShelde/CRIU_Lab)

The line 22 is the last line, the `done`, yep. Don't know why, maybe because the `criu` made the shell script stuck?

My problem is how can I checkpoint/restore a process back and forth multiple times using pipe or UDP? As you can see the checkpoint/restore is good to run without while loop, but when a while loop, failed.

Thank you again for your time.

**Comment by avagin** [comment]
you run restore without the --detach option, so criu waits when a restored process will exit. If it isn't a case, you need to look at the process tree. Maybe there is a criu process... You can try to play with the strace and gdb. You can try to add "set -x" in your script to see what commands have been executed.

**Comment by SpereShelde** [comment]
Great! 

`-d` solved my problem.

Thank you!
