### ISSUE TITLE
criu : applying images

### ISSUE THREAD

**Issue by gitsvm** [checkpoint-restore/criu#1345]
Need some information about the current status of this idea : https://www.criu.org/Applying_images

As mentioned in the link, it's possible to do this but that's a lot of patching? Any design idea how can i proceed to build this? Some lower level details are required.

**Comment by rst0git** [comment]
The paper following paper seems relevant to what you are trying to do.

Duan, Ruian, et al. "Automating Patching of Vulnerable Open-Source Software Versions in Application Binaries." NDSS. 2019.
https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_05A-3_Duan_paper.pdf
