### ISSUE TITLE
openj9 tests are failing

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1370]
@nidhi1605 all your openj9 CRIU tests are failing (https://github.com/checkpoint-restore/criu/runs/1869412177)

Can you please check what is going on? Let us know if we should disable it?

**Comment by rst0git** [comment]
>(00.427831) Error (criu/file-lock.c:112): Some file locks are hold by dumping tasks!You can try --file-locks to dump them.
(00.427887) Unlock network
(00.427894) Unfreezing tasks into 1
(00.427898)     Unseizing 22060 into 1
(00.427995) Error (criu/cr-dump.c:1780): Dumping FAILED.
