### ISSUE TITLE
Containers Starts From Initial States After Checkpoint & Restoring

### ISSUE THREAD

**Issue by lzqlzqwhr** [checkpoint-restore/criu#1378]
I tried the Docker 20.10.2 to checkpoint a container, however, once restoring it does not restart from the checkpointed states. Instead, it starts from the beginning. 

Docker version: 20.10.2 
CRIU version: 3.15 
RUNC version 1.0.0-rc92

1. Start the container: 
`docker run --security-opt=seccomp:unconfined --name cr -d busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
2. Check the log: 
`docker logs cr` 
0
1
2
3
4
5
6
7
8
9
10
11
3. Checkpoint the container: 
`docker checkpoint create cr checkpoint0`
4. Restore the container: 
`docker start --checkpoint=checkpoint0 cr`
5. Check the log again: 
`sudo docker logs`
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4

However, once I changed the Docker version to 17.03, it works fine.

**Comment by Snorch** [comment]
See #1365 and #1223 and #1374. You probably need to search for your problem in issues first before filling a new one =)

**Comment by adrianreber** [comment]
@Snorch is right. This has been discussed multiple times already and it is a Docker problem.

You can try Podman. That should give you a working container checkpoint and restore implementation.

I am closing this ticket as it is a duplicate and not a CRIU bug.
