### ISSUE TITLE
Current sid 18028 intersects with pid (255) in images

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#1400]
Commit https://github.com/checkpoint-restore/criu/commit/77968d43c3641baa189212ee3547e932fff7f634 causes all Java tests to fail with the following error

```
(00.000228) pstree pid_max=23001
(00.000236) Migrating process tree (SID 18028->18028)
(00.000238) Error (criu/pstree.c:377): Current sid 18028 intersects with pid (255) in images
```

**Comment by rst0git** [comment]
cc: @Snorch

**Comment by Snorch** [comment]
Sorry for breaking tests, I missed this case where old_sid==new_sid, please see a pr #1413. It should help.
