### ISSUE TITLE
criu/lsm.c:90: Invalid selinux context kernel

### ISSUE THREAD

**Issue by Snorch** [checkpoint-restore/criu#1402]
I can see all tests failing on my system (f33) like this:

```
[root@snorch criu]# ./test/zdtm.py run -t zdtm/static/env00 --ignore-taint
userns is supported
=== Run 1/1 ================ zdtm/static/env00
timens isn't supported on 5.10.19-200.snorch.fc33.x86_64
========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
=[log]=> dump/zdtm/static/env00/56/1/dump.log
------------------------ grep Error ------------------------
b'pie: 56: __fetched msg: 64 0 0'
b'pie: 56: __sent ack msg: 64 64 0'
b'pie: 56: Daemon waits for command'
b'(00.012355) Fetched ack: 64 64 0'
b'(00.012387) Error (criu/lsm.c:90): Invalid selinux context kernel'
b'(00.012391) ----------------------------------------'
b'(00.012394) Error (criu/cr-dump.c:1402): Dump core (pid: 56) failed with -1'
b'(00.012786) 56 was stopped'
b'(00.012941) Unlock network'
b'(00.012950) Unfreezing tasks into 1'
b'(00.012953) \tUnseizing 56 into 1'
b'(00.012963) Error (criu/cr-dump.c:1780): Dumping FAILED.'
------------------------ ERROR OVER ------------------------
################### Test zdtm/static/env00 FAIL at CRIU dump ###################
Send the 9 signal to  56
Wait for zdtm/static/env00(56) to die for 0.100000
##################################### FAIL #####################################
```

I have selinux "enabled" on my system in some strange way:

```
[root@snorch criu]# sestatus
SELinux status:                 disabled
[root@snorch criu]# getenforce
Disabled
```
But there is empty dir in /sys/fs/selinux:

```
[root@snorch criu]# ls /sys/fs/selinux/
[root@snorch criu]# 
```

And kerndat_lsm() states that it means that selinux is though enabled.

That's why in selinux_get_label() we try to get selinux process context but get "kernel" in responce.

E.g.:
```
[snorch@snorch criu]$ cat /proc/self/attr/current 
kernel[snorch@snorch criu]$
```

"kernel" selinux init context (SECINITSID_KERNEL in kernel) is only given if selinux is uninitialized (selinux_initialized() kernel helper called from security_sid_to_context_core()).

And our selinux_get_label is not ready for "kernel" string and fails.

Next I will try to fully disable selinux to w/a this problem (with kernel boot param).

**Comment by adrianreber** [comment]
Interesting. Never seen selinux in this state. Probably easy to fix if we know that `current` can also contain the string `kernel` for being uninitialized.

**Comment by Snorch** [comment]
@adrianreber Note that there are some other "initial" states https://github.com/torvalds/linux/blob/master/security/selinux/include/initial_sid_to_string.h, but probably handling "kernel" is enough for now...

Note: adding "selinux=0" kernel boot parameter workarounded the problem for me.

**Comment by rajbhar** [comment]
I ran into the same issue today. Do we have a kernel/criu fix for this? With SELINUX disabled, this issue is not seen. I am using Ubuntu with 5.11 kernel and my test environment was checkpoint inside a docker container. I didn't see this issue earlier but recently migrated to 5.11 kernel and latest criu as on commit e49ce513c8df43e8d3b30b7acfbe7bd496d89862
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Mon Mar 15 17:07:01 2021 +0100

**Comment by adrianreber** [comment]
No, there is no fix yet. What is your kernel config to get this error?

**Comment by adrianreber** [comment]
A quick fix would probably be to uninstall selinux development libraries. This way CRIU would be built without selinux support and not fail here.

**Comment by rajbhar** [comment]
Hi Adrian, PFA .

[dbg_defconfig.log](https://github.com/checkpoint-restore/criu/files/6341317/dbg_defconfig.log)

**Comment by adrianreber** [comment]
@Snorch In your kernel config you had SELINUX enabled right? But you probably do not install any policies, right? Do you know what mounts `/sys/fs/selinux`? Probably systemd?

I think CRIU's detection if SELinux is available is wrong. Currently we test for the existence of `/sys/fs/selinux` and that seems to exist if the kernel has SELinux support but even if no policies are loaded.

All systems I have access to, either have SELinux working normally or `/sys/fs/selinux` is not mounted at all.

**Comment by adrianreber** [comment]
Could someone tries this patch to see if that is a better check:
```
diff --git a/criu/lsm.c b/criu/lsm.c
index 7cc36049f..e746a4b14 100644
--- a/criu/lsm.c
+++ b/criu/lsm.c
@@ -207,12 +207,7 @@ void kerndat_lsm(void)
        }
 
 #ifdef CONFIG_HAS_SELINUX
-       /*
-        * This seems to be the canonical place to mount this fs if it is
-        * enabled, although we may (?) want to check /selinux for posterity as
-        * well.
-        */
-       if (access("/sys/fs/selinux", F_OK) == 0) {
+       if (is_selinux_enabled()) {
                kdat.lsm = LSMTYPE__SELINUX;
                return;
        }
```

That is using the official library call to check for SELinux, which does check if the mount exists (like CRIU already does) and it checks if `/etc/selinux/config` exists.

**Comment by rajbhar** [comment]
I once booted my machine(remote) with selinux=0 so now when I try to enable it back again, Ubuntu gets stuck at boot as some libs (libnftables) can't load so I could not test this patch. I'll let you know when I see this issue next time or when I get a chance to fix my remote machine.

**Comment by rajbhar** [comment]
I was able to try this today and it works. Also tested the better version from your PR, works too.
