### ISSUE TITLE
Failed to checkpoint restored sessions.

### ISSUE THREAD

**Issue by lvella** [checkpoint-restore/criu#1404]
I am trying to make periodic checkpoints for a long running ffmpeg encode. I wrote a python script that spawns the ffmpeg process as a child, and periodically writes a checkpoint. I record the size of the output file after the checkpoint with `--leave-stopped` and then `SIGCONT` the process, so I can truncate the output to the same size when restoring.

So far I managed to checkpoint repeatedly and restore the latest checkpoint. Then I get the following error when I try to checkpoint the restored session:
```
Error (criu/namespaces.c:419): Can't dump nested time namespace for 8422
Error (criu/namespaces.c:685): Can't make timens id
Error (criu/cr-dump.c:1764): Dumping FAILED.
```

This is the command I run to make the checkpoint:
```criu dump --tree 8622 --shell-job --images-dir checkpoints/tmp --leave-stopped```

And this is the command I run to restore it:
```criu restore --shell-job --images-dir checkpoints/00005```

How can I checkpoint restored sessions?

**Comment by adrianreber** [comment]
@lvella Can you tell us which version of CRIU and Kernel you use?

@avagin any ideas what is happening here? Is this related to #1323 ?

**Comment by lvella** [comment]
@adrianreber I got the same issue with criu 3.15, but I first got with Ubuntu's criu 3.14. Kernel is Ubuntu's 5.8.0-44-lowlatency.

I could not build previous criu release, got some struct redefinition error.

**Comment by adrianreber** [comment]
@lvella There has been a fix concerning time namespaces in 5.11 (see #1323) but I am not sure this related to your failure. But @avagin should now.

**Comment by lvella** [comment]
I tested, and I get the same issue with master.

**Comment by avagin** [comment]
Sorry for the delay. I will take a look at it.

**Comment by lvella** [comment]
I no longer have interest in this issue. Maybe I have stumbled upon a bug and it would be nice if could fix it, but I no longer have the original files, the script and don't remember what I have learned at the time about criu, so I'm afraid I'll be of little help.

**Comment by Snorch** [comment]
Note: I don't see --restore-detached at restore, so criu restore waiter process was still there at the time of second dump. Can't it be criu waiter process the one which was dumped at second dump instead of real process? That can explain nested time namespace detected...

![800px-Criu-restore-dflt](https://user-images.githubusercontent.com/6671311/119947305-4815e880-bfa0-11eb-9320-3c5acbcd9a05.png)

**Comment by avagin** [comment]
@Snorch The scenario that you described looks real.

**Comment by avagin** [comment]
```
    477 ?        Ss     0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
  68263 ?        Ss     0:00  \_ sshd: root [priv]
  68284 ?        S      0:00  |   \_ sshd: root@pts/0
  68289 pts/0    Ss     0:00  |       \_ -bash
  69825 pts/0    S      0:00  |           \_ ./criu/criu restore -o restore.log.log -D images/ -vvvv -j
  69746 pts/0    S+     0:00  |               \_ sh -c while :; do sleep 10; done
  69777 pts/0    S+     0:00  |                   \_ sleep 10


[root@fc24 criu]# mkdir images2
[root@fc24 criu]# ./criu/criu dump -o dump.log -D images2/ -vvvv -j -t 69825
[root@fc24 criu]# echo $?
1
[root@fc24 criu]# cat images2/dump.log | grep Error
(00.001702) Error (criu/namespaces.c:423): Can't dump nested time namespace for 69746
(00.001711) Error (criu/namespaces.c:691): Can't make timens id
(00.001776) Error (criu/cr-dump.c:1780): Dumping FAILED.
[root@fc24 criu]# ./criu/criu dump -o dump.log -D images2/ -vvvv -j -t 69746
[root@fc24 criu]# echo $?
0
```
