### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1405]
Hello @checkpoint-restore/maintainers 

In a recent pull request @avagin brought up if we should drop Python 2 support? We discussed it already a couple of times and the only reason to not drop it was that CentOS/RHEL 7 still exists until 2024.

@avagin correctly mentioned that CentOS/RHEL 7 also comes with Python 3. So we could drop Python 2 support without breaking any of our tested platforms.

Right now this would mean switching the CentOS 7 CI run to Python 3 and no longer test on Python 2.

Does anyone has any reasons to keep supporting Python 2 or can we just ignore it from now on?

**Comment by 0x7f454c46** [comment]
I don't have anything against it. Moreover, for some time I already have to call `make PYTHON=python3` because the default python version in nmk is:
```
FULL_PYTHON	:= $(shell which python2 2>/dev/null || which python3 2>/dev/null)
```
and maintainers of Arch Linux stopped supporting python2 protobuf bindings, I only have these days:
```
extra/python-protobuf 3.12.4-3 [installed]
    Python 3 bindings for Google Protocol Buffers
```
So, sounds good to me.

**Comment by avagin** [comment]
> Does anyone has any reasons to keep supporting Python 2 or can we just ignore it from now on?
I think we can stop supporting python 2.

**Comment by adrianreber** [comment]
I had a closer look and unfortunately there are no Python 3 protobuf bindings in CentOS/RHEL 7.

So we cannot really drop Python 2 support without dropping CentOS/RHEL 7 support.

We could at least help @0x7f454c46 by defaulting to Python 3. But not being able to drop Python 2 support means that either we have more effort making sure everything still works with Python 2 or we reduce the number of tests on Python 2 platforms.

Not sure what to do. Maybe we should just drop CentOS/RHEL 7 support and if there is an important fix we could backport fixes to 3.15.x and have 3.15 be the last release supporting Python 2.

**Comment by rst0git** [comment]
> I had a closer look and unfortunately there are no Python 3 protobuf bindings in CentOS/RHEL 7.

Would it work to install the protobuf bindings with pip?
https://pypi.org/project/protobuf/

**Comment by adrianreber** [comment]
> > I had a closer look and unfortunately there are no Python 3 protobuf bindings in CentOS/RHEL 7.
> 
> Would it work if we install the protobuf bindings with pip?
> https://pypi.org/project/protobuf/

That would work for CI. It would not help for packaging on the distribution side. The packaging would need to drop the crit sub-package and criu python bindings, but that is doable. If someone really wants to run the latest version of CRIU on CentOS/RHEL 7 with Python bindings they would need to use pip to install it. Sounds acceptable to me.

Use pip in CI, drop python related packages in our packages for CentOS/RHEL 7. Let me try that out.

**Comment by Snorch** [comment]
>I had a closer look and unfortunately there are no Python 3 protobuf bindings in CentOS/RHEL 7.

In Virtuozzo 7 we also have only python2 option, it would be sad If we would not be able to run zdtm =)

**Comment by adrianreber** [comment]
> > I had a closer look and unfortunately there are no Python 3 protobuf bindings in CentOS/RHEL 7.
> 
> In Virtuozzo 7 we also have only python2 option, it would be sad If we would not be able to run zdtm =)

For me that is a good enough argument to not drop Python 2 support.

**Comment by adrianreber** [comment]
Closing as we cannot really drop Python 2 support.
