### ISSUE TITLE
Cannot export container checkpoint inside Podman pod

### ISSUE THREAD

**Issue by mind-mind** [checkpoint-restore/criu#1424]
Hi,

I tried to use "podman container checkpoint" the container running on podman's pod

This container create by "sudo podman play kube pod.yml" for more detail: https://developers.redhat.com/blog/2019/01/29/podman-kubernetes-yaml/  

It running inside a pod of podman.

I used "podman container checkpoint <container name>"
           "podman container restore <container name>"
It works.

But, the problem is when I tried to export by using "podman container checkpoint -e checkpoiont.tar.gz" 

I got error 
Error: Cannot export checkpoints of containers with dependencies 

How can I fix this? Thank you very much.

**Comment by adrianreber** [comment]
This is a Podman problem, not a CRIU problem. Please report it to Podman.

> How can I fix this? Thank you very much.

This is not implemented in Podman. You could provide patches to implement it.

This should not be too difficult. I did the necessary changes in CRI-O (https://github.com/cri-o/cri-o/pull/4199).

Closing as this is not a CRIU problem.
