### ISSUE TITLE
sem_next_id is inaccessible: No such file or directory

### ISSUE THREAD

**Issue by hiyangyue** [checkpoint-restore/criu#1446]
I use criu on the Android Platform, the error looks like that. I rebuild the kernel config following the documents: https://criu.org/Linux_kernel
```
./criu check                                                                                                                                    
Warn  (criu/net.c:2910): Unable to get socket network namespace
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Warn  (criu/net.c:2910): Unable to get socket network namespace
Error (criu/cr-check.c:512): /proc/sys/kernel/sem_next_id is inaccessible: No such file or directory
Does not look good.
```
My Kernel Info : 
> Linux version 4.4.192+ (root@VM-236-196-ubuntu) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #8 SMP PREEMPT Mon Apr 19 19:33:00 CST 2021

Kernel config:
https://github.com/hiyangyue/Criu-Android/blob/master/androidArm64Config

**Comment by adrianreber** [comment]
Interesting. I would have said do you have CONFIG_CHECKPOINT_RESTORE set to yes because https://github.com/torvalds/linux/blob/v4.4/ipc/ipc_sysctl.c#L177 says that `sem_next_id` only exists if CONFIG_CHECKPOINT_RESTORE=y.

Are you sure your kernel has CONFIG_CHECKPOINT_RESTORE=y?

Can you see the file `/proc/sys/kernel/ns_last_pid` ? That file also only exists if CONFIG_CHECKPOINT_RESTORE=y

**Comment by mihalicyn** [comment]
@hiyangyue hi!

Can you publish your kernel source code somewhere (on GitHub/GitLab/etc)?

**Comment by hiyangyue** [comment]
> Interesting. I would have said do you have CONFIG_CHECKPOINT_RESTORE set to yes because https://github.com/torvalds/linux/blob/v4.4/ipc/ipc_sysctl.c#L177 says that `sem_next_id` only exists if CONFIG_CHECKPOINT_RESTORE=y.
> 
> Are you sure your kernel has CONFIG_CHECKPOINT_RESTORE=y?
> 
> Can you see the file `/proc/sys/kernel/ns_last_pid` ? That file also only exists if CONFIG_CHECKPOINT_RESTORE=y

![image](https://user-images.githubusercontent.com/9319738/115326226-89f08980-a1bf-11eb-8f4f-84cf43d1563e.png)
Is it right ?

**Comment by hiyangyue** [comment]
> @hiyangyue hi!
> 
> Can you publish your kernel source code somewhere (on GitHub/GitLab/etc)?

I use Google Goldfish as Kernel.
```
git clone  https://android.googlesource.com/kernel/goldfish
cd goldfish
git checkout android-goldfish-4.4-dev
// and checkout this commit
git checkout f4355abac45a608dbe0e7d87fd50c349b90d6928
```
Do I need to provide other extra compile info?

**Comment by hiyangyue** [comment]
> @hiyangyue hi!
> 
> Can you publish your kernel source code somewhere (on GitHub/GitLab/etc)?

I use this repo as Kernel.
```
git clone https://android.googlesource.com/kernel/common/
git checkout  da6d147f98d198c3d9059e609ca492a4824d9ef5
```
Do I need to provide other extra info?

**Comment by mihalicyn** [comment]
@hiyangyue

> Do I need to provide other extra info?

no, I'll take a look on your kernel code and config

**Comment by mihalicyn** [comment]
1. "Unable to get socket network namespace" it's about ioctl(SIOCGSKNS). This ioctl absent on your kernel commit. It's not critical issue.
2. "tun: Unable to create tun: No such file or directory" please, try `mknod -m 666 /dev/net/tun c 10 200`
3. "unix: Unable to open a socket file: Bad address" - ioctl(SIOCUNIXFILE). Also absent in your kernel code.
4. "/proc/sys/kernel/sem_next_id is inaccessible" - this is present in code and under "CONFIG_CHECKPOINT_RESTORE".
BUT, if we take a look on Makefile:
`obj-$(CONFIG_SYSVIPC_SYSCTL) += ipc_sysctl.o`
we can see that we need to enable CONFIG_SYSVIPC_SYSCTL which is disabled in your config.

**Comment by mihalicyn** [comment]
I've added `CONFIG_SYSVIPC_SYSCTL` to the https://criu.org/Linux_kernel page

**Comment by hiyangyue** [comment]
> 1. "Unable to get socket network namespace" it's about ioctl(SIOCGSKNS). This ioctl absent on your kernel commit. It's not critical issue.
> 2. "tun: Unable to create tun: No such file or directory" please, try `mknod -m 666 /dev/net/tun c 10 200`
> 3. "unix: Unable to open a socket file: Bad address" - ioctl(SIOCUNIXFILE). Also absent in your kernel code.
> 4. "/proc/sys/kernel/sem_next_id is inaccessible" - this is present in code and under "CONFIG_CHECKPOINT_RESTORE".
>    BUT, if we take a look on Makefile:
>    `obj-$(CONFIG_SYSVIPC_SYSCTL) += ipc_sysctl.o`
>    we can see that we need to enable CONFIG_SYSVIPC_SYSCTL which is disabled in your config.

 I use `./criu check`, the output shows "looks good".
```
crosshatch:/criu # ./criu check
Warn  (criu/net.c:2910): Unable to get socket network namespace
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Warn  (criu/net.c:2910): Unable to get socket network namespace
Looks good.
```

When I try to dump the process. It shows other error:
```
Warn  (criu/net.c:2910): Unable to get socket network namespace
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Warn  (criu/net.c:2910): Unable to get socket network namespace
Error (criu/files-ext.c:96): Can't dump file 6 of that type [20666] (chr 10:59)
Error (criu/cr-dump.c:1345): Dump files (pid: 2751) failed with -1
Error (criu/cr-dump.c:1743): Dumping FAILED.
```

The test code:
```
#include <stdio.h>
#include <unistd.h>

int main() {
    long long i = 0;
    while(1) {
        printf("%lld\n", ++i);
        sleep(1);
    }
    return 0;
}
```

Would criu work perfectly if these errors have not fixed? (eg. `Unable to get socket network namespace`)

**Comment by adrianreber** [comment]
You should run CRIU with `-v4` for full debug output. The problem that you have is that your process has a device open which CRIU does not know how to handle:
```
Error (criu/files-ext.c:96): Can't dump file 6 of that type [20666] (chr 10:59)
```

On my local Android device that is
```
crw-rw----  1 system          system           10,  59 1971-06-18 05:47 faceauth
```

You need to close that device in your process before running CRIU or tell CRIU, using a plugin, how to handle such a device.

**Comment by mihalicyn** [comment]
>Would criu work perfectly if these errors have not fixed?

1. tun error is not important if you are not  planning to C/R tun devices
2. ioctl(SIOCUNIXFILE) has the middle level of importance :) If the system does not support it, then the socket mount id will be grabbed from root task mntns. C/R may break in some cases.
3. ioctl(get_socket_ns) used in `get_socket_ns` to get socket network namespace for unconnected/unbounded sockets (which is ignored by sockdiag interface). It's absence may also cause problems in some cases.

**Comment by hiyangyue** [comment]
> > Would criu work perfectly if these errors have not fixed?
> 
> 1. tun error is not important if you are not  planning to C/R tun devices
> 2. ioctl(SIOCUNIXFILE) has the middle level of importance :) If the system does not support it, then the socket mount id will be grabbed from root task mntns. C/R may break in some cases.
> 3. ioctl(SIOCGSKNS) used in `get_socket_ns` to get socket network namespace for unconnected/unbounded sockets (which is ignored by sockdiag interface). It's absence may also cause problems in some cases.

Thanks for the reply, it was very useful

**Comment by adrianreber** [comment]
@hiyangyue It sounds like your question was answered. Can you close this ticket?

**Comment by hiyangyue** [comment]
> @hiyangyue It sounds like your question was answered. Can you close this ticket?

done.
