### ISSUE TITLE
Test code using c library won't let me restore

### ISSUE THREAD

**Issue by niansa** [checkpoint-restore/criu#1466]
The code:

    #include <stdio.h>
    #include <stdlib.h>
    #include <fcntl.h>
    #include <string.h>
    #include <errno.h>
    #include <sys/stat.h>
    #include <sys/types.h>
    #include <criu/criu.h>
    
    
    void print_usage(const char *prgn) {
        fprintf(stderr, "Usage: %s <dump/restore> <pid>\n", prgn);
    }
    
    int main(int argc, char **argv) {
        // Get args
        if (argc < 3) {
            print_usage(argv[0]);
            return -1;
        }
        // Argument 1
        _Bool dump = strcmp(argv[1], "dump") == 0;
        if (!dump) {
            if (strcmp(argv[1], "restore") != 0) {
                print_usage(argv[0]);
                return -1;
            }
        }
        // Argument 2
        int target_pid = atoi(argv[2]);
        // Argument 3
        char *image_dir = "/tmp/proc_baks";
        if (argc > 3) {
            image_dir = argv[3];
        }
        // Initialize CRIU
        if (criu_init_opts() < 0) {
            return errno;
        }
        // Create/Open target dir
        mkdir(image_dir, 77777);
        int image_dir_fd = open(image_dir, O_DIRECTORY);
        if (image_dir_fd < 0) {
            perror("Failed to open image directory");
            return errno;
        }
        // Set options
        criu_set_service_address("/var/run/criu_service.socket");
        criu_set_pid(target_pid);
        criu_set_images_dir_fd(image_dir_fd);
        criu_set_shell_job(true);
        criu_set_log_level(4);
        // Perform operation
        {
            int res;
            if (dump) {
                res = criu_dump();
            } else {
                res = criu_restore();
            }
            if (res < 0 || (!dump && res == 0)) {
                if (errno) {
                    perror("Failed to perform operation");
                } else {
                    fprintf(stderr, "Unknown failure when performing operation\n");
                }
                return errno;
            }
        }
    }

Which just results in:

    Error (criu/tty.c:697): tty: Failed to set group 17561 on 0: Inappropriate ioctl for device
    Unknown failure when performing operation

I am really sure my code is working it's just some library bug...

**Comment by adrianreber** [comment]
Can you restore the process using the CRIU binary directly? Without the library?

**Comment by niansa** [comment]
Yep, without a problem.

**Comment by adrianreber** [comment]
Please share the log of failed restore and the command-line options for CRIU when it works using the CLI.

**Comment by niansa** [comment]
I am not able to get any more logging information except to that for some reason
    criu_set_log_file("./criu.log");

Results in
    Invalid request code

**Comment by niansa** [comment]
The working CLI command is:
    sudo criu restore --shell-job -D /tmp/proc_baks -t 13973

**Comment by adrianreber** [comment]
Try to set the log file with a full path. Not sure it works the way you do it.

**Comment by adrianreber** [comment]
Maybe also try `criu_restore_child()`.

**Comment by adrianreber** [comment]
Ah, you cannot use any path in the log file function. Just remove `./`.

**Comment by niansa** [comment]
> Ah, you cannot use any path in the log file function. Just remove `./`.

Does not create any file then

**Comment by niansa** [comment]
> Maybe also try `criu_restore_child()`.

    Error (criu/log.c:224): Can't create log file criu.log: Permission denied
    Error (criu/cr-service.c:403): Can't initiate log: Permission denied
    Failed to perform operation: Invalid request code

Doing the same thing as root raises no error but breaks terminal

**Comment by niansa** [comment]
With
    criu_set_service_binary("criu");
and normal
    criu_restore();

instead of using service and criu_restore_child() it breaks terminal too, again without doing anything at all.

**Comment by niansa** [comment]
Update: simply deadlocking at the the end of main() did the trick! But why??
