### ISSUE TITLE
(still) no good solution for inotify inode->path conversion (irmap)

### ISSUE THREAD

**Issue by chenhaiq** [checkpoint-restore/criu#147]
It always failed when dump a lxc ubuntu 14.04 instance with NetworkManager.

The pid 17890 is the process of NetworkManager, and no error if stop it.

```
(00.201179) Dumping opened files (pid: 17890)
(00.201180) ----------------------------------------
pie: __fetched msg: 13 0 0
pie: __sent ack msg: 13 13 0
pie: Daemon waits for command
(00.201195) Sent msg to daemon 13 0 0
(00.201200) Wait for ack 13 on daemon socket
(00.201201) Fetched ack: 13 13 0
(00.201210) 17890 fdinfo 0: pos: 0x               0 flags:           100002/0
(00.201220) Dumping path for 0 fd via self 76 [/dev/null]
(00.201224) fdinfo: type: 0x 1 flags: 0100002/0 pos: 0x       0 fd: 0
(00.201237) 17890 fdinfo 1: pos: 0x               0 flags:           100002/0
(00.201240) fdinfo: type: 0x 1 flags: 0100002/0 pos: 0x       0 fd: 1
(00.201245) 17890 fdinfo 2: pos: 0x               0 flags:           100002/0
(00.201248) fdinfo: type: 0x 1 flags: 0100002/0 pos: 0x       0 fd: 2
(00.201253) 17890 fdinfo 3: pos: 0x               0 flags:          2000002/0x1
(00.201255)     Searching for socket 332838 (family 1.0)
(00.201257)     Searching for socket 330e72 (family 1.0)
(00.201260) No filter for socket
(00.201261) sk unix: Dumping unix socket at 3
(00.201262) sk unix:    Dumping: ino 0x332838 peer_ino 0x330e72 family    1 type    2 state  7 name (null)
(00.201265) sk unix:    Dumped: id 0xc1 ino 0x332838 peer 0x330e72 type 2 state 7 name 0 bytes
(00.201267) fdinfo: type: 0x 5 flags: 02000002/01 pos: 0x       0 fd: 3
(00.201273) 17890 fdinfo 4: pos: 0x               0 flags:          2004002/0x1
(00.201284) eventfd: Dumping : id 0x0000c2 flags 0x80802 counter 0000000000000000
(00.201287) fdinfo: type: 0x 6 flags: 02004002/01 pos: 0x       0 fd: 4
(00.201292) 17890 fdinfo 5: pos: 0x               0 flags:          2004002/0x1
(00.201294)     Searching for socket 332839 (family 16.0)
(00.201298) No filter for socket
(00.201300) fdinfo: type: 0x d flags: 02004002/01 pos: 0x       0 fd: 5
(00.201305) 17890 fdinfo 6: pos: 0x               0 flags:          2000002/0x1
(00.201306)     Searching for socket 33283a (family 16.0)
(00.201309) No filter for socket
(00.201311) fdinfo: type: 0x d flags: 02000002/01 pos: 0x       0 fd: 6
(00.201315) 17890 fdinfo 7: pos: 0x               0 flags:          2004002/0x1
(00.201317)     Searching for socket 33283b (family 1.0)
(00.201318)     Searching for socket 33283c (family 1.0)
(00.201323) No filter for socket
(00.201324) sk unix: Dumping unix socket at 7
(00.201325) sk unix:    Dumping: ino 0x33283b peer_ino 0x33283c family    1 type    1 state  1 name (null)
(00.201328) sk unix:    Dumped: id 0xc5 ino 0x33283b peer 0x33283c type 1 state 1 name 0 bytes
(00.201330) sk unix:    Dumped: id 0x61 ino 0x33283c peer 0x33283b type 1 state 1 name 0 bytes
(00.201332) fdinfo: type: 0x 5 flags: 02004002/01 pos: 0x       0 fd: 7
(00.201342) 17890 fdinfo 8: pos: 0x               0 flags:          2004000/0x1
(00.201363) fsnotify: wd: wd 0x00000004 s_dev 0x0000002c i_ino 0x          330e22 mask 0x00000fce
(00.201365) fsnotify:   [fhandle] bytes 0x00000008 type 0x00000001 __handle 0x0000000000330e22:0x0000000000000000
(00.201367) fsnotify: Opening fhandle 2c:330e22...
(00.201372) mnt: Path `/' resolved to `./' mountpoint
(00.201376) Error (fsnotify.c:214): fsnotify: Can't open file handle for 0x0000002c:0x0000000000330e22: Stale file handle
(00.201378) Warn  (fsnotify.c:281): fsnotify:   Handle 0x2c:0x330e22 cannot be opened
(00.201380) irmap: Resolving 2c:330e22 path
(00.201385) irmap: Scanning /etc hint
....

(00.202289) irmap: Scanning /. hint
(00.202290) irmap: Refresh stat for /.
(00.202292) irmap: Scanning /no-such-path hint
(00.202293) irmap: Refresh stat for /no-such-path
(00.202300) Error (irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.202302) Error (fsnotify.c:284): fsnotify:   Can't dump that handle
(00.202305) ----------------------------------------
(00.202311) Error (cr-dump.c:1312): Dump files (pid: 17890) failed with -1
(00.202330) Waiting for 17890 to trap
```

**Comment by xemul** [comment]
The process keeps an inotify on some inode that sits on device 0x2c and has an i_num 0x330e22. Can you try to find out what this file is? I mean the name.

**Comment by tych0** [comment]
On Thu, Apr 14, 2016 at 02:59:11AM -0700, Pavel Emelyanov wrote:
> The process keeps an inotify on some inode that sits on device 0x2c and has an i_num 0x330e22. Can you try to find out what this file is? I mean the name.

You can do this via:

```
debugfs -R "ncheck $inode" /dev/$device
```

where $inode is the inode number above and the device is the one that
your rootfs is on.

**Comment by xemul** [comment]
Yes, thanks, @tych0 :)

**Comment by chenhaiq** [comment]
In error message:
```
(02.332615) fdinfo: type: 0x 5 flags: 02004002/01 pos: 0x       0 fd: 7
(02.332644) 32423 fdinfo 8: pos: 0x               0 flags:          2004000/0x1
(02.332686) fsnotify: wd: wd 0x00000004 s_dev 0x0000002b i_ino 0x          4d5e1c mask 0x00000fce
(02.332691) fsnotify:   [fhandle] bytes 0x00000008 type 0x00000001 __handle 0x00000000004d5e1c:0x0000000000000000
(02.332695) fsnotify: Opening fhandle 2b:4d5e1c...
(02.332707) mnt: Path `/' resolved to `./' mountpoint
(02.332716) Error (fsnotify.c:214): fsnotify: Can't open file handle for 0x0000002b:0x00000000004d5e1c: Stale file handle
(02.332724) Warn  (fsnotify.c:281): fsnotify:   Handle 0x2b:0x4d5e1c cannot be opened
(02.332729) irmap: Resolving 2b:4d5e1c path
(02.332739) irmap: Scanning /etc hint
```

pid 32423 is NetworkManager
0x4d5e1c is 5070364, which is /var/lib/lxc/i-t9nqfg6v/rootfs/lib/firmware

The lxc instance is running on top of overlayfs, which has mountinfo of:
`126 23 0:43 / /var/lib/lxc/i-t9nqfg6v/rootfs rw,relatime shared:106 - overlay rootfs rw,lowerdir=/opt/trustysrvx64f,upperdir=/pitrix/data/container/i-t9nqfg6v/upperdir,workdir=/pitrix/data/container/i-t9nqfg6v/workdir`

There are lots of error related to " Handle 0x2b:... cannot be opened", but only the one from NetworkManager is fatal.

**Comment by avagin** [comment]
It looks like https://github.com/xemul/criu/issues/136. A "wrong" devices is reported for overlayfs files.

**Comment by chenhaiq** [comment]
@avagin which device is wrong?

**Comment by avagin** [comment]
Hmm. In you case, we see the 0x2b (0:43) devices in mountinfo and fdinfo, so it may be another problem.

**Comment by avagin** [comment]
Could you try to add --irmap-scan-path /lib/firmware to other criu dump options?

**Comment by chenhaiq** [comment]
The " Handle 0x2b:... cannot be opened" error may come from two places:
1.  "<rootfs>/lib/firmware". Is this directory special to criu?
2. if above dir is deleted, it still has "can not be open" error by handle to "14 -> anon_inode:inotify" from NetworkManager.

Anyway, I can see there are lots of error about "Handle 0x2b:... cannot be opened", even it can be dumped successfully.

Looks like "Handle 0x2b:... cannot be opened" is not a fatal error. The error failed dumping may be this one:
irmap: Can't stat /no-such-path: No such file or directory

#136 has a similar error to it.

**Comment by chenhaiq** [comment]
@avagin with  --irmap-scan-path /lib/firmware, it still failed. The "can not be open" error is caused by handle to "14 -> anon_inode:inotify", which is exactly the same as I deleted /lib/firmware directory.

**Comment by avagin** [comment]
Yes, it isn't fatal. open_by_handle() doesn't work for overlayfs. If open_by_handle() doesn't work, we try to find an inode in the irmap cache.
https://criu.org/Irmap

**Comment by xemul** [comment]
@chenhaiq , I didn't get from the conversation whether adding the /lib/firmware to irmap scan path helped or not? Does dump work now? If it does, are you only worried by the Error-s in logs?

**Comment by chenhaiq** [comment]
@xemul adding the /lib/firmware to irmap scan path does not help. It still hit "can not be open" error by handle to "14 -> anon_inode:inotify", and failed in irmap cache. Dump does not work.

**Comment by xemul** [comment]
OK. This means that irmap scanner doesn't find an inode on overlayfs.

Would you show the dump.log with this patch:

diff --git a/criu/irmap.c b/criu/irmap.c
index a69776c..c62ab97 100644
--- a/criu/irmap.c
+++ b/criu/irmap.c
@@ -177,6 +177,8 @@ static struct irmap *irmap_scan(struct irmap *t, unsigned int dev, unsigned long
        if (t->dev == dev && t->ino == ino)
                return t;
 
+       pr_debug("\tmiss %x:%lx (%s)\n", t->dev, t->ino, t->path);
+
        if (irmap_update_dir(t))
                return NULL;

**Comment by chenhaiq** [comment]
log file can be found in:
[full log](https://pek3a.qingstor.com/oc-storage/dump.log)


```
(00.950830) irmap: Refresh stat for /lib/udev/scsi_id
(00.950833) irmap: 	miss 800001:e008e (/lib/udev/scsi_id)
(00.950837) irmap: Refresh stat for /lib/udev/collect
(00.950841) irmap: 	miss 800001:e009c (/lib/udev/collect)
(00.950842) irmap: Scanning /. hint
(00.950843) irmap: Refresh stat for /.
(00.950845) irmap: 	miss 7d:99ae93 (/.)
(00.950846) irmap: Scanning /no-such-path hint
(00.950847) irmap: Refresh stat for /no-such-path
(00.950856) Error (irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.950859) Error (fsnotify.c:284): fsnotify: 	Can't dump that handle
(00.950864) ----------------------------------------
(00.950872) Error (cr-dump.c:1312): Dump files (pid: 29353) failed with -1
```

**Comment by xemul** [comment]
@chenhaiq I don't see that criu scans for /lib/firmware. Have you added this path with the --irmap-scan-path option before trying my patch?

**Comment by chenhaiq** [comment]
@xemul the previous log does not contain error from NetworkManager. Looks like it failed before start dumping NetworkManager. It may be another error.

However, after restart the lxc instance, I can get the error from NetworkManager. You can see it in:
[dump2]( https://pek3a.qingstor.com/oc-storage/dump2.log)

This file is /lib/firmware:
`(02.910444) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x7d:0x99c09b cannot be opened`
```
# ls -id ./lib/firmware
10076315 ./lib/firmware
```

**Comment by xemul** [comment]
OK, but there's still no signs of scanning for /lib/formware. Again -- do you use the --irmap-scan-path option?

Please, add this patch too:

    diff --git a/criu/irmap.c b/criu/irmap.c
    index a69776c..c79cdb9 100644
    --- a/criu/irmap.c
    +++ b/criu/irmap.c
    @@ -261,7 +261,9 @@ char *irmap_lookup(unsigned int s_dev, unsigned long i_ino)
     	/* Let's scan any user provided paths first; since the user told us
     	 * about them, hopefully they're more interesting than our hints.
     	 */
    +	pr_debug("Scanning CLI hints\n");
     	list_for_each_entry(o, &opts.irmap_scan_paths, node) {
    +		pr_debug("`- scan [%s] cli hint\n", o->path);
     		c = irmap_scan(o->ir, s_dev, i_ino);
     		if (c) {
     			pr_debug("\tScanned %s\n", c->path);
    @@ -270,6 +272,7 @@ char *irmap_lookup(unsigned int s_dev, unsigned long i_ino)
     		}
     	}
     
    +	pr_debug("Scanning standard hints\n");
     	for (h = hints; h->path; h++) {
     		pr_debug("Scanning %s hint\n", h->path);
     		c = irmap_scan(h, s_dev, i_ino);

**Comment by chenhaiq** [comment]
[dump3](https://pek3a.qingstor.com/oc-storage/dump3.log)

0x2d:0x1107719 is /lib/firmware

I modified one line of your patch to:
``` 
               pr_debug("`- scan [%s] cli hint\n", o->ir->path);
```
The cmd line is:
`criu dump --tcp-established --file-locks --link-remap --force-irmap --manage-cgroups --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /var/lib/lxc/i-u7sasgor/dump -o /var/lib/lxc/i-u7sasgor/dump/dump.log -vvvvvv -t 13061 --freeze-cgroup /sys/fs/cgroup/freezer///lxc/i-u7sasgor --leave-running`

**Comment by xemul** [comment]
@chenhaiq you forgot to add option '--irmal-scan-path /lib/firmware' :) Thus criu doesn't look into /lib/firmware for fsnotify inodes at all.

**Comment by chenhaiq** [comment]
added '--irmap-scan-path /lib/firmware'.
[dump4](https://pek3a.qingstor.com/oc-storage/dump4.log)

**Comment by xemul** [comment]
@chenhaiq , thank you :) Now the /lib/formware is resolved, next unseen handle is 0x2d:0x1106923
:\ 

Would you find one on disk as you did for /lib/firmware?

@avagin , @tych0 , we need some better way of resolving inodes to paths. Any ideas?

**Comment by chenhaiq** [comment]
@xemul the handle 0x1106923 is not a file. It is "anon_inode:inotify"

**Comment by xemul** [comment]
@chenhaiq I meant the same as for the /lib/firmware. There's an inode 0x1106923 on device 0x2d (which is presumably /). Would you find one's path using the debugfs as Tycho suggested?

**Comment by chenhaiq** [comment]
[dump5](https://pek3a.qingstor.com/oc-storage/dump5.log)

The lxc instance for dump4 was destroyed. I created another dump log (with --irmap-scan-path /lib/firmware) to explain those inode handles. They can not be found by debugfs and are "anon_inode:inotify".

For example: in dump5, the last 5 errors:
```
(01.029730) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x39:0x2045156 cannot be opened
(01.029770) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x39:0x20440b1 cannot be opened
(01.029797) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x39:0x20452b7 cannot be opened
(01.029822) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x39:0x20451b6 cannot be opened
(01.030194) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x39:0x20437f9 cannot be opened
```
Their process id is 3724, which is NetworkManager. I can not find them in file system, because they are "anon_inode:inotify", and belong to fd 7 and 14. Those info can be found using "ls /proc/3724/fd/14".

```
/proc/3724/fdinfo# grep -H ino *
14:inotify wd:1 ino:20437f9 sdev:39 mask:8 ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:f937040200000000
7:inotify wd:4 ino:2045156 sdev:39 mask:fce ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:5651040200000000
7:inotify wd:3 ino:20440b1 sdev:39 mask:fce ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:b140040200000000
7:inotify wd:2 ino:20452b7 sdev:39 mask:fce ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:b752040200000000
7:inotify wd:1 ino:20451b6 sdev:39 mask:fce ignored_mask:0 fhandle-bytes:8 fhandle-type:1 f_handle:b651040200000000

/proc/3724/fdinfo# ls -l ../fd
lr-x------ 1 root root 64 Apr 26 15:53 14 -> anon_inode:inotify
lr-x------ 1 root root 64 Apr 26 15:53 7 -> anon_inode:inotify
```

**Comment by tych0** [comment]
On Tue, Apr 26, 2016 at 01:31:46AM -0700, Pavel Emelyanov wrote:
> @chenhaiq , thank you :) Now the /lib/formware is resolved, next unseen handle is 0x2d:0x1106923
> :\ 
> 
> Would you find one on disk as you did for /lib/firmware?
> 
> @avagin , @tych0 , we need some better way of resolving inodes to paths. Any ideas?

After talking about this problem with @hallyn, he suggested finding
some way to call `d_find_alias` from userspace, which should give us a
path (which we could stat for a sanity check). I'll see if I can
figure out a way to call this function in the existing code, but we
many need some small kernel patch to expose it.

**Comment by xemul** [comment]
@tych0 d_find_alias can report back so called "anonymous dentry" -- the one without a name :(

**Comment by xemul** [comment]
@chenhaiq , the messages "handle ... cannot be opened" mean that the dev:ino in question will be looked up in the irmap. All the handles you mention except the last one are found in it and are finally opened. The only one that is missing is the last one -- 0x39:0x20437f9.

Next, what you see in /proc/pid/fd/fdinfo is devices and inode numbers that are being watched by the descriptors in question -- by inotifies. And the inotifies themselves are anon_inode:inotify-s indeed, but we're looking for the inode being watched. The device 0x39 is the device where container root is located. Inode 0x20437f9 should be there unless it's unlinked.

I guess we need to dive into kernel to find out what this nasty inode is :\ What kernel are you using? If I give a kernel patch, will you be able to compile the kernel and boot it?

**Comment by chenhaiq** [comment]
0x39 is the mount point for overlay. I can not find inode with id of 0x20437f9 in it.
I am using kernel 4.4.0-21-generic (ubuntu 16.04), and able to compile the kernel and boot it.

**Comment by xemul** [comment]
OK, here's the patch against 4.4, let's try to checkpoint the stuff again, but right after it -- look into dmesg. Kernel will (should) print info about the inode read from inotify's fdinfo file

    diff --git a/fs/notify/fdinfo.c b/fs/notify/fdinfo.c
    index fd98e51..742c50b 100644
    --- a/fs/notify/fdinfo.c
    +++ b/fs/notify/fdinfo.c
    @@ -95,6 +95,22 @@ static void inotify_fdinfo(struct seq_file *m, struct fsnotify_mark *mark)
     			   mask, mark->ignored_mask);
     		show_mark_fhandle(m, inode);
     		seq_putc(m, '\n');
    +		{
    +			struct dentry *de;
    +
    +			printk("Read inode %x:%lx, i_nlink %d, i_flags %x, i_state %lx\n",
    +					inode->i_sb->s_dev, inode->i_ino, inode->i_nlink,
    +					inode->i_flags, inode->i_state);
    +			de = d_find_alias(inode);
    +			if (de) {
    +				const char *name;
    +				spin_lock(&de->d_lock);
    +				name = (const char *) de->d_name.name;
    +				printk("`- [%s]\n", name);
    +				spin_unlock(&de->d_lock);
    +			} else
    +				printk("`- <noname>\n");
    +		}
     		iput(inode);
     	}
     }

**Comment by chenhaiq** [comment]
error:
```
(00.012897) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x4a71 cannot be opened
(00.020313) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x4fa3 cannot be opened
(00.780394) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x5450 cannot be opened
(00.785765) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x4bdc cannot be opened
(01.394220) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x67c8 cannot be opened
(01.394283) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x54a8 cannot be opened
(01.394333) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x6a0b cannot be opened
(01.394382) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x69de cannot be opened
(01.395521) Warn  (fsnotify.c:281): fsnotify: 	Handle 0x2c:0x5005 cannot be opened
```
kernel log:

```
Apr 28 00:16:29 hyper4 kernel: [  332.530763] Read inode 2c:4a71, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:29 hyper4 kernel: [  332.530766] `- [etc]
Apr 28 00:16:29 hyper4 kernel: [  332.530792] Read inode 2c:4a71, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:29 hyper4 kernel: [  332.530793] `- [etc]
Apr 28 00:16:29 hyper4 kernel: [  332.538175] Read inode 2c:4fa3, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:29 hyper4 kernel: [  332.538177] `- [init]
Apr 28 00:16:29 hyper4 kernel: [  332.538212] Read inode 2c:4fa3, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:29 hyper4 kernel: [  332.538213] `- [init]
Apr 28 00:16:29 hyper4 kernel: [  332.632740] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:29 hyper4 kernel: [  332.788680] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:29 hyper4 kernel: [  332.944677] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:29 hyper4 kernel: [  333.092649] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:29 hyper4 kernel: [  333.244641] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:30 hyper4 kernel: [  333.298236] Read inode 2c:5450, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.298238] `- [system-services]
Apr 28 00:16:30 hyper4 kernel: [  333.298240] Read inode 2c:4bdc, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.298241] `- [system.d]
Apr 28 00:16:30 hyper4 kernel: [  333.298253] Read inode 2c:5450, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.298254] `- [system-services]
Apr 28 00:16:30 hyper4 kernel: [  333.298255] Read inode 2c:4bdc, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.298256] `- [system.d]
Apr 28 00:16:30 hyper4 kernel: [  333.388718] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:30 hyper4 kernel: [  333.540720] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:30 hyper4 kernel: [  333.672766] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:30 hyper4 kernel: [  333.856744] cgroup: new mount options do not match the existing superblock, will be ignored
Apr 28 00:16:30 hyper4 kernel: [  333.911893] Read inode 2c:67c8, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911899] `- [firmware]
Apr 28 00:16:30 hyper4 kernel: [  333.911906] Read inode 2c:54a8, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911908] `- [NetworkManager]
Apr 28 00:16:30 hyper4 kernel: [  333.911914] Read inode 2c:6a0b, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911916] `- [system-connections]
Apr 28 00:16:30 hyper4 kernel: [  333.911921] Read inode 2c:69de, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911924] `- [VPN]
Apr 28 00:16:30 hyper4 kernel: [  333.911978] Read inode 2c:67c8, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911980] `- [firmware]
Apr 28 00:16:30 hyper4 kernel: [  333.911985] Read inode 2c:54a8, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911987] `- [NetworkManager]
Apr 28 00:16:30 hyper4 kernel: [  333.911992] Read inode 2c:6a0b, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.911994] `- [system-connections]
Apr 28 00:16:30 hyper4 kernel: [  333.911999] Read inode 2c:69de, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912001] `- [VPN]
Apr 28 00:16:30 hyper4 kernel: [  333.912349] Read inode 33:1e, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912352] `- [users]
Apr 28 00:16:30 hyper4 kernel: [  333.912358] Read inode 33:1f, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912360] `- [sessions]
Apr 28 00:16:30 hyper4 kernel: [  333.912365] Read inode 33:1d, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912367] `- [seats]
Apr 28 00:16:30 hyper4 kernel: [  333.912404] Read inode 33:1e, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912407] `- [users]
Apr 28 00:16:30 hyper4 kernel: [  333.912411] Read inode 33:1f, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912413] `- [sessions]
Apr 28 00:16:30 hyper4 kernel: [  333.912418] Read inode 33:1d, i_nlink 2, i_flags 0, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.912420] `- [seats]
Apr 28 00:16:30 hyper4 kernel: [  333.913253] Read inode 2c:5005, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.913258] `- [hostname]
Apr 28 00:16:30 hyper4 kernel: [  333.913299] Read inode 2c:5005, i_nlink 1, i_flags 82, i_state 0
Apr 28 00:16:30 hyper4 kernel: [  333.913301] `- [hostname]
```

**Comment by xemul** [comment]
OK, so presumably the inode 0x2c:0x5005 is the one that cannot be opened and resolved. According to dmesg this is an _alive_ inode (link count is 1) with standard flags and state. The name of the inode in question is "hostname". Hm... Presumably this is /etc/hostname, but this is not guaranteed :)

Would you do

find / -name hostname

over the container's root and check these file's dev:ino pairs?

**Comment by avagin** [comment]
inotify fdinfo contains "real" inode numbers:
```
                seq_printf(m, "inotify wd:%x ino:%lx sdev:%x mask:%x ignored_mask:%x ",
                          inode_mark->wd, inode->i_ino, inode->i_sb->s_dev,
                          mark->mask, mark->ignored_mask);
```

stat() calls ovl_getattr and shows inode numbers from an underline file system.
```
static int ovl_getattr(struct vfsmount *mnt, struct dentry *dentry,
                         struct kstat *stat)
{
        struct path realpath;

        ovl_path_real(dentry, &realpath);
        return vfs_getattr(&realpath, stat);
}
```

**Comment by tych0** [comment]
Hi avagin,

Is your reply in reference to how to do inode->filepath mapping? I don't understand what to stat in this case to get the filepath out of the real inode once we have it.

**Comment by avagin** [comment]
FYI: inotify-s doesn't work for files on overlayfs
https://gist.github.com/avagin/a70a68bee80e72643389dc3e793a5382

**Comment by avagin** [comment]
I think this issue should be fixed in kernel. What do you think about this patch:
https://github.com/avagin/linux-task-diag/commit/db3bf205180524a4829b49d80bcbc5a917518f11

**Comment by chenhaiq** [comment]
@xemul
There are 4 files with name of hostname. You can find inode in below:

/etc/hostname             0xC79F6
/usr/share/doc/hostname   0xA009
/bin/hostname             0x100027
/proc/sys/kernel/hostname 0xCC55D

**Comment by avagin** [comment]
@chenhaiq, can you compile a kernel with https://github.com/avagin/linux-task-diag/commit/db3bf205180524a4829b49d80bcbc5a917518f11  and try to dump the container on this kernel. It works for me.

**Comment by avagin** [comment]
My patch is wrong, because inode numbers are not permanent in this case. Probably we need to modify code to print correct inode numbers in inotify fdinfo files.

**Comment by xemul** [comment]
@avagin "correct" is not the underlying one ;)

**Comment by xemul** [comment]
@avagin for inode number to permanent is not ... critical for this case. We only need stat() to report the overlayfs' inode instead of the underlying one. So you patch should help the issue, though it's not 100% correct.

**Comment by chenhaiq** [comment]
@avagin your patch works for me with option "--irmap-scan-path /lib/firmware"

Why it has error with /lib/firmware directory?

**Comment by avagin** [comment]
@chenhaiq do you ask why you need to specify this option? It's because open_by_handle() doesn't work for overlayfs files and criu has to search files by inode numbers in the irmap cache. You can find more information about irmap cache here: https://criu.org/Irmap
criu has a set of predefined paths to build irmap cache: https://github.com/xemul/criu/blob/master/criu/irmap.c#L57. If you have inotify-s to files from other directories, you need specify them with help of --irmap-scan-path.

**Comment by chenhaiq** [comment]
@avagin Do you mean that all applications depended on inotify-s can not be dumped unless irmap cache contain the file of inotify-s?
This sounds like a huge limitation of using criu with overlayfs.

**Comment by avagin** [comment]
overlayfs is in development now. It doesn't look like a production ready solution.

My patch will not be accepted into the kernel in this form, so we can say that criu can't dump inotify-s with files on overlayfs. Could you report about this problem to overlayfs developers? I think stat() and inotify fdinfo files should report the same inode numbers for a file.

**Comment by chenhaiq** [comment]
@avagin did you involve Miklos Szeredi for this issue? I found "CC: Miklos Szeredi" in comment of your kernel patch.

**Comment by xemul** [comment]
@chenhaiq 
> Do you mean that all applications depended on inotify-s can not be dumped
> unless irmap cache contain the file of inotify-s?
> This sounds like a huge limitation of using criu with overlayfs.

Yes, this is a big problem for CRIU.

Inotifies are attached to files using paths, but then the path information is lost and we only have the inode number at hands. And there's not easy way to get the path back. The irmap is the best workaround we have so far -- it scans for pre-hinted paths looking for the inode in question. And list of pre-hinted paths is quite incomplete. We try to keep it up-to-date, but, as you see, sometimes miss :)

If you have any ideas how to solve this, you're welcome!

**Comment by danbeaulieu** [comment]
Hi, we are interested in the latest thinking on this issue. We are able to reproduce with criu 3.12 and docker 18.09.2 using overlay2 on kernel 4.9.0 (also reproduces on docker 17.09.1-ce with overlay and kernel 4.14.137)

```
$ docker run -d --name waiter ubuntu:18.04 sh -c 'apt-get update; apt-get install -y inotify-tools; touch /etc/foobar; inotifywait -m /etc/foobar'
# wait for container to run the wait...
$ docker checkpoint create waiter cr
Error response from daemon: Cannot checkpoint container waiter: runc did not terminate sucessfully: criu failed: type NOTIFY errno 0 path= /run/containerd/io.containerd.runtime.v1.linux/moby/d664c21edd993c69b556c3a3dbf147406fee894f535fa7fb11947b88bb560a2b/criu-dump.log: unknown
```
[criu-dump.log](https://github.com/checkpoint-restore/criu/files/3731369/criu-dump.log)

dump log shows the irmap looks at /etc/foobar so I don't think it is a matter of adding it to the irmap scan path:

```
(00.312064) irmap: Refresh stat for /etc/foobar
```

This issue was last updated over 3 years ago. Has anything changed where we can checkpoint containers using overlay that have an inotify watch?

**Comment by avagin** [comment]
> Has anything changed where we can checkpoint containers using overlay that have an inotify watch?

@danbeaulieu No, nothing changed. If you want, you can fix this issue. I can help if you will have any question.
