### ISSUE TITLE
Dump docker container failture : Error (criu/tty.c:2430): tty: Unable to find a master for /0

### ISSUE THREAD

**Issue by lolo-pop** [checkpoint-restore/criu#1480]
I want to use CRIU's memory change tracking to reduce the migration time of live migration. However, I am getting the following error when using `criu dump`. 

> (06.909153) 0x7fff7f9db000-0x7fff7f9dd000 (8K) prot 0x5 flags 0x22 fdflags 0 st 0x209 off 0 reg vdso ap  shmid: 0
(06.909156) 0xffffffffff600000-0xffffffffff601000 (4K) prot 0x5 flags 0x22 fdflags 0 st 0x204 off 0 vsys ap  shmid: 0
(06.909161) Obtaining task auvx ...
(06.909948) Dumping task cwd id 0x10 root id 0x11
(06.910187) mnt: Dumping mountpoints
(06.910192) mnt: 	1576: cc:/ @ ./sys/firmware
(06.916935) mnt: 	1575: cb:/ @ ./proc/scsi
(06.923530) mnt: 	1574: c4:/null @ ./proc/sched_debug
(06.923547) mnt: Mount is not fully visible ./dev
(06.923599) mnt: 	mount has children ./dev
(06.944690) mnt: 	1564: c4:/null @ ./proc/timer_list
(06.944716) mnt: 	1536: c4:/null @ ./proc/keys
(06.944724) mnt: 	1535: c4:/null @ ./proc/kcore
(06.944731) mnt: 	1534: ca:/ @ ./proc/acpi
(06.951536) mnt: 	1533: c9:/ @ ./proc/asound
(06.958392) mnt: 	1532: c3:/sysrq-trigger @ ./proc/sysrq-trigger
(06.958416) mnt: 	1531: c3:/sys @ ./proc/sys
(06.958423) mnt: 	1530: c3:/irq @ ./proc/irq
(06.958429) mnt: 	1529: c3:/fs @ ./proc/fs
(06.958434) mnt: 	1528: c3:/bus @ ./proc/bus
(06.958440) mnt: 	1527: c5:/0 @ ./dev/console
(06.958449) Error (criu/tty.c:2430): tty: Unable to find a master for /0
(06.958916) Unlock network
(06.958965) Running network-unlock scripts
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(06.965124) Unfreezing tasks into 1
(06.965152) 	Unseizing 16871 into 1
(06.965168) 	Unseizing 16988 into 1
(06.966536) Error (criu/cr-dump.c:1768): Dumping FAILED.

I used the following command to create the docker container. 

> docker run -it --name userserver --net staticnet --ip 192.168.0.2 tf-test:v1

I used the following command to use the `CRIU dump`.

> CID=`docker inspect --format="{{.Id}}" userserver`
PID=`docker inspect --format="{{.State.Pid}}" userserver`
ROOT=`docker inspect --format="{{.GraphDriver.Data.MergedDir}}" userserver`

> criu dump -o dump.log -v4 -t $PID -D image/1 --root $ROOT \
--ext-mount-map /etc/resolv.conf:/etc/resolv.conf --ext-mount-map /etc/hosts:/etc/hosts \
--ext-mount-map /etc/hostname:/etc/hostname --evasive-devices --manage-cgroups \
--ext-mount-map /.dockerinit:/.dockerinit --ext-mount-map /sys/fs/cgroup/memory:/sys/fs/cgroup/memory \
--ext-mount-map /sys/fs/cgroup/blkio:/sys/fs/cgroup/blkio \
--ext-mount-map /sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer \
--ext-mount-map /sys/fs/cgroup/hugetlb:/sys/fs/cgroup/hugetlb \
--ext-mount-map /sys/fs/cgroup/devices:/sys/fs/cgroup/devices \
--ext-mount-map /sys/fs/cgroup/cpu,cpuacct:/sys/fs/cgroup/cpu,cpuacct \
--ext-mount-map /sys/fs/cgroup/net_cls,net_prio:/sys/fs/cgroup/net_cls,net_prio \
--ext-mount-map /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset \
--ext-mount-map /sys/fs/cgroup/perf_event:/sys/fs/cgroup/perf_event \
--ext-mount-map /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd \
--ext-mount-map /sys/fs/cgroup/rdma:/sys/fs/cgroup/rdma \
--ext-mount-map /sys/fs/cgroup/pids:/sys/fs/cgroup/pids \
--leave-running --tcp-established --track-mem
 
CRIU version : 3.15
`criu -V
Version: 3.15`

system version: ubuntu 18.04
`uname -a
Linux node2 4.15.0-139-generic #143-Ubuntu SMP Tue Mar 16 01:30:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by adrianreber** [comment]
Using CRIU to dump a container standalone is always difficult and I am not sure anyone is using it like this. The recommendation is to always use the built-in checkpoint/restore support in the container runtime/engine.

Podman has support to use pre-dump. Maybe you could try that. Or, instead of using CRIU directly to dump your container. Look at what runc does to checkpoint/restore a container with pre-copy and post-copy support.

The easiest solution would be to just use Podman.

**Comment by lolo-pop** [comment]
> Using CRIU to dump a container standalone is always difficult and I am not sure anyone is using it like this. The recommendation is to always use the built-in checkpoint/restore support in the container runtime/engine.
> 
> Podman has support to use pre-dump. Maybe you could try that. Or, instead of using CRIU directly to dump your container. Look at what runc does to checkpoint/restore a container with pre-copy and post-copy support.
> 
> The easiest solution would be to just use Podman.

I chose to use CRIU because I wanted to use the iterative migration feature. Does Podman also support this feature? If Podman also supports this feature, I will try it.

**Comment by adrianreber** [comment]
Yes, Podman supports that. A single pre-dump: http://docs.podman.io/en/latest/markdown/podman-container-checkpoint.1.html#pre-checkpoint-p

**Comment by lolo-pop** [comment]
Thank you for your help.

**Comment by adrianreber** [comment]
> > Yes, Podman supports that. A single pre-dump: http://docs.podman.io/en/latest/markdown/podman-container-checkpoint.1.html#pre-checkpoint-p
> 
> Hello, I'm sorry to bother you again, but does Podman support only one round of iterative migration?

Yes.

> I am more in need of a tool that enables multiple rounds of iterative migration. When a non-I/O intensive task is migrated, I think multiple rounds of iterative migration can help reduce the amount of state data being transferred, e.g. we can gradually reduce the interval between iterations to reduce the state data.
> 
> Can you provide some suggestions? Thank you for your reply!

Someone needs to implement it for Podman. So far no one has stepped up. If it is important for you, maybe it something you could do.

Closing this again as this is not a CRIU issue.

**Comment by rst0git** [comment]
>I am more in need of a tool that enables multiple rounds of iterative migration.

It depends on your use case, but you can use `runc checkpoint` with `--pre-dump` and `--parent-path`.

**Comment by lolo-pop** [comment]
> > I am more in need of a tool that enables multiple rounds of iterative migration.
> 
> It depends on your use case, but you can use `runc checkpoint` with `--pre-dump` and `--parent-path`.

Thanks
