### ISSUE TITLE
Run runc container over SSH

### ISSUE THREAD

**Issue by mouri11** [checkpoint-restore/criu#1488]
I am working on a cluster of runc containers running in AWS EC2 Ubuntu 18.04 x86_64 instances. I intend to have one master node run the containers in all the other nodes via SSH. I am using the following bash script in the master node:
```
#!/bin/bash
while read node
do
      ssh user@$node "cd ~/mycont; sudo runc run mycont"
done <active
```
The "active" file contains list of remote IPs for the EC2 instances. Running this results in an error similar to the one below
```level=error msg="open /dev/tty: no such device or address"```

Running the runc command by directly accessing the remote terminal via SSH works, but not in this inline format. Also, using ```ssh -t``` works as inline in the local terminal, but not in the bash script.

I am not sure what I am missing here. I don't have an in-depth knowledge of how SSH issues the commands: in the remote terminal, or by creating a terminal in the local machine. Also, will restoring the container via inline SSH have any issues? Any help would be appreciated.

Edit: Does it have anything to do with ```terminal: true``` in config.json?

**Comment by adrianreber** [comment]
Why are you asking `runc run` questions here?

So far this seems unrelated to CRIU.

I would recommend, however, redirecting stdin, stdout and stderr to /dev/null for checkpointing and restoring.

**Comment by mouri11** [comment]
Ok. My bad. Thanks for the pointers.
