### ISSUE TITLE
Problem restoring container containing tun device

### ISSUE THREAD

**Issue by seanrmurphy** [checkpoint-restore/criu#1499]
Hi,

I'm having an issue which seems similar to this unresolved issue - https://github.com/checkpoint-restore/criu/issues/838 - namely when I perform a restore via `podman` it fails, giving this error

```
(00.047285)     10: Error (criu/tun.c:391): tun: No tun device for file tap0
```

The setup is as follows:
- a tun/tap device is created manually within the container
- we are using qemu in a container which picks up the above tun/tap and connects to it
- the checkpointing operation works via `podman` without any problems, but dumping `network.status` does not show the tun/tap device
- I guess the restore is restoring qemu properly, which expects the tun device to exist, but it has not been captured by criu and hence the error occurs

I'm working on:
```
# podman --version
podman version 3.1.2
# criu --version
Version: 3.15
# crun --version
crun version 0.19.1
commit: 1535fedf0b83fb898d449f9680000f729ba719f5
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
# cat /etc/os-release 
NAME=Fedora
VERSION="33 (Cloud Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
<snip>
```

Any thoughts/pointers on how to handle this appreciated.

**Comment by adrianreber** [comment]
Unfortunately this is not easy to solve. In contrast to Docker/LXC CRIU does not touch the network namespace when using Podman. In combination with Podman we restore into an existing network namespace that has been set up by Podman/CNI.

In the Podman case CRIU completely ignores the network namespace and so all changes you do to the network namespace, in your case the tun/tap device, will not be checkpointed and restored.

You need to include the tun/tap device creation somehow in how CNI sets up the network namespace for the container. Not sure if that is doable.

So this is not a CRIU problem but a Podman/CNI problem. It is also not solvable by Podman as the tun/tap creation happens manually. No idea how to solve it.

CRIU's action scripts could help, but I am not sure anybody used them in combination with Podman. Maybe through a CRIU config file.

**Comment by seanrmurphy** [comment]
Thanks so much for the speedy response!

> In combination with Podman we restore into an existing network namespace that has been set up by Podman/CNI.

By 'existing', I guess you mean created by `podman` as part of the restore operation - is this correct?

> In the Podman case CRIU completely ignores the network namespace and so all changes you do to the network namespace, in your case the tun/tap device, will not be checkpointed and restored.

Clear and helpful - thanks!

> You need to include the tun/tap device creation somehow in how CNI sets up the network namespace for the container. Not sure if that is doable.

Thanks - will look into it.

> So this is not a CRIU problem but a Podman/CNI problem. It is also not solvable by Podman as the tun/tap creation happens manually. No idea how to solve it.

Ok - not a good sign...

> CRIU's action scripts could help, but I am not sure anybody used them in combination with Podman. Maybe through a CRIU config file.

Thanks again for the pointers - if I find some workable approach, I'll update.

**Comment by adrianreber** [comment]
> > In combination with Podman we restore into an existing network namespace that has been set up by Podman/CNI.
> 
> By 'existing', I guess you mean created by `podman` as part of the restore operation - is this correct?

Yes. Created by `podman` using CNI.

**Comment by seanrmurphy** [comment]
I don't have a complete solution to my problem as yet, but I'll put this here as it might help someone in future... @bboreham pointed me in this direction on CNI slack...

AWS has developed a CNI plugin called `tc-redirect-tap` (https://github.com/awslabs/tc-redirect-tap) which can create a `tap`  in a netns; an example use case is that a `tap` interface gets created along with a `veth` pair (using CNI `ptp` plugin) in the container namespace - the `tc-redirect-tap` plugin redirects traffic from the `tap` interface to one end of the `veth` pair which then ends up at the other end of the `veth` pair, usually in a host bridge.

This is a mechanism by which CNI can create the `tap`, obviating the need for manually creating it - this approach can probably be handled better by `podman`/`criu`.

For me, this addresses the `tun`/`tap` issue, so I'll close this.

**Comment by seanrmurphy** [comment]
As noted above, there is a solution for bringing up the container by which CNI creates the `tap` and `qemu` can connect to it.

I am still unclear around whether all of this needs to be run in privileged mode - there seems to be a bug in `podman` handling restore of privileged containers which some redhat folks are currently looking into.

Trying the unprivileged approach, it's possible to `run` the container with `CAP_NET_ADMIN` and `--device /dev/net/tun`; it's then possible to perform a checkpoint; however, the restore fails with `criu` still being unable to find the `tun`
 
```
(00.038679)      2: Error (criu/tun.c:391): tun: No tun device for file tap0
(00.038696)      2: Error (criu/files.c:1215): Unable to open fd=11 id=0xba
```

Here is a dump of the `network.status` file generated as part of the checkpoint:

```
[root@ip-10-0-2-102 tmp]# cat network.status
[
  {
    "cniVersion": "0.4.0",
    "interfaces": [
      {
        "name": "veth684702b9",
        "mac": "f2:ea:e8:33:92:c5"
      },
      {
        "name": "eth0",
        "mac": "ba:6a:d2:ad:32:b1",
        "sandbox": "/run/netns/cni-8e5bf32f-759c-2010-1ded-40fe9eec25e4"
      },
      {
        "name": "tap0",
        "sandbox": "/run/netns/cni-8e5bf32f-759c-2010-1ded-40fe9eec25e4"
      },
      {
        "name": "tap0",
        "mac": "ba:6a:d2:ad:32:b1",
        "sandbox": "0b53ae153cb749b785e040b1857e3c4a06c9f705ea8dbf1792a9bac1d0342d73"
      }
    ],
    "ips": [
      {
        "version": "4",
        "interface": 1,
        "address": "192.168.10.4/24",
        "gateway": "192.168.10.1"
      },
      {
        "version": "4",
        "interface": 3,
        "address": "192.168.10.4/24",
        "gateway": "192.168.10.1"
      }
    ],
    "dns": {
      "nameservers": [
        "127.0.0.53"
      ],
      "search": [
        "eu-west-1.compute.internal"
      ],
      "options": [
        "edns0",
        "trust-ad"
      ]
    }
  }
```

I'm not sure if this is an issue with `criu`, `cni`, or `podman` (or interactions between them)- the issue is raised by `criu` so that's why I'm reporting here first....

**Comment by adrianreber** [comment]
Not sure. I guess the network namespace is not set up in a way that CRIU expects. So right now I think this might be a CNI problem. I guess no one has ever used CRIU to do what you are trying to do, so it could be that it is just unexpected. Not sure.

@avagin Do you know if restoring into an existing network namespace should work with tun devices?

**Comment by seanrmurphy** [comment]
Just to be clear - it's not specifically my intention to have the restore process restore to an **existing** netns - if that is the best solution, I'm fine with it, but if CNI automatically creates a new netns in the appropriate manner, that's fine. Also, if CNI needs to recreate a netns with a specific ID (eg the ID defined in the `network.status` file), that's fine too.

**Comment by adrianreber** [comment]
> Just to be clear - it's not specifically my intention to have the restore process restore to an **existing** netns

If you want to use Podman CRIU is required to restore into an existing network namespace, because that is how Podman works. It tells CNI to create a network namespace and then tells CRIU to restore the process into it. Right now either CNI does not create the network namespace correctly or CRIU cannot handle restoring processes into an existing network namespace with existing tun devices.

**Comment by seanrmurphy** [comment]
Thanks (again) for the v helpful clarification...

**Comment by bboreham** [comment]
I'm not aware of any cases where CNI creates a network namespace; IME it is told to use an existing one.

**Comment by adrianreber** [comment]
> I'm not aware of any cases where CNI creates a network namespace; IME it is told to use an existing one.

Sorry, that was then wrong. From my standpoint, checkpoint restore, Podman or CNI creates the network namespace and Podman tells runc tells CRIU to restore into the network namespace. I assumed that CNI also creates the network namespace but it seems, from your comment, it only configures it after it has been setup by someone else.

Whoever does creates the network namespace, CRIU is told to restore into an existing network namespace by runc and that network namespace is not in a form CRIU expects or CRIU cannot restore processes with tun devices open into an existing network namespace.
