### ISSUE TITLE
Can the --lazy-page feature be adapted for restoring process over and over again?

### ISSUE THREAD

**Issue by LiuChangFreeman** [checkpoint-restore/criu#1502]
I'm trying to eliminate process restoring time using the `--lazy-page` feature but later I find that it seems to be designed  only 
 for one-time C/R.    
So I'm wondering is it possible to change the strategy to checkpoint once and restore many times?    
![Criu-memory-wflow](https://user-images.githubusercontent.com/20047907/121519400-42021c00-ca24-11eb-9e5f-3ab4c1959972.png)    
The procedure I want to make is as followed:  
1. Run a process which will consume a lot of memory pages.
2. Dump the meta data to `/home/lazy/checkpoint` and leave the pages not dumped.  
```
criu dump --tree $PID --images-dir /home/lazy/checkpoint --lazy-pages --address 127.0.0.1 --port 7000  
```
3. Modify the ip/port/paths to prepare new resources for the new restored process to use.  
```
crit decode -i /home/lazy/checkpoint/files.img --pretty >> /home/lazy/checkpoint/files.json
// modify the files.json
crit encode -i /home/lazy/checkpoint/files.json -o /home/lazy/checkpoint/files.img
```
4. Start the page server which will connect to `127.0.0.1:7000` to ask for pages transferring.
```
criu lazy-pages --images-dir /home/lazy/checkpoint --page-server --address 127.0.0.1 --port 7000  
```
5. Restore the process with modified meta and lazy restored pages.  
```
criu restore --images-dir /home/lazy/checkpoint --lazy-pages
```

I wish the step 3-5 can be done over and over again so that I can always restore a process from the page server without reading pages from filesystem and  pausing for pages restore complete.  
Also I want to know is it possible to use the `--lazy-page` feature without page server.   
It's a pity to use the `--lazy-page` only for migration and I think it may also should be introduced into local C/R.

**Comment by adrianreber** [comment]
If I remember it correctly this will not work because for lazy-pages we are not reading the pages from the disk but directly from CRIU which is running as a server on port 7000 (step 2). You would need to changes `criu lazy-pages` to not read from another CRIU process like in step 2, but it would need to read the pages directly from pages-*.img.

Restoring processes lazily via userfaultfd is really much slower than just a simple restore from disk. If you already have you process written to disk lazy restore only makes it really slow.

**Comment by LiuChangFreeman** [comment]
> If I remember it correctly this will not work because for lazy-pages we are not reading the pages from the disk but directly from CRIU which is running as a server on port 7000 (step 2). You would need to changes `criu lazy-pages` to not read from another CRIU process like in step 2, but it would need to read the pages directly from pages-*.img.
> 
> Restoring processes lazily via userfaultfd is really much slower than just a simple restore from disk. If you already have you process written to disk lazy restore only makes it really slow.

Thanks. In my situation, the process need only be restored as quickly as possible and the performance is not very important.    
So I think it may be a good idea to let the pages restore later to achieve the lowest restore time which means the restored process will not need to access all the memory pages the time when it is booted.   
Though the total time may be much slower than restoring from disk, it can reduce the time before the process can do anything.  
Have you ever compared the two methods(restore from disk via page-server) in such situations?

**Comment by adrianreber** [comment]
> So I think it may be a good idea to let the pages restore later to achieve the lowest restore time which means the restored process will not need to access all the memory pages the time when it is booted.
> Though the total time may be much slower than restoring from disk, it can reduce the time before the process can do anything.
> Have you ever compared the two methods(restore from disk via page-server) in such situations?

I would say it is at least a factor 10 slower. For every single page, in the beginning, there is one page fault a TCP request to the server and back to the client. It has a lot of room for optimization, but as far I as remember we never optimized it. If you are interested you are more than welcome.

lazy-migration usually only makes sense with pre-copy migration

**Comment by LiuChangFreeman** [comment]
> > So I think it may be a good idea to let the pages restore later to achieve the lowest restore time which means the restored process will not need to access all the memory pages the time when it is booted.
> > Though the total time may be much slower than restoring from disk, it can reduce the time before the process can do anything.
> > Have you ever compared the two methods(restore from disk via page-server) in such situations?
> 
> I would say it is at least a factor 10 slower. For every single page, in the beginning, there is one page fault a TCP request to the server and back to the client. It has a lot of room for optimization, but as far I as remember we never optimized it. If you are interested you are more than welcome.
> 
> lazy-migration usually only makes sense with pre-copy migration

May I ask you more about the `page server`?   
I'm preparing to rewrite the page server which can read pages from disk files such as `pages-n.img` from previous checkpoint and store them in its own memory. Then I will try to use the new page server to handle the `one page fault a TCP request` just like what the server create in this step do:  
```
// Dump the meta data to /home/lazy/checkpoint and leave the pages not dumped.
criu dump --tree $PID --images-dir /home/lazy/checkpoint --lazy-pages --address 127.0.0.1 --port 7000  
```
Do you think it easy to do this job? Or is there any difficulty which is hard to deal with? Thank you for being patient with me.

**Comment by adrianreber** [comment]
> Do you think it easy to do this job? Or is there any difficulty which is hard to deal with? Thank you for being patient with me.

It think it should be doable.

@rppt did I remember it correctly? Do you think creating a page server from dumped filed would be difficult?

**Comment by LiuChangFreeman** [comment]
> > Do you think it easy to do this job? Or is there any difficulty which is hard to deal with? Thank you for being patient with me.
> 
> It think it should be doable.
> 
> @rppt did I remember it correctly? Do you think creating a page server from dumped filed would be difficult?

This feature has just been supported by:
```
criu lazy-pages --images-dir DIR
```
