### ISSUE TITLE
write() argument must be str, not bytes

### ISSUE THREAD

**Issue by EaZyq** [checkpoint-restore/criu#1505]
pls help me i got this issue

crit encode -i cgroup.json -o crgoup.img
Traceback (most recent call last):
  File "/usr/bin/crit", line 6, in <module>
    cli.main()
  File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 410, in main
    opts["func"](opts)
  File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 50, in encode
    pycriu.images.dump(img, outf(opts))
  File "/usr/lib/python3/dist-packages/pycriu/images/images.py", line 625, in dump
    f.write(struct.pack('i', magic.by_name['IMG_COMMON']))
TypeError: write() argument must be str, not bytes

**Comment by adrianreber** [comment]
Which version do you use? This should be already fixed in the development branch `criu-dev`.

**Comment by EaZyq** [comment]
I'm using 3.15 on ubuntu

**Comment by rst0git** [comment]
This issue appears to have been fixed with https://github.com/checkpoint-restore/criu/pull/1388

**Comment by EaZyq** [comment]
yes it does work thank you!!!

**Comment by EaZyq** [comment]
now i got this issue:

criu restore -D checkpoint
     1: Error (criu/net.c:2468): Unable to find an external netns: extRootNetNS
     1: Error (criu/cr-restore.c:1827): Can't unshare net-namespace: No such file or directory
Error (criu/cr-restore.c:2483): Restoring FAILED.

any quick solve pls?

**Comment by adrianreber** [comment]
How did you do the checkpoint?

**Comment by EaZyq** [comment]
i got it from a ctf challenge

**Comment by EaZyq** [comment]
there is "net" in error name so i think this may help:
network.status
[
  {
    "cniVersion": "0.4.0",
    "interfaces": [
      {
        "name": "cni-podman0",
        "mac": "ce:c3:6c:a9:64:fc"
      },
      {
        "name": "veth7b23ba41",
        "mac": "a6:e1:b7:a8:55:08"
      },
      {
        "name": "eth0",
        "mac": "46:13:28:62:42:dc",
        "sandbox": "/run/netns/cni-a8181caa-d269-17e9-1b2a-10cf157230be"
      }
    ],
    "ips": [
      {
        "version": "4",
        "interface": 2,
        "address": "10.88.0.4/16",
        "gateway": "10.88.0.1"
      }
    ],
    "routes": [
      {
        "dst": "0.0.0.0/0"
      }
    ],
    "dns": {}
  }
]

**Comment by adrianreber** [comment]
Are you trying to restore a container? 

Use podman container restore. It is difficult to restore a container checkpoint without the container engine. Why are you using criu directly?

**Comment by EaZyq** [comment]
bruh i searched google for a way to restore a checkpoint and criu came up so i think i should use that
im a noob btw
sry

**Comment by adrianreber** [comment]
Sorry, it is unclear what you are trying to do. Please list all steps you are doing and tell us what you want to achieve.

**Comment by adrianreber** [comment]
Closing. Please open a new ticket if you have further questions.
