### ISSUE TITLE
Error (criu/mount.c:660): mnt: 554:./etc/hosts doesn't have a proper root mount

### ISSUE THREAD

**Issue by AditiThirdEye** [checkpoint-restore/criu#1511]
I m very new to CRIU; I have tried simple loop in c++ with criu it works fine but
With the pid is of a simple loop program in c++ running in a docker container
It gives the below error

$ sudo criu dump -t 17427 -D checkpoint/ -j -v4  

(00.000008) Version: 3.14 (gitid 0)
(00.000037) Running on kali Linux 5.10.0-kali8-amd64 #1 SMP Debian 5.10.40-1kali1 (2021-05-31) x86_64
(00.000057) Loaded kdat cache from /run/criu.kdat
(00.000067) ========================================
(00.000074) Dumping processes (pid: 17427)
(00.000079) ========================================
(00.000091) rlimit: RLIMIT_NOFILE unlimited for self
(00.000108) Running pre-dump scripts
(00.000144) irmap: Searching irmap cache in work dir
(00.000172) No irmap-cache image
(00.000183) irmap: Searching irmap cache in parent
(00.000192) irmap: No irmap cache
(00.000203) cpu: x86_family 6 x86_vendor_id GenuineIntel x86_model_id Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
(00.000210) cpu: fpu: xfeatures_mask 0x15 xsave_size 1088 xsave_size_max 1088 xsaves_size 960
(00.000220) cpu: fpu: x87 floating point registers     xstate_offsets      0 / 0      xstate_sizes    160 / 160   
(00.000230) cpu: fpu: AVX registers                    xstate_offsets    576 / 576    xstate_sizes    256 / 256   
(00.000238) cpu: fpu: MPX CSR                          xstate_offsets   1024 / 832    xstate_sizes     64 / 64    
(00.000246) cpu: fpu:1 fxsr:1 xsave:1 xsaveopt:1 xsavec:1 xgetbv1:1 xsaves:1
(00.000545) cg-prop: Parsing controller "cpu"
(00.000561) cg-prop:    Strategy "replace"
(00.000570) cg-prop:    Property "cpu.shares"
(00.000579) cg-prop:    Property "cpu.cfs_period_us"
(00.000586) cg-prop:    Property "cpu.cfs_quota_us"
(00.000591) cg-prop:    Property "cpu.rt_period_us"
(00.000605) cg-prop:    Property "cpu.rt_runtime_us"
(00.000613) cg-prop: Parsing controller "memory"
(00.000617) cg-prop:    Strategy "replace"
(00.000628) cg-prop:    Property "memory.limit_in_bytes"
(00.000635) cg-prop:    Property "memory.memsw.limit_in_bytes"
(00.000642) cg-prop:    Property "memory.swappiness"
(00.000649) cg-prop:    Property "memory.soft_limit_in_bytes"
(00.000656) cg-prop:    Property "memory.move_charge_at_immigrate"
(00.000663) cg-prop:    Property "memory.oom_control"
(00.000669) cg-prop:    Property "memory.use_hierarchy"
(00.000676) cg-prop:    Property "memory.kmem.limit_in_bytes"
(00.000683) cg-prop:    Property "memory.kmem.tcp.limit_in_bytes"
(00.000690) cg-prop: Parsing controller "cpuset"
(00.000696) cg-prop:    Strategy "replace"
(00.000703) cg-prop:    Property "cpuset.cpus"
(00.000710) cg-prop:    Property "cpuset.mems"
(00.000718) cg-prop:    Property "cpuset.memory_migrate"
(00.000724) cg-prop:    Property "cpuset.cpu_exclusive"
(00.000729) cg-prop:    Property "cpuset.mem_exclusive"
(00.000738) cg-prop:    Property "cpuset.mem_hardwall"
(00.000751) cg-prop:    Property "cpuset.memory_spread_page"
(00.000768) cg-prop:    Property "cpuset.memory_spread_slab"
(00.000785) cg-prop:    Property "cpuset.sched_load_balance"
(00.000793) cg-prop:    Property "cpuset.sched_relax_domain_level"
(00.000801) cg-prop: Parsing controller "blkio"
(00.000808) cg-prop:    Strategy "replace"
(00.000820) cg-prop:    Property "blkio.weight"
(00.000826) cg-prop: Parsing controller "freezer"
(00.000837) cg-prop:    Strategy "replace"
(00.000846) cg-prop: Parsing controller "perf_event"
(00.000852) cg-prop:    Strategy "replace"
(00.000862) cg-prop: Parsing controller "net_cls"
(00.000868) cg-prop:    Strategy "replace"
(00.000874) cg-prop:    Property "net_cls.classid"
(00.000881) cg-prop: Parsing controller "net_prio"
(00.000889) cg-prop:    Strategy "replace"
(00.000895) cg-prop:    Property "net_prio.ifpriomap"
(00.000900) cg-prop: Parsing controller "pids"
(00.000908) cg-prop:    Strategy "replace"
(00.000915) cg-prop:    Property "pids.max"
(00.000924) cg-prop: Parsing controller "devices"
(00.000933) cg-prop:    Strategy "replace"
(00.000945) cg-prop:    Property "devices.list"
(00.000999) Preparing image inventory (version 1)
(00.001047) Add pid ns 1 pid 17697
(00.001064) Add net ns 2 pid 17697
(00.001081) Add ipc ns 3 pid 17697
(00.001097) Add uts ns 4 pid 17697
(00.001115) Add time ns 5 pid 17697
(00.001140) Add mnt ns 6 pid 17697
(00.001156) Add user ns 7 pid 17697
(00.001172) Add cgroup ns 8 pid 17697
(00.001180) cg: Dumping cgroups for 17697
(00.001212) cg:  `- New css ID 1
(00.001224) cg: Set 1 is criu one
(00.001252) Detected cgroup V1 freezer
(00.001426) Seized task 17427, state 1
(00.001439) seccomp: Collected tid_real 17427 mode 0
(00.001520) Collected (4 attempts, 0 in_progress)
(00.001574) Collected (4 attempts, 0 in_progress)
(00.001594) Collected 17427 in 1 state
(00.001635) Will take pid namespace in the image
(00.001647) Add pid ns 9 pid 17427
(00.001665) Will take net namespace in the image
(00.001676) Add net ns 10 pid 17427
(00.001697) Will take ipc namespace in the image
(00.001705) Add ipc ns 11 pid 17427
(00.001722) Will take uts namespace in the image
(00.001729) Add uts ns 12 pid 17427
(00.001765) Will take mnt namespace in the image
(00.001772) Add mnt ns 13 pid 17427
(00.001798) Will take cgroup namespace in the image
(00.001805) Add cgroup ns 14 pid 17427
(00.001818) Lock network
(00.001824) Running network-lock scripts
(00.009394)     type overlay source overlay mnt_id 544 s_dev 0x36 / @ ./ flags 0x280000 options lowerdir=/var/lib/docker/overlay2/l/3TGSWOAIUI2XK4J43HMEYF4IJI:/var/lib/docker/overlay2/l/XP4R6FZIEFV4AHJUTRY7BKAQMN:/var/lib/docker/overlay2/l/6HHQ3PXDQUSEYVY77SA3OX4CZX:/var/lib/docker/overlay2/l/646M56KYV4VEZI6XMR57CPSEID:/var/lib/docker/overlay2/l/TMIONOISC4NFE52DVOOANZJGQT:/var/lib/docker/overlay2/l/IUTRBLDLNJNK4LP4SBKXP2FA3R:/var/lib/docker/overlay2/l/WF2S53JEDNEC6YUUATXQOB6PWG:/var/lib/docker/overlay2/l/NG67EXBSXFAJSHCL3KZWKNGSDQ:/var/lib/docker/overlay2/l/G2OUEOXHH7YAMQBCMOXUZMRCDN:/var/lib/docker/overlay2/l/KRU3UTKMKGBNICJIJE73DY27FM:/var/lib/docker/overlay2/l/ZLYWHBKNYYWUHRBNVZMHLZ62OY,upperdir=/var/lib/docker/overlay2/07f867ebebf50190764d92a34402ceccb704271bd079f347844cafd17b674915/diff,workdir=/var/lib/docker/overlay2/07f867ebebf50190764d92a34402ceccb704271bd079f347844cafd17b674915/work
(00.009436)     type proc source proc mnt_id 545 s_dev 0x39 / @ ./proc flags 0x20000e options 
(00.009453)     type tmpfs source tmpfs mnt_id 546 s_dev 0x3b / @ ./dev flags 0x1000002 options size=65536k,mode=755
(00.009504)     type devpts source devpts mnt_id 547 s_dev 0x3c / @ ./dev/pts flags 0x20000a options gid=5,mode=620,ptmxmode=666
(00.009562)     type sysfs source sysfs mnt_id 548 s_dev 0x3d / @ ./sys flags 0x20000e options 
(00.009573)     type cgroup2 source cgroup mnt_id 549 s_dev 0x1c /system.slice/docker-dc5249478f2271d3daa82e08eb275e7902528649510346912040d1e32421a3b7.scope @ ./sys/fs/cgroup flags 0x20000e options nsdelegate,memory_recursiveprot
(00.009583)     type mqueue source mqueue mnt_id 550 s_dev 0x38 / @ ./dev/mqueue flags 0x20000e options 
(00.009593)     type tmpfs source shm mnt_id 551 s_dev 0x3e / @ ./dev/shm flags 0x20000e options size=65536k
(00.009603)     type ext4 source /dev/sda8 mnt_id 552 s_dev 0x800008 /var/lib/docker/containers/dc5249478f2271d3daa82e08eb275e7902528649510346912040d1e32421a3b7/resolv.conf @ ./etc/resolv.conf flags 0x200000 options errors=remount-ro
(00.009616)     type ext4 source /dev/sda8 mnt_id 553 s_dev 0x800008 /var/lib/docker/containers/dc5249478f2271d3daa82e08eb275e7902528649510346912040d1e32421a3b7/hostname @ ./etc/hostname flags 0x200000 options errors=remount-ro
(00.009628)     type ext4 source /dev/sda8 mnt_id 554 s_dev 0x800008 /var/lib/docker/containers/dc5249478f2271d3daa82e08eb275e7902528649510346912040d1e32421a3b7/hosts @ ./etc/hosts flags 0x200000 options errors=remount-ro
(00.009640) mnt: Building mountpoints tree
(00.009644) mnt:        Building plain mount tree
(00.009649) mnt:                Working on 554->544
(00.009655) mnt:                Working on 553->544
(00.009660) mnt:                Working on 552->544
(00.009664) mnt:                Working on 551->546
(00.009668) mnt:                Working on 550->546
(00.009672) mnt:                Working on 549->548
(00.009676) mnt:                Working on 548->544
(00.009680) mnt:                Working on 547->546
(00.009683) mnt:                Working on 546->544
(00.009689) mnt:                Working on 545->544
(00.009694) mnt:                Working on 544->456
(00.009698) mnt:        Resorting children of 544 in mount order
(00.009703) mnt:        Resorting children of 554 in mount order
(00.009707) mnt:        Resorting children of 553 in mount order
(00.009711) mnt:        Resorting children of 552 in mount order
(00.009714) mnt:        Resorting children of 548 in mount order
(00.009718) mnt:        Resorting children of 549 in mount order
(00.009722) mnt:        Resorting children of 546 in mount order
(00.009726) mnt:        Resorting children of 551 in mount order
(00.009730) mnt:        Resorting children of 550 in mount order
(00.009734) mnt:        Resorting children of 547 in mount order
(00.009739) mnt:        Resorting children of 545 in mount order
(00.009744) mnt: Done:
(00.009747) mnt: [./](544->456)
(00.009751) mnt:  [./etc/hosts](554->544)
(00.009754) mnt:  <--
(00.009759) mnt:  [./etc/hostname](553->544)
(00.009763) mnt:  <--
(00.009767) mnt:  [./etc/resolv.conf](552->544)
(00.009770) mnt:  <--
(00.009772) mnt:  [./sys](548->544)
(00.009775) mnt:   [./sys/fs/cgroup](549->548)
(00.009779) mnt:   <--
(00.009782) mnt:  <--
(00.009784) mnt:  [./dev](546->544)
(00.009788) mnt:   [./dev/shm](551->546)
(00.009791) mnt:   <--
(00.009795) mnt:   [./dev/mqueue](550->546)
(00.009800) mnt:   <--
(00.009803) mnt:   [./dev/pts](547->546)
(00.009805) mnt:   <--
(00.009809) mnt:  <--
(00.009812) mnt:  [./proc](545->544)
(00.009816) mnt:  <--
(00.009820) mnt: <--
(00.009830) mnt: Inspecting sharing on 554 shared_id 0 master_id 0 (@./etc/hosts)
(00.009835) mnt:        The mount 553 is bind for 554 (@./etc/hostname -> @./etc/hosts)
(00.009840) mnt:        The mount 552 is bind for 554 (@./etc/resolv.conf -> @./etc/hosts)
(00.009844) mnt: Inspecting sharing on 553 shared_id 0 master_id 0 (@./etc/hostname)
(00.009848) mnt: Inspecting sharing on 552 shared_id 0 master_id 0 (@./etc/resolv.conf)
(00.009852) mnt: Inspecting sharing on 551 shared_id 0 master_id 0 (@./dev/shm)
(00.009856) mnt: Inspecting sharing on 550 shared_id 0 master_id 0 (@./dev/mqueue)
(00.009860) mnt: Inspecting sharing on 549 shared_id 0 master_id 0 (@./sys/fs/cgroup)
(00.009864) mnt: Inspecting sharing on 548 shared_id 0 master_id 0 (@./sys)
(00.009868) mnt: Inspecting sharing on 547 shared_id 0 master_id 0 (@./dev/pts)
(00.009872) mnt: Inspecting sharing on 546 shared_id 0 master_id 0 (@./dev)
(00.009875) mnt: Inspecting sharing on 545 shared_id 0 master_id 0 (@./proc)
(00.009879) mnt: Inspecting sharing on 544 shared_id 0 master_id -1 (@./)
(00.009884) Error (criu/mount.c:660): mnt: 554:./etc/hosts doesn't have a proper root mount
(00.009898) Unlock network
(00.009902) Running network-unlock scripts
(00.014474) Unfreezing tasks into 1
(00.014493)     Unseizing 17427 into 1
(00.014519) Error (criu/cr-dump.c:1764): Dumping FAILED.

I tried making the etc folder giving it global access, then shifted everything to root folder in order to solve the problem;
 Nothing worked. 
Hope you can help me.

Thank you !

**Comment by adrianreber** [comment]
Are you doing the checkpoint on the inside or on the outside of the container?

**Comment by AditiThirdEye** [comment]
From Outside the container

**Comment by AditiThirdEye** [comment]
I tried from inside the with normal docker checkpoint commands it didn't work either 
For that older versions of docker is required and I tried to install them but because my kali linux kernal is new so it didn't work.

**Comment by adrianreber** [comment]
> From Outside the container

That is doable but really difficult, because you need to know a lot of details of how the container was set up. Either use Docker or Podman to checkpoint the complete container or run CRIU in the container (requires `--privileged`).

You can also take a look at the source code of `runc` or `crun` to see all the options they use to checkpoint a container.

**Comment by adrianreber** [comment]
> I tried from inside the with normal docker checkpoint commands it didn't work either
> For that older versions of docker is required and I tried to install them but because my kali linux kernal is new so it didn't work.

Is that because of cgroup2? Try Podman with crun they handle cgroup2 without a problem.

**Comment by AditiThirdEye** [comment]
Yes I have tried podman in my kali linux but with that it says, runtime not configured.

**Comment by adrianreber** [comment]
This no longer sounds like a CRIU problem. Please close the ticket if you have no further CRIU questions.

**Comment by AditiThirdEye** [comment]
Can you suggest something with respect to root mount?

**Comment by AditiThirdEye** [comment]
Thankyou for your time.
