### ISSUE TITLE
Restoring TCP connection: No tcp-stream-XXXX.img image

### ISSUE THREAD

**Issue by yimin-zhao** [checkpoint-restore/criu#1523]
Hi there,

I met a restoring error when I try to restore a container pod.
```
(00.068100)      1: unix: Opening standalone (stage 0 id 0x46 ino 101122607 peer 0)
(00.068103)      1:             Create fd for 40
(00.068105)      1:             Create fd for 37
(00.068106)      1: inet:       Restore: family AF_INET    type SOCK_STREAM    proto IPPROTO_TCP      port 5701 state TCP_CLOSE        src_addr 10.85.0.97
(00.068109)      1: tcp: Restoring TCP connection
(00.068110)      1: tcp: Restoring TCP connection id 47 ino 608276c
(00.068116)      1: No tcp-stream-608276c.img image
(00.068117)      1: Error (criu/protobuf.c:74): Unexpected EOF on (empty-image)
(00.068123)      1: Error (criu/files.c:1216): Unable to open fd=38 id=0x47
(00.084407) mnt: Switching to new ns to clean ghosts
(00.094449) Error (criu/cr-restore.c:2483): Restoring FAILED.
```
I already use `tcp-close` option for both dump and restore, but I checked the this [doc](https://criu.org/CLI/opt/--tcp-close), it says  `--tcp-close option affects all the process tree TCP sockets that have any TCP state except CLOSED and LISTEN`. In this way, the `tcp-close` flag doesn't affect the closed inet socket, but I also see a comment in the [source code](https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/sk-inet.c#L205)  
```
case TCP_CLOSE:	
    /* Trivial case, we just need to create a socket on restore */		
    break;
```
Because the container is going to be migrated to a host with a different IP, so I have to use `tcp-close` to drop all TCP connections.
I am kind of confused, anyway, for this error how can I resolve it?

Besides, is it related to the `nftables-devel` package? I cannot find this package at CentOS 8, I built criu without nftables support. 

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

[restore.log](https://github.com/checkpoint-restore/criu/files/6685549/restore.log)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.15
GitID: v3.14-174-gf68da4a86
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Warn  (criu/cr-check.c:1230): clone3() with set_tid not supported
Error (criu/cr-check.c:1272): Time namespaces are not supported
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
It works if I try it locally in Podman just as it should. Not sure. Could you also share the log file of the checkpoint? Maybe that has a clue why it fails.

**Comment by yimin-zhao** [comment]
[cr-dump.log](https://github.com/checkpoint-restore/criu/files/6690465/cr-dump.log)
[cr-restore.log](https://github.com/checkpoint-restore/criu/files/6690466/cr-restore.log)

Sometimes if there is no TCP_CLOSE inet socket dumped, then the pod can be restored successfully.

**Comment by adrianreber** [comment]
This is strange. I think this could be a bug. Unfortunately I am not able to reproduce it locally to provide a fix.

@avagin I had a look at the code and only if opts.tcp_close it set and if the socket is not already in the TCP_CLOSE state are we skipping restoring of the connection state. During dumping it seems, however, we do not write the state of the socket and so it fails during restore with:
```
(00.078512)      1: inet: 	Restore: family AF_INET    type SOCK_STREAM    proto IPPROTO_TCP      port 5701 state TCP_CLOSE        src_addr 10.85.0.101
(00.078516)      1: tcp: Restoring TCP connection
(00.078517)      1: tcp: Restoring TCP connection id 46 ino 62a6873
(00.078523)      1: No tcp-stream-62a6873.img image
```

The restore code:
```
        if (opts.tcp_close &&
            ii->ie->state != TCP_LISTEN && ii->ie->state != TCP_CLOSE) {
                if (shutdown(fd, SHUT_RDWR) && errno != ENOTCONN) {
                        pr_perror("Unable to shutdown the socket id %x ino %x",
                                  ii->ie->id, ii->ie->ino);
                }
                return 0;
        }
```

So with `--tcp-close` it seems we are not writing TCP state images during dump but require them during restore.
