### ISSUE TITLE
Is feature custom checkpoint-dir for docker restore available on 20.10?

### ISSUE THREAD

**Issue by john-lark** [checkpoint-restore/criu#1527]
**Description**
I have make some tests on docker 17.03 which is the latest release that can support custom checkpoint-dir  when using `docker start`. But since the next version, this feature was forbidden for some reasons.   
https://github.com/moby/moby/pull/41031 The pr says that according to his test, fixes have been enough and the forbid can be removed safely as expected.  
So I want to know is this pr all right?

**Comment by adrianreber** [comment]
I am a bit confused why you are asking this question here. We are not directly involved with Docker. Not sure we can help you.

**Comment by john-lark** [comment]
> I am a bit confused why you are asking this question here. We are not directly involved with Docker. Not sure we can help you.

Yes it may be a little unsuitable. 
I open the issue here because I see the fixes made by the developers who are criu contributors https://github.com/moby/moby/issues/37344#issuecomment-402239185
I think the guys may tell me something about this not the moby team.

**Comment by adrianreber** [comment]
Closing as it is CRIU unrelated.

**Comment by avagin** [comment]
@john-lark It was my comment, but it was three years about and I totally lost the context.
