### ISSUE TITLE
zdtm: netns_lock test unexpected CI behavior

### ISSUE THREAD

**Issue by ZeyadYasser** [checkpoint-restore/criu#1530]
I created a test for network internal locking which was recently merged: https://github.com/checkpoint-restore/criu/pull/1465

For some reason this test doesn't always pass on CentOS7:
- This is running and failing https://api.cirrus-ci.com/v1/task/6633582350303232/logs/build.log
- Here I just reran the test and it passed https://api.cirrus-ci.com/v1/task/6302001949573120/logs/build.log

Also here https://ci.kernoops.org/job/CRIU/job/CRIU-iter/job/criu-dev/431/testReport/(root)/criu/zdtm_static_netns_lock/ the test failure is interesting because it states that the --pre-dump hook is being run again after restore which expectedly causes the test to fail as it is highly dependent on the order of the hooks

I just wanted to document this weird behavior in an open issue until I figure out what is wrong.

**Comment by adrianreber** [comment]
Thanks for opening the ticket to track this. I also saw this and was confused why it fails sometimes. Good that you are aware of it.

**Comment by ZeyadYasser** [comment]
@adrianreber  I think I figured out the cause of random failure in CentOS7.

I believe this is caused by a race condition where the following execution flow takes place:
1. ```--post-start``` hook starts just after the test (both are run in parallel) https://github.com/checkpoint-restore/criu/blob/98186981d9eb430e39da3ee692e41ccdcfa67bff/test/zdtm.py#L426
2. ```--post-start``` hook calls ```ip netns add``` to create the test netns https://github.com/checkpoint-restore/criu/blob/98186981d9eb430e39da3ee692e41ccdcfa67bff/test/zdtm/static/netns_lock.hook#L25
3. ```ip``` creates the netns file https://github.com/shemminger/iproute2/blob/9f366536edb5158343152604e82b968be46dbf26/ip/ipnetns.c#L888
4. ```netns_lock``` test opens that file and uses it in ```setns``` https://github.com/checkpoint-restore/criu/blob/98186981d9eb430e39da3ee692e41ccdcfa67bff/test/zdtm/static/netns_lock.c#L44 https://github.com/checkpoint-restore/criu/blob/98186981d9eb430e39da3ee692e41ccdcfa67bff/test/zdtm/static/netns_lock.c#L58
5. ```ip``` mounts the netns to the file https://github.com/shemminger/iproute2/blob/9f366536edb5158343152604e82b968be46dbf26/ip/ipnetns.c#L910

Test fails at 4 because ```setns``` is called on an invalid ```nstype``` as ```ip``` didn't mount the netns in time.
https://man7.org/linux/man-pages/man2/setns.2.html#ERRORS
>        EINVAL fd refers to a namespace whose type  does
>        not match that specified in nstype.

I didn't know how to run the CentOS tests locally and I wasn't able to reproduce the error locally at first.
I added a deliberate sleep after file creation in the ```ip``` source code, compiled and forced the test to use this build locally.
I was able to reproduce the error locally:
```bash
The kernel is tainted: '12289\n'
userns is supported
=== Run 1/1 ================ zdtm/static/netns_lock
======================= Run zdtm/static/netns_lock in h ========================
Start test
Test is SUID
Running zdtm/static/netns_lock.hook(--post-start)
./netns_lock --pidfile=netns_lock.pid --outfile=netns_lock.out
make: *** [Makefile:437: netns_lock.pid] Error 1
 Test zdtm/static/netns_lock FAIL at ['make', '--no-print-directory', '-C', 'zdtm/static', 'netns_lock.pid'] 
Test output: ================================
14:29:25.668:    54: ERR: netns_lock.c:59: setns 4 (errno = 22 (Invalid argument))
14:29:25.668:    53: ERR: test.c:316: Test exited unexpectedly with code 1

 <<< ================================
Running zdtm/static/netns_lock.hook(--clean)
##################################### FAIL #####################################
```

There is the lazy solution of just adding a sleep before ```setns```, but I will think of something to synchronize the hooks and the test.

**Comment by adrianreber** [comment]
> I didn't know how to run the CentOS tests locally and I wasn't able to reproduce the error locally at first.

Probably mentioning the obvious here, but a VM is probably your easiest solution.

**Comment by rst0git** [comment]
@ZeyadYasser I think we could use `test_wait_pre_dump()` to fix this issue:

```diff
diff --git a/test/zdtm/static/netns_lock.c b/test/zdtm/static/netns_lock.c
index 300349c03..3e603ec5e 100644
--- a/test/zdtm/static/netns_lock.c
+++ b/test/zdtm/static/netns_lock.c
@@ -12,7 +12,7 @@ const char *test_author = "Zeyad Yasser <zeyady98@gmail.com>";
 
 int main(int argc, char **argv)
 {
-       int i, ns_fd;
+       int ns_fd;
 
        test_init(argc, argv);
 
@@ -40,16 +40,9 @@ int main(int argc, char **argv)
         * connect operation causes a timeout.
         */
 
-       for (i = 0; i < MAX_RETRY; i++) {
-               ns_fd = open(NS_PATH, O_RDONLY);
-               if (ns_fd < 0) {
-                       /* Netns not created yet by post-start hook */
-                       sleep(1);
-                       continue;
-               }
-               break;
-       }
+       test_wait_pre_dump();
 
+       ns_fd = open(NS_PATH, O_RDONLY);
        if (ns_fd < 0) {
                pr_perror("can't open network ns");
                return 1;
```

**Comment by rst0git** [comment]
@ZeyadYasser I think we could use something like the following to fix this issue:
```diff
--- a/test/zdtm/static/netns_lock.c
+++ b/test/zdtm/static/netns_lock.c
@@ -8,11 +8,10 @@ const char *test_author = "Zeyad Yasser <zeyady98@gmail.com>";
 #include <sched.h>
 
 #define NS_PATH "/var/run/netns/criu-net-lock-test"
-#define MAX_RETRY 3
 
 int main(int argc, char **argv)
 {
-       int i, ns_fd;
+       int ns_fd;
 
        test_init(argc, argv);
 
@@ -40,16 +39,7 @@ int main(int argc, char **argv)
         * connect operation causes a timeout.
         */
 
-       for (i = 0; i < MAX_RETRY; i++) {
-               ns_fd = open(NS_PATH, O_RDONLY);
-               if (ns_fd < 0) {
-                       /* Netns not created yet by post-start hook */
-                       sleep(1);
-                       continue;
-               }
-               break;
-       }
-
+       ns_fd = open(NS_PATH, O_RDONLY);
        if (ns_fd < 0) {
                pr_perror("can't open network ns");
                return 1;
diff --git a/test/zdtm/static/netns_lock.desc b/test/zdtm/static/netns_lock.desc
index 79362790e..29435d163 100644
--- a/test/zdtm/static/netns_lock.desc
+++ b/test/zdtm/static/netns_lock.desc
@@ -1,6 +1,6 @@
 {
     'flavor': 'h',
-    'flags': 'suid',
+    'flags': 'suid pre-dump-notify',
     'opts': '--tcp-established',
     'ropts': '--join-ns net:/var/run/netns/criu-net-lock-test'
 }
```

**Comment by adrianreber** [comment]
Just saw a failure on non CentOS 7

https://app.circleci.com/pipelines/github/checkpoint-restore/criu/362/workflows/d3ed193f-617e-44ed-8a91-b3a48a66e9b4/jobs/726
