### ISSUE TITLE
Cannot checkpoint anonymous hugepages

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1533]
**Description**
Tried to checkpoint a program using anonymous hugepages, got error "Can't lookup mount=16 for fd=-3 path=/anon_hugepage (deleted)"

**Steps to reproduce the issue:**
1. Wrote a program using anonymous hugepage, `mmap(NULL, 134217728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_HUGETLB, -1, 0)` and run it on a system enabled huge page.
2. CRIU checkpoint will be failed.

**Describe the results you received:**
Tried to research this and have no idea why the mnt id of the anonymous hugepage is 16, and I cannot find this number anywhere on the system.

```
# grep "^16\>" /proc/*/mountinfo

# pmap -p `pgrep test_huge` | grep anon_hugepage
00007fd2b7200000 131072K rw--- /anon_hugepage (deleted)

# exec 100< /proc/`pgrep test_huge`/map_files/7fd2b7200000-7fd2bf200000
# cat /proc/$$/fdinfo/100 
pos:    0
flags:  0100000
mnt_id: 16
```

Use `--external` can probably get around this, but since the program can mmap a new anonymous huge page at any time, it's not feasible to get the inode number of all the huge page mappings before checkpoint.

I also feel like this is something we probably can make CRIU just support it naturally, after all, it's an anonymous huge page, we can dump the data, restore the hugepage mapping and copy the data back. Isn't it?

**Describe the results you expected:**
Can successfully checkpoint a program using anonymous hugepage.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by geminijun** [comment]
Hi @Snorch , do you have any idea about this?

**Comment by Snorch** [comment]
Looks like MAP_HUGETLB mappings are not supported:

We don't even have a zdtm test for it, but adding this hunk to maps01:

```
diff --git a/test/zdtm/static/maps01.c b/test/zdtm/static/maps01.c
index 119d7a6a4..a20581e94 100644
--- a/test/zdtm/static/maps01.c
+++ b/test/zdtm/static/maps01.c
@@ -32,6 +32,12 @@ int main(int argc, char ** argv)
 
        task_waiter_init(&t);
 
+       if (MAP_FAILED == mmap(NULL, 4*1024*1024, PROT_WRITE | PROT_READ,
+                       MAP_PRIVATE|MAP_ANONYMOUS|MAP_HUGETLB, -1, 0)) {
+               pr_perror("mmap MAP_HUGETLB");
+               return -1;
+       }
+
        m = mmap(NULL, MEM_SIZE, PROT_WRITE | PROT_READ,
                                MAP_SHARED | MAP_ANONYMOUS, -1, 0);
```

I can reproduce your problem.

Note: On fedora34 I also needed to enable hugetlbfs via `echo 20 > /proc/sys/vm/nr_hugepages` first.

**Comment by zouyonghao** [comment]
Any updates for this?

**Comment by Snorch** [comment]
I believe it's a new feature.

One would need to implement support of MAP_HUGETLB, most likely including:
1) skip mount lookup for MAP_HUGETLB mappings
2) TODO in is_memfd should be done
3) and probably something more, it's hard to say until you actually do it =)
