### ISSUE TITLE
[Request] Is there any way to realize the C/R function on Windows?

### ISSUE THREAD

**Issue by ryuujo1573** [checkpoint-restore/criu#1538]
Thanks!  <3

**Comment by rst0git** [comment]
>Is there any way to realize the C/R function on Windows?

Yes, but not with CRIU. There two ancient papers describing how process checkpoint/restore could work on Windows:
- [Winckp: a transparent checkpointing and rollback recovery tool for Windows NT applications](https://ieeexplore.ieee.org/document/781053)
- [NT-SwiFT: software implemented fault tolerance on windows NT](https://dl.acm.org/doi/abs/10.1016/S0164-1212%2802%2900154-1)

**Comment by adrianreber** [comment]
@ryuujo1573 can we close this ticket?

**Comment by ryuujo1573** [comment]
Thanks for your reply!
