### ISSUE TITLE
[Request] Is there any way to support socketCAN?

### ISSUE THREAD

**Issue by zzyyrr** [checkpoint-restore/criu#1544]
**Description**
I want to use CRIU to checkpoint a program which uses VCAN or CAN to receive CAN messages. But the CRIU says the socket is unknown.  I wonder if the CRIU supports CAN or what command should I use? Thank you!

**Steps to reproduce the issue:**
1. I installed can-utils on Ubuntu 20.04. 
```
 $ sudo apt install can-utils
 $ modprobe vcan
 $ sudo ip link add dev vcan0 type vcan
 $ sudo ip link set up vcan0
```
2. I wrote a program:
can_receive.c:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <net/if.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <linux/can.h>
#include <linux/can/raw.h>

int main()
{
    int s, nbytes;
    struct sockaddr_can addr;
    struct ifreq ifr;
    struct can_frame frame;
    struct can_filter rfilter[1];
    s = socket(PF_CAN, SOCK_RAW, CAN_RAW);
    strcpy(ifr.ifr_name, "vcan0" );
    ioctl(s, SIOCGIFINDEX, &ifr); 
    addr.can_family = AF_CAN;
    addr.can_ifindex = ifr.ifr_ifindex;
    bind(s, (struct sockaddr *)&addr, sizeof(addr));
    while(1)
    {
        nbytes = read(s, &frame, sizeof(frame));   
        if(nbytes > 0)
        {
            printf("ID=0x%X DLC=%d data[0]=0x%X\n", frame.can_id,frame.can_dlc, frame.data[0]);
        }
    }
    close(s);
    return 0;
}
```

3. Run the program and get the pid;
4. 
```
$ criu pre-dump --shell-job --images-dir ./chkp01 -t 101612
```
The command was executed successfully.

5.
```
$ criu dump --track-mem --shell-job --images-dir ./chkp02 -t 101612 --prev-images-dir ./chkp01 --leave-running
```

**Describe the results you received:**
I got this:
```
Error (criu/sockets.c:739): sockets: BUG! Unknown socket collected (family 29)
Error (criu/cr-dump.c:1351): Dump files (pid: 101612) failed with -1
Error (criu/cr-dump.c:1768): Dumping FAILED.
```
**Describe the results you expected:**
Is there any way to support socketCAN? Or is my command line incorrect?

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
Error (criu/sockets.c:739): sockets: BUG! Unknown socket collected (family 29)
Error (criu/cr-dump.c:1351): Dump files (pid: 101612) failed with -1
Error (criu/cr-dump.c:1768): Dumping FAILED.
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.15
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good.
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
There is no support for CAN sockets in CRIU currently. Someone would need to implement it.

**Comment by adrianreber** [comment]
@zzyyrr Can we close this issue?

**Comment by zzyyrr** [comment]
> @zzyyrr Can we close this issue?

OK, sure.
