### ISSUE TITLE
Got different performance when restoring a group of tasks from the same checkpoint

### ISSUE THREAD

**Issue by LiuChangFreeman** [checkpoint-restore/criu#1547]
**Description**
I'm trying to restore 8 different task at the same time which use the same checkpoint.  
However, the 8th costs almost 8-times time to boot up than the first one(**the worst case**).  
This machine has 8 physical cores and I think every task should behavior almost the same.  
I guess there is something about the lock. 
So could anyone tell me more about why it comes to this result?  
```
container started
1 boot:0.737s
container started
2 boot:0.742s
container started
3 boot:1.455s
container started
4 boot:2.852s
container started
5 boot:3.249s
container started
6 boot:5.73s
container started
8 boot:5.532s
container started
7 boot:5.685s
```

**Steps to reproduce the issue:**
1. Checkpoint a task which doesn't occupy any entire resources 
2. Start restoring 8 tasks using the checkpoint at the same time 
3. Count the time cost by criu

**Describe the results you received:**  
The last task costs more time than the first one, usually 2x~8x. 

**Describe the results you expected:**
The time will exactly be the same.

**Comment by Snorch** [comment]
> So could anyone tell me more about why it comes to this result?

This task looks like mission-impossible for now =)

1. We need to know _exactly_ how do you do the restore, full criu command line with arguments, criu version, container runtime related info, what is the application you dump, how it was setup.

2. Please provide full criu logs for all 8 restores, this might help if criu hangs on anything.

3. If you have a reproduce, probably you can script it and provide the script.
