### ISSUE TITLE
Checkpoint/restore a docker container in a new container fails

### ISSUE THREAD

**Issue by lzmihoubi** [checkpoint-restore/criu#1548]
**Description**

I am trying to checkpoint and restore a container in another new container. I followed the tutorial in https://criu.org/Docker, at first I had a few errors (like custom checkpointdir not supported), after some research, I fixed them and finally got to execute all the steps (from container creation to restoration in a new container) without errors. But when I check the logs, the problem is the new container ignores the checkpoint and starts fresh instead of where the source container left off. 

**Steps to reproduce the issue:**
1. Running looper container: `docker run -d --name looper --security-opt seccomp:unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
2. Wait a few moments for the loop to progress
3. Creating checkpoint: `docker checkpoint create --checkpoint-dir=/tmp looper checkpoint-looper1`
4. Creating new container looper-clone: `docker create --name looper-clone busybox`
5. Moving the checkpoint to default dir: `cp -r /tmp/checkpoint-looper1 /var/lib/docker/containers/$(docker ps -aq --no-trunc --filter name=looper-clone)/checkpoints/`
6. Restoring the checkpoint in the new container: `docker start --checkpoint=checkpoint-looper1 looper-clone`

**Describe the results you received:**

It didn't start any errors or warnings but the new container's log is empty after the restoration. When I tried `docker create --name looper-clone --security-opt seccomp:unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'` instead of command 4. for the creation of the new container, the looper-clone's log after the restoration shows that the loop startes from 0 instead of the value stored in the checkpoint.

**Describe the results you expected:**
The new container's logs was supposed to start from where the checkpoint source container left off not from the 
**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>Output of `criu --version`: </summary>
<p>

```
Version: 3.15
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good.
```

</p>
</details>

**Additional environment details:**
Docker 20.10.2 
VM running Ubuntu 20.04.2

**Comment by adrianreber** [comment]
Can you try it with Podman. Podman's checkpoint restore support works much better: https://criu.org/Podman

**Comment by lzmihoubi** [comment]
> Can you try it with Podman. Podman's checkpoint restore support works much better: https://criu.org/Podman

I am obligated to use docker. I'm working on container migration. The container that I need to migrate is a third-party piece of software that I need in my system. I am currently just playing around with the existing tutorials to get comfortable with criu in order to use it later on in the migration. So I believe I can't use podman.

**Comment by adrianreber** [comment]
You should really try Podman. It can be a drop in replacement for Docker. If that is not possible you have to take your bug report
to Docker. We know that it does not always work reliably but that is not something we cannot fix here.

Especially if you are working on container migration. Try Podman.

**Comment by lzmihoubi** [comment]
@adrianreber Thank you so much!!
 What about runc? is it a good alternative?

**Comment by adrianreber** [comment]
Docker and Podman both use runc, so runc should just work, yes.
