### ISSUE TITLE
A question on criu implementation detail

### ISSUE THREAD

**Issue by wangtianxia-sjtu** [checkpoint-restore/criu#1551]
**Description**

I find that during the criu restoration phase, CRIU will eagerly read the page contents into the memory, using **sys_preadv**. Here is the [code](https://github.com/checkpoint-restore/criu/blob/73d76d45c16f95d3f00d0331265ea04d6e54c7be/criu/pie/restorer.c#L1569). This is a major overhead in the restoration phase (in my test, 2.2ms in 4.7ms, the restoration of a simple python process).

Why does CRIU choose to eagerly install memory contents instead of lazily using linux's page fault handler to install the memory on-demand?

**Steps to reproduce the issue:**
We can restore any program with big memory usage.

**Describe the results you received:**
This **sys_preadv** function will contribute to a huge part of restoration latency.

**Describe the results you expected:**
Maybe we can install the page on-demand in page fault handler?

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

Key output: (Preadv takes 2.2ms in this case, total 4.7ms)
```
(00.002049) pie: 467: 	mmap(0x7ffea5602000 -> 0x7ffea5623000, 0x3 0x132 -1)
(00.002052) pie: 467: Preadv 0x400000:4096... (41 iovs)
(00.004260) pie: 467: `- returned 5636096
...
(00.004696) Writing stats
(00.004721) Running post-resume scripts
```

Full output is in the attachment.
[restore.log](https://github.com/checkpoint-restore/criu/files/6798252/restore.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/6798255/restore.log)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.15
GitID: 2d3c952
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Error (criu/cr-check.c:697): mmap(0) failed: Invalid argument
Error (criu/cr-check.c:776): Child exited with 1
Warn  (criu/cr-check.c:1365): Does not look good.
```

However, the restoration and checkpoint process works very well...

</p>
</details>

**Additional environment details:**
[restore.log](https://github.com/checkpoint-restore/criu/files/6798265/restore.log)

**Comment by adrianreber** [comment]
> Why does CRIU choose to eagerly install memory contents instead of lazily using linux's page fault handler to install the memory on-demand?

What do you exactly mean with 'using linux's page fault handler'. It is not clear to me. Can you go a bit more into details how you think this could be done differently?

**Comment by wangtianxia-sjtu** [comment]
Thank you for your reply!

I think that we can use the mmap syscall to map the specific image file range into the memory instead of eagerly reading the image contents into memory using sys_preadv.

mmap syscall will not do the file read operation immediately, thus decreasing the restore latency. The actual read operation happens in the linux page fault handler.

**Comment by adrianreber** [comment]
I cannot answer that, sorry. It was introduced with this commit: https://github.com/checkpoint-restore/criu/commit/91388fce03f8dde9eca6a3cb7c9afb6bc0fbdfcb . Maybe the commit message helps you.

Maybe also @xemul and @avagin can give you answers.

**Comment by rppt** [comment]
> I think that we can use the mmap syscall to map the specific image file range into the memory instead of eagerly reading the image contents into memory using sys_preadv.
> 
> mmap syscall will not do the file read operation immediately, thus decreasing the restore latency. The actual read operation happens in the linux page fault handler.

We cannot use `mmap` with actual file parameter to map an image file to a memory region of the restored process because this region is an anonymous  memory from the restored process point of view.

It is possible to restore anonymous memory on demand with `--lazy-pages` option, but this option has it own cost because the only way to hook up into the Linux page fault processing is userfaultfd that `lazy-pages` is using.

**Comment by wangtianxia-sjtu** [comment]
Thank you for your generous replies! Now I have a deeper understanding on criu memory restoration.

**Comment by imachug** [comment]
> We cannot use `mmap` with actual file parameter to map an image file to a memory region of the restored process because this region is an anonymous memory from the restored process point of view.

Technically, if memory was mmaped rather than read, would there be any side effects except for inconsistency in restored vs original /proc/self/maps?
