### ISSUE TITLE
CRIU installation fails on ubuntu 18.04

### ISSUE THREAD

**Issue by Srinidhi2301** [checkpoint-restore/criu#1569]
i used sudo apt-get install -y criu
and did  sudo criu check

i repeatedly keep getting this error

'''
Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink
Error (criu/libnetlink.c:26): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:26): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:26): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:26): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink
Warn  (criu/sockets.c:711): The current kernel doesn't support packet_diag
Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink
Warn  (criu/sockets.c:721): The current kernel doesn't support netlink_diag
Error (criu/cr-check.c:147): sys/kernel/ns_last_pid sysctl is inaccessible: No such file or directory
Does not look good.

docker info:
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 26
  Paused: 0
  Stopped: 13
 Images: 17
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.140-tegra
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 31.17GiB
 Name: ****
 ID: KXLL:NKMO:WRPA:BC3M:VQTZ:HZP2:4ZLK:6L3I:IM3M:WRUO:Z2K6:RWOW
 Docker Root Dir: /nvme/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by Srinidhi2301** [comment]
Could you please help with this @adrianreber

**Comment by adrianreber** [comment]
Why are you mentioning Docker?

Are you running CRIU as root?

**Comment by Srinidhi2301** [comment]
> Why are you mentioning Docker?
> 
> Are you running CRIU as root?

Thanks for your response.
Yes . I am running it as a root

**Comment by adrianreber** [comment]
> > Why are you mentioning Docker?
> > 
> > Are you running CRIU as root?
> 
> Thanks for your response.
> Yes . I am running it as a root

And why are you mentioning Docker?

**Comment by Srinidhi2301** [comment]
Sorry it was my mistake. i should have just mentioned about the kernel version..

The current stste of the error shows:

~/sri/criu/criu-3.11$ **criu check**

Warn  (criu/kerndat.c:659): Can't load /run/criu.kdat
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/util.c:714): exited, status=3
Error (criu/util.c:714): exited, status=3
Write 4294967295 to /proc/self/loginuid failed: Operation not permittedError (criu/uffd.c:231): uffd: Lazy pages are not available: Function not implemented
Error (criu/util.c:802): You need to be root to run this command

/sri/criu/criu-3.11$ **sudo criu check**

Warn  (criu/kerndat.c:857): Stale /run/criu.kdat file
Error (criu/sockets.c:216): sockets: Diag module missing (-2)
Error (criu/sockets.c:216): sockets: Diag module missing (-2)
Error (criu/sockets.c:216): sockets: Diag module missing (-2)
Warn  (criu/net.c:2840): Unable to get socket network namespace
Warn  (criu/net.c:2840): Unable to get tun network namespace
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Warn  (criu/libnetlink.c:55): ERROR -95 reported by netlink
Error (criu/net.c:3155): Unable to create a veth pair: -95
Warn  (criu/net.c:3177): NSID isn't reported for network links
Error (criu/uffd.c:264): uffd: Lazy pages are not available: Function not implemented
Warn  (criu/net.c:2840): Unable to get socket network namespace
Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
Warn  (criu/libnetlink.c:55): ERROR -2 reported by netlink
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/libnetlink.c:55): ERROR -2 reported by netlink
Warn  (criu/sockets.c:801): sockets: The current kernel doesn't support packet_diag
Warn  (criu/libnetlink.c:55): ERROR -2 reported by netlink
Warn  (criu/sockets.c:811): sockets: The current kernel doesn't support netlink_diag
Error (criu/cr-check.c:147): sys/kernel/ns_last_pid sysctl is inaccessible: No such file or directory
Does not look good.

**Comment by adrianreber** [comment]
It seems you are running in some kind of restricted environment. What kind of system are you using?

**Comment by Srinidhi2301** [comment]
> It seems you are running in some kind of restricted environment. What kind of system are you using?

**ARM 64 Arch**

$ uname -r
4.9.140-tegra

$ lsb_release -a
Distributor ID : Ubuntu
Description:   : Ubuntu 18.04.3 LTS
Release:          : 18.04
Codename:     :  bionic

Also could you please tell me if CRIU will be supported for my environment?

thanks

**Comment by adrianreber** [comment]
> > It seems you are running in some kind of restricted environment. What kind of system are you using?
> 
> **ARM 64 Arch**
> 
> $ uname -r
> 4.9.140-tegra
> 
> $ lsb_release -a
> Distributor ID : Ubuntu
> Description: : Ubuntu 18.04.3 LTS
> Release: : 18.04
> Codename: : bionic
> 
> Also could you please tell me if CRIU will be supported for my environment?
> 
> thanks

You really should have included this information from the beginning. The kernel sounds like a vendor kernel and not an official Ubuntu kernel. Not sure what the vendor configured but it seems to be missing many options required for CRIU.

Anyway, in theory your hardware should work with CRIU. Maybe you can recompile the kernel and enable the necessary options for CRIU: https://criu.org/Linux_kernel

**Comment by Srinidhi2301** [comment]
> > > It seems you are running in some kind of restricted environment. What kind of system are you using?
> > 
> > 
> > **ARM 64 Arch**
> > $ uname -r
> > 4.9.140-tegra
> > $ lsb_release -a
> > Distributor ID : Ubuntu
> > Description: : Ubuntu 18.04.3 LTS
> > Release: : 18.04
> > Codename: : bionic
> > Also could you please tell me if CRIU will be supported for my environment?
> > thanks
> 
> You really should have included this information from the beginning. The kernel sounds like a vendor kernel and not an official Ubuntu kernel. Not sure what the vendor configured but it seems to be missing many options required for CRIU.
> 
> Anyway, in theory your hardware should work with CRIU. Maybe you can recompile the kernel and enable the necessary options for CRIU: https://criu.org/Linux_kernel

Thanks for your reply. 
I recompiled the kernel by enabling the necessary configs. But it shows the same error. And my hardware is NVIDIA Jetson Xavier where is try to perform check point of docker containers and migrate it.

**Comment by adrianreber** [comment]
Strange. If the options are enabled and if you are sure you booted the new kernel, it should work. What does uname -a say?

**Comment by Srinidhi2301** [comment]
> Strange. If the options are enabled and if you are sure you booted the new kernel, it should work. What does uname -a say?

Hello,  I tried and rebuilt the new kernel successfully now. I could use the checkpointing functionality now. Thank you for your guidance. 

Just one think i want to clarify now. does CRIU support checkpointing of GPU enabled docker containers which uses CUDA. 

When i referred to the previous discussions 

 --> https://github.com/checkpoint-restore/criu/issues/534
 --> https://github.com/NVIDIA/nvidia-container-runtime/issues/44

which says rightnow it is now possible which is on 2018.

So, i would like to know the current update on this if NVIDIA-docker containers that uses CUDA and GPUs can be checkpointed or not? . I use jetson Xavier AGX and deep learning applications using Tensorflow in NVIDIA containers.

Please help!
@adrianreber

**Comment by rst0git** [comment]
> Just one think i want to clarify now. does CRIU support checkpointing of GPU enabled docker containers which uses CUDA.

@Srinidhi2301 There is a CRIU plug-in for AMD GPUs currently in development (https://github.com/checkpoint-restore/criu/pull/1556 and https://github.com/checkpoint-restore/criu/pull/1557), but CRIU doesn't have out-of-the box support for Nvidia GPUs.

This could be implemented as a proxy process described in [this paper](https://dl.acm.org/doi/abs/10.1145/3342195.3387555).

**Comment by Srinidhi2301** [comment]
> There is a CRIU plug-in for AMD GPUs currently in development (#1556 and #1557), but CRIU doesn't have out-of-the-box support for Nvidia GPUs.

Thank you so much for your valuable information

**Comment by Srinidhi2301** [comment]
@rst0git  
Hello, 
After recompiling the kernel with enabling all these options,

CONFIG_CHECKPOINT_RESTORE=y
CONFIG_NAMESPACES=y 
CONFIG_UTS_NS=y 
CONFIG_IPC_NS=y
CONFIG_SYSVIPC_SYSCTL=y
CONFIG_PID_NS=y 
CONFIG_NET_NS=y 
CONFIG_FHANDLE=y
CONFIG_EVENTFD=y
CONFIG_EPOLL=y 
Networking support
CONFIG_UNIX_DIAG=y 
CONFIG_INET_DIAG=y 
CONFIG_INET_UDP_DIAG=y 
CONFIG_PACKET_DIAG=y 
CONFIG_NETLINK_DIAG=y 
CONFIG_NETFILTER_XT_MARK=y 
CONFIG_TUN=y 

sudo criu check says,
Warn  (criu/kerndat.c:792):cant load /run/criu.kdat
Warn (criu/net.c:2780) unable to get socket network namespace
Warn (criu/net.c:2780) unable to get tun network namespace
Warn (criu/skunix.c:229):unix: unable to open a socket file: Bad address 
Error (criu/uffd.c:264:uffd: Lazy pages are not available: Function not implemented

Looks good.

My question is , I have enabled all the necessary options for network namespace, but still it shows a warning. How should i proceed with this?
And what other options should i enable to avoid the error Lazy pages are not available.

Kindly help. Thank you

**Comment by adrianreber** [comment]
@Srinidhi2301 I am closing this. Please re-open if you still have problems.
