### ISSUE TITLE
docker start from the checkpoint image fails 

### ISSUE THREAD

**Issue by Srinidhi2301** [checkpoint-restore/criu#1584]
I simply try to checkpoint a simple busybox container as given in the example criu page. But starting a container from checkpointed image fails. It again starts counting from first.

$ docker run -d --name looper --security-opt seccomp:unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 15; done'
236544fc063dfa3f188f604c4276333e828a98c4d72a01bd8a6db661ea2bb9fa

$ docker logs looper
0

$ docker logs looper
0
1

$ docker checkpoint create looper checkpoint1
checkpoint1

$ docker start --checkpoint checkpoint1 looper

$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
236544fc063d        busybox                    "/bin/sh -c 'i=0; wh…"   57 seconds ago      Up 11 seconds                           looper

$ docker logs looper
0
1
0
1
2
3

docker version : 19.03.6
$ sudo criu check
Looks good.
version - 3.11

kindly help. 
@adrianreber

**Comment by adrianreber** [comment]
This is a docker bug. As far as I know checkpoint/restore is not maintained actively in docker. It breaks sometimes until someone reports it upstream.

This is not a CRIU problem. I guess updating to a newer version of docker should help. Or try Podman.

**Comment by rst0git** [comment]
@SaiedKazemi This problem has been discussed previously in https://github.com/checkpoint-restore/criu/issues/1365, https://github.com/checkpoint-restore/criu/issues/1223, and https://github.com/checkpoint-restore/criu/issues/1378. You can try to update your [containerd](https://github.com/containerd/containerd/releases) version.

In CI we currently use the latest release from GitHub.
https://github.com/checkpoint-restore/criu/blob/7b71c0090fc4e192ec03d4210d2c4bbc84dcef38/scripts/ci/docker-test.sh#L36

**Comment by Srinidhi2301** [comment]
> @Srinidhi2301 This problem has been discussed previously in #1365, #1223, and #1378. You can try to update your [containerd](https://github.com/containerd/containerd/releases) version.
> 
> In CI we currently use the latest release from GitHub.
> https://github.com/checkpoint-restore/criu/blob/7b71c0090fc4e192ec03d4210d2c4bbc84dcef38/scripts/ci/docker-test.sh#L36

Thank you so much for your response. @rst0git 

currently, I am using, 
A custom kernel on ubuntu 18.04 
Architecture: aarch64
kubernetes version - 1.18.3-00

$ docker --version
Docker version 19.03.6

$ containerd --version
containerd github.com/containerd/containerd 1.3.3-0ubuntu1~18.04.2

Default Runtime: nvidia.

I will try to update my containerd version.

**Comment by Srinidhi2301** [comment]
> @Srinidhi2301 This problem has been discussed previously in #1365, #1223, and #1378. You can try to update your [containerd](https://github.com/containerd/containerd/releases) version.
> 
> In CI we currently use the latest release from GitHub.
> https://github.com/checkpoint-restore/criu/blob/7b71c0090fc4e192ec03d4210d2c4bbc84dcef38/scripts/ci/docker-test.sh#L36

@rst0git 

Hello, I am currently working on ARM64 based machine(NVIDIA Jetson). Bionic version. 
Could you please confirm if docker checkpoint restore works properly for ARM64 based machines?

I could not find any previous issues related to arm64. 

Initially i tried with the below mentioned docker version
https://launchpad.net/ubuntu/+source/docker.io/19.03.6-0ubuntu1~18.04.3/+build/20703365 

19.03.6

Then later i changed the docker to community edition and tried various combinations of docker and containerd versions for the past one month. Still there is no solution that i could find. 

Could you please help me on this . 

Your help is highly appreciated.

**Comment by Srinidhi2301** [comment]
Also , adding you the versions

xavier2@xavier2:~$ dpkg -l | grep containerd
rc  containerd                                    1.3.3-0ubuntu1~18.04.2                 arm64        daemon to control runC
ii  containerd.io                                 1.2.0~rc.2-1                                     arm64        An open and reliable container runtime

xavier2@xavier2:~$ dpkg -l | grep docker
ii  docker                                        1.5-1build1                                      arm64        System tray for KDE3/GNOME2 docklet applications
ii  docker-ce                                     5:19.03.6~3-0~ubuntu-bionic                      arm64        Docker: the open-source application container engine
ii  docker-ce-cli                                 5:19.03.6~3-0~ubuntu-bionic                      arm64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras                     5:20.10.8~3-0~ubuntu-bionic                      arm64        Rootless support for Docker.
ic  docker.io                                     19.03.6-0ubuntu1~18.04.1                         arm64        Linux container runtime
rc  nvidia-docker2                                2.2.0-1                                          all          nvidia-docker CLI wrapper
