### ISSUE TITLE
CRIU Pre-Dump failing. It's showing a Waring.

### ISSUE THREAD

**Issue by Avijit009** [checkpoint-restore/criu#1589]
CRIU Pre-Dump failing. It's showing some Waring. I am not able to understand why this one is showing like this. Please help me out to get out of this problem.
after running  **"criu pre-dump --tree <pid> --images-dir <path-to-existing-directory-A>"** this command its showing
exact code I have executed **"criu pre-dump --tree 46292 --images-dir /home/mypc/Desktop/criu/checkpoint"**
**Warn  (compel/arch/x86/src/lib/infect.c:281): Will restore 46292 with interrupted system call**

**Comment by Snorch** [comment]
Some times when criu dumps a process it can stop the process in the middle of syscall, e.g. in the middle of sys_nanosleep and criu just makes this process to receive -EINTR return value from this syscall after restore.

Normally all well-coded applications check return values of syscalls and for blocking syscalls check for -EINTR and restart the syscall when needed. But badly written code can break on it.

For instance if your code would just call sys_nanosleep(1min) once without any checking/restarting logic you can end up sleeping much less after CRIU migration. Though same would happen if you get some non-killing signal in the middle.

Please take a look on https://github.com/checkpoint-restore/criu/commit/dd71cca58a commit description for more info.

**Comment by Avijit009** [comment]
@Snorch Thank You

**Comment by adrianreber** [comment]
Closing as it seems solved.
