### ISSUE TITLE
missing files inside checkpointed image

### ISSUE THREAD

**Issue by Srinidhi2301** [checkpoint-restore/criu#1594]
hello,

i am trying to implement the basic checkpoint/restore of looper container using busybox image mentioned in many examples.

i could checkpoint the container successfully but restoring the container starts again from the first leaving the checkpointed image.

on entering into the checkpointed image, i found that there are many missing files such as 

1) config.json
2) criu.work
3) eventfd.img
3) eventpoll.img
4) inetsk.img
5) ip6tables-9.img
6) iptables-9.img
7) pipes-data.img
8) pipes.img
9) unixsk.img

Is any of this related to criu. I read from the previous posts that config.json is a docker issue. but about criu.work folder which has all the logs are dependent on CRIU? 

criu check looks good.  i use docker container  -->  docker version 19.03.6   --> criu version 3.11  

any help would be helpful.
thanks in advance.

**Comment by adrianreber** [comment]
Closing this as it does not seem to be CRIU problem.
