### ISSUE TITLE
i686 Build

### ISSUE THREAD

**Issue by radumamy** [checkpoint-restore/criu#1654]
Question: Is it possible to build `criu` in an i686 environment? Could I please have some suggestions to what distro/version to use in order to get this working? Thank you.

**Comment by adrianreber** [comment]
CRIU does not support i686

There is a 32bit compatibility mode: https://criu.org/32bit_tasks_C/R Not sure if that would be helpful.

**Comment by radumamy** [comment]
Understood, thank you @adrianreber.
