### ISSUE TITLE
criu check fails in docker container

### ISSUE THREAD

**Issue by satbekmyrza** [checkpoint-restore/criu#1663]
**Description**

I am trying to build CRIU in a Docker container running Ubuntu 18.04. CRIU builds without errors, but `criu check` fails. I am signed in as `root`. 

System info:
```
/code/criu# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

/code/criu# uname -a
Linux 574279c8dc49 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

This is the Dockerfile I used to build the Docker image and then a container:
```
FROM       ubuntu:18.04

RUN apt-get update

RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd

RUN echo 'root:root' |chpasswd

RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN mkdir /root/.ssh

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22

CMD    ["/usr/sbin/sshd", "-D"]
```

**Steps to reproduce the issue:**
1. Create a Docker image
2. Create a Docker container from the image  
Inside the container:
3. Clone CRIU sources
4. Install dependencies
5. Build CRIU
6. Run ./criu check

**The result I received:**
```
/code/criu# criu/criu check 
Error (criu/util.c:635): exited, status=1
Error (criu/util.c:635): exited, status=1
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:224): unix: Unable to open a socket file: Operation not permitted
Error (criu/net.c:3726): Unable create a network namespace: Operation not permitted
Warn  (criu/net.c:3782): NSID isn't reported for network links
Warn  (criu/net.c:3442): Unable to get socket network namespace
Error (criu/net.c:1246): Unexpected error: -1(Operation not permitted)
Error (criu/kerndat.c:1166): Unable create a network namespace: Operation not permitted
Error (criu/util.c:1339): Can't wait or bad status: errno=0, status=256
Error (criu/kerndat.c:1359): kerndat_has_nftables_concat failed when initializing kerndat.
Error (criu/crtools.c:210): Could not initialize kernel features detection.
```

**The result I expected:**
```
/code/criu# criu/criu check
Looks good.
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
/code/criu# criu/criu --version
Version: 3.16.1
GitID: v3.16.1
```

**Comment by adrianreber** [comment]
You don't say how you started the container. But you have to start your container engine with `--privileged` to be able to use CRIU in the container.

**Comment by satbekmyrza** [comment]
> You don't say how you started the container. But you have to start your container engine with `--privileged` to be able to use CRIU in the container.

Yes, thanks for pointing that out. I 'reran' the image with `--privileged` and now I can see `Looks good.`
However, the full output of `./criu check` is:
```
/code/criu# criu/criu check
Error (criu/util.c:635): exited, status=1
Error (criu/util.c:635): exited, status=1
Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
Looks good.
```

Should I be concerned about it?

**Comment by adrianreber** [comment]
> Should I be concerned about it?

Not really. CRIU checks the system on the first run and stores the information on a `tmpfs` (`/run`). On every subsequent CRIU start this file is read to speedup CRIU initialization. If `/run` is not a `tmpfs` you get an error like the one you see. Starting the container with `--tmpfs /run` will silence the error. CRIU's functionality will not change. The second startup is just faster. So it depends on how often you plan to start CRIU in your container and if it speed is important to your use case.

**Comment by satbekmyrza** [comment]
Thank you @adrianreber, the issue is solved.
