### ISSUE TITLE
fail to restore after killing a restored process

### ISSUE THREAD

**Issue by satbekmyrza** [checkpoint-restore/criu#1665]
While playing around with CRIU, I noticed the following:

1. I ran a simple Java program with a loop that contains `Thread.sleep(1000);`. 
2. I ran `criu dump -t <pid> -o dump.log -vvv -D <ckpt-dir1> --shell-job`
3. Then I restored the checkpoint by `criu restore -vvv -o restore.log --shell-job -D <ckpt-dir1>`
4. Then I dumped the restored checkpoint again to a different directory `criu dump -t <pid> -o dump.log -vvv -D <ckpt-dir2> --shell-job`
5. Then I restored the checkpoint in [4] `criu restore -vvv -o restore.log --shell-job -D <ckpt-dir2>`
6. Then I killed the process `kill <pid>`

After killing the process, I cannot restore neither `<ckpt-dir1>` nor `<ckpt-dir2>`. The following is the output of `criu restore`:
```
$ criu restore -vvv -o restore.log --shell-job -D <ckpt-dir1> // no output
$ criu restore -vvv -o restore.log --shell-job -D <ckpt-dir2>
Aborted (core dumped)
```

Is this the expected behavior?

**Comment by adrianreber** [comment]
That is not expected. Please share the log files for all dumps and restores.

**Comment by satbekmyrza** [comment]
Logs: [https://gist.github.com/satbekmyrza/52d03a4b43adf6512e0fec01644787a0](url)

- ch1-dump.log - after [2]
- ch1-restore.log - after [3]
- ch2-dump.log - after [4]
- ch2-restore.log - after [5]
- ch1-restore.log.afterkill - after [6] and `criu restore -vvv -o restore.log --shell-job -D <ckpt-dir1>`
- ch2-restore.log.afterkill, ch1-restore.log.afterkill.2 - after [6] and `criu restore -vvv -o restore.log --shell-job -D <ckpt-dir2>`. There are two files, because `criu restore` printed `Aborted (core dumped)` only on the second run. 

I tried creating a longer chain of checkpoint and restores like above. If the restored process is killed at any of the 'parts' of the chain, none of the others can be restored. 

I am running CRIU in a Docker container running:
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

# uname -a
Linux 377a83190b55 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Also, need to note that I didn't include `--tmpfs /run` option when starting the Docker container as was suggested in #1663.

**Comment by adrianreber** [comment]
The log says you are using CRIU 3.6. Can you try 3.16.1?

**Comment by satbekmyrza** [comment]
Logs for `v3.16.1`: https://gist.github.com/satbekmyrza/70f13d8aa168189cdcbccc70d46a5754

Unfortunately, `v3.16.1` produces the same result. The only difference from `v3.6` is that `v3.16.1` does not produce any `Aborted (core dumped)` output.

Sample run with a longer chain of C/R. `# num` is to indicate the order of commands for reference.
Terminal 1:
```
root@377a83190b55:~# java Test   # 1
0
1
2
Killed
root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch1/  # 4
3
4
5
root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch2/  # 6
6
7
8
9
root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch3/  # 8
10
11
12
13
^C  # 9

root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch3/  # 10
root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch2/  # 11
root@377a83190b55:~# criu/criu/criu restore -vvv -o restore.log --shell-job -D ch1/  # 12
root@377a83190b55:~# 
```

Terminal 2:
```
root@377a83190b55:~# ps -aux | grep " java "  # 2
root     50022  2.2  0.0 40040304 34204 pts/0  Sl+  08:15   0:00 java Test
root     50127  0.0  0.0  13220  1092 pts/1    S+   08:15   0:00 grep --color=auto  java 
root@377a83190b55:~# criu/criu/criu dump -o dump.log -vvv -D ch1/ --shell-job -t 50022  # 3
root@377a83190b55:~# criu/criu/criu dump -o dump.log -vvv -D ch2/ --shell-job -t 50022  # 5
root@377a83190b55:~# criu/criu/criu dump -o dump.log -vvv -D ch3/ --shell-job -t 50022  # 7
root@377a83190b55:~# 
```

**Comment by rst0git** [comment]
```
(00.017434)  35174: Error (criu/files-reg.c:1719): Can't open file tmp/hsperfdata_root/35174 on restore: No such file or directory
(00.017439)  35174: Error (criu/files-reg.c:1658): Can't open file tmp/hsperfdata_root/35174: No such file or director
```
You might need to use `java -XX:-UsePerfData ...` to resolve this problem.

**Comment by adrianreber** [comment]
Exactly what @rst0git is saying. During restore all files need to be the same as during checkpointing. If files are changing the possibility for crashes is high and CRIU checks the file size to make sure that the file did not change. If the file has the same size CRIU will do the restore, but the application might be confused because the content of the file changed unexpected.

Either you need to ensure that the restore has access to the same files or, like @rst0git suggested, certain files are not created. In your case there is an easy solution.

**Comment by satbekmyrza** [comment]
Thanks @rst0git, using `java -XX:-UsePerfData ...` worked.
