### ISSUE TITLE
Support restoring multiple copies of the same container

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#167]
I'm using the experimental Docker build with C/R support to restore multiple copies of the same container on the same host. I was having networking issues when trying to restore a second container after having already restored one copy, and realized it was because the IP address in the criu image did not match the container's address. The IP addresses in the criu image stay the same (of course), but each new container has a new address (and the container's address is referenced by most sockets in the criu image, unsurprisingly). This mismatch was giving me the error "Error (sk-inet.c:748): Can't connect inet socket back: Invalid argument" (which wasn't too helpful; I wonder if that message can be improved).

So, I tried using CRIT to modify the criu image and replace the container address at the time of checkpoint with the actual address at the time of restore, which worked. I'm opening this issue then as a query / feature request as to whether criu plans to add a nice cli for the restore subcommand, for example, to handle scenarios like this. Possibly something like "criu restore --replace-ip=100.100.0.1:100.100.0.2". I would think this isn't too uncommon of a use case, especially once Docker fully integrates with criu. Or, if there are currently better workarounds to handle this situation, I'd love to hear them. Thanks for the consideration!

**Comment by xemul** [comment]
> "Error (sk-inet.c:748): Can't connect inet socket back: Invalid argument" 
> (which wasn't too helpful; I wonder if that message can be improved).

:) Yes, the message can be improved. Log messages are not cut in stone, so feel free to update them the way you think they should be.

> I'm opening this issue then as a query / feature request as to whether 
> criu plans to add a nice cli for the restore subcommand, for example, to 
> handle scenarios like this. Possibly something like
> "criu restore --replace-ip=100.100.0.1:100.100.0.2". 

Yes, this would be good to have. We already have the --cgroup-root option that replaces cgroups root paths from image onto something else. Having something generic enough to substitute arbitrary stuff would be nice. I can't say whether us, Virtuozzo, will implement it soon, but if you would like to start -- we're always ready to help.

**Comment by xemul** [comment]
Cc @avagin

**Comment by tswift242** [comment]
@crosbymichael @dmcgowan This is an important piece to support certain use cases, such as cloning certain apps. This pain point still exists with the latest docker c/r support (and the latest containerd c/r support based on our talk).
