### ISSUE TITLE
docker restore did not work as expected

### ISSUE THREAD

**Issue by surenraju** [checkpoint-restore/criu#1679]
**docker restore did not work as expected**

I am following the example provided in the official documentation https://criu.org/Docker. But steps mentioned in the documentation and results did not match the results in my environment. 

**Steps to reproduce the issue:**
Execute the following command and check the logs after
```
docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
```
```
docker checkpoint create looper checkpoint1
```

```
docker start --checkpoint checkpoint1 looper
```

**Describe the results you received:**
There is no errors while restoring the checkpoint. However,  after restoring the container from the checkpoint, the work completed by previous container is repeated. 

Example logs 0 1 2 3 4 0 1 2 3

**Describe the results you expected:**
After restoring the container from checkpoint, container should continue from the checkpoint, should not start from the beginning

Example logs 0 1 2 3 4 5 6 7 8

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.6
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
```
uname -a
Linux ip-172-31-44-121 5.4.0-1058-aws #61~18.04.3-Ubuntu SMP Fri Oct 1 14:04:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adrianreber** [comment]
Unfortunately the docker support is always a bit problematic. There are some versions that do not work correctly and it seems you have found one of those versions. Try to update Docker or maybe try Podman which should work much better.

Please let us know which version of Docker you use.

**Comment by surenraju** [comment]
@adrianreber 
```
docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:48 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by adrianreber** [comment]
I do not know which Docker versions are working but @rst0git usually does.

**Comment by surenraju** [comment]
@adrianreber 

Tried with podman and it worked beautifully. 

```
 podman run -dt --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

 podman logs looper

 podman container checkpoint looper

 podman logs looper

 podman container restore looper

 podman logs looper
```
@rst0git Please let me know the docker versions supported.

**Comment by adrianreber** [comment]
> Tried with podman and it worked beautifully.

Perfect!

**Comment by rst0git** [comment]
> @rst0git Please let me know the docker versions supported.

Hi @surenraju, you need to upgrade [containerd](https://github.com/containerd/containerd/releases) to version 1.5.0 or newer. For example, you can install the latest version from GitHub as follows:

```bash
CONTAINERD_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/containerd/containerd/releases/latest | grep '"browser_download_url":.*/containerd-.*-linux-amd64.tar.gz.$' | cut -d\" -f4)
wget -nv "$CONTAINERD_DOWNLOAD_URL" -O - | sudo tar -xz -C /usr/
```
Note that after upgrade you need to restart the systemd service: `sudo systemctl restart containerd.service`

**Comment by surenraju** [comment]
@rst0git thank you very much. After upgrading the containerd to version 1.5.0 or newer as you mentioned, it worked as expected.
