### ISSUE TITLE
Error (criu/kerndat.c:1048): Unexpected error from clone3 on OL8.4

### ISSUE THREAD

**Issue by dineshputchala** [checkpoint-restore/criu#1683]
Description: /sbin/criu  check is failing with "Error (criu/kerndat.c:1048): Unexpected error from clone3" on OracleLinux8.4

bash-4.4# /sbin/criu  check --version
Version: 3.15
GitID: f9533f0

bash-4.4# /sbin/criu  check --all
Error (criu/kerndat.c:1048): Unexpected error from clone3
: Invalid argument
Error (criu/kerndat.c:1181): kerndat_has_clone3_set_tid failed when initializing kerndat.
Error (criu/crtools.c:213): Could not initialize kernel features detection.
Error (criu/kerndat.c:1048): Unexpected error from clone3
: Invalid argument
Error (criu/kerndat.c:1181): kerndat_has_clone3_set_tid failed when initializing kerndat.
Error (criu/crtools.c:213): Could not initialize kernel features detection.

bash-4.4# cat /etc/oracle-release
Oracle Linux Server release 8.4

bash-4.4# uname -r
5.4.17-2102.203.6.el8uek.x86_64

Can you please check ?

**Comment by adrianreber** [comment]
This is known. An incomplete Backport of clone3 in the Oracle kernel. Nothing we can do.

**Comment by adrianreber** [comment]
See #1592
