### ISSUE TITLE
restore fails with glibc-2.34.9000-30.fc36.x86_64

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#1695]
The CI tests fail with the following error when running on Fedora Rawhide:

```
Error (criu/cr-restore.c:1480): 56 killed by signal 11: Segmentation fault
Error (criu/cr-restore.c:2470): Restoring FAILED.
```

This reason for this error appears to be a change in [glibc-2.34.9000-30.fc36](https://src.fedoraproject.org/rpms/glibc/c/0c78549fbcc7bdf354fb87adf487839604444060). After downgrading to [glibc-2.34.9000-29.fc36](https://koji.fedoraproject.org/koji/buildinfo?buildID=1866396) the tests work as expected.

This problem has been reported in https://bugzilla.redhat.com/show_bug.cgi?id=2033397.

**Comment by mihalicyn** [comment]
Wow. Interesting...
this change looks very suspicious https://patches-gcc.linaro.org/patch/64865/

**Comment by adrianreber** [comment]
If you look at the mentioned bugzilla tickets, it seems like CRIU is missing support for the rseq syscall.

**Comment by rst0git** [comment]
Duplicate of https://github.com/checkpoint-restore/criu/issues/1696
