### ISSUE TITLE
Implement rseq support, as required by glibc 2.35

### ISSUE THREAD

**Issue by fweimer-rh** [checkpoint-restore/criu#1696]
glibc 2.35 enables restartable sequences (rseq) during process startup. This designates a memory area, associated with each thread, to which the kernel can write as it sees fit.

This has two consequences for CRIU: A restored process can crash once the memory for the registered rseq area is unmapped (this is the rseq area for the *new* process). And the restored process, when running, will appear to present a successful rseq registration, but the kernel will not write to the rseq areas of any restored threads.

Linux 5.13 added `PTRACE_GET_RSEQ_CONFIGURATION` in commit torvalds/linux@90f093fa8ea48e5d991332cee160b761423d55c1 to support checkpoint and restore.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2033397

**Comment by adrianreber** [comment]
Seeing https://github.com/torvalds/linux/commit/90f093fa8ea48e5d991332cee160b761423d55c1 was developed by Google to support checkpoint/restore I am wondering if Google has already a patch for this for their internal CRIU version.

@mclapinski you seemed to have worked on CRIU for Google. Do you know if anything regarding rseq exists in Google's version of CRIU?

**Comment by mihalicyn** [comment]
@fweimer-rh thanks a lot for looking into this!

If nobody wants to implement that and our Google friends have no support of that feature yet I'm ready to take this issue on myself.

**Comment by adrianreber** [comment]
Please revert #1697 again if this is fixed.

**Comment by mihalicyn** [comment]
I've played with `rseq` locally and written dump part implementation. But before diving into full and prod-ready implementation let's wait 1-2 days for some response from our friends.

**Comment by figiel** [comment]
Hi, this was used only in a prototype. I don't have a production ready patch for CRIU which would use this yet (and not planning to focus on that in upcoming weeks).

**Comment by adrianreber** [comment]
@figiel Thanks for your feedback.

**Comment by fweimer-rh** [comment]
Is there anything I can to do to help with moving this forward? Thanks.

**Comment by adrianreber** [comment]
This is the announcement of CentOS 9 also wanting to switch to rseq: https://lists.centos.org/pipermail/centos-devel/2022-January/120153.html

**Comment by melsamathew** [comment]
I am facing one issue with glibc upgrade, so found this thread while searching for the error.. Is this issue related to the rseq support in glibc? Please see the problem below and give support for this

We are currently using CRIU version 3.15 for checkpoint and restore operations in our Linux application.
The environment consists of Glibc 2.40 and GCC 14.2.0.
While the checkpoint (dumping) process is successful, we encounter an issue during restore, where the process fails with the following error:

(00.064198) pie: 5495:    `- skip pagemap
(00.064199) pie: 5495:    `- skip pagemap
(00.064201) pie: 5495:    `- skip pagemap
(00.064297) Error (criu/cr-restore.c:1573): 5495 killed by signal 127: Unknown signal 127
(00.064335) Error (criu/cr-restore.c:2498): Restoring FAILED.
Our query is whether there could be any compatibility issues between CRIU 3.15 and the newer versions of Glibc (2.40) and GCC (14.2.0). Specifically, we would like to know:

Under what circumstances can CRIU throw an "unknown signal 127" during a restore?
How can we debug this issue further to pinpoint the cause?
We appreciate any insights or suggestions to help resolve this issue.

**Comment by adrianreber** [comment]
@melsamathew If you have a new enough kernel your application will use restartable sequences with that version of glibc. Your version of CRIU is too old to handle it.

You can try to set `GLIBC_TUNABLES=glibc.pthread.rseq=0` before starting your application the first time. This will tell glibc to not use restartable sequences and then your old version of CRIU should work.

**Comment by melsamathew** [comment]
Thank you for the suggestion. I tried setting GLIBC_TUNABLES=glibc.pthread.rseq=0 before starting the application, but the restore process still fails with the unknown signal 127. Here are the relevant logs:
task_args->thread_args: 0x24540
(00.002217) pie: 6809: Switched to the restorer 6809
(00.071453) Error (criu/cr-restore.c:1573): 6809 killed by signal 127: Unknown signal 127
(00.071499) Error (criu/cr-restore.c:2498): Restoring FAILED.
Could you suggest how to resolve or debug this issue further, or is it a known problem in CRIU?

**Comment by adrianreber** [comment]
As mentioned in the comment before. Your version is too old. Setting the variable is a workaround.
