### ISSUE TITLE
No rule to make target 'umount2' when make test

### ISSUE THREAD

**Issue by Yangfisher1** [checkpoint-restore/criu#1699]
Hi, I'm trying to make a pull request, so I followed the instruction [How_to_submit-patches](https://criu.org/How_to_submit_patches). Entering `make` seemed all right, but when I entered `make test`, it showed out that `make[3]: *** No rule to make target 'umount2'.  Stop.`. And I checked out the `Makefile` in `test` directory. It actually doesn't have the target `umount2`, and the branch is `criu-dev`. So is there any solution for this problem? Also I want to know that is there anything I should pay attention to if I want to make a pull request? Thanks for your help!

**Comment by mihalicyn** [comment]
@Yangfisher1 hi,

please tell us, do you have the same error when trying the `sudo ./test/zdtm.py run -a`?

The problem probably is that when you run `make test` all environment variables from "root" make passes through zdtm.py to nested make here:
```
    def available():
        if not os.access("umount2", os.X_OK):
            subprocess.check_call(["make", "umount2"])
...
```

I will send a fix for this problem. But I'm not sure that `make test` works perfectly in all cases.

**Comment by mihalicyn** [comment]
Please feel free to post your PR if `./test/zdtm.py run -a` passes.

Thanks,
Alex

**Comment by Yangfisher1** [comment]
Thanks a lot! It really worked out, but the result showed that the kernel is tainted. I'll try to use another machine cause the machine is shared with many people. Anyway, I'll post a PR as long as I solve the problem.

**Comment by adrianreber** [comment]
> Thanks a lot! It really worked out, but the result showed that the kernel is tainted. I'll try to use another machine cause the machine is shared with many people. Anyway, I'll post a PR as long as I solve the problem.

There is the option --ignore-taint which should ignore it for your local test.

**Comment by Yangfisher1** [comment]
Wow, I'll try this one too, thanks.

**Comment by Yangfisher1** [comment]
May I ask a question more? I ran `sudo ./zdtm.py run -a`, when testing `zdtm/static/net_lock_socket_iptables`, it showed out that
```
Running zdtm/static/net_lock_socket_iptables.hook(--post-start)
./net_lock_socket_iptables --pidfile=net_lock_socket_iptables.pid --outfile=net_lock_socket_iptables.out
Traceback (most recent call last):
  File "zdtm/static/net_lock_socket_iptables.hook", line 44, in <module>
    test_sock = socket.create_connection((server_addr, PORT), TIMEOUT)
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
So I checked the code, it created a UNIX socket with name `\0internal_server`, and used a child process as a client to connect with it. However, the child process connected to `127.0.0.1:8880` rather than `\0internal_server`. I guess that's why the error occurred?

**Comment by Yangfisher1** [comment]
Or maybe I can just simply replace the `test_sock = socket.create_connection((server_addr, PORT), TIMEOUT)` in `test/zdtm/static/net_lock_socket_iptables.hook` with
```
    s2 = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s2.connect(INTERNAL_SERVER)
```
I wrote a simple python script to test it, it ran well and no error for `Connection refused`, here is my code.
```
PORT = 8880
TIMEOUT = 0.1
INTERNAL_SERVER = "\0internal_server"

internal_sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
internal_sock.bind(INTERNAL_SERVER)
internal_sock.listen(1)

print(internal_sock.getsockname())

# Wait for test server to be ready
server_addr = "127.0.0.1"

pid = os.fork()
if pid == 0:
    os.setsid()  # Detach from parent
    s2 = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s2.connect(INTERNAL_SERVER)
    # test_sock = socket.connect(INTERNAL_SERVER, TIMEOUT)

while True:
    pass
```

**Comment by Yangfisher1** [comment]
It did solve the problem, now there is no `Connection Refused` error, but it just stuck there. The test showed that it ran the hook with `--post-start`, so it just hung there waiting for message while `test_sock` did nothing. The output is below. I just use a unmodified criu-dev branch to test, so I don't know why this happened.

**Comment by Yangfisher1** [comment]
I don't know why, but running `sudo make test` won't throw the error, but sometimes it can also be stuck at the test `zdtm/static/net_lock_socket_iptables`, maybe there're still some bugs, but anyway, it can at least pass the whole test sometimes.(I mean, if the last line of the output is 
```
==================== Test zdtm/transition/thread-bomb PASS =====================
```
, does that mean I pass the whole test?)

**Comment by adrianreber** [comment]
If you get a return code of 0, then all tests were running successfully.
