### ISSUE TITLE
Don't lose pull request information on release branch

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1704]
Our current development model (`criu-dev` and `master`) has, from my point of view, the problem that we lose the link between commit and pull request on the `master` branch. It becomes difficult to find the corresponding pull request and discussion once we move code to our release branch (`master`).

I see two possible approaches how solve this.

1. Only use a single branch. We used to have more unfinished features on `criu-dev` previously. For 3.16 the only thing which is `criu-dev` only is the `flog` support. So instead of developing against `criu-dev` and then manually merging basically everything back to master, we could just use a single branch. This seems to be a common approach for many projects.
2. Add the PR information to the commit message. Like we see in the Linux kernel with links to the mailing list discussions. (`Link:`). As we rely on the github interface I am not sure there is an easy way to change commit messages. Before merging someone (the PR submitter or the person merging the PR) would need to adapt the commit message and add a line (`Link: https://github.com/checkpoint-restore/criu/pull/number`). We could also amend all pull request commits with the corresponding PR during release preparation while merging commits to the release branch (I guess that a half-scripted solution should be possible).

I have no strong opinion on any of those approaches, but something like these two approaches (or something else) would be helpful I think. I had to search a couple of times for merged pull requests any would have preferred it there is an easy link between a commit and a pull request.

@checkpoint-restore/maintainers any comments, feedback? Should we just leave everything as is? Or would it make sense to change something?

**Comment by Snorch** [comment]
I don't have strong opinion on this too.

On one hand it's hard to search for PR by commit, main problem is that github merges search results for PRs and issues, e.g.: https://github.com/checkpoint-restore/criu/search?q=restore+current+work+directory+after+restoring+mnt+ns&type=issues It becomes better with `""` though https://github.com/checkpoint-restore/criu/search?q=%22restore+current+work+directory+after+restoring+mnt+ns%22&type=issues .

On the other hand there are BIG features like mount-v2 or nested namespaces support (pid, user and so on) which may not be reviewed in one piece, and if we want to add (port from VZ) them we need to merge some "preparational" changes, some of which may only be needed for a future-comming feature... Maybe that was the initial reason why we wanted criu-dev, to collect the whole feature first in criu-dev and only then merge it to master.

**Comment by avagin** [comment]
In the ideal cases, all discussions in PR-s to be summarized in proper commit messages.
