### ISSUE TITLE
Rust bindings for CRIU

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1722]
I created rust bindings for CRIU and I pushed them temporarily to https://github.com/adrianreber/rust-criu

@nviennot as criu-image-streamer is in Rust, maybe you could have a look at my code. If it makes sense so far.

I tried to follow what we have done in go-criu and provide a similar interface in Rust. The main difference to the Go bindings is that I do not plan to expose the RPC interface directly but I rather would prefer to have wrapper as we do in libcriu.

@checkpoint-restore/maintainers in case anyone wants to look over it, please let me know if you have any feedback.

**Comment by adrianreber** [comment]
@avagin Can you create a rust-criu project under checkpoint-restore.

I have a working checkpoint support PR for youki open and would like to move the rust-criu bindings away from my personal account to checkpoint-restore: https://github.com/containers/youki/pull/641

**Comment by avagin** [comment]
https://github.com/checkpoint-restore/rust-criu

**Comment by adrianreber** [comment]
Thanks.
