### ISSUE TITLE
Error when restoring same process in multiple containers simultaneously with host network namespace

### ISSUE THREAD

**Issue by new-sashok724** [checkpoint-restore/criu#1735]
Hello! I am running multiple copies of application (from same dump) in different Podman containers. When i try to restore them simultaneously (not one after another, but concurrently), CRIU sometimes fails to bind abstract unix socket because it is bound by some other CRIU instance in different container, but same host network namespace. This bug happens only with `--network=host`.

**Steps to reproduce the issue:**
1. `podman run -it --privileged --network=host --name=app-container app-base-image` (app will dump itself inside container)
2. `podman commit app-container app-dumped-image`
3. Run multiple containers from dumped app image simultaneously:
`podman run -t --privileged --network=host --name=app-copy1 -e app-settings=1 app-dumped-image &`
`podman run -t --privileged --network=host --name=app-copy2 -e app-settings=2 app-dumped-image &`
`podman run -t --privileged --network=host --name=app-copy3 -e app-settings=3 app-dumped-image &`
`podman run -t --privileged --network=host --name=app-copy4 -e app-settings=4 app-dumped-image &`
`podman run -t --privileged --network=host --name=app-copy5 -e app-settings=5 app-dumped-image &`

Command used to restore application inside container: `criu restore -D criu -v4 -o criu-restore.log -l -j --tcp-close --skip-in-flight`

**Describe the results you received:**
CRIU successfully restored application in all containers

**Describe the results you expected:**
Some copies of application failed to restore
[criu-dump.log](https://github.com/checkpoint-restore/criu/files/7954045/criu-dump.log)
[criu-restore.log](https://github.com/checkpoint-restore/criu/files/7954046/criu-restore.log)

CRIU Version: 3.16.1

<details><summary>Output of `criu check --all` (inside container):</summary>
<p>

Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

</p>
</details>

**Comment by avagin** [comment]
I think https://github.com/avagin/criu/commit/43e3e68e5609b2eed7016091ff7ba89cbfd9cfcd has to fix this issue. Could you try it out?
