### ISSUE TITLE
criu-ns returns non-0 exit code after successful dump

### ISSUE THREAD

**Issue by PavloMykhailyshyn** [checkpoint-restore/criu#1739]
I noticed one strange error
when I run the dump with criu and it succeeds, criu returns 0
but when I run criu-ns and it succeeds too - return code is now 5
I checked the logs for both criu and criu-ns everything is the same (dump successful)

**Comment by PavloMykhailyshyn** [comment]
@rst0git you did a mistake here
```
def wrap_dump():
    (pid, pid_idx) = get_varg(('-t', '--tree'))
    if pid is None:
        raise OSError(errno.EINVAL, 'No --tree option given')

    set_pidns(pid, pid_idx)
    set_mntns(pid)

    criu_pid = os.fork()
    if criu_pid == 0:
        run_criu(sys.argv[1:])
    return _wait_for_process_status(pid)
```
Instead of passing **criu_pid** to the function `_wait_for_process_status(PID)` you passed PID of the dumping process
that is why criu-ns always returns 5 (-251)

**Comment by rst0git** [comment]
@PavloMykhailyshyn Thank you for pointing this out. I've opened a pull request with a fix: https://github.com/checkpoint-restore/criu/pull/1740
