### ISSUE TITLE
Cannot checkpoint container (which writes to directory mounted using -v flag)

### ISSUE THREAD

**Issue by 108anup** [checkpoint-restore/criu#1745]
**Description**
I am facing issues with check-pointing a container that writes to a mounted directory. If I run the checkpoint before the container dirties the mounted path, then the checkpoint succeeds. But if I make the checkpoint after dirtying, then the checkpoint fails.

I am not sure if criu even handles or is supposed to handle mounted directories. E.g., at restore time would it change the state of the mounted directory to exactly as it was at checkpoint time? What if there were some read-only changes made to the mount by other processes which shouldn't be touched by the restored container, but still could affect semantics of the restored container... I would imagine checkpoint-restore would require some kind of (read-only/write/etc.) annotations for shared mounts.

**Steps to reproduce the issue:**
Versions:
OS: Ubuntu 18.04.4
kernel: 5.4.0-1068-azure (this is on an azure machine)
CRIU version: 3.6 (installed from ppa)
docker version: 20.10.7

Container used:
https://hub.docker.com/r/broadinstitute/gatk

Commands: I use a set of scripts and inputs that call gatk binary. Might take more effort to share everything. I suspect the issue is due  to file writes in mounted dir. 

**Describe the results you received:**

Error message:
```
Error response from daemon: Cannot checkpoint container gatk_bg: runc did not terminate successfully: exit status 1: criu failed: type NOTIFY errno 0 path= /run/containerd/io.containerd.runtime.v2.task/moby/e8b12e79b32cae761045e3917616ade968318a5f1ebf7b25f2b4b7a39d60bb45/criu-dump.log: unknown

```

Tail of error log:
```
(00.199611) Dumping path for 77 fd via self 87 [/gatk/mnt/tmp/spark-af28dfc2-9d52-49cc-8a02-fa030428aea8/userFiles-74802758-9b49-4feb-8bf9-1745c0134f22/dbsnp_138.b37.20.21.vcf]
(00.199653) 2126 fdinfo 78: pos:                0 flags:           100000/0
(00.199680) Dumping path for 78 fd via self 88 [/gatk/mnt/tmp/spark-af28dfc2-9d52-49cc-8a02-fa030428aea8/userFiles-74802758-9b49-4feb-8bf9-1745c0134f22/human_g1k_v37.20.21.fasta]
(00.199730) 2126 fdinfo 79: pos:         0x180c0e flags:           100000/0
(00.199760) Dumping path for 79 fd via self 89 [/gatk/mnt/tmp/spark-af28dfc2-9d52-49cc-8a02-fa030428aea8/userFiles-74802758-9b49-4feb-8bf9-1745c0134f22/dbsnp_138.b37.20.21.vcf]
(00.199807) 2126 fdinfo 80: pos:                0 flags:             4002/0
(00.199824)     Searching for socket fefc4 (family 2.6)
(00.199830) Error (criu/sk-inet.c:174): Connected TCP socket, consider using --tcp-established option.
(00.199842) ----------------------------------------
(00.199871) Error (criu/cr-dump.c:1352): Dump files (pid: 2126) failed with -1
(00.202248) Unlock network
(00.202260) Running network-unlock scripts
(00.202265)     RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.241486) Unfreezing tasks into 1
(00.244025) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

FYI: `/gatk/mnt` is the mounted path.

**Comment by adrianreber** [comment]
It says to use `--tcp-established`. Try that. I guess that docker does not expose this option to the user. Either use a criu configuration file to enable `--tcp-established` or try Podman. Podman has better checkpoint/restore integration and exposes `--tcp-established`.

The error is completely unrelated to writing to directories. It is just about established TCP connections.

**Comment by 108anup** [comment]
Thanks. I will try criu config and/or podman.

I was still curious on how check-pointing is done for dirty files in mounted directories as the semantics might be application dependent.

**Comment by adrianreber** [comment]
> Thanks. I will try criu config and/or podman.
> 
> I was still curious on how check-pointing is done for dirty files in mounted directories as the semantics might be application dependent.

Everything which is outside of the container has to be handled by the user. Everything inside the container, in the case of podman, is handled by podman. Docker does not handle changed files automatically.

**Comment by 108anup** [comment]
I am able to checkpoint the container but the the restore fails now.
The restore is not able to find a local file. I would imagine that criu would checkpoint all local files needed.

**Error message:**
```
Error response from daemon: OCI runtime restore failed: criu failed: type NOTIFY errno 0
log file: /run/containerd/io.containerd.runtime.v2.task/moby/f2b9a1ca03ed6c0b88fe1a25725ee269c1a9b9264c3d78cb95a8b1fe753f4e72/work/restore.log: unknown
```

**Error log tail:**
```
(04.805654)     14: sockets:    set keepidle for socket
(04.805660)     14: sockets:    set keepintvl for socket
(04.805673)     14:             Create fd for 54
(04.805713)     14: Error (criu/files-reg.c:2143): Can't open file gatk/data/tmp/spark-02a34fb2-f6a6-4a7f-ac4e-f3528c102269/userFiles-039a8466-fd29-47b6-9b75-8ad3d07e16f7/dbsnp_138.b37.20.21.vcf on restore: No such file or directory
(04.805729)     14: Error (criu/files-reg.c:2086): Can't open file gatk/data/tmp/spark-02a34fb2-f6a6-4a7f-ac4e-f3528c102269/userFiles-039a8466-fd29-47b6-9b75-8ad3d07e16f7/dbsnp_138.b37.20.21.vcf: No such file or directory
(04.805735)     14: Error (criu/files.c:1200): Unable to open fd=55 id=0x74
(04.849111) pie: 12: `- returned 204800
(04.849138) pie: 12:    `- skip pagemap
(04.849141) pie: 12:    `- skip pagemap
(04.849145) pie: 12:    `- skip pagemap
(04.849149) pie: 12:    `- skip pagemap
(04.849152) pie: 12:    `- skip pagemap
(04.849155) pie: 12:    `- skip pagemap
(04.849159) pie: 12:    `- skip pagemap
(04.849162) pie: 12:    `- skip pagemap
(04.849166) pie: 12:    `- skip pagemap
(04.849169) pie: 12:    `- skip pagemap
(04.849173) pie: 12:    `- skip pagemap
(04.849176) pie: 12:    `- skip pagemap
(04.849180) pie: 12:    `- skip pagemap
(04.849191) pie: 12: vdso: Parsing at 0x7fff0278c000 0x7fff0278d000
(04.849196) pie: 12: vdso: PT_LOAD p_vaddr: 0x0
(04.849200) pie: 12: vdso: DT_HASH: 0x120
(04.849204) pie: 12: vdso: DT_STRTAB: 0x2d8
(04.849211) pie: 12: vdso: DT_SYMTAB: 0x1b8
(04.849215) pie: 12: vdso: DT_STRSZ: 0x72
(04.849219) pie: 12: vdso: DT_SYMENT: 0x18
(04.849224) pie: 12: vdso: nbucket 0x3 nchain 0xc bucket 0x7fff0278c128 chain 0x7fff0278c134
(04.849232) pie: 12: vdso: image [vdso] 0x7fff0278c000-0x7fff0278d000 [vvar] 0x7fff02789000-0x7fff0278c000
(04.849238) pie: 12: vdso: Runtime vdso/vvar matches dumpee, remap inplace
(04.849268) pie: 12: vdso: Remap rt-vdso 0x2f000 -> 0x7fff0278c000
(04.849293) pie: 12: vdso: Remap rt-vvar 0x2c000 -> 0x7fff02789000
(04.849306) pie: 12: vdso: Using gettimeofday() on vdso at 0x7fff0278c8a0
(04.849417) pie: 12: Restoring scheduler params 0.0.0
(04.849459) pie: 12: 12: Restored
(04.950288) pie: 13: Task 14 exited, status= 1
(04.950447) pie: 12: Task 13 stopped with 19
(04.963536) mnt: Switching to new ns to clean ghosts
(04.963939) Error (criu/cr-restore.c:2447): Restoring FAILED.
```

**What I do for mounted files:**
I mount a directory at `/gatk/mnt` for input/output files. (e.g., `-v ~/main/genomics/mnt:/gatk/mnt/`)
Then copy the mounted dir as a container local dir (`cp -r mnt data`)
Run the workload and copy back results from local to mounted dir. (`cd data && ./gatk_run.sh && cp -r small-chkpt/output/* ../mnt/small-chkpt/output/`)
I run the checkpoint before the outputs are being copied so the mount point is not dirty. While restoring it complains about not able to find a file which is supposed to be container local.

**Comment by 108anup** [comment]
From this: https://github.com/checkpoint-restore/criu/issues/293, it would seem that I need to:
```
docker pause
docker commit
docker checkpoint create
docker unpause
..
..
docker start  # I need to specify the image here?
```

The issue mentioned is 3 years old, it says that criu does not support automatic checkpointing of paused containers (unable to automatically detect if container is paused). Is that still the case? If I always checkpoint paused containers, can I specify some config for criu to work?

**Comment by 108anup** [comment]
Also how would I restore the checkpoint. This https://github.com/checkpoint-restore/criu/issues/293 says to create a new container from the image and restore the checkpoint on that created container.

But docker start does not support a checkpoint-dir option anymore. I.e., it would maintain its own mapping between container and checkpoint. So how would I restore checkpoint (taken on container A) on container B. I can't restore checkpoint on A because A has advanced and has a different FS image. B is created using committed image but is a different container.

**Comment by adrianreber** [comment]
You are asking a lot of questions at the same time which makes it a bit difficult to answer.

Anyway, please try Podman. That should solve most your problems.

**Comment by adrianreber** [comment]
@108anup Did you have a chance to try Podman? Please close this ticket if it works for you.

**Comment by adrianreber** [comment]
> Hi, I haven't tried podman yet. But I guess this is a docket feature limitation than anything to do with criu, so closing...

Yes, I am pretty sure that it is a Docker problem.

If you have any more questions please ask. Probably best to open a new ticket.

**Comment by rst0git** [comment]
> docker start does not support a checkpoint-dir option anymore.

@108anup there is an issue (https://github.com/moby/moby/issues/37344) and a pull request (https://github.com/moby/moby/pull/41031) for this feature
