### ISSUE TITLE
criu doesn't dump anon shared memory vma-s if it executed over a non-root user

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#175]
```
[root@fc22-vm criu]# python test/zdtm.py run -t zdtm/static/pthread00 -f h  -k always --norst
=== Run 1/1 ================

======================== Run zdtm/static/pthread00 in h ========================
Makefile:299: target 'mnt_enablefs.pid' given more than once in the same rule
Start test
Makefile:299: target 'mnt_enablefs.pid' given more than once in the same rule
./pthread00 --pidfile=pthread00.pid --outfile=pthread00.out
Run criu dump
Wait for zdtm/static/pthread00 to die for 0.100000
======================= Test zdtm/static/pthread00 PASS ========================
[root@fc22-vm criu]# ls -l test/dump/zdtm/static/pthread00/24/1/pagemap-shmem-*.img
-rw-r--r-- 1 root root 14 Jun 16 00:59 test/dump/zdtm/static/pthread00/24/1/pagemap-shmem-205603.img
[root@fc22-vm criu]# 
[root@fc22-vm criu]# 
[root@fc22-vm criu]# python test/zdtm.py run -t zdtm/static/pthread00 -f h  -k always --norst --user
=== Run 1/1 ================

======================== Run zdtm/static/pthread00 in h ========================
Makefile:299: target 'mnt_enablefs.pid' given more than once in the same rule
Start test
Makefile:299: target 'mnt_enablefs.pid' given more than once in the same rule
./pthread00 --pidfile=pthread00.pid --outfile=pthread00.out
Run criu dump
=[log]=> dump/zdtm/static/pthread00/24/1/dump.log
------------------------ grep Error ------------------------
(00.003999) Error (util.c:665): exited, status=3
(00.007890) Error (util.c:665): exited, status=3
------------------------ ERROR OVER ------------------------
Wait for zdtm/static/pthread00 to die for 0.100000
======================= Test zdtm/static/pthread00 PASS ========================
[root@fc22-vm criu]# ls -l test/dump/zdtm/static/pthread00/24/1/pagemap-shmem-*.img
ls: cannot access 'test/dump/zdtm/static/pthread00/24/1/pagemap-shmem-*.img': No such file or directory
```

**Comment by xemul** [comment]
Yup. Due to /proc/pid/map_files :(

**Comment by avagin** [comment]
The problem is that CRIU skips shared mappings silently and we found that only after restore, when processes start seg-faulting.

**Comment by xemul** [comment]
Silently?! The dump_shmem() tries to open /proc/pid/map_files and fails.

**Comment by xemul** [comment]
There's another problem, the so called "greedy mode" of pagemap silently skipped all the pages on dump, not only anon shared, but also anon private :) But this mode is removed from criu.

**Comment by eabatalov** [comment]
Hello. I've run this test on my PC:

 python test/zdtm.py run -t zdtm/static/pthread00 -f h  -k always --norst --user
=== Run 1/1 ================

======================== Run zdtm/static/pthread00 in h ========================
Start test
./pthread00 --pidfile=pthread00.pid --outfile=pthread00.out
Run criu dump
=[log]=> dump/zdtm/static/pthread00/26/1/dump.log
------------------------ grep Error ------------------------
(00.003269) Error (criu/util.c:666): exited, status=3
(00.005050) Error (criu/util.c:666): exited, status=3
(00.007083) Error (criu/ptrace.c:54): Unable to detach from 26: No such process
(00.007088) Error (criu/cr-dump.c:1664): Dumping FAILED.
------------------------ ERROR OVER ------------------------
################# Test zdtm/static/pthread00 FAIL at CRIU dump #################
Wait for zdtm/static/pthread00 to die for 0.100000
##################################### FAIL #####################################

In my case dump is completely failing:
ls test/dump/zdtm/static/pthread00/26/1/
dump.cropt  dump.log

In my dump.log I see that almost nothing works (not only pagemaps):
[dump.zip](https://github.com/xemul/criu/files/400074/dump.zip)

**Comment by xemul** [comment]
Well, yes ;) It won't work just with your patches. I mean I need some functionality that you have implemented to fix this bug.

**Comment by eabatalov** [comment]
Okey. I plan to send you this patches on August :)
