### ISSUE TITLE
Github Workflow Action [criu failed: type NOTIFY errno 0 ]

### ISSUE THREAD

**Issue by Mohsen7s** [checkpoint-restore/criu#1751]
Looks like we cant use criu on github actions. Is there any workaround to fix it ?

Logs:
 ```
Error response from daemon: Cannot checkpoint container f8d6f6058172: runc did not terminate successfully: criu failed: type NOTIFY errno 0 path= /run/containerd/io.containerd.runtime.v2.task/moby/f8d6f605817248ecdf7e44e501fd5dcd4e26e5d127615cb6d83cbcecf3738e66/criu-dump.log: unknown
Error: Process completed with exit code 1.
```

Command : 
```docker checkpoint create --leave-running=false $(docker ps -q) cp0```

**Comment by adrianreber** [comment]
We are using GitHub Actions a lot with CRIU. Still seems to work for us. We would need the log file to understand what is going on.

**Comment by Mohsen7s** [comment]
I am really sorry, I used the docker-compose to create and run container while I had to use docker. This fixed the problem
