### ISSUE TITLE
--ext-unix-sk

### ISSUE THREAD

**Issue by superbu1234** [checkpoint-restore/criu#1766]
I used criu in Ubuntu desktop version and called the desktop application. The following error occurred. What should I do?what is unix[id]?
![image](https://user-images.githubusercontent.com/49075156/157661187-ab073e83-90ee-49ab-8a93-be58447db8ea.png)

**Comment by adrianreber** [comment]
Please share the complete log file when running CRIU with `-v4` and tell us which application you are trying to checkpoint.

**Comment by superbu1234** [comment]
gnome-calculator&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "checkpoint-restore/criu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上8:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [checkpoint-restore/criu] --ext-unix-sk (Issue #1766)





 
Please share the complete log file when running CRIU with -v4 and tell us which application you are trying to checkpoint.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adrianreber** [comment]
You cannot checkpoint graphical applications which are accessing the GPU.

**Comment by superbu1234** [comment]
Does criu not support it? Or how to achieve it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "checkpoint-restore/criu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [checkpoint-restore/criu] --ext-unix-sk (Issue #1766)





 
You cannot checkpoint graphical applications which are accessing the GPU.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by adrianreber** [comment]
It is complicated, but the short answer is that it is not supported to checkpoint applications accessing the GPU.

**Comment by rst0git** [comment]
> Does criu not support it? Or how to achieve it?

You can use VNC: https://criu.org/VNC
