### ISSUE TITLE
Dump fails with the error `All tasks in criu's cgroups. Nothing to dump.`

### ISSUE THREAD

**Issue by PavloMykhailyshyn** [checkpoint-restore/criu#1775]
I ran into a problem during process dump.
I am starting a process in a separate session using setsid
I use criu-ns to perform dump and restore.
The dump did not work as expected after several times of successful dumping and restoring the same process.
The dump fails with such log `All tasks in criu's cgroups. Nothing to dump`.
Everything works well before this failed dump.
What could be the reason for such a problem?

**Comment by PavloMykhailyshyn** [comment]
@Snorch and @rst0git

**Comment by PavloMykhailyshyn** [comment]
here are the logs for this particular failed dump
[logs.txt](https://github.com/checkpoint-restore/criu/files/8251858/logs.txt)

**Comment by PavloMykhailyshyn** [comment]
and I do not understand this comment
	/*
	 * Check whether root task lives in its own set as compared
	 * to criu. If yes, we should not dump anything. Note that
	 * list_is_singular() is slightly wrong here: if the criu cgset has
	 * empty cgroups, those will not be restored on the target host, since
	 * we're not dumping anything here.
	 */
Is everything ok in regards to this?

**Comment by avagin** [comment]
"All tasks in criu's cgroups. Nothing to dump." is not an error message... I don't see any errors in the log, so we need to find a code path where we forgot to print an error.

**Comment by avagin** [comment]
```
(00.281640) Writing image inventory (version 1)
(00.281729) Running post-dump scripts
(00.281732) Unfreezing tasks into 2
(00.281735) 	Unseizing 352481 into 2
```

"Running post-dump scripts" means that we dumped processes successfully.

**Comment by PavloMykhailyshyn** [comment]
@avagin it didn't crash, but exited with a status code of 1 (probably, but the point is that it's not 0)

**Comment by avagin** [comment]
@PavloMykhailyshyn could you add more debug in the criu code and find out why it exits with a non-zero code?

**Comment by PavloMykhailyshyn** [comment]
What do you mean?
Add more logs and try to debug?

**Comment by avagin** [comment]
I mean something like this:
https://github.com/avagin/criu/commit/749ce82f16cf2be9ec3e07e8030a5c978d5f00e0

**Comment by PavloMykhailyshyn** [comment]
Thanks
Will try

pr_err - does this write info to the file with the provided argument —log-file?

**Comment by avagin** [comment]
You will see this messages in the log file.

**Comment by rst0git** [comment]
> I use criu-ns to perform dump and restore.

> it didn't crash, but exited with a status code of 1

`criu` or `criu-ns` exit with status code of 1?

**Comment by PavloMykhailyshyn** [comment]
criu-ns
maybe it is a problem there

**Comment by PavloMykhailyshyn** [comment]
def _wait_for_process_status(criu_pid):
    """
    Wait for CRIU to exit and report the status back.
    """
    while True:
        try:
            (pid, status) = os.wait()
            if pid == criu_pid:
                return os.waitstatus_to_exitcode(status) <—- here
        except OSError:
            return -251

**Comment by avagin** [comment]
Could you collect perf trace and attach the perf.log to this issue:
perf trace --event signal:* --syscall -fo perf.log ./criu-ns [arguments...]

**Comment by PavloMykhailyshyn** [comment]
I found a workaround for such case
I just used an action script to determine if the dump was successful, no matter what exit code it returns.
also, restore was successful for such a dump
I don't know why the correct exit code is not being returned
and I don't have enough time to troubleshoot criu :(
Thanks

**Comment by PavloMykhailyshyn** [comment]
also, it is not so easy to reproduce
I have a complex system that dumps and restores multiple processes an infinite number of times every 2 minutes until they terminate on their own.

**Comment by PavloMykhailyshyn** [comment]
I caught it again
criu-ns returns 1 or 247, but dump successful (post-dump script succeeds)
the logs are exactly the same as I provided in this issue

**Comment by avagin** [comment]
We don't see "Dumping finished successfully" in logs, so I am not sure that criu exits with the zero code:
https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/cr-dump.c#L1789

**Comment by PavloMykhailyshyn** [comment]
I understood this
what could be the reason?
Is it correct to ignore and rely to the finished 'post-dump' action script?

**Comment by PavloMykhailyshyn** [comment]
`and then you will see all fatal signals in the kernel log.`
what should I look for?

**Comment by PavloMykhailyshyn** [comment]
just see nothing for criu
maybe I'm looking elsewhere
where should I check such logs?

**Comment by rst0git** [comment]
> (00.281732) Unfreezing tasks into 2
(00.281735)     Unseizing 352481 into 2

`Unfreezing tasks into 2` means that criu executes the following code in `compel_resume_task()` with `pid=352481`
```C
if (st == COMPEL_TASK_DEAD) {
	kill(pid, SIGKILL);
	return 0;
}
```

Then it runs the following in `pstree_switch_state()`:
```C
if (st == TASK_DEAD)
	pstree_wait(root_item);
```

It looks like something fails either in `pstree_wait()` or in:
```C
timing_stop(TIME_FROZEN);
free_pstree(root_item);
seccomp_free_entries();
free_file_locks();
free_link_remaps();
free_aufs_branches();
free_userns_maps();

close_service_fd(CR_PROC_FD_OFF);
close_image_dir();
```

> I have a complex system that dumps and restores multiple processes an infinite number of times every 2 minutes until they terminate on their own.

Is it possible that something kills the criu process before it exits?

**Comment by PavloMykhailyshyn** [comment]
> Is it possible that something kills the criu process before it exits?
I have such functionality but it only kills criu if the process runs for more than 10 minutes (I mean criu process)
so it is not possible that something from my program kills it (every dump take less than 13 sec)

**Comment by avagin** [comment]
> where should I check such logs?

$ dmesg

**Comment by PavloMykhailyshyn** [comment]
there is nothing

**Comment by avagin** [comment]
Another way is how you can get more info:

You need to do  these preparation steps:
$ echo 'comm == "criu"' > /sys/kernel/debug/tracing/events/signal/signal_generate/filter 
$ echo 1 > /sys/kernel/debug/tracing/events/signal/signal_generate/enable
$ echo 1 > /sys/kernel/debug/tracing/tracing_on

and then when you trigger the issue, you need to run this command:
$ cat /sys/kernel/debug/tracing/trace_pipe

**Comment by PavloMykhailyshyn** [comment]
I see messages like this
```
              sh-592553  [000] dN.. 31314.187239: signal_generate: sig=17 errno=0 code=1 comm=criu pid=592455 grp=1 res=0
              sh-592566  [002] dN.. 31314.220382: signal_generate: sig=17 errno=0 code=1 comm=criu pid=592461 grp=1 res=0
            criu-470274  [002] dN.. 25649.886278: signal_generate: sig=9 errno=0 code=128 comm=criu pid=471802 grp=1 res=0
            criu-471739  [001] d... 25649.888382: signal_generate: sig=17 errno=0 code=2 comm=criu pid=471739 grp=1 res=1
            criu-471760  [002] d... 25649.926709: signal_generate: sig=17 errno=0 code=2 comm=criu pid=471760 grp=1 res=1
            criu-471760  [002] d... 25649.926717: signal_generate: sig=17 errno=0 code=2 comm=criu pid=469996 grp=1 res=1
            criu-469996  [002] dN.. 25649.928018: signal_generate: sig=9 errno=0 code=128 comm=criu pid=471760 grp=1 res=0
```

**Comment by avagin** [comment]
I know what is going on here.

> The dump did not work as expected after several times of successful dumping and restoring the same process.

1. "criu-ns restore" creates a new pid namespace and executes "criu restore" there. The criu process (A) is the init process in the new pid namespace. It restores target processes and then it collects zombies and waits for the root target process. When the target process exits, criu exits too. But as it is the init process, it kills the pid namespace on exit.
2. "criu-ns dump" enters the target process pid namespace and executes criu dump there. The criu process (b) dumps the target processes and kills them. 

So we have a race condition. If the criu process A exits before the criu process (B), it kills  the pid namespace and so it kills all processes in it (including the criu process (B)).

**Comment by avagin** [comment]
hmm. criu waits for all processes in its pid namespace:
https://github.com/checkpoint-restore/criu/blob/afbfacaadb15dd1f01d4590d04ac59d4db1b1b5b/criu/cr-restore.c#L2142

**Comment by avagin** [comment]
I was wrong in the previous comment. criu dump (the process B) isn't a child of the criu process (A), so reap_zombies doesn't wait for it.

**Comment by PavloMykhailyshyn** [comment]
Soo
Does the problem exist?
Is this something that needs to be fixed on my side, or is it criu's fault?

**Comment by avagin** [comment]
Yes, the problem exists. CRIU is on your side, so you you need to fix it ;).

**Comment by avagin** [comment]
@PavloMykhailyshyn could you try out https://github.com/avagin/criu/commit/7ef19412acd5c76de3662f6239432cca7d23c5da. I think it has to fix the issue.

**Comment by PavloMykhailyshyn** [comment]
> Yes, the problem exists. CRIU is on your side, so you you need to fix it ;).

Nice try :)

> @PavloMykhailyshyn could you try out https://github.com/avagin/criu/commit/7ef19412acd5c76de3662f6239432cca7d23c5da. I think it has to fix the issue.

Started my testing

**Comment by PavloMykhailyshyn** [comment]
I have done almost ~10 thousand dumps and restores and I did not catch errors when dumping.
Basically, all dumps ended with the correct exit code.

Probably the fix is working correctly

**Comment by PavloMykhailyshyn** [comment]
During this testing, I also noticed some errors while restoring (not that many, less than 10)

(00.015843)   6399: Error (soccr/soccr.c:529): Can't connect inet socket back: Cannot assign requested address
(00.015856)   6399: Error (criu/files.c:1200): Unable to open fd=4 id=0x18

(00.062892) pie: 537569: Error (criu/pie/restorer.c:1518): Can't restore 0x7fcb5c033000 mapping with 0xfffffffffffffff4
(00.062898) pie: 537569: Error (criu/pie/restorer.c:1925): Restorer fail 537569

the case is the same
The restore did not work as expected after several times of successful dumping and restoring the same process.
but these errors are really rare

**Comment by PavloMykhailyshyn** [comment]
Also, it is impossible to check by exit code criu restore completion with the --restore-detached argument using criu-ns
What would you suggest in this case? To be able to check if the restore was successful I use the `post-resume` script.

You said

> > Is it correct to ignore exit code and rely on the finished 'post-dump' action script?

> No, it isn't correct... in long term

what about restore?

**Comment by avagin** [comment]
> what about restore?

On restore, It should work.

**Comment by PavloMykhailyshyn** [comment]
probably this issue can be resolved
