### ISSUE TITLE
Does the CRIU have an API or CLI that guarantee user-requested QoS (Quality of Service)?

### ISSUE THREAD

**Issue by YJ243** [checkpoint-restore/criu#1782]
hi,
I'm looking for if CRIU has an API or CLI that guarantees the required I/O throughput (ex. 100MBps) requested by the user when checkpointing the processes.

@adrianreber  Please let me know...Thank you.

**Comment by adrianreber** [comment]
How does a user request the required I/O throughput? Not sure what you exactly mean.

**Comment by YJ243** [comment]
First, I considered the following situation.
For example, in a distributed environment if I send a request to 100Mbs and it doesn't respond as expected, then the user can experience inconvenience.
The checkpointing job is to write image files to the storage like SSD. Therefore, if a user wants to receive a response 100mbps or 300mbps, it seems that QoS can be guaranteed by further utilizing more channels of SSD when writing to it.

The reason why I asked is that I'm currently studying docker checkpoints using criu for ZNS SSD (Zoned namespace SSD), which is the next-generation storage.

Thank you.

**Comment by adrianreber** [comment]
As far as I know nothing like this exists.

**Comment by YJ243** [comment]
Okay.. then CRIU does not show the throughput such as bandwidth and IOPS when checkpointing container jobs, right?

**Comment by adrianreber** [comment]
> Okay.. then CRIU does not show the throughput such as bandwidth and IOPS when checkpointing container jobs, right?

No. We only provide timing related statistics. See `podman container checkpoint --print-stats`.

Please close if there are no further questions.
