### ISSUE TITLE
--inherit-fd option change the /proc/pid/fd link permission from lrwx------ to l-wx------

### ISSUE THREAD

**Issue by dora-zhang** [checkpoint-restore/criu#1794]
**Description**

I used `--inherit-fd` to redirect both input and output file of my testing program, and notice the link permission changed from **lrwx------** to **l-wx------** after redirect, this makes

**Steps to reproduce the issue:**
1. I have a testing script in c, open two files. 
```
-rw-r--r-- 1 root root 6 Mar 28 17:39 /tmp/cp_auto.in
-rw-r--r-- 1 root root 0 Mar 28 17:22 /tmp/cp_auto.out
```
The program starts an infinite loop to read from `/tmp/cp_auto.in` and write the input to  `/tmp/cp_auto.out`
2. Checkpoint with `criu dump -D /image/path -t pid --shell-job`
3. Terminate the process then restore with `criu restore -D /image/path --shell-job --inherit-fd 'fd[5]:tmp/cp_auto.out' 5> /tmp/cp_auto.out.clone01 --inherit-fd 'fd[4]:tmp/cp_auto.in' 4> /tmp/cp_auto.in.clone01`
4. Program restored but not functioned.

**Describe the results you received:**
Before checkpointing
```
ll /proc/pid/fd
lr-x------ 1 root root 64 Mar 28 17:38 3 -> /tmp/cp_auto_tmp
lrwx------ 1 root root 64 Mar 28 17:39 4 -> /tmp/cp_auto.in
lrwx------ 1 root root 64 Mar 28 17:39 5 -> /tmp/cp_auto.out
```

After restoration,
```
lr-x------ 1 root root 64 Mar 28 17:39 3 -> /tmp/cp_auto_tmp
l-wx------ 1 root root 64 Mar 28 17:40 4 -> /tmp/cp_auto.in.clone01
l-wx------ 1 root root 64 Mar 28 17:40 5 -> /tmp/cp_auto.out.clone01
```
When the program broke, and input to `/tmp/cp_auto.in.clone01` is not able to transfer to `/tmp/cp_auto.out.clone01` because of the missing of read permission.

The expected result is link permission should be **lrwx------**, not **l-wx------**

CentOS Stream 8

The criu I use 
Version: 3.16.1
GitID: v3.16.1-255-g68477be19

**Comment by avagin** [comment]
@Snorch could you take a look at this issue?

**Comment by avagin** [comment]
I think you provide wrong fds on restore:
```
$ sleep 1000 5> /tmp/cp_auto.out.clone01 4> /tmp/cp_auto.in.clone01 &
[1] 352061
total 0
lrwx------ 1 avagin primarygroup 64 Mar 30 09:17 0 -> /dev/pts/4
lrwx------ 1 avagin primarygroup 64 Mar 30 09:17 1 -> /dev/pts/4
lrwx------ 1 avagin primarygroup 64 Mar 30 09:17 2 -> /dev/pts/4
l-wx------ 1 avagin primarygroup 64 Mar 30 09:17 4 -> /tmp/cp_auto.in.clone01
l-wx------ 1 avagin primarygroup 64 Mar 30 09:17 5 -> /tmp/cp_auto.out.clone01
$ sleep 1000 5<> /tmp/cp_auto.out.clone01 4<> /tmp/cp_auto.in.clone01 &
[1] 352170
total 0
lrwx------ 1 avagin primarygroup 64 Mar 30 09:18 0 -> /dev/pts/4
lrwx------ 1 avagin primarygroup 64 Mar 30 09:18 1 -> /dev/pts/4
lrwx------ 1 avagin primarygroup 64 Mar 30 09:18 2 -> /dev/pts/4
lrwx------ 1 avagin primarygroup 64 Mar 30 09:18 4 -> /tmp/cp_auto.in.clone01
lrwx------ 1 avagin primarygroup 64 Mar 30 09:18 5 -> /tmp/cp_auto.out.clone01
```

**Comment by dora-zhang** [comment]
@avagin Thanks! This is helpful. When restore with --inherit-fd 'fd[4]:tmp/cp_auto.in' 4<> /tmp/cp_auto.in.clone01 the link is restored to `lrwx------`. In this example, do you know if it is possible to restore to read and **append** mode?

**Comment by avagin** [comment]
I am not sure that it is possible from bash, but you can write a python wrapper.
