### ISSUE TITLE
Is it possible to allow restoring a different pid from dumping stage to slove the pid mismatch problem?

### ISSUE THREAD

**Issue by anatasluo** [checkpoint-restore/criu#1807]
In most cases, mismatch problems can be solved by isolated pid namespace.

But sometimes, we don't want to manage these pid namespaces. And also, for most applications like nginx, we don't care about its pid.

So I wonder if it is a good idea to add a config option for criu to choose a different option when the pid mismatch problem happens.

**Comment by avagin** [comment]
nginx cares about PID-s of its workers, cgi scripts and etc.

**Comment by anatasluo** [comment]
> nginx cares about PID-s of its workers, cgi scripts and etc.

I think about it twice, pid may be used as the value of a variable in the program. So it is hard to find these places and make corrections. Thanks avagin, I will close this question.
