### ISSUE TITLE
help: the breakpoint problem in arm64 platform

### ISSUE THREAD

**Issue by time-river** [checkpoint-restore/criu#1811]
I try to implement the breakpoint in arm64 platform. [Here](https://github.com/time-river/criu/commit/be7a2438675d4ee209a029db56c841b91b959d35) is my code. But I met one problem which makes the feature abnormal:

In x86_64 platform, it seems that the Debug Exception event happens after the `rt_sigreturn` syscall has been executed, the change event that the content stored in the breakpoint address triggers the Debug Exception.

However, I tried to do the same procedure in arm64 platform, nothing happened, and I try to use execution breakpoint for `rt_sigreturn` syscall (code is [here](https://github.com/time-river/criu/commit/460633515ce8fa8dd7d2151460d82e75b882e1e9)), the program will triger segment fault after the restoration, the reason seems that the Debug Exception happens before the `svc` instruction fetching.

How should I implement this feature? @avagin

**Comment by avagin** [comment]
I am not sure that I understand the question. You can look at the gdb code how it sets breakpoints.

**Comment by time-river** [comment]
> I am not sure that I understand the question. You can look at the gdb code how it sets breakpoints.

I find the problem. The breakpoint event triggers when the instruction is fetch, and the instruction don't execute yet. Here is the phenomenon:

```
# crit show core-51754.img
                    "sp": "0xffffc21d8af0",
                    "pc": "0xffff8c88ea30",

# the good restoration (use `ptrace(SYSCALL)`)
(00.011463) 51754 (native) is going to execute the syscall 139, required is 139
(00.011464) >>> **sp: 0x28080 pc: ffff8c9a08e4**
(00.011474) 51754 was stopped
(00.011483) >>> **get regs ip ffff8c88ea30 stack ffffc21d8af0**
(00.011485) >>> parasite regs ip 11d20 stack (nil)
(00.011494) 51754 was trapped
(00.011496) 51754 (native) is going to execute the syscall 215, required is 215
(00.011498) >>> sp: 0xffffc21d8af0 pc: 15894

# the bad restoration (use hw breakpoint)
(00.054686) 51754 (native) is going to execute the syscall 139, required is 139
(00.054688) >>> **sp: 0x28080 pc: ffff8c9a08e0**
(00.054696) 51754 was stopped
(00.054703) >> unset hbrkt
(00.054713) >>> **get regs ip ffff8c9a08e0 stack 28080**
(00.054715) >>> parasite regs ip 11d20 stack (nil)
(00.054724) 51754 was trapped
(00.054726) 51754 (native) is going to execute the syscall 215, required is 215
(00.054728) >>> sp: 0x28080 pc: 15894
(00.054739) 51754 was stopped
```

I fetch the registers before munmap parasite blob,  find the sp and pc don't restore to the specific status before munmap event.

I try to use single step debug tip to solve the problem, it looks like good. :-)
