### ISSUE TITLE
change the port of the local service when restoring

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1812]
The dumpee use port:6000, and I want to change the local service port to 10000 when restoring.
I don't know if the parameters already support this feature, or how should I change the code.

**Comment by avagin** [comment]
You can modify the port in image files. You can use crit to decode/encode images:
http://manpages.ubuntu.com/manpages/bionic/man1/crit.1.html

**Comment by mrc1119** [comment]
I have modified the file (criu/sk-inet.c) to parameterize it. Thanks!
