### ISSUE TITLE
How do I display my modified log message visible when docker container checkpointing?

### ISSUE THREAD

**Issue by YJ243** [checkpoint-restore/criu#1855]
Hi, I'm currently researching criu for my study. 
And I'm checking my log (modified criu code) to confirm the image file writing path to the ssd from the main function after issuing the cmd ***criu dump***.
And I checked the posix write(fd, buf, size) in **write_all** function (criu/util.c)

My question is this.
If I issue a command with **_criu dump_**, I can see the logs clearly on the shell. But if I issue a command with **_docker checkpoint create_**, I can't see my logs. What is the reason? Isn't the cmd ***docker checkpoint create*** going to cmd ***criu dump*** after all?

**Steps to reproduce the issue.**

> criu dump -t 151797 -D cp -j -v4
![image](https://user-images.githubusercontent.com/60027712/164708475-3acaeba9-4986-4f3a-88a1-0989d1dc84a3.png)
![image](https://user-images.githubusercontent.com/60027712/164708162-3a6a702a-8f9a-42d3-9617-02dfdec12594.png)
I can see my logs well.

> docker checkpoint create --checkpoint-dir /home/yejin/fiotest 8dee RedisCheck
![image](https://user-images.githubusercontent.com/60027712/164708382-d7d4459b-5a02-4a22-99f4-3bb56c2c8b55.png)
I can't see my logs..

Kindly let me know why the logs were not displayed, please... Thnks
@adrianreber

**Comment by rst0git** [comment]
> If I issue a command with criu dump, I can see the logs clearly on the shell. But if I issue a command with docker checkpoint create, I can't see my logs. What is the reason?

In addition to the [command-line interface](https://criu.org/CLI), CRIU provides an RPC API. `docker checkpoint create` would invoke [containerd](https://github.com/containerd/containerd), which then invokes [runc](https://github.com/opencontainers/runc). runc interacts with CRIU via the RPC API and one of the parameters it provides is a [log file](https://criu.org/Logging). Therefore, all CRIU logs are stored in that log file and printed out to stdout.

**Comment by YJ243** [comment]
Thanks
