### ISSUE TITLE
Is pre-dump supported on arm64?

### ISSUE THREAD

**Issue by carlhoerberg** [checkpoint-restore/criu#1859]
Quick question, is pre-dump supported on arm64? 

```
$ sudo criu check --feature mem_dirty_track
Warn  (criu/cr-check.c:813): Dirty tracking is OFF. Memory snapshot will not work.
$ uname -a
Linux ip-172-31-92-117.ec2.internal 5.17.3-302.fc36.aarch64 #1 SMP Sun Apr 17 13:03:19 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ criu --version
Version: 3.16.1
$ grep CONFIG_PROC_PAGE_MONITOR /boot/config-5.17.4-200.fc35.aarch64
CONFIG_PROC_PAGE_MONITOR=y
```

**Comment by adrianreber** [comment]
> Quick question, is pre-dump supported on arm64?

No. Arm is missing `CONFIG_MEM_SOFT_DIRTY=y`. Nobody implemented the kernel support for it.

**Comment by carlhoerberg** [comment]
ok! thank you for the quick answer!

**Comment by ShivanshVij** [comment]
We have actually created a preliminary patch to add dirty memory tracking to the linux kernel: https://github.com/loopholelabs/linux/pull/3

It passes the entire ZDTM test suite with the `--pre` flag set (specifically I'm testing with `sudo test/zdtm.py run --page-server --remote-lazy-pages --keep-going --pre 3 -a` on CRIU v3.19)

**Comment by adrianreber** [comment]
@ShivanshVij Good to know, thanks. Are you trying to get this upstream?

**Comment by ShivanshVij** [comment]
Yes! I was going to try and submit a patch tomorrow, this is based on a [previous attempt](https://patchwork.kernel.org/project/linux-arm-kernel/patch/1512029649-61312-1-git-send-email-bin.lu@arm.com/) about 8 years ago but actually works on the newer kernels and (theoretically) fixes the race condition that caused the original patch to get abandoned.

**Comment by ShivanshVij** [comment]
Submitted: https://patchwork.kernel.org/project/linux-arm-kernel/patch/MW4PR12MB687563EFB56373E8D55DDEABB92B2@MW4PR12MB6875.namprd12.prod.outlook.com/
