### ISSUE TITLE
Python is confused by package`crit`

### ISSUE THREAD

**Issue by dilyanpalauzov** [checkpoint-restore/criu#1878]
I have installed libcriu-3.17 from source.  Apparently it does install the `crit` python command and sets as version 0.0.1.  After the 
installation I run 
```
$ pip list --outdated
Package  Version Latest Type
-------- ------- ------ -----
crit     0.0.1   0.1    sdist
```
and crit 0.1 means https://pypi.org/project/crit/ .  This is a collision.

Please do something, so that two different projects do not use the same name from the perspective of `pip` and [PyPi](https://pypi.org/project/crit).

**Comment by avagin** [comment]
https://github.com/jessielaf/crit

This project looks abandoned.

**Comment by rst0git** [comment]
https://peps.python.org/pep-0541/#removal-of-an-abandoned-project

An abandoned project can be transferred to a new owner for purposes of reusing the name when ALL of the following are met:
- the project has been determined abandoned by the rules described above;
- the candidate is able to demonstrate their own failed attempts to contact the existing owner;
- the candidate is able to demonstrate that the project suggested to reuse the name already exists and meets notability requirements;
- the candidate is able to demonstrate why a fork under a different name is not an acceptable workaround;
- download statistics on the Package Index for the existing package indicate project is not being used; and
- the maintainers of the Package Index don’t have any additional reservations.

**Comment by avagin** [comment]
@rst0git can we fix crit to report the criu version? I think this will fix the issue.
