### ISSUE TITLE
Restore a checkpoint using RPC

### ISSUE THREAD

**Issue by camilo1729** [checkpoint-restore/criu#1881]
Hello,

How can I restore a checkpoint using RPC? I was able to dump the process using RPC but when I tried to restore it I got the following message:

```bash
Restore fail: Error (criu/tty.c:1014): tty: Don't have tty to inherit session from, aborting
```

Am I missing some additional option?  I used the `restore-loop.py` example code and a modifed version of `test-c.c` where I've just changed:

```c
        req.type = CRIU_REQ_TYPE__RESTORE;
```

I got the same result with both client programs. My version of criu is: 3.15.

Thank you in advance.

**Comment by adrianreber** [comment]
We have multiple users of the RPC interface. We have the go-bindings and the rust-bindings. The container runtime `runc` is using the go-bindings to interact with the RPC interface. Maybe have a look there and see how these projects are using it.

Let us know if you need more help.

**Comment by rst0git** [comment]
@camilo1729 you can use the tests for RPC as an example:

https://github.com/checkpoint-restore/criu/tree/criu-dev/test/others/rpc

**Comment by rst0git** [comment]
> tty: Don't have tty to inherit session from, aborting

This error also appears in CI: https://github.com/checkpoint-restore/criu/blob/4f62ec02ea4de62eef23638e178e6b6f425e3897/scripts/ci/run-ci-tests.sh#L260

**Comment by camilo1729** [comment]
I had a deeper look and the errors seems to be related to the fact that the criu daemon does not run from a terminal (which seems normal), I see this in the logs:
```bash
tty: Standard stream is not a terminal, may fail later 
```
I have a look at rust-bindings and it seems to use the swrk mode. So, I wrote a python script to perform a test using that mode and I was able to restore my process. I will continue with my tests to evaluate if this mode is a good option in my case.

**Comment by adrianreber** [comment]
service mode is kind of deprecated and swrk is the preferred way to work with criu.

**Comment by adrianreber** [comment]
Please close this ticket if your question has been answered.

**Comment by camilo1729** [comment]
Thank you for your answers.
