### ISSUE TITLE
rename process name

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1883]
I want to rename process name like this:
when checkout:
process name is [nginx]
and when restore:
rename the process to [nginx2]

**Comment by adrianreber** [comment]
Using `crit decode` and `crit encode` you should be able to change the core-*.img file and change the process name. Never tried it, but it sounds possible,

**Comment by mrc1119** [comment]
I want to change the process name by passing the parameter. Which file is the key code in?

**Comment by avagin** [comment]
@mrc1119 first, you need to explain why the crit way doesn't work for you.

**Comment by mrc1119** [comment]
Crit is not efficient when using CRIU for automated restore.
Maybe I'm not familiar with the usage of crit...

**Comment by mrc1119** [comment]
@avagin @adrianreber  
I used crit to process each core file, but it didn't work. 

1.crit-python2 decode --pretty -i core-1.img > 1.json
2.sed -i "s/nginx/nginx2/g" 1.json
3.crit-python2 encode -i 1.json -o core-1.img

**Comment by mrc1119** [comment]
> 
@Snorch 
Oh,yeah. I find the cmdline in pages image.  Since the cmdline has port information and I changed the listening port when I restored, I want the restored cmdline to be the same as the actual port.
Would you tell me how you changed the ps output?

**Comment by Snorch** [comment]
> > 
> 
> @Snorch Oh,yeah. I find the cmdline in pages image. Since the cmdline has port information and I changed the listening port when I restored, I want the restored cmdline to be the same as the actual port. Would you tell me how you changed the ps output?

I just changed "00" to "22" in vim in the image and it happened to be that the length of binary representation of "00" and "22" is the same, so I didn't broke the memory layout and after restore it just worked with updated name in /proc/{pid}/cmdline. If you are accurate enough it should probably be possible to print a new name just above the old one adding proper escape in the end.

**Comment by mrc1119** [comment]
@Snorch Oh I see. If pages-x.img has a lot of data, it is time-consuming to find cmdline. Do you know the location of source code which about restoring cmdline  ?

**Comment by Snorch** [comment]
> @Snorch Oh I see. If pages-x.img has a lot of data, it is time-consuming to find cmdline. Do you know the location of source code which about restoring cmdline ?

It's just general memory restore code (likely around prepare_mappings()), there is no special piece of code for cmdline AFAICS.

**Comment by mrc1119** [comment]
I find the piece of code for cmdline, location: criu/pie/restorer.c :
**sys_prctl(PR_SET_MM, PR_SET_MM_MAP, (long)&prctl_map, sizeof(prctl_map), 0);**
change cmdline from "args->mm.mm_arg_start" to "args->mm.mm_arg_end",
I kept the length of the string the same, so it doesn't have any problems
Thank you for your help! @avagin @adrianreber @Snorch
