### ISSUE TITLE
Restoring inside a container causes a segmentation fault

### ISSUE THREAD

**Issue by spullara** [checkpoint-restore/criu#1885]
**Description**

Inside a running Docker container on an M1 Mac I am able to checkpoint a process. If I attempt to restore that process the criu command segfaults.

**Steps to reproduce the issue:**
Start a docker container with some additional flags:
docker run -it --tmpfs /run --privileged ...
Run the example from the video
dump it
Try to restore it

**Describe the results you received:**
# criu dump -t 10 -D checkpoint/ -j
# criu restore -D checkpoint/ -j
Error (criu/cr-restore.c:1480): 560 killed by signal 11: Segmentation fault
Error (criu/cr-restore.c:2447): Restoring FAILED.

**Describe the results you expected:**
Restoration of the process

<details><summary>Output of `criu --version`:</summary>
<p>

```
 criu --version
Version: 3.16.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Error (criu/util.c:635): exited, status=1
Error (criu/util.c:635): exited, status=1
Warn  (criu/cr-check.c:855): Dirty tracking is OFF. Memory snapshot will not work.
Warn  (criu/cr-check.c:1284): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1250): UFFD is not supported
Error (criu/cr-check.c:1250): UFFD is not supported
Error (criu/cr-check.c:1325): IFLA_NEW_IFINDEX isn't supported
Error (criu/cr-check.c:1038): failed to mount autofs: No such device
Warn  (criu/cr-check.c:1204): CRIU built without CONFIG_COMPAT - can't C/R compatible tasks
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
Which distribution and kernel are you using?

**Comment by spullara** [comment]
I was using ubuntu:latest. I am on M1 though so it was the ARM version.

**Comment by adrianreber** [comment]
Is ubuntu:latest 22.04 or 20.04?

**Comment by spullara** [comment]
22.04

**Comment by adrianreber** [comment]
22.04 uses glibc with restartable sequences and that requires at least Linux 5.13 and criu 3.17.

**Comment by adrianreber** [comment]
You can temporarily disable restartable sequences with 

`export GLIBC_TUNABLES=glibc.pthread.rseq=0`

**Comment by spullara** [comment]
Using that I don't get a segfault but it seems to hang and I can't interrupt it.

```
root@e81efb206f02:/# criu dump -t 354 -D checkpoint/ -j
Error (criu/util.c:635): exited, status=1
Error (criu/util.c:635): exited, status=1
[1]+  Killed                  nohup ./a.out > log.txt
root@e81efb206f02:/# criu restore -D checkpoint/ -j

^C
^Z
```

**Comment by avagin** [comment]
What process do you try to C/R? Could you increase the verbosity level and attach criu logs?
$ criu dump -t PID -D checkpoint/ -vvv -o dump.log -j
$ criu restore  -D checkpoint/ -vvv -o restore.log -j

**Comment by spullara** [comment]
Here is the code:

```
#include <stdio.h>
#include <unistd.h>
int main()
{
    long long i = 0;
    while(1) {
        printf("%lld\n", ++i);
        sleep(1);
    }
    return 0;
}
```

So when I restore and it "hangs" it is actually running you just can't interrupt anymore so it is working for me. Thanks for the help.

**Comment by adrianreber** [comment]
You could also use `-d|--restore-detached`.

Good that it works now. Please close the ticket if you have no further questions.
