### ISSUE TITLE
3.17.1 tracker

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1886]
There are a couple of problems in 3.17 which probably means we need a 3.17.1 release:

 * #1876 
 * #1884 
 * https://github.com/opencontainers/runc/pull/3442 mount-v2 errors

**Comment by Snorch** [comment]
I believe that it's not an issue of mount-v2 but sort of bad external mounts configuration. If criu dumps two mounts having exact the same shared group on dump, and on restore these mounts appear to have different superblocks due to bad external mount options, criu can't do anything but fail.

**Comment by adrianreber** [comment]
Concerning https://github.com/opencontainers/runc/pull/3442: I am a bit afraid that we might break many existing runc/CRIU installation if CRIU is upgraded to 3.17. Maybe we need to think about to default to `--mntns-compat-mode` at least for RPC mode for the runc/crun use case. I have seen the mount-v2 errors as described in https://github.com/opencontainers/runc/pull/3442 also in Kubernetes tests and I really do not want to break container checkpoint/restore on multiple systems.

runc often seems to be tied to the container stack and might not be updated regularly.  CRIU might come as a normal OS update and would then break the container checkpoint/restore.

@checkpoint-restore/maintainers any comments on defaulting to  `--mntns-compat-mode` until 3.18 (at least for the RPC use case)?

**Comment by Snorch** [comment]
@adrianreber If we have no other choice yes we can switch to compat by defaul. Though leaving mount-v2 by default will help us track all these tricky cases about which I forgot (didn't though).

Please try this w/a https://github.com/checkpoint-restore/criu/pull/1898 maybe it would help to runc.

**Comment by adrianreber** [comment]
Having a fix sounds much better than disabling. I will test your fix tomorrow. Thanks.

**Comment by adrianreber** [comment]
We also would want to have #1918 in 3.17.1 once it has been merged.

**Comment by rst0git** [comment]
@adrianreber I think we can close this issue?
