### ISSUE TITLE
Segmentation fault when restore

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1892]
**Description**
criu version: 3.15
              OS:  CentOS Linux release 7.1.1503 (Core) 
         kernel:  Linux  5.12.4-1.el7.elrepo.x86_64 #1 SMP Fri May 14 06:36:46 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce the issue:**
1.dump:    ./criu dump --ghost-limit=500M -D /export/sine/dumpdata -j -R -t $pid --tcp-close --skip-in-flight --external mnt[/etc/hosts]:hostsmount --external mnt[/etc/hostname]:hostnamemount --external mnt[/etc/resolv.conf]:reslovemount --external mnt[/var/log/mydb]:mydbmount -v4 -o /export/sine/sinedump.log

2.restore:  ./criu restore --ghost-limit=500M -D /export/sine/dumpdata -j -d --tcp-close --root /export/Data/docker/vfs/dir/${containerid}  --external mnt[hostsmount]:/etc/hosts --external mnt[hostnamemount]:/etc/hostname --external mnt[reslovemount]:/etc/resolv.conf --external mnt[mydbmount]:/var/log/mydb -v4 -o /export/sine/restore.log

3.There is an error
(03.820187) pie: 1: vdso: image [vdso] 0x7ffe5c5e5000-0x7ffe5c5e7000 [vvar] 0xffffffffffffffff-0xffffffffffffffff
(46.650041) Error (criu/cr-restore.c:1567): 547 killed by signal 11: Segmentation fault
(46.650083) Warn  (criu/cr-restore.c:2480): Unable to wait 547: No child processes
(46.650302) mnt: Switching to new ns to clean ghosts
(46.650563) Error (criu/cr-restore.c:2494): Restoring FAILED.

**Describe the results you expected:**
I have been successful in restoring on other kernel versions, such as 3.10 and 4.18.

<details><summary>Output of `criu check --all`:</summary>
<p>
Error (criu/util.c:631): exited, status=3
Warn  (criu/kerndat.c:877): Can't keep kdat cache on non-tempfs
Warn  (criu/cr-check.c:850): Dirty tracking is OFF. Memory snapshot will not work.
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

</p>
</details>

I hope I can get your help.

**Comment by mrc1119** [comment]
I drew inspiration from other issue, and the problem was fixed when I updated to version 3.17.  Thanks

**Comment by mrc1119** [comment]
[https://github.com/checkpoint-restore/criu/issues/1894](url)

**Comment by rafaelgieschke** [comment]
For other people with the same problem (using older CRIU versions): this was caused by "%zu" in https://github.com/checkpoint-restore/criu/blob/d46f40f4ff0c724e0b9f0f8a2e8c043806897e94/criu/pie/parasite-vdso.c#L162 and was fixed in https://github.com/checkpoint-restore/criu/commit/c39ed518f099dafa98396ab9d66821afcce6b09a and https://github.com/checkpoint-restore/criu/commit/b28eb7b2d18184cf8ef1a8f95719f47499967c8c for CRIU >= 3.16. If you want to continue using CRIU 3.15, you can `sed -i 's/%zu/%zd/' criu/pie/parasite-vdso.c`.
