### ISSUE TITLE
Can't mount controller net_cls: Device or resource busy

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1897]
**Description**
criu version: 3.17

**1) The information about the dump **_host_**:**
kernel:3.10.0-327.28.3.el7.x86_64
<details><summary>Output of `/proc/self/cgroup `:</summary>
<p>

```
10:memory:/user.slice
9:devices:/
8:freezer:/
7:blkio:/user.slice
6:net_cls:/
5:hugetlb:/
4:cpuset:/
3:cpuacct,cpu:/user.slice
2:perf_event:/
1:name=systemd:/user.slice/user-0.slice/session-125294.scope
```

</p>
</details>
dump cmd:  
./criu dump --ghost-limit=500M -D /export/sine/dumpdata -j -R -t $pid --tcp-close --skip-in-flight --external mnt[/etc/hosts]:hostsmount --external mnt[/etc/hostname]:hostnamemount --external mnt[/etc/resolv.conf]:reslovemount --external mnt[/var/log/mydb]:mydbmount -v4 -o /export/sine/sinedump.log

**2) And the information about the restore **_container_**:**
kernel:5.12.4-1.el7.elrepo.x86_64
<details><summary>Output of `/proc/self/cgroup `:</summary>
<p>

```
12:pids:/
11:memory:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
10:freezer:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
9:hugetlb:/
8:rdma:/
7:cpuset:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
6:devices:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
5:cpu,cpuacct:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
4:blkio:/system.slice/docker-e7b712511e0979cdc06c16864b0c897030227e583c26f5a45223dc4502cb2823.scope
3:perf_event:/
2:net_cls,net_prio:/
1:name=systemd:/system.slice/docker.service

```

</p>
</details>
restore cmd:  
    ./criu restore --ghost-limit=500M -D /export/sine/dumpdata -j -d --tcp-close --root /export/Data/docker/vfs/dir/  --external mnt[hostsmount]:/etc/hosts --external mnt[hostnamemount]:/etc/hostname --external mnt[reslovemount]:/etc/resolv.conf --external mnt[mydbmount]:/var/log/mydb -v4 -o /export/sine/sinerestore.log

**Describe the results you received:**
retore failed:
(00.012272) Error (criu/cgroup.c:1805): cg: 	Can't mount controller dir .criu.cgyard.TL5et3/net_cls: Device or resource busy

I tried to solve the problem based on this link:
https://github.com/checkpoint-restore/criu/issues/453
"cnames": [
          "net_prio",
           "net_cls"
 ],
and a new error was occurred:
(00.014233) No pidns-9.img image
(00.014291) Forking task with 1 pid (flags 0x2c020000)
(00.014293) Creating process using clone3()
(00.014571) PID: real 1997 virt 1
(00.014691) Wait until namespaces are created
(00.014858)      1: timens: monotonic 19902628 977511782
(00.014878)      1: timens: boottime 19902628 977491503
(00.014975) Running setup-namespaces scripts
(00.014990)      1: cg: Move into 2
(00.014999)      1: Error (criu/cgroup.c:1119): cg: No cg_controller_entry found for net_cls//
(00.015001)      1: Error (criu/cgroup.c:1171): cg: failed preparing cgns
(00.015377) Error (criu/cr-restore.c:2536): Restoring FAILED.

I really look forward to your help!

**Comment by adrianreber** [comment]
I would not recommend going from 3.10 to 5.12 using CRIU. In this case you could ignore the cgroup settings during migration using `--manage-cgroup=ignore`.

The differences between those kernels are just too big.

**Comment by mrc1119** [comment]
> I would not recommend going from 3.10 to 5.12 using CRIU. In this case you could ignore the cgroup settings during migration using `--manage-cgroup=ignore`.
> 
> The differences between those kernels are just too big.

I got it, and I restore on kernel(3.10.0-957.21.3.el7.x86_64) have the same error.

**Comment by mrc1119** [comment]
I tried using the new parameters(--manage-cgroup=ignore) to see if the problem was solved

**Comment by mrc1119** [comment]
@adrianreber 
I used this parameter to resolve the error, thanks.  Is there any other unknown problem?
