### ISSUE TITLE
Could not initialize kernel features detection

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1904]
This error is a first for me, is it a kernel problem?
Looking forward to your help!

**Description**
(00.000039) Version: 3.17 (gitid 496bcdb)
(00.000057) Running on A01-R11-219G7-I108-129.JD.LOCAL Linux 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64
(00.000065) File /run/criu.kdat does not exist
(00.000077) sockets: Probing sock diag modules
(00.001246) sockets: Done probing
(00.003853) Error (criu/util.c:641): exited, status=3
(00.003913) Pagemap is fully functional
(00.003941) Error (criu/kerndat.c:210): Can't stat self map_files 2: No such file or directory
(00.003958) Error (criu/kerndat.c:1509): kerndat_get_shmemdev failed when initializing kerndat.
(00.003986) Adjust mmap_min_addr 0x1000 -> 0x10000
(00.003988) Found mmap_min_addr 0x10000
(00.003997) files stat: fs/nr_open 1048576
(00.003998) Error (criu/crtools.c:260): Could not initialize kernel features detection.

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.17
GitID: 496bcdb
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Error (criu/kerndat.c:210): Can't stat self map_files 2: No such file or directory
Error (criu/kerndat.c:1509): kerndat_get_shmemdev failed when initializing kerndat.
Error (criu/crtools.c:260): Could not initialize kernel features detection.
```

</p>
</details>

**Comment by mrc1119** [comment]
cat /boot/config-3.10.0-229.el7.x86_64 |grep CONFIG_CHECKPOINT_RESTORE
# CONFIG_CHECKPOINT_RESTORE is not set

So I guess the reason is that the kernel was compiled without CONFIG_CHECKPOINT_RESTORE.

**Comment by mrc1119** [comment]
Can this configuration be added dynamically without rebooting the system?

**Comment by mrc1119** [comment]
@avagin @adrianreber @Snorch help~

**Comment by adrianreber** [comment]
> Can this configuration be added dynamically without rebooting the system?

No
