### ISSUE TITLE
We need test(s) for criu-ns script

### ISSUE THREAD

**Issue by Snorch** [checkpoint-restore/criu#1909]
We have quiet some reports about criu-ns problems, but we don't have tests to show that when we fix something we don't break everything else.

Links:
criu-ns script - https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/criu-ns
criu-ns documentation - https://github.com/checkpoint-restore/criu/blob/criu-dev/Documentation/criu-ns.txt

Examples of what the test should check:
https://github.com/checkpoint-restore/criu/issues/1893#issuecomment-1162938507
https://github.com/checkpoint-restore/criu/issues/232#issuecomment-945911657

Notes:

We need to test criu-ns
- with --shell-job and without it
- with --restore-detached and without it

Meaning that you need separate testcases for
- dumpee is init of pidns
- dumpee is not init of pidns
- dumpee to has own session and detached from ttys
- dumpee inherited session from parent and is attached to same tty as parent

We need to have automatic tests integrated in criu CI.

**Comment by warusadura** [comment]
Hi @Snorch, I'm interested in working on this issue. Can you please tell me a little bit about this issue.

**Comment by Snorch** [comment]
> Hi @Snorch, I'm interested in working on this issue. Can you please tell me a little bit about this issue.

I updated the description.

**Comment by warusadura** [comment]
Thanks @Snorch! I'll let you know if I have any questions.

**Comment by warusadura** [comment]
@Snorch I'm still not clear what do here :)

I think I'll have to create a test case for [`def wrap_restore()`](https://github.com/checkpoint-restore/criu/blob/b0de6f4c98d67f414f89303c2b32207af6e1f8f9/scripts/criu-ns#L108). But, I'm not sure where. Also, I understand that `criu` usese `ZDTM`. But, I couldn't find any existing tests for `criu-ns`

Also, what do you meant by "dumpee"?

**Comment by Snorch** [comment]
> @Snorch I'm still not clear what to do here :)
> 
> I think I'll have to create a test case for [`def wrap_restore()`](https://github.com/checkpoint-restore/criu/blob/b0de6f4c98d67f414f89303c2b32207af6e1f8f9/scripts/criu-ns#L108).

You can create a test case which runs criu-ns executable, not a function from it.

> But, I'm not sure where. Also, I understand that `criu` usese `ZDTM`. But, I couldn't find any existing tests for `criu-ns`

ZDTM is a nice place for a test which checks that criu is able to dump/restore something, in your case you check the additional utility criu-ns, that's why I think the proper place for it would be in test/others/.

> Also, what do you meant by "dumpee"?

By `dumpee` I mean the process which was dumped by criu.

**Comment by warusadura** [comment]
@Snorch thanks for the reply.

> You can create a test case which runs criu-ns executable, not a function from it.

Understood. But, is there an existing test implementation similar to this requirement? Is [shell-job](https://github.com/checkpoint-restore/criu/tree/criu-dev/test/others/shell-job) a similar implementation?

Also, how do I execute the previously mentioned `shell-job` test?

**Comment by Snorch** [comment]
> Understood. But, is there an existing test implementation similar to this requirement? Is [shell-job](https://github.com/checkpoint-restore/criu/tree/criu-dev/test/others/shell-job) a similar implementation?

Yes, I believe you can use shell-job test as a skeleton for your criu-ns test. It is really similar to what we need with criu-ns.

> Also, how do I execute the previously mentioned `shell-job` test?

```
[ criu]# cd test/others/shell-job
[ shell-job]# python3 run.py
```
This should do the trick.

**Comment by warusadura** [comment]
Understood, thank you @Snorch

**Comment by warusadura** [comment]
@Snorch 
When I executed the `./scripts/criu-ns` without any arguments, it prints out the usage info. But, when I pass an argument to it as in `./scripts/criu-ns check` or `./scripts/criu-ns dump -t 24445`, I'm getting the following errors,

```
['./scripts/criu-ns', 'check']
Traceback (most recent call last):
  File "/..../criu/./scripts/criu-ns", line 268, in <module>
    run_criu(sys.argv[1:])
  File "/..../criu/./scripts/criu-ns", line 83, in run_criu
    os.execlp('criu', *['criu'] + args)
  File "<frozen os>", line 557, in execlp
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

```
['./scripts/criu-ns', 'dump', '-t', '24445']
Traceback (most recent call last):
  File "/..../criu/./scripts/criu-ns", line 266, in <module>
    res = wrap_dump()
          ^^^^^^^^^^^
  File "/..../criu/./scripts/criu-ns", line 240, in wrap_dump
    run_criu(sys.argv[1:])
  File "/..../criu/./scripts/criu-ns", line 83, in run_criu
    os.execlp('criu', *['criu'] + args)
  File "<frozen os>", line 557, in execlp
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 616, in _execvpe
  File "<frozen os>", line 607, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

Any idea why?

**Comment by warusadura** [comment]
cc @rppt

**Comment by Snorch** [comment]
```
os.execlp('criu', *['criu'] + args)
FileNotFoundError: [Errno 2] No such file or directory
```
Error probably says that you don't have criu binary.

**Comment by warusadura** [comment]
I see. But, I do have the criu binary.

```
./criu/criu check --unprivileged
Looks good.
```

**Comment by rst0git** [comment]
@warusadura [`os.execlp()`](https://docs.python.org/3/library/os.html#os.execlp) is using the `PATH` environment variable to locate `criu`.

**Comment by warusadura** [comment]
Understood. Thanks @rst0git
