### ISSUE TITLE
Socket file missing after successful checkpoint and restore step in postgres image

### ISSUE THREAD

**Issue by shashank-sharma** [checkpoint-restore/criu#1914]
**Description**

After checkpoint and restore of postgres image (14.3), criu is not able to restore one socket file. I observed that after checkpoint, socket file is still there (I checked by mounting the directory and seeing if it is still there), after restoration is when the socket file is missing

**Steps to reproduce the issue:**
1. Pull postgres:14.3 image through docker and export OCI bundle
2. Start runc container and test if it's working fine
3. Do checkpoint and then restore it, you'll notice after restore, it doesn't restore `.s.PGSQL.5432` socket file

Detailed steps can be found here: https://github.com/shashank-sharma/psql-testing/blob/master/pdb/start.sh
And it is possible to reproduce, I have created minimal example:

https://github.com/shashank-sharma/psql-testing

**Describe the results you received:**

```Runc starting
 ?column?                          <<<<<<<< Showing that postgres working fine
----------
        1
(1 row)

total 12                                        <<<<<<<< ls -la /var/run/postgresql
drwxrwsr-x 2 puser puser 4096 Jun 14 00:50 .
drwxr-xr-x 4 root  root  4096 May 28 11:51 ..
srwxrwxrwx 1 puser puser    0 Jun 14 00:50 .s.PGSQL.5432
-rw------- 1 puser puser   59 Jun 14 00:50 .s.PGSQL.5432.lock

Checkpoint starting                            <<<<<<<< showing runc list
ID          PID         STATUS      BUNDLE      CREATED     OWNER

Restoring
total 12                                       <<<<<<<< After restore, ls -la /var/run/postgresql
drwxrwsr-x 2 puser puser 4096 Jun 14 00:50 .
drwxr-xr-x 4 root  root  4096 May 28 11:51 ..
-rw------- 1 puser puser   59 Jun 14 00:50 .s.PGSQL.5432.lock
```

**Describe the results you expected:**

Expected `.s.PGSQL.5432` after restoration so that it is possible to use after restore

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

Log [here](https://raw.githubusercontent.com/shashank-sharma/psql-testing/master/restore.log)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.14
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Error (criu/uffd.c:272): uffd: Lazy pages are not available: Function not implemented
Warn  (criu/kerndat.c:869): Can't keep kdat cache on non-tempfs
Warn  (criu/cr-check.c:850): Dirty tracking is OFF. Memory snapshot will not work.
Error (criu/cr-check.c:1207): UFFD is not supported
Error (criu/cr-check.c:1207): UFFD is not supported
Error (criu/cr-check.c:1033): failed to mount autofs: No such device
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

**Comment by avagin** [comment]
```
(00.469809)      7: unix: ghost: bind id 0x38 ino 621859 addr /var/run/postgresql/.s.PGSQL.5432
(00.469841)      7: unix: ghost: socket id 0x38 ino 621859 name /var/run/postgresql/.s.PGSQL.5432 detected F_OK /var/run/postgresql
(00.469850)      7: unix: ghost: socket id 0x38 ino 621859 name /var/run/postgresql/.s.PGSQL.5432 creating /var/run/postgresql
(00.469906)      7: unix: ghost: id 0x38 621859 fdstore_id 2 /var/run/postgresql/.s.PGSQL.5432
```

@Snorch could you take a look at why criu decided that it is a ghost socket?

**Comment by Snorch** [comment]
I checked it in Virtuozzo container and it `.s.PGSQL.5432` do not dissapear, It can indicate that we need to port something related to unixsk from vzcriu.

I guess it can be due to overmounted files support which we haven't ported yet on top of mount-v2.

Will continue investigating.

**Comment by avagin** [comment]
@Snorch could you write instructions how to dump/restore with the mount-v1 engine. Maybe it will work with it.

**Comment by rst0git** [comment]
> could you write instructions how to dump/restore with the mount-v1 engine.

```
criu --help | grep mntns-compat-mode
  --mntns-compat-mode   Use mount engine in compatibility mode. By default criu
                        tries to use mount-v2 mode with more reliable algorithm
                        based on MOVE_MOUNT_SET_GROUP kernel feature
```

**Comment by Snorch** [comment]
JFYI: Found this problem in mount-v2 when trying to reproduce with newer criu:
https://github.com/checkpoint-restore/criu/pull/1918

**Comment by Snorch** [comment]
@shashank-sharma I've updated your reproduce to use latest criu/docker and it works smoothly now:

https://github.com/Snorch/psql-testing/tree/updated-reproduce

```
Runc starting
 ?column? 
----------
        1
(1 row)

total 4
drwxrwsr-x 1 puser puser 62 Jun 17 12:28 .
drwxr-xr-x 1 root  root  36 May 28 11:51 ..
srwxrwxrwx 1 puser puser  0 Jun 17 12:28 .s.PGSQL.5432
-rw------- 1 puser puser 59 Jun 17 12:28 .s.PGSQL.5432.lock
Checkpoint starting
ID          PID         STATUS      BUNDLE      CREATED     OWNER
Restoring
WARN[0000] Kernel memory settings are ignored and will be removed 
total 4
drwxrwsr-x 1 puser puser 62 Jun 17 12:28 .
drwxr-xr-x 1 root  root  36 May 28 11:51 ..
srwxrwxrwx 1 puser puser  0 Jun 17 12:28 .s.PGSQL.5432
-rw------- 1 puser puser 59 Jun 17 12:28 .s.PGSQL.5432.lock
```

So I believe problem is already solved.

As you can see there are quiet a lot of unix-socket changes in criu between v3.14 which you use and latest criu-dev branch:

```
[snorch@turmoil criu]$ git log --oneline v3.14..criu-dev criu/sk-unix.c
baa4516e6 sk-unix: make add_fake_unix_queuers earier and rework find_queuer_for
d14dbb8c7 sk-unix: rework bind_on_deleted() return codes
9e7473516 sk-unix: fix e_str leak in unix_sk_id_add
1b4a9df9c sk-unix: fix uint32_t id variable printf format specifier
530ad9c89 sk-unix: Add support for SOCK_SEQPACKET unix sockets
94111596f sk-unix: Fix TCP_ESTABLISHED checks in unix sockets
26db7adbb clang-format: do automatic comment fixups
c6b5e7d92 sk-unix: fix prep_unix_sk_cwd root and cwd restoring
93dd984ca Run 'make indent' on all C files
2609e98ee sk-unix: ghost: fix deadlock between peer_fle->stage and fds wake up
f10425e05 criu: end pr_(err|warn|msg|info|debug) with \n
878223560 sk-unix: check whether a socket name is NULL before printing it
7c5c81366 sk-unix: rework unix_resolve_name
d0308e5ec sk-unix: make criu respect existing files while restoring ghost unix socket fd
34024dfdc util: move open_proc_self_fd to service_fd
04d7b7157 sk-unix: ignore coverity chroot() warning
9b1921fb7 sk-unix: do not overwrite function parameter
5b751fbaf criu: the type of a socket inode has to be "unsigned int"
e57e74a18 criu: optimize find_unix_sk_by_ino()
```

**Comment by shashank-sharma** [comment]
@Snorch Thanks for the quick update, I just tested it out (3.17) and you are right, it works fine with the latest version.

Closing this issue, Resolved
