### ISSUE TITLE
predump failed, kernel not support?

### ISSUE THREAD

**Issue by mrc1119** [checkpoint-restore/criu#1926]
I failed to predump the container on a host. And I would like to know how to confirm if the host supports this feature.

criu cmd:
./criu pre-dump -t $pid -j -D /export/sine/predump/ --tcp-close --skip-in-flight v4 -o /export/sine/predump.log

some error:
pie: 1: Error (criu/pie/parasite.c:92): Can't splice pages to pipe (-11/1/472)
(01.412641) Error (compel/src/lib/infect-rpc.c:68): Command 66 for daemon failed with -1
(01.437502) Error (criu/mem.c:625): Can't dump page with parasite
(01.438995) Error (criu/cr-dump.c:1853): Pre-dumping FAILED.

criu version:
Version: 3.17

kernel version:
3.10.0-327.28.3.el7.x86_64

os version:
CentOS Linux release 7.2.1511 

criu check:
./criu check --feature mem_dirty_track
Warn  (criu/autofs.c:99): Failed to find pipe_ino option (old kernel?)
Warn  (criu/cr-check.c:813): Dirty tracking is OFF. Memory snapshot will not work.

**Comment by mrc1119** [comment]
The operating system that has a lot of stock containers is really old, but I can't migrate those containers.
Oddly enough, the dump operation is ok in the current environment.
What do I need to do to confirm that predump is not supported?

**Comment by adrianreber** [comment]
CRIU was never fully supported on CentOS 7. Only as tech preview. predump support was backported later to CentOS.

> What do I need to do to confirm that predump is not supported?
```
./criu check --feature mem_dirty_track
Warn (criu/autofs.c:99): Failed to find pipe_ino option (old kernel?)
Warn (criu/cr-check.c:813): Dirty tracking is OFF. Memory snapshot will not work.
```
You already did it. It is not supported.
