### ISSUE TITLE
Checkpointing Tensorflow-rocm with CRIU

### ISSUE THREAD

**Issue by Skydermoby** [checkpoint-restore/criu#1927]
So I'm trying to checkpoint a tensorflow-rocm (2.9.1) application running on my GPU (Raedeon RX 6950 XT), however, have been so far unsuccessful and have been unable to see why.

Steps
1. Install rocm-5.1.3
2. Install Tensorflow-rocm
3. Install CRIU 3.17
4.  Run a sample TensorFlow program (I used mnist.py)
5.  Use criu dump

Supposedly I should received an echoed "OK" and see multiple new img files created, however neither has occured and when I checked my dump log this is what it replied:

<p>

```
(00.006208) Found regular file mapping, OK
(00.006237) Dumping path for -3 fd via self 12 [/usr/bin/python3.8]
(00.006290) vma 423000 borrows vfi from previous 400000
(00.006298) vma 6b8000 borrows vfi from previous 423000
(00.006304) vma 8f5000 borrows vfi from previous 6b8000
(00.006310) vma 8f6000 borrows vfi from previous 8f5000
(00.016598) Error (criu/proc_parse.c:114): handle_device_vma plugin failed: No such file or directory
(00.016610) Error (criu/proc_parse.c:609): Can't handle non-regular mapping on 11845's map 7f4110000000
(00.016739) Error (criu/cr-dump.c:1524): Collect mappings (pid: 11845) failed with -1
(00.016818) Unlock network
(00.016824) Unfreezing tasks into 1
(00.016825)     Unseizing 11845 into 1
(00.016958) Error (criu/cr-dump.c:2053): Dumping FAILED.
```

</p>

I looked into the test log so I know there is no problem with the tensorflow program itself, I've tried to find solutions and see if anyone else is in the same boat but so far have been unsuccessful

Note: When running criu check --all it displays:
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

**Comment by Snorch** [comment]
CC: @rajbhar @dayatsin-amd @fxkamd Please take a look.

**Comment by Skydermoby** [comment]
I also forgot to mention that my OS is Ubuntu 20.0.4

**Comment by dayatsin-amd** [comment]
@Skydermoby 
Could you post your smaps:
cat /proc/<PID>/smaps

**Comment by Skydermoby** [comment]
I saved my smaps to a txt file
[smaps.txt](https://github.com/checkpoint-restore/criu/files/8994247/smaps.txt)

**Comment by dayatsin-amd** [comment]
Actually, it looks like the CRIU cannot find amdgpu_plugin.

Can you please check if there are errrors when trying to install the plugin:

criu-3.17.1$ sudo make install
Note: Building criu **with amdgpu_plugin**.
:
:


With CRIU 3.17.1, the default path for the plugin is:
/usr/local/lib/criu/amdgpu_plugin.so

With older versions, it is:
/var/lib/criu/amdgpu_plugin.so

**Comment by Skydermoby** [comment]
> criu-3.17.1$ sudo make install

I also want to quickly mention that my default directory name is "criu" and not "criu-3.17.1", not sure if that makes a difference but I just wanted to double check

**Comment by dayatsin-amd** [comment]
Can you try to re-compile your kernel with the options listed here:
https://criu.org/Linux_kernel

**Comment by dayatsin-amd** [comment]
Can you also try to run CRIU with: -L/usr/local/lib/criu/

**Comment by Skydermoby** [comment]
> Can you also try to run CRIU with: -L/usr/local/lib/criu/
I'm not sure what you mean by this/how to do this

**Comment by dayatsin-amd** [comment]
> 

When you run the criu command to checkpoint, you can add "-L/usr/local/lib/criu/ to override the module directory

**Comment by Skydermoby** [comment]
> Can you try to re-compile your kernel with the options listed here: https://criu.org/Linux_kernel 

Thanks, can you also explain how to do this as well?

**Comment by Skydermoby** [comment]
Update: running the -L/usr/local/lib/criu/calong with the dump has worked, however trying to restore via the same method has failed, the error message from the restore log is as below:

`(00.019208)   2266: amdgpu_plugin: Restoring 1 devices
(00.020766)   2266: amdgpu_plugin: amdgpu_plugin: passing drm render fd = 9 to driver
(00.020786)   2266: amdgpu_plugin: Restore devices Ok (ret:0)
(00.020799)   2266: amdgpu_plugin: Restoring 100 BOs
(00.020802)   2266: amdgpu_plugin: Restore BOs Ok
(00.021950)   2266: amdgpu_plugin: amdgpu_plugin: Thread[0x3984] started
(00.022795)   2266: amdgpu_plugin: amdgpu-pages-187-3984.img:Opened file for read with size:16808726528
(62.699087)   2266: Error (amdgpu_plugin.c:640): amdgpu_plugin: failed to create userptr for sdma: Device or resource busy
(62.700140)   2266: Error (amdgpu_plugin.c:1022): amdgpu_plugin: Failed to fill the BO using sDMA: bo_buckets[56]
(62.700222)   2266: amdgpu_plugin: amdgpu_plugin: Thread[0x3984] done num_bos:8 ret:-14
(63.209360)   2266: amdgpu_plugin: Thread[0x3984] finished ret:-14
(63.210279)   2266: Error (amdgpu_plugin.c:1850): amdgpu_plugin: amdgpu_plugin: Failed to restore (ret:-14)
(63.210739)   2266: Error (criu/files-ext.c:53): Unable to restore 0xbb
(63.210820)   2266: Error (criu/files.c:1213): Unable to open fd=3 id=0xbb
(63.212439) Error (criu/cr-restore.c:2536): Restoring FAILED.
(63.213136) amdgpu_plugin: amdgpu_plugin: finished  amdgpu_plugin (AMDGPU/KFD)`

The specific restore line I used is "criu restore -vvvv -o restore.log --shell-job --link-remap --tcp-established --file-locks -L/usr/local/lib/criu/ && echo OK"

**Comment by dayatsin-amd** [comment]
Nice.
Can you check whether if there were any errors reported in dmesg.
Also make sure you run criu restore as a super user.

**Comment by Skydermoby** [comment]
I do not see any error in dmesg, here's everything:
`[    0.920544] [drm] amdgpu kernel modesetting enabled.
[    0.921268] [drm] amdgpu version: 5.13.20.22.10
[    0.922681] amdgpu: CRAT table not found
[    0.923398] amdgpu: Virtual CRAT table created for CPU
[    0.924069] amdgpu: Topology: Add CPU node
[    0.982363] amdgpu: PeerDirect support was initialized successfully
[    0.983617] fb0: switching to amdgpudrmfb from EFI VGA
[    0.984289] amdgpu 0000:03:00.0: vgaarb: deactivate vga console
[    0.984382] amdgpu 0000:03:00.0: amdgpu: Trusted Memory Zone (TMZ) feature not supported
[    0.985651] amdgpu 0000:03:00.0: No more image in the PCI ROM
[    0.985664] amdgpu 0000:03:00.0: amdgpu: Fetched VBIOS from ROM BAR
[    0.985666] amdgpu: ATOM BIOS: 113-EXT800376-L04
[    0.985701] amdgpu 0000:03:00.0: amdgpu: MEM ECC is not presented.
[    0.985702] amdgpu 0000:03:00.0: amdgpu: SRAM ECC is not presented.
[    0.985710] amdgpu 0000:03:00.0: amdgpu: VRAM: 16368M 0x0000008000000000 - 0x00000083FEFFFFFF (16368M used)
[    0.985713] amdgpu 0000:03:00.0: amdgpu: GART: 512M 0x0000000000000000 - 0x000000001FFFFFFF
[    0.985715] amdgpu 0000:03:00.0: amdgpu: AGP: 267894784M 0x0000008400000000 - 0x0000FFFFFFFFFFFF
[    0.985751] [drm] amdgpu: 16368M of VRAM memory ready
[    0.985754] [drm] amdgpu: 16368M of GTT memory ready.
[    2.462670] amdgpu 0000:03:00.0: amdgpu: STB initialized to 2048 entries
[    2.463896] amdgpu 0000:03:00.0: amdgpu: Will use PSP to load VCN firmware
[    2.660172] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
[    2.660196] amdgpu 0000:03:00.0: amdgpu: use vbios provided pptable
[    2.734404] amdgpu 0000:03:00.0: amdgpu: SMU is initialized successfully!
[    2.965211] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    3.027573] amdgpu: HMM registered 16368MB device memory
[    3.027996] amdgpu: SRAT table not found
[    3.027997] amdgpu: Virtual CRAT table created for GPU
[    3.028174] amdgpu: Topology: Add dGPU node [0x73a5:0x1002]
[    3.028177] kfd kfd: amdgpu: added device 1002:73a5
[    3.028199] amdgpu 0000:03:00.0: amdgpu: SE 4, SH per SE 2, CU per SH 10, active_cu_number 80
[    3.028266] amdgpu 0000:03:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[    3.028269] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[    3.028271] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[    3.028272] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 5 on hub 0
[    3.028274] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 6 on hub 0
[    3.028276] amdgpu 0000:03:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 7 on hub 0
[    3.028277] amdgpu 0000:03:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 8 on hub 0
[    3.028279] amdgpu 0000:03:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 9 on hub 0
[    3.028281] amdgpu 0000:03:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 10 on hub 0
[    3.028283] amdgpu 0000:03:00.0: amdgpu: ring kiq_2.1.0 uses VM inv eng 11 on hub 0
[    3.028284] amdgpu 0000:03:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[    3.028286] amdgpu 0000:03:00.0: amdgpu: ring sdma1 uses VM inv eng 13 on hub 0
[    3.028288] amdgpu 0000:03:00.0: amdgpu: ring sdma2 uses VM inv eng 14 on hub 0
[    3.028289] amdgpu 0000:03:00.0: amdgpu: ring sdma3 uses VM inv eng 15 on hub 0
[    3.028291] amdgpu 0000:03:00.0: amdgpu: ring vcn_dec_0 uses VM inv eng 0 on hub 1
[    3.028293] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc_0.0 uses VM inv eng 1 on hub 1
[    3.028294] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc_0.1 uses VM inv eng 4 on hub 1
[    3.028296] amdgpu 0000:03:00.0: amdgpu: ring vcn_dec_1 uses VM inv eng 5 on hub 1
[    3.028298] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc_1.0 uses VM inv eng 6 on hub 1
[    3.028300] amdgpu 0000:03:00.0: amdgpu: ring vcn_enc_1.1 uses VM inv eng 7 on hub 1
[    3.028301] amdgpu 0000:03:00.0: amdgpu: ring jpeg_dec uses VM inv eng 8 on hub 1
[    3.029276] amdgpu 0000:03:00.0: amdgpu: Using BACO for runtime pm
[    3.029827] [drm] Initialized amdgpu 3.45.0 20150101 for 0000:03:00.0 on minor 0
[    3.039192] fbcon: amdgpudrmfb (fb0) is primary device
[    3.347585] amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
[    5.025727] snd_hda_intel 0000:03:00.1: bound 0000:03:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])`

I'm doing all this as a root user, but using "sudo" hasn't worked either

**Comment by Skydermoby** [comment]
I used  ` rocm-smi --showpids ` to identify the process being used by my GPU. While the restore log still says `amdgpu_plugin: failed to create userptr for sdma: Device or resource busy` I do not see any processes running before or after the restore attempt. Is it possible there are other problems that is being confused with, or possibly a process that I can not see, as using "radeontop" shows that 0.8% of VRAM is in use

**Comment by rajbhar** [comment]
can you try once with module param amdgpu.runpm=0 ?

**Comment by Skydermoby** [comment]
Sorry, but how can I set the module parameter?

**Comment by Skydermoby** [comment]
Update: I managed to set runpm to 0, unfortunately, the same error still resides. 
In the meantime I thought I take a look at the following error from the restore log:
`(64.361787) 165091: Error (criu/files-ext.c:53): Unable to restore 0xba
(64.361797) 165091: Error (criu/files.c:1213): Unable to open fd=3 id=0xba`
I saw that the dump created 9 fd indexed 0-8, and that the restore collected all of them as well, however was unable to open fd=3, which has an ID of 0xba, which it said previously it was unable to restore.
0xba can not be found anywhere in the dump log, and flags for fdinfo 3 differ from fdinfo 0,1, and 2. Is there a solution for that?

**Comment by Skydermoby** [comment]
Update:
I'm not sure if this is the best solution, but I found a work around.

Something I didn't mention was that rocm-smi showed vram usage at 99% when tensorflow was running. 
Apparently tensorflow likes to allocate as much memory there is, which explains why criu took around 2 minutes to dump and was unable to restore.

For now, I recommend writing:
`
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
  except RuntimeError as e:
    print(e)
`

At the beginning of your tensorflow program, change the memory_limit value accordingly.

Thanks to anyone who has helped along the way, if anyone else knows of a better solution feel free to reply.

**Comment by rajbhar** [comment]
Did the restore work for you with that workaround?
