### ISSUE TITLE
Rebase criu-dev after 3.17.1 release

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#1940]
I was able to rebase the criu-dev branch on master without any conflicts. Would it be possible to update the criu-dev branch in GitHub as well?

**Comment by rst0git** [comment]
@avagin ping

**Comment by adrianreber** [comment]
@avagin Can you please rebase criu-dev on top of 3.18?

**Comment by avagin** [comment]
Done. Sorry for the delay.
