### ISSUE TITLE
ppc64le: blinky zdtm/transition/maps007

### ISSUE THREAD

**Issue by mihalicyn** [checkpoint-restore/criu#1946]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
We have blinking `zdtm/transition/maps007` test

https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/497/testReport/junit/(root)/criu/zdtm_transition_maps007/
https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/495/testReport/junit/(root)/criu/zdtm_transition_maps007/
https://ci.kernoops.org/job/CRIU/view/CRIU-devel/job/CRIU-ppc64le/job/criu-dev/484/testReport/junit/(root)/criu/zdtm_transition_maps007/

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by rppt** [comment]
CC @ldu4

**Comment by mihalicyn** [comment]
Thanks, Mike! I'll perform initial investigation and experiments with that. I believe that help will be needed for further investigation.
