### ISSUE TITLE
Unable to dump Redis server process during lazy migration

### ISSUE THREAD

**Issue by chengpei1229** [checkpoint-restore/criu#1948]
**Description**

I am trying to perform a lazy migration on the Redis server to migrate the process from one virtual machine to the other VM on another computer. When I use the --lazy-pages option during the dump, the running Redis server is not killed and cannot be stopped by ctrl+c.

**Steps to reproduce the issue:**
1. Download Redis and start Redis server by running: `redis-server`
2. Run command: `sudo criu dump -t $(pidof redis-server) -D <img_dir> --lazy-pages --address <src> --port <port> --shell-job`

**Describe the results you received:**
Does not receive feedback of successful dump. Cannot stop Redis server with ctrl+c unless stop dump using ctrl+c in the criu terminal first.

**Describe the results you expected:**
Redis-server process dumped.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>

</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.15
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good.
```

</p>
</details>

**Additional environment details:**
Ubuntu 20.04
Linux 5.15.0-41-generic

**Comment by adrianreber** [comment]
Hmm. It sounds a bit like you misunderstood how to use lazy migration.

With that command you should have a page server for lazy migration running on port `<port>` which is waiting for request for memory pages from the restore side. The process you are trying to dump is under the control of CRIU and that is why signals like CTRL-C are blocked. It sounds like it works like it should.

**Comment by rst0git** [comment]
@chengpei1229 The following wiki page contains an example with more information: https://criu.org/Lazy_migration
If you have any other questions, please feel free to ask in [gitter](https://gitter.im/save-restore/CRIU) or to create a new issue.
