### ISSUE TITLE
Can dump, but not restore VNC server

### ISSUE THREAD

**Issue by NoobTracker** [checkpoint-restore/criu#1953]
**Description**
I can dump a VNC server and criu tells me that it was successful, but when I try to restore it, it fails.

**Steps to reproduce the issue:**
Here are the commands I've executed:
```
sudo setsid unshare -i ./vnc_server.sh icewm
vncviewer localhost:25
mkdir test 
sudo criu dump -t `pgrep vnc_server.sh` --tcp-established -D ./test -j --ghost-limit 100M -v4
sudo criu restore -D ./test -j --tcp-established --ghost-limit 100M 
```
vnc_server.sh can be found on https://criu.org/VNC . Those commands match https://www.youtube.com/watch?v=kjhuzSl6JYc aside from replacing firefox with icewm (and -v4). 

**Describe the results you received:**
```
$ sudo criu restore -D ./test -j --tcp-established --ghost-limit 100M    
criu: /lib/x86_64-linux-gnu/libnftables.so.1: no version information available (required by criu)
  1348: Error (criu/tty.c:625): tty: Unable to open dev/pts/ptmx with specified index 1
  1348: Error (criu/tty.c:1009): tty: Can't open master pty 0x8 (index 1)
  1348: Error (criu/files.c:1213): Unable to open fd=0 id=0x8
Error (criu/cr-restore.c:2536): Restoring FAILED.
```

**Describe the results you expected:**
A successful restore ...

**Additional information you deem important (e.g. issue happens only occasionally):**
-

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

[dump.log](https://github.com/checkpoint-restore/criu/files/9262502/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/9262503/restore.log)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
criu: /lib/x86_64-linux-gnu/libnftables.so.1: no version information available (required by criu)
Version: 3.17.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
criu: /lib/x86_64-linux-gnu/libnftables.so.1: no version information available (required by criu)
sudo: mon_handle_sigchld: waitpid: No child processes
Looks good.
```

</p>
</details>

**Additional environment details:**
I'm using Kali Linux on a virtual machine.

**Comment by rst0git** [comment]
@NoobTracker Following the steps above, I'm not able to replicate this error on Fedora 36 ([restore.log](https://github.com/checkpoint-restore/criu/files/9262869/restore.log)).

**Comment by NoobTracker** [comment]
Okay, in that case I'll just switch to Fedora, there's not really a reason why I'm using Kali. We'll see if it works.

**Comment by rst0git** [comment]
@NoobTracker from the messages in gitter it looks like the VNC example works on Fedora. If you have any further questions, please to ask in gitter or to create a new issue.
