### ISSUE TITLE
C API Documentation Service Address

### ISSUE THREAD

**Issue by andrej** [checkpoint-restore/criu#1954]
This should be an easy fix. I would do it myself if I was able to edit the wiki, however I do not have an account.

At [Wiki/C-API ](https://criu.org/C_API#set_service_address), it is stated that if you call `criu_set_service_address(NULL)` (with a null argument), it will initialize the API with a socket to `/var/run/criu_service.socket`. I have found this to not be accurate. Instead, it will initialize the address to `./criu_service.socket`, i.e. in the local directory.

This would be good to accurately document, because it might be one of the first points of contact for people with CRIU. (It was for me.)

Proposed documentation change:

> **set service address**[[edit](https://criu.org/index.php?title=C_API&action=edit&section=4)]
> Use `void criu_set_service_address(char *address)` to specify path to a CRIU service socket. Call it with `NULL` to make libcriu use the default address (currently `criu_service.socket` in the local directory).
> Note that a CRIU service must be running at that address for the C-API to work; you cannot use the C-API standalone. To start a CRIU service, run
>     criu service --address /path/to/criu_service.socket
> The path given in this command is the path that needs to be passed to `criu_set_service_address`.

This adds some clarification on the mode of operation, which was not entirely clear to me from the start either.

**Comment by rst0git** [comment]
>Instead, it will initialize the address to ./criu_service.socket, i.e. in the local directory.

This change appears to have been made in https://github.com/checkpoint-restore/criu/commit/a90d01a078421906a09d6b2dc5d62d50e4a627c0. I've updated the wiki page with the proposed documentation change.

@andrej Please feel free to request a wiki account at https://criu.org/Special:RequestAccount
