### ISSUE TITLE
wait_on_helpers_zombies is not covered by tests

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#196]
https://coveralls.io/builds/7166427/source?filename=criu%2Fcr-restore.c#L773

Cc: @tych0

**Comment by xemul** [comment]
Guys, please, remind me, does zdtm/static/helper_zombie_child cover this case or not?

**Comment by tych0** [comment]
Hmm. I think in theory it should be, but coveralls disagrees https://coveralls.io/builds/8365884/source?filename=criu%2Fcr-restore.c and when I put an exit(1) in that function and run the test, it doesn't fail, so clearly something is wrong. I'll look into it :)

**Comment by tych0** [comment]
Hi guys,

So I just looked into this again, and it seems my exit(1) actually is getting called; perhaps I forgot to rebuild. coveralls.io seems broken right now (it won't show me the coverage for recent files), so I can't confirm that it's still broken. Assuming it is, though, it seems like this code is covered, and coveralls fails to detect that somehow (maybe it doesn't look through forks?)
