### ISSUE TITLE
criu_dump without PTRACE_ATTACH

### ISSUE THREAD

**Issue by nakasan617** [checkpoint-restore/criu#1960]
**Description**

I am trying to use criu dump for system calls, and to do that, I am using the ptrace to capture the system calls. But ptrace is also used by criu and this presents some problems. I can detach and attach, but whenever you detach, the process restarts and you are checkpointing the place which is not exactly where you want. 
Is there a way to checkpoint without PTRACE_ATTACH and PTRACE_DETACH in criu?

I have been trying to resolve that by simply commenting out the place where the source code is attaching and detaching, yet I am having an issue with compiling right now, which will be posted in another issue.

**Comment by avagin** [comment]
> Is there a way to checkpoint without PTRACE_ATTACH and PTRACE_DETACH in criu?

No, there isn't.

>  I can detach and attach, but whenever you detach, the process restarts and you are checkpointing the place which is not exactly where you want.

You can send SIGSTOP before detaching from the process.

**Comment by nakasan617** [comment]
thank you.
