### ISSUE TITLE
include/common/scm-code.c:41: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules

### ISSUE THREAD

**Issue by CodeCoderLee** [checkpoint-restore/criu#1967]
When I run "make install" command, some errors like this:

In file included from compel/plugins/std/fds.c:16:
include/common/scm-code.c: In function ‘__recv_fds’:
include/common/scm-code.c:41: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:43: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:42: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:40: note: initialized from here
include/common/scm-code.c: In function ‘send_fds’:
include/common/scm-code.c:41: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:43: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:42: error: dereferencing pointer ‘cmsg’ does break strict-aliasing rules
include/common/scm-code.c:40: note: initialized from here

The gcc version is 
4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)

**Comment by adrianreber** [comment]
You are not saying which OS you use, but from the compiler version it looks like RHEL 6. CRIU does not build nor work on that OS.

Closing this issue. Please re-open if you have further questions.
