### ISSUE TITLE
Fail to restore simple loop process: Segmentation Fault

### ISSUE THREAD

**Issue by RonaldGalea** [checkpoint-restore/criu#1987]
**Description**

Hello! I'm having an issue checkpoint-restoring the simple loop process with the steps provided on the website: https://criu.org/Simple_loop.

**Steps to reproduce the issue:**

I just copy-paste the commands, but have to run them as sudo. For convenience:

`setsid ./test.sh  < /dev/null &> test.log &`

`sudo criu dump -t 86768 -vvv -o dump.log && echo OK`

`sudo criu restore -d -vvv -o restore.log && echo OK`

**Describe the results you received:**

The dumping step works (the last line in *dump.log* is "Dumping finished successfully"), but the restore step fails. Here are the last 2 lines from *restore.log* (no other errors apart from this):

> (00.086901)  63978: Error (criu/cr-restore.c:1480): 64166 killed by signal 11: Segmentation fault
> (00.086952) Error (criu/cr-restore.c:2447): Restoring FAILED.

<br>
What could cause this issue? (it happens both with the isolated run and the `--shell-job` version)

Any hints are appreciated, thank you!
<br>

**CRIU logs and information:**

<details><summary>Output of `sudo criu --version`:</summary>
<p>

```
Version: 3.16.1
```

</p>
</details>

<details><summary>Output of `sudo criu check --all`:</summary>
<p>

```
sudo: mon_handle_sigchld: waitpid: No child processes
Looks good.
```

</p>
</details>

**Additional environment details:**

- OS: Ubuntu 22.04.1 LTS
- Kernel: 5.15.0-52-generic

**Comment by adrianreber** [comment]
This is very unusual. Not sure why that happens. Can you maybe share the complete `dump.log` and `restore.log`. Please run it with `-v4`. What kind of hardware are you using? Any chance you could try it on CentOS/Fedora? Just to see if it works there.

**Comment by RonaldGalea** [comment]
Thank you for the quick reply, Adrian!

I've run it in a priviledged Docker container based on [Fedora](https://hub.docker.com/_/fedora/), and it worked! I attach the full -v4 logs from both OS runs here:
[dump_fedora_container.log](https://github.com/checkpoint-restore/criu/files/9900490/dump_fedora_container.log)
[restore_fedora_container.log](https://github.com/checkpoint-restore/criu/files/9900491/restore_fedora_container.log)
[dump_ubuntu.log](https://github.com/checkpoint-restore/criu/files/9900493/dump_ubuntu.log)
[restore_ubuntu.log](https://github.com/checkpoint-restore/criu/files/9900494/restore_ubuntu.log)

One thing I've noticed is that the criu version for Ubuntu is 3.16.1, but for Fedora it's 3.17.1. I've installed criu with:
`sudo apt-get install criu`
and
`yum install criu`
respectively.

Regarding hardware, I have a regular x86 64bit CPU. Are there other relevant details I could share? Thanks again.

**Comment by adrianreber** [comment]
Ah, now I remember. The error happens because Ubuntu also turned on support for restartable sequences but didn't update the CRIU package. You need 3.17 at least. The CRIU package in fedora is maintained by us the Ubuntu version not. We have a opa and a repository in OBS for up to date CRIU packages.

Just update and you should be good.

**Comment by RonaldGalea** [comment]
Yep, works as expected after updating. Thanks a lot for the help :)
