### ISSUE TITLE
Not an issue: does Mariadb updates mtime for (*.ibd and *.frm) files?

### ISSUE THREAD

**Issue by trendymail** [checkpoint-restore/criu#2005]
Hello From France. :)

**Description**

I am using a backup tool using rsync.

Rsync "quick check" will sync every file if size if different or if mtime is different.

However, it happears that files (*.ibd and *.frm) used by MariaDB are not "updated" very ofen (mtime).

I mean, data is up to date inside these files but why MariadDB doesn't update mtime of these files on each commit?

I am quite sure this is not a bug.

So, please send a "RTFM", I will be very happy! ^^

**Comment by Snorch** [comment]
You should be asking it somewhere else, e.g.: https://github.com/MariaDB/server, not related to CRIU.

**Comment by trendymail** [comment]
Oops...

Sorry for the noise.
