### ISSUE TITLE
criu 3.17.1 does not work on Manjaro Linux with kernel version 6.1.1-1

### ISSUE THREAD

**Issue by Ralf12358** [checkpoint-restore/criu#2033]
**Description**

criu produces the following error on Manjaro Linux with kernel:

criu version: 3.17.1
Kernerl version: Linux 6.1.1-1

```
$ criu check
Looks good.
```

```
(00.022866) No parent images directory provided
(00.022893) Error (criu/lsm.c:37): err scanfing: Invalid argument
(00.022989) Unlock network
(00.022998) Unfreezing tasks into 1
(00.023000)     Unseizing 2745391 into 1
(00.023005)     Unseizing 2752834 into 1
(00.023011) Error (criu/cr-dump.c:2053): Dumping FAILED.
```

criu/lsm.c:37
```C
static int apparmor_get_label(pid_t pid, char **profile_name)
{
	FILE *f;
	char *space;

	f = fopen_proc(pid, "attr/current");
	if (!f)
		return -1;

	if (fscanf(f, "%ms", profile_name) != 1) {
                // !!! Error message generated here. f has unexpected format. Put content of f into log file?
		pr_perror("err scanfing"); 
		fclose(f);
		return -1;
	}
	
// ...
```

**Comment by adrianreber** [comment]
Do you have apparmor enabled on your system? What is the content of `/proc/self/attr/current`?

**Comment by Ralf12358** [comment]
> Do you have apparmor enabled on your system? What is the content of `/proc/self/attr/current`?
```
$ aa-enabled 
Yes
```
apparmor is enabled

```
$ cat /proc/self/attr/current
cat: /proc/self/attr/current: Invalid argument
```
Ok. I see. Seems it is a general problem and not related to criu.

I found this: 
https://unix.stackexchange.com/questions/570545/why-does-sudo-cat-proc-self-attr-current-return-invalid-argument 
... but unfortunately with no solution. 

If you have an advice how to fix it, this would of course help, anyway.

Thanks for the quick response!

**Comment by adrianreber** [comment]
@brauner any ideas why `current` would return invalid argument?

**Comment by Ralf12358** [comment]
> @brauner any ideas why `current` would return invalid argument?

I think I found something. But have to try it:

https://github.com/docker/for-linux/issues/1199
https://wiki.archlinux.org/title/AppArmor#Installation

```
cat /sys/kernel/security/lsm
capability,landlock,lockdown,yama,bpf,apparmor
```

I will try this from the arch wiki:

To enable the AppArmor Linux security model by default and omit the need to set kernel parameters, additionally set the CONFIG_LSM option and specify apparmor as the first "major" module in the list:

It seems *apparmor* needs to be before *bpf*

I will try using these kernel parameters:
```
apparmor=1 lsm=capability,landlock,lockdown,yama,apparmor,bpf
```

**Comment by brauner** [comment]
> @brauner any ideas why `current` would return invalid argument?

It's the default value when no matching LSM has been found. So returning `EINVAL` suggests that no LSM has been activated. The list of LSMs just indicates what LSMs are available.

**Comment by Ralf12358** [comment]
> I will try using these kernel parameters:
> 
> ```
> apparmor=1 lsm=capability,landlock,lockdown,yama,apparmor,bpf
> ```

This fixed it! The issue can be closed. Thanks again for putting me in the right direction.

**Comment by adrianreber** [comment]
Good to hear!
