### ISSUE TITLE
Missing rseq headers on centos7 in CI

### ISSUE THREAD

**Issue by Snorch** [checkpoint-restore/criu#2036]
```
In file included from criu/include/parasite.h:13:0,
                 from criu/cr-dump.c:46:
criu/include/linux/rseq.h:7:22: fatal error: sys/rseq.h: No such file or directory
 #include <sys/rseq.h>
                      ^
compilation terminated.
```

https://github.com/checkpoint-restore/criu/pull/2030/checks?check_run_id=10303595406
https://github.com/checkpoint-restore/criu/pull/2022/checks?check_run_id=10145226897

**Comment by mihalicyn** [comment]
I'll take a look

**Comment by rst0git** [comment]
I was able to replicate this error locally using CentOS 7 container. The error occurs only when the `libbsd-devel` package is installed.

**Comment by adrianreber** [comment]
Thanks. So we either have to not use libbsd or a newer compiler. We are using strlcopy, strlcat and setproctitle from libbsd but there are workarounds if libbsd is not available. Sounds like possible workaround.
