### ISSUE TITLE
criu failed: type NOTIFY errno 0 when create checkpoint from jupyter lab image

### ISSUE THREAD

**Issue by FMyb** [checkpoint-restore/criu#2043]
**Description**

Hello, I will try to create checkpoint from jupyter/scipy-notebook docker image, and it's failed with exception: `Error response from daemon: Cannot checkpoint container 4996abdfd581: runc did not terminate successfully: exit status 1: criu failed: type NOTIFY errno 0 path= *path*: unknown`.

**Steps to reproduce the issue:**
1. run `sudo docker run -p 8888:8888  jupyter/scipy-notebook`
2. Go to jupyter lab and run some executions
3. run `sudo docker checkpoint create --leave-running=true --checkpoint-dir /home/fmyar/checkpoint 4996abdfd581 save7`

**Additional information you deem important (e.g. issue happens only occasionally):**

if don't open jupiter lab and don't run execution inside, but just run the container and create a checkpoint, everything will work

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

[logs](https://gist.github.com/FMyb/6926ecc0f0ac8cd75517771a7d443e1d)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.17.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
sudo: mon_handle_sigchld: waitpid: No child processes
Looks good.
```

</p>
</details>

**Additional environment details:**
`Linux fmyar 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by adrianreber** [comment]
I agree with @hesch.

I never used jupyter myself, but I think it is a browser application. So in that case it might make also sense to use `--tcp-close`.

Something like `echo tcp-established >> /etc/criu/runc.conf` or `echo tcp-close >> /etc/criu/runc.conf` should solve your problem.

**Comment by FMyb** [comment]
Thank you very much. It helped me a lot

**Comment by adrianreber** [comment]
Is checkpointing now working for you? Please close the ticket if it works.
