### ISSUE TITLE
Build error with non-standard prefix

### ISSUE THREAD

**Issue by satmandu** [checkpoint-restore/criu#2045]
I'm building a criu package or Chromebrew and we're having this issue building:

```
  CC       images/pidns.o
  CC       images/google/protobuf/descriptor.o
  CC       images/opts.o
  CC       images/seccomp.o
  CC       images/binfmt-misc.o
  CC       images/time.o
  CC       images/sysctl.o
  CC       images/autofs.o
  CC       images/macvlan.o
  CC       images/sit.o
  CC       images/memfd.o
  CC       images/timens.o
  CC       images/img-streamer.o
  CC       images/bpfmap-file.o
  CC       images/bpfmap-data.o
  CC       images/apparmor.o
  CC       images/rseq.o
  LINK     images/built-in.o
ld.gold: fatal error: -f/--auxiliary may not be used without -shared
make[1]: *** [images/Makefile:118: images/built-in.o] Error 1
make: *** [Makefile:217: images/built-in.o] Error 2
```

The only modification we have otherwise had to make is to fix the hard coded `images/google/protobuf/descriptor.proto` symlink to point to our `/usr/local/include/google/protobuf/descriptor.proto`.

Is there a good way to avoid this issue? We're using GCC 12.2.1 and the gold linker.

**Comment by adrianreber** [comment]
Not sure anyone has tried building CRIU with the gold linker.

Not sure we can help you. We never had linker problem reports. Please try it with another linker if possible.

**Comment by satmandu** [comment]
Thanks. `ld.bfd` worked. `ld.gold` and `mold` linkers did not work.
