### ISSUE TITLE
Cleanup comments regarding todo in cr-dump.c file

### ISSUE THREAD

**Issue by dharmicksai** [checkpoint-restore/criu#2049]
**Description**

In cr-dum.c the [todo](https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/cr-dump.c#L2244) mentions that `cr_dump_shmem has to be called before dump_namespaces()` 
but below the [todo](https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/cr-dump.c#L2249) , we can see that cr_dum_shmem is called before dump_namespace.
Looks like the todo is already implemented and the comments are still remaining 

I wanted to know if the Todo is still yet to be implemented or if the comments are misleading

**Comment by rst0git** [comment]
> I wanted to know if the Todo is still yet to be implemented or if the comments are misleading

@dharmicksai The comment is not misleading. In the [commit message](https://github.com/checkpoint-restore/criu/commit/f65517b95d9da8117d74065da3e3b4877f75731f) that added this comment is mentioned that the patch introduced a quick workaround. This implies that there should be a better solution for this problem that might require refactoring of `cr_dump_shmem()`.
