### ISSUE TITLE
Compilation with glibc 2.24 (centos 6.7)

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#205]
http://paste.ubuntu.com/23061693/

In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from /home/projects/criu/criu-2.5/criu/include/fcntl.h:5,
                 from /home/projects/criu/criu-2.5/criu/include/image.h:9,
                 from /home/projects/criu/criu-2.5/criu/include/imgset.h:6,
                 from criu/seccomp.c:7:
/opt/glibc-2.24/include/bits/fcntl-linux.h:203:0: error: "F_SETPIPE_SZ" redefined [-Werror]
 # define F_SETPIPE_SZ 1031 /\* Set pipe page size array.  _/
 ^
In file included from /home/projects/criu/criu-2.5/criu/include/config.h:4:0,
                 from criu/seccomp.c:6:
/home/projects/criu/criu-2.5/criu/include/config-base.h:33:0: note: this is the location of the previous definition
 # define F_SETPIPE_SZ (F_LINUX_SPECIFIC_BASE + 7)
 ^
In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from /home/projects/criu/criu-2.5/criu/include/fcntl.h:5,
                 from /home/projects/criu/criu-2.5/criu/include/image.h:9,
                 from /home/projects/criu/criu-2.5/criu/include/imgset.h:6,
                 from criu/seccomp.c:7:
/opt/glibc-2.24/include/bits/fcntl-linux.h:204:0: error: "F_GETPIPE_SZ" redefined [-Werror]
 # define F_GETPIPE_SZ 1032 /_ Set pipe page size array.  */
 ^
In file included from /home/projects/criu/criu-2.5/criu/include/config.h:4:0,
                 from criu/seccomp.c:6:
/home/projects/criu/criu-2.5/criu/include/config-base.h:37:0: note: this is the location of the previous definition
 # define F_GETPIPE_SZ  (F_LINUX_SPECIFIC_BASE + 8)
 ^
cc1: all warnings being treated as errors
# 

  CC       criu/page-xfer.o
In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from criu/page-xfer.c:6:
/opt/glibc-2.24/include/bits/fcntl-linux.h:321:0: error: "FALLOC_FL_KEEP_SIZE" redefined [-Werror]
 # define FALLOC_FL_KEEP_SIZE  1 /\* Don't extend size of file
 ^
In file included from criu/page-xfer.c:4:0:
/opt/glibc-2.24/include/linux/falloc.h:4:0: note: this is the location of the previous definition
 #define FALLOC_FL_KEEP_SIZE 0x01 /\* default is extend size _/
 ^
In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from criu/page-xfer.c:6:
/opt/glibc-2.24/include/bits/fcntl-linux.h:324:0: error: "FALLOC_FL_PUNCH_HOLE" redefined [-Werror]
 # define FALLOC_FL_PUNCH_HOLE  2 /_ Create a hole in the file.  _/
 ^
In file included from criu/page-xfer.c:4:0:
/opt/glibc-2.24/include/linux/falloc.h:5:0: note: this is the location of the previous definition
 #define FALLOC_FL_PUNCH_HOLE 0x02 /_ de-allocates range _/
 ^
In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from criu/page-xfer.c:6:
/opt/glibc-2.24/include/bits/fcntl-linux.h:325:0: error: "FALLOC_FL_COLLAPSE_RANGE" redefined [-Werror]
 # define FALLOC_FL_COLLAPSE_RANGE 8 /_ Remove a range of a file
 ^
In file included from criu/page-xfer.c:4:0:
/opt/glibc-2.24/include/linux/falloc.h:28:0: note: this is the location of the previous definition
 #define FALLOC_FL_COLLAPSE_RANGE 0x08
 ^
In file included from /opt/glibc-2.24/include/bits/fcntl.h:61:0,
                 from /opt/glibc-2.24/include/fcntl.h:35,
                 from criu/page-xfer.c:6:
/opt/glibc-2.24/include/bits/fcntl-linux.h:328:0: error: "FALLOC_FL_ZERO_RANGE" redefined [-Werror]
 # define FALLOC_FL_ZERO_RANGE  16 /\* Convert a range of a
 ^
In file included from criu/page-xfer.c:4:0:
/opt/glibc-2.24/include/linux/falloc.h:42:0: note: this is the location of the previous definition
 #define FALLOC_FL_ZERO_RANGE  0x10

Cc @cyrillos

**Comment by xemul** [comment]
Maybe @kolyshkin would have chance to look at it...

**Comment by xemul** [comment]
Any volunteers? Maybe @gorcunov?

**Comment by cyrillos** [comment]
I fear not at the moment, possibly in March.

**Comment by lovemyliwu** [comment]
@xemul you may check tutorial https://www.smitechow.com/2018/03/compile-criu-on-centos-6.html

**Comment by xemul** [comment]
@lovemyliwu , wow! Thanks. @avagin , @cyrillos , would you please pick this up?

**Comment by avagin** [comment]
I've update the articles page:  https://criu.org/Articles

**Comment by xemul** [comment]
If it's still an issue for anyone -- feel free to re-open.
