### ISSUE TITLE
Is process duplication supported?

### ISSUE THREAD

**Issue by cadedaniel** [checkpoint-restore/criu#2053]
Hi CRIU team, impressed by the project, thanks for your work!

Is it possible to duplicate processes with CRIU, given that I am OK with PIDs changing? Furthermore, is it even recommended to do so, given that the process may have internally stored its PID and thus may encounter bugs upon restoration with a different PID?

I am interested in prototyping CRIU as a mechanism for duplicating processes. My high-level goal is to support preloading python programs (with their large imports, e.g. tensorflow). A simple `fork`server would do the trick except some popular python libraries spawn pthreads upon import (`numpy`).

I saw https://criu.org/index.php?title=Usage_scenarios#Processes_duplication, but I didn't see any command-line options for this and didn't see despite googling around. Sorry if I missed something!

**Comment by adrianreber** [comment]
Please have a look at #1980 and https://github.com/albertz/python-preloaded which tries to do similar things. I think.

> Is it possible to duplicate processes with CRIU, given that I am OK with PIDs changing?

Yes, you can edit the checkpoint files with the help of CRIT and select another PID. Or you can create a PID namespace for each process you restore, that is even easier.

> Furthermore, is it even recommended to do so, given that the process may have internally stored its PID and thus may encounter bugs upon restoration with a different PID?

That is something only you can decide. Generally speaking, no, but if you know what you do and have full control over your source code it could be doable.

**Comment by cadedaniel** [comment]
Thanks @adrianreber !
