### ISSUE TITLE
Can't handle non-regular mapping / handle_device_vma plugin failed

### ISSUE THREAD

**Issue by TCH68k** [checkpoint-restore/criu#2065]
I am trying to store a process, but CRIU always fails to do this.
```
# criu dump -t [PID] -D /tmp/
```
3.16.1 and before:
```
Error (criu/proc_parse.c:603): Can't handle non-regular mapping on 14090's map 7b8fa000
Error (criu/cr-dump.c:1250): Collect mappings (pid: 14090) failed with -1
Error (criu/cr-dump.c:1768): Dumping FAILED.
```
3.17 and 3.17.1:
```
Error (criu/proc_parse.c:114): handle_device_vma plugin failed: No such file or directory
Error (criu/proc_parse.c:609): Can't handle non-regular mapping on 28051's map 7bf52000
Error (criu/cr-dump.c:1524): Collect mappings (pid: 28051) failed with -1
Error (criu/cr-dump.c:2053): Dumping FAILED.
```
Currently i use CRIU 3.13, because that is the last version which only simply says _"Looks good."_, but does not work either.
```
# criu check --all
```
From 3.14 it starts to complain about missing kernel features. (The kernel is 4.19.) 3.17 and 3.17.1 even refuses to install, because `drm/drm.h` is missing. It is actually located under `libdrm/drm.h`, but i do a symlink, then it starts to complain about undefined macros. If i remove the amdgpu plugin parts in `Makefile.config`, then it compiles and installs. (I have an nVidia card.) But it still does not work. The result for
```
# criu check --all
```
with 3.17.1 is the following:
```
Warn  (criu/kerndat.c:1093): Stale /run/criu.kdat file
Warn  (criu/kerndat.c:1336): Can't get pidfd
Warn  (criu/kerndat.c:1453): CRIU was built without libnftables support
Warn  (criu/cr-check.c:1231): clone3() with set_tid not supported
Error (criu/cr-check.c:1273): Time namespaces are not supported
Error (criu/cr-check.c:1283): IFLA_NEW_IFINDEX isn't supported
Warn  (criu/cr-check.c:1300): Pidfd store requires pidfd_open syscall which is not supported
Warn  (criu/cr-check.c:1334): Nftables based locking requires libnftables and set concatenations support
Warn  (criu/cr-check.c:804): ptrace(PTRACE_GET_RSEQ_CONFIGURATION) isn't supported. C/R of processes which are using rseq() won't work.
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```
I understand that 3.14 and above does not work because of missing functions in the kernel, but why does not 3.13 and below either?

**Comment by adrianreber** [comment]
The output from 3.17.1 looks okay. Just do not run it with `--all`. It still says `Looks good`.

Can you share the complete log of your checkpoint attempt. This is probably not related to the version of CRIU, this seems to be a problem with the process you are trying to checkpoint. Maybe you are doing something that is just not supported.

**Comment by TCH68k** [comment]
Today i've upgraded my system to Devuan 4 with kernel 5.10 and recompiled CRIU v3.17.1.
```
# criu check --all -v4 -o /tmp/criu_check.log
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

root@Csabi:/tmp/criu-3.17.1
# criu dump -t 6963 -D /tmp/ -v4 -o /tmp/criu_dump.log
```
Logfiles:
http://oscomp.hu/depot/criu_check.log
http://oscomp.hu/depot/criu_dump.log
The process is a game, running from WINE 8.0.

**Comment by adrianreber** [comment]
CRIU cannot checkpoint any process using hardware accelerated graphics. Basically anything with a graphical interface cannot be checkpointed (if you run it without hardware acceleration like VNC it might work).

The problem is that CRIU cannot restore the state of the GPU because CRIU does not know how to extract that information from the GPU and restore it later back.

In your case Nvidia could write a plugin for CRIU to support it, but it is very unlikely they will do it.

**Comment by TCH68k** [comment]
Oh... That's too bad. It seems i still have to resort to use a VM for this. Well, thank you for enlightening me. This can be closed as it is not a problem with CRIU, sorry for the misunderstanding.

**Comment by adrianreber** [comment]
No, problem.
