### ISSUE TITLE
CRIU Issues: The criu itself is within dumped tree

### ISSUE THREAD

**Issue by Basileuszsr** [checkpoint-restore/criu#2080]
**Description**
When I am periodically making checkpoints inside a docker, I got these errors:

Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.048903) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.048985) Seized task 209, state 0
(00.049003) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049039) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049107) Seized task 209, state 0
(00.049125) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049156) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049224) Seized task 209, state 0
(00.049241) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049272) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049341) Seized task 209, state 0
(00.049358) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049391) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049458) Seized task 209, state 0
(00.049475) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049508) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049513) Collected (-1 attempts, 1 in_progress)
(00.049516) Collected (4 attempts, -1 in_progress)
(00.049529) Unlock network
(00.049534) Unfreezing tasks into 1
(00.049737) Error (criu/cr-dump.c:2099): Dumping FAILED.

CRIU check: looks good

**Comment by rst0git** [comment]
@Basileuszsr Could you please upload the entire log file?

**Comment by Basileuszsr** [comment]
> @Basileuszsr Could you please upload the entire log file?
> 
> > When I am periodically making checkpoints inside a docker
> 
> Note that you might need to start the container with ` --privileged` to be able to use CRIU. For example:
> 
> ```
> sudo podman run -it --rm \
>     --privileged \
>     --mount type=tmpfs,tmpfs-size=512M,destination=/tmp \
>     --mount type=tmpfs,tmpfs-size=512M,destination=/run \
>     --network=host \
>     --cgroupns=host \
>     -v /lib/modules:/lib/modules \
>     alpine sh
> 
> # apk add criu --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
> ```

Hi Thank you for your reply. It is kind of hard to provide the whole log, but here is a more detailed one. I added --privileged to start CRIU. This is the whole error when making a checkpoint.

Error (criu/sockets.c:210): sockets: Diag module missing (-2)
Warn  (criu/kerndat.c:1538): CRIU was built without libnftables support
Looks good.
...some linux information and then...
(00.000055) Loaded kdat cache from /run/criu.kdat
(00.000084) Hugetlb size 2 Mb is supported but cannot get dev's number
(00.000100) Hugetlb size 1024 Mb is supported but cannot get dev's number
(00.000382) ptrace(PTRACE_GET_RSEQ_CONFIGURATION) is not supported
(00.000510) Will dump/restore TCP connections
(00.000521) ========================================
(00.000525) Dumping processes (pid: 29)
(00.000526) ========================================
Use heaptrack_print to see total criu checkpoint runtime.
criu checkpoint begins... See timestamp ↓
2023/02/09 18:26:42:713
(00.005387) irmap: Searching irmap cache in work dir
(00.005457) No irmap-cache image
(00.005463) irmap: Searching irmap cache in parent
(00.005468) irmap: No irmap cache
(00.005815) cg-prop: Parsing controller "cpu"
(00.005847) cg-prop: 	Strategy "replace"
(00.005879) cg-prop: 	Property "cpu.shares"
(00.005904) cg-prop: 	Property "cpu.cfs_period_us"
(00.005925) cg-prop: 	Property "cpu.cfs_quota_us"
(00.005946) cg-prop: 	Property "cpu.rt_period_us"
(00.005968) cg-prop: 	Property "cpu.rt_runtime_us"
(00.005981) cg-prop: Parsing controller "memory"
(00.006000) cg-prop: 	Strategy "replace"
(00.006021) cg-prop: 	Property "memory.limit_in_bytes"
(00.006048) cg-prop: 	Property "memory.memsw.limit_in_bytes"
(00.006068) cg-prop: 	Property "memory.swappiness"
(00.006090) cg-prop: 	Property "memory.soft_limit_in_bytes"
(00.006108) cg-prop: 	Property "memory.move_charge_at_immigrate"
(00.006129) cg-prop: 	Property "memory.oom_control"
(00.006148) cg-prop: 	Property "memory.use_hierarchy"
(00.006168) cg-prop: 	Property "memory.kmem.limit_in_bytes"
(00.006194) cg-prop: 	Property "memory.kmem.tcp.limit_in_bytes"
(00.006209) cg-prop: Parsing controller "cpuset"
(00.006240) cg-prop: 	Strategy "replace"
(00.006262) cg-prop: 	Property "cpuset.cpus"
(00.006282) cg-prop: 	Property "cpuset.mems"
(00.006310) cg-prop: 	Property "cpuset.memory_migrate"
(00.006334) cg-prop: 	Property "cpuset.cpu_exclusive"
(00.006356) cg-prop: 	Property "cpuset.mem_exclusive"
(00.006380) cg-prop: 	Property "cpuset.mem_hardwall"
(00.006402) cg-prop: 	Property "cpuset.memory_spread_page"
(00.006423) cg-prop: 	Property "cpuset.memory_spread_slab"
(00.006444) cg-prop: 	Property "cpuset.sched_load_balance"
(00.006468) cg-prop: 	Property "cpuset.sched_relax_domain_level"
(00.006483) cg-prop: Parsing controller "blkio"
(00.006506) cg-prop: 	Strategy "replace"
(00.006526) cg-prop: 	Property "blkio.weight"
(00.006538) cg-prop: Parsing controller "freezer"
(00.006560) cg-prop: 	Strategy "replace"
(00.006574) cg-prop: Parsing controller "perf_event"
(00.006593) cg-prop: 	Strategy "replace"
(00.006605) cg-prop: Parsing controller "net_cls"
(00.006627) cg-prop: 	Strategy "replace"
(00.006647) cg-prop: 	Property "net_cls.classid"
(00.006659) cg-prop: Parsing controller "net_prio"
(00.006683) cg-prop: 	Strategy "replace"
(00.006706) cg-prop: 	Property "net_prio.ifpriomap"
(00.006721) cg-prop: Parsing controller "pids"
(00.006743) cg-prop: 	Strategy "replace"
(00.006762) cg-prop: 	Property "pids.max"
(00.006774) cg-prop: Parsing controller "devices"
(00.006797) cg-prop: 	Strategy "replace"
(00.006816) cg-prop: 	Property "devices.list"
(00.007228) Preparing image inventory (version 1)
(00.007365) Add pid ns 1 pid 209
(00.007387) Add net ns 2 pid 209
(00.007409) Add ipc ns 3 pid 209
(00.007432) Add uts ns 4 pid 209
(00.007452) Add time ns 5 pid 209
(00.007474) Add mnt ns 6 pid 209
(00.007495) Add user ns 7 pid 209
(00.007518) Add cgroup ns 8 pid 209
(00.007521) cg: Dumping cgroups for thread 209
(00.007932) cg: Set 1 is criu one
(00.040167) Seized task 29, state 1
(00.040352) Collected (4 attempts, 0 in_progress)
(00.040438) Seized task 38, state 0
(00.040579) Collected (4 attempts, 0 in_progress)
(00.040622) Seized task 43, state 0
(00.041164) 	Seizing 43's 124 thread
(00.041240) 	Seizing 43's 125 thread
(00.041311) 	Seizing 43's 126 thread
(00.041376) 	Seizing 43's 127 thread
(00.041453) 	Seizing 43's 128 thread
(00.041555) 	Seizing 43's 129 thread
(00.041683) 	Seizing 43's 130 thread
(00.041754) 	Seizing 43's 131 thread
(00.041818) 	Seizing 43's 132 thread
(00.041879) 	Seizing 43's 133 thread
(00.041949) 	Seizing 43's 134 thread
(00.042058) 	Seizing 43's 135 thread
(00.042133) 	Seizing 43's 136 thread
(00.042204) 	Seizing 43's 137 thread
(00.042285) 	Seizing 43's 138 thread
(00.042352) 	Seizing 43's 139 thread
(00.042421) 	Seizing 43's 140 thread
(00.042497) 	Seizing 43's 141 thread
(00.042563) 	Seizing 43's 167 thread
(00.042632) 	Seizing 43's 168 thread
(00.042708) 	Seizing 43's 169 thread
(00.042770) 	Seizing 43's 170 thread
(00.042835) 	Seizing 43's 171 thread
(00.042908) 	Seizing 43's 172 thread
(00.042972) 	Seizing 43's 173 thread
(00.043037) 	Seizing 43's 174 thread
(00.043109) 	Seizing 43's 175 thread
(00.043607) Collected (3 attempts, 0 in_progress)
(00.043741) Collected (4 attempts, 0 in_progress)
(00.047788) Collected 43 in 1 state
(00.047845) Collected (3 attempts, 0 in_progress)
(00.047988) Collected 38 in 1 state
(00.047993) Seized task 189, state 0
(00.048122) Collected (4 attempts, 0 in_progress)
(00.048192) Seized task 207, state 0
(00.048313) Collected (4 attempts, 0 in_progress)
(00.048342) Collected (4 attempts, 0 in_progress)
(00.048507) Collected 207 in 1 state
(00.048512) Seized task 208, state 0
(00.048642) Collected (4 attempts, 0 in_progress)
(00.048672) Collected (4 attempts, 0 in_progress)
(00.048844) Collected 208 in 1 state
(00.048848) Seized task 209, state 0
(00.048869) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.048903) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.048985) Seized task 209, state 0
(00.049003) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049039) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049107) Seized task 209, state 0
(00.049125) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049156) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049224) Seized task 209, state 0
(00.049241) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049272) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049341) Seized task 209, state 0
(00.049358) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049391) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049458) Seized task 209, state 0
(00.049475) Warn  (compel/src/lib/infect.c:133): Unable to interrupt task: 209 (Operation not permitted)
(00.049508) Error (compel/src/lib/infect.c:261): The criu itself is within dumped tree.
(00.049513) Collected (-1 attempts, 1 in_progress)
(00.049516) Collected (4 attempts, -1 in_progress)
(00.049529) Unlock network
(00.049534) Unfreezing tasks into 1
(00.049737) Error (criu/cr-dump.c:2099): Dumping FAILED.

**Comment by adrianreber** [comment]
How do you run CRIU? Which options? Which process are you trying to checkpoint in the container? Complete logs would be helpful, indeed.
