### ISSUE TITLE
docker checkpoint create failed

### ISSUE THREAD

**Issue by Carol-code2222** [checkpoint-restore/criu#2082]
I refer to the official document https://criu.org/Docker to create a container to run "docker run -d --name looper test /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done' " and create a checkpoint. However, it fails.  
the criu-dump.log  show: /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/2da7622894eda3c98c5f6375cf0b6129f64374203564501ecb3787f2603f70cf/criu-dump.log 

(00.000000) Unable to get $HOME directory, local configuration file will not be used.
(00.000043) Version: 3.17 (gitid v3.17-146-g317170ce0)
(00.000048) Running on localhost.localdomain Linux 5.10.167 #2 SMP Tue Feb 14 11:46:24 CST 2023 x86_64
(00.000069) Warn  (criu/kerndat.c:1153): Stale /run/criu.kdat file
(00.000093) sockets: Probing sock diag modules
(00.000142) sockets: Done probing
(00.002846) Pagemap is fully functional
(00.002880) Found anon-shmem device at 1
(00.002912) Hugetlb size 2 Mb is supported but cannot get dev's number
(00.002922) Hugetlb size 1024 Mb is supported but cannot get dev's number
(00.002937) Reset 14527's dirty tracking
(00.002972)  ... done
(00.002991) Dirty track supported on kernel
(00.003040) Found task size of 7ffffffff000
(00.004449) Restoring netdev veth idx 10
(00.004717) Dumping netns links
(00.004740)     LD: Got link 1, type 772
(00.004743)     LD: Got link 10, type 1
(00.021144) No MOVE_MOUNT_SET_GROUP kernel feature
(00.025478) vdso: Parsing at 7ffd14315000 7ffd14317000
(00.025488) vdso: PT_LOAD p_vaddr: 0
(00.025490) vdso: DT_HASH: 120
(00.025491) vdso: DT_STRTAB: 2d8
(00.025493) vdso: DT_SYMTAB: 1b8
(00.025494) vdso: DT_STRSZ: 72
(00.025495) vdso: DT_SYMENT: 18
(00.025496) vdso: nbucket 3 nchain c bucket 7ffd14315128 chain 7ffd14315134
(00.025500) vdso: rt [vdso] 7ffd14315000-7ffd14317000 [vvar] 7ffd14311000-7ffd14315000
(00.025943) vdso: Parsing at 7fd1ea7c1000 7fd1ea7c3000
(00.025953) vdso: PT_LOAD p_vaddr: 0
(00.025954) vdso: DT_HASH: b4
(00.025956) vdso: DT_STRTAB: 1f0
(00.025957) vdso: DT_SYMTAB: 140
(00.025958) vdso: DT_STRSZ: c0
(00.025960) vdso: DT_SYMENT: 10
(00.025961) vdso: nbucket 3 nchain b bucket 7fd1ea7c10bc chain 7fd1ea7c10c8
(00.025963) vdso: compat [vdso] 7ffd14319000-7ffd1431b000 [vvar] 7ffd14315000-7ffd14319000
(00.026515) cpu: x86_family 6 x86_vendor_id GenuineIntel x86_model_id Intel(R) Xeon(R) Gold 6261 CPU @ 3.00GHz
(00.026526) cpu: fpu: xfeatures_mask 0xf5 xsave_size 2688 xsave_size_max 2688 xsaves_size 2560
(00.026543) cpu: fpu: x87 floating point registers     xstate_offsets      0 / 0      xstate_sizes    160 / 160
(00.026547) cpu: fpu: AVX registers                    xstate_offsets    576 / 576    xstate_sizes    256 / 256
(00.026549) cpu: fpu: MPX CSR                          xstate_offsets   1024 / 832    xstate_sizes     64 / 64
(00.026551) cpu: fpu: AVX-512 opmask                   xstate_offsets   1088 / 896    xstate_sizes     64 / 64
(00.026552) cpu: fpu: AVX-512 Hi256                    xstate_offsets   1152 / 960    xstate_sizes    512 / 512
(00.026554) cpu: fpu: AVX-512 ZMM_Hi256                xstate_offsets   1664 / 1472   xstate_sizes   1024 / 1024
(00.027002) ptrace(PTRACE_GET_RSEQ_CONFIGURATION) is not supported
(00.027150) Adjust mmap_min_addr 0x1000 -> 0x10000
(00.027153) Found mmap_min_addr 0x10000
(00.027159) files stat: fs/nr_open 1073741816
(00.027227) ========================================
(00.027230) Dumping processes (pid: 6274)
(00.027231) ========================================
(00.027235) rlimit: RLIMIT_NOFILE unlimited for self
(00.027239) Running pre-dump scripts
(00.027240)     RPC
(00.027357) irmap: Searching irmap cache in work dir
(00.027365) No irmap-cache image
(00.027367) irmap: Searching irmap cache in parent
(00.027371) No parent images directory provided
(00.027373) irmap: No irmap cache
(00.027375) cpu: fpu:1 fxsr:1 xsave:1 xsaveopt:1 xsavec:1 xgetbv1:1 xsaves:1
(00.027434) cg-prop: Parsing controller "cpu"
(00.027437) cg-prop:    Strategy "replace"
(00.027440) cg-prop:    Property "cpu.shares"
(00.027442) cg-prop:    Property "cpu.cfs_period_us"
(00.027443) cg-prop:    Property "cpu.cfs_quota_us"
(00.027444) cg-prop:    Property "cpu.rt_period_us"
(00.027446) cg-prop:    Property "cpu.rt_runtime_us"
(00.027447) cg-prop: Parsing controller "memory"
(00.027449) cg-prop:    Strategy "replace"
(00.027450) cg-prop:    Property "memory.limit_in_bytes"
(00.027452) cg-prop:    Property "memory.memsw.limit_in_bytes"
(00.027453) cg-prop:    Property "memory.swappiness"
(00.027454) cg-prop:    Property "memory.soft_limit_in_bytes"
(00.027461) cg-prop:    Property "memory.move_charge_at_immigrate"
(00.027463) cg-prop:    Property "memory.oom_control"
(00.027464) cg-prop:    Property "memory.use_hierarchy"
(00.027466) cg-prop:    Property "memory.kmem.limit_in_bytes"
(00.027467) cg-prop:    Property "memory.kmem.tcp.limit_in_bytes"
(00.027469) cg-prop: Parsing controller "cpuset"
(00.027470) cg-prop:    Strategy "replace"
(00.027472) cg-prop:    Property "cpuset.cpus"
(00.027473) cg-prop:    Property "cpuset.mems"
(00.027475) cg-prop:    Property "cpuset.memory_migrate"
(00.027476) cg-prop:    Property "cpuset.cpu_exclusive"
(00.027477) cg-prop:    Property "cpuset.mem_exclusive"
(00.027479) cg-prop:    Property "cpuset.mem_hardwall"
(00.027480) cg-prop:    Property "cpuset.memory_spread_page"
(00.027482) cg-prop:    Property "cpuset.memory_spread_slab"
(00.027483) cg-prop:    Property "cpuset.sched_load_balance"
(00.027484) cg-prop:    Property "cpuset.sched_relax_domain_level"
(00.027486) cg-prop: Parsing controller "blkio"
(00.027487) cg-prop:    Strategy "replace"
(00.027489) cg-prop:    Property "blkio.weight"
(00.027490) cg-prop: Parsing controller "freezer"
(00.027492) cg-prop:    Strategy "replace"
(00.027493) cg-prop: Parsing controller "perf_event"
(00.027495) cg-prop:    Strategy "replace"
(00.027496) cg-prop: Parsing controller "net_cls"
(00.027497) cg-prop:    Strategy "replace"
(00.027499) cg-prop:    Property "net_cls.classid"
(00.027500) cg-prop: Parsing controller "net_prio"
(00.027502) cg-prop:    Strategy "replace"
(00.027503) cg-prop:    Property "net_prio.ifpriomap"
(00.027505) cg-prop: Parsing controller "pids"
(00.027506) cg-prop:    Strategy "replace"
(00.027507) cg-prop:    Property "pids.max"
(00.027509) cg-prop: Parsing controller "devices"
(00.027510) cg-prop:    Strategy "replace"
(00.027512) cg-prop:    Property "devices.list"
(00.027544) Preparing image inventory (version 1)
(00.027563) Add pid ns 1 pid 14527
(00.027570) Add net ns 2 pid 14527
(00.027576) Add ipc ns 3 pid 14527
(00.027582) Add uts ns 4 pid 14527
(00.027589) Add time ns 5 pid 14527
(00.027600) Add mnt ns 6 pid 14527
(00.027606) Add user ns 7 pid 14527
(00.027613) Add cgroup ns 8 pid 14527
(00.027615) cg: Dumping cgroups for thread 14527
(00.027634) cg:  `- New css ID 1
(00.027636) cg:     `- [blkio] -> [/system.slice/docker.service] [0]
(00.027638) cg:     `- [cpu,cpuacct] -> [/system.slice/docker.service] [0]
(00.027639) cg:     `- [cpuset] -> [/] [0]
(00.027640) cg:     `- [devices] -> [/system.slice/docker.service] [0]
(00.027642) cg:     `- [freezer] -> [/system.slice/docker.service] [0]
(00.027643) cg:     `- [hugetlb] -> [/] [0]
(00.027644) cg:     `- [memory] -> [/system.slice/docker.service] [0]
(00.027646) cg:     `- [name=systemd] -> [/system.slice/docker.service] [0]
(00.027647) cg:     `- [net_cls,net_prio] -> [/] [0]
(00.027648) cg:     `- [perf_event] -> [/] [0]
(00.027650) cg:     `- [pids] -> [/system.slice/docker.service] [0]
(00.027651) cg:     `- [rdma] -> [/] [0]
(00.027652) cg: Set 1 is criu one
(00.027658) Detected cgroup V1 freezer
(10.027693) Error (criu/cr-dump.c:1785): Timeout reached. Try to interrupt: 0
(10.027805) Error (compel/src/lib/infect.c:263): Unseizable non-zombie **6274** found, state D, err -1/4
(10.027830) Unlock network
(10.027837) Unfreezing tasks into 1
(10.027838)     Unseizing 6274 into 1
(10.027851) Error (compel/src/lib/infect.c:418): Unable to detach from **6274**: No such process
(10.027866) Error (criu/cr-dump.c:2099): Dumping FAILED.

The pid **6274** is command:  " /bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done"
#ps aux | grep  **6274**  
root        **6274**  0.0  0.0   4032  2948 ?        Ss   11:52   0:04 **/bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done**
The status of this command process is not D state,
#cat /proc/**6274**/status | grep State
State:  S (sleeping)
why criu cannot checkpoint???

**Comment by adrianreber** [comment]
I have not seen an error like this before. Does it happen all the time?

**Comment by Carol-code2222** [comment]
It's probably not criu's problem. I used the docker-ce-18.09 rpm package of centos7 to replace the modified docker package by us. This problem does not exist. It is not clear what code of docker is modified by us to cause this problem.

**Comment by Carol-code2222** [comment]
> It's probably not criu's problem. I used the docker-ce-18.09 rpm package of centos7 to replace the modified docker package by us. This problem does not exist. It is not clear what code of docker is modified by us to cause this problem.

**Comment by Carol-code2222** [comment]
> 



> I have not seen an error like this before. Does it happen all the time?

It's probably not criu's problem. I used the docker-ce-18.09 rpm package of centos7 to replace the modified docker package by us. This problem does not exist. It is not clear what code of docker is modified by us to cause this problem.

**Comment by adrianreber** [comment]
Sounds like this can be closed, right?
