### ISSUE TITLE
Can criu checkpoint and restore processes in a container outside the container?

### ISSUE THREAD

**Issue by Carol-code2222** [checkpoint-restore/criu#2083]
why criu should be run by docker？？Can criu checkpoint and restore processes in a container independently outside the container?

**Comment by adrianreber** [comment]
It depends. If your container is setup in a way that nothing from the host leaks in the container it can work.

**Comment by Carol-code2222** [comment]
For example, what on the host leaks into the container that causes the CRIU  fail to checkpoint and restore processes from outside the container?

**Comment by Carol-code2222** [comment]
> It depends. If your container is setup in a way that nothing from the host leaks in the container it can work.

For example, what on the host leaks into the container that causes the CRIU fail to checkpoint and restore processes from outside the container?

**Comment by adrianreber** [comment]
> > It depends. If your container is setup in a way that nothing from the host leaks in the container it can work.
> 
> For example, what on the host leaks into the container that causes the CRIU fail to checkpoint and restore processes from outside the container?

What people usually report is about mount points. You have to mark them as external in CRIU and then it should work.

What I also did not mention is that you need a privileged container. So you need to start your container, depending on your container engine, with something like `--privileged`.

**Comment by Carol-code2222** [comment]
> > > It depends. If your container is setup in a way that nothing from the host leaks in the container it can work.
> > 
> > 
> > For example, what on the host leaks into the container that causes the CRIU fail to checkpoint and restore processes from outside the container?
> 
> What people usually report is about mount points. You have to mark them as external in CRIU and then it should work.
> 
> What I also did not mention is that you need a privileged container. So you need to start your container, depending on your container engine, with something like `--privileged`.

**Comment by Carol-code2222** [comment]
> > > > It depends. If your container is setup in a way that nothing from the host leaks in the container it can work.
> > > 
> > > 
> > > For example, what on the host leaks into the container that causes the CRIU fail to checkpoint and restore processes from outside the container?
> > 
> > 
> > What people usually report is about mount points. You have to mark them as external in CRIU and then it should work.
> > What I also did not mention is that you need a privileged container. So you need to start your container, depending on your container engine, with something like `--privileged`.

Thank you very much for your patient answer.
