### ISSUE TITLE
Unable to open fd=1 id=0xab when restoring

### ISSUE THREAD

**Issue by StephenShiSiyuan** [checkpoint-restore/criu#2085]
Hello, I tried to C/R a process attached with multiple sockets.
Checkpointing succeeded, but restore failed.

**Steps to reproduce the issue:**
1. Dump the process with the following command:
sudo criu dump -D images -o dump.log -v4 --external unix[5286540] --external unix[5281049] --external unix[5281050] --external unix[5274269] --external unix[5261880] -t 2668152 --shell-job
2. Restore the process with the following command:
sudo criu restore -d -D images -o restore.log --pidfile restore.pid -v4 --external unix[5286540] --external unix[5281049] --external unix[5281050] --external unix[5274269] --external unix[5261880]  --shell-job

**Describe the results you received:**
Restore Failed log:
(00.005589) 2668152: Restoring resources
(00.005598) 2668152: Opening fdinfo-s
(00.005610) 2668152:            Create fd for 0
(00.005614) 2668152: unix: Opening standalone (stage 0 id 0xab ino 5286540 peer 5189592)
(00.005617) 2668152: Error (criu/sk-unix.c:1911): unix: External socket found in image. Consider using the --ext-unix-sk option to allow restoring it.
(00.005621) 2668152: Error (criu/files.c:1213): Unable to open fd=1 id=0xab

**Describe the results you expected:**
Restore succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
[dump.log](https://github.com/checkpoint-restore/criu/files/10753693/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/10753694/restore.log)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.17.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Warn  (criu/kerndat.c:1079): Can't load /run/criu.kdat
Error (criu/util.c:641): exited, status=4
Error (criu/util.c:641): exited, status=4
Warn  (criu/proc_parse.c:930): Write 4294967295 to /proc/self/loginuid failed: Operation not permitted
Warn  (criu/net.c:3427): Unable to get tun network namespace
Warn  (criu/sk-unix.c:224): unix: Unable to open a socket file: Operation not permitted
Error (criu/net.c:3711): Unable create a network namespace: Operation not permitted
Warn  (criu/net.c:3767): NSID isn't reported for network links
Warn  (criu/net.c:3427): Unable to get socket network namespace
Error (criu/net.c:1246): Unexpected error: -1(Operation not permitted)
Error (criu/kerndat.c:1414): Unable create a network namespace: Operation not permitted
Error (criu/util.c:1411): Can't wait or bad status: errno=0, status=256
Error (criu/kerndat.c:1645): kerndat_has_nftables_concat failed when initializing kerndat.
Error (criu/crtools.c:260): Could not initialize kernel features detection.
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
Looking at your logs that (FD=1) seems to be the FD which had the socket to `/run/systemd/journal/stdout` open. Did you try the flag `--ext-unix-sk` as suggested by the error message. Maybe you should also mark that socket as external as you did with the other sockets.


I see from your logs you are trying to checkpoint `gnome-calculator`. Graphical applications are usually not suited very well for checkpoint and restore. Any reasons why you are trying to do this? Just for testing? Maybe use something else for testing.

**Comment by StephenShiSiyuan** [comment]
Hi Adrianreber,

Thanks for reply.
`Calculator` application is just a test. 
The main purpose is trying to checkpoint/restore a big game application, to see if this can speed up its launch time.
Any suggestion for this use case? Can CRIU achieve it?

Thanks.

BRs

**Comment by StephenShiSiyuan** [comment]
> Did you try the flag --ext-unix-sk as suggested by the error message.

Sorry I didn't try it yesterday, I misunderstood this option is deprecated.
I just tried with --ext-unix-sk, the process was successfully restored(I can see its pid with ps).
But unfortunately its UI didn't recover..
Is it just as you said, not suitable for graphical app?

Restore Log attached here.
[
[restore.log](https://github.com/checkpoint-restore/criu/files/10762703/restore.log)
](url)

**Comment by adrianreber** [comment]
> Is it just as you said, not suitable for graphical app?

That is not easy to answer. It can work, but usually a graphical application is using the GPU for accelerated graphics output. This usually means there is a state in the GPU and CRIU currently cannot checkpoint the state your application has in the GPU. To have a chance that this works someone would need to write a plugin to handle the GPU state. So, it is probably not impossible from a technical side, but so far no one has done that. At this point I would not expect a graphical application to be usable with CRIU if it uses hardware acceleration in the GPU.

**Comment by StephenShiSiyuan** [comment]
I see, thanks for your explanation.

**Comment by adrianreber** [comment]
Closing. Please re-open if there are any  further questions.
