### ISSUE TITLE
Can criu be used to c/r the ’containerd-shim’ process?

### ISSUE THREAD

**Issue by Carol-code2222** [checkpoint-restore/criu#2086]
I'm making an attempt:

Start a Docker container:
[root@localhost ~]# docker run -d --name looper test /bin/sh -c 'i=0; while true; do echo (expr $i + 1); sleep 1; done'

I'm trying to use criu to dump the process 'containerd-shim'

[root@localhost tmp]# ps -ef | grep while
root      399002  **398984**  0 Feb17 ?        00:00:00 /bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done
root     1452408    2334  0 17:04 pts/0    00:00:00 grep --color=auto while

[root@localhost tmp]# ps -ef | grep 398984
root      **398984**    2667  0 Feb17 ?        00:00:07 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/2e1deb44e00349759690efa26cf3df0a7f5db243cc1713abc57e203999c91686 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      399002  **398984**  0 Feb17 ?        00:00:00 /bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done

[root@localhost tmp]# criu dump -D imgdir/ -j -t **398984** -v4 -o dump.log

An error occurred: Error (criu/namespaces.c:463): Can't dump nested pid namespace for **398984**

Is this error normal? Is there a solution?

**Comment by adrianreber** [comment]
> Is this error normal?  Is there a solution?

No, nested namespaces is something CRIU currently cannot handle.

> I'm trying to use criu to dump the process 'containerd-shim'

Why are you trying to do that?

**Comment by Carol-code2222** [comment]
> > Is this error normal?  Is there a solution?
> 
> No, nested namespaces is something CRIU currently cannot handle.
> 
> > I'm trying to use criu to dump the process 'containerd-shim'
> 
> Why are you trying to do that?

I want to dump all processes in the container by dumping the parent process.

Currently, there are many types of containers, such as lxc, podman, docker, and apptainer. Each type of container uses different commands to invoke the criu. The criu needs to adapt to each type of container, which is troublesome.

If all containers comply with the OCI runtime (runc) standard, can the criu dump and restore the processes in the container in a unified manner from outside container?

**Comment by adrianreber** [comment]
> > > Is this error normal?  Is there a solution?
> > 
> > 
> > No, nested namespaces is something CRIU currently cannot handle.
> > > I'm trying to use criu to dump the process 'containerd-shim'
> > 
> > 
> > Why are you trying to do that?
> 
> I want to dump all processes in the container by dumping the parent process.

The process `containerd-shim` is not part of the container. You have to select the PID 1 in the container's PID namespace.

> Currently, there are many types of containers, such as lxc, podman, docker, and apptainer. Each type of container uses different commands to invoke the criu. The criu needs to adapt to each type of container, which is troublesome.

I think it makes more sense that each container runtime or engine implements checkpoint/restore themselves as each container is configured differently and the container runtime or engine has all the necessary information to checkpoint the processes in the container.

> If all containers comply with the OCI runtime (runc) standard, can the criu dump and restore the processes in the container in a unified manner from outside container?

For me it feels like you are comparing things in your list which cannot be compared easily. lxc, from my point of view, is more like a container runtime like runc, crun or youki, but independent of OCI. Podman and docker are using runc, crun or youki. runc, crun and youki are using CRIU to checkpoint the container. Podman and docker do not really call CRIU themselves. I think Apptainer is something completely different. Not sure if it uses OCI runtimes at all.

So, back to the questions "Why are you trying to do that". Most container runtimes already have CRIU support implemented and higher level container engines like Podman, LXD, CRI-O are using the support in the corresponding runtimes.
