### ISSUE TITLE
A few questions about container live migration

### ISSUE THREAD

**Issue by Carol-code2222** [checkpoint-restore/criu#2087]
I'm trying a live migration of docker containers, referring to https://criu.org/Docker.
After I run the command:"docker checkpoint create looper ck1" to dump the process in the container, some *.img files generated by criu exist in the directory: /var/lib/docker/containers/$containerID/checkpoints/ck1/, no dump log exists. On the other hand,, when I run the command:"docker start --checkpoint ck1 looper" to restore the process, A restore.log file is stored in the directory：/var/lib/containerd/io.containerd.runtime.v1.linux/moby/$containerID/.

I want to know: 
1. How to record the dump process log? 
2. Where is the restore.log file generated? I cannot find the "-v4 -o restore.log" parameter when the criu command is invoked in the source code of docker-cli, moby, and containerd. 
3. If I want to add some other criu parameters, how can I do it during container live migration?

**Comment by adrianreber** [comment]
First of all, this is a question for the container engine you are using and not for CRIU. But I still think we can help you.

> 1. How to record the dump process log?

If you try Podman there is a special command line option just for this:
```
$  podman container checkpoint -h | grep keep
  -k, --keep                  Keep all temporary checkpoint files
```

For other container engines you have to talk to them.

>  2. Where is the restore.log file generated? I cannot find the "-v4 -o restore.log" parameter when the criu command is invoked in the source code of docker-cli, moby, and containerd.

Container engines do not directly call CRIU they talk to container runtimes like runc, crun or youki (for example). These container runtimes usually do not invoke CRIU with parameters but they use CRIU's RPC interface. So grepping for command line parameters will not work.

> 3. If I want to add some other criu parameters, how can I do it during container live migration?

Either you have to adapt code in the container engine and container runtime or use CRIU's configuration file: https://criu.org/Configuration_files

**Comment by Carol-code2222** [comment]
> First of all, this is a question for the container engine you are using and not for CRIU. But I still think we can help you.
> 
> > 1. How to record the dump process log?
> 
> If you try Podman there is a special command line option just for this:
> 
> ```
> $  podman container checkpoint -h | grep keep
>   -k, --keep                  Keep all temporary checkpoint files
> ```
> 
> For other container engines you have to talk to them.
> 
> > 2. Where is the restore.log file generated? I cannot find the "-v4 -o restore.log" parameter when the criu command is invoked in the source code of docker-cli, moby, and containerd.
> 
> Container engines do not directly call CRIU they talk to container runtimes like runc, crun or youki (for example). These container runtimes usually do not invoke CRIU with parameters but they use CRIU's RPC interface. So grepping for command line parameters will not work.
> 
> > 3. If I want to add some other criu parameters, how can I do it during container live migration?
> 
> Either you have to adapt code in the container engine and container runtime or use CRIU's configuration file: https://criu.org/Configuration_files

Thank you very much for your patient answer.
