### ISSUE TITLE
Restoring a checkpoint in docker hangs

### ISSUE THREAD

**Issue by MFAshby** [checkpoint-restore/criu#2093]
**Description**
Following the example on https://criu.org/Docker, the `docker start --checkpoint checkpoint1 looper` command never returns, it just hangs. 

**Steps to reproduce the issue:**
1. `docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
2. `docker checkpoint create looper checkpoint1`
3. `docker start --checkpoint checkpoint1 looper`

**Describe the results you received:**
The 'docker start' command never returns, and produces no output on the terminal.

**Describe the results you expected:**
The container 'looper' restarts from the checkpoint.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
# criu --version
Version: 3.16.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
# criu check --all
Looks good.
```

</p>
</details>

**Additional environment details:**
Running on Ubuntu in a virtual machine: 
```
# uname -a
Linux martin-work-vm 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/criu/runc.conf
file-locks
tcp-established
```

**Comment by adrianreber** [comment]
Can you try a newer version of CRIU. Ubuntu ships a completely broken version.

There is a PPA from us and there is also something on open build service from us.

Or try something that is not Ubuntu in your VM.

**Comment by MFAshby** [comment]
Thanks so much @adrianreber @rst0git , installing criu from PPA worked (used the launchpad.net one)

docker info output in case it's still interesting
```
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 63
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-60-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 19.08GiB
 Name: martin-work-vm
 ID: 308a0d7a-873f-4fc1-87ee-8747a7cf4281
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
