### ISSUE TITLE
criu check fails in kernel 6.3.0-rc4+ qemu emulator

### ISSUE THREAD

**Issue by warusadura** [checkpoint-restore/criu#2148]
**Description**

I'm trying to test out `criu` features in a latest kernel release emulated through qemu using [virtme](https://github.com/amluto/virtme). I have already included all the `config` options listed [here](https://criu.org/Linux_kernel) in my `.config`. Still, the `./criu/criu check --all` fails with the following errors,

**Describe the results you received:**
```
./criu/criu check --all
Error (criu/util.c:643): exited, status=4
Error (criu/util.c:643): exited, status=4
Error: Could not process rule: Operation not supported
create table inet CRIU
^^^^^^^^^^^^^^^^^^^^^^^
Error (criu/kerndat.c:1508): Can't create nftables table
Error (criu/util.c:1413): Can't wait or bad status: errno=0, status=256
Error (criu/kerndat.c:1632): kerndat_has_nftables_concat failed when initializing kerndat.
Error (criu/crtools.c:263): Could not initialize kernel features detection.
```

**Additional information you deem important (e.g. issue happens only occasionally):**
```
uname -r
6.3.0-rc4+
```
kernel [.config](https://paste.opensuse.org/pastes/64dafcf0af29)

Can you please let me know the reason behind these errors and how can I resolve them.
Thanks!

**Comment by adrianreber** [comment]
Your kernel configuration does not seem to have `NF_TABLES` enabled but you built CRIU with nftables support. Either disable nftables support in CRIU or enable it in the kernel.

**Comment by adrianreber** [comment]
Again something is missing in your kernel.

**Comment by warusadura** [comment]
@adrianreber yeah I think so too :)

**Comment by warusadura** [comment]
@adrianreber by any chance do you know/have a `qemu` friendly kernel .config that works with CRIU?

**Comment by adrianreber** [comment]
I would just be using the one from my current distribution.

**Comment by warusadura** [comment]
I see, thanks!
