### ISSUE TITLE
criu_check() failing with returning -52

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2157]
// Added all required header files
int main()
{
  int ret;
  int  fd = open("dump",O_DIRECTORY);

ret = criu_init_opts(); // Output : return =0

ret = criu_set_service_binary("criu") ; // Output : return =0

ret = criu_get_version();  // Output : return =31500

**ret = criu_check(); // output : return = -52**

}

I could see the issue from error code -52 is EBADE(RPC has returned fail)

**Note**:
In CLI, check is successful.
criu check - looks good
criu check  --all - looks good

Any help on this is appreciated.
Thanks

**Comment by adrianreber** [comment]
Can you checkpoint a process using `criu_dump()`? I am not sure `criu_check()` really works via RPC.

**Comment by indusai99** [comment]
I have checked with criu_dump() also, I am seeing same issue 

steps:
criu_set_images_dir-fd(fd);
criu_set_leave_running(true);
criu_set_log_level(4);
criu_set_log_file("dump.log")
ret = criu_dump(); // output = -52

**Comment by indusai99** [comment]
I won't be able to share logs due to some reasons. But i could see below error in dump logs
`Error (criu/lsm.c:90): Invalid selinux context kernel `

**Comment by adrianreber** [comment]
Without a full log it is hard to tell, sorry.

**Comment by avagin** [comment]
> Error (criu/lsm.c:90): Invalid selinux context kernel 

```
pr_err("Invalid selinux context %s\n", (char *)ctx);
```

We expect to see something like unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023

**Comment by adrianreber** [comment]
Right, I think we fixed something like this at some point. So, this depends on the CRIU version.

**Comment by avagin** [comment]
https://github.com/checkpoint-restore/criu/issues/1402

**Comment by adrianreber** [comment]
Nice. Which kernel are you using? Are you building CRIU yourself?

You could also build CRIU without selinux support or install the correct selinux policies on your system. Both should work.

**Comment by indusai99** [comment]
Yes , got it 
Thanks @adrianreber
