### ISSUE TITLE
CRIU(Podman) iterative migration not working

### ISSUE THREAD

**Issue by liang995** [checkpoint-restore/criu#2166]
**Description**

I am running on Ubuntu 20.04 vm with CRIU 3.16.1 version and Podman 3.4.4. I try to create checkpoint for a infinite number loop output container on VM, move it to another VM and restore it. When I hit the checkpoint step it throws and error

**Steps to reproduce the issue:**
1. Run sudo podman run -d --name looper busybox /bin/sh -c          'i=0; while true; do echo \$i; i=$(expr \$i + 1); sleep 30; done'
2. Create checkpoint: sudo podman container checkpoint looper
3. Restore checkpoint

**Describe the results you received:**
<img width="856" alt="image" src="https://user-images.githubusercontent.com/94180038/234650456-fb081cfa-5e54-406d-b409-d4180f8b096f.png">

**Describe the results you expected:**
Being able to restore the VM after the operations

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
No output as step not achieved here.
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>
<img width="269" alt="image" src="https://user-images.githubusercontent.com/94180038/234652062-227c1182-fc2d-44c1-996d-b9963b31a1e1.png">

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

<img width="373" alt="image" src="https://user-images.githubusercontent.com/94180038/234652232-b4e0c8df-7224-43f6-94e0-d4dc1efc4bda.png">

</p>
</details>

**Additional environment details:**
<img width="854" alt="image" src="https://user-images.githubusercontent.com/94180038/234651504-e941e485-58ff-47a1-8c0e-f798ac709e87.png">

**Comment by adrianreber** [comment]
This is an installation problem. The version of crun you are using is compiled without criu support. You need to talk to Ubuntu and have them fix it. From past experience I would not expect them to fix it.

You can try to switch the container runtime fro crun to runc. That should work. Podman defaults to crun but also supports runc.
