### ISSUE TITLE
openface

### ISSUE THREAD

**Issue by zhangrjcsu** [checkpoint-restore/criu#2169]
**Description**

Can CRIU support hot migration of openface image cropping?

**Comment by adrianreber** [comment]
What is openface image cropping?

**Comment by zhangrjcsu** [comment]
OpenFace image cropping is a technique used in computer vision and facial recognition systems to extract the face from an image and crop it for further processing.

**Comment by zhangrjcsu** [comment]
We want to migrate it by using docker and CRIU

**Comment by adrianreber** [comment]
Unfortunately that doesn't really help me.

It probably works if it does not require a GPU.

Did you try it already?

**Comment by zhangrjcsu** [comment]
I have tried it, but the result of hot migration is not as expected.

It does not require a GPU.
