### ISSUE TITLE
Does `criu dump` always kill the process that is being checkpointed ?

### ISSUE THREAD

**Issue by thcodr** [checkpoint-restore/criu#2172]
**Description**

I have installed `criu-3.17.1` on Fedora 38 and then I followed the simple example in (https://criu.org/Simple_loop)

It worked great (i.e I was able to dump and restore) but I also noticed that `criu dump -t 2221 -vvv -o dump.log` kills `test.sh`.
Is it expected ? Is there a way to checkpoint a process without killing it ?

**Comment by adrianreber** [comment]
Sure. Have a look at the man page or at `criu --help`:
```
  -R|--leave-running    leave tasks in running state after checkpoint
```

**Comment by thcodr** [comment]
It worked. Thanks @adrianreber !
