### ISSUE TITLE
Can't do criu dump when using shared memory in process

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2173]
I have used sysvipc object that is **shared memory** in my current process. I am trying to dump this process. But it is failing with an issue of
Task @XXXX with SYSVIPC shmem map @XXXXXXXXXXXX doesn't live in IPC ns

**Steps to reproduce the issue:**
1. Get the shared memory using shmget
2.Attach shared memory to current process using shmat
3.Write some data in shared memory 
4. Print some values 
5. Do criu dump - failing

If I am detaching shared memory, criu dump is successful. I guess, if we detach it, current process doesn't aware of shared memory used. 

From criu official page, I seen like we need to dump entire namespace if we use any Ipc objects (https://criu.org/What_cannot_be_checkpointed#:~:text=When%20a%20busy%20filesystem%20is,unless%20the%20file%20is%20closed.)  (SysVIPC memory segment w/o IPC namespace) 
Is there any specific step or command I need to add to dump entire namespace? 

Note: I am using criu 3.15 version
Any help can be appreciated, Thanks.

**Comment by adrianreber** [comment]
If you start you process in an IPC namespace you should be able to checkpoint it. Have a look at `unshare` to see how to create an IPC namespace.

**Comment by indusai99** [comment]
Thanks @adrianreber, this works.

**Comment by adrianreber** [comment]
Not entirely sure, but if you use any IPC you need to checkpoint all involved processes or you will see inconsistencies.

I do not think I understand your example correctly, but for any IPC, all processes should be dumped at the same time.

**Comment by indusai99** [comment]
When using shared memory, I have dumped the entire namespace. But before restoring, I have written to the same shared memory segment from different process. Now when I restored the process and checked shared memory. I could see the Value I have written after the dump instead of the value before dump.
Eg:
1. From process 1, Write data "Hello, from dump process P1" to shared memory segment S1
2. Dump process P1 
3. From process2, write data "Hello, from normal process P2" to same sh mem segment S1
4. Restore P1
5.Print Sh mem segment value
   Actual: Hello, from normal process P2
   Expected: Hello, from dump process P1
As per criu, which one should shmem segment should print (is it actual or expected)?
I hope this example cleared my query.

**Comment by 0x7f454c46** [comment]
I'd expect that it should fail to restore the process if the same shmem id exists in the ipc namespace:
```
	id = shmget(shm->desc->key, shm->size, hugetlb_flag | shm->desc->mode | IPC_CREAT | IPC_EXCL);
	if (id == -1) {
		pr_perror("Failed to create shm set");
		return -errno;
	}
```
Note `IPC_EXCL`. Not sure what goes on in your use-case.

**Comment by adrianreber** [comment]
> * From process 1, Write data "Hello, from dump process P1" to shared memory segment S1
> 
> * Dump process P1
> 
> * From process2, write data "Hello, from normal process P2" to same sh mem segment S1
> 
> * Restore P1
> 
> * Read Sh mem segment value
>   Actual Output: Hello, from normal process P2
>   Expected Output: Hello, from dump process P1

This sounds like your are only checkpointing P1? Are you also checkpointing P2?

**Comment by indusai99** [comment]
> > * From process 1, Write data "Hello, from dump process P1" to shared memory segment S1
> > * Dump process P1
> > * From process2, write data "Hello, from normal process P2" to same sh mem segment S1
> > * Restore P1
> > * Read Sh mem segment value
> >   Actual Output: Hello, from normal process P2
> >   Expected Output: Hello, from dump process P1
> 
> This sounds like your are only checkpointing P1? Are you also checkpointing P2?

yes, I am checkpointing only P1.

**Comment by indusai99** [comment]
> I'd expect that it should fail to restore the process if the same shmem id exists in the ipc namespace:
> 
> ```
> 	id = shmget(shm->desc->key, shm->size, hugetlb_flag | shm->desc->mode | IPC_CREAT | IPC_EXCL);
> 	if (id == -1) {
> 		pr_perror("Failed to create shm set");
> 		return -errno;
> 	}
> ```
> 
> Note `IPC_EXCL`. Not sure what goes on in your use-case.

I didn't get any error. Restore is passed.
I want to check criu handling for shared memory

**Comment by adrianreber** [comment]
Please share your test code.

I think what you are trying to do is not really doable. You have to checkpoint all processes in your IPC namespace at the same time (as already mentioned). You will get inconsistencies if you only one process part of the IPC.

But @0x7f454c46 is right, if your setup of the shared memory is correct CRIU should not be able to restore it.

Please share the source code of your test programs and please also list exactly what commands you use to checkpoint and restore. Please include also all namespace setup you do.
