### ISSUE TITLE
Criu restore not working as expected when using shared memory

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2176]
@adrianreber , As my query doesn't belong to issue https://github.com/checkpoint-restore/criu/issues/2173, I created new one. Here I have provided all my test code and commands I used.  Please have a look.

test files: [criu_sm.zip](https://github.com/checkpoint-restore/criu/files/11461408/criu_sm.zip) 

1. Enter in new ipc namespace from command line using "unshare -i"
2. start the dumpP1 process(compiled using gcc and run) in the above namespace and run criu dump command in another terminal (outside of namespace)
    Dump command: criu dump -t PID -v4 -R --shell-job --ext-unix-sk
4. After dump succesful, execute execP2.c inside namespace once dumpP1 completed.
5. Now execute restore_dumped_process_P1.c in the same namespace to restore dumped namespace.
     Expected output read from shared memory after restore - Hi, how are you from main - P1
     Actual Output read from shared memory after restore - Hi, how are you from exec - P2

**Comment by indusai99** [comment]
As I am using criu 3.15, I think criu-ns is not supported in my machine. (I could see criu-ns is implemented in version 3.16)
So I will try by using --external during checkpoint and inheritfd during restore

**Comment by adrianreber** [comment]
Not criu-ns. **join-ns**

**Comment by indusai99** [comment]
I have used below command to restore.
criu restore -D logs -v4 -j --joins-ns ipc:1
But I am facing below issue

` Error (criu/ipc_ns.c:823): Failed to create shm set: File exists
Error (criu/ipc_ns.c:884): Failed to prepare shm segment
Error (criu/cr-restore.c:2483): Restoring FA`

**Comment by adrianreber** [comment]
Now you get the error you should get. As mentioned a couple of times. You need to checkpoint and restore all processes of the IPC namespaces at the same time.

**Comment by indusai99** [comment]
Yes, I got same error as @0x7f454c46 expected.
I understand now. As I am trying to restore to same ipc namespace, its throwing error as we have already existing shared memory segment in that namespace. So its failing to create same during restoring.(Failed to create shm set: File exists). What can be the solution for this?


> Now you get the error you should get. As mentioned a couple of times. You need to checkpoint and restore all processes of the IPC namespaces at the same time.

 Here I am dumping all the processes in the namespace (entire namespace). I don't have any other processes to dump. But can you please say how this point relates to error I am facing?

**Comment by rst0git** [comment]
> What can be the solution for this?

@indusai99 Have you tried to run the application in a container? Then, you should be able to checkpoint/restore the whole container (using Podman, Docker, etc.).

**Comment by indusai99** [comment]
No @rst0git . I haven't run inside this application inside container.
So if we want to use shared memory in multi process environment, Do we must run application inside container only?

**Comment by adrianreber** [comment]
> So if we want to use shared memory in multi process environment, Do we must run application inside container only?

No, as told multiple times, you need to checkpoint all processes in the ipc namespace at the same time.

A container helps you to do it if you do not want to manage it yourself.

You are not telling us what you want to do and it seems you are trying things which are not possible.

**Comment by indusai99** [comment]
Yes @adrianreber, I understand what you are trying to say and issue is resolved now
Thanks
