### ISSUE TITLE
about build for cross-compiling aarch64

### ISSUE THREAD

**Issue by TonyLiangSZ** [checkpoint-restore/criu#2177]
Hello team:
The following errors still occur when I compile the aarch64 project after installing the this patch.[aarch64-cross-build.patch](https://gist.github.com/shrkamat/ee9cbc8f3175c3df5bc3bcdcf8c028e9#file-aarch64-cross-build-patch)
`In file included from compel/plugins/std/infect.c:14:
compel/plugins/std/infect.c: In function ‘fini’:
compel/include/uapi/compel/asm/sigframe.h:74:94: error: ‘mcontext_t’ {aka ‘struct <anonymous>’} has no member named ‘pc’
   74 | #define RT_SIGFRAME_REGIP(rt_sigframe)      ((long unsigned int)(rt_sigframe)->uc.uc_mcontext.pc)
      |                                                                                              ^
compel/plugins/std/infect.c:10:53: note: in expansion of macro ‘RT_SIGFRAME_REGIP’
   10 | #define pr_debug(fmt, ...) print_on_level(4, fmt, ##__VA_ARGS__)
      |                                                     ^~~~~~~~~~~
compel/plugins/std/infect.c:94:2: note: in expansion of macro ‘pr_debug’
   94 |  pr_debug("%ld: new_sp=%lx ip %lx\n", sys_gettid(), new_sp, RT_SIGFRAME_REGIP(sigframe));
      |  ^~~~~~~~
make[1]: *** [/home/tony/tony/criu-criu-dev/deps/criu-aarch64/scripts/nmk/scripts/build.mk:215: compel/plugins/std/infect.o] Error 1
make: *** [Makefile.compel:56: compel/plugins/std.lib.a] Error 2
`

I can't fix this. I wonder if anyone can help with that.Thank you for your efforts

My compile command is: **make ARCH=aarch64**
Compile environment:**Linux ubuntu 5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by adrianreber** [comment]
We are cross compiling CRIU in CI all the time: https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/build/Dockerfile.stable-cross.tmpl

So we know it works for many target platforms. Does that file help you.

**Comment by TonyLiangSZ** [comment]
Glad you answered so quickly, as you can see Dockerfile.aarch64-cross I have added. But my problem is still there. My modification is as follows

diff --git a/scripts/build/Dockerfile.aarch64-cross b/scripts/build/Dockerfile.aarch64-cross
new file mode 100644
index 00000000..e0d033d5
--- /dev/null
+++ b/scripts/build/Dockerfile.aarch64-cross
@@ -0,0 +1,44 @@
+FROM dockcross/base:latest
+
+# Add the cross compiler sources
+RUN echo "deb http://ftp.us.debian.org/debian/ jessie main" >> /etc/apt/sources.list && \
+  dpkg --add-architecture arm64 && \
+  apt-get install emdebian-archive-keyring
+
+RUN apt-get update && apt-get install -y \
+	crossbuild-essential-arm64	\
+	libbz2-dev:arm64		\
+	libexpat1-dev:arm64		\
+	ncurses-dev:arm64		\
+	libssl-dev:arm64		\
+	protobuf-c-compiler		\
+	protobuf-compiler		\
+	python-protobuf			\
+	libnl-3-dev:arm64		\
+	libprotobuf-dev:arm64		\
+	libnet-dev:arm64		\
+	libprotobuf-c-dev:arm64		\
+	libcap-dev:arm64		\
+	libaio-dev:arm64		\
+	libnl-route-3-dev:arm64
+
+ENV CROSS_TRIPLE=aarch64-linux-gnu
+ENV CROSS_COMPILE=${CROSS_TRIPLE}-				\
+	CROSS_ROOT=/usr/${CROSS_TRIPLE}				\
+	AS=/usr/bin/${CROSS_TRIPLE}-as				\
+	AR=/usr/bin/${CROSS_TRIPLE}-ar				\
+	CC=/usr/bin/${CROSS_TRIPLE}-gcc				\
+	CPP=/usr/bin/${CROSS_TRIPLE}-cpp			\
+	CXX=/usr/bin/${CROSS_TRIPLE}-g++			\
+	LD=/usr/bin/${CROSS_TRIPLE}-ld				\
+	FC=/usr/bin/${CROSS_TRIPLE}-gfortran
+
+ENV PATH="${PATH}:${CROSS_ROOT}/bin"				\
+	PKG_CONFIG_PATH=/usr/lib/${CROSS_TRIPLE}/pkgconfig	\
+	ARCH=aarch64						\
+	SUBARCH=armv8
+
+COPY . /criu
+WORKDIR /criu
+
+RUN	make mrproper && date && make zdtm V=1 && date

**Comment by adrianreber** [comment]
Please take a look at our CI setup and try to use those steps.

**Comment by TonyLiangSZ** [comment]
OKay, let me read over the CI steps again
