### ISSUE TITLE
Checkpoint error

### ISSUE THREAD

**Issue by zhangrjcsu** [checkpoint-restore/criu#2179]
**Description**
Error response from daemon: Cannot checkpoint container 307baf18593a: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/307baf18593ac70e0361f3a407827b2dbda19d110ea52d46c5f86672b0f94763/checkpoints/checkpoint-openface/criu.work/dump.log\n"

**Comment by adrianreber** [comment]
That is an error message from docker. We cannot really help you with that. But if you share the log file mentioned in the error message we might be able to help you.

**Comment by adrianreber** [comment]
Can you share how you started the container? And all commands you have been using.

**Comment by zhangrjcsu** [comment]
sudo docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash

 ./openface/util/aligned-dlib.py ./data/training-images align outerEyesAndNose ./aligned-images/ --size 96

docker checkpoint create container-id checkpoint1

**Comment by zhangrjcsu** [comment]
OK，thank you.I will try it

**Comment by zhangrjcsu** [comment]
The error message I received after terminating the container process before the checkpoint is the same as before.

**Comment by adrianreber** [comment]
Are you starting the container differently now? How? Please always share what you do.

**Comment by avagin** [comment]
You need to start it without the -t argument.
