### ISSUE TITLE
criu dump/restore process with network namespace and veth pair

### ISSUE THREAD

**Issue by renjinxi** [checkpoint-restore/criu#2180]
**Description**

I created some network namespace with veth pair, restore failed when joining network namespace from one to another. 

```bash
[root@localhost ~]# criu -V
Version: 3.17
[root@localhost ~]# criu check --all
Warn  (criu/cr-check.c:1334): Nftables based locking requires libnftables and set concatenations support
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
[root@localhost ~]# uname -a
Linux localhost.localdomain 5.14.0-305.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 27 11:32:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
<details><summary>create network namespace and veth pair</summary>

```bash
[root@localhost ~]# ip netns add n2
[root@localhost ~]# ip netns add n3
[root@localhost ~]# ip link add veth_to_n2 type veth peer veth0 netns n2
[root@localhost ~]# ip link add veth_to_n3 type veth peer veth0 netns n3
[root@localhost ~]# ip link set veth_to_n2 master br0
[root@localhost ~]# ip link set veth_to_n3 master br0
[root@localhost ~]# ip link set veth_to_n2 up
[root@localhost ~]# ip link set veth_to_n3 up
[root@localhost ~]# ip netns exec n2 ip link set lo up
[root@localhost ~]# ip netns exec n2 ip link set veth0 up
[root@localhost ~]# ip netns exec n2 ip address add 172.253.1.2/24 dev veth0
[root@localhost ~]# ip netns exec n3 ip link set lo up
[root@localhost ~]# ip netns exec n3 ip link set veth0 up
[root@localhost ~]# ip netns exec n3 ip address add 172.253.1.3/24 dev veth0
[root@localhost ~]# ping -c 1 172.253.1.2
PING 172.253.1.2 (172.253.1.2) 56(84) 比特的数据。
64 比特，来自 172.253.1.2: icmp_seq=1 ttl=64 时间=0.035 毫秒

--- 172.253.1.2 ping 统计 ---
已发送 1 个包， 已接收 1 个包, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.035/0.035/0.035/0.000 ms
[root@localhost ~]# ping -c 1 172.253.1.3
PING 172.253.1.3 (172.253.1.3) 56(84) 比特的数据。
64 比特，来自 172.253.1.3: icmp_seq=1 ttl=64 时间=0.040 毫秒

--- 172.253.1.3 ping 统计 ---
已发送 1 个包， 已接收 1 个包, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.040/0.040/0.040/0.000 ms
```
</details>

**Steps to reproduce the issue:**
1.  run server (a flask server )
<details><summary>server.py</summary>

```python 
from daemon import DaemonContext
from flask import Flask

app = Flask(__name__)

times = 0

@app.route('/')
def hello_world():
    global times
    times += 1
    return f'{times}: Hello from Flask!\n'

if __name__ == '__main__':
    with DaemonContext():
        app.run(host='0.0.0.0', port=8181)


```

</details>

```bash
[root@localhost ~]# python server.py
[root@localhost ~]# curl http://127.0.0.1:8181/
1: Hello from Flask!
```

2. first dump 

```bash
[root@localhost ~]# criu dump  -t 257890 --shell-job -v1  --images-dir /tmp/criu_imgs/0 --leave-stopped --tcp-close
[root@localhost ~]# kill -9 257890
```

3. first restore join ns 

```bash
[root@localhost ~]# criu restore -v1 --shell-job --images-dir /tmp/criu_imgs/0 -d --tcp-close --join-ns net:/var/run/netns/n2
[root@localhost ~]# curl http://172.253.1.2:8181/
2: Hello from Flask!
[root@localhost ~]# ping -c 1 172.253.1.2
PING 172.253.1.2 (172.253.1.2) 56(84) 比特的数据。
64 比特，来自 172.253.1.2: icmp_seq=1 ttl=64 时间=0.043 毫秒

--- 172.253.1.2 ping 统计 ---
已发送 1 个包， 已接收 1 个包, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.043/0.043/0.043/0.000 ms
``` 
4.  second dump 

```bash
[root@localhost ~]# criu dump  -t 257890 --shell-job -v4  --images-dir /tmp/criu_imgs/1 --leave-stopped --tcp-close  -o dump.log
[root@localhost ~]# ping -c 1 172.253.1.2
PING 172.253.1.2 (172.253.1.2) 56(84) 比特的数据。

--- 172.253.1.2 ping 统计 ---
已发送 1 个包， 已接收 0 个包, 100% packet loss, time 0ms

```
[dump.log](https://github.com/checkpoint-restore/criu/files/11513992/dump.log)

**ping failed after criu dump（This is not what I wanted ）**

5. second restore

5.1 restore failed 
```bash 
[root@localhost 1]# criu restore -v4 --shell-job --images-dir /tmp/criu_imgs/1 -d --tcp-close  -o restore.log
```
 error msg 
```bash 
(00.001893) 257890: Restoring link veth0 type 2
(00.001896) 257890: Restoring netdev veth0 idx 2
(00.001899) 257890: Restore ll addr (72:../6) for device
(00.001900) 257890: Error (criu/net.c:1462): Unknown peer net namespace
(00.007753) 257890: Error (criu/libnetlink.c:54): -17 reported by netlink: File exists
(00.007760) 257890: Error (criu/net.c:1816): Can't restore link: -17
(00.007820) 257890: Error (criu/util.c:1411): Can't wait or bad status: errno=0, status=65280
(00.007989) Error (criu/cr-restore.c:2536): Restoring FAILED.
```
[restore.log](https://github.com/checkpoint-restore/criu/files/11513995/restore.log)

5.2 restore success when add --external veth...
```bash
[root@localhost 1]# criu restore -v4 --shell-job --images-dir /tmp/criu_imgs/1 -d --tcp-close --external veth[veth0]:veth_to_n2_test@br0
[root@localhost 1]# curl http://172.253.1.2:8181/
3: Hello from Flask!
```
**The dev veth_to_n2 exists, so why should I specify another one**

5.3 restore failed when add --join-ns 
```bash
[root@localhost 1]# criu restore -v4 --shell-job --images-dir /tmp/criu_imgs/1 -d --tcp-close --external veth[veth0]:veth_to_n2_test@br0  --join-ns net:/var/run/netns/n3 -o join_another_net_restore.log

```
error msg
```bash 
(00.001045) 257890: Restoring namespaces 257890 flags 0x40000080
(00.001644) 257890: Try to restore a link 9:2:veth0
(00.001649) 257890: Restoring link veth0 type 2
(00.001653) 257890: Restoring netdev veth0 idx 2
(00.001656) 257890: Restore ll addr (72:../6) for device
(00.001669) 257890: Error (criu/libnetlink.c:54): -95 reported by netlink: Operation not supported
(00.001670) 257890: Error (criu/net.c:1816): Can't restore link: -95
(00.001758) 257890: Error (criu/util.c:1411): Can't wait or bad status: errno=0, status=65280
(00.001863) Error (criu/cr-restore.c:2536): Restoring FAILED.
```
[join_another_net_restore.log](https://github.com/checkpoint-restore/criu/files/11513997/join_another_net_restore.log)

**Describe the results you received:**
- [ ] Unable to communicate with network namespace after criu dump 
- [ ] restore failed when I want to criu restore from one network namespace  to another network namespace 

**Describe the results you expected:**
I think network namespace and veth pair should be an external resource. I found this [article](https://criu.org/External_net_namespaces) but it's empty

**I NEED HELP!!!**

**Comment by adrianreber** [comment]
You are asking a lot of questions at the same time.

Starting at your first questions: No ping after second dump. If I remember it correctly CRIU blocks network traffic after checkpointing using iptables. Please check your iptables rules after the second dump. My expectation is that there should be a rule active blocking the traffic. If you remove the corresponding rules the ping should work.

**Comment by renjinxi** [comment]
> You are asking a lot of questions at the same time.
> 
> Starting at your first questions: No ping after second dump. If I remember it correctly CRIU blocks network traffic after checkpointing using iptables. Please check your iptables rules after the second dump. My expectation is that there should be a rule active blocking the traffic. If you remove the corresponding rules the ping should work.

Thank you for your reply, I'm going to try something, I would also like to ask if there is an option that would allow it to have no impact on network namespace, as there could be cases where multiple processes use the same network namespace . This affects the use of other processes

**Comment by adrianreber** [comment]
> > You are asking a lot of questions at the same time.
> > Starting at your first questions: No ping after second dump. If I remember it correctly CRIU blocks network traffic after checkpointing using iptables. Please check your iptables rules after the second dump. My expectation is that there should be a rule active blocking the traffic. If you remove the corresponding rules the ping should work.
> 
> Thank you for your reply, I'm going to try something, I would also like to ask if there is an option that would allow it to have no impact on network namespace, as there could be cases where multiple processes use the same network namespace . This affects the use of other processes

That should work. You can tell CRIU to handle a network namespace as an external resource and it will ignore it during checkpointing (`--external`) and restoring (`--inheritfd`). Podman, for example, uses CRIU that way.

**Comment by renjinxi** [comment]
> inheritfd

![image](https://github.com/checkpoint-restore/criu/assets/48796935/46ab17a5-1502-4d4a-948a-62a86cdfc418)

![image](https://github.com/checkpoint-restore/criu/assets/48796935/006caa44-99e5-4212-bdb5-588026a9b5b7)

I've used this `--externel net`,But I don't know if I'm using the right method. I need to try it again, but There is nothing in this `--inherit-fd` that corresponds to `--external net`


Here's what I tried to do before, but I don't know if `inode` is `/proc/pid/ns/net` or `/var/run/netns/n2`
```bash 
criu dump ... --externel net[inode]: test 
```

**Comment by renjinxi** [comment]
> 

Sorry I Won't be sending any more screenshots

I used `--external` `--inherit-fd` , which could restore from one network namespace  to  another network namespace, but still couldn't communicate after criu dump

**Comment by adrianreber** [comment]
> > 
> 
> Sorry I Won't be sending any more screenshots
> 
> I used `--external` `--inherit-fd` , which could restore from one network namespace to another network namespace, but still couldn't communicate after criu dump

Did you check for iptables rules blocking the communication?

**Comment by renjinxi** [comment]
> > > 
> > 
> > 
> > Sorry I Won't be sending any more screenshots
> > I used `--external` `--inherit-fd` , which could restore from one network namespace to another network namespace, but still couldn't communicate after criu dump
> 
> Did you check for iptables rules blocking the communication?

When I use `--leave-stopped`,  it's blocked( `iptables -L` show CRIU DROP ALL), I use `--leave-running`, It can communicate.

Now my problems have been solved, thank you very much for your help

**Comment by adrianreber** [comment]
> Now my problems have been solved, thank you very much for your help

Good to hear.

There is a reason for the behaviour your are seeing. If the process is stopped during checkpointing CRIU blocks all communication to avoid network connection resets. By blocking all traffic, TCP connections for example, the connection will not be reset so fast, because the network stack cannot not answer there is nothing running on a certain port.. If you later restore the process on the same IP address the iptables rule will be removed and the network communication can continue.

If you keep the process running after checkpointing, CRIU is not blocking the network as the process continues to run and can still communicate without being reset. The assumption is, if you keep the process running you do not want to migrate the process, if you stop it you might want to migrate the process somewhere elese.
