### ISSUE TITLE
How to trace the execution process of CRIU

### ISSUE THREAD

**Issue by zhangrjcsu** [checkpoint-restore/criu#2184]
**How to trace the execution process of CRIU**

****
I would like to see how CRIU implements a hot migration, such as which functions are used in the dump process or how the recovery process is implemented. How do I do this?

**Comment by warusadura** [comment]
I'm also interested in this.

**Comment by avagin** [comment]
* Add log message in the criu code
* https://man7.org/linux/man-pages/man1/strace.1.html
* gdb
