### ISSUE TITLE
Error on restoring customized mysql application via Kubernetes C/R

### ISSUE THREAD

**Issue by varungup90** [checkpoint-restore/criu#2185]
**Description**

We run a customized mysql application internally. Checkpoint and Restore works for open-source mysql. For our internal application, I ran into the issue for FD limit when doing checkpoint, but that issue is fixed following [this](https://github.com/cri-o/cri-o/issues/6936#issuecomment-1553533775) recommendation. After checkpoint, I created an image using buildah (following this [tutorial](https://martinheinz.dev/blog/85)). Now I am trying to restore and getting an error but error message is not descriptive enough. Attached the log file for CRIU.

**Steps to reproduce the issue:**
I am following this [tutorial](https://martinheinz.dev/blog/85) for checkpoint/restore.

**Describe the results you received:**
Able to restore our application

**Describe the results you expected:**
Getting error on restore, attached log files.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore
[criu.log](https://github.com/checkpoint-restore/criu/files/11567750/criu.log)
 logs:</summary>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
root@n209-035-156:~# criu --version
Version: 3.17.1
GitID: v3.17.1-13-g712cdbba0
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
root@n209-035-156:~# criu check --all
Warn  (criu/cr-check.c:1231): clone3() with set_tid not supported
Error (criu/cr-check.c:1273): Time namespaces are not supported
Error (criu/cr-check.c:1283): IFLA_NEW_IFINDEX isn't supported
Warn  (criu/cr-check.c:1305): Pidfd store requires pidfd_getfd syscall which is not supported
Warn  (criu/cr-check.c:1334): Nftables based locking requires libnftables and set concatenations support
Warn  (criu/cr-check.c:804): ptrace(PTRACE_GET_RSEQ_CONFIGURATION) isn't supported. C/R of processes which are using rseq() won't work.
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
The following seems to be the reason for your failure:

```(00.214201)   1581: Error (criu/files-reg.c:2094): File var/log/ndb/lst_log/mysqld.n209-035-156.invalid-user.log.WARNING.001 has bad size 378073 (expect 374776)```

CRIU stops restoring if any open file has a different file size. Restoring a process with open files that have changed are an indication that something is not right and might result in failures in the future. In you case it could mean that CRIU positions the file pointer at the wrong location during restore and existing data in the log file will be overwritten.

The CRI-O code is based on the Podman code and default behaviour in Podman is that the container does not continue running. In CRI-O and Kubernetes the only possibility is to checkpoint a container and keep it running. From the KEP introducing this into Kubernetes it is the only possibility.

The problem you are now hitting is that your application is checkpointed and then continues running and then we collect in CRI-O all the files that have changed. By the time we collect your files the application has changed the log file and the size we put in the checkpoint archive is now larger. So this is a CRI-O not handling checkpointing process correctly.

CRI-O needs to pause the container before checkpointing and let it continue to run just after all files have been collected.

Should be an easy change. Again, this is a CRI-O problem and not a CRIU problem.

**Comment by varungup90** [comment]
@adrianreber Thank you for the reply. Moved the [issue](https://github.com/cri-o/cri-o/issues/6972) to CRI-O repo.
