### ISSUE TITLE
How to change external bind mount point with `--external mnt`

### ISSUE THREAD

**Issue by renjinxi** [checkpoint-restore/criu#2186]
Here's what I did
```bash 
mkdir /bar /foo
mount --bind /bar /root/mnt_a
chroot /root

criu-ns  dump ... --external mnt[/mnt_a]:test
criu-ns restore ... --external mnt[test]:/foo
```
I want to go from `mnt_a -> /bar` to `mnt_a -> /foo` after being restored. But It didn't work

**Comment by adrianreber** [comment]
You should include the error messages you get. Without it is difficult to help.

**Comment by renjinxi** [comment]
> You should include the error messages you get. Without it is difficult to help.

No error messages; dump and restore were successful, But `external mnt` didn't work

```bash 
[root@localhost test]# tree mnt_test
mnt_test
├── a
│   └── a.txt
├── c
│   └── c.txt

[root@localhost test]# mount --bind mnt_test/a mnt_namespace/tmp/mnt_a
[root@localhost test]# chroot mnt_namespace 
root@localhost:/# /root/miniconda3/bin/python tmp/server_test.py

[root@localhost test]# /home/rjx/.local/bin/criu-ns dump --shell-job -t $pid -v4  --images-dir /home/rjx/test/mnt_imgs/server/0 --leave-running --tcp-close --external tty[34824:23]:tty_test --external mnt[/tmp/mnt_a]:a -o dump.log
[root@localhost test]# /home/rjx/.local/bin/criu-ns restore --shell-job -v4  --images-dir /home/rjx/test/mnt_imgs/server/0 --tcp-close  --inherit-fd 'fd[1]:tty[34824:23]' -d --root /home/rjx/test/mnt_namespace --external mnt[a]:/home/rjx/test/mnt_test/c -o restore.log

[root@localhost test]# nsenter -a -t $pid /bin/bash
[root@localhost test]# tree mnt_namespace/tmp/mnt_a
mnt_a
└── a.txt 
```

[dump.log](https://github.com/checkpoint-restore/criu/files/11589920/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/11589921/restore.log)

**Comment by adrianreber** [comment]
I am not sure why you are using `criu-ns`. Is it really necessary? I would just change the bind mount manually. Does that work?

You are not using namespaces in your original process. I think I am still confused what you are trying to achieve.

From my point of view you could just do:

* bind mount
* chroot
* run process
* dump process
* change bind mount
* restore process

That should give you what you want. I think.
