### ISSUE TITLE
criu_coredump missing files

### ISSUE THREAD

**Issue by TahaW863** [checkpoint-restore/criu#2187]
I tried to run the script from this path [criu coredump](https://github.com/checkpoint-restore/criu/blob/criu-dev/coredump/coredump-python3)
But i noticed that it won't work because the [.ignore](https://github.com/checkpoint-restore/criu/blob/criu-dev/lib/py/images/.gitignore) is ignoring these files {magic, pb, etc}. Hence, the needed functions for converting the core dump files won't work. I tested the latest tag v3.18 and older tags with the same issue of circular references. Moreover, missing modules.  
```
# /root/criu-3.18/coredump/coredump-python3 -i ./checkpoint/ -o ./checkpoint/
Traceback (most recent call last):
  File "/root/criu-3.18/coredump/coredump-python3", line 3, in <module>
    import coredump
  File "/root/criu-3.18/coredump/coredump.py", line 5, in <module>
    import criu_coredump
  File "/root/criu-3.18/coredump/criu_coredump/__init__.py", line 1, in <module>
    from .coredump import coredump_generator
  File "/root/criu-3.18/coredump/criu_coredump/coredump.py", line 35, in <module>
    from pycriu import images
  File "/root/criu-3.18/coredump/pycriu/__init__.py", line 3, in <module>
    from . import rpc_pb2 as rpc
ImportError: cannot import name 'rpc_pb2' from partially initialized module 'pycriu' (most likely due to a circular import) (/root/criu-3.18/coredump/pycriu/__init__.py)
```
If you guys have any direction on how to fix it. 
@adrianreber 
I tagged you because i'm following your [tutorial ](https://kubernetes.io/blog/2023/03/10/forensic-container-analysis/#using-gdb-for-further-analysis).

**Comment by adrianreber** [comment]
Did you do `make install` to ensure the necessary Python libraries are at the right place.

**Comment by TahaW863** [comment]
Oops, my bad. I forgot to do that. After ```make``` now the files were generated. I'm currently making a research paper about container checkpoints. I will include the work about checkpoints, the team behind it, and how important It's going to be for memory forensics. Because the research is not talking about how useful these checkpoints. Thanks again.

**Comment by adrianreber** [comment]
Please close the ticket if this is solved. If you have any more questions, I am always happy to help.

**Comment by TahaW863** [comment]
When i execute the core dump python3 script to convert core dumps. It gives me that some files are missing, such as 
/usr/lib/x86_64-linux-gnu/libpcre2-8.so.0.10.1. i was able to get the [files](https://debian.pkgs.org/11/debian-main-arm64/libpcre2-8-0_10.36-2+deb11u1_arm64.deb.html). However, after retrieving the files and running the script. It gives back this error: 
```
$ /home/taha/Desktop/criu/coredump/coredump-python3 
Traceback (most recent call last):
  File "/home/taha/Desktop/criu/coredump/coredump-python3", line 6, in <module>
    coredump.main()
  File "/home/taha/Desktop/criu/coredump/coredump.py", line 39, in main
    coredump(opts)
  File "/home/taha/Desktop/criu/coredump/coredump.py", line 10, in coredump
    cores = generator(os.path.realpath(opts['in']))
  File "/home/taha/Desktop/criu/coredump/criu_coredump/coredump.py", line 176, in __call__
    self.coredumps[pid] = self._gen_coredump(pid)
  File "/home/taha/Desktop/criu/coredump/criu_coredump/coredump.py", line 198, in _gen_coredump
    cd.vmas = self._gen_vmas(pid)
  File "/home/taha/Desktop/criu/coredump/criu_coredump/coredump.py", line 843, in _gen_vmas
    v.data = self._gen_mem_chunk(pid, vma, v.filesz)
  File "/home/taha/Desktop/criu/coredump/criu_coredump/coredump.py", line 693, in _gen_mem_chunk
    fname = next(filter(lambda x: x["id"] == shmid, files))["name"]
StopIteration
```
I tried to solve it, but it seems like the **filter()** function is not returning any items that match the condition x["id"] == shmid, so next() is trying to access an item that doesn't exist. Do you have any suggestion or do you have a container image that have all the needed dependencies because it's killing me lol.

**Comment by adrianreber** [comment]
As the variable is named shmid maybe you are the first to use it on a process with shared memory in a long time. Could be that it just doesn't work and any fix would be welcome.

**Comment by TahaW863** [comment]
Since you might face new shmid like how you described 
I changed the coredump python file to try and catch any error and just move on. it's not the best solution but at least you will be able to see some results. 
I made the following changes, within function:
```
def _gen_mem_chunk(self, pid, vma, size):
---
            fname=""
            try:
              fname = next(filter(lambda x: x["id"] == shmid, files))["name"]
            except StopIteration:
              print(f"No file with id {shmid} found.")
              return b""
---
```
and  function:
```
def _gen_files(self, pid):
---
            try:
              fname = next(filter(lambda x: x["id"] == shmid, files))["name"]
            except StopIteration:
              print(f"No file with id {shmid} found.")
              continue
---
```
Again it "worked", but there will some things missing. I will modify the code later to list out all the missing stuff and let the user now what they have missed.
![image](https://github.com/checkpoint-restore/criu/assets/51216558/788a7e4a-657f-4cf6-8266-152813a8f13d)
