### ISSUE TITLE
Is it possible to change a variable value after dumping at the time of restore

### ISSUE THREAD

**Issue by PSoni8** [checkpoint-restore/criu#2189]
**Description**
Suppose in process P1, a variable initaialize with a=2 and taken dump . In another process P2, I want to restore P1 with changed value of variable a. Is it possible to change a variable value after dumping at the time of restore? How I can do this?

**Comment by PSoni8** [comment]
I am taking about a local variable which was initialize before taking dump in main function of C.

**Comment by adrianreber** [comment]
> I am taking about a local variable which was initialize before taking dump in main function of C.And before restoring it I want to modify its value with new one and then restore it with new value.

As mentioned above this is not possible. Your variable is now some random local variable of your process. CRIU has no knowledge about any internals of your process.

**Comment by PSoni8** [comment]
Is it possible to convert criu image to json, change in image for changing variable value, convert back to image using CRIT and restore the process with modified value of the variable ?

**Comment by adrianreber** [comment]
> Is it possible to convert criu image to json, change in image for changing variable value, convert back to image using CRIT and restore the process with modified value of the variable ?

You can change values exposed in the image files like you mentioned, but CRIU is not aware of single variables. CRIU just writes all memory pages to the image files without knowing any of the actual usage in the process.

If you are able to find the memory location of your variable in the dumped memory pages you should be able to restore it.

CRIU, once again, is not aware how a process uses its internal variables.

**Comment by avagin** [comment]
> If you are able to find the memory location of your variable in the dumped memory pages you should be able to restore it.

If we are talking about local variables, their values in registers or saved on the thread stack.
