### ISSUE TITLE
Error (criu/cr-restore.c:1514): Can't fork for 2158017: File exists

### ISSUE THREAD

**Issue by PSoni8** [checkpoint-restore/criu#2190]
**Description**
Getting issue while restoring.
Code :
[sample.txt](https://github.com/checkpoint-restore/criu/files/11661369/sample.txt)

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**
a is 2
criu dump init return 0
criu service binary return 0
criu dump log file return 0
dump open fxn return 3
criu dump return 0
criu restore init return 0
criu restore service binary return 0
criu restore log file return 0
restore open fxn return 4
criu restore return -52
a is 4
5
6
**Describe the results you expected:**
a is 2
criu dump init return 0
criu service binary return 0
criu dump log file return 0
dump open fxn return 3
criu dump return 0
criu restore init return 0
criu restore service binary return 0
criu restore log file return 0
restore open fxn return 4
criu restore return 0
a is 4
5
6

**Additional information you deem important (e.g. issue happens only occasionally):**
[dump.log](https://github.com/checkpoint-restore/criu/files/11661371/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/11661373/restore.log)

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
[restore.log](https://github.com/checkpoint-restore/criu/files/11661336/restore.log)
[dump.log](https://github.com/checkpoint-restore/criu/files/11661337/dump.log)

```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
I think the problem you are seeing is that you are trying to restore your process while it is still running. CRIU always restores a process with exactly the same PID it had during checkpointing. Your process is still running and CRIU tries to restore the process with the same PID. As the PID still exists it is not possible to create a process an CRIU fails with the error you see. Works as designed.

**Comment by PSoni8** [comment]
I have changed my program as below:
[sample.zip](https://github.com/checkpoint-restore/criu/files/11662776/sample.zip)
While compiling and running sample.c , I got below output:
a is 12
criu dump init return 0
criu service binary return 0
criu dump log file return 0
dump open fxn return 3
criu dump return 0
5
6
After that compiling and running restore.c , I got below output:
criu restore init return 0
criu restore service binary return 0
criu restore log file return 0
restore open fxn return 3
criu restore return -52
a is 40
Why criu_restore is failing with below error?
(00.002094) 2171923: Error (criu/files-reg.c:2065): File users/ssdrive/Desktop/sample/sample has bad size 25088 (expect 25232)
(00.002104) 2171923: Error (criu/mem.c:1383): `- Can't open vma
(00.002143) Error (criu/cr-restore.c:2483): Restoring FAILED.
Dump log = 
[dump.log](https://github.com/checkpoint-restore/criu/files/11662803/dump.log)
Restore log = 
[restore.log](https://github.com/checkpoint-restore/criu/files/11662804/restore.log)

**Comment by adrianreber** [comment]
All open files have to stay the same between checkpoint and restore. Your file `sample` has changed size and thus CRIU will not restore your process.

**Comment by PSoni8** [comment]
After initialazing variable ptr and taking criu dump in sample .c I have just changed the value of ptr variable before restoring in restore.c, thats the reason for file size changes?
