### ISSUE TITLE
zdtm/centos 7: wait() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#2203]
After commit https://github.com/checkpoint-restore/criu/commit/0bd5abe4ed331c96fcc6d4da5fc4a60ece0045e2, the CentOS 7 CI tests fail with the following error:

```
Traceback (most recent call last):
  File "./test/zdtm.py", line 2854, in <module>
    opts['action'](opts)
  File "./test/zdtm.py", line 2427, in run_tests
    features[feat] = criu.check(feat)
  File "./test/zdtm.py", line 1507, in check
    return criu_cli.run("check", args, opts['criu_bin']) == 0
  File "./test/zdtm.py", line 903, in run
    return cr.wait(timeout=timeout)
TypeError: wait() got an unexpected keyword argument 'timeout'
```
The reason for this error is because in CentOS 7 we run the tests with Python 2.7 and with this version [wait()](https://docs.python.org/2.7/library/subprocess.html#subprocess.Popen.wait) does not support a `timeout` option.

This version of python has been deprecated for a few years now. Should we introduce a workaround to fix this problem or simply drop compatibility with Python 2?

**Comment by avagin** [comment]
To: @osctobe

**Comment by avagin** [comment]
@rst0git @adrianreber  RHEL7/Centos7 is in the maintenance mode, I think we can stop testing new versions of CRIU on it. WDYT?

**Comment by avagin** [comment]
python2 reached eof too, so I think we need to drop its support from criu too.

**Comment by avagin** [comment]
python2 reached eof too, so I think we need to drop its support from criu too.

**Comment by adrianreber** [comment]
I agree. Last time we talked about it @Snorch indicated that it might still be needed for openvz. From my point of view we can ignore CentOS 7 at this point in time.

**Comment by Snorch** [comment]
Initially I was against dropping python2 as we still use it in VZ7 based on Centos7
https://github.com/checkpoint-restore/criu/issues/1405
But then we have ported newer protobuf-compiler package and python3 should work on VZ7 now.
https://github.com/checkpoint-restore/criu/pull/1733#discussion_r809887414

So I also agree. (though I would probably get some more pain on my ass on next rebase =))

**Comment by rst0git** [comment]
Great! I will open a pull request to drop Python 2 and CentOS 7 :)
