### ISSUE TITLE
criu dump failing intermittently with -111

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2204]
I have written basic program([sample.txt](https://github.com/checkpoint-restore/criu/files/11796176/sample.txt)) for criu dump.
But, when i am executing program, intermittently I am facing below issue

```
Can't read swrk pid: Interrupted system call
Can't connect to criu: Bad file descriptor
ret is -111
```

`Error (criu/cr-service.c:59): Can't read request: Connection reset by peer
Error (criu/cr-service.c:1208): Can't recv request: Connection reset by peer`

After 2 or 3 retries, dumping is getting succesful. I suppose this might be because of criu and kernel both trying to access any file at the same time. So I have increased criu timeout by using ` criu_set_timeout(200)`. But it didn't help me.

CRIU version - 3.15
kernel version - 5.12.3

Any help on this issue can be appreciated.
Thanks in advance

**Comment by indusai99** [comment]
@adrianreber or @avagin .
Can anyone help me on this

**Comment by rst0git** [comment]
@indusai99 What is the content of the log file when using `criu_set_log_file("dump.log")`?

**Comment by indusai99** [comment]
Dump logs are not generated in this case @rst0git

**Comment by indusai99** [comment]
I executed this test in our own simulation environment

**Comment by Snorch** [comment]
Dup of https://github.com/checkpoint-restore/criu/issues/2205
