### ISSUE TITLE
criu dump finised succesfully. But returning -70 intermittently

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2205]
I have written basic program for criu dump.
I used pybind interface and called this criu_dump from python file. When executed python file, I could see below issue intermittently

```
Can't read request: Interrupted system call
Can't receive response: Interrupted system call
```

Dump.log:
```
(00.017974) Dumping finished successfully
response is -70
(00.017984) Error (criu/cr-service.c:119): Can't send response: Broken pipe
(00.017990) Error (criu/cr-service.c:738): Can't send response: Broken pipe
```

After 2 or 3 retries only ,I am getting response. I suppose this might be because of criu and kernel both trying to access any file at the same time. So I have increased criu timeout by using  criu_set_timeout(200). But it didn't help me.

CRIU version - 3.15
kernel version - 5.12.3
python version - 3.8.6

Any help on this issue can be appreciated.
Thanks in advance

**Comment by rst0git** [comment]
@indusai99 Would this be the same problem as in https://github.com/checkpoint-restore/criu/issues/2204? What is the difference?

**Comment by indusai99** [comment]
@rst0git , Both are different errors. But I am guessing ground reason might be same for both. I am not sure about this.
The difference is 
In this #2205 - Dump logs are getting generated and and dump is also finished succesfully. But issue is not able to receive dump resposne. 
**Error (criu/cr-service.c:119): Can't send response: Broken pipe**

In #2204 - Dump logs is not generating. It s throwing this error
**Can't read swrk pid: Interrupted system call**

**Comment by indusai99** [comment]
I executed this test in our own simulation environment

**Comment by Snorch** [comment]
That all looks like your process which does send_req_and_recv_resp_sk through pycriu is constantly interrupted (e.g. with some signal), and pycriu is not ready for that.

You may want to run your program under strace `strace -e 'trace=!all'` and see signals it receives to confirm.

It would be much easier to understand your problem if you prepare a small reproduce with clear steps.

**Comment by indusai99** [comment]
@Snorch , Thanks for your response.

I can't use 3.18 as my kernel is little older version. The latest criu supported version that I can use it 3.16. 
I am facing same issue in 3.16 also.

Sorry as I couldn't able to share much details about the simulation environment.
I used `strace -e 'trace=!all'` as per your suggestion while running python test.
I could see below trace 
```
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=1021610, si_uid=0, si_status=0, si_utime=5, si_stime=0} ---
+++ exited with 0 +++
```
Can you please have a look on this ?

**Comment by Snorch** [comment]
> I can't use 3.18 as my kernel is little older version(5.12). The latest criu supported version that I can use it 3.16. I am facing same issue in 3.16 also.

I'm not sure what you mean, our current kernel requirement is 3.11 (https://criu.org/Installation#Checking_That_It_Works) =) If you don't have "latest" version you can see how to build it here https://criu.org/Installation

> Sorry as I couldn't able to share much details about the simulation environment

Then we might not be able to help much. Without reproduce it's hard to distinguish that either you are doing something "wrong" or the problems is somewhere in pycriu.

> Can you please have a look on this?

We see only SIGCHLD, maybe you can block it (maybe with suspended_signals from pysigset or something similar) in the beginning of your program and see if it helps.

**Comment by indusai99** [comment]
Thank you @Snorch . I don't see any intermittent issue when I block SIGCHLD during dump.

**Comment by Snorch** [comment]
You are welcome =)
