### ISSUE TITLE
Build criu 32-bit source code

### ISSUE THREAD

**Issue by indusai99** [checkpoint-restore/criu#2246]
Hi,
I want to run criu in 32-bit mode . As the 32-bit libraries are not available, I want to generate them from criu source build.
I have cloned criu package and installed all required dependency libraries. 
Using `make` command, I have build criu. I could see libcriu.so is generated- which is of 64-bit
But my requirement is building 32-bit criu source and generating 32-bit shared libs.
From criu webiste,  (https://criu.org/Installation#Distribution_Packages:~:text=For%20building%20with%2032bit%20tasks%20C/R%20support%20you%20will%20need%20libc6%2Ddev%2Di386%2C%20gcc%2Dmultilib%20instead%20of%20gcc.) , I could see criu supports 32-bit build if we have required libc6-dev-i386, gcc-multilib.  
I have them in my machine. Apart from this, there is no info about 32-bit build  process/command
Can anyone guide me on how to do criu 32-bit build ? 

Machine Details:
Fedora based Linux kernel version - 5.12

Please let me know if any other input is required.

**Comment by indusai99** [comment]
`x32 - specially compiled binaries to run on x86_64 machine with CONFIG_X86_X32 config option set.`
I could see something like this in https://criu.org/32bit_tasks_C/R 
Do we need to enable this `CONFIG_X86_X32 `in kernel config or criu config?

**Comment by avagin** [comment]
> But my requirement is building 32-bit criu source and generating 32-bit shared libs.

We don't support this configuration. But 64-bit criu on amd64 can C/R 32-bit processes.
