### ISSUE TITLE
Explicit support for one dump - multiple restore?

### ISSUE THREAD

**Issue by marto1** [checkpoint-restore/criu#2257]
**Description**

Would it be in the scope of CRIU to support "template" process dumps? My use case is a python environment that does a lot of library imports and the idea was to use criu to speedup spawning many of these environments. I made a hacky workflow  that actually works. Running this:

```python
import os
from time import sleep
# Import a lot of libraries here


# Dump process somewhere here
print("Sleeping for a while..")
for _ in range(10):
    sleep(1)

print("Old PID:", os.getpid())
pid = os.fork()
if pid > 0:
   exit(0)
os.setpgrp()
print("New PID:", os.getpid())

# Any code can go below..
while(True):
    print("RUNNING")
    sleep(5)
```

When restored I wait for the pid to change and can restore again ad infinitum. This is obviously pretty awkward and can probably be improved a lot with native support. I also saw some people doing custom namespaces instead, but don't know yet about the overhead and/or management of that option. 

**Steps to reproduce the issue:**
1.  criu dump --shell-job -D checkpoint -t <PID>
2.  criu restore --shell-job -d -D checkpoint
3.  criu restore --shell-job -d -D checkpoint

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by avagin** [comment]
>  I also saw some people doing custom namespaces instead, but don't know yet about the overhead and/or management of that option.

The most straightforward way is to restore processes in new pid namespaces. The overhead is almost zero/unnoticeable in this case.

More hacky way is to change pid-s in the image files. I don't recommend to use it.

**Comment by marto1** [comment]
Sorry for the late reply and thanks! About the overhead, probably not an issue, but it's extra pollution for the kernel with namespaces going in and out. Hopefully same as deallocating a pid.
