### ISSUE TITLE
intermittent grow_map fail

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#226]
Test grow_map fails sometimes, with binary receiving SIGSEGV here:

`*(fake_grow_down - 1) = 'b';`

I was able to reproduce it on my laptop (and showed it to @avagin) last week. Today, I was able to reproduce it in Travis (the issue was, as we used gcov-enabled builds, everything was compiled with -O0, now with default optimization flags the bug is reproducible). For example, see
https://travis-ci.org/kolyshkin/criu/jobs/166347976 (this is CLANG build but I believe this is irrelevant).

**Comment by xemul** [comment]
#224?
