### ISSUE TITLE
Restore is not working with following capabilities 

### ISSUE THREAD

**Issue by PSoni8** [checkpoint-restore/criu#2262]
**Description**
I am running checkpoint and restore using CLI mode with following capabilities on fedora 34 based system, criu-3.16.1 version.
$ uname -a
Linux localhost.localdomain 5.12.3.valarch.master.1.2 #1 SMP Thu Oct 14 17:01:59 MDT 2021 x86_64 x86_64 x86_64 GNU/Linux
setcap \
    'cap_dac_override=eip \
     cap_chown=eip \
     cap_setpcap=eip \
     cap_setgid=eip \
     cap_audit_control=eip \
     cap_dac_read_search=eip \
     cap_net_admin=eip \
     cap_sys_admin=eip \
     cap_sys_chroot=eip \
     cap_sys_ptrace=eip \
     cap_fowner=eip \
     cap_kill=eip \
     cap_fsetid=eip \
     cap_sys_resource=eip \
     cap_setuid=eip' \
    /usr/sbin/criu

**Describe the results you received:**
Dump is successful but restore is failing with below issues:
[2023-09-08T11:53:53.719Z] (00.010083)  39524: timens: monotonic -6 965717522
[2023-09-08T11:53:53.719Z] (00.010099)  39524: Error (criu/timens.c:97): Unable to set a monotonic clock offset: Operation not permitted
[2023-09-08T11:53:53.719Z] (00.010122) Error (criu/cr-restore.c:2447): Restoring FAILED.
[2023-09-08T11:53:53.719Z] (00.010301) Error (criu/cr-restore.c:1480): 39524 killed by signal 9: Killed

But when executing it with superuser permissions (sudo) both checkpoint-restore is successful.

Want to konw which other cap permissions are required apart from this.

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
[dump_log.txt](https://github.com/checkpoint-restore/criu/files/12583167/dump_log.txt)

[restore_log.txt](https://github.com/checkpoint-restore/criu/files/12583127/restore_log.txt)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
3.16.1
```

</p>
</details>

**Additional environment details:**
$ uname -a
Linux localhost.localdomain 5.12.3.valarch.master.1.2 #1 SMP Thu Oct 14 17:01:59 MDT 2021 x86_64 x86_64 x86_64 GNU/Linux
[sample_code_in_system.txt](https://github.com/checkpoint-restore/criu/files/12583212/sample_code_in_system.txt)

**Comment by rst0git** [comment]
```
(00.010384)   2309: timens: monotonic -6 966515607
(00.010402)   2309: Error (criu/timens.c:97): Unable to set a monotonic clock offset: Operation not permitted
```
@PSoni8 This error appears because CRIU attempts to write to [timens_offsets](https://www.man7.org/linux/man-pages/man7/time_namespaces.7.html). This requires `CAP_SYS_TIME` capability.
