### ISSUE TITLE
No criu 3.18 in ubuntu repos

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#2287]
For Ubuntu packages, criu wiki (https://criu.org/Packages#Ubuntu) recommends 3 repos:

* https://build.opensuse.org/project/show/devel:tools:criu
* https://launchpad.net/~criu/+archive/ubuntu/ppa
* https://launchpad.net/ubuntu/+source/criu

Alas, all three has 3.17.1 as the most recent version. While this might be a sign that criu finally achieved maturity, I think it still makes sense to provide the latest version.

Cc @rst0git

**Comment by kolyshkin** [comment]
(found while looking into runc tests in which we install criu from the first link above; we also test the tip of `criu-dev` from git)

**Comment by rst0git** [comment]
Thank you @kolyshkin! I will update the packages in OBS / launchpad later today.

**Comment by kolyshkin** [comment]
Now the repo is broken 😢 

```
Get:4 https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04  criu 3.18-1 [697 kB]
Err:4 https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04  criu 3.18-1
  File has unexpected size (697812 != 697432). Mirror sync in progress? [IP: 146.75.37.91 443]
  Hashes of expected file:
   - SHA256:a11a1c56ba0c8ec688590f0e24aaa5028f3a7380fc2775b8a5d4c674552d07e9
   - SHA1:d25e0e6de9f7e83525cef6b0f4a53a22a1f8911f [weak]
   - MD5Sum:b8d628828ba2face32f612b8140b75bb [weak]
   - Filesize:697432 [weak]
Fetched 127 kB in 2s (51.7 kB/s)
E: Failed to fetch https://downloadcontentcdn.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_20.04/amd64/criu_3.18-1_amd64.deb  File has unexpected size (697812 != 697432). Mirror sync in progress? [IP: 146.75.37.91 443]
   Hashes of expected file:
    - SHA256:a11a1c56ba0c8ec688590f0e24aaa5028f3a7380fc2775b8a5d4c674552d07e9
    - SHA1:d25e0e6de9f7e83525cef6b0f4a53a22a1f8911f [weak]
    - MD5Sum:b8d628828ba2face32f612b8140b75bb [weak]
    - Filesize:697432 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by rst0git** [comment]
>  File has unexpected size (697812 != 697432). Mirror sync in progress?

@kolyshkin It takes some time for OBS to update the repository. It should be working now.

**Comment by kolyshkin** [comment]
Guess this is now fixed. Thank you @rst0git!
