### ISSUE TITLE
Error: configured runtime does not support checkpoint/restore on Ubuntu 23.10

### ISSUE THREAD

**Issue by Parthiba-Hazra** [checkpoint-restore/criu#2317]
I was trying to to check how criu works with podman and each time getting same error - 
```
➜  ~ sudo podman run -d --name httpd -p 7000:80 docker.io/httpd

bc1dd363790edfc0b6825da0f50bb67b34826fd15f09b4c322ed831e9be86785
➜  ~ sudo podman ps
CONTAINER ID  IMAGE                           COMMAND               CREATED         STATUS             PORTS                 NAMES
3e694a7ea034  docker.io/library/nginx:latest  nginx -g daemon o...  20 minutes ago  Up 20 minutes ago  0.0.0.0:9000->80/tcp  my_container
bc1dd363790e  docker.io/library/httpd:latest  httpd-foreground      8 seconds ago   Up 9 seconds ago   0.0.0.0:7000->80/tcp  httpd
➜  ~ sudo podman container checkpoint -k -e chkpt.tar.gz httpd        
Error: configured runtime does not support checkpoint/restore
```

OS - Ubuntu 23.10

**Comment by adrianreber** [comment]
That is pretty easy:

```Error: configured runtime does not support checkpoint/restore```

My guess is that crun is built without CRIU support on Ubuntu. Try Fedora, we know that crun supports CRIU there.

On Ubuntu you could also try to switch to runc.

**Comment by Parthiba-Hazra** [comment]
> That is pretty easy:
> 
> `Error: configured runtime does not support checkpoint/restore`
> 
> My guess is that crun is built without CRIU support on Ubuntu. Try Fedora, we know that crun supports CRIU there.
> 
> On Ubuntu you could also try to switch to runc.

Hi @adrianreber actually I was working on this issue - https://github.com/checkpoint-restore/checkpointctl/issues/77

and I just wanted to check how criu works with checkpointctl, is there any way to see that on ubuntu system?

**Comment by adrianreber** [comment]
Try to use runc instead of crun.
