### ISSUE TITLE
criu error about docker

### ISSUE THREAD

**Issue by wdjiang** [checkpoint-restore/criu#2318]
My problem：
I am trying to manipulate docker using criu.The following occurs during the criu dump process
dump log:
[criu-dump.log](https://github.com/checkpoint-restore/criu/files/13770996/criu-dump.log)

Error (criu/mount.c:1088): mnt: Mount 1322 ./dev/dri/renderD135 (master_id: 2 shared_id: 0) has unreachable sharing. Try --enable-external-masters.

What does this error mean and should I add the --enable-external-masters option at compile time?

**Comment by adrianreber** [comment]
That sounds like you are checkpointing a graphical application. That usually doesn't work as CRIU cannot extract the state of the GPU.

Generally speaking if CRIU needs additional options they need to be added to the CRIU command line or in the container case, where you cannot change the command line options, you can add it to the CRIU configuration file. See details in the wiki.

**Comment by avagin** [comment]
@wdjiang pls add more details how you start a container, what you are dumping and how you execute criu.

**Comment by wdjiang** [comment]
As you said, criu is too complicated for docker, so we have adopted another solution. Thank you for your reply.
