### ISSUE TITLE
thread-bomb in h test failure

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#234]
I just got the following fail with latest criu-dev + couple of my fixes to compile it with clang.

NOTE that:
1. clang is used as a compiler
2. previous two tests with the same code/config worked fine, so it's probably some rare race
3. one thing that might be relevant, now travis compiles code to test with -O2 not -O0

Here's the output excerpt:

```
===================== Run zdtm/transition/thread-bomb in h =====================
Start test
./thread-bomb --pidfile=thread-bomb.pid --outfile=thread-bomb.out
03:13:49.444:    25: 1024
Run criu pre-dump
Run criu pre-dump
=[log]=> dump/zdtm/transition/thread-bomb/26/2/pre-dump.log
------------------------ grep Error ------------------------
(00.243237) Error (criu/pagemap.c:193): Missing 2b665fc00000 in parent pagemap
(00.243239) Error (criu/page-xfer.c:254): Hole 0x2b665fc00000/114688 not found in parent
(00.243296) Error (criu/cr-dump.c:1509): Pre-dumping FAILED.
------------------------ ERROR OVER ------------------------
############ Test zdtm/transition/thread-bomb FAIL at CRIU pre-dump ############
Send the 9 signal to  26
Wait for zdtm/transition/thread-bomb(26) to die for 0.100000
##################################### FAIL #####################################

```

The full logs can be found at https://travis-ci.org/kolyshkin/criu/jobs/169425879

The commits (I don't think they are relevant, but still) can be found at https://github.com/kolyshkin/criu/commit/105af5e99189a2dc46269d55383d5fff87d8cc88

Guys @adrianreber @rppt can you please take a look?

**Comment by xemul** [comment]
Nice! We have issue #231 about it :) @kolyshkin , is it reproducible?

**Comment by kolyshkin** [comment]
@xemul I was only able to reproduce it once, out of 3 or 4 travis-ci runs. Will do more testing today and report.

**Comment by kolyshkin** [comment]
All I can say now is I think I ran the Travis test 3 or 4 times and it only
happened once. I will do more testing next Monday.

**Comment by xemul** [comment]
OK, let's hope that https://github.com/xemul/criu/commit/4ee30b10435eb15a9a60d540d993977d6e3b2ed7 mentioned by @rppt in issue #231 really fixes it.

**Comment by kolyshkin** [comment]
Unfortunately, this commit was included into what I was testing: https://github.com/kolyshkin/criu/commits/clang-fix-2

**Comment by kolyshkin** [comment]
so please reopen this (looks like I don't have rights to do so)

**Comment by rppt** [comment]
@kolyshkin, do you have the dump tar by any chance?

**Comment by 0x7f454c46** [comment]
Also reproduced accidentally:
https://travis-ci.org/0x7f454c46/criu/jobs/177940013
```
===================== Run zdtm/transition/thread-bomb in h =====================
Start test
./thread-bomb --pidfile=thread-bomb.pid --outfile=thread-bomb.out
11:37:52.914:    25: 1024
Run criu pre-dump
Run criu pre-dump
=[log]=> dump/zdtm/transition/thread-bomb/26/2/pre-dump.log
------------------------ grep Error ------------------------
(00.277310) Error (criu/pagemap.c:210): Missing 2b0117600000 in parent pagemap
(00.277314) Error (criu/page-xfer.c:255): Hole 0x2b0117600000/1794048 not found in parent
(00.277404) Error (criu/cr-dump.c:1511): Pre-dumping FAILED.
------------------------ ERROR OVER ------------------------
############ Test zdtm/transition/thread-bomb FAIL at CRIU pre-dump ############
Send the 9 signal to  26
Wait for zdtm/transition/thread-bomb(26) to die for 0.100000
```

**Comment by avagin** [comment]
https://travis-ci.org/criupatchwork/criu/jobs/179549874

**Comment by kolyshkin** [comment]
OK, we have 3 failures now, two of them with clang used to compile the code, and one with gcc, so clang is probably irrelevant.

**Comment by avagin** [comment]
Here is an attempt to get logs https://travis-ci.org/avagin/criu/builds/180573886

**Comment by avagin** [comment]
https://ci.openvz.org/job/CRIU/view/All/job/CRIU-3.11/368/
https://www.dropbox.com/s/ykiiko391qxn263/log.tar.gz?dl=0

**Comment by rppt** [comment]
I still cannot grok what's exactly happening there, but judging by the logs, somehow the stack guard page allocated by glibc as a part of the thread stack, gets present bit in the page table, but it's missing soft-dirty flag.
Could be related to https://github.com/xemul/criu/issues/207
I've tried to reproduce with 3.11.10-301.fc20.x86_64 as well as 3.19.0-64-generic that travis used to run, but still no success...
