### ISSUE TITLE
Failed to dump the process that was restored from the checkpoint

### ISSUE THREAD

**Issue by liuaifu** [checkpoint-restore/criu#2341]
**Description**

Failed to dump the process that was restored from the checkpoint.

**Steps to reproduce the issue:**
1. sudo ~/criu/scripts/criu-ns dump -t [pid] -D ~/test -j
2. sudo ~/criu/scripts/criu-ns restore -D ~/test -j
3. sudo ~/criu/scripts/criu-ns dump -t [newpid] -D ~/test2 -j

**Describe the results you received:**
eplace pid 5191 with 3069
['/home/dev/criu/scripts/criu-ns', 'dump', '-t', '3069', '-D', '/home/dev/test2', '-j']
Warn  (compel/arch/x86/src/lib/infect.c:281): Will restore 3069 with interrupted system call
Error (criu/files-reg.c:1371): Can't lookup mount=26 for fd=0 path=/dev/pts/0
Error (criu/cr-dump.c:1348): Dump files (pid: 3069) failed with -1
Error (criu/cr-dump.c:1764): Dumping FAILED.

**Describe the results you expected:**
ok.

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.14
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good.
```

</p>
</details>

**Additional environment details:**
```
dev@dev-VirtualBox:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
dev@dev-VirtualBox:~$ uname -r
5.8.0-63-generic
```

**Comment by adrianreber** [comment]
Any specific reason you are using `criu-ns`? Did you try it without `criu-ns`?

**Comment by liuaifu** [comment]
@adrianreber The main purpose of using criu-ns is to clone processes, where a specified process is cloned into multiple processes. criu cannot achieve this task.

Is the version of criu I'm using too old? Does the new version fix this?

**Comment by adrianreber** [comment]
Ah, okay, makes sense.

**Comment by Snorch** [comment]
>Version: 3.14
>Is the version of criu I'm using too old? Does the new version fix this?

Yes, I believe new version can fix your problem, as we had problems with criu-ns recently.

For reference, see:
 https://github.com/checkpoint-restore/criu/issues/1909
 https://github.com/checkpoint-restore/criu/issues/232
 https://github.com/checkpoint-restore/criu/issues/1893

**Comment by liuaifu** [comment]
I tested v3.18-201-ga9cbdad76 on Ubuntu 22.04.3 LTS and this issue has been fixed, thanks.

**Comment by Snorch** [comment]
Thanks for confirming!
