### ISSUE TITLE
How do I detect if the current process has restored from a checkpoint?

### ISSUE THREAD

**Issue by liuaifu** [checkpoint-restore/criu#2354]
I use criu to dump and restore my app, and everything works. But my program needs to perform some specific actions when it is restored. How can I detect the event that is restored? Thank you.

	#include <iostream>
	#include <thread>
	#include <chrono>
	
	
	bool is_restored_from_checkpoint() {
		// ......
		return false;
	}

	int main(){
		int n = 0;
		while(n < 3600) {
			if(is_restored_from_checkpoint()) {
				std::cout << "restored from checkpoint." << std::endl;
				// do something
			}
			
			std::this_thread::sleep_for(std::chrono::seconds(1));
			std::cout << n++ << std::endl;
		}
	}

**Comment by rst0git** [comment]
@liuaifu you can use an [action-script](https://criu.org/Action_scripts) to create a file that indicates the current process has been restored. Then `is_restored_from_checkpoint()` could return `true` if this file exists and `false` otherwise.

**Comment by liuaifu** [comment]
Got it. Thank you.

**Comment by Snorch** [comment]
There is actually one more option I recently found, it's with external file descriptors "debug" mode https://criu.org/Inheriting_FDs_on_restore#Debugging_aid

**Comment by liuaifu** [comment]
@rst0git @Snorch Consider the following scenario:
1. Dump process A and keep A running：`sudo criu-ns dump -D ./checkpoint -R -t xxx -j`
2. Restore process B: `sudo criu-ns restore -D ./checkpoint -j`, now action-script is executed and a specific file f is created.
At this time, both A and B can detect the existence of f, so it is still impossible to distinguish which is restored by checkpoint.

Is there a way to add or modify environment variables during criu-ns restore? Or change the value of a variable in checkpoint?

**Comment by Snorch** [comment]
One hack to distinguish the restored from the original process would be to look on the process start time (start_time param from /proc/[pid]/stat). As this is not virtualized (yet) and just restored process will have recent start time, where original process, which I suppose already worked for quite some time, will have much earlier start time.

**Comment by rst0git** [comment]
As Pavel pointed out, using the process start time is a good way to distinguish between restored process. Here is an example:

```python3
import psutil
import datetime
import sys

def get_start_time_by_name(process_name):
    found = False

    for process in psutil.process_iter(['pid', 'name', 'create_time']):
        try:
            if process.info['name'] == process_name:
                found = True
                start_time = datetime.datetime.fromtimestamp(
                    process.info['create_time']
                )

                print(f"PID: {process.info['pid']}")
                print(f"Name: {process.info['name']}")
                print(f"Start Time: {start_time}")
                print("-" * 40)

        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue

    if not found:
        print(f"No running process found with name '{process_name}'")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(1)
    process_name = sys.argv[1]
    get_start_time_by_name(process_name)
```

```console
$ python3 get_start_time.py loop
PID: 550265
Name: loop
Start Time: 2026-02-12 09:27:46.510000
----------------------------------------
PID: 550415
Name: loop
Start Time: 2026-02-12 09:27:55.080000
----------------------------------------
```
