### ISSUE TITLE
ENOMEM when restoring big mappings with PROT_NONE 

### ISSUE THREAD

**Issue by AT120** [checkpoint-restore/criu#2364]
**Description**

I was trying to checkpoint/restore aspnet.core application and while dump was successful I kept getting out of memory errors during restore. (The application should not consume >1GB ram and ~15GB was available at the moment of a restore)
```
(00.081792) pie: 20: Error (criu/pie/restorer.c:1774): Can't restore 0x7ba7a5c11000 mapping with 0xfffffffffffffff4
(00.081798) pie: 20: Error (criu/pie/restorer.c:2208): Restorer fail 20
```
And corresponding dmesg log

```
 __vm_enough_memory: pid: 3763, comm: criu, not enough memory for the allocation
```
According to logs, the problem is criu trying to mmap block >200GB in size with PROT_WRITE, inspite of it originally being mmap'ed with PROT_NONE.

**Steps to reproduce the issue:**

I can consistently reproduce this issue when trying to restore the following sample code:
<details><summary>code</summary>
<p>

```c
#include <stdio.h>
#include <sys/mman.h>
#include <unistd.h>
#include <string.h>


int main() {
    unsigned long prot_none_gb = 400;
    unsigned long inside_prot_none_mb = 10;

    void *prot_none_ptr1 = mmap(0,  (prot_none_gb << 30ul), PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
    if (prot_none_ptr1 == MAP_FAILED) {
        printf("failed to allocate with prot_none\n");
        return 0;
    }
    printf("allocated %lugb in %p\n", prot_none_gb, prot_none_ptr1);


    void *prot_none_ptr2 = mmap(0,  (prot_none_gb << 30ul), PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
    if (prot_none_ptr2 == MAP_FAILED) {
        printf("failed to allocate with prot_none\n");
        return 0;
    }
    printf("allocated %lugb in %p\n", prot_none_gb, prot_none_ptr2);



    void *inside_prot_none_ptr = mmap(prot_none_ptr1, (inside_prot_none_mb << 20ul), PROT_READ|PROT_WRITE, MAP_FIXED|MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
    if (inside_prot_none_ptr == MAP_FAILED) {
        printf("failed to allocate inside of prot_none block\n");
        return 0;
    }
    printf("allocated %lumb in %p\n", inside_prot_none_mb, inside_prot_none_ptr);


    void *inside_prot_none_ptr1 = mmap(prot_none_ptr2, (inside_prot_none_mb << 20ul), PROT_READ|PROT_WRITE, MAP_FIXED|MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
    if (inside_prot_none_ptr1 == MAP_FAILED) {
        printf("failed to allocate inside of prot_none block\n");
        return 0;
    }
    printf("allocated %lumb in %p\n", inside_prot_none_mb, inside_prot_none_ptr1);


    char str[] = "test string" ;
    if (!strcpy(inside_prot_none_ptr, str)) {
        printf("failed to write inside of nested block\n");
        return 0;
    }
    if (!strcpy(inside_prot_none_ptr1, str)) {
        printf("failed to write inside of nested block\n");
        return 0;
    }

    printf("reading from nested block: %s\n", (char *)inside_prot_none_ptr);
    printf("reading from nested block: %s\n", (char *)inside_prot_none_ptr1);
    printf("my pid: %d\n", getpid());
    printf("press enter to continue...\n");
    getchar();
    printf("reading from nested block: %s\n", (char *)inside_prot_none_ptr);
    printf("reading from nested block: %s\n", (char *)inside_prot_none_ptr1);
}

```

</p>
</details>

**Potential solution:**

The problem might be in these lines. 

https://github.com/checkpoint-restore/criu/blob/cb39c62f8a2be2a686dbfc60a2730729dd082624/criu/mem.c#L1057-L1063

I assume this code tries to find an intersections with `vma` and if no intersections were found, marks `vma` with `VMA_NO_PROT_WRITE`. In my case, there was iteration where `pr->pe->vaddr` == `vma->e->end` so `vma` wasn't marked as `VMA_NO_PROT_WRITE` leading to ENOMEM. It seems to me that a memory interval is a half-open interval so the condition when `pr->pe->vaddr` == `vma->e->end` should not be interpreted as an intersection. 

Changing line 1060 to 
```c
if (pr->pe->vaddr >= vma->e->end)
```
fixed restore for sample code and aspnet.core application. They seem to function correctly after restore.

**CRIU logs and information:**

<details><summary>aspnet.core application dump log</summary>
<p>

[aspnet-dump.log](https://github.com/checkpoint-restore/criu/files/14593778/aspnet-dump.log)

</p>
</details>

<details><summary>aspnet.core application restore log</summary>
<p>

[aspnet-restore.log](https://github.com/checkpoint-restore/criu/files/14593780/aspnet-restore.log)

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.19
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good.
```

</p>
</details>

**Comment by avagin** [comment]
> It seems to me that a memory interval is a half-open interval so the condition when pr->pe->vaddr == vma->e->end should not be interpreted as an intersection.

You are right. Do you want to create a pr with this fix?
