### ISSUE TITLE
Y'all seen this??

### ISSUE THREAD

**Issue by aidan-gibson** [checkpoint-restore/criu#2369]
https://arxiv.org/pdf/2103.04916.pdf

They extended CRIU to OpenGL and suspended / restored Autodesk Maya. No code published tho ):

**Comment by adrianreber** [comment]
Thanks. The following also seems to be from memverge. Unfortunately memverge does not really talk to upstream CRIU about their work. This sounds slightly related to:

- https://www.nvidia.com/gtc/posters/#/session/1705106137731001cNAN
-  ![gtc24-web-poster-1920x1080_P63184_1709928723357001pVZQ](https://github.com/checkpoint-restore/criu/assets/8724298/2604655e-e406-44d7-b3f9-d566af9f0062)
- [DCCDCCS_1_P63184_Bernie Wu_web_1710777201737001ioQN.pdf](https://github.com/checkpoint-restore/criu/files/14734930/DCCDCCS_1_P63184_Bernie.Wu_web_1710777201737001ioQN.pdf)
- https://youtu.be/p-zNA1AN37M

I am closing this ticket in favour of #534. That ticket seems to have become the main location for
