### ISSUE TITLE
[question about criu] Will it work on steam deck?

### ISSUE THREAD

**Issue by DuckersMcQuack** [checkpoint-restore/criu#2385]
As i love the save states for emulators, i'd love to have the same function for regular pc games. 

Would it work to bind it's checkpoint store and restore for any running pc game on steam deck's back buttons? And does it dump it as fast as the storage on the computer can write it? As in one large file? Or is it dumping lots of tiny files within the memory for it?

**Comment by adrianreber** [comment]
The main problem I see with your question is that CRIU usually cannot checkpoint/restore processes which are using a GPU (or any external hardware device basically). CRIU has no way of saving the state of the GPU (except certain AMD accelerators) so it might not be possible at all what you want to do. What people usually do if the really need to do this is to have the output on something like VNC without hardware acceleration and then it is doable.

Concerning speed. I did some tests many years ago around process migration and checkpointing/restoring was much faster than the network transfer time (around 20Gbit/s at that time). So writing and reading checkpoints is definitely not slow, but you should just measure it yourself.
