### ISSUE TITLE
How disable plugin for nvidia gpu

### ISSUE THREAD

**Issue by FuwuerRyu** [checkpoint-restore/criu#2394]
I am trying to manage nvidia resource by myself.
But When I was tying to dump  a CUDA APP, the error blow was met.

Could you let me know how to disable the plugin?

(00.028819) vma 563f5e653000 borrows vfi from previous 563f5e64d000
(00.028851) Handling VMA with the following smaps entry: 563f5e654000-563f5e655000 rw-p 00000000 00:00 0 
(00.028863) Handling VMA with the following smaps entry: 563f5edf1000-563f5ee7a000 rw-p 00000000 00:00 0                          [heap]
(00.028872) Handling VMA with the following smaps entry: 7f3158000000-7f3158021000 rw-p 00000000 00:00 0 
(00.028880) Handling VMA with the following smaps entry: 7f3158021000-7f315c000000 ---p 00000000 00:00 0 
(00.028889) Handling VMA with the following smaps entry: 7f3160000000-7f3170000000 ---p 00000000 00:00 0 
(00.028898) Handling VMA with the following smaps entry: 7f3177f42000-7f3177f43000 ---p 00000000 00:00 0 
(00.028907) Handling VMA with the following smaps entry: 7f3177f43000-7f317bf43000 rw-p 00000000 00:00 0 
(00.028932) Handling VMA with the following smaps entry: 7f317bf43000-7f317c9c7000 ---p 00000000 00:00 0 
(00.028941) Handling VMA with the following smaps entry: 7f317c9c7000-7f317ca92000 rw-p 00000000 00:00 0 
(00.028950) Handling VMA with the following smaps entry: 7f317ca92000-7f3182a92000 ---p 00000000 00:00 0 
(00.028959) Handling VMA with the following smaps entry: 7f3182a92000-7f3182aa2000 -w-s 00000000 00:06 11385090                   /dev/nvidia3
(00.029028) Error (criu/proc_parse.c:114): handle_device_vma plugin failed: No such file or directory
(00.029033) Error (criu/proc_parse.c:629): Can't handle non-regular mapping on 3388's map 7f3182a92000
(00.029045) Error (criu/cr-dump.c:1569): Collect mappings (pid: 3388) failed with -1

**Comment by rst0git** [comment]
@FuwuerRyu CRIU currently does not support checkpoint/restore of CUDA applications (https://github.com/checkpoint-restore/criu/issues/534)

**Comment by FuwuerRyu** [comment]
> (00.028959) Handling VMA with the following smaps entry: 7f3182a92000-7f3182aa2000 -w-s 00000000 00:06 11385090 /dev/nvidia3

I do not need criu to dump cuda resource.
Is there any possible to skip the error during dumping?
