### ISSUE TITLE
How to use CRIU with CUDA

### ISSUE THREAD

**Issue by FuwuerRyu** [checkpoint-restore/criu#2395]
> (00.028959) Handling VMA with the following smaps entry: 7f3182a92000-7f3182aa2000 -w-s 00000000 00:06 11385090 /dev/nvidia3

I do not need criu to dump cuda resource.
Is there any possible to skip the error during dumping?

_Originally posted by @FuwuerRyu in https://github.com/checkpoint-restore/criu/issues/2394#issuecomment-2065941468_

**Comment by rst0git** [comment]
> I do not need criu to dump cuda resource.
Is there any possible to skip the error during dumping?

The README file in the following repository describes you can do that https://github.com/RWTH-ACS/cricket

**Comment by rst0git** [comment]
NVIDIA have released a new CUDA checkpointing tool. The readme file in the following repository provides more information on how it can be used with CRIU: https://github.com/NVIDIA/cuda-checkpoint
