### ISSUE TITLE
Following the `setcap` instruction raises 'fatal error: Invalid argument'

### ISSUE THREAD

**Issue by aqjune** [checkpoint-restore/criu#2401]
**Description**

When I try `criu dump` it requests that capability of CAP_SYS_ADMIN or CAP_CHECKPOINT_RESTORE must be given to criu, with an instruction showing how to use `setcap`. However, if I follow it, I am seeing the following error:

```
$ ~/criu-3.19/criu/criu dump -t 31058 -vvv -o dump.log --unprivileged && echo OK
CRIU needs to have the CAP_SYS_ADMIN or the CAP_CHECKPOINT_RESTORE capability:
setcap cap_checkpoint_restore+eip /home/aqjune/criu-3.19/criu/criu
(00.000000) Effective capability 40 missing
(00.000000) Effective capability 21 missing
$ setcap cap_checkpoint_restore+eip /home/aqjune/criu-3.19/criu/criu
fatal error: Invalid argument
usage: setcap [-q] [-v] [-n <rootid>] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
```

This might not be a problem of criu (I found that criu's CI script is in fact using the same command), but was just wondering whether any further instruction could be given in the case, which might be helpful to beginners.

**Describe the results you expected:**

The `setcap` command is succesfully done

**Additional information you deem important (e.g. issue happens only occasionally):**

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
```

**CRIU logs and information:**

criu 3.19

<details><summary>CRIU full dump/restore logs:</summary>
<p>

None

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.19
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
$ ~/criu-3.19/criu/criu check --all
CRIU needs to have the CAP_SYS_ADMIN or the CAP_CHECKPOINT_RESTORE capability:
setcap cap_checkpoint_restore+eip /home/aqjune/criu-3.19/criu/criu
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
My first guess would be that Ubuntu 20.04 is just too old. Please retry with something newer.

**Comment by aqjune** [comment]
Thanks @adrianreber, it worked on 24.04. If `CAP_CHECKPOINT_RESTORE` is a new capability option of a newer Linux, I think that printing something like `This linux does not unsupport CAP_CHECKPOINT_RESTORE` other than the `setcap cap_checkpoint_restore+eip ...` command line could be an option.

**Comment by adrianreber** [comment]
Please close if resolved.

**Comment by aqjune** [comment]
My concern was that it was printing a wrong diagnostic message, sorry - I think it should emit a different message than 'setcap ...' if the capability was not available. The issue is not resolved yet.

**Comment by adrianreber** [comment]
If your setcap is too old there is nothing CRIU can do.

**Comment by rst0git** [comment]
@aqjune As mentioned in the [capabilities](https://www.man7.org/linux/man-pages/man7/capabilities.7.html) man page,`CAP_CHECKPOINT_RESTORE` is supported since version 5.9.

Ubuntu 20.04 has kernel version 5.15. The reason for the error is because the [`libcap2-bin`](https://packages.ubuntu.com/focal/libcap2) package in 20.04 provides libcap v2.32, and support for `CAP_CHECKPOINT_RESTORE` was introduced in [v2.43](https://sites.google.com/site/fullycapable/release-notes-for-libcap#h.p_ID_32).

**Comment by avagin** [comment]
@aqjune if you don't like the error message, pls open a pull request with the fix. We will be glad to accept it.
