### ISSUE TITLE
Can CRIU use arm based runners from Actuated?

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#2402]
Hello @alexellis, you mentioned in a runc and CRI-O ticket that Actuated now has 6.x based kernels for their aarch64 runners.

Would it be possible for CRIU to also use those runners for CI testing?

**Comment by kolyshkin** [comment]
You can see how runc enabled this: https://github.com/opencontainers/runc/pull/4142

**Comment by alexellis** [comment]
Hi @adrianreber @kolyshkin how many jobs do you think you'd be generating?

**Comment by adrianreber** [comment]
Looking at the history of the last 6 months there were around 50 pull requests. A pull request takes a couple of attempts before it is merged, but I would say an average of 6 CI runs each for 50 pull requests. A common test setup we have is to built and test CRIU once with GCC and once with LLVM. That would mean 50 pull requests * running around 6 times * 2 CI setups. So maybe something like 600 runs in 6 months on average. 100 per month. The free GitHub Actions runners need around 25 minutes for building and running all tests in the last few months.

@alexellis Is that helpful?

**Comment by alexellis** [comment]
Let's get your details if that's OK? https://docs.google.com/forms/d/e/1FAIpQLScA12IGyVFrZtSAp2Oj24OdaSMloqARSwoxx3AZbQbs0wpGww/viewform?usp=send_form

**Comment by adrianreber** [comment]
> Let's get your details if that's OK? https://docs.google.com/forms/d/e/1FAIpQLScA12IGyVFrZtSAp2Oj24OdaSMloqARSwoxx3AZbQbs0wpGww/viewform?usp=send_form

Done.

**Comment by alexellis** [comment]
Access is enabled and working, this issue can be closed.

**Comment by alexellis** [comment]
Hi @kolyshkin and @adrianreber 

Quick question - now that GitHub offers free Arm runners for OSS, are you in a position to switch over to their runners?

Outside of future plans like offering a Rocky9 image, is there any reason for you to retain access to actuated?

Regards,

Alex
