### ISSUE TITLE
Website isn't reachable

### ISSUE THREAD

**Issue by richardcase** [checkpoint-restore/criu#2447]
**Description**

In the last few days i've noticed that the [criu website](https://[criu.org](https://criu.org/)/)  isn't reachable. I could get it last week without issues.

![image](https://github.com/user-attachments/assets/3b696143-8d85-4a0f-b5c8-f2a7f93433ba)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by rst0git** [comment]
Pavel Tikhomirov (@Snorch) has reported this problem to the IT Services team, and it should be resolved soon, hopefully.

**Comment by Snorch** [comment]
Hi all, and really sorry for a long wait, criu.org is now available again.
