### ISSUE TITLE
Docker checkpoint fails on a previously restored container

### ISSUE THREAD

**Issue by abhineet09** [checkpoint-restore/criu#2453]
**Description**
I  have an use case for frequent migration of docker containers across multiple hosts. While docker checkpoint works for the first time I checkpoint the container. When I try to checkpoint the restored container, it fails. 

**Steps to reproduce the issue:**
```
docker run -d --name looper --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

=> 3ae70a4f1cf4270795b9a57afb6210d839d5f387674ace6601105d9635775ae8

docker checkpoint create --checkpoint-dir=/tmp looper checkpoint

docker create --name looper-clone --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

=> 831a48211c1c1335aa8d23d419093337b3fdbff632e00b6f4f44be3b8247de23

cp -a /tmp/checkpoint /var/lib/docker/containers/831a48211c1c1335aa8d23d419093337b3fdbff632e00b6f4f44be3b8247de23/checkpoints

docker start --checkpoint=checkpoint looper-clone

docker checkpoint create --checkpoint-dir=/tmp looper-clone checkpoint2
```

**Describe the results you received:**
`Error response from daemon: Cannot checkpoint container looper-clone: OCI runtime pause failed: freezer not supported: openat2 /sys/fs/cgroup/system.slice/docker-831a48211c1c1335aa8d23d419093337b3fdbff632e00b6f4f44be3b8247de23.scope/cgroup.freeze: no such file or directory: unknown`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
My runc.conf:
```
file-locks
tcp-established
link-remap
manage-cgroups=full 
```
NOTE: Getting same result without, manage-cgroups=full 

ls for /sys/fs/cgroup/system.slice/  has the following directory 

docker-3ae70a4f1cf4270795b9a57afb6210d839d5f387674ace6601105d9635775ae8.scope 

which is the looper (first) container's id

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.19
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Warn  (criu/cr-check.c:1346): Nftables based locking requires libnftables and set concatenations support
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**
```
docker --version
Docker version 27.0.3, build 7d4bcd8
```

**Comment by adrianreber** [comment]
That is a docker error and not a CRIU error. The cgroup is not restored correctly. You could try the checkpoint functionality if Podman, I am pretty sure it works there.

**Comment by abhineet09** [comment]
This can be resolved with:

```
docker run -d --name looper --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

docker checkpoint create --checkpoint-dir=/tmp looper checkpoint

[THE CHANGE!]
docker run -d --name looper-clone --security-opt seccomp:unconfined busybox \
         /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

sudo cp -a /tmp/checkpoint /var/lib/docker/containers/<container_id>/checkpoints

docker start --checkpoint=checkpoint looper-clone

docker checkpoint create --checkpoint-dir=/tmp looper-clone checkpoint2
```

Leaving it out here, in case someone needs it.

**Comment by adrianreber** [comment]
Thanks, the part of `--security-opt seccomp:unconfined` seems unnecessary. It was necessary 10 years ago.
