### ISSUE TITLE
Question: is it possible keep criu dump process running in lazy-pages mode always, even restore finished?

### ISSUE THREAD

**Issue by vitan** [checkpoint-restore/criu#2455]
as the subject.

I am trying to restore many same processes from one dumped process in lazy page mode, but I found the criu page server will exit once one restore process finished.

Is it possible to freeze the dump process or switch the dumped process in readonly mode but page server keep running? I am trying to use criu to make a snapshot to speed up my process, and I can make sure the to-dump process is in ready-mode before restore N same processes.

**Comment by adrianreber** [comment]
This sounds like code changes will be necessary. I am not sure the page server in lazy mode can correctly handle if one page is requested twice. So it is only possible with code changes.
