### ISSUE TITLE
cannot checkpoint a gnome desktop container

### ISSUE THREAD

**Issue by coldbloodx** [checkpoint-restore/criu#2460]
**Description**
cannot checkpoint a gnome desktop container

**Steps to reproduce the issue:**
1. create ubuntu desktop docker image
2. start the container with below options:
```
docker run -d -it --rm --shm-size 20737418240 \
    --security-opt="apparmor:unconfined" \
    -p 4401:6401  -e XDG_DATA_DIRS="" -e APP_ID=1\
    -e MY_USER_GROUP=domainusers -e MY_USER=admin -e MY_UID=1001 \
    -e MY_GID=1001 -e HOME=/home/admin -e MYAPP_PASSWD=letmein \
    -u 1001:1001 -v /run/dbus:/run/dbus \
    -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
    -v /public:/public  ubuntudesk:v01 \
    /entrypoint/entrypoint.sh
```

**Describe the results you received:**
 run docker checkpoint for above container.
```
[root@laworks ~]# docker checkpoint create 3af1bc07fbe4 testcp01

Error response from daemon: Cannot checkpoint container 3af1bc07fbe4: runc did not terminate successfully: exit status 1: criu failed: type NOTIFY errno 0 path= /run/containerd/io.containerd.runtime.v2.task/moby/3af1bc07fbe476ba40364c33f191f4d404dc9cea1a2e27e6ffa2064d73f204b7/criu-dump.log: unknown
```

check above log file, got below content
```
(03.006321) unix: Dumping external sockets
(03.006324) unix:       Dumping extern: ino 565231 peer_ino 565230 family    1 type    1 state  1 name /run/dbus/system_bus_socket
(03.006333) unix:       Dumped extern: id 0x430 ino 565231 peer 0 type 2 state 10 name 28 bytes
(03.006336) unix:       Ext stream not supported: ino 565231 peer_ino 565230 family    1 type    1 state  1 name /run/dbus/system_bus_socket
(03.006338) Error (criu/sk-unix.c:881): unix: Can't dump half of stream unix connection. name: (null); peer name: /run/dbus/system_bus_socket
(03.006413) net: Unlock network
(03.006437) Running network-unlock scripts
(03.006439)     RPC

```

I've checked 'docker checkpoint create' there is no options like 'criu dump --external unix[]'

my question here:
1. is it possible to checkpoint gnome desktop container with 'docker checkpoint'?
2. how could I use --external in docker?

**Describe the results you expected:**
container should be checkpointed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**CRIU logs and information:**
[criu-dump.log](https://github.com/user-attachments/files/16454232/criu-dump.log)

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
[root@laworks ~]# criu --version
Version: 3.19
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
[root@laworks ~]# criu check --all
Warn  (criu/cr-check.c:1346): Nftables based locking requires libnftables and set concatenations support
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

**Comment by coldbloodx** [comment]
@adrianreber 
Thanks for the quick response :)

> Checkpointing GUI applications is often not possible. Especially if those applications are using the GPU (using VNC is one possible workaround, but GUI applications usually do not work with CRIU). I would say it will probably not work.

some additional question.
our applications running on gnome/xfce4 desktop in a container, we're seeking some checkpoint/restore or live migration solutions.

since checkpoint whole GUI container is impossible, I have some other ideas here:
1. checkpoint/restore workload application inside container 
2. checkpoint/restore workload application out of container, use criu checkpoint/restore workload process tree directly.

for the idea 2, maybe it's a little bit crazy :), I did not think it's possible, cos the application container state/context are unknow, and not easy to checkpoint/restore.

for the idea 1, I've just made a try in my gui container, criu cannot pass check.

have you ever tried to run criu inside a container?
any thoughts on ideas above?

**Comment by adrianreber** [comment]
> since checkpoint whole GUI container is impossible

"Impossible" is a strong word here. It is very unlikely, but probably not impossible (depending on how much effort you want to put in).

> have you ever tried to run criu inside a container?

We do all the time. Most of our tests are running inside of containers. You need to start the container with `--privileged`. Depending on the application using `CAP_CHECKPOINT_RESTORE` might also be enough.

> any thoughts on ideas above?

I don't think I understand what your goal is with idea 2.

**Comment by coldbloodx** [comment]
already found a solution with vnc remote desktop.
