### ISSUE TITLE
CRIU restore fails due to segmentation fault with libc6 2.36-9+deb12u8

### ISSUE THREAD

**Issue by ghost** [checkpoint-restore/criu#2477]
**Description**

After the glibc package in Debian Bookworm was updated to [2.36-9+deb12u8](https://launchpad.net/debian/+source/glibc/2.36-9+deb12u8), `criu restore` fails with this error message:
`(00.012523) Error (criu/cr-restore.c:1499): 14598 killed by signal 11: Segmentation fault`

However, with glibc [2.36-9+deb12u7](https://launchpad.net/debian/+source/glibc/2.36-9+deb12u7) it works as expected.

**Steps to reproduce the issue:**
1. Follow the steps indicated in https://criu.org/Simple_loop on Debian Bookworm. Make sure the glibc version is 2.36-9+deb12u8. (This is the latest version at the time of writing).

**Describe the results you received:**

- Dump works
- Restore fails

**Describe the results you expected:**

- The restore command succeeds

**Additional information you deem important (e.g. issue happens only occasionally):**

This problem also occurs when dumping and then trying to restore a small test program written in c. The logs and information in this post are taken from a WSL Debian Bookworm installation, but I observed the same behavior in a virtual machine (x86_64) and a bare metal installation (arm64).

**CRIU logs and information:**

[dump.log](https://github.com/user-attachments/files/16983246/dump.log)
[restore.log](https://github.com/user-attachments/files/16983247/restore.log)

<details><summary>CRIU full dump/restore logs:</summary>
<p>

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 3.17.1
```
</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Warn  (criu/cr-check.c:813): Dirty tracking is OFF. Memory snapshot will not work.
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure
```

</p>
</details>

**Additional environment details:**

**Comment by adrianreber** [comment]
This is probably an error in the Debian CRIU package. It might be related to restartable sequences and some internal glibc structure that was changed without rebuilding CRIU. Can you try to rebuild CRIU on your system and if that works submit a bug in Debian.

**Comment by igmogo-ku** [comment]
Hi,

thanks for your response.

I build the package following this [tutorial](https://wiki.debian.org/BuildingTutorial). Unfortunately the problem persists.

Regards

**Comment by adrianreber** [comment]
I just tried CRIU in a debian bookworm container and can confirm that it does not work.

Rebuilding CRIU from git fixes this error for me.

Please report this error at Debian. They have to rebuild the package or upgrade to a newer version.

**Comment by adrianreber** [comment]
You can also use the binary packages we create. Please see: https://criu.org/Packages

The Debian 12 package also works in my test container.

**Comment by carnil** [comment]
Thanks, I will handle it downstream with https://bugs.debian.org/1081683

Note, criu for Debian in unstable is currently in a similar bad shape. I'm trying to get some traction in helping building the python part, but was so for not successful.

I will see how your own packages are built to maybe get the correct indication.

**Comment by adrianreber** [comment]
Let us know if you need any help.

**Comment by rst0git** [comment]
@carnil The following repository contains the files we use to build a deb packages:

https://github.com/rst0git/criu-deb-packages/tree/open-build-service/debian

**Comment by carnil** [comment]
I guess this is actually https://github.com/checkpoint-restore/criu/issues/1935 and cherry-picking the two commits cacddf19dad339f963b0b01f7174091b90c49e5d and f7972a3f0468e32231af6914e2e9c9e07ac53ae6 seem tosolve the issue.
