### ISSUE TITLE
Rebase criu-dev branch on 4.0 release

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#2485]
Hi @avagin, would it be possible to update the version of CRIU in the criu-dev branch?

Currently, this is set (in [Makefile.versions](https://github.com/checkpoint-restore/criu/blob/criu-dev/Makefile.versions)) to 3.18. However, in go-criu and runc we assume that if the CRIU version includes a git ID, the minor version should be incremented by one:
https://github.com/checkpoint-restore/go-criu/blob/39135d0112fa0fb12e80ba04ef843eea097add46/main.go#L253

**Comment by avagin** [comment]
pls verify that I didn't miss anything: https://github.com/checkpoint-restore/criu/tree/criu-dev-next

**Comment by rst0git** [comment]
I noticed that the [flog](https://github.com/checkpoint-restore/criu/tree/criu-dev/flog) patches are not in the `criu-dev-next` branch.

@avagin Could you confirm if this is intentional?
```console
$ git diff --stat criu-dev-next criu-dev
 Makefile                 |  12 ++++++-
 Makefile.versions        |   6 ++--
 flog/Makefile            |  29 +++++++++++++++++
 flog/built-in.S          |   4 +++
 flog/include/compiler.h  |  77 +++++++++++++++++++++++++++++++++++++++++++++
 flog/include/flog.h      |   9 ++++++
 flog/include/log.h       |  17 ++++++++++
 flog/include/types.h     |  16 ++++++++++
 flog/include/uapi/flog.h | 139 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 flog/include/util.h      |  41 ++++++++++++++++++++++++
 flog/src/Makefile        |   5 +++
 flog/src/flog.c          | 215 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 flog/src/main.c          | 158 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 flog/tests/test00        |  22 +++++++++++++
 14 files changed, 746 insertions(+), 4 deletions(-)
```

**Comment by avagin** [comment]
I moved flog in the separate branch: https://github.com/checkpoint-restore/criu/tree/wip/flog

**Comment by rst0git** [comment]
Thank you Andrei! It looks good to me.
