### ISSUE TITLE
Where is the SYS_PTRACE capability being used

### ISSUE THREAD

**Issue by leonard520** [checkpoint-restore/criu#2495]
**Description**

Recently, I've been experimenting with this project using OpenJDK's CRaC. I found that in order to perform checkpoint and restore, additional `sys_ptrace` permissions are required. It works with these permissions, but since `ptrace` has elevated privileges, I'm trying to understand in what scenarios it's actually needed. I did a test where I only granted the container `checkpoint_restore` capability, and it still completed the operation successfully. So, I'm wondering if it depends on specific application scenarios? If so, what are the scenarios where it's needed? Thank you!

**Comment by adrianreber** [comment]
I am confused. You say:

>  I found that in order to perform checkpoint and restore, additional sys_ptrace permissions are required.

and

>  I did a test where I only granted the container checkpoint_restore capability, and it still completed the operation successfully.

Do you see that `CAP_SYS_PTRACE` is needed or not. If it is not needed why do you think it might be necessary?

There is following line in the man-page:
```
criu also needs either CAP_SYS_PTRACE or a value of 0 in /proc/sys/kernel/yama/ptrace_scope (see ptrace(2)) to be able to interrupt the process for dumping.
```

Does that help?

**Comment by avagin** [comment]
> Recently, I've been experimenting with this project using OpenJDK's CRaC.

This is unprivileged single-user variant, so I think CAP_SYS_PTRACE is required only when yama policies are enabled:
https://www.kernel.org/doc/html/v4.15/admin-guide/LSM/Yama.html

**Comment by leonard520** [comment]
> I am confused. You say:
> 
> > I found that in order to perform checkpoint and restore, additional sys_ptrace permissions are required.
> 
> and
> 
> > I did a test where I only granted the container checkpoint_restore capability, and it still completed the operation successfully.
> 
> Do you see that `CAP_SYS_PTRACE` is needed or not. If it is not needed why do you think it might be necessary?
> 
> There is following line in the man-page:
> 
> ```
> criu also needs either CAP_SYS_PTRACE or a value of 0 in /proc/sys/kernel/yama/ptrace_scope (see ptrace(2)) to be able to interrupt the process for dumping.
> ```
> 
> Does that help?

Sorry, I mean that I read from [doc](https://docs.azul.com/core/crac/crac-guidelines#starting-an-application-in-a-docker-container) `SYS_PTRACE` is required but in my testing it seems not.

**Comment by leonard520** [comment]
> > Recently, I've been experimenting with this project using OpenJDK's CRaC.
> 
> This is unprivileged single-user variant, so I think CAP_SYS_PTRACE is required only when yama policies are enabled: https://www.kernel.org/doc/html/v4.15/admin-guide/LSM/Yama.html

Thanks for guiding! I will take a look.
