### ISSUE TITLE
criu 4.0 to OBS

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#2498]
I see that repos at https://download.opensuse.org/repositories/devel:/tools:/criu/ still have criu 3.19.

It makes sense to add a new version.

**Comment by kolyshkin** [comment]
@rst0git PTAL 🙏🏻

**Comment by kolyshkin** [comment]
Same for https://launchpad.net/~criu/+archive/ubuntu/ppa

**Comment by rst0git** [comment]
@kolyshkin Thank you for creating this issue. I will update the packages in OBS and Launchpad later today.

**Comment by rst0git** [comment]
@kolyshkin The packages in [OBS](https://build.opensuse.org/project/show/devel:tools:criu) and [Launchpad](https://launchpad.net/~criu) have been updated to v4.0.

**Comment by kolyshkin** [comment]
@rst0git thanks a lot! Perhaps you can add an item to https://criu.org/Releasing to not forget about these repos (the alternative is some cron jobs checking for new criu version -- I'm not sure it's possible without using third-party infra).
