### ISSUE TITLE
Setting ghost-limit in "docker checkpoint create" 

### ISSUE THREAD

**Issue by hanwen-flow** [checkpoint-restore/criu#2501]
I am trying to checkpoint a Java process, and am running into the same
issue as discussed in issue #491 (coincidentally, for me it is also
the Netty JNI `.so` causing problems; it seems that dlopen()ing a .so
file and then deleting it is the normal way that Java loads JNI files).

Could you share the recommended way to get Docker to specify `--ghost-limit`?

I don't understand why `--ghost-limit` exists; if a process is to be
checkpointed, shouldn't the ghost file be always be saved?

For posterity, I traced through how this works; presumably setting the
limit involves plumbing through the integer through all the code below.

**

The CRIU RPC protocol involves writing a protobuf
(https://github.com/checkpoint-restore/go-criu/blob/master/rpc/rpc.proto#L3)
over a connection inherited by the CRIU process. This protobuf
supports all criu options, including ghost_limit.

runc's criu support is in libcontainer, which supports its own set of options
https://sourcegraph.com/github.com/opencontainers/runc/-/blob/libcontainer/criu_opts_linux.go?L15
and lacks support for ghost_limit.

runc has a `checkpoint` command which constructs an instance of libcontainer options.
https://sourcegraph.com/github.com/opencontainers/runc/-/blob/checkpoint.go?L120

runc is invoked through the `go-runc` repo, which has its own set of runc
options
https://github.com/containerd/go-runc/blob/main/runc.go#L62. It has an
ExtraArgs field that could be used to pass options generically.

Docker daemon calls runc as a subprocess to manage the container, possibly through the code in containerd,
which has its own checkpoint options as specified in the oci protobuf
https://github.com/containerd/containerd/blob/main/api/types/runc/options/oci.proto#L39.

github.com/containerd/containerd inexplicably vendors itself, in
https://github.com/containerd/containerd/tree/main/vendor/github.com/containerd/containerd

The docker daemon's checkpoint code is here,
https://github.com/moby/moby/blob/master/daemon/checkpoint.go#L55
this repo also holds the client as a library, here
https://github.com/moby/moby/blob/master/client/checkpoint_create.go

Aforementioned library is used by the CLI, which is
https://github.com/docker/cli/blob/master/cli/command/checkpoint/create.go

**CRIU logs and information:**

```
....
(00.071958) Found regular file mapping, OK
(00.071993) Dumping path for -3 fd via self 14 [/tmp/libnetty_tcnative_linux_x86_647903423796204522932.so (deleted)]
(00.071996) Strip ' (deleted)' tag from './tmp/libnetty_tcnative_linux_x86_647903423796204522932.so (deleted)'
(00.071997) Dumping ghost file for fd 14 id 0x17
(00.071998) Error (criu/files-reg.c:1031): Can't dump ghost file /tmp/libnetty_tcnative_linux_x86_647903423796204522932.so of 2715648 size, increase limit
(00.072012) Error (criu/cr-dump.c:1570): Collect mappings (pid: 488576) failed with -1
```
<details><summary>Output of `criu --version`:</summary>
<p>

```00.000000) Unable to get $HOME directory, local configuration file will not be used.
(00.000029) Version: 3.18 (gitid v3.18-320-gdfb56eed6)
(00.000034) Running on hanwen-flow Linux 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
sudo criu check --all
sudo: mon_handle_sigchld: waitpid: No child processes
Looks good.
```

</p>
</details>

**Additional environment details:**

Ubuntu 22

**Comment by adrianreber** [comment]
Did you try to set it in `/etc/criu/runc.conf`? That should

**Comment by adrianreber** [comment]
I documented something similar here: https://www.redhat.com/en/blog/podman-checkpoint-restore-and-sql-server-2019

**Comment by hanwen-flow** [comment]
> Did you try to set it in /etc/criu/runc.conf? That should work.

yes, that worked! Could be documented better on the CRIU wiki. Can I just edit it?

**Comment by adrianreber** [comment]
> > Did you try to set it in /etc/criu/runc.conf? That should work.
> 
> yes, that worked! Could be documented better on the CRIU wiki. Can I just edit it?

If you have an account, sure. I am not sure what the steps are to get an account.

**Comment by rst0git** [comment]
> Could be documented better on the CRIU wiki

It is currently documented in https://criu.org/Docker#Passing_additional_options

**Comment by adrianreber** [comment]
@hanwen-flow please close the ticket if your problem is solved
