### ISSUE TITLE
Error with the combination of page-server and iterative migration

### ISSUE THREAD

**Issue by obsidian0215** [checkpoint-restore/criu#2503]
**Description**
I want to iteratively migrate a RunC container with page-server, so I tried to use pre-dump with --page-server. However, I found that criu finally dump the entire container which the pre-dumped pages transferred to destination by page-server did not effect the C/R process. I wonder how to combine --page-server with multiple pre-dump and a final dump.

**Steps to reproduce the issue:**
1. At destination, start a page server for pre-copy: `criu page-server --images-dir /runc/containers/redis-pre-d/parent0 --port 27 --auto-dedup -v4 -o /home/debian/CRIU-xiezuo/v4.0/dirty-track/mig-scripts/logs/ps.log`
2. At source, run a pre-copy iteration for the container "redis-pre-d": `runc checkpoint --pre-dump --page-server 192.168.37.154:27 --image-path parent0 redis-pre-d`
3. At source, checkpoint the container "redis-pre-d": `runc checkpoint --image-path image --shell-job --tcp-established --parent-path ../parent0 redis-pre-d`
4. At destination, restore the container "redis-pre-d": `runc restore --console-socket /runc/containers/redis-pre-d/console.sock -d --image-path /runc/containers/redis-pre-d/image --work-path /runc/containers/redis-pre-d/image --shell-job --tcp-established redis-pre-d`

**Describe the results you received:**
At source, I found that criu didn't write anything in parent dir, that dumped the entire container.
```
runc checkpoint --pre-dump --page-server 192.168.37.154:27 --image-path parent0 redis-pre-d finished after 1177.880 ms with 0
the total size of /runc/containers/redis-pre-d/parent0 with pattern pages is 0Byte
runc checkpoint --image-path image --shell-job --tcp-established --parent-path ../parent0 redis-pre-d finished after 427.326 ms with 0
DUMP size: 153M	/runc/containers/redis-pre-d/image
Transferring DUMP to 192.168.37.154

sent 24.55M bytes  received 1.18K bytes  16.36M bytes/sec
total size is 159.80M  speedup is 6.51
DUMP transfer time 1037.512 ms
the total size of /runc/containers/redis-pre-d/image is 152.4MB
```
![image](https://github.com/user-attachments/assets/2836d76f-c821-4e14-a124-97ed930cdcef)

At destination, I got pagemaps and pages images in parent dir, which means page-server worked. However, the image dir still contained pagemaps and pages images which are bigger than those in parent dir.
![image](https://github.com/user-attachments/assets/8d24ef31-7644-48f7-97ce-04e171694b02)
(I'm sorry that this pic cannot show the size differences between page images)
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**
dump.log showed that criu cannot find the parent pagemap.img since the parent dir is empty.
![image](https://github.com/user-attachments/assets/f80c08cc-ef48-4612-b1ca-3b62661d5662)

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 4.0
GitID: v3.19-167-g600f69f59
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**
Debian 12.5, Linux 6.1.111

**Comment by avagin** [comment]
This configuration doesn't supported right now. It makes sense but it has never been implemented. CRIU wants to open parent pagemap images to dump pages: https://github.com/checkpoint-restore/criu/blob/dfb56eed62f2b1dd7eaf830f44ae83eca6a1dc46/criu/page-xfer.c#L377.

It should not be hard to support this configuration. If you are willing to implement it, we are happy to help with advice.

**Comment by obsidian0215** [comment]
> This configuration doesn't supported right now. It makes sense but it has never been implemented. CRIU wants to open parent pagemap images to dump pages:
> 
> https://github.com/checkpoint-restore/criu/blob/dfb56eed62f2b1dd7eaf830f44ae83eca6a1dc46/criu/page-xfer.c#L377
> 
> .
> It should not be hard to support this configuration. If you are willing to implement it, we are happy to help with advice.

Thanks a lot. I think I will make some effort to implement this configuration later. This issue can be closed at this point, since I will open another issue for help of implementation.
