### ISSUE TITLE
crit not found after installing criu

### ISSUE THREAD

**Issue by tamaroning** [checkpoint-restore/criu#2506]
**Description**

After installing criu with apt, the criu command work but crit is not found

```sh
$ crit
Command 'crit' not found, but can be installed with:
sudo apt install criu
$ criu --version
Version: 4.0
```

**Steps to reproduce the issue:**
1. `sudo add-apt-repository ppa:criu/ppa`
2. `sudo apt install criu`

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
Version: 4.0
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
Warn  (criu/cr-check.c:824): Dirty tracking is OFF. Memory snapshot will not work.
Warn  (criu/cr-check.c:1259): Do not have API to map vDSO - will use mremap() to restore vDSO
Warn  (criu/cr-check.c:1348): Nftables based locking requires libnftables and set concatenations support
Warn  (criu/cr-check.c:1179): CRIU built without CONFIG_COMPAT - can't C/R compatible tasks
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**

Raspberry Pi 4 Model B
Ubuntu 24.04.1 LTS

**Comment by rst0git** [comment]
@tamaroning Thank you for opening this issue! I've updated the criu package in Launchpad with a fix for this problem and it is currently  pending publication.

**Comment by tamaroning** [comment]
@rst0git 
Thank you very much!
I confirmed crit is installed after running the commands.
