### ISSUE TITLE
podman instructions do not work.

### ISSUE THREAD

**Issue by hanwen-flow** [checkpoint-restore/criu#2523]
**Description**

the instructions at https://criu.org/Podman do not work. I tested on Ubuntu 22.04 and Fedora 39. The symptoms are the same,
```
hanwen@hanwen-flow:~/vc/ci-experiments$ podman run -d --name looper2 busybox /bin/sh -c \
         'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
6efa431f914bf306432284e9b052105153ea6eef1f1b531a79366c7825bd2412
hanwen@hanwen-flow:~/vc/ci-experiments$ podman logs -l
0
1
2
3
4
5
6
7
8
9
10
11
12
hanwen@hanwen-flow:~/vc/ci-experiments$ sudo podman container checkpoint -l
Error: no such container
hanwen@hanwen-flow:~/vc/ci-experiments$ sudo podman container checkpoint looper2
Error: no container with name or ID "looper2" found: no such container
hanwen@hanwen-flow:~/vc/ci-experiments$ podman ps
CONTAINER ID  IMAGE                             COMMAND               CREATED         STATUS             PORTS       NAMES
a96ca5ad012d  docker.io/library/busybox:latest  /bin/sh -c i=0; w...  16 hours ago    Up 16 hours ago                looper
6efa431f914b  docker.io/library/busybox:latest  /bin/sh -c i=0; w...  42 seconds ago  Up 42 seconds ago              looper2
hanwen@hanwen-flow:~/vc/ci-experiments$ podman -v
podman version 3.4.4
```

Fedora 39 runs podman 5.2.3 but fails in the same way.

**Comment by hanwen-flow** [comment]
I suspect this is due to 

> Checkpoints currently work with root containers only. Therefore, you have to run the example container as root.

https://podman.io/docs/checkpoint

this could be more obvious in the criu docs.

**Comment by hanwen** [comment]
note that the slowness I referred to in https://github.com/checkpoint-restore/criu/issues/2523#issuecomment-2485462783 was on my Fedora 40 personal machine.

**Comment by rst0git** [comment]
@hanwen-flow Thank you for opening this issue. I have updated the criu docs with your suggestions.

The following option may help with obtaining more detailed information on the performance of CRIU and Podman:
```
podman container checkpoint --print-stats ...
```

**Comment by hanwen-flow** [comment]
:+1:

**Comment by hanwen** [comment]
I tried repro'ing the wait in https://github.com/checkpoint-restore/criu/issues/2523#issuecomment-2485462783, by clearing out /var/lib/containers and reinstalling podman, but the problem did not reproduce.

**Comment by hanwen-flow** [comment]
The slowness looks suspiciously like https://github.com/checkpoint-restore/criu/issues/2032
