### ISSUE TITLE
criu fails for RDMA programs

### ISSUE THREAD

**Issue by wangchenghku** [checkpoint-restore/criu#267]
Even with `--tcp-established`, CRIU still fails to dump a program with RDMA (Remote Direct Memory Access). The dump log is below:
```
Error (criu/proc_parse.c:551): Can't handle non-regular mapping on 98391's map 7fb222c9e000
Error (criu/cr-dump.c:1213): Collect mappings (pid: 98391) failed with -1
Error (criu/cr-dump.c:1636): Dumping FAILED.
```

**Comment by xemul** [comment]
Yes, that's because RDMA implies having a memory mapping of special file in process' address space. We don't have expertise in this area to provide support in CRIU code, but if you're willing to help somehow -- you're very welcome :) On our side we are fully open for any type of collaboration.

**Comment by dav-ell** [comment]
Do you guys have a timeline for when you anticipate being able to work on this? I'm also coming across this error, and I doubt my chances of being able to add this feature in any reasonable period of time.

**Comment by xemul** [comment]
@dav-ell , it's hard to say. The first obstacle we have is the lack of hardware to play with. Also, the active criu team is quite small at the moment, most of the time we can devote to the project is around the needs that don't have rdma in it. However, we can discuss other forms of collaboration, feel free to ping me on xemul (at) openvz (dot) org.

**Comment by dav-ell** [comment]
@xemul , my problem may actually be better suited for another issue. The error is:

```
(00.017654) cg:         Making controller dir .criu.cgyard.Wyi7us/rdma (rdma)
(00.017679) Error (criu/cgroup.c:1700): cg:     Can't mount controller dir .criu.cgyard.Wyi7us/rdma: No such file or directory
```

which is more closely related to an [issue](https://github.com/lxc/lxd/issues/3715) someone had in LXD, referencing CRIU.

**Comment by dav-ell** [comment]
My error was indeed unrelated to this issue and was caused by differing kernel versions on the two hosts I was using. [Apparently](https://github.com/opencontainers/runtime-spec/pull/942) RDMA was added to the linux kernel in 4.11, so checkpointing on one host with 4.11 or higher and restoring on another host with less than 4.11 will cause the error I had. A workaround is to make the kernel versions the same on each host.

**Comment by adrianreber** [comment]
@LianJieZhang no. In the future please a open a new ticket for new problems/questions?
