### ISSUE TITLE
Restore performance degrades linearly on breakpoints inside Xen (EC2 instance)

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#268]
I'm using criu through docker 1.13 to C/R containers. Specifically I'm cloning containers by checkpointing one container, and then restoring N copies from that single image. At the moment, we are restoring 45 copies, one at a time. I've noticed that as we progress through these 45 restores, each one takes longer than the last, and the relationship is almost perfectly linearly. The first restore takes about 2 seconds, but the 45th restore takes ~16-18 seconds. Looking at the criu restore logs, almost all of that time is used by criu (as opposed to docker), and almost all of criu's time looks to be spent restoring seccomp and apparmor settings. In my latest run, restoring these settings for the 45th container took up 15.8 of the 16.6 seconds for the restore. However, restoring these settings for the 1st container took less than 0.1 seconds.

I'm attaching the restore log from both the 1st and 45th containers. I've tried using the --privileged option for my docker containers which disables both seccomp and apparmor, but this didn't fix the issue.

Here is the restore time data I collected from an earlier run:

[1.89, 1.73, 1.99, 2.30, 2.59, 2.70, 3.51, 4.99, 7.57, 4.48, 4.31, 4.44, 4.75, 5.17, 5.49, 5.86, 6.14, 6.16, 6.49, 6.78, 7.11, 7.38, 7.71, 7.96, 8.37, 8.64, 8.83, 9.22, 9.50, 9.87, 10.16, 10.65, 11.10, 11.31, 11.60, 12.11, 12.41, 12.96, 13.42, 14.10, 14.67, 15.23, 16.48, 17.22, 18.00]

If you plot this you'll see it's almost perfectly linearly (Note this is docker restore time, not criu restore time, but as I mentioned above, criu takes up almost all of the docker restore time).

I'm using criu 2.9 and Linux kernel 4.4.39.
[restore1.txt](https://github.com/xemul/criu/files/690776/restore1.txt)
[restore45.txt](https://github.com/xemul/criu/files/690775/restore45.txt)

**Comment by xemul** [comment]
@tswift242 , the very first question while looking at the log files -- what are the "REMOVED" lines in them?

**Comment by xemul** [comment]
@tswift242 , but logs show that seccomp mode 2 (filter) is restored anyway, so --privilidged doesn't seem do help. Did you use the option only for restore?

**Comment by tswift242** [comment]
@xemul Thanks for looking at this issue. The "REMOVED" lines correspond mostly to filesystem paths; I had to censor the log files a bit, like I did for other issues I've created here. I don't think anything too important was removed.

The log files I provided are from when I did not use --privileged. For these logs, I did not change the docker security options at all. I just tried using --privileged as a test to see if it would make a difference, but it did not surprisingly. When I did this I provided the option on both checkpoint and restore.

**Comment by xemul** [comment]
OK, let's try to start with simple things. Here's the patch (9240f58388336dbcd82a58b39bf369ca5f1f3fce) to add timestamps to final stages of restore (or pick the br-2.9-rst-slow branch). Can you grab "slow" logs with this one applied? So we could see what's happening between 0.6 and 16.0 timestamps :)

Cc @tych0

**Comment by tswift242** [comment]
@xemul I've built criu with that patch, and I'm attaching the restore log for the 45th container in my deployment. The restore takes ~18.1 seconds. The last thing it prints before saying "Restore finished successfully" is "restoring lsm profile changeprofile docker-default". So, it seems that either restoring the default docker AppArmor profile is taking 17+ seconds, or something else is taking a lot of time, but not logging anything to the restore log.
[restore45.txt](https://github.com/xemul/criu/files/694408/restore45.txt)

**Comment by tswift242** [comment]
@xemul I added a bunch more logging to criu for the final restore stages, and it looks like the issue is actually not with seccomp or apparmor. All the time is spent in catch_tasks() (https://github.com/xemul/criu/blob/a7faf367a6b2e215a86f2fffe785c63aa3902c96/criu/cr-restore.c#L1466), and specifically within ptrace_stop_pie() (https://github.com/xemul/criu/blob/a7faf367a6b2e215a86f2fffe785c63aa3902c96/criu/cr-restore.c#L1492). When there are 44 containers already running, while restoring the 45th, each call to ptrace_stop_pie() takes ~70 ms, and there are many such calls. When there are no containers running and I'm doing the 1st restore, there are the same number of calls to ptrace_stop_pie(), but each call takes less than 1 ms. I'm attaching the new restore logs for the 1st and 45th containers.

Any idea why the cost of this call increases for each container that is running on the system? Keep in mind each container is restored from the same image; is that a factor somehow? Is there any other logging or info I can provide to help with the investigation?




[restore1.txt](https://github.com/xemul/criu/files/694696/restore1.txt)
[restore45.txt](https://github.com/xemul/criu/files/694695/restore45.txt)

**Comment by xemul** [comment]
@tswift242 , are you running it in a VM or on hardware? The part you've found uses hardware breakpoints to trace tasks to the resume point, which can sometimes be slow. Try disabling the breakpoints (criu will use step-by-step tracing, everything will continue working) with exporting environment variable 'CRIU_FAULT=130'

Cc @avagin

**Comment by tswift242** [comment]
@xemul This is running on a VM, an ec2 instance using a Xen hypervisor and HVM virtualization. I did "export CRIU_FAULT=130" and then tried restoring another container, but I don't think the environment variable took affect. I'm assuming that with this set I should see this line in the debug log, but I don't: https://github.com/xemul/criu/blob/a7faf367a6b2e215a86f2fffe785c63aa3902c96/criu/parasite-syscall.c#L1432. Is there anything else I need to do like rebuild criu?

**Comment by xemul** [comment]
@tswift242  :( yes, the environment didn't get to the CRIU. Does runc sanitized environment? Or maybe CRIU gets launched by dockerd/containerd who don't see this env?

Anyway, since you're patching it all around :) just pick the commit https://github.com/xemul/criu/commit/255d8f315197babc3ea16c1506bb36bbb89f0074, I've disabled breakpoints there.

**Comment by tswift242** [comment]
@xemul Yep, it looks like docker/containerd/runc don't pass the environment to criu. :( I'll create an issue to them about that.

Anyway, disabling the breakpoints through your patch fixed the issue! The restore now takes 1 second, even with 44 other containers running. Is there a reason that using the hardware breakpoints is the default? You said they can sometimes be slow. Are there cases where it's better to use the hardware breakpoints than the alternate approach?

**Comment by xemul** [comment]
@tswift242 , whee! :)

The reason for hardware breakpoints is (surprisingly) the performance :) This very last stage of resume used to work on step-by-step tracing of a bunch of syscalls the restored tasks did. We didn't like this (too many ptrace() calls) and did speed this up (in KVM and on bare metal) by placing a breakpoint the way GDB does before the very last syscall. But it looks like in Xen hypervisor this slows things down not speeds it up :(

**Comment by tswift242** [comment]
@xemul That makes sense. I'd expect the hardware breakpoint approach to perform better in general too. Is there anything that can be done on the criu side to speed this up on Xen? AWS EC2 instances all run on Xen, so running criu on this platform should be a fairly common case. The CRIU_FAULT=130 work around would be great, except for the fact that docker doesn't seem to pass the environment to criu (I've created https://github.com/docker/docker/issues/30031). Any theories as to why this call doesn't scale well with the number of running containers?

**Comment by cyrillos** [comment]
An option might be to inject int3 (or similar instruction on other archs) before sigreturn call and then wait for single sigreturn syscall only. This could improve the situation I think but require significant amount of code to add ;)

**Comment by xemul** [comment]
Yeah, it's a tough question :\  Taking into account EC2 case is quite common, we'd better temporary disable this mode in the next release (the performance loss we'll have will not be disastrous) and think on fixing this properly with int3 or similar later.

@avagin , what do you think?

**Comment by JoeCEngineer** [comment]
+1 for getting EC2 case working by default in the short term

**Comment by tswift242** [comment]
@xemul That sounds like a good plan to me. It would be much appreciated!

**Comment by avagin** [comment]
@xemul I don't like the idea to disable breakpoints without understanding reasons.

@tswift242 Could you try out this commit https://github.com/avagin/criu/commit/2264e59d790515b0fe4bec3ee1a34911a234ff9f ?

**Comment by xemul** [comment]
@avagin , sure, I told "temporary", since the next release is several days ahead ;)

**Comment by tswift242** [comment]
@avagin Unfortunately that commit did not fix the issue (I was supposed to apply it on top of criu-dev, right?). I still see the same performance degradation.

**Comment by tswift242** [comment]
@xemul Unless a better option comes along (perhaps @avagin has other patch ideas I can try), can we move forward with the plan to temporarily disable the hardware breakpoints in the next release?

**Comment by xemul** [comment]
@tswift242 , of course! That's the current plan :)

**Comment by tswift242** [comment]
@xemul Awesome! Glad to hear that! :)
