### ISSUE TITLE
Add /etc/criu.conf and/or /etc/criu.d/ dir

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#278]
For generic and common stuff it would be nice to keep things there.

**Comment by xemul** [comment]
Cc-ing @adrianreber

**Comment by adrianreber** [comment]
@veruu posted a first patch to get a configuration file on the criu mailing list:

https://lists.openvz.org/pipermail/criu/2017-March/036731.html

The initial patch add negative boolean options so that options enabled in the configuration can be disabled on the command-line if required.

**Comment by lizhi16** [comment]
I want to use --ghost-limit in docker CLI(docker version 17.09-ce), but docker still doesn't have it. I use criu3.6, there is not /etc/criu.conf and/or /etc/criu.d/ dir. Please tell me how to solve it, thanks!

**Comment by lizhi16** [comment]
I want to use --ghost-limit in docker CLI(docker version 17.09-ce), but docker still doesn't have it. I use criu3.6, there is not /etc/criu.conf and/or /etc/criu.d/ dir. Please tell me how to solve it, thanks! @xemul @

**Comment by adrianreber** [comment]
Configuration files are only available on the development branch ```criu-dev``` right now. It is also not clear how to handle he RPC case (how docker uses it). So not possible yet easily.

**Comment by lizhi16** [comment]
I installed criu-dev, but I still can't find /etc/criu.conf and/or /etc/criu.d/ . Could you tell me where is the configuration file? thank u so much!

**Comment by lizhi16** [comment]
I installed criu-dev, but I still can't find /etc/criu.conf and/or /etc/criu.d/ . Could you tell me where is the configuration file? thank u so much! @adrianreber

**Comment by adrianreber** [comment]
You have to create the files yourself, but as docker uses RPC to call CRIU it will not work as CRIU via RPC does not (yet) read the configuration file. So it needs code changes to CRIU to work. This is still being discussed on the mailing list.

**Comment by lizhi16** [comment]
I have solved this problem. I modified `#define DEFAULT_GHOST_LIMIT	(1 << 20)` to `#define DEFAULT_GHOST_LIMIT	(1 << 30)`, and it work well. Thanks for your help!

**Comment by lizhi16** [comment]
@farooqte96 you can modify criu/criu/include/cr_options.h

**Comment by farooqte96** [comment]
Thanks ! I made necessary change to criu/criu/include/cr_options.h but getting same error of increase size.

**Comment by adrianreber** [comment]
Configuration file support in RPC mode has been merged into the development branch : https://github.com/checkpoint-restore/criu/commit/d1439a67468d86e73b5df275dd352258fd8d5187

**Comment by adrianreber** [comment]
Available in CRIU since 3.11
