### ISSUE TITLE
Docker restore doesn't work on freshly created container (on any FS that differs from the checkpoint-time one)

### ISSUE THREAD

**Issue by andremichaud** [checkpoint-restore/criu#289]
There are two ways I've tried to use the checkpoint (created with checkpoint-dir). The first way is run a container, checkpoint it, then start it again using the checkpoint. When done this way everything seems to work ok.  If i stop the container and then try to start it using that same checkpoint, though, I get an error like the one below. So only the first start with a checkpoint works. Subsequent ones fail.

The second way is that i run a container, checkpoint it, create a new container and then try to start that new container using the checkpoint. When done this way it fails every time with an error like the one below.

**The error I get when trying to start the container with the checkpoint:**
Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0

**Errors in the log:**
sudo cat /tmp/checkpoint1/criu.work/restore-2017-03-10T11:01:36-05:00/restore.log | grep Error
(23.949053)     58: Error (criu/files-reg.c:1565): Can't open file var/data/dbdata/pg_log/postgresql-2017-03-10_152046.log on restore: No such file or directory
(23.949083)     58: Error (criu/files-reg.c:1504): Can't open file var/data/dbdata/pg_log/postgresql-2017-03-10_152046.log: No such file or directory
(23.977095)     57: Error (criu/cr-restore.c:1009): 58 exited, status=1
(24.131964) Error (criu/cr-restore.c:1012): 16421 killed by signal 9: Killed
(24.178789) Error (criu/cr-restore.c:1897): Restoring FAILED.

**sudo criu check --all**
Warn  (criu/cr-check.c:705): Dirty tracking is OFF. Memory snapshot will not work.
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

**sudo criu check -V**
Version: 2.11

**cat /etc/redhat-release**
Red Hat Enterprise Linux Server release 7.2 (Maipo)

**docker version**
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64
 Experimental: true

**cat /proc/version**
Linux version 4.10.1-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Sun Feb 26 19:47:48 EST 2017

**Comment by xemul** [comment]
The file  var/data/dbdata/pg_log/postgresql-2017-03-10_152046.log is kept on ephemeral layer which is lost when you do anything with the container but restore from the previously created image.

Cc @boucher

**Comment by boucher** [comment]
Yes, you need to also "docker commit" the filesystem, and use that filesystem in any new container you create.

**Comment by andremichaud** [comment]
makes complete sense and resolved the error for me. thanks so much for the prompt replies!

**Comment by xemul** [comment]
@tych0 , may I please draw your attention to this? :)
Is there a chance, that "docker checkpoint" command adds some ID of the filesystem being in use and "docker start from checkpoint" refuses to restore on a "wrong" root? This is quite a frequent complain from Docker users, half of the issues we have here are about this scenario.

**Comment by tych0** [comment]
What about if "docker checkpoint" did a "docker commit" for you?

**Comment by xemul** [comment]
Presumably ... yes. I think. But not only this. The "docker restore" (or whatever it's called) should check for the root FS being correct too. Or do "check checkout" (or whatever is't called).

**Comment by xemul** [comment]
Ccing @avagin here too.

**Comment by xemul** [comment]
Let's keep this issue open until we find out the proper way to handle this on the Docker/RunC side.

**Comment by bhaktibohara** [comment]
@andremichaud  how did you move the image for restore? I am facing similar error and I checked on internet, where they show to save and load the image. This is taking alot of time. I am trying to use the checkpoint restore to live migrate, hence I cannot lose connections and as well keep the down time to minimum. Any guidance will be helpful.

**Comment by andremichaud** [comment]
@bhaktibohara I am not moving images for restore - everything is one the same machine (for now at least)

**Comment by pmontrasio** [comment]
The fix of doing a `docker commit` didn't work for me.

```
docker run --name container --security-opt seccomp:unconfined image command
docker checkpoint create --checkpoint-dir=dir container checkpoint
docker commit container new-image
docker create --name container2 --security-opt seccomp:unconfined new-image command
docker start --checkpoint-dir=dir container2 checkpoint
```

I get several errors in the log file. Among them

```
(07.981876)    222: Error (criu/files-reg.c:1528): Can't open file dev/shm/PostgreSQL.1804289383 on restore: No such file or directory
(07.981879)    222: Error (criu/files-reg.c:1463): Can't open file dev/shm/PostgreSQL.1804289383: No such file or directory
(07.981881)    222: Error (criu/mem.c:907): `- Can't open vma
(08.048017) Error (criu/cr-restore.c:1024): 11619 killed by signal 9: Killed
```

**Comment by andremichaud** [comment]
The fix for me was to do run the container, do the commit and then take the checkpoint. It looks like you've switched the order of the last two things. It did also help me to wait a little bit (~1 minute) after starting the container before doing the commit because without this i was getting intermittent criu bad file size errors.

**Comment by pmontrasio** [comment]
I tried to do the commit before the checkpoint to no avail. I believe that the database in my container is never at rest and some files get created or deleted in the time between the commit and the checkpoint, no matter the order. Unfortunately we can't checkpoint a paused container.
It would be great if we could do that, or if there would be an atomic checkpoint for both CPU, RAM and file system.

**Comment by boucher** [comment]
Not that this is an ideal answer, but are you able to stop sending traffic
to your database prior to checkpointing? In our setup, we have pretty tight
control over the process, so we're able to guarantee its not really doing
anything while we checkpoint.

**Comment by pmontrasio** [comment]
It's not the normal case of a one process per container. It's a third party application with at least a Java application server and PostgreSQL running inside the container. It's much like a black box for us. No source code either. I will check if at least I can stop the PostgreSQL inside the container and start it again after resuming from the checkpoint.

**Comment by xemul** [comment]
Cc @avagin . Andrey, I guess we need the "checkpoint paused container" feature soon.

**Comment by avagin** [comment]
It is in a queue: https://github.com/opencontainers/runc/pull/1355/commits/73258813d37effc24075c1d6333b18441da18447

**Comment by xemul** [comment]
Cool, thanks!

**Comment by mj41** [comment]
@andremichaud I have also similar use case and can't make it work. See https://gist.github.com/mj41/44296e0a976364433277300e21f96303

**Comment by richardweib** [comment]
+1

**Comment by andremichaud** [comment]
@mj41 my magic sauce was to start the container, wait for activity against the database to stop (or if you can as recommended above by boucher, stop all activity to the database), do a docker commit and then take the checkpoint. I then use the image created when doing the commit if i want to start a container using the checkpoint.
