### ISSUE TITLE
Auto-freeze cgroup dumping tasks live in

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#295]
As proposed in #293 by @boucher, it would be much much more convenient if CRIU freezes the cgroup tasks live in w/o any specific CLI option.

The proposal that seems to work would be in checking that the root task parent cgroup differs from the one of the root task itself and freezing the latter one.

Cc @avagin

**Comment by avagin** [comment]
https://github.com/avagin/runc/commit/447eebc3ddf959a36ff2f558eea6a8d0215aec78

But a container is restored into the unfrozen state:
```
(00.018311) cg: Preparing cgroups yard (cgroups restore mode 0x4)
...
(00.020829) cg: Skip restoring properties on cgroup dir freezer//config
```
