### ISSUE TITLE
Absence of time namespace causes some apps (Oracle) to crash after restore

### ISSUE THREAD

**Issue by steffengy** [checkpoint-restore/criu#296]
# Summary
Running an Oracle 11g XE container works as expected.
Creating and restoring a snapshot (using docker, which uses CRIU) itself also works.

The problem is that after the restore, the oracle processes crash becauseof a segfault.
(likely SysVIPC related, according to a stacktrace walkthrough [here](https://community.oracle.com/message/14023602#14023602).

The comments in the reproduction below explain some of what seems to go on.

# Reproduction
The following was run on a fresh Ubuntu 16.10.
```shell
# Install Docker on Host ( 17.03.0-ce / 3a232c8 )
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update && sudo apt-get install -y docker-ce

# Compile CRIU [ 36ebce8d9cf1b05cec691c642fc63fc8bfe44918 ] & put Docker into experimental mode
sudo apt-get install -y libaio-dev build-essential libnet1-dev pkg-config libnet1-dev
sudo apt-get install -y libprotobuf-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libcap-dev
sudo apt-get install -y --no-install-recommends asciidoc xmlto
git clone --depth=1 https://github.com/xemul/criu.git && cd criu && make install
echo "{\"experimental\": true}" > /etc/docker/daemon.json
sudo service docker restart

# Run a oracle DB
docker run -d --shm-size=2g -p 1521:1521 -p 8080:8080 --name inspiring_swirles alexeiled/docker-oracle-xe-11g
docker checkpoint create inspiring_swirles test
docker start inspiring_swirles --checkpoint test
docker exec -it inspiring_swirles /bin/bash
cat /u01/app/oracle/diag/rdbms/xe/XE/trace/alert_XE.log
# This shows a time drift first, but that's only a warning
#  VKTM detected a time drift. Please check trace file for more details.
#  GEN0 (ospid: 43): terminating the instance due to error 472
#  Instance terminated by GEN0, pid = 43
# So the actual error happened in GENO, so let's take a look at that (the number after gen0 might be different case)
cat /u01/app/oracle/diag/rdbms/xe/XE/trace/XE_gen0_43.trc

# skgvtime: process 35 unix pid wrap detected 1115231 1138692
# kjzduptcctx: Notifying DIAG for crash event
# ----- Abridged Call Stack Trace -----
# ksedsts()+461<-kjzdsssd()+279<-kjzdechk()+298<-kjzdicrshnfy()+53<-ksuitm()+1325<-ksuinstalive()+64<-ksumcl()+33<-ksbasend()+1373<-ksbabs()$
# <-_start()+37
# ----- End of Abridged Call Stack Trace -----
# GEN0 (ospid: 43): terminating the instance due to error 472
# So an uninteresting PID wrap and a crash (segfault) which caused the whole instance to shutdown.
# A walkthrough for a similar stacktrace can be found in the link posted above.
```

**Comment by xemul** [comment]
Cc @cyrillos and @avagin

**Comment by cyrillos** [comment]
First of all -- thanks a *huge* for report! And sorry for delay in reply. I'll try to reproduce this issue on next week and report the details.

**Comment by cyrillos** [comment]
Gonna take a look tomorrow.

**Comment by cyrillos** [comment]
I think the issue might be a side effect of https://github.com/xemul/criu/issues/287

**Comment by cyrillos** [comment]
Because ubuntu is based on criu-2.6 the fix is not there of course.

**Comment by cyrillos** [comment]
With latest criu-dev I'm getting
root@ubuntu:~# docker start inspiring_swirles --checkpoint test
Error response from daemon: oci runtime error: container_linux.go:1036: running prestart hook 0 caused "error running hook: exit status 1, stdout: , stderr: time=\"2017-03-29T14:32:00+03:00\" level=fatal msg=\"failed to add interface veth81c3ef5 to sandbox: error renaming interface \\\"veth81c3ef5\\\" to \\\"eth0\\\": file exists\" \n"

**Comment by cyrillos** [comment]
Is there a way to say disable network inside container completely?

**Comment by steffengy** [comment]
@cyrillos 
> Because ubuntu is based on criu-2.6 the fix is not there of course.

I tested using the *latest CRIU-master* [ 36ebce8d9cf1b05cec691c642fc63fc8bfe44918 ], as
you can see in the instructions which install that version, so if the issue is fixed in 2.6,
that can't be the issue?

I can only say that the steps mentioned above work on a clean ubuntu 16.04, maybe your 
docker veth-renaming issue is fixed in a new docker version?

As a workaround, for disabling network, maybe passing ```--net none``` to docker run works?

**Comment by cyrillos** [comment]
Thanks, will try with --net none

**Comment by cyrillos** [comment]
With --net none it restores just fine, but I fear it's because oracle didn't work properly when run without net.

**Comment by cyrillos** [comment]
heh, with latest master now it fails as
> (02.216512)      1: Error (criu/mount.c:701): mnt: 231:/tmp/.criu.mntns.MhxlRe/12-0000000000/sys/fs/cgroup/systemd doesn't have a proper root mount

**Comment by cyrillos** [comment]
I'll back once I found more details.

**Comment by cyrillos** [comment]
It looks like a process waiting for IPC message but on dump queue is empty and we don't restore anything. Hard to tell why exactly that. Need to think if there some way to debug the situation.

**Comment by avagin** [comment]
```

{
           "fstype": 5, 
           "mnt_id": 800, 
           "root_dev": "0:127", 
           "parent_mnt_id": 779, 
           "flags": "0x20000e", 
           "root": "/dev/shm", 
           "mountpoint": "/dev/shm", 
           "source": "shm", 
           "options": "size=2097152k", 
           "shared_id": 0, 
           "master_id": 0, 
           "ext_mount": true, 
           "sb_flags": "0x0"
       },
```
CRIU doesn't dump the content of /dev/shm, because it think that /dev/shm is an external mapping

**Comment by avagin** [comment]
The same problem is in https://github.com/xemul/criu/issues/300

**Comment by avagin** [comment]
@kolyshkin reproduces the problem on his host and we found that /dev/shm isn't a fatal problem in this case. The more serious issue is that Oracle is monitoring starttime (/proc/pid/stat) for each its processes and if starttime has changed for one of them, Oracle decides to stop all processes. It is what we see after restoring a container.

**Comment by xemul** [comment]
https://criu.org/Time_namespace

**Comment by dineshputchala** [comment]
@xemul  any plans on when this will get implemented ? Is this new feature to be implemented in criu or kernel ?

**Comment by adrianreber** [comment]
This needs to be implemented first in the kernel and then in CRIU. It comes up regularly in discussions but as far as I know nobody is working on it.
