### ISSUE TITLE
Is there a (sane) way to migrate a checkpointed container to a different server?

### ISSUE THREAD

**Issue by jmserre** [checkpoint-restore/criu#303]
High level requirements: Use CRIU to Speeding up slow-start containers (>5 minutes)
and restart several instances of the same thing on different servers.

My experiment.

I have two servers (A and B) with identical 
CRIU  (2.11)
docker (experimental flag)
docker --version
Docker version 17.03.0-ce, build 60ccb22
(storage driver overlayfs2)
Exactly the same images on A and B (nothing less, nothing more)
On both server I can start my stuff
(docker-compose 3 containers)
can checkpoint/restore the container I am interested in on either of them. (do a docker commit before the docker checkpoint)

Now I tried to checkpoint on A copy to B and restart from there. I ran into issues such as 

1: Error (criu/files-reg.c:1520): File nlps-uima-as.gc.0.current has bad size 0 (expect 1051)
(05.225492) Error (criu/cr-restore.c:1012): 8261 killed by signal 9: Killed
(05.249742) mnt: Switching to new ns to clean ghosts
(05.262219) Error (criu/cr-restore.c:1897): Restoring FAILED.)
But I went past that by copying everything from var/lib/doclker/overlay2 from A to B.

So to be exact I restart fresh containers on B.  Kill the one I want to restore.
 I am copying everything related to my container from A to B including relevant /var/lib/docker/container/xxxxxx    to /var/lib/docker/container/yyyyyyy  (including check point. data) and everything from overlayfs2 from A to B  (including the softlinks in 'l').  Note (in B) I am not overwriting anything in overlayfs2  just adding in the layers created in A.

My last attempt ended up with ,.....

(04.894233)      1: Found fd 409 (id pipe:[320016510]) in inherit fd list (caller inherit_fd_resolve_clash)
(04.894241)      1: Inherit fd 409 moved to 413 to resolve clash
(04.894248)      1:             Create fd for 409
(04.894258)      1:     Restore: family 10 type 1 proto 6 port 34880 state 1 src_addr ::ffff:172.19.0.4
(04.894276)      1: Restoring TCP connection
(04.894286)      1: Restoring TCP connection id 3a0 ino 13132760
(04.924936) Error (criu/cr-restore.c:1009): 9748 exited, status=1
(04.956236) mnt: Switching to new ns to clean ghosts
(04.980690) Error (criu/cr-restore.c:1897): Restoring FAILED.

[restore.log.txt](https://github.com/xemul/criu/files/876808/restore.log.txt)

Is there a less convoluted way to do this?
What I am doing wrong?

**Comment by xemul** [comment]
@avagin , looks like we're missing some error logs in libsoccr -- it failed, but there's no message why.

@jmserre , as far as the live migration is concerned. There's [a short summary](https://criu.org/Live_migration#Prerequisites) of what CRIU expects from the environment to live migrate tasks. In short, when live migrating anything with CRIU some help from the environment is required.

In Docker case one need to copy root filesystem (which you had done) and (!) help locking the networking. The latter is being discussed at the moment. IIRC Docker deliberately and explicitly asks CRIU not to mess with the net namespace it creates for containers, so migrating the contents of the net namespace is Docker's issue.

Your particular error is about CRIU being unable to restore TCP socket. This typically happens when the IP address, that was used on source side is not kept on the destination, so bind() (or connect()) just fails.

To proceed with this you should first make sure that you create container on the destination side with the same IP address or (!) modify criu images to fix the ip addresses (with crit tool). But the latter will likely not work for established connections, since the connection client won't change it's remote address to match yours. You may try to overcome this with NAT, but that's far more complex than keeping the address.

Anyway, "live migration with two clicks" of a Docker container can only work when properly supported by Docker. Right now this is not the case, Docker only provides a way to create a checkpoint, not more, and that's surely not enough.

We're constantly receiving complains about inability to restore from image on a freshly created container. You've hit that too :) and came to the conclusion that fs copy is required. And we want this to become the part of "docker checkpoint" command, because otherwise it won't work.

On the upcoming Dockercon there's going to be a discussion of all these things between @avagin, @boucher, @tych0, @SaiedKazemi and other people. Hopefully I'll be able to join via skype too.

**Comment by jmserre** [comment]
Sorry for piling up 'complaints' on the same topics and thanks for your clear description of the issues. 

 There is just one thing I am surprised.  My 3 containers have only connections between themselves and when I resurrect my target container on server B using the exact same docker-compose file the other two are pretty much in the same state. (using a network/bridge between the three of them). So do I have any mean to try to understand exactly which connection to whom is failing?
 (maybe this is the first line of your response ", looks like we're missing some error logs in libsoccr ...."). 

One possible work around for me maybe to create a special flag/state in my container where all connection gets closed (to be ready to be frozen) and to re-create connections after unfreeze.

**Comment by xemul** [comment]
@jmserre , yes, finding out the exact failing socket would be possible once we return back logging into libsoccr :(

As far as the ability to auto-close the connections is concerned -- we have this feature request in issue #280 :)

**Comment by xemul** [comment]
For the record. There's a [golang code](https://github.com/xemul/criu/tree/criu-dev/phaul) that does the core of live migration using criu [pre-dump.](https://criu.org/Iterative_migration) In the future we'll have the [lazy memory restore](https://criu.org/Userfaultfd) support in it and [direct images transfer](https://criu.org/Image_cache/proxy_TODO).

**Comment by jmserre** [comment]
Thanks I will take a look, maybe it will give me a clue what I am missing.

**Comment by avagin** [comment]
As for the tcp problem, I think the container is restored with another ip address and we get the next error:
(00.054365)     32: Error (soccr/soccr.c:475): Can't bind inet socket back: Cannot assign requested address

**Comment by xemul** [comment]
@avagin , you're correct, but I haven't seen this message in the attached log file.

**Comment by jmserre** [comment]
So Is the actual hostname/(real IP) of server A hidden somewhere in the checkpoint files?... May grep for hit (and replace it).  I thought because my docker compose file is creating a bridge network and the three containers refers to each other only by their container names I was safe.

**Comment by xemul** [comment]
@jmserre IP-s sit in image files, yes. You can explore them with crit, and modify with crit too. In docker case you'd only need to fix inetsk.img file.

But just changing them won't work. Although your containers refer to each other only by names, kernel network stack still uses IP addresses. Also, some apps may keep IP addresses in their memory (e.g. by calling gethostbyname()).

**Comment by jmserre** [comment]
I grep r in the checkpoint directory did not found any direct reference to sever A IP address, not its hostname but I found a few things like that in the dump.log

riu.work/dump.log:(00.224918)  Dumping: ino 0x13132760 family   10 type    1 po                                             rt    34880 state  1 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.224925)  Dumped: family 10 type 1 proto 6 port 34880 stat                                             e 0 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.225075)  Dumping: ino 0x13132173 family   10 type    1 po                                             rt    34882 state  1 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.225081)  Dumped: family 10 type 1 proto 6 port 34882 stat                                             e 0 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.228045)  Dumping: ino 0x13131977 family   10 type    1 po                                             rt    34906 state  1 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.228052)  Dumped: family 10 type 1 proto 6 port 34906 stat                                             e 0 src_addr ::ffff:172.19.0.4
criu.work/dump.log:(00.331722) pagemap-cache: filling VMA 3f4280000-400000000 (1                                             94048K) [l:3f4200000 h:3f4400000]

But remember I started 3 containers on both servers  and I went into the other two (the one I did not checkpoint restore) they have identical internal IP address.
So on both servers one is 172.19.0.4
the other is 172.19.0.2

So I am back to my understanding that the sockets on both server A and B have the same IPs at both ends.  (Maybe by luck)  (Sorry I just saw you added something, I will try to find out what crit is

**Comment by xemul** [comment]
[Wiki page](https://criu.org/CRIT)
[Man page](https://github.com/xemul/criu/blob/master/Documentation/crit.txt)

The latter is more up-to-date though :)

**Comment by xemul** [comment]
Also, you cannot just grep the images directly. Images are in [binary](https://criu.org/Images) format and you need to decode them with crit first.

**Comment by jmserre** [comment]
Thank you, Educating your customers must be 95% of your job

**Comment by jmserre** [comment]
I had not used python for a long time, but finally.....

.../crit/crit decode -i inetsk.img

There are a 4 , they look like

"magic" : "INETSK",
	"entries" : [{
			"src_port" : 46602,
			"family" : 10,
			"proto" : 6,
			"opts" : {
				"so_passsec" : false,
				"so_snd_tmo_sec" : 0,
				"so_sndbuf" : 131072,
				"so_passcred" : false,
				"so_mark" : 0,
				"reuseaddr" : false,
				"so_rcv_tmo_usec" : 0,
				"so_priority" : 0,
				"so_rcvlowat" : 1,
				"so_no_check" : false,
				"so_rcv_tmo_sec" : 0,
				"so_rcvbuf" : 131072,
				"so_dontroute" : false,
				"so_snd_tmo_usec" : 0
			},
			"fown" : {
				"pid_type" : 0,
				"signum" : 0,
				"pid" : 0,
				"uid" : 0,
				"euid" : 0
			},
			"dst_addr" : [0, 0, 4294901760, 33559468],
			"v6only" : false,
			"state" : 1,
			"ino" : 36108,
			"flags" : 2,
			"dst_port" : 61616,
			"src_addr" : [0, 0, 4294901760, 67113900],
			"type" : 1,
			"id" : 527,
			"backlog" : 0,
			"ip_opts" : {}
		}, 
[inetsk.img.txt](https://github.com/xemul/criu/files/886914/inetsk.img.txt)

**Comment by jmserre** [comment]
ok ok 4294901760 = FFFF0000 probably a mask 255.255.0.0  
33559468  =   02 00 13 AC   or   2.0.19.172   up side down but 172.19.0.2 is one of the two IPs of my other containers, and was the same on both server A and B. But then others looks strange....


 {
			"src_port" : 33332,
			"family" : 10,
			"proto" : 17,
			"opts" : {
				"so_passsec" : false,
				"so_snd_tmo_sec" : 0,
				"so_sndbuf" : 212992,
				"so_passcred" : false,
				"so_mark" : 0,
				"reuseaddr" : false,
				"so_rcv_tmo_usec" : 0,
				"so_priority" : 0,
				"so_rcvlowat" : 1,
				"so_no_check" : false,
				"so_rcv_tmo_sec" : 0,
				"so_rcvbuf" : 212992,
				"so_dontroute" : false,
				"so_snd_tmo_usec" : 0
			},
			"fown" : {
				"pid_type" : 0,
				"signum" : 0,
				"pid" : 0,
				"uid" : 0,
				"euid" : 0
			},
			"dst_addr" : [0, 0, 0, 0],
			"v6only" : false,
			"state" : 7,
			"ino" : 40499,
			"flags" : 2,
			"dst_port" : 0,
			"src_addr" : [0, 0, 0, 0],
			"type" : 2,
			"id" : 783,
			"backlog" : 0,
			"ip_opts" : {}
		}

Note the source and destination address being 0,0,0,

**Comment by xemul** [comment]
@jmserre , you can use 'crit show $image-name', it will prettify the output :)

**Comment by xemul** [comment]
Also, src and dst addresses look to be the IPv6 ones in your case.

**Comment by jmserre** [comment]
crit show /var/lib/docker/containers/....../checkpoints/..../inetsk.img

The result is strange, crit issue, or there really is an issue with the TCP socket stuff...
[inetsk.img.txt](https://github.com/xemul/criu/files/893973/inetsk.img.txt)


{
    "magic": "INETSK",
    "entries": [
        {
            "id": 527,
            "ino": 36108,
            "family": 10,
            "type": 1,
            "proto": 6,
            "state": 1,
            "src_port": 46602,
            "dst_port": 61616,
            "flags": "0x2",
            "backlog": 0,
            "src_addr": [
                "::ffff:ac13:4"
            ],
            "dst_addr": [
                "::ffff:ac13:2"
            ],
            "fown": {
                "uid": 0,
                "euid": 0,
                "signum": 0,
                "pid_type": 0,
                "pid": 0
            },
            "opts": {
                "so_sndbuf": 131072,
                "so_rcvbuf": 131072,
                "so_snd_tmo_sec": 0,
                "so_snd_tmo_usec": 0,
                "so_rcv_tmo_sec": 0,
                "so_rcv_tmo_usec": 0,
                "reuseaddr": false,
                "so_priority": 0,
                "so_rcvlowat": 1,
                "so_mark": 0,
                "so_passcred": false,
                "so_passsec": false,
                "so_dontroute": false,
                "so_no_check": false
            },
            "v6only": false,
            "ip_opts": {}
        },

So that one is state 1 (hopefully means open)
The next connection is state 7 (closed?)  source and dest address are empty
next one is state 10 (source and dest are 0.0.0.0 (????)
next one state 7  source and dest are 0.0.0.0
next one is state 1 looks very similar to first one
next one is state 1 again similar to first one
final one is state 10 source and dest are empty.

**Comment by jmserre** [comment]
I am pretty sure my IPs are v4, so do criu thinks they are v6?  (hence the weird printout)

**Comment by xemul** [comment]
@jmserre , state 1 means ESTABLISHED, 7 is CLOSED, yes. Addresses are IPv6 for real, it's not CRIT issue. The ::ffff:<something> is so called [mapped address](https://en.wikipedia.org/wiki/IPv6_address#Transition_from_IPv4). In theory we could detect this in CRIT and print the <something> part in a more common format, i.e. in the a.b.c.d one.

**Comment by jmserre** [comment]
So for sure the state 7 are not the problem.  Do you know what state 10 means?
(as always thanks for your time)

**Comment by xemul** [comment]
7 yes, closed sockets are easy. State 10 is LISTEN :)

**Comment by xiaozhazi** [comment]
I have migrate the docker container to a different host successful, the container IP in the two host are same.
The service running in the container is apache ab test, command is ：
**ab -c 100 -n 1000000 -k -s 120 http://10.3.1.82:80/**
But there is one problem, when the container restored on the destination host, the ab test will interrupt, and show the Error:
**apr_pollset_poll the timeout specified has expired (70007)**
the reason is that restored container in destination host cannot ping 10.3.1.82 successful. It seems that the tcp connection restore has some problem?

**Comment by xemul** [comment]
@xiaozhazi , live migrating Docker container also implies moving the host-side configuration Docker creates. Do network work at all for your container on the destination host?

**Comment by jmserre** [comment]
Can you clarify 'moving the host-side configuration'
One experiment I tried (but I need to more time to make sure I did not make a mistake)  is to fix the IPs of all 3 containers in my docker-compose

networks:
  fernando-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24
        gateway: 172.16.1.1

......
services:
  <first container>:
.....
        fernando-net:
        ipv4_address: 172.16.1.2

....
  <second container>:
.....
        fernando-net:
        ipv4_address: 172.16.1.3
(same for third one)

and even then the restoration of the connection seemed to have failed (again I need to confirm my set-up)  Hopefully can provide logs next week.

**Comment by SaiedKazemi** [comment]
@xemul @jmserre I talked with Madhu at DockerCon about this.
@mavenugo Can you please take a look at this?

**Comment by xiaozhazi** [comment]
@xemul What host-side configuration should i move? 

The restored container in destination node has the right eth0 and L0, but when I run the 'arp' command, it shows that:
**?(172.17.100.1) at <incomplete> on eth0.** 
Seems that the container losing its MAC address?

**Comment by xemul** [comment]
Thanks, @SaiedKazemi :) 

@xiaozhazi , I'm not an expert on what's currently going on with Docker networking :) But here are some suggestions:

- If the container is just bridged with the host network, then the corresponding device should be put back into bridge
- If the container is NAT-ed, then you should make sure that the NAT rule is preserved on the host side.

Changed MAC address of the container shouldn't be the problem, as for new MACs ARP will just resolve them.

**Comment by iprimo** [comment]
Hi @xemul,

I have been following CRIU team great work for sometime and can foresee many great opportunities for Live\Cold container migration technology.

I already started to playground with CRIU, and unfortunately I am experiencing similar issues with restoring containers on Docker.

You mentioned there are constant complaints about restoring containers in to new containers, I am wondering is this just for Docker, or it is an issue in general for CRIU? 

If networking is the issue, could it be resolved by using copies of the same VM on both source\destination side? (with same Docker network configuration)

Dose CRIU experiences similar challenges with 'runc' ?

Is there any platform that CRIU based on and works the best on it ? 

And finally, May I ask is there any company out there that their internal teams officially started to implement CRIU into their products ? (and providing support)

Thanks

**Comment by xemul** [comment]
@iprimo I've received a github notification from you on this issue, but don't see the comment itself, neither notification has your e-mail for contact. If you want, let's discuss your question over e-mail, write me to xemul (at) openvz (dot) org.
