### ISSUE TITLE
Migrating between different cgroup merge policies

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#307]

**Comment by c1t4r** [comment]
Hi,

 We tried all available --cgroup merge policies but none of them worked out.
 I collected the requested infos and will attach them here.

`diff`

 criuchecks.centos73.txt criuchecks.centos72.txt
6a7
> Warn  (cr-check.c:696): Dirty tracking is OFF. Memory snapshot will not work.
17a19
> Warn  (cr-check.c:696): Dirty tracking is OFF. Memory snapshot will not work.
27c29
< mem_dirty_track is supported
---
> Warn  (cr-check.c:696): Dirty tracking is OFF. Memory snapshot will not work.


[cgroups.txt](https://github.com/xemul/criu/files/919107/cgroups.txt)
[criuchecks.centos72.txt](https://github.com/xemul/criu/files/919108/criuchecks.centos72.txt)
[criuchecks.centos73.txt](https://github.com/xemul/criu/files/919106/criuchecks.centos73.txt)`





greets

**Comment by xemul** [comment]
@c1t4r , thanks a lot!
@cyrillos , would you please check why ignoring cgroups didn't help?
@eabatalov , this might be an interesting task for your lab.

**Comment by cyrillos** [comment]
will try on the next week if time allow
