### ISSUE TITLE
error in maps restore

### ISSUE THREAD

**Issue by rppt** [checkpoint-restore/criu#326]
When I run
```
python test/zdtm.py run -t zdtm/static/env00
```
On current criu-dev I get the following error:
```
========================= Run zdtm/static/env00 in ns ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
Run criu restore
1: Old maps lost: set(["7ffcc6b46000-7ffcc6b8b000 ['rw-p']"])
1: New maps appeared: set(["7ffcc6b47000-7ffcc6b8b000 ['rw-p']"])
################# Test zdtm/static/env00 FAIL at maps compare ##################
Send the 9 signal to  70
Wait for zdtm/static/env00(70) to die for 0.100000
##################################### FAIL #####################################
```

With '-f h' the test passes
I've bisected it to 
commit 3ca8e575b49763030d3ddfec4af190a4c9f9deef
mem: Don't assume guard page is returned in procfs with new kernels

CC @cyrillos

**Comment by cyrillos** [comment]
Which kernel is it?

**Comment by rppt** [comment]
fc25 with 4.11.5:
$ uname -a
Linux localhost.localdomain.localdomain 4.11.5-200.fc25.x86_64 #1 SMP Wed Jun 14 17:17:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cyrillos** [comment]
@avagin Andrew, revert this commit please!
