### ISSUE TITLE
Optimize shell code with <'s (instead of cat + |)

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#330]
https://www.codacy.com/app/xemul/criu/issues?bid=4795042&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiQ29kZSBTdHlsZSJdfSx7ImlkIjoiTGV2ZWwiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsyMzk1XX0seyJpZCI6IkF1dGhvciIsInZhbHVlcyI6W251bGxdfSx7InZhbHVlcyI6W119XQ==

**Comment by sankalp-12** [comment]
Could I take up this issue?
