### ISSUE TITLE
Move timers dump/restore code into separate file

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#335]
In `criu/cr-restore.c` file there's a set of functions starting from `prepare_posix_timers()` and `prepare_itimers()`. In `criu/parasite-syscall.c` there's a set starting from `parasite_dump_itimers_seized()` and `parasite_dump_posix_timers_seized()`.

Both are better to be moved to separate .c file in the criu/ directory.

**Comment by Rajiv2605** [comment]
This issue seems unresolved/ open. Can I work on this issue?
