### ISSUE TITLE
Move sigact dump/restore code into separate file

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#336]
In the `parasite-syscall.c` file there's a function `parasite_dump_sigacts_seized()`. In the `cr-restore.c` file there's a `prepare_sigactions()` call (and whatever it calls).

Both are better to be moved into a .c file in the criu/ dir.

**Comment by prakritigoyal19** [comment]
@xemul Hi! I would like to work on this issue. Can this be assigned to me please?

**Comment by xemul** [comment]
Done

**Comment by prakritigoyal19** [comment]
Thanks!
I am planning to move those functions from their original files along with all the necessary imports, to another file, created in the criu dir. Then importing this newly created file to the original files (parasite-syscall.c , cr-restore.c).
Please correct me if I'm wrong.

**Comment by prakritigoyal19** [comment]
Hey, I have mailed my patches to the CRIU mailing list. Please let me know if I should make any changes. 

The repo link for the same is https://github.com/prakritigoyal19/criu/tree/sigactions.

Thank You!
