### ISSUE TITLE
Remove unused imports from python code

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#337]
https://www.codacy.com/app/xemul/criu/issues?bid=4795042&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOlsiVW51c2VkIENvZGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbMTcyMF19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX0seyJ2YWx1ZXMiOltdfV0=

**Comment by xobx-cherif** [comment]
@xemul Hi ! i want to work on this issue
