### ISSUE TITLE
Reduce code duplication in lib/py

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#340]
https://www.codacy.com/app/xemul/criu/file/7625550609/duplication/source?bid=4795042&fileBranchId=4795042

**Comment by mitulkarnik** [comment]
Is this issue resolved? 
Because when I visited the link mentioned in the description the page says "This file no longer exists"

**Comment by rst0git** [comment]
I don't think this one has been fixed. Try the following:
```sh
$ cd lib/py
$ pylint --disable=all -e R0801 images/*.py
```

**Comment by eliams** [comment]
The links in the issue are no longer valid

**Comment by rst0git** [comment]
The file [`lib/py/images/images.py`](https://github.com/checkpoint-restore/criu/blob/criu-dev/lib/py/images/images.py) contains code duplication.

**Comment by behouba** [comment]
Hi @rst0git, 
My name is Behouba Manassé, and I am new to CRIU I would like to contribute to the next GSoC.
Can I work on this issue?

**Comment by rst0git** [comment]
Hi Behouba, you are welcome to work on this GitHub issue :)
If you have any questions about GSoC, feel free to reach out to me in [gitter](https://gitter.im/save-restore/CRIU) or via email.
