### ISSUE TITLE
Show vma's madvise flags as names

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#342]
Look at `images/vma.proto`. Fields `prot`, `flags` and `status` are marked with `(criu).flags`. This means, that when showing an image with `crit show` the respective field is analyzed and bits in it are shown as respective symbolic values.

At the same time field `madv` is marked with `(criu).hex` which means, that the value is just printed in hexadecimal. It would be nice to show symbolic makes here as well.

The de-/encoding happens at `lib/py/images/pb2dict.py`

**Comment by JoeCEngineer** [comment]
Not sure if this is related - it may not be - wanted to check first. I have a use for cloning an application using checkpoint/restore and marking it's heap memory blocks with MADV_MERGEABLE on restore. The intent is to leverage KSM and reduce memory footprint for cloned Docker containers on the same host. Reading this enhancement, I take it I can already do that use case, this is more about making the madvise flags human readable, correct? Thanks!

**Comment by xemul** [comment]
@JoeCEngineer , you can fix madvise flags already, but you'd have to know the flag numerical value and write it correctly in the decoded image file. This issue is about making this more human-friendly :)
