### ISSUE TITLE
Pre-dump produces too big memory overhead

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#351]
Current pre-dump mode suffers from several issues

1. It keeps all the memory in pipes, and their number can be huge due to limited one pipe size
2. It keeps all the memory in pipes and this memory is unreclaimable for that period
3. It infects tasks to drain memory from

We can try to use sys_read_process_vm() syscall to mitigate all of the above

1. No pipes, just copy data into temp buffer and send
2. Memory is always reclaimable
3. No infection is needed, just freeze, reset the tracker and proceed

Ideally there should be sys_splice_process_vm() syscall in the kernel :)

**Comment by avagin** [comment]
Here is a prototype https://github.com/avagin/criu/tree/process_vm_readv

**Comment by avagin** [comment]
If we use sys_read_process_vm(), we can't dump memory which are not accessible to read. Currently we call add PROT_READ by mprotect(),  add pages into pipes, and restore vma_prot.

**Comment by avagin** [comment]
Here is a draft version of sys_process_vmsplice: https://github.com/avagin/linux-task-diag/commit/35420bd6d4a5305f6bf39ec002f0e5d31708280a

**Comment by rst0git** [comment]
As this was completed by Abhishek in GSoC 2019, should we close this issue?
