### ISSUE TITLE
uffd-events in h: shutil.Error: [('dump/zdtm/static/uffd-events/24/1/lazy-pages.socket', 'report/zdtm_static_uffd-events_h/images/1/lazy-pages.socket', "[Errno 6] No such device or address: 'dump/zdtm/static/uffd-events/24/1/lazy-pages.socket'")]

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#355]
======================= Run zdtm/static/uffd-events in h =======================
Start test
./uffd-events --pidfile=uffd-events.pid --outfile=uffd-events.out
Run criu dump
Run criu lazy-pages
Run criu restore
Send the 15 signal to  24
Wait for zdtm/static/uffd-events(24) to die for 0.100000
Wait for zdtm/static/uffd-events(24) to die for 0.200000
###### Test zdtm/static/uffd-events FAIL at criu lazy-pages exited with 1 ######
Test output: ================================
23:00:49.841:    25: PASS
23:00:49.842:    24: PASS

 <<< ================================
Traceback (most recent call last):
  File "zdtm.py", line 2010, in <module>
    do_run_test(tinfo[0], tinfo[1], tinfo[2], tinfo[3])
  File "zdtm.py", line 1458, in do_run_test
    add_to_report(cr_api.logs(), tname.replace('/', '_') + "_" + f + "/images")
  File "zdtm.py", line 94, in add_to_report
    shutil.copytree(path, tgt_path)
  File "/usr/lib64/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('dump/zdtm/static/uffd-events/24/1/lazy-pages.socket', 'report/zdtm_static_uffd-events_h/images/1/lazy-pages.socket', "[Errno 6] No such device or address: 'dump/zdtm/static/uffd-events/24/1/lazy-pages.socket'")]

https://ci.openvz.org/job/CRIU/job/CRIU-lazy/job/criu-dev/71/

Cc @rppt, @avagin

**Comment by rppt** [comment]
I'm trying to reproduce locally, but still no luck :(
Elaborate logs or help with reproducing will be highly appreciated

**Comment by rppt** [comment]
[1] should fix the error in shutil.copytree and [2] hopefully fixes the real problem :)

[1] https://lists.openvz.org/pipermail/criu/2017-July/038679.html
[2] https://lists.openvz.org/pipermail/criu/2017-July/038695.html
