### ISSUE TITLE
[Docker] Restore fails if previously restored (second order/second/multiple restore)

### ISSUE THREAD

**Issue by jvlatzko** [checkpoint-restore/criu#359]
Hi, 

I am trying to restore a docker container that has been checkpointed. Trouble occurs when this exact procedure happened before (and succeeded): 

1. run something
2. checkpoint it
3. restore from checkpoint 
4. checkpoint anew
5. restore anew

This follows the [wiki](https://criu.org/Docker) regarding c/r with Docker. Mind you, all is happening on the same machine.

_Expected behaviour:_ 
continues running

_Observed behaviour:_ 
`Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0`

**Real code:** 

```
➜  ~ docker create --name looper-clone busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'                  
cd14381f19032558581c0895ec64a87d1e17a4c82fecbe3b5f50e51c9eaef267
➜  ~ docker create --name looper-cloneclone busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
a97ae1170ab82967767b2cee0e3b476cb696b35a56c90f314b01b171dd31c721
➜  ~ docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
d9dd0c2c5f8fe453228e31e7758ec5660d5078ccaf20d716258c5705aa9d312f

➜  ~ docker checkpoint create --checkpoint-dir=/home/user/tcpl looper cp1       
cp1
➜  ~ docker start --checkpoint-dir=/home/user/tcpl --checkpoint=cp1 looper-clone1

➜  ~ docker checkpoint create --checkpoint-dir=/home/user/tcpl looper-clone1 cp2 
cp2
➜  ~ docker start --checkpoint-dir=/home/user/tcpl --checkpoint=cp2 looper-cloneclone
Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /home/user/tcpl/cp2/criu.work/restore-2017-07-06T09:01:46+02:00/restore.log
```

As you see, everything works as expected up to and including step 4 (at least from my point of view). 

The referenced logfile is quite big, please find it [here](https://pastebin.com/T3W8nTwv)

Best, Vincent

**Comment by xemul** [comment]
Failure:

      (00.327207)      1: pr1 Read 7fffc9bfc000 3 pages
      (00.327216)      1:     pr1 Read page from self 7fffc9bfc000/a000
      (00.327251)      1: Error (criu/pagemap.c:266): Can't read mapping page -1: Bad address
      (00.360175) Error (criu/cr-restore.c:1024): 27242 killed by signal 9: Killed

@jvlatzko what version of CRIU do you use? May I also look at the list of images generated (incuding their sized)?

**Comment by jvlatzko** [comment]
Sure! Please find the output of `ls -al` for both checkpoints [here](https://pastebin.com/3eyJvH89)

I'm using 2.6-1ubuntu1~ubuntu16.04.2 (installed from package in apt)

**Comment by xemul** [comment]
So, this really looks like the recent stack guard page breakage in the kernel (issue #322). I's been fixed in criu-3.2.1. Hopefully Ubuntu kernel guys has fixed their kernel too :)

Would you be able to check 3.2.1 criu compiled from sources?

**Comment by jvlatzko** [comment]
I can confirm it works with criu compiled from source! Thanks a lot! 

(Using Ubuntu kernel 4.8.0-56-generic)

**Comment by jvlatzko** [comment]
I'm sorry to report his, but things do not seem to work as well as it looked. 
[Here](https://pastebin.com/59AsVF98) is another pastebin of the logfile criu created when it failed to restore a container. This occured at trying to restore the second checkpoint (cp2), as above. 
Note that this time a more involved [experiment](https://pastebin.com/uaLMXk63) took place, but with the same error message. 
Unfortunately, the kernel has updated to 4.8.0-58-generic so a direct comparison might not be adequate.

**Comment by xemul** [comment]
That's another issue.

      (00.579902) mnt: Switching to new ns to clean ghosts
      (00.600497) Error (criu/cr-restore.c:2099): Restoring FAILED.

the only path that can behave like that is in depopulate_roots_yard->try_clean_remaps->clean_one_remap->rst_get_mnt_root->FAILURE.

Can you show us the contents of reg-files.img, remap-fpath.img and mountpoints-*.img? With crit tool. Or put them somewhere so that we can download it and decode ourselves?

**Comment by jvlatzko** [comment]
Hi xemul, thanks for your fast reply. Please use this file [here](https://www.dropbox.com/s/83xxvc5dm2q36fo/criu_errors.tar?dl=0) (also added as edit in OP) while I figure out how to extract the data with crit / getting my system to run crit.

**Comment by xemul** [comment]
@jvlatzko , this problem is the same as the one we're discussing in #365 -- you restore into a different container, this time the problem is in changed IP address inside it. The established TCP socket tries to bind to its "old" address (the one seen at the time of dump), while inside new container you there's already some other address. So bind fails. In issue #303 we're discussing it, briefly -- it's Docker integration issue and we have a patch (will be in 3.3) that just kills all established TCP sockets.

**Comment by jvlatzko** [comment]
@xemul sorry for the delay. So a follow-up question for the change in 3.3 (which has been released, correct? I've recently pulled and compiled a 3.3): 
Does this change (kill all established TCP sockets) mean that all established connections are broken? 

We explicitly want that feature - in our understanding, it is vital for (container) live migration with network functionality. Is there another way to migrate containers with their TCP connections intact? (Apologies if it is documented anywhere, I have not found it)

Or is this something the Docker guys have to fix?

**Comment by xemul** [comment]
@jvlatzko the answer is, well, complex :) So the ability to drop the established TCP sockets is in 3.3 (https://criu.org/CLI/opt/--tcp-close), but this behavior should be explicitly enabled. There are two options to do it, first is via CLI/RPC option and the respective changes should be done by Docker guys. Another option is to enable it via configuration file. The latter is a feature in development, which is almost finished, so it's in criu-dev branch (commit 19c2935f5d226c365003f0d2b3816a06f82a88eb) and is about to get merged into master (and released) some day soon.
