### ISSUE TITLE
Restore sibling via C API

### ISSUE THREAD

**Issue by sinainnet** [checkpoint-restore/criu#370]
Hi, 

As the following page states, the CRIU command-line is capable of restoring a process as a sibling of the CRIU process.

[https://criu.org/Tree_after_restore]()

However, I could not find any suitable API in the libcriu (and the corresponding criu.h). Is it possible to restore a process as sibling or even detached, via C-API?

P.S: I've already installed the pre-build debian package on ubuntu 16.04 LTS!

**Comment by avagin** [comment]
Pls, take a look at criu_local_restore_child()
https://github.com/xemul/criu/blob/master/lib/c/criu.c#L1378

**Comment by sinainnet** [comment]
Thanks a lot.
May I ask further questions? 

1) In the Ubuntu pre-build package, the header files does provide the any facility for using RPC. Indeed, I've ought to implement the criu.c again in my code!!! I think that Ubuntu packaging is poor, indeed.

2) My business includes a self-checkpointing and self-restoring! I mean, the same command (with different options) is used for dumping and restoring the whole context of the process. The weird things is after restoring the process,  top and htop do not show it. Even, I cannot send signal using kill command!!! It gets new PID and its parrent is init! If I use the setseid() systme call, it will be appeared and then I will lose the stdin and stdout!!!!

**Comment by xemul** [comment]
@sinainnet ,

1. Well, I don't disagree :) The thing is that it's ubuntu team who does packaging, so the question should rather be addressed to them. On the other hand, if there's anything we can do on criu side to facilitate convenient packaging, we're all open to it.

2. Yes, it gets a new pid as it's seen from the host namespace and gets re-parented. However, the getpid() would still return the same value. You can read more about it here -- https://criu.org/CR_in_namespace. Also, you can restore a process as a sibling, here's how https://criu.org/CLI/opt/--restore-sibling

If you have any other questions, don't hesitate to ask!

**Comment by sinainnet** [comment]
Thanks a lot!. Indeed, the biggest problem is lack of proper access to the global_opts variable, which is defined in criu/lib/c/criu.c .

#include "criu.h"
#include "rpc.pb-c.h"
#include "cr-service-const.h"

#define CR_DEFAULT_SERVICE_BIN "criu"

const char *criu_lib_version = CRIU_VERSION;

struct criu_opts {
	CriuOpts		*rpc;
	int			(*notify)(char *action, criu_notify_arg_t na);
	enum criu_service_comm	service_comm;
	union {
		char		*service_address;
		int		service_fd;
		char		*service_binary;
	};
	int			swrk_pid;
};

static criu_opts ***global_opts**;
static int saved_errno;

Ubuntu package is provided the criu.h file, through which we can not access the **_global_opt_** variable. In case we do not want to rewrite the criu.c in our code! Cause you've done it very good.

**Comment by xemul** [comment]
Well, giving raw access to global opts would cause compatibility problems, thus all access is via functions only. If any setter is missing -- feel free to submit a patch for libcriu.so )
