### ISSUE TITLE
The patch mentioned in criu/Documentation/HOWTO.cross-compile doesn't exist

### ISSUE THREAD

**Issue by yihuad** [checkpoint-restore/criu#374]
Hey,

I am trying to follow criu/Documentation/HOWTO.cross-compile to build criu statically; but it seems that the patch [1] doesn't exist anymore; any clue where I could find it? Is the patch still relevant?

Thanks!

[1] http://16918.selcdn.ru/crtools/aarch64/0001-protobuf-added-the-support-for-the-acrchitecture-AAr.patch

**Comment by yihuad** [comment]
Ping

**Comment by xemul** [comment]
@yihuad , sorry for the delay :) We haven't played with static compilation for a long time indeed. This particular recipe from the docs is about getting statically linked protobuf library and it looks like the patch may not be required any longer. At least https://coderanch.com/wiki/659932/Protoc-Independent-Binary says, that it's enough to properly configure the protobuf sources.

Can you check whether it's really the case?

**Comment by yihuad** [comment]
Thanks for the response; I will try it out and see whether it works or we have something missing.
