### ISSUE TITLE
Can't open fake fifo 0x42

### ISSUE THREAD

**Issue by johnmoore4** [checkpoint-restore/criu#375]
I'm running OpenMPI with the command:
setsid mpirun -np 2 ~/local/FUN3D/fun3d_install/bin/nodet_mpi  < /dev/null &> /dev/null &
and dumping with:
sudo $CRIU --tree $1 --images-dir ~/dumps --leave-running --tcp-established --ghost-limit 1000000000
The application dumps without error. I attempt to restore using:
sudo criu restore --tree $1 --images-dir ~/dumps --tcp-established

However, I get the following error:
  4718: Error (criu/fifo.c:92): Can't open fake fifo 0x42 [tmp/openmpi-sessions-john@criu_0/29677/0/debugger_attach_fifo]: No such file or directory
  4718: Error (criu/files-reg.c:1658): Can't open file tmp/openmpi-sessions-john@criu_0/29677/0/debugger_attach_fifo: No such file or directory
Error (criu/cr-restore.c:1213): 4718 exited, status=1
Error (criu/cr-restore.c:2083): Restoring FAILED.

This appears to have to do with temporary files which are created by mpirun, but are deleted when mpirun is stopped. Therefore, upon restore, the files are no longer there. Is there a way to fix this issue? Can I just tell criu not to look for these files, or are they necessary?

Thanks!
John

**Comment by xemul** [comment]
@johnmoore4 , the files in question are used by the processes you dump and restore, otherwise criu wouldn't want to open them. I'm not an expert in openmpi :) but it seems to me that these files are channels that are set up by mpi runtime to make application talk to the master process. Can you confirm that?

**Comment by Qinghe12** [comment]
@johnmoore4    I met the same issue, did you got any solution ？
