### ISSUE TITLE
How to measure CPU usage for a criu restore?

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#378]
I'm using criu (through docker) to quickly start an application which otherwise takes a long time to start up. In addition to starting much quicker, it seems that starting the application through a criu restore uses a lot less cpu (which intuitively makes sense). I'm trying to measure the difference in cpu usage between doing a criu restore vs a normal application start. However, I'm having trouble accurately measuring the amount of cpu criu uses during a restore. I do see that criu outputs a stats-restore file which contains some metrics for each restore, but cpu usage doesn't seem to be one of them.

I first tried reading /proc/pid/stat for the cpu usage information. However, this is not trivial, as criu seems to spawn multiple helper processes while doing a restore and these processes have varying lifetimes. I tried summing the utime (user time) and stime (system time) for each process returned by `pgrep criu` during the restore. This gave me a cpu usage of 65 clock ticks (.65 seconds) over the course of the restore which took about 1 second. This seems like it could be close to the truth, although I feel like I'm missing some cputime with this method.

I then tried taking the difference in the whole system's cputime (/proc/stat) between the start and end of the restore. I closed all other processes running on my system to try to minimize noise. This gave me a cpu usage of ~1400 clock ticks (14 seconds) over the course of the 1 second restore, which is way too high (my system doesn't even have 14 cpus).

Do you guys have any suggestions as to how I can measure the criu cputime during a restore more accurately? Thanks!

**Comment by xemul** [comment]
@tswift242 , you can use the getrusage(2) call. It can report the user and system time for the whole sub-tree. Generally it should look like this:

      pid = fork();
      if (pid == 0) {
              execl("criu", ...);
      }
      wait();
      getrusage(RUSAGE_CHILDREN, &usage);

I think it would be worthwhile fixing criu to make the stats-restore to include the rusage statistics as well.

**Comment by tswift242** [comment]
Thanks for the response @xemul ! Could you point me to where in the criu code I could insert a snippet like that to capture this metric? (where is the primary fork for a restore?)

Yes, that'd be great if cpu usage stats were included in stats-restore!

**Comment by xemul** [comment]
@tswift242 , the place where root task forks is restore_root_task() routine. Somehwere in the middle it calls fork_with_pid(init);. But playing with getrusage in this place seems to help only for the --check-only case :\ as it collects timings for exited children (and grandchildren) only.

**Comment by xemul** [comment]
On the other hand, you're interested in time spent restoring, so you don't need to "really restore" them, don't you?

**Comment by tswift242** [comment]
Yea that's right. I'm just interested in cpu time during the restore, it's okay if the processes aren't actually restored as long as that doesn't affect the cpu time. In that case, I can use --check-only? I don't think docker exposes that option so I guess I'd have to call criu directly.
