### ISSUE TITLE
pstree.img format breakage in criu-dev

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#382]
Cc @avagin and @tkhai 

Commit 94e0beadc1945134a6cc918784905f3a33f0e944 changes required fields into optional, which is probably not extremely nice. In particular, this breaks crit x functionality, it can no longer access pstree_item_entry['pid'] value as it's absent.

**Comment by tkhai** [comment]
I've reflected the above in "[PATCH] crit: Use ns_pid, ns_sid and ns_gid" in criu mailing list.

**Comment by xemul** [comment]
The issue was not about fixing CRIT, but about returning pid field back to required. Or proving that changing required to optional is valid.

**Comment by tkhai** [comment]
I've checked env00, dumped via old criu (before the commit), and it was restored on recent criu-dev w/o problems.

We may leave the field optional "as is", until anybody reports there is a problem with the field type, but I'm not sure this will happen. What do you think?

**Comment by xemul** [comment]
@avagin ?

**Comment by avagin** [comment]
4b8a09f043a1c3de454ecf56b2c819ac63be73d2
