### ISSUE TITLE
Please provide an example for docker container live migration from source ip to dest ip.

### ISSUE THREAD

**Issue by ank4r** [checkpoint-restore/criu#386]
The [criu wiki](https://criu.org/P.Haul) does not mention on how to set file descriptors corresponding to socket and it seems like golang doesn't expose socket file descriptor.

**Comment by xemul** [comment]
Cc @avagin and @kolyshkin

**Comment by avagin** [comment]
@gargankur74 I don't understand what you mean. You can call s.Fd() and gets a file descriptor.
```
func (f *File) Fd() uintptr
```

If you want to integrate phaul into Docker, you need to find a way how to create a channel between two nodes. Docker has to have infrastructure to create channels between two nodes in one swarm cluster.

**Comment by gargankur74** [comment]
Earlier I was using ssh connection to migrate the dump files but dump was created using docker create checkpoint. Now, I am trying to include pre-dump feature provided by phaul library.
If I could get an example to migrate a simple process (like piggie.c) from one machine to another by creating a simple tcp connection (or some other way) and extracting file descriptor from it (to be passed as an arg for phaul config) then hopefully I would be able to extend it for docker as well.

**Comment by wenjianhn** [comment]
I'd like to implement an example. And extend it to Containerd or Docker.

**Comment by xemul** [comment]
Cc @rppt

**Comment by wenjianhn** [comment]
@gargankur74 You can use raw syscall to create the sockets. 

e.g.
memfd, err := syscall.Socket(syscall.AF_INET, syscall.SOCK_STREAM, syscall.IPPROTO_TCP)

cfd, _, err := syscall.Accept(sfd)

**Comment by gargankur74** [comment]
Thank you @xemul @avagin @wenjianhn. I'll try raw syscall to create sockets and use it in similar way as in piggie.c

**Comment by wenjianhn** [comment]
@gargankur74 or you can use IP address and port of the page server.

I will add an example in the following issue.
https://github.com/containerd/containerd/issues/1731
