### ISSUE TITLE
dump & restore succeeded but live migration failed

### ISSUE THREAD

**Issue by sandylss** [checkpoint-restore/criu#389]
First, in issue #321 , we want to dump SCTP sockets.
currently, we can dump & restore SCTP sockets with no errors. But actually the restored socket cannot send or receive data. So meanwhile we are working on the live migration of our program which uses SCTP sockets. Since this new problem seems to have no relationship to SCTP sockets, I start a new issue.  

The dumping & restoring of our program on the same host succeeded. However, live migration failed.
Refer to the simple loop example, I make the program and script available on both nodes. I command `setsid ./criu4sctp.sh  < /dev/null &> test.log &` to run it isolated. Then dump it and copy the files to the other node and command `criu restore -d -v4 -o restore.log`

And there will be a mount error.

> (00.000033) Version: 3.4 (gitid 0)
> (00.000055) Warn  (criu/crtools.c:717): Using -t with criu restore is obsoleted
> (00.000111) Loaded kdat cache from /run/criu.kdat
> (00.000128) cpu: fpu:1 fxsr:1 xsave:0
> (00.000208) vdso: Parsing at 7ffdb7b1f000 7ffdb7b21000
> (00.000216) vdso: PT_LOAD p_vaddr: 0
> (00.000219) vdso: DT_HASH: 120
> (00.000222) vdso: DT_STRTAB: 268
> (00.000224) vdso: DT_SYMTAB: 160
> (00.000226) vdso: DT_STRSZ: 5e
> (00.000228) vdso: DT_SYMENT: 18
> (00.000230) vdso: nbucket 3 nchain b bucket 7ffdb7b1f128 chain 7ffdb7b1f134
> (00.000235) vdso: rt [vdso] 7ffdb7b1f000-7ffdb7b21000 [vvar] 7ffdb7b1d000-7ffdb7b1f000
> (00.000267) kernel pid_max=32768
> (00.000271) Reading image tree
> (00.000297) Add mnt ns 5 pid 31492
> (00.000313) pstree pid_max=31493
> (00.000320) Will restore in 0 namespaces
> (00.000322) NS mask to use 0
> (00.000326) Collecting 37/54 (flags 2)
> (00.000340) Collected [bin/bash] ID 0x1
> (00.000345) Collected [usr/lib/locale/locale-archive] ID 0x2
> (00.000348) Collected [lib/x86_64-linux-gnu/libc-2.23.so] ID 0x3
> (00.000354) Collected [lib/x86_64-linux-gnu/libdl-2.23.so] ID 0x4
> (00.000358) Collected [lib/x86_64-linux-gnu/libtinfo.so.5.9] ID 0x5
> (00.000361) Collected [lib/x86_64-linux-gnu/ld-2.23.so] ID 0x6
> (00.000364) Collected [usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache] ID 0x7
> (00.000368) Collected [dev/null] ID 0x8
> (00.000371) Collected [home/lab931/enb.log] ID 0x9
> (00.000374) Collected [home/lab931/criu4sctp_start.sh] ID 0xa
> (00.000378) Collected [home/lab931] ID 0xb
> (00.000381) Collected [.] ID 0xc
> (00.000384) Collected [home/lab931/OAI/OAI/openairinterface5g/cmake_targets/lte_build_oai/build/lte-softmodem] ID 0xd
> (00.000390) Collected [home/lab931/OAI/OAI/openairinterface5g/cmake_targets/lte_build_oai/build/liboai_usrpdevif.so] ID 0xe
> (00.000393) Collected [usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0] ID 0xf
> (00.000397) Collected [usr/lib/x86_64-linux-gnu/libXau.so.6.0.0] ID 0x10
> (00.000400) Collected [usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0] ID 0x11
> (00.000403) Collected [lib/x86_64-linux-gnu/libgcc_s.so.1] ID 0x12
> (00.000407) Collected [usr/lib/x86_64-linux-gnu/libX11.so.6.3.0] ID 0x13
> (00.000410) Collected [usr/lib/x86_64-linux-gnu/libXpm.so.4.11.0] ID 0x14
> (00.000413) Collected [lib/x86_64-linux-gnu/libm-2.23.so] ID 0x15
> (00.000417) Collected [usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21] ID 0x16
> (00.000420) Collected [usr/lib/libforms.so.2.1.3] ID 0x17
> (00.000425) Collected [usr/local/lib/libusrsctp.so.1.0.0] ID 0x18
> (00.000429) Collected [usr/lib/libnettle.so.4.4] ID 0x19
> (00.000432) Collected [lib/x86_64-linux-gnu/libcrypto.so.1.0.0] ID 0x1a
> (00.000435) Collected [lib/x86_64-linux-gnu/libcrypt-2.23.so] ID 0x1b
> (00.000439) Collected [lib/x86_64-linux-gnu/librt-2.23.so] ID 0x1c
> (00.000442) Collected [usr/lib/x86_64-linux-gnu/libconfig.so.9.2.0] ID 0x1d
> (00.000445) Collected [lib/x86_64-linux-gnu/libpthread-2.23.so] ID 0x1e
> (00.000453) epoll: Collected eventpoll: id 0x00001f flags 0x02
> (00.000458) eventfd: Collected : id 0x000020 flags 0x02 counter 0000000000000000
> (00.000462) epoll: Collected eventpoll: id 0x000021 flags 0x02
> (00.000467) eventfd: Collected : id 0x000022 flags 0x02 counter 0000000000000000
> (00.000471) epoll: Collected eventpoll: id 0x000023 flags 0x02
> (00.000475) eventfd: Collected : id 0x000024 flags 0x02 counter 0000000000000000
> (00.000478) epoll: Collected eventpoll: id 0x000025 flags 0x02
> (00.000482) eventfd: Collected : id 0x000026 flags 0x02 counter 0000000000000000
> (00.000485) epoll: Collected eventpoll: id 0x000027 flags 0x02
> (00.000489) eventfd: Collected : id 0x000028 flags 0x02 counter 0000000000000000
> (00.000493) epoll: Collected eventpoll: id 0x000029 flags 0x02
> (00.000496) eventfd: Collected : id 0x00002a flags 0x02 counter 0000000000000000
> (00.000500) epoll: Collected eventpoll: id 0x00002b flags 0x02
> (00.000505) eventfd: Collected : id 0x00002c flags 0x02 counter 0000000000000000
> (00.000509) epoll: Collected eventpoll: id 0x00002d flags 0x02
> (00.000512) eventfd: Collected : id 0x00002e flags 0x02 counter 0000000000000000
> (00.000516) epoll: Collected eventpoll: id 0x00002f flags 0x02
> (00.000525) eventfd: Collected : id 0x000030 flags 0x02 counter 0000000000000000
> (00.000529) epoll: Collected eventpoll: id 0x000031 flags 0x02
> (00.000532) eventfd: Collected : id 0x000032 flags 0x02 counter 0000000000000000
> (00.000536) epoll: Collected eventpoll: id 0x000033 flags 0x02
> (00.000539) eventfd: Collected : id 0x000034 flags 0x02 counter 0000000000000000
> (00.000545) epoll: Collected eventpoll: id 0x000035 flags 0x02
> (00.000548) eventfd: Collected : id 0x000036 flags 0x02 counter 0000000000000000
> (00.000552) epoll: Collected eventpoll: id 0x000037 flags 0x02
> (00.000555) eventfd: Collected : id 0x000038 flags 0x02 counter 0000000000000000
> (00.000559) epoll: Collected eventpoll: id 0x000039 flags 0x02
> (00.000562) eventfd: Collected : id 0x00003a flags 0x02 counter 0000000000000000
> (00.000566) epoll: Collected eventpoll: id 0x00003b flags 0x02
> (00.000569) eventfd: Collected : id 0x00003c flags 0x02 counter 0000000000000000
> (00.000573) eventfd: Collected : id 0x00003d flags 0x02 counter 0x00000000000f76
> (00.000598)  `- ... done
> (00.000601) Collecting 43/59 (flags 0)
> (00.000606) No remap-fpath.img image
> (00.000608)  `- ... done
> (00.000749) cg: Preparing cgroups yard (cgroups restore mode 0x4)
> (00.000822) cg: Opening .criu.cgyard.fcZqQ9 as cg yard
> (00.000835) cg: 	Making controller dir .criu.cgyard.fcZqQ9/devices (devices)
> (00.000866) cg: Determined cgroup dir devices/user.slice already exist
> (00.000870) cg: Skip restoring properties on cgroup dir devices/user.slice
> (00.000881) cg: 	Making controller dir .criu.cgyard.fcZqQ9/cpuset (cpuset)
> (00.000901) cg: Determined cgroup dir cpuset/ already exist
> (00.000905) cg: Skip restoring properties on cgroup dir cpuset/
> (00.000913) cg: Determined cgroup dir cpuset//docker already exist
> (00.000916) cg: Skip restoring properties on cgroup dir cpuset//docker
> (00.000924) cg: Determined cgroup dir cpuset//docker/4dce45cbcffed83f1aa6aaf77726d51eea6af1d55b2aff243606cca238c10673 already exist
> (00.000927) cg: Skip restoring properties on cgroup dir cpuset//docker/4dce45cbcffed83f1aa6aaf77726d51eea6af1d55b2aff243606cca238c10673
> (00.000935) cg: Determined cgroup dir cpuset//docker/f4c3e28764d2cf6d40cc5fc580bf823c382be1492e84306d02be86c664b1913d already exist
> (00.000938) cg: Skip restoring properties on cgroup dir cpuset//docker/f4c3e28764d2cf6d40cc5fc580bf823c382be1492e84306d02be86c664b1913d
> (00.000946) cg: Determined cgroup dir cpuset//docker/6a4c08da1ce7c233df728d9c003ace681870f11b9f2fbf203ad8e3590d1c941b already exist
> (00.000949) cg: Skip restoring properties on cgroup dir cpuset//docker/6a4c08da1ce7c233df728d9c003ace681870f11b9f2fbf203ad8e3590d1c941b
> (00.000957) cg: 	Making controller dir .criu.cgyard.fcZqQ9/pids (pids)
> (00.000977) Error (criu/cgroup.c:1642): cg: 	Can't mount controller dir .criu.cgyard.fcZqQ9/pids: No such file or directory

I notice that the error is about controller dir. So is this error related to file system?

**Comment by xemul** [comment]
Please, make sure you have the same set of controllers on both sides, and chose the proper cgroup management mode for criu: https://criu.org/CGroups

**Comment by sandylss** [comment]
Thanks, I've solved this problem. ^_^

**Comment by xemul** [comment]
Cool

**Comment by phenix317** [comment]
Hello guys, 
Actually we are trying to run some tests on applications that contain the same kind of protocol (‘SCTP’) is there any official patch in the user space @sandylss ?

BR,

**Comment by ShunmugaPriyaR** [comment]
> Thanks, I've solved this problem. ^_^

Hello @sandylss 

We are working on one of the applications that require SCTP support for CRIU. From this email thread, it looks like you are using userland SCTP instead of the kernel and you enabled the checkpoint and restore support for CRIU.  We would like to know whether the CRIU works well for the SCTP sockets in connected states.  If you have the working copy, could you share the  SCTP portion of the code accordingly? Thank you.

Regards,
Priya.
