### ISSUE TITLE
docker restore error

### ISSUE THREAD

**Issue by blondita** [checkpoint-restore/criu#390]
Hi,guys i've a new error on my live-migration project.
I'm in rancherOS for testing in container live:
docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: true

i'm using a nginix container for his migration in different machine
after restoring i've this error:

Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /tmp/check_1506357819/criu.work/restore-2017-09-25T16:43:49Z/restore.log

in restore.log  i find this error:

 1: Error (criu/cr-restore.c:1207): 5 exited, status=1
(00.727106)      7: Restoring resources
(00.727209)      7: Opening fdinfo-s
(00.727295)      7: Found fd 0 (id pipe:[401016]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.727339)      7: Inherit fd 0 moved to 4 to resolve clash
(00.727369)      7:             Create fd for 0
(00.727383)      7: Found fd 1 (id pipe:[401017]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.727393)      7: Inherit fd 1 moved to 3 to resolve clash
(00.727401)      7:                     Going to dup 0 into 1
(00.727411)      7: Found fd 2 (id pipe:[401018]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.727421)      7: Inherit fd 2 moved to 5 to resolve clash
(00.727430)      7:                     Going to dup 0 into 2
(00.727439)      7:     Receive fd for 1
(00.727447)      7:     Receive fd for 2
(00.727477)      7:     Restore: family 2 type 1 proto 6 port 46838 state 1 src_addr 127.0.0.1
(00.727521)      7: Restoring TCP connection
(00.727542)      7: Restoring TCP connection id 54 ino 627d4
(00.727697)      7: 6 restore sndbuf 2626560 rcv buf 1061808
(00.727746)      7:     restore priority 0 for socket
(00.727756)      7:     restore rcvlowat 1 for socket
(00.727765)      7:     restore mark 0 for socket
(00.727782)      7: Found fd 3 (id pipe:[401017]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.727792)      7: Inherit fd 3 moved to 7 to resolve clash
(00.727801)      7:             Create fd for 3
(00.727813)      7:     Restore: family 2 type 1 proto 6 port 46840 state 1 src_addr 127.0.0.1
(00.727838)      7: Restoring TCP connection
(00.727853)      7: Restoring TCP connection id 55 ino 627d6
(00.727933)      7: 6 restore sndbuf 2626560 rcv buf 1061808
(00.727950)      7:     restore priority 0 for socket
(00.727960)      7:     restore rcvlowat 1 for socket
(00.727968)      7:     restore mark 0 for socket
(00.727983)      7: Found fd 4 (id pipe:[401016]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.727992)      7: Inherit fd 4 moved to 8 to resolve clash
(00.728002)      7:             Create fd for 4
(00.728011)      7:             Creating pipe pipe_id=0x6276d id=0x56
(00.728028)      7: Schedule 3 socket for repair off
(00.728054)      7: Schedule 4 socket for repair off
(00.728066)      7:             Creating pipe pipe_id=0x6276d id=0x56
(00.728079)      7:             Creating pipe pipe_id=0x6276d id=0x56
(00.731643) mnt: Switching to new ns to clean ghosts
(00.732126) Error (criu/cr-restore.c:2075): Restoring FAILED.

Thanks in advance!

**Comment by avagin** [comment]
Could you show a full restore.log?

**Comment by blondita** [comment]
it is very big. i attach it
[restore.log](https://github.com/xemul/criu/files/1336641/restore.log)

**Comment by avagin** [comment]
```
(00.792259)      5: Inherit fd 14 moved to 18 to resolve clash
(00.792264)      5:             Create fd for 14
(00.792269)      5:     Restore: family 2 type 1 proto 6 port 1935 state 1 src_addr 127.0.0.1
(00.792283)      5: Restoring TCP connection
(00.792289)      5: Restoring TCP connection id 1b ino faea8
(00.792334)      5: 16 restore sndbuf 16384 rcv buf 87380
(00.792342)      5:     restore priority 0 for socket
(00.792347)      5:     restore rcvlowat 1 for socket
(00.792351)      5:     restore mark 0 for socket
(00.792358)      5: Found fd 15 (id pipe:[1026255]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.792363)      5: Inherit fd 15 moved to 19 to resolve clash
(00.792367)      5:             Create fd for 15
(00.793596)      1: Error (criu/cr-restore.c:1207): 5 exited, status=1
```

**Comment by avagin** [comment]
What version of criu do you use?

**Comment by blondita** [comment]
criu --version
Version: 3.3
but i installed it with dnf install criu so i can' t add the patch

**Comment by xemul** [comment]
@avagin , do you plan to send this patch int master?

**Comment by avagin** [comment]
The patch is in master (d50f0e90fad3200710d0932af39586002a5526b4).

Please reopen this issue if the issue will be reproduced again.
