### ISSUE TITLE
restore PF_PACKET socket in docker failed due to "no such device"

### ISSUE THREAD

**Issue by sandylss** [checkpoint-restore/criu#391]
I'm trying to restore a docker container. I'm using a packet socket whose type is PF_PACKET in this container and its networking is created by `docker network create`. I got this error

> (00.366376)     85: arrive inet_bind
> (00.366387)     85: 34 restore sndbuf 16384 rcv buf 87380
> (00.366392)     85: 	restore priority 0 for socket
> (00.366395)     85: 	restore rcvlowat 1 for socket
> (00.366397)      1: 		Create fd for 255
> (00.366398)     85: 	restore mark 0 for socket
> (00.366407)     85: 		Create fd for 34
> (00.366410)     85: Opening packet socket id 0x42
> (00.366409)      1: Opening 0x00000000400000-0x000000004ef000 0000000000000000 (41) vma
> (00.366436)     85: Error (criu/sk-packet.c:492): Can't bind packet socket: No such device
>

I checked the source code, the error is at
```
if ( bind (sk, (struct sockaddr *)&addr, sizeof(addr)) < 0 ) {
    pr_error("can't bind packet socket");
    got err_cl;
}
```
and all about this socket sk is 
```
		sk = socket(PF_PACKET, pse->type, pse->protocol);
		if (sk < 0) {
			pr_perror("Can't create packet sock"); 
			goto err;
		}
	
		memset(&addr, 0, sizeof(addr));
		addr.sll_family = AF_PACKET;
   	        addr.sll_ifindex = pse->ifindex;
```
It looks fine. And I found that I won't get this error if I restore the program on bare-metal.

So it seems a bug with docker. I suppose that after a container is stopped, the Virtual Ethernet will be released so CRIU is not able to find the device?

docker inspect shows the networking information of this stopped container

>                 "oai-net2": {
>                     "IPAMConfig": {},
>                     "Links": null,
>                     "Aliases": [
>                         "4dce45cbcffe"
>                     ],
>                     "NetworkID": "77f19ad517116ea786941a1f8cfc25c921d23edc3033601acde8d00b758da4bd",
>                     "EndpointID": "",
>                     "Gateway": "",
>                     "IPAddress": "",
>                     "IPPrefixLen": 0,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": ""
> 
Emmmmm.... Any idea of this problem?

**Comment by xemul** [comment]
Most likely the problem is with device index change. On dump the index was A, at restore time, since Docker creates the network itself, the device index is B. I'm not 100% sure binding to another index won't break the proggie :) but we can try.

**Comment by sandylss** [comment]
Thanks to National Day, I have a long holiday, lol.
Yes, the problem is with device index change. So I use
```
char *interface = "eth1";
addr.sll_ifindex = if_nametoindex(interface);
```
instead of 
`addr.sll_ifindex = pse->ifindex;`

No error occurs when restoring. But since the ifindex is changed, the sendto() function will fail. Still trying to work it out.

Making ifindex fixed seems to make sense but Docker does not have this feature.
CRIU can restore a certain veth pair according to https://criu.org/VETH_device. I wonder how can I use this feature with docker c/r so that the ifindex will not change?

By the way, when reading the source code of docker and containerd, I notice that in the source code of containerd, some advanced usage of CRIU is implemented as follows
```
func (o *CheckpointOpts) args() (out []string) {
	if o.ImagePath != "" {
		out = append(out, "--image-path", o.ImagePath)
	}
	if o.WorkDir != "" {
		out = append(out, "--work-path", o.WorkDir)
	}
	if o.ParentPath != "" {
		out = append(out, "--parent-path", o.ParentPath)
	}
	if o.AllowOpenTCP {
		out = append(out, "--tcp-established")
	}
	if o.AllowExternalUnixSockets {
		out = append(out, "--ext-unix-sk")
	}
	if o.AllowTerminal {
		out = append(out, "--shell-job")
	}
	if o.CriuPageServer != "" {
		out = append(out, "--page-server", o.CriuPageServer)
	}
	if o.FileLocks {
		out = append(out, "--file-locks")
	}
	if string(o.Cgroups) != "" {
		out = append(out, "--manage-cgroups-mode", string(o.Cgroups))
	}
	for _, ns := range o.EmptyNamespaces {
		out = append(out, "--empty-ns", ns)
	}
	return out
}
```
But I did not see upper level API for those advanced usage. Are these features available now?

**Comment by xemul** [comment]
If docker uses host network, then criu can do nothing with ifndex. At the same time, if docker /doesn't/ use the host net, if creates veth pair itself, and he can safely request the desired ifindex itself.
