### ISSUE TITLE
Docker start from checkpoint fails with "BUG at criu/include/image.h:144"

### ISSUE THREAD

**Issue by aivrit** [checkpoint-restore/criu#393]
HI,
I am testing criu to use it as a slow-start-speed-up mechanism or as a snapshot alternative for an openstack devstack in a container that i am using. 
I compiled and installed criu v3.5 on an ubuntu 16.04.3 machine.
Checkpoint and restore on docker a container failed at the most basic usage:
`sudo docker create redis`
`sudo docker start redis`
`sudo docker checkpoint create redis test_3`
`sudo docker start --checkpoint test_3 redis`

And the output:
> Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/containers/07055d4caa5455637d359e494dbb8b296236e609114e5d7f5e35197be84f6354/checkpoints/test_3/criu.work/restore-2017-10-03T19:05:05.70908964+03:00/restore.log

the log file info is attached as a file. 
[log.log](https://github.com/checkpoint-restore/criu/files/1352988/log.log)

Help would be appreciated =]
Thanks!

**Comment by avagin** [comment]
I think it is a bug in Docker, it doesn't pass "--empty-ns net" to "runc restore".

**Comment by aivrit** [comment]
thanks @avagin . Should I open a dup in moby?

**Comment by aivrit** [comment]
thanks @avagin . Should I open a dup in docker/cli or moby?

**Comment by avagin** [comment]
@aivrit Yes, you should, it isn't trouble for you.

**Comment by avagin** [comment]
I'm sure that it is a bug in Docker. But we know that criu worked with Docker despite this bug, so I investigated this issue and found that it stopped working after cde33dcb06394e1654018045ac78244fa95af4d2. And you can build criu with a following patch to workaround this problem.

diff --git a/criu/net.c b/criu/net.c
index 936611de8..4f4e1b424 100644
--- a/criu/net.c
+++ b/criu/net.c
@@ -1541,7 +1541,11 @@ static inline int restore_iptables(int pid)
        struct cr_img *img;
 
        img = open_image(CR_FD_IPTABLES, O_RSTR, pid);
-       if (img) {
+       if (img != NULL) {
+               if (empty_image(img)) {
+                       ret = 0;
+                       goto out;
+               }
                ret = run_iptables_tool("iptables-restore", img_raw_fd(img), -1);
                close_image(img);
        }

**Comment by avagin** [comment]
Cc: @kolyshkin

**Comment by kolyshkin** [comment]
From what I see in the code, Docker engine does append `--empty-ns network` to criu cmdline:
https://github.com/moby/moby/blob/master/libcontainerd/client_linux.go#L579
https://github.com/moby/moby/blob/master/vendor/github.com/containerd/containerd/runtime/container.go#L396

@aivrit can you check options criu is called with?

**Comment by avagin** [comment]
@kolyshkin I already checked and docker doesn't pass this option to "criu restore"

**Comment by fntlnz** [comment]
FTR: In containerd's master this seems to be solved here https://github.com/containerd/containerd/blob/master/vendor/github.com/containerd/go-runc/runc.go#L415 docker however at the state of art uses an older version of containerd that only passes `empty-ns` at creation time.

**Comment by avagin** [comment]
https://github.com/checkpoint-restore/criu/commit/832dfed7778fd8f6d1a579c84be75b12b6fa92c5
