### ISSUE TITLE
Running setup-namespaces script takes a long time even when no action scripts are specified.

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#394]
I'm doing C/R through docker, using criu 3.5 and docker 17.03. From my understanding, action scripts are optional hooks that can be specified to criu that execute at different stages during the checkpoint and restore processes. One of those hooks is for the "setup-namespaces" stage. By adding a log statement right after https://github.com/checkpoint-restore/criu/blob/1510b248687f978e614b0bc8c08c0027c729c8a3/criu/action-scripts.c#L126, I see that the setup-namespaces action script takes over 80 milliseconds to execute, out of a total restore time of about 1 second. However, I don't believe docker/containerd/runc are specifying any action scripts to criu (for any stage). Therefore, I'm curious as to why this step takes so long, and wonder if the performance can be improved. Additionally, none of the other action script stages take more than a couple milliseconds to complete, with most taking less than one millisecond.

I'm attaching the full restore log in case that's helpful
[restore.txt](https://github.com/checkpoint-restore/criu/files/1363744/restore.txt)

**Comment by avagin** [comment]
Docker uses the setup-namespaces action to setup a network namespace:
https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L1443

**Comment by zhouxinyu** [comment]
Hi @avagin I have the same issue, What are the detail jobs about setup-namespaces? where can I find the script?

**Comment by avagin** [comment]
@zhouxinyu You need to find what Prestart hooks are set by Docker for a container:
https://github.com/opencontainers/runc/blob/master/libcontainer/container_linux.go#L1475
