### ISSUE TITLE
lxc-checkpoint not restore debian 8

### ISSUE THREAD

**Issue by ofinto** [checkpoint-restore/criu#395]
Hello, I tried to use CRIU with LXC, but faced the issue - lxc-checkpoint can't restore debian 8. I contacted [lxc](https://github.com/lxc/lxc/issues/1853) but they said that it's CRIU issue, not theirs. In fact Ubuntu 12.04 and 14.04 works.

### # Steps to reproduce
1. Version
```
uname -srvp
Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

lsb_release -d
Description:	Ubuntu 16.04.3 LTS

criu -V
Version: 2.6
```
2. Create container
```
lxc-create -t download -B zfs --zfsroot=data -n d1 -- -d debian -r jessie -a amd64
```
3. Add the following lines
```
cat | tee -a /var/lib/lxc/d1/config << EOF
# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
EOF
```
4. Start container and checkpoint the container
```
lxc-start -n d1
sleep 5s
lxc-checkpoint -s -D /tmp/d1 -n d1
```
5. Restore the container
```
lxc-checkpoint -r -D /tmp/d1 -n d1 -l DEBUG -o debug.log
```

[config.txt](https://github.com/checkpoint-restore/criu/files/1376028/config.txt)
[debug.log](https://github.com/checkpoint-restore/criu/files/1376029/debug.log)
[dmesg.txt](https://github.com/checkpoint-restore/criu/files/1376031/dmesg.txt)
[dump.log](https://github.com/checkpoint-restore/criu/files/1376032/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/1376033/restore.log)

**Comment by ofinto** [comment]
I recordered [asciinema](https://asciinema.org/a/oV7OFxQRXoDcTocsdnuheOeUb)

**Comment by ofinto** [comment]
I recordered [asciinema](https://asciinema.org/a/oV7OFxQRXoDcTocsdnuheOeUb)

**Comment by ofinto** [comment]
I recorded [asciinema](https://asciinema.org/a/oV7OFxQRXoDcTocsdnuheOeUb)

**Comment by ofinto** [comment]
I recorded [asciinema](https://asciinema.org/a/oV7OFxQRXoDcTocsdnuheOeUb)

**Comment by avagin** [comment]
I have reproduced this issue locally. First of all I checked a criu version and it is very old.

root@ubuntu-2gb-nyc3-01:~/criu# dpkg-query -l | grep criu
ii  criu                             2.6-1ubuntu1~ubuntu16.04.2                   amd64        checkpoint and restore in userspace

Then I updated criu to 3.5 and found that it works fine
root@ubuntu-2gb-nyc3-01:~/criu# lxc-checkpoint -s -D /tmp/d1 -n d1
root@ubuntu-2gb-nyc3-01:~/criu# echo $?
0
root@ubuntu-2gb-nyc3-01:~/criu# lxc-checkpoint -r -D /tmp/d1 -n d1 -l DEBUG -o debug.log -vv
root@ubuntu-2gb-nyc3-01:~/criu# echo $?
0

**Comment by kirillrst** [comment]
Thank you @avagin. What is the best way to install CRIU 3.5 on Ubuntu?

**Comment by xemul** [comment]
@kirillrst , likely compile it from sources. Ubuntu guys has some strange policy on updating criu package, they somehow depend on the debian team. So you can try pinging them compiling criu from sources at the same time :)
