### ISSUE TITLE
ssh dump issue

### ISSUE THREAD

**Issue by n0way0ut** [checkpoint-restore/criu#396]
![dump log](https://user-images.githubusercontent.com/5345101/31457047-e729cf62-aebb-11e7-850d-10ce095dca22.jpg)

      root@88ff288930ff:~# ps aux
      USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
      root         1  0.1  0.0  18240  3192 pts/0    Ss+  17:28   0:00 /bin/bash
      root        11  0.0  0.0  65524  5364 ?        Ss   17:28   0:00 /usr/sbin/sshd -D
      root        17  0.0  0.0  93052  6528 ?        Rs   17:28   0:00 sshd: root@pts/1
      root        26  0.0  0.0  18252  3220 pts/1    Ss   17:28   0:00 -bash
      root        57  0.0  0.0  71580  4172 ?        Ss   17:29   0:00 /usr/sbin/apache2 -k start
      www-data    61  0.0  0.0 360744  6136 ?        Sl   17:29   0:00 /usr/sbin/apache2 -k start
      www-data    62  0.0  0.0 360744  6124 ?        Sl   17:29   0:00 /usr/sbin/apache2 -k start
      root       120  0.0  0.0  34428  2860 pts/1    R+   17:29   0:00 ps aux
      root@88ff288930ff:~# w
       17:29:18 up 39 min,  2 users,  load average: 0.26, 0.18, 0.17
      USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
      root     pts/1    172.17.0.1       17:28    4.00s  0.01s  0.00s w
      root     pts/2    172.17.0.1       Sun19    0.00s  0.00s  0.01s -bash

      docker checkpoint create ossh1 c_ossh5

      crit x /var/lib/docker/containers/88ff288930ff9dd6eb04b9229ee1328c403c84df12e3798ec45eaf164314f1c4/checkpoints/c_ossh5/ ps
          PID   PPID   PGID    SID   COMM
            1      0      1      1   bash
           57      1     57     57      apache2
           61     57     57     57         apache2
           62     57     57     57         apache2

as you can see no sshd daemon is dumped, no errors in the dump.log (attached, I renamed it dump.log.jpg)

Note: I started ssh daemon with: docker exec ossh1 /usr/sbin/sshd -D

      # criu -V
      Version: 3.5
      GitID: v3.5

**Comment by xemul** [comment]
Is there any chance to get dump log as text file instead of a picture?

**Comment by n0way0ut** [comment]
[dump.txt](https://github.com/checkpoint-restore/criu/files/1376661/dump.txt)

**Comment by n0way0ut** [comment]
with a docker container that runs ssh daemon from the init it works properly. So the issue seems to be only when the daemon is started with docker exec

**Comment by adrianreber** [comment]
Looking at runC it uses the container's init process for CRIU as the top level process. If processes started via exec are not child processes of the container's init process then they will not be checkpointed. Works as designed or intended. Not much CRIU can do about I guess.

**Comment by xemul** [comment]
Yup :) Thanks, @adrianreber . @n0way0ut , why do you start services via exec?

**Comment by n0way0ut** [comment]
it makes sense. I just did it for this container for a quick test.
thank you all.
