### ISSUE TITLE
compel fails with: Unsupported relocation of type 42

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#397]
Today I got a new error while building CRIU on x86_64. The same build works on s390x. The environment is RHEL 7.4 (ish). Some packages are a bit different but I did not look very closely at it.

```
# ./compel/compel-host hgen -f criu/pie/restorer.built-in.o -o criu/pie/restorer-blob.h -l 1000
Error (compel/src/lib/handle-elf-host.c:572): Unsupported relocation of type 42
```

This is the official 3.5 tarball and the complete output of compel is here: https://lisas.de/~adrian/compel.out

**Comment by avagin** [comment]
Cc: @cyrillos @0x7f454c46

**Comment by 0x7f454c46** [comment]
It looks to be
```
#define R_X86_64_REX_GOTPCRELX  42      /* Load from 32 bit signed pc relative
                                           offset to GOT entry with REX prefix,
                                           relaxable.  */
```

**Comment by 0x7f454c46** [comment]
And it's for `restore_rt_sigaction()`.

**Comment by 0x7f454c46** [comment]
I wonder if something like that would work?
(NOT EVEN COMPILE-TESTED)
[new-reloc-add.txt](https://github.com/checkpoint-restore/criu/files/1388496/new-reloc-add.txt)

**Comment by 0x7f454c46** [comment]
Ifdef-guards may be also needed as it looks to be introduced in last 3 years to ABI.

**Comment by 0x7f454c46** [comment]
Hey @adrianreber, could you check if the mentioned commit for you?
It would be good if you try it with any ia32 test.

**Comment by cyrillos** [comment]
Should do the trick, thanks!

**Comment by adrianreber** [comment]
Referenced patch works. Thanks. How can I run any of the ia32 tests?

**Comment by avagin** [comment]
```
git clean -dxf test/
export COMPAT_TEST=y
make -C test/zdtm
python test/zdtmp.py run -a
```

**Comment by adrianreber** [comment]
Does not work, but not sure if that kernel has the necessary configs:

```
(00.002222) ----------------------------------------
(00.002230) Dump private signals of 48
(00.002236) Dump shared signals of 48
(00.002244) Parasite syscall_ip at 0x8048000
(00.002253) Error (compel/arch/x86/src/lib/infect.c:410): Can't dump task 48 running in 32-bit mode
(00.002256) Error (criu/cr-dump.c:1376): Can't infect (pid: 48) with parasite
(00.002285) Unlock network
(00.002290) Unfreezing tasks into 1
(00.002292) 	Unseizing 48 into 1
(00.002310) Error (criu/cr-dump.c:1819): Dumping FAILED.
```

**Comment by avagin** [comment]
There are a number of patches from @0x7f454c46 which you need to backport into the RHEL kernel for this feature.
https://lists.openvz.org/pipermail/devel/2016-July/069107.html

**Comment by 0x7f454c46** [comment]
Well, I think it's better to grab mainstream ones, as I had reworked vz-patches afterwards a bit and also found mmap() bug in the kernel, which was fixed later.
https://criu.org/Upstream_kernel_commits
Also you can check it with
```
[dima@ criu]$$sudo ./criu/criu check --all
Looks good.
```
Which shouldn't say anything about missing config compat or something %)
```
static int check_compat_cr(void)
{
#ifdef CONFIG_COMPAT
        if (kdat_compatible_cr())
                return 0;
        pr_warn("compat_cr is not supported. Requires kernel >= v4.12\n");
#else
        pr_warn("CRIU built without CONFIG_COMPAT - can't C/R compatible tasks\n");
#endif
        return -1;
}
```

**Comment by adrianreber** [comment]
With a 4.14rcX kernel I am able to run one test (and then the kernel crashes...). But the patch seems correct. The kernel crashes with:

[  150.961462] IP: bm_evict_inode+0x16/0x40 [binfmt_misc] 

But check seems happy:

```
# criu/criu check --all
Looks good.
```

**Comment by 0x7f454c46** [comment]
May be related to https://lkml.org/lkml/2017/10/13/493

**Comment by 0x7f454c46** [comment]
Well, ok if that works, I'll send the patch in ml, thanks!

**Comment by adrianreber** [comment]
Your lkml link looks exactly like what I am seeing. Thanks for that link.
