### ISSUE TITLE
build: CRIU is not rebuilding on plugins change

### ISSUE THREAD

**Issue by cyrillos** [checkpoint-restore/criu#399]
@avagin has reported

[root@usr-LAN-dhcp-38 criu]# make -j 4
make[1]: Nothing to be done for 'all'.
 DEP      compel/plugins/std/infect.d
make[1]: 'soccr/libsoccr.a' is up to date.
 CC       compel/plugins/std/infect.o
 AR       compel/plugins/std.lib.a
make[1]: 'compel/plugins/fds.lib.a' is up to date.
make[1]: 'compel/compel-host-bin' is up to date.
make[1]: 'compel/libcompel.a' is up to date.
make[1]: Nothing to be done for 'all'.
make[1]: 'images/built-in.o' is up to date.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: 'lib/c/built-in.o' is up to date.
 GEN      magic.py

**Comment by cyrillos** [comment]
I think we might try to move to https://ninja-build.org/

**Comment by cyrillos** [comment]
OK, I just remember the overall scheme: the plugins them selves are not involved into CRIU build. They are part of compel system. So it's not a bug but rather a feature.

In turn if you change something in libcompel (compel/src/lib/*) it force the criu rebuild.

make[1]: Nothing to be done for 'all'.
make[1]: 'images/built-in.o' is up to date.
make[1]: 'compel/plugins/std.lib.a' is up to date.
make[1]: 'compel/plugins/fds.lib.a' is up to date.
  DEP      compel/arch/x86/src/lib/cpu.d
  CC       compel/arch/x86/src/lib/cpu.o
  AR       compel/libcompel.a
make[1]: 'compel/compel-host-bin' is up to date.
make[1]: Nothing to be done for 'all'.
make[1]: 'soccr/libsoccr.a' is up to date.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
make[2]: Nothing to be done for 'all'.
  LINK     criu/criu
make[2]: 'lib/c/built-in.o' is up to date.
  GEN      magic.py
[cyrill@uranus criu] 

@avagin close the bug please as invalid.

**Comment by avagin** [comment]
> @avagin close the bug please as invalid.
No way! It is a BUGgggg. Each time when I do changes in compel, libsoccr, or other parts of the criu tree, I want to execute make and get a binary with all these changes.

**Comment by cyrillos** [comment]
criu don't use plugins at all :)

**Comment by avagin** [comment]
@cyrillos Are you sure? What is about compel/plugins/std/infect.c?

**Comment by cyrillos** [comment]
Yes. All plugins are for those who will use compel as its own. We still have TODO to enhance the plugins up to the state where we can use them instead of own CRIU implementation. And once we make so we will need to add build dependency over plugins.

**Comment by avagin** [comment]
```
[root@fc24 criu]# python test/zdtm.py run -t zdtm/static/env00 -k always -f h
=== Run 1/1 ================ zdtm/static/env00

========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
Run criu restore
Send the 15 signal to  36
Wait for zdtm/static/env00(36) to die for 0.100000
========================= Test zdtm/static/env00 PASS ==========================
[root@fc24 criu]# grep new_sp= test/dump/zdtm/static/env00/36/1/dump.log 
pie: 36: 36: new_sp=0x7fc49dcff008 ip 0x7fc49d81b527
[root@fc24 criu]# git grep new_sp=
compel/plugins/std/infect.c:    pr_debug("%ld: new_sp=%lx ip %lx\n", sys_gettid(),
```

**Comment by avagin** [comment]
The previous comment proves that plugins are already used by criu.

**Comment by cyrillos** [comment]
Sigh, indeed. They are used indirectly :/

**Comment by 0x7f454c46** [comment]
Patch is in v3.7, maybe the issue is good to close:
https://github.com/checkpoint-restore/criu/commit/6ea74dda5808
(the commit misses Fixed tag, so not auto-closed)
