### ISSUE TITLE
Error (criu/util.c:444): Can't get rlimit: Function not implemented

### ISSUE THREAD

**Issue by emilydolson** [checkpoint-restore/criu#400]
I'm trying to run CRIU in an Ubuntu 16.04 Singularity container running on a cluster. The cluster's operating system is CentOS 6.6, in case that matters. I've tried installing the criu package through apt-get and I've also tried building from this git repository. Regardless of which one I try, running `criu check` gives me this error: `Error (criu/util.c:444): Can't get rlimit: Function not implemented`. This makes it seem like I'm missing some sort of system package, but I can't figure out what it is. Any ideas?

**Comment by adrianreber** [comment]
It is not totally clear what you are tying to achieve. If you could give some more background info that would help. But from what you wrote it is not possible. If the  cluster uses the CentOS 6.6 kernel it can never work. As CRIU needs a much newer kernel. CentOS 7.4 has many necessary backports to make CRIU work. What is running inside the container is not relevant if the cluster kernel is that old.

What I tried, is to checkpoint a singularity container and it also failed. There is an email on CRIU development list but we never followed up on it. It sounds, however, unrelated to what you are trying to do.

**Comment by emilydolson** [comment]
I'm running a large number of instances of a long program that isn't playing nicely with BLCR, so I was hoping CRIU might do better. However, installing CRIU on the cluster, where I don't have root access, wasn't going well. At the same time, I was trying out Singularity, and noticed [this faq question](http://singularity.lbl.gov/faq#can-a-singularity-container-be-suspended-or-check-pointed) and [this github issue](https://github.com/singularityware/singularity/issues/468). So I thought I'd give the idea that they proposed, of including CRIU inside the container, a try.

But, based on what you say about the kernel, it sounds like it's a dead end. Thanks for the fast response!

**Comment by lovemyliwu** [comment]
@emilydolson you may check tutorial https://www.smitechow.com/2018/03/compile-criu-on-centos-6.html
