### ISSUE TITLE
restore with `--track-mem`

### ISSUE THREAD

**Issue by hamann** [checkpoint-restore/criu#401]
Would it be possible to restore an incremental checkpoint with `--track-mem` enabled, so that the next dump of that process isn't a full dump and just dumps the changes again? We tried that flag on restore, but it had no effect.
We would need that to restore a process in different states.

**Comment by adrianreber** [comment]
Not sure I totally understand what you mean. You want to incrementally checkpoint a process using --track-mem. But instead of restoring only the final checkpoint you want to be able to restore any of the incremental steps, right?

That is not possible right now as the pre-dump action does not write out all information about the process. If you look at the checkpoint directory you should see that most checkpoint files are missing, except the memory pages dump.

**Comment by hamann** [comment]
Sorry for being unclear. We restore the last dump (that one without `--leave-running`) and want to restore it in that way, that the next dump of the restored checkpoint also just include changes. see https://criu.org/Incremental_dumps

**Comment by adrianreber** [comment]
I still don't get it ;-)

You do
 * pre-dump 1
 * pre-dump 2
 * pre-dump 3
 ...
 * final-dump
 * restore

And then you want to start a new pre-dump, but you want to use the 'final dump' as a reference for the memory tracking. You want in the new pre-dump only the changes since the previous 'final dump', right? Are you migrating and want to reduce the amount of memory being transferred? What is your motivation?

By the way, you do not really need to specify ```--leave-running``` for the pre-dump steps. CRIU does that automatically.

**Comment by hamann** [comment]
We're checkpointing language interpretes/repls to be able to restore it to previous states (`time-travel`). We don't use `pre-dumps`, our first dump is done when the interpreter is loaded and must be blocking, which generates a full dump. If we then execute arbitrary code in the interpreter, we use [incremental dumps](https://criu.org/Incremental_dumps) repeatedly  to be able to go back to a previous interpreter state. We use incremental dumps, because they are faster and smaller in size. But if we go back in time by loading a (incremental) checkpoint, we want to continue making incremental checkpoints from that state (immediately enable `--track-mem` again)

1\. start interpreter
2\. full dump with --track-mem and --leave-running
... execute code in interpreter
3\. incremental dump with --track-mem and --leave-running
... execute code in interpreter
4\. incremental dump with --track-mem and --leave-running
... execute code in interpreter
5\. incremental dump without --leave-running

6\. restore checkpoint  from 5 (or 2, 3, 4) and enable *--track-mem* (which isn't implemented)
... execute code in interpreter
7\. incremental dump with --track-mem and --leave-running (but this one now creates a full dump again which we'd like to avoid)
... execute code in interpreter
8\. incremental dump with --track-mem and --leave-running
and so on


Currently when we restore the checkpoint from 6 and continue executing code, the next checkpoint (7) is a full dump (in size), not an incremental one. 
Our hope is, that if we restore a process from any dump, that we can enable `--track-mem` immediately after restore to only dump the changed pages on the next dump of the restored process.

**Comment by adrianreber** [comment]
This is probably something @xemul has to answer, but I think you could implement it.

1. Reset dirty memory tracking during restore. Requires code changes.
2. Then you need to specify that checkpoint you restored as ```--parent```

This might already be enough, @xemul what do you think?

**Comment by avagin** [comment]
@adrianreber  is right, we need to reset dirty memory tracking after restoring processes. Could you try out this patch:

```
diff --git a/criu/cr-restore.c b/criu/cr-restore.c
index 7086c7415..b76f1e0f9 100644
--- a/criu/cr-restore.c
+++ b/criu/cr-restore.c
@@ -2047,6 +2047,11 @@ skip_ns_bouncing:
        if (ret < 0)
                goto out_kill;
 
+       for_each_pstree_item(item) {
+               if (task_reset_dirty_track(item->pid->real) < 0)
+                       goto out_kill;
+       }
+
        ret = stop_usernsd();
        if (ret < 0)
                goto out_kill;
diff --git a/criu/include/mem.h b/criu/include/mem.h
index bb897c599..42b222190 100644
--- a/criu/include/mem.h
+++ b/criu/include/mem.h
@@ -22,6 +22,7 @@ extern bool page_in_parent(bool dirty);
 extern int prepare_mm_pid(struct pstree_item *i);
 extern void prepare_cow_vmas(void);
 extern int do_task_reset_dirty_track(int pid);
+extern int task_reset_dirty_track(int pid);
 extern unsigned long dump_pages_args_size(struct vm_area_list *vmas);
 extern int parasite_dump_pages_seized(struct pstree_item *item,
                                      struct vm_area_list *vma_area_list,
diff --git a/criu/mem.c b/criu/mem.c
index f3b2c224d..b6820e814 100644
--- a/criu/mem.c
+++ b/criu/mem.c
@@ -34,7 +34,7 @@
 #include "protobuf.h"
 #include "images/pagemap.pb-c.h"
 
-static int task_reset_dirty_track(int pid)
+int task_reset_dirty_track(int pid)
 {
        int ret;
 
```

**Comment by hamann** [comment]
@avagin Thanks a lot! I tried it with patching 3.6, but I had to execute `restore` a few times until it worked and dumping the restored task failed afterwards.

```sh
mkdir -p images/{1,2,3,4,5}
echo "julia -e 'sleep(9999999)'" > test.sh && chmod +x test.sh
setsid ./test.sh  < /dev/null &> test.log & 

sudo criu dump --tree $julia_pid --images-dir images/1/ --leave-running --track-mem --shell-job
ls -lh images/1/pages-1.img
-rw-r--r-- 1 root root 90M Oct 30 15:58 images/1/pages-1.img

sudo criu dump --tree $julia_pid --images-dir images/2/ --prev-images-dir ../1 --leave-running --track-mem --shell-job
ls -lh images/2/pages-1.img
-rw-r--r-- 1 root root 16K Oct 30 15:58 images/2/pages-1.img

sudo criu dump --tree $julia_pid --images-dir images/3/ --prev-images-dir ../2 --shell-job
ls -lh images/3/pages-1.img
-rw-r--r-- 1 root root 90M Oct 30 15:59 images/3/pages-1.img


sudo criu restore --images-dir images/3/ --prev-images-dir ../2 -d --track-mem --shell-job
pie: 16073: Error (criu/pie/restorer.c:498): Thread pid mismatch 16073/16072
>
pie: 16072: Error (criu/pie/restorer.c:498): Thread pid mismatch 16072/16071
>
pie: 16073: Error (criu/pie/restorer.c:544): Restorer abnormal termination fo>
pie: 16071: Error (criu/pie/restorer.c:498): Thread pid mismatch 16071/16070
>
pie: 16072: Error (criu/pie/restorer.c:544): Restorer abnormal termination fo>
pie: 16073: r 16063
pie: 16072: r 16063
pie: 16071: Error (criu/pie/restorer.c:544): Restorer abnormal termination fo>
pie: 16071: r 16063
Error (criu/cr-restore.c:2176): Restoring FAILED.
# restore worked after a few more tries

sudo criu dump --tree $julia_pid --images-dir images/4/ --prev-images-dir ../3 --leave-running --track-mem --shell-job
Error (criu/page-xfer.c:256): Missing 561b0d712000 in parent pagemap
Error (criu/page-xfer.c:301): Hole 0x561b0d611000/21901312 not found in parent
Error (criu/mem.c:465): Can't dump page with parasite
Error (criu/cr-dump.c:1709): Dumping FAILED.
```

**Comment by avagin** [comment]
Cc: @Snorch

**Comment by avagin** [comment]
@GrachevaAS You can modify inventory.img. You can use the crit tool to convert an image into the yaml format:

```
./crit/crit decode --pretty -i inventory.img  > inventory.yaml
```

back to the criu format
```
./crit/crit encode -i inventory.yaml > inventory.img
```

**Comment by avagin** [comment]
> pie: 16073: Error (criu/pie/restorer.c:498): Thread pid mismatch 16073/16072

@hamann https://criu.org/When_C/R_fails

**Comment by avagin** [comment]
BTW: If you want to do an incremental dump after restore, you need to check that task_reset_dirty_track() is called for restored tasks.

**Comment by Snorch** [comment]
May-be we can put everything under --track-mem option on restore. For it we both reset dirty tracking for newly created processes and fixup dump_uptime in inventory.img of the dump we restore from to the time of the reset. That will work as at these point we have all newly restored processes in the same memory state as it was when we saved the dump_uptime for these dump.

But I also see the problem, if on step:
> 6. restore checkpoint from 5 (or 2, 3, 4) and enable --track-mem (which isn't implemented)
> ... execute code in interpreter

we restore from e.g. checkpoint 2 and fixup dump_uptime for it, restoring from 3, 4 and 5 becomes now unsafe as pid-reuse will not be detected and we can restore wrong/alien memory for processes.

**Comment by Snorch** [comment]
JFYI: also we should not use --auto-dedup option on restore else we will lose all memory of the dump.

**Comment by GrachevaAS** [comment]
Thank you, @avagin!
@Snorch, why does restoring become unsafe? Do you mean that image 3 from your example may be overwritten by some process with reused pid?

**Comment by Snorch** [comment]
Task1 from 3 which reused the pid of some other task2 from 2, if it setups right memory layout, can steal memory from task1 during checkpoint/restore. Please see test/zdtm/transition/pid_reuse.c test where second child steals VALUE_B from first child for reference.

**Comment by juancampa** [comment]
Hi! I have a similar use-case to @hamann's and was wondering if anyone already implemented what @Snorch proposed. If not, I might give it a shot

**Comment by avagin** [comment]
@juancampa it isn't implemented yet. It would be good if you will be able to work on it. Let me know if you will have any questions.

**Comment by juancampa** [comment]
I want to clarify, this isn't yet a priority for us so no progress has been made. If I start working on it, I'll post any updates here.

**Comment by gitsvm** [comment]
This full dump incremental checkpointing is there in criu  only? for runc incremental checkpointing is done with multiple steps of  pre-dump and then a single dump? not for multiple full-dumps(i.e. each dump will not be incremental)?
> This is probably something @xemul has to answer, but I think you could implement it.
> 
> 1. Reset dirty memory tracking during restore. Requires code changes.
> 2. Then you need to specify that checkpoint you restored as `--parent`
> 
> This might already be enough, @xemul what do you think?
