### ISSUE TITLE
Please help, problem: Unlock network Error

### ISSUE THREAD

**Issue by zlyuan** [checkpoint-restore/criu#402]
I need an urgent help, thanks.

I am using the "checkpoint create", it occurs an error and the command failed.
"Error response from daemon: Cannot checkpoint container android-1901: rpc error: code = Unknown desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/e05c75dde309b94f943c0af3adadadf17d1d2689b9a8d20a9e33c18fce37fe11/checkpoints/aa6/criu.work/dump.log\n"

Following is the dump.log.

(00.317078) 30618 fdinfo 14: pos:                0 flags:             4002/0
(00.317081) 	Searching for socket 58b6a (family 2.6)
(00.317086) No filter for socket
(00.317087) Dumping inet socket at 14
(00.317088) 	Dumping: ino  0x58b6a family    2 type    1 port    45006 state  8 src_addr 172.18.0.2
(00.317090) 	Dumped: family 2 type 1 proto 6 port 45006 state 0 src_addr 172.18.0.2
(00.317092) Dumping TCP connection
(00.317093) 	Turning repair on for socket 58b6a
(00.317097) ----------------------------------------
(00.317103) Error (criu/cr-dump.c:1352): Dump files (pid: 30618) failed with -1
(00.317480) Unlock network
(00.317500) Running network-unlock scripts
(00.317502) 	RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.332832) Unfreezing tasks into 1
(00.332892) Error (criu/cr-dump.c:1709): Dumping FAILED.

**Comment by adrianreber** [comment]
Which version of CRIU are you using with which kernel and version of docker? Can you provide the complete dump.log?

**Comment by zlyuan** [comment]
Thanks for your quick reply.
CRIU version is 3.6. Kernel version is 4.4.0-62-generic. Docker version is 17.09.0-ce.
[dump.log](https://github.com/checkpoint-restore/criu/files/1424996/dump.log)

**Comment by zlyuan** [comment]
By the way, I am running docker on the cloud.

**Comment by zlyuan** [comment]
@adrianreber By the way, I am running docker on the cloud.

**Comment by adrianreber** [comment]
Not sure what is going wrong. It is definitely strange:

(00.119891) Dumping path for -3 fd via self 10 [/bin/bash]

fd being -3 means there was probably a ESRCH (No such process) during file descriptor collection.

Maybe someone else has a better idea of what is happening here.

The ```iptables-restore: invalid option -- 'w'``` is probably not relevant. A new upcoming iptables release will include this parameter and the old version should theoretically just work.

**Comment by avagin** [comment]
```
(00.119767) Collecting mappings (pid: 30480)
(00.119769) ----------------------------------------
(00.119891) Dumping path for -3 fd via self 10 [/bin/bash]
```
Here we are dumping file mappings, so -3 (FD_DESC_INVALID) means that it is not a file descriptor.

```
(00.317087) Dumping inet socket at 14
(00.317088)     Dumping: ino  0x58b6a family    2 type    1 port    45006 state  8 src_addr 172.18.0.2
(00.317090)     Dumped: family 2 type 1 proto 6 port 45006 state 0 src_addr 172.18.0.2
(00.317092) Dumping TCP connection
(00.317093)     Turning repair on for socket 58b6a
(00.317097) ----------------------------------------
(00.317103) Error (criu/cr-dump.c:1352): Dump files (pid: 30618) failed with -1
```
Something went wrong when we were dumping a tcp socket.

**Comment by zlyuan** [comment]
OK, thank you so much. @avagin @adrianreber

**Comment by avagin** [comment]
@zlyuan Could you compile criu from sources and try to run the zdtm/static/socket-tcp-local test?
python test/zdtm.py run -t zdtm/static/socket-tcp-local

If it will fail, could you send us a content of the test/dump directory?

**Comment by zlyuan** [comment]
OK，I will try.

**Comment by avagin** [comment]
@zlyuan Are you sure that the Docker daemon uses the criu 3.6?
