### ISSUE TITLE
Problem during the restore part after an iterative migration

### ISSUE THREAD

**Issue by ramy150** [checkpoint-restore/criu#404]
Dear all

It seems that we have found a problem during the last part of the live migration (restore part). After longly investigating we observed that MySQL daemon ((mysqld) (mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper )) could be the source of the problem.

attached you can find all the collected information and log files:

Host1 information:
[host1_information.txt](https://github.com/checkpoint-restore/criu/files/1433759/host1_information.txt)

Host2 information:
[host2_information.txt](https://github.com/checkpoint-restore/criu/files/1433760/host2_information.txt)

container config file:
[config.txt](https://github.com/checkpoint-restore/criu/files/1433772/config.txt)

first pre-dump log file:
[pre-dump.log](https://github.com/checkpoint-restore/criu/files/1433761/pre-dump.log)

second pre-dump log file:
[pre-dump2.log](https://github.com/checkpoint-restore/criu/files/1433763/pre-dump2.log)

dump log file:
[dump.log](https://github.com/checkpoint-restore/criu/files/1433764/dump.log)

restore file:
[restore.log](https://github.com/checkpoint-restore/criu/files/1433765/restore.log)

Screen Shot before the migration process:
![runningprocesses](https://user-images.githubusercontent.com/22980151/32270844-21e9f470-bf00-11e7-8799-83d0e6c09330.png)

**Comment by 0x7f454c46** [comment]
Looking at the log, I've only found:
```
(00.274569)     70: 		Create fd for 4
(00.274571)      1: Error (criu/files-reg.c:1682): File sys/fs/cgroup/systemd has bad mode 040555 (expect 040755)
```
Would fixing with chmod cgroupfs permissions help for you?

**Comment by ramy150** [comment]
I have found this inside restore log:
Warn  (criu/sk-unix.c:1368): sk unix: Can't unlink stale socket 0x249948 peer 0 (name /var/run/mysqld/mysqld.sock dir -)

but i'm ok if what you suggest can help me to solve my issue!!!
Kind Regards,

**Comment by 0x7f454c46** [comment]
That's only a warning and it might mean that the socket is absent on fs (which is fine, AFAIU).
You can check the error if you have concerns with the following diff:
(even compile UNTESTED)
```
diff --git a/criu/sk-unix.c b/criu/sk-unix.c
index 3963a4ad5ead..d5771f87bea0 100644
--- a/criu/sk-unix.c
+++ b/criu/sk-unix.c
@@ -1539,7 +1539,7 @@ static void unlink_stale(struct unix_sk_info *ui)
 
        ret = unlinkat(AT_FDCWD, ui->name, 0) ? -1 : 0;
        if (ret < 0) {
-               pr_warn("Can't unlink stale socket %#x peer %#x (name %s dir %s)\n",
+               pr_warn("Can't unlink stale socket %#x peer %#x (name %s dir %s) : %m\n",
                        ui->ue->ino, ui->ue->peer,
                        ui->name ? (ui->name[0] ? ui->name : &ui->name[1]) : "-",
                        ui->name_dir ? ui->name_dir : "-");
```

**Comment by ramy150** [comment]
Hi, I tried for the chmod proposition and without success, it's always the same error. I noticed that there are some ghost files in the last dump do you think that it's may cause the issue.

**Comment by 0x7f454c46** [comment]
Just for sure, have you chmod `sys/fs/cgroup/systemd` on the _destination_ node for migration, not on the source node? (And checked perms afterwards?)

**Comment by ramy150** [comment]
I maid a mistake in the chmod I put it 777 it was still given me this error and when I did the same amount of privilege they asked for (chmod 755 /sys/fs/cgroup/systemd ) it works.
Thanks for your precious helping
