### ISSUE TITLE
Namespace & GTP protocol unsupported 

### ISSUE THREAD

**Issue by ramy150** [checkpoint-restore/criu#405]
Dear all

It seems that we have found another problem during the dump part of the live migration (the last part of the live migration). After investigating we observed that GTP is causing trouble to our tests. If someone can help it will be great.

attached you can find all the collected information and log files:

Host1 information:
[host1_information.txt](https://github.com/checkpoint-restore/criu/files/1433759/host1_information.txt)

Host2 information:
[host2_information.txt](https://github.com/checkpoint-restore/criu/files/1433760/host2_information.txt)

container config file:
[config.txt](https://github.com/checkpoint-restore/criu/files/1433772/config.txt)

dump phase log file:
[dump.log](https://github.com/checkpoint-restore/criu/files/1437876/dump.log)

**Comment by xemul** [comment]
Ah, that's another type of netdevice :) I can suggest you two things -- first is to skip dumping (and restoring) net namespace with the --empty-ns net option. In this case criu will skip dumping (and restoring) net ns, you'll have to set it up your own.

Another option is to add support for gpt device. That's not hard. I've recently did it for sit tunnels, the patches are 4a044e6af93f6b9d473a8ca56cbc0b07224cf6ab for dump and 87bfe588006929f1fce5110a1e2b615b28828989 for restore (and fb85281c3b88cd159255bbadbe8e6882ecf2e576 for test). If you're willing to take this part we will provide all the needed help :)

**Comment by ramy150** [comment]
Hi, Pavel, we tried the first path and it seems that we have this problem in the restore part.

Restore part:
[restore3.log](https://github.com/checkpoint-restore/criu/files/1454478/restore3.log)

kindly take a look at it and give further suggestions.

**Comment by ramy150** [comment]
Hi Pavel,

after investigating we observed that there is a lot of constraints, so now we are thinking about how to contribute to the CRIU code in order to solve all the related issue to GTP protocol. Please, if you can provide for us all the necessary in order to start working on the integration of GTP in CRIU code.

Best Regards,

**Comment by xemul** [comment]
@ramy150 that's good news. To support another netdevice you can look at how SIT device is handled. And post your questions here or on the mailing list.

**Comment by ramy150** [comment]
Hi @xemul 

Concerning the GTP contribution, we tried to finish the work, however, we are facing a problem in the restore part. The dump part was successfully integrated.

attached you can find the contribution link followed by the log files of the dump and the restore.

link to the contribution: 
[https://github.com/MOSAIC-LAB-AALTO/criu-gtp-support/commit/fa4e5de2a95d5d5b8715b14b519e03b9484a77d9](url)

dump log:
[dump.log](https://github.com/checkpoint-restore/criu/files/1720366/dump.log)

restore log:
[restore.log](https://github.com/checkpoint-restore/criu/files/1720368/restore.log)



BR,

**Comment by xemul** [comment]
@ramy150 , I don't see any errors in your restore.log file. Also, I will leave some comments about the code [here](https://github.com/MOSAIC-LAB-AALTO/criu-gtp-support/commit/fa4e5de2a95d5d5b8715b14b519e03b9484a77d9)

**Comment by 0x7f454c46** [comment]
As it's a new feature request, marked no-auto-close.
