### ISSUE TITLE
docker restore error

### ISSUE THREAD

**Issue by vaidehip86** [checkpoint-restore/criu#408]
I'm getting this error from docker restore 
Error response from daemon: shim error: open /tmp/checkpoint2/config.json: no such file or directory
what to do?

**Comment by avagin** [comment]
pls, give us more details what you do. What commands do you run? What version of criu do you use? What version of Docker do you use? What logs do you have? etc

**Comment by vaidehip86** [comment]
Docker version -17.09.0-ce 
criu version- 2.6
Ubuntu 16.04

Following the same steps as given on https://criu.org/Docker getting error for this script
$ docker start --checkpoint-dir=/tmp --checkpoint=checkpoint2 looper-clone
Error response from daemon: shim error: open /tmp/checkpoint2/config.json: no such file or directory

**Comment by avagin** [comment]
Cc: @kolyshkin

**Comment by kolyshkin** [comment]
`--checkpoint-dir` option is currently broken, see https://github.com/moby/moby/issues/34601

**Comment by vaidehip86** [comment]
Then what I need to do? which version I can use to perform checkpoint and restore

**Comment by avagin** [comment]
I can run docker without the --checkpoint-dir option
```
        docker checkpoint create CT_NAME checkpoint1
        docker start --checkpoint checkpoint1 CT_NAME
```

**Comment by hetianzhang** [comment]
you could find the checkpoints in `/tmp/<containerID>/checkpoints`
Therefore, you could add it to `--checkpoint-dir` instead of `/tmp`

It works for me.

**Comment by vaidehip86** [comment]
okay thanks, im able to solve it.

**Comment by vaidehip86** [comment]
Now I'm getting another error for docker restore,
(00.640202) 196: Error (criu/files-reg.c:1528): Can't open file tmp/liblz4-java1595117645323586684.so on restore: No such file or directory
(00.640214) 196: Error (criu/files-reg.c:1463): Can't open file tmp/liblz4-java1595117645323586684.so: No such file or directory
(00.640218) 196: Error (criu/mem.c:513): Can't fixup VMA's fd
(00.641647) 54: Error (criu/cr-restore.c:1021): 196 exited, status=1
(00.650250) Error (criu/cr-restore.c:1024): 13121 killed by signal 9: Killed
(00.661342) mnt: Switching to new ns to clean ghosts
(00.661395) Error (criu/cr-restore.c:1890): Restoring FAILED.

I'm following the same steps commit checkpoint and restore still getting the error
sudo docker run --rm --name cont1 -h scale1.docker -p7077:7077 -p8080:8080 -i spark-cluster
sudo docker commit cont1 sample
sudo docker create --name cont2 sample
sudo docker checkpoint create --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ cont1 chk1
sudo docker start --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ --checkpoint=chk1 cont2

**Comment by vaidehip86** [comment]
@avagin @hetianzhang 
Now I'm getting another error for docker restore,
(00.640202) 196: Error (criu/files-reg.c:1528): Can't open file tmp/liblz4-java1595117645323586684.so on restore: No such file or directory
(00.640214) 196: Error (criu/files-reg.c:1463): Can't open file tmp/liblz4-java1595117645323586684.so: No such file or directory
(00.640218) 196: Error (criu/mem.c:513): Can't fixup VMA's fd
(00.641647) 54: Error (criu/cr-restore.c:1021): 196 exited, status=1
(00.650250) Error (criu/cr-restore.c:1024): 13121 killed by signal 9: Killed
(00.661342) mnt: Switching to new ns to clean ghosts
(00.661395) Error (criu/cr-restore.c:1890): Restoring FAILED.

I'm following the same steps commit checkpoint and restore still getting the error
sudo docker run --rm --name cont1 -h scale1.docker -p7077:7077 -p8080:8080 -i spark-cluster
sudo docker commit cont1 sample
sudo docker create --name cont2 sample
sudo docker checkpoint create --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ cont1 chk1
sudo docker start --checkpoint-dir=/home/hiteshvm1/Documents/tmp/ --checkpoint=chk1 cont2

**Comment by avagin** [comment]
You have a race window between docker commit and docker checkpoint. Something can be changed between these two action on a container file system.

You can try to execute docker run with --tmpfs /tmp

**Comment by vaidehip86** [comment]
@avagin Could you please explain more how i can use  --tmpfs /tmp with my docker run command?
sudo docker run --rm --name cont1 -h scale1.docker -p7077:7077 -p8080:8080 -i spark-cluster
Here, I'm trying to run spark inside my docker container

**Comment by avagin** [comment]
sudo docker run --rm --name cont1 -h scale1.docker -p7077:7077 -p8080:8080 -i spark-cluster --tmpfs /tmp
