### ISSUE TITLE
Live migration of docker container with OpenMPI inside (TCP)

### ISSUE THREAD

**Issue by planetA** [checkpoint-restore/criu#410]
Hello,

I'm trying to create two docker containers on separate hosts and then migrate container from one host to another one. I do as [wiki](https://criu.org/Live_migration) suggests, but when I try to restore the container, it fails with following message:

```
Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /home/user/ckpt/8e973ca0dfe8a2dc0b7b3fc56a8d229184836dd33e9b0fc0eb37de5544268c9e/checkpoints/checkpoint1/criu.work/restore-2017-11-17T14:24:38.910705416-05:00/restore.log
```

For brevity I post the [log](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-restore-log) in separate gists and here I just describe the general scheme.

1. Create a swarm with several nodes in the same overlay network.
2. Create additional containers (openmpi.1 and openmpi.2) and attach them to the overlay network
3. Start mpi application on openmpi.2, which periodically calls MPI_Barrier
4. Create a checkpoint of openmpi.1 into a specified checkpoint directory
5. Transfer checkpoint directory to another node
6. Create another container openmpi.1-clone
7. Restore the checkpoint into openmpi.1-clone. This step fails

The logic behind step one, is that I first configured swarm and then learned that CRIU doesn't work with swarms. But I still could benefit from preconfigured overlay network in swarm mode.

For all these steps I have a [script](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-redeploy-sh), [Dockerfile](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-dockerfile) and [swarm configuration](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-openmpi-debian-yml)

Criu version is 3.6 from github. Docker version is 17.09.0-ce [(full info)](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-docker-info)

My kernel is:

```
Linux ib1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux
```

I tried different variants of migration. It turned out that migrating a container with ping to another node works for me. But restoring container with running MPI application doesn't work even if restoring on the same node [(log)](https://gist.github.com/planetA/8ed7b2e711f73bbb71db53830e3270c3#file-restore_same_node-log). But works if I restore it into the same container.

**Comment by avagin** [comment]
```
[avagin@laptop criu]$ log=~/Downloads/restore.log; for i in `cat $log | awk '/: Error/ { print $2}'`; do cat $log | grep $i | grep -B 5 'Error'; done
(00.385967)      7: 	Receive fd for 1
(00.385970)      7: 	Receive fd for 2
(00.385977)      7: 	Restore: family 2 type 1 proto 6 port 22 state 1 src_addr 10.0.1.10
(00.385985)      7: Restoring TCP connection
(00.385988)      7: Restoring TCP connection id 35 ino b51d7e
(00.386010)      7: Error (criu/files.c:1191): Unable to open fd=3 id=0x35
(00.386229)     20: 	restore mark 0 for socket
(00.386232)     20: 		Create fd for 18
(00.386234)     20: 	Restore: family 2 type 1 proto 6 port 1024 state 1 src_addr 10.0.1.10
(00.386237)     20: Restoring TCP connection
(00.386240)     20: Restoring TCP connection id d2 ino b513fd
(00.386257)     20: Error (criu/files.c:1191): Unable to open fd=20 id=0xd2
(00.386781)     15: Further fle=0x7f129444d7d8, pid=15
(00.386782)     15: Found fd 9 (id pipe:[11869354]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.386786)     15: Inherit fd 9 moved to 13 to resolve clash
(00.386788)     15: 		Create fd for 9
(00.386789)     15: sk unix: Opening standalone socket (id 0x74 ino 0xb51d87 peer 0)
(00.386821)     15: Error (criu/cr-restore.c:1298): 20 exited, status=1
(00.386839)     15: Error (criu/sk-unix.c:1194): sk unix: Can't bind socket: No such file or directory
(00.386843)     15: sk unix: Reverted working dir
(00.386848)     15: Error (criu/files.c:1191): Unable to open fd=10 id=0x74
(00.386781)     15: Further fle=0x7f129444d7d8, pid=15
(00.386782)     15: Found fd 9 (id pipe:[11869354]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.386786)     15: Inherit fd 9 moved to 13 to resolve clash
(00.386788)     15: 		Create fd for 9
(00.386789)     15: sk unix: Opening standalone socket (id 0x74 ino 0xb51d87 peer 0)
(00.386821)     15: Error (criu/cr-restore.c:1298): 20 exited, status=1
(00.386839)     15: Error (criu/sk-unix.c:1194): sk unix: Can't bind socket: No such file or directory
(00.386843)     15: sk unix: Reverted working dir
(00.386848)     15: Error (criu/files.c:1191): Unable to open fd=10 id=0x74
(00.386781)     15: Further fle=0x7f129444d7d8, pid=15
(00.386782)     15: Found fd 9 (id pipe:[11869354]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.386786)     15: Inherit fd 9 moved to 13 to resolve clash
(00.386788)     15: 		Create fd for 9
(00.386789)     15: sk unix: Opening standalone socket (id 0x74 ino 0xb51d87 peer 0)
(00.386821)     15: Error (criu/cr-restore.c:1298): 20 exited, status=1
(00.386839)     15: Error (criu/sk-unix.c:1194): sk unix: Can't bind socket: No such file or directory
(00.386843)     15: sk unix: Reverted working dir
(00.386848)     15: Error (criu/files.c:1191): Unable to open fd=10 id=0x74
(00.387024)     19: 	restore mark 0 for socket
(00.387025)     19: 		Create fd for 17
(00.387028)     19: 	Restore: family 2 type 1 proto 6 port 44742 state 1 src_addr 10.0.1.10
(00.387030)     19: Restoring TCP connection
(00.387032)     19: Restoring TCP connection id bb ino b51da8
(00.387045)     19: Error (criu/files.c:1191): Unable to open fd=19 id=0xbb
```

**Comment by avagin** [comment]
CRIU doesn't restore a network namespace for docker containers. Are you sure that Docker sets the same ip address for a resumed container as it was when a container was dumped.

**Comment by planetA** [comment]
@avagin I'm not sure, how can I check that? I think yes, because ping works and IP address should restore to the same value.

**Comment by avagin** [comment]
Here are two problems.
1. You have to mount tmpfs into container's /tmp. If you want to migrate a docker container, you have to be sure that all new data are placed on tmpfs, otherwise they are not dumped and you will need to migrate a container file system.

(00.000808) sk unix:  `- Got 0xb51d87 peer 0 (name /tmp/openmpi-sessions-1000@8e973ca0dfe8_0/18713/0/usock dir -)
(00.338202)      1: Warn  (criu/sk-unix.c:1515): sk unix: Can't unlink stale socket 0xb51d87 peer 0 (name /tmp/openmpi-sessions-1000@8e973ca0dfe8_0/18713/0/usock dir -)
(00.386789)     15: sk unix: Opening standalone socket (id 0x74 ino 0xb51d87 peer 0)
(00.386839)     15: Error (criu/sk-unix.c:1194): sk unix: Can't bind socket: No such file or directory

**Comment by avagin** [comment]
2. criu can't restore tcp sockets. The log file doesn't contain enough information to investigate this problem.
Could you try to run docker -l debug start  --checkpoint-dir ... and attach a new log?

**Comment by planetA** [comment]
@avagin Setting up tmpfs helped. Thank you.

I had to add:

`--mount type=tmpfs,destination=/tmp`

to docker run and docker create.
