### ISSUE TITLE
CRIU 3.6 make failure on oracle linux 7.3

### ISSUE THREAD

**Issue by dineshputchala** [checkpoint-restore/criu#416]
bash-4.2$ uname -a
Linux slc12moz 4.1.12-61.1.27.el7uek.x86_64 #2 SMP Fri Feb 3 12:31:56 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

bash-4.2$ cat /etc/oracle-release
Oracle Linux Server release 7.3

OS is Oracle Linux 7.3

Steps followed to install CRIU 3.6 version,

bash$pwd
/scratch
 
1. Trying to build and install protobuf

 git clone https://github.com/google/protobuf.git protobuf
 cd protobuf
 ./autogen.sh
 ./configure --prefix=`pwd`/../`uname -m`-linux-gnu
 make
 make install
 cd ../..

 git clone https://github.com/protobuf-c/protobuf-c.git protobuf-c
 cd protobuf-c
 ./autogen.sh
 mkdir ../pbc-`uname -m`
 cd ../pbc-`uname -m`
 ../protobuf-c/configure --prefix=`pwd`/../`uname -m`-linux-gnu \
   PKG_CONFIG_PATH=`pwd`/../`uname -m`-linux-gnu/lib/pkgconfig
 make
 make install

After above steps , I see below directory got created under /scratch

bash-4.2# cd x86_64-linux-gnu
bash-4.2# ls
bin  include  lib

bash-4.2# ls bin
protoc  protoc-c  protoc-gen-c

bash-4.2# ls include/
google  protobuf-c

bash-4.2# ls lib/
libprotobuf-c.a   libprotobuf-c.so.1      libprotobuf-lite.la     libprotobuf-lite.so.14.0.0  libprotobuf.so         libprotoc.a   libprotoc.so.14
libprotobuf-c.la  libprotobuf-c.so.1.0.0  libprotobuf-lite.so     libprotobuf.a               libprotobuf.so.14      libprotoc.la  libprotoc.so.14.0.0
libprotobuf-c.so  libprotobuf-lite.a      libprotobuf-lite.so.14  libprotobuf.la              libprotobuf.so.14.0.0  libprotoc.so  pkgconfig

bash-4.2# ls include/
google/     protobuf-c/

bash-4.2# ls include/protobuf-c/
protobuf-c.h

2. cloned criu and tried to build

git clone https://github.com/checkpoint-restore/criu.git

cd criu
make

But I faced some missing header file errors and missing binaries during make , then done below steps to resolve them,

[a]bash-4.2$ export PATH=$PATH:/scratch/x86_64-linux-gnu/bin

bash-4.2$ echo $PATH
/bin:/usr/bin:/usr/dev_infra/platform/bin:/usr/dev_infra/generic/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/ade/bin:/scratch/x86_64-linux-gnu/bin

bash-4.2$ which protoc-c
/scratch/dputchal/x86_64-linux-gnu/bin/protoc-c

[b]  cp -r /scratch/x86_64-linux-gnu/include/protobuf-c /usr/include/

     cp -r /scratch/x86_64-linux-gnu/include/google/protobuf/* /usr/include/

[c] Downloaded libnet from github (https://github.com/sam-github/libnet.git)  and installed it to resolve missing libnet.h files error during criu make

After above steps , I see below error now,

bash-4.2$ make
make[1]: Nothing to be done for `all'.
make[1]: `images/built-in.o' is up to date.
make[1]: `compel/plugins/std.lib.a' is up to date.
make[1]: `compel/plugins/fds.lib.a' is up to date.
make[1]: `compel/libcompel.a' is up to date.
make[1]: `compel/compel-host-bin' is up to date.
make[1]: Nothing to be done for `all'.
make[1]: `soccr/libsoccr.a' is up to date.
criu/Makefile.packages:25: Can not find some of the required libraries
criu/Makefile.packages:25: Make sure the following packages are installed
criu/Makefile.packages:25: RPM based distros: protobuf protobuf-c protobuf-c-devel protobuf-compiler protobuf-devel protobuf-python libnl3-devel libcap-devel
criu/Makefile.packages:25: DEB based distros: libprotobuf-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libcap-dev
criu/Makefile.packages:25: To run tests the following packages are needed
criu/Makefile.packages:25: RPM based distros: libaio-devel
criu/Makefile.packages:25: DEB based distros: libaio-dev
criu/Makefile.packages:25: *** Compilation aborted.  Stop.
make[1]: *** [check-packages] Error 2
make: *** [criu] Error 2

Copied libs from "/scratch/x86_64-linux-gnu/lib/" to /usr/lib64

bash-4.2$ ls /usr/lib64 |grep protobuf
libprotobuf-c.a
libprotobuf-c.la
libprotobuf-c.so
libprotobuf-c.so.1
libprotobuf-c.so.1.0.0
libprotobuf-lite.a
libprotobuf-lite.la
libprotobuf-lite.so
libprotobuf-lite.so.14
libprotobuf-lite.so.14.0.0
libprotobuf.a
libprotobuf.la
libprotobuf.so
libprotobuf.so.14
libprotobuf.so.14.0.0
libprotobuf.so.8
libprotobuf.so.8.0.0
bash-4.2$

Even then I see same error while doing make.

Also tried , export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/scratch/x86_64-linux-gnu/lib/
export LIBRARY_PATH=$LIBRARY_PATH:/scratch/x86_64-linux-gnu/lib/

But same error while doing a make in criu dir.

**Comment by adrianreber** [comment]
I hardly know anything about oracle linux except that it is supposed to be a RHEL clone. CRIU on RHEL/CentOS works correctly, you could use that. If you want to compile it yourself, your approach seems unnecessary complicated. As oracle linux ships CRIU, they have to build it. This means all build dependencies are part of your distribution. Install the necessary distribution package and type 'make'. That is all. I am using CentOS and RHEL as a CRIU development system and it just works.

**Comment by dineshputchala** [comment]
Yum search for criu lists only criu 2.12v , so trying to build criu 3.6

bash-4.2# yum install criu

Package criu-2.12-2.el7.x86_64 already installed and latest version
Nothing to do


As per below page,

https://criu.org/Installation

CRIU build requires "protobuf protobuf-c protobuf-c-devel protobuf-compiler protobuf-devel protobuf-python"

I have already checked in my machine ,  some of the above packages are not available and hence I tried to build

bash-4.2# yum search protobuf

=================================================================== N/S matched: protobuf ====================================================================
protobuf.i686 : Protocol Buffers - Google's data interchange format
protobuf.x86_64 : Protocol Buffers - Google's data interchange format
protobuf-c.i686 : C bindings for Google's Protocol Buffers
protobuf-c.x86_64 : C bindings for Google's Protocol Buffers


Is there any specific repo which lists CRIU 3.6v and above protobuf packages ?

**Comment by adrianreber** [comment]
That is the result on RHEL/CentOS for the same query:

```
protobuf.i686 : Protocol Buffers - Google's data interchange format
protobuf.x86_64 : Protocol Buffers - Google's data interchange format
protobuf-c.i686 : C bindings for Google's Protocol Buffers
protobuf-c.x86_64 : C bindings for Google's Protocol Buffers
protobuf-c-compiler.x86_64 : Protocol Buffers C compiler
protobuf-c-devel.x86_64 : Protocol Buffers C headers and libraries
protobuf-compiler.x86_64 : Protocol Buffers compiler
protobuf-devel.x86_64 : Protocol Buffers C++ headers and libraries
protobuf-python.x86_64 : Python bindings for Google Protocol Buffers
```

So, as building protobuf yourself failed, please use an operating system which provides the packages you need or figure out why your OS is not shipping the development packages. Again, this is not related to CRIU.

**Comment by dineshputchala** [comment]
Can u just paste your repo details which is providing above packages ?

example:
vim /etc/yum.repos.d/PDIT-ol7.repo

[ol7_addons]
name=OracleLinux OL7 addons $basearch
baseurl=http://pd-yum-slc-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-den-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-bus-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-llg-01.uk.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-adc-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-rws-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
        http://pd-yum-sca-01.us.oracle.com/pditrepos/OracleLinux/OL7/addons/$basearch
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle-7
gpgcheck=1
enabled=1

**Comment by adrianreber** [comment]
I cannot look at those repositories to check. Are those oracle internal only repository?

You should really just install CentOS and try it. It is in the base repository:

```
# yum info protobuf-c-devel | grep Repo
Repo        : base/7/x86_64
```

So the most simplest CentOS installation should work. I doubt it would be a good idea to install CentOS packages on oracle linux.

**Comment by 0x7f454c46** [comment]
> criu/Makefile.packages:25: Can not find some of the required libraries

That means that you don't have some shared library.
Try to compile hello-world program like this:
```
int main(int argc, char **argv) { return 0; }
```
And specify the following flags to your gcc:
```
gcc hello-world.c -lrt -lpthread -lprotobuf-c -ldl -lnl-3 -lsoccr -Lsoccr/ -lnet -o /dev/null
```
As libsoccr is built by criu itself, I suspect that it's not the reason of your failure,
so basically you just don't have one of this libs: `-lrt -lpthread -lprotobuf-c -ldl -lnl-3 -lnet`.
I would suggest to try removing them one-by-one for hello-world compilation and finding a lib which you're missing.

**Comment by dineshputchala** [comment]
bash-4.2#  gcc test.c  -lrt -lpthread -lprotobuf-c -ldl -lnl-3 -lsoccr -Lsoccr/ -lnet -o /dev/null
/bin/ld: cannot find -lnl-3
/bin/ld: cannot find -lsoccr

bash-4.2# yum search libnl
==
libnl-devel.i686 : Libraries and headers for using libnl
libnl-devel.x86_64 : Libraries and headers for using libnl
libnl3-cli.i686 : Command line interface utils for libnl3
libnl3-cli.x86_64 : Command line interface utils for libnl3
libnl.i686 : Convenience library for kernel netlink sockets
libnl.x86_64 : Convenience library for kernel netlink sockets
libnl3.i686 : Convenience library for kernel netlink sockets
libnl3.x86_64 : Convenience library for kernel netlink sockets

I have installed all above , but still see "/bin/ld: cannot find -lnl-3" . May be it require some dev pkg of libnl3.

**Comment by adrianreber** [comment]
You need libnl3-devel

**Comment by 0x7f454c46** [comment]
I think you don't have binary sharad library.
In my case it's:
```
/usr/lib64/libnl-3.so.200
/usr/lib64/libnl-3.so.200.25.0
```
So that's what linker says to you - you need to have some package which provides such .so library.

**Comment by dineshputchala** [comment]
I have

bash-4.2# ls /usr/lib64/| grep libnl-3
libnl-3.so.200
libnl-3.so.200.23.0

**Comment by 0x7f454c46** [comment]
Yes, so you don't have `libnl-3.so`.
You can make it a symlink to `libnl-3.so.200`, but..
I think it's provided by `libnl3-devel` as @adrianreber said.
So, after you'll have a symlink - you'll have compilation errors in missing headers.

**Comment by dineshputchala** [comment]
Already checked , my yum is not listing libnl3-devel

**Comment by 0x7f454c46** [comment]
Well, I don't know much about Oracle Linux packaging.
But at least you know now what's missing.
At worst you can always compile it yourself and package/make install in the /opt/lib64

**Comment by dineshputchala** [comment]
Downloaded libnl3 and built it and created softlinks to my include dir's to resolve header file issues.
