### ISSUE TITLE
Built  in Ubuntu and deployed on Yocto but /run/criu.kdat not found

### ISSUE THREAD

**Issue by 0Camus0** [checkpoint-restore/criu#417]
Hello, I built the project, resolved the dependencies, but when try to dump I got this errors:

root@:Dom0 ~ $ ./criu dump --tree 524 --images-dir /home/root/images/ --leave-stopped
Warn  (criu/kerndat.c:658): Can't load /run/criu.kdat
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/sockets.c:132): Diag module missing (-2)
Error (criu/kerndat.c:182): Can't stat self map_files 2: No such file or directory

I looked on the project directory and couldn't find any criu.kdat.

**Comment by avagin** [comment]
I think your kernel is compiled without CONFIG_CHECKPOINT_RESTORE
