### ISSUE TITLE
docker checkpoint restore can not find config.json file

### ISSUE THREAD

**Issue by slient-rain** [checkpoint-restore/criu#419]
I use docker checkpoint create command to get a checkpoint of a running container,
but when i use checkpoint ls or start --checkpoint command to view or start the checkpoint i got an error : can not find config.json file, anyone know the reason?

ERRO[2017-12-04T11:47:52.383359149+08:00] Handler for GET /v1.34/containers/looper/checkpoints returned error: open /var/lib/docker/containers/aab56fd5eba6d38f7a5aac04de9da23c0a7e04c1a73e474648a78bdad3170bdc/checkpoints/checkpoint1/config.json: no such file or directory 

docker verion:
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:36:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:10 2017
 OS/Arch:      linux/amd64
 Experimental: true

criu verion：
Version: 3.6
GitID: v3.6-65-g3121d90

**Comment by adrianreber** [comment]
config.json is not a CRIU file and so I guess this needs to be handled by docker. The error seems unrelated to the actual process of checkpointing or restoring and the usage of CRIU.

**Comment by slient-rain** [comment]
@adrianreber  then do you have any idea about this error?What should i do to check what is the reason resulting in the problem .And more details, after i executed checkpoint create command ,the container is not stopped.

**Comment by adrianreber** [comment]
It is hard to tell what your problems might be without knowing what you did. Some more information would be really helpful. The commands you used, the environment, the container and probably even more. But from my point of view this is primarily not a CRIU problem from what you reported. You are using docker commands and something did not work. There is not a single CRIU error message. So maybe reach out to docker and try to get the setup working.

If there is then a CRIU error message or warning come back here for help.

**Comment by slient-rain** [comment]
@adrianreber  Thank you very much, I was  puzzled by this problem for a few days,but now it is solved.The problem is indeed  caused by the docker environment . I changed the docker version from 17.11 to 11.04, and other environment is the same as before ,and the problem is disappeared.

**Comment by adrianreber** [comment]
Would it make sense to open a docker ticket to track this?

**Comment by kolyshkin** [comment]
Yes this is a docker issue; not sure if it's reported already or not

**Comment by adrianreber** [comment]
@kolyshkin thanks for clarifying

@slient-rain can you report your problem in the docker bug  tracker so it does not get lost?

**Comment by slient-rain** [comment]
@adrianreber OK，I am glad to report this problem,but I am new student and not very familiar with this , what should I do to report the problem in the docker bug tracker or where should I go to report it?

**Comment by user171** [comment]
Anyone knows if it is reported on Docker? I think I am experiencing the same bug and I am looking for the corresponding ticket. Thanks.

**Comment by adrianreber** [comment]
I am not aware. If you want, please open a bug and mention it here.

**Comment by user171** [comment]
It looks like this is the one: https://github.com/moby/moby/issues/35690 and it also links to https://github.com/moby/moby/issues/35691

**Comment by adrianreber** [comment]
Thanks for tracking down. I guess this could be closed as it is a docker bug.
