### ISSUE TITLE
Checkpoint creation sporadically fails with timeout

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#423]
We're doing C/R on docker containers. The containers being checkpointed run serveral different processes. We've recently noticed that about 4% of the time creating the checkpoint fails with this error: "Error (criu/cr-dump.c:1445): Timeout reached. Try to interrupt: 0". (full dump log attached)

[dump.txt](https://github.com/checkpoint-restore/criu/files/1543686/dump.txt)

Unfortunately, there's not a lot of information in the dump log. The failure happens very early on when criu is walking the process tree and freezing the processes. It looks like criu times out waiting for a particular process to stop execution after freezing it with ptrace. The process which hangs the dump is the 6th process criu seizes out of 11 processes in the tree.

We were wondering if you guys had any ideas on what might be causing the checkpoint to fail. Is there any other diagnostic information we can grab the next time this happens that would be helpful in debugging the issue?

We were also wondering in what order does criu seize the various processes in the process trees. It looks like it walks the process tree based on the ordering in /proc/[pid]/task/[tid]/children. However, I'm not sure how the contents in this file or ordered, if they are at all. They don't seem to be ordered by start time or pid. Is the ordering of this file random?

We are using criu version 3.6 and kernel version 4.13.

**Comment by avagin** [comment]
@tswift242 Could you collect a perf trace for a criu dump process?

You will need to apply this patch:
```
diff --git a/criu/cr-dump.c b/criu/cr-dump.c
index 35ca7019e..bfa89ab93 100644
--- a/criu/cr-dump.c
+++ b/criu/cr-dump.c
@@ -1721,6 +1721,8 @@ int cr_dump_tasks(pid_t pid)
        int pre_dump_ret = 0;
        int ret = -1;
 
+       sleep(100);
+
        pr_info("========================================\n");
        pr_info("Dumping processes (pid: %d)\n", pid);
        pr_info("========================================\n");
```

Then you need to execute docker -vvvv checkpoint ... and from another console you need to find a criu process and execute perf trace -p PID -o trace.log and wait when the criu process will exit.

**Comment by avagin** [comment]
@tswift242 btw: Does a container live in a separate freezer cgroup?

**Comment by tswift242** [comment]
@avagin Thanks for replying. I can try to collect a perf trace. Right now I don't have a way to consistently reproduce this issue. If I find a way to do that, I'll look into getting a perf trace.

I have not explicitly specified any settings to docker/runc/criu related to freezer cgroups, so it's using whatever the default is, which I think is to not have a separate freezer cgroup?

We were also wondering more generally if you guys have any insight as to what may prevent or delay the kernel from being able to freeze a process.
