### ISSUE TITLE
FAIL: Restore of RabbitMQ Cluster of 3 Nodes is failing

### ISSUE THREAD

**Issue by harishankard** [checkpoint-restore/criu#426]
Following Steps:
1. Created dump on all the 3 nodes of RabbitMQ cluster.(Eg. ./criu dump --tree 7432 --images-dir ./build -vvvvv --tcp-established --shell-job) (Dump Created Successfully) 
2. Removed the VM and created a VM with same IP , HOST etc. (it is clone of the actual VM)
3. Applied the iptables rules also which were obtained during dump in the new VM.
4. Triggered restore on the all 3 nodes of RabbitMQ cluster.(Eg. /criu restore -t 7432 --images-dir ./build/ -vvvvv --tcp-established --shell-job --restore-detached)
Restore failed on all 3 nodes.
Attached the logs.
[criu_restore_log.log](https://github.com/checkpoint-restore/criu/files/1551576/criu_restore_log.log)

**Comment by avagin** [comment]
What criu version do you use? Could you check dmesg? 
```
$ dmesg | grep segfault
```

**Comment by harishankard** [comment]
I haves used this version of CRIU :http://download.openvz.org/criu/criu-3.6.tar.bz2 
This error occurs sometimes and sometimes it restores fine.
Also when this error occurs "dmesg | grep segfault" doesn't return any output and i didn't  find any segmentation fault.

**Comment by avagin** [comment]
@harishankard What we have here. A process has a few threads. CRIU detaches from a group leader, and then CRIU detaches from other threads, but gets these errors. Usually this means that the group leader was exited or it was killed.

BTW: These errors are not fatal.

**Comment by avagin** [comment]
You can try to enable trace events to understand what is going on there:
echo 1 > /sys/kernel/debug/tracing/events/sched/sched_process_exit/enable 
echo 1 > /sys/kernel/debug/tracing/events/sched/sched_process_fork/enable 
echo 1 > /sys/kernel/debug/tracing/events/signal/enable 
echo 1 > /sys/kernel/debug/tracing/events/sched/sched_process_exec/enable

that you need to try to restore processes and analyse a content of /sys/kernel/debug/tracing/trace

**Comment by harishankard** [comment]
Hi,
We don't find any information in trace or logs. But we noticed this behaviour 
1. Created dump of rabbitmq process in a VM.
2. Restore the dump of rabbitmq process in same VM. It restores successfully. 
3. Created another dump of rabbitmq process in a VM.
4. Restart the VM. Restore the rabbitmq process. No errror but the process never comes up. When checked it rabbitmq startup-err logs it says " OS monotonic time stepped backwards
Aborted".
5. Try the same dump to restore after some 15-20 mins interval , the process is restored successfully. 
6. Created a dump of rabbitmq process in a VM.
7. Moved this dump to another VM and restarted the VM and applied the restore of dump.
8. No error but the process never comes up as mentioned above. But after some interval time when we do restore the process comes up.

We find this error added whenever the process never comes up : 
   OS monotonic time stepped backwards
Aborted
Any solution for this error...?

**Comment by shashankmjain** [comment]
https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_time_sup.c is where this error appears in Erlang code.

**Comment by shashankmjain** [comment]
Infact changing the Erlang setting to not do a time check, fixes the issue for me. Is there some setting in CRIU which is possible though to fix this?

**Comment by avagin** [comment]
It is the known problem and it can't be fixed without changing the kernel.
https://criu.org/Time_namespace

There was an attempt to implement this feature ten years ago
https://lkml.org/lkml/2006/4/19/34

**Comment by shashankmjain** [comment]
Then the only way is to set this at Erlang level as I had suggested above?

**Comment by avagin** [comment]
@shashankmjain yes, it is. You can use this way, if it works for you. But it is a workaround. And if we want to fix this issue, we have to fix the kernel.
