### ISSUE TITLE
Fail: Dump For PostgreSql fails

### ISSUE THREAD

**Issue by harishankard** [checkpoint-restore/criu#428]
Hi ,
I tried create checkpoint dump for PostgreSql. It fails with the following error:
(00.027752) Error (criu/cr-dump.c:431): Task 8778 with SysVIPC shmem map @7f173f7d3000 doesn't live in IPC ns
(00.027784) Error (criu/cr-dump.c:1411): Dump mappings (pid: 8778) failed with -1
I ran this command ./criu dump --tree 8778 --images-dir ./build -vvvvv --tcp-established --shell-job
[criu_log.log](https://github.com/checkpoint-restore/criu/files/1562163/criu_log.log)

**Comment by adrianreber** [comment]
Processes which are using SysVIPC shared memory need to be in a IPC namespace like the error message says.

So you need to stop the database, unshare -i, start the database and try it again.

I have successfully live migrated postgresql this way.

**Comment by harishankard** [comment]
Hi,
I was able create a dump for PostgreSql when there was no Shared Buffer Cache with unshare -i. But when i tried to create a dump of postgresql which contained shared cache buffer, the dump failed with the following error:
Command Ran : 
./criu dump --tree 15189 --images-dir ./build -vvvvv --tcp-established --shell-job --ext-unix-sk

(00.425640) sk unix: Dumping external sockets
(00.425662) sk unix:    Dumping extern: ino 0x4495 peer_ino 0 family    1 type    2 state  7 name /dev/log
(00.425732) sk unix:    Dumped extern: id 0x95 ino 0x4495 peer 0 type 2 state 10 name 9 bytes
(00.425787) sk unix:    Dumped: id 0x13 ino 0xb1709 peer 0x4495 type 2 state 7 name 0 bytes
(00.425855) sk unix:    Dumping extern: ino 0xb1884 peer_ino 0xb1885 family    1 type    1 state  1 name (null)
(00.425920) sk unix:    Dumped extern: id 0x96 ino 0xb1884 peer 0 type 2 state 10 name 0 bytes
(00.425994) sk unix:    Ext stream not supported: ino 0xb1884 peer_ino 0xb1885 family    1 type    1 state  1 name (null)
(00.426049) Error (criu/sk-unix.c:715): sk unix: Can't dump half of stream unix connection.

**Comment by avagin** [comment]
Here is an article which explains this error:
https://criu.org/External_UNIX_socket
