### ISSUE TITLE
Mips supprot

### ISSUE THREAD

**Issue by jackssirs** [checkpoint-restore/criu#431]
Ciru Do not support mips, how to add MIPS support?

**Comment by avagin** [comment]
You need to look in criu/arch/ and compel/arch/, thera are directories for each supported architectures. You need implement the same things for MIPS.

**Comment by jackssirs** [comment]
I can implement  c code，but no the mips asm at all

**Comment by avagin** [comment]
@jackssirs I can't too;). We need someone who can.

**Comment by jackssirs** [comment]
@avagin  you know someone who familiar mips assembler

**Comment by Ydcool** [comment]
Hi,  if I can provide some kind of mips asm, could you do that implementions ? @avagin @jackssirs

**Comment by adrianreber** [comment]
The latest CRIU versions are supporting MIPS. Closing.
