### ISSUE TITLE
Restoration failed: 9060: Error (criu/files-reg.c:1682) 

### ISSUE THREAD

**Issue by psinha01** [checkpoint-restore/criu#433]
I am doing a live migration of a memory intensive process using page server and iterative migration.
After final iteration, I copy the all the dumps other than user memory dumps on destination using scp. Then I try to restore the process on destination which results in following error:
```
9060: Error (criu/files-reg.c:1682): File home/o196/sample/pagef has bad mode 0100755 (expect 0100775)
  9060: Error (criu/mem.c:689): Can't fixup VMA's fd
Error (criu/cr-restore.c:1301): 9060 killed by signal 9: Killed
Error (criu/cr-restore.c:2171): Restoring FAILED

```

Following are the steps that i followed:
Step 1: creating tmpfs on destination and source
On destination: 
```
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/d1/
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/d2/
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/df/
```

On source: 
```
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/d1/
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/d2/
sudo mount -t tmpfs none  /home/o196/sample/predump_tempfs/df/
```
Step 2: On destination: running a page server to receive dumps for 1st iteration:

`sudo criu page-server -D /home/o196/sample/predump_tempfs/d1 -o ps.log -v4 --port 22222`

Step 3: On source, running pre-dump to dump memory for 1st iteration and send to destination's page server:

`sudo criu pre-dump --tree <pid> --images-dir d1 --shell-job --track-mem --leave-running -o dmp.log --page-server --address 10.128.19.10 --port 22222`

Step 3: On destination: running a page server to receive dumps for 2nd iteration:

`sudo criu page-server -D /home/o196/sample/predump_tempfs/d2 -o ps.log -v4 --port 22222`

Step 4: On source, running pre-dump to dump memory for 2nd iteration and send to destination's page server:

`sudo criu pre-dump --tree <pid> --images-dir d2 --prev-images-dir ../d1 --shell-job --track-mem --leave-running -o dmp.log --page-server --address 10.128.19.10 --port 22222`

Step 5: On destination: running a page server to receive dumps for final iteration:

`sudo criu page-server -D /home/o196/sample/predump_tempfs/df -o ps.log -v4 --port 22222`

Step 6: On source, running pre-dump to dump memory for final iteration and send to destination's page server:

`sudo criu dump --tree <pid> --images-dir df --prev-images-dir ../d2 --shell-job --track-mem -o dmp.log --page-server --address 10.128.19.10 --port 22222`

The process on source is killed after above command. 

Step 7: 
I copy all the "img" files from from source's "df" i.e. directory having dumps for final iterations to destination's "df" (directory having dumps for final iteration) using scp. 

Step 8:
On destination, I create softlinks to make sure iterative dumps are linked i.e.
```
df/parent -> ../d2
d2/parent -> ../d1
```

Step 9: Ran the command to restore the process
`sudo criu restore --images-dir /home/o196/sample/predumps/df --shell-job 
`

**Comment by avagin** [comment]
```
9060: Error (criu/files-reg.c:1682): File home/o196/sample/pagef has bad mode 0100755 (expect 0100775)
```
This error means that a file tree isn't synced between source and destination nodes. For example, home/o196/sample/pagef has different permissions.
