### ISSUE TITLE
make test fails - TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by itoffshore** [checkpoint-restore/criu#434]
`criu 3.7` builds successfully on Alpine Linux `3.7` but running `make test` fails with:

```
 LINK      fifo_loop
make[2]: Leaving directory '/home/stuart/aports/testing/criu/src/criu-3.7/test/zdtm/transition'
make[1]: Leaving directory '/home/stuart/aports/testing/criu/src/criu-3.7/test/zdtm'
make[1]: Entering directory '/home/stuart/aports/testing/criu/src/criu-3.7/test'
make zdtm
make[2]: Entering directory '/home/stuart/aports/testing/criu/src/criu-3.7/test'
./zdtm.py run -a --parallel 2
Traceback (most recent call last):
  File "./zdtm.py", line 23, in <module>
    import criu as crpc
  File "/home/stuart/aports/testing/criu/src/criu-3.7/test/criu.py", line 12, in <module>
    import rpc_pb2 as rpc
  File "/home/stuart/aports/testing/criu/src/criu-3.7/test/rpc_pb2.py", line 172, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
make[2]: *** [Makefile:23: zdtm] Error 1
make[2]: Leaving directory '/home/stuart/aports/testing/criu/src/criu-3.7/test'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/home/stuart/aports/testing/criu/src/criu-3.7/test'
make: *** [Makefile:285: test] Error 2
```
I have `python-yaml` installed as a `checkdepends`

**Comment by avagin** [comment]
We run our test on alpine 3.7 https://travis-ci.org/checkpoint-restore/criu/jobs/323479272

**Comment by avagin** [comment]
rpc_pb2 is generated by this command:
```
protoc -I=images/ --python_out= images/rpc.proto
```

**Comment by avagin** [comment]
@itoffshore I think its issue depends on a protobuf compiler, what you use. Could you check that all protobuf packages have the same version?

**Comment by itoffshore** [comment]
@avagin - yes I think this is the cause thank you:

```
musl64 [~/aports/testing/criu]$ apk search protobuf
protobuf-3.5.1-r1
protobuf-c-1.3.0-r5
py2-protobuf-3.2.0-r0
ruby-google-protobuf-3.5.1-r1
protobuf-c-dev-1.3.0-r5
protobuf-dev-3.5.1-r1
py3-protobuf-3.2.0-r0
protobuf-vim-3.5.1-r1
py-protobuf-3.2.0-r0
```
I'll update `py-protobuf` & re-run the tests

**Comment by avagin** [comment]
@itoffshore can we close this issue?

**Comment by itoffshore** [comment]
yes I think you found the problem with the library mismatch.

**Comment by zaninip** [comment]
Dear everybody,
I write here since my problem seems similar to that discussed here.
I installed the release 3.5.1 of protobuf according to
https://github.com/google/protobuf/tree/master/python

Then, trying the addressbook tutorial
https://developers.google.com/protocol-buffers/docs/pythontutorial
I have an error in the python script when running
import addressbook_pb2

```
Traceback (most recent call last):
  File "Data/Paolo/test/script_test.py", line 2, in <module>
    import addressbook_pb2
  File "D:\Data\Paolo\test\addressbook_pb2.py", line 67, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
```
Do you have any idea?

Thank you very much in advance,
Paolo

**Comment by zaninip** [comment]
I solved the problem deleting by hand from every _descriptor.FieldDescriptor in the <name>_pb2.py file created by the compilar, the argument file=DESCRIPTOR.
With this "trick", now I can read the .proto file.
This is a very strange bug, somone has already had it?

**Comment by avagin** [comment]
@zaninip could you check that all protobuf libraries have the same version?

**Comment by andypost** [comment]
Tests still fail with protobuf 3.5.1 & criu 3.8.1
```
make[3]: Leaving directory '/mnt/testing/criu/src/criu-3.8.1/test'
mount: permission denied (are you root?)
Traceback (most recent call last):
  File "./zdtm.py", line 2113, in <module>
    tst.available()
  File "./zdtm.py", line 528, in available
    subprocess.check_call(["flock", "zdtm_mount_cgroups.lock", "./zdtm_mount_cgroups"])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flock', 'zdtm_mount_cgroups.lock', './zdtm_mount_cgroups']' returned non-zero exit status 1
make[2]: *** [Makefile:23: zdtm] Error 1
```
Any idea what could be wrong

**Comment by avagin** [comment]
@andypost 
```
make[3]: Leaving directory '/mnt/testing/criu/src/criu-3.8.1/test'
mount: permission denied (are you root?)
```
Here we execute a command like this:
$ mount -t cgroup -o none,name=zdtmtst zdtm /tmp/zdtm.XXXXXX

zdtm_mount_cgroups mounts test cgroups, and so it requires super-user privileges.

**Comment by andypost** [comment]
@avagin thanx a lot not it's clear
