### ISSUE TITLE
Zombied process and Migration

### ISSUE THREAD

**Issue by MadMub** [checkpoint-restore/criu#435]
Hello, I've been playing with criu a bit. I have been able to dump and restore a c++ app (when it is run isolated and not attached to a shell session). I followed the instructions here:

https://criu.org/Simple_loop

Although the memory usage of my VM decreases in htop, the process seems to still be present in the list of processes (I know htop can be misleading sometimes though). Is the process zombied? When I then manually killed the pid after a successful dump, and attempted a restore the result failed (claiming a PID mismatch).

I am looking to potentially migrate the process to another VM and the instructions for that seem to be incomplete regarding killing the source pid

https://criu.org/Live_migration#Kill

My apologies if this was not the appropriate forum to ask questions, I am also very new to criu and toying with linux at this low level.

**Comment by adrianreber** [comment]
Maybe you could give us more details. How do you use CRIU? Which options, parameters and the version (and kernel). How do you determine memory usage? Normally the process is gone after a successful dump but complete command-lines and CRIU logs would make answering this a lot easier. Right now an answer is impossible besides that it usually works.

**Comment by MadMub** [comment]
After a full VM restart, I actually am not able to recreate the situation I had before. Everything appears to be fully released and restored now (no leftover PIDS). My apologies for jumping the gun with a question.

For reference
Kernel: `4.10.0-19-generic`
Criu Version: `2.12.1`
Criu Check: `Looks good.`
