### ISSUE TITLE
criu with VirtualGL

### ISSUE THREAD

**Issue by phil294** [checkpoint-restore/criu#436]
General GPU dumping is not supported because it is highly driver-dependent (#384). Could it be possible to do so using virtualized OpenGL? https://virtualgl.org/ (OS)

The error I am getting is `Error (criu/proc_parse.c:549): Can't handle non-regular mapping on 19509's map 7fef8da4c000`. Is this intended? Is there a way to get it working?

Reproduce:
- Steps explained at https://criu.org/VNC (awesome!!)
- `Xvnc` also needs the option `-depth 24` passed
- Install VirtualGL, start program with `vglrun`. For demonstration purposes: `vglrun glxheads`
- Dump as specified (`--tcp-established`) -> error

**Comment by avagin** [comment]
I don't know how vglrun works, but it doesn't allow us to avoid  /drm mappings, criu doesn't support them right now.

```
[avagin@laptop linux-task-diag]$ ps -C glxgears
  PID TTY          TIME CMD
  544 pts/7    00:01:08 glxgears
[avagin@laptop linux-task-diag]$ ls -l /proc/544/map_files/
...
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b732000-7fc41b73a000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b762000-7fc41b7ba000 -> /SYSV00000000 (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b7ba000-7fc41b7ca000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b7ca000-7fc41b8ca000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b8fe000-7fc41b8ff000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b8ff000-7fc41b900000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b900000-7fc41b901000 -> /memfd:xshmfence (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b901000-7fc41b902000 -> /memfd:xshmfence (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b903000-7fc41b904000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b904000-7fc41b90c000 -> /drm mm object (deleted)
lrw-------. 1 avagin avagin 64 Jan 17 09:22 7fc41b90c000-7fc41b92d000 -> /SYSV00000000 (deleted)
```

**Comment by phil294** [comment]
@avagin ok thanks. I am not seeing any /drm mappings, but some /dev/nvidiactl and /dev/nvidia0. The issue is probably the same?
Any idea on how to workaround this? Criu+VNC is doable, OpenGL/VirtualGL is not.

I assume that the possibility of checkpointing these kind of mappings would result in various new usecases.
