### ISSUE TITLE
lxd stateful stop fails

### ISSUE THREAD

**Issue by iatrou** [checkpoint-restore/criu#439]
Trying to do a stateful stop for a LXD container fails:

$ lxc launch ubuntu:x c1
$ lxc list
+------+---------+----------------------+------+------------+-----------+
| NAME |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+----------------------+------+------------+-----------+
| c1   | RUNNING | 10.59.127.189 (eth0) |      | PERSISTENT | 0         |
+------+---------+----------------------+------+------------+-----------+

$ lxc stop c1 --stateful
error: snapshot dump failed
(00.083230) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.359325) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(00.359336) Error (criu/parasite-syscall.c:134): Can't block signals for 10113: No such process
(00.359340) Error (criu/cr-dump.c:1244): Can't infect (pid: 10113) with parasite
(00.375919) Error (criu/ptrace.c:54): Unable to detach from 10113: No such process
(00.376281) Error (criu/cr-dump.c:1628): Dumping FAILED.
Try `lxc info --show-log c1` for more info

$ lxc info --show-log c1
Log:

            lxc 20180124155413.489 ERROR    lxc_criu - criu.c:do_dump:1134 - dump failed with 1
            lxc 20180124155413.489 ERROR    lxc_criu - criu.c:do_dump:1148 - criu output: Will skip in-flight TCP connections

The process it complaints about, 10113 is the following one:
100000   10113  9777  0 15:53 ?        00:00:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0

Manually killing dhclient allows for the stateful stop to complete successfully.

$ uname -a
Linux a0-dc1-002 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

<pre>
$ dpkg -l | egrep 'lxd|lxc|criu' 
ii  criu        2.6-1ubuntu1~ubuntu16.04.2  amd64  checkpoint and restore in userspace
ii  liblxc1     2.0.8-0ubuntu1~16.04.2      amd64  Linux Containers userspace tools (library)
ii  lxc-common  2.0.8-0ubuntu1~16.04.2      amd64  Linux Containers userspace tools (common tools)
ii  lxcfs       2.0.7-0ubuntu1~16.04.2      amd64  FUSE based filesystem for LXC
ii  lxd         2.21-0ubuntu2~16.04.1       amd64  Container hypervisor based on LXC - daemon
ii  lxd-client  2.21-0ubuntu2~16.04.1       amd64  Container hypervisor based on LXC - client
</pre>

$ lxc exec c1 -- dpkg -l isc-dhcp-client
ii  isc-dhcp-client                                    4.3.3-5ubuntu12.7              amd64                          DHCP client for automatically obtaining an IP address

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

~

**Comment by adrianreber** [comment]
I am not 100% sure but I think dhclient might use a raw socket and I do not think CRIU can handle that. But I am happy to be corrected by someone. Do you actually need dhclient in your container?

You could definitely try to use a much newer version CRIU. 2.6 sounds really old.

**Comment by avagin** [comment]
@iatrou could you try the last version of criu? And it would be good if you increase a verbosity level for criu. I don't know how to do this in case of lxc, but you can apply this patch for criu:

```
diff --git a/criu/crtools.c b/criu/crtools.c
index 5f005387d..83ae0b9a3 100644
--- a/criu/crtools.c
+++ b/criu/crtools.c
@@ -974,6 +974,7 @@ int main(int argc, char *argv[], char *envp[])
                return 1;
        }
 
+       log_level = 10;
        log_set_loglevel(log_level);
 
        if (log_init(opts.output))
```

**Comment by iatrou** [comment]
A quick test shows that indeed when dhclient is running, there is a raw socket open.

<pre>
root@c1:~# ps -fe  | grep dhclient
root       197     1  0 17:52 ?        00:00:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
root       363   350  0 17:52 ?        00:00:00 grep --color=auto dhclient

root@c1:~# ss -f link -ln
Netid State      Recv-Q Send-Q                                                                 Local Address:Port                                                                                Peer Address:Port              
p_raw UNCONN     0      0                                                                                  *:eth0                                                                                            *                   

root@c1:~# kill 197
root@c1:~# ps -fe  | grep dhclient
root       369   350  0 17:57 ?        00:00:00 grep --color=auto dhclient
root@c1:~# ss -f link -ln
Netid State      Recv-Q Send-Q                                                                 Local Address:Port                                                                                Peer Address:Port              
</pre>

I installed criu 3.6-2 from bionic (so all the other versions are the same as before), but I still get an error:

<pre>
$ lxc stop c1 --stateful
error: snapshot dump failed
(00.035153) Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
(00.040430) Error (criu/sk-netlink.c:73): The socket has data to read
(00.040446) Error (criu/cr-dump.c:1352): Dump files (pid: 1396) failed with -1
(00.054570) Error (criu/cr-dump.c:1709): Dumping FAILED.
Try `lxc info --show-log c1` for more info

$ lxc info --show-log c1
Log:

            lxc 20180126020504.328 ERROR    lxc_criu - criu.c:do_dump:1134 - dump failed with 1
            lxc 20180126020504.328 ERROR    lxc_criu - criu.c:do_dump:1148 - criu output: Will skip in-flight TCP connections
</pre>

Manually killing dhclient still does the trick...

**Comment by avagin** [comment]
Could you show output for " ss -e -f netlink -a". This command should be executed in a container before and after lxc stop c1 --stateful

**Comment by iatrou** [comment]
Certainly, here it is:

<pre>
$ lxc launch ubuntu:x c1
Creating c1 
Starting c1 

$ lxc exec c1 -- ss -e -f netlink -a
State       Recv-Q Send-Q  Local Address:Port                Peer Address:Port       
UNCONN      0      0                rtnl:kernel                          *       sk=0 cb=0 groups=0x00000000
UNCONN      4352   0             tcpdiag:ss/443                          *       sk=0 cb=0 groups=0x00000000
UNCONN      768    0             tcpdiag:kernel                          *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0               audit:kernel                          *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0               audit:systemd/1                       *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0           fiblookup:kernel                          *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:systemd/1                       *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:kernel                          *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:-1988769276                     *       sk=0 cb=0 groups=0x00000001
UNCONN      0      0              uevent:-18727511                       *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:systemd-logind/326              *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1461960585                     *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-18727511                       *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1461960585                     *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:systemd-logind/326              *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1988769276                     *       sk=0 cb=0 groups=0x00000001
UNCONN      0      0                genl:kernel                          *       sk=0 cb=0 groups=0x00000000

$ lxc stop c1 --stateful
error: snapshot dump failed       
(00.039498) Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
(00.044578) Error (criu/sk-netlink.c:73): The socket has data to read    
(00.044593) Error (criu/cr-dump.c:1352): Dump files (pid: 3023) failed with -1   
(00.059174) Error (criu/cr-dump.c:1709): Dumping FAILED.                 
Try `lxc info --show-log c1` for more info

$ lxc exec c1 -- ss -e -f netlink -a
State       Recv-Q Send-Q  Local Address:Port               Peer Address:Port 
UNCONN      0      0                rtnl:kernel                         *       sk=0 cb=0 groups=0x00000000
UNCONN      768    0             tcpdiag:kernel                         *       sk=0 cb=0 groups=0x00000000
UNCONN      4352   0             tcpdiag:ss/444                         *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0               audit:kernel                         *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0               audit:systemd/1                      *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0           fiblookup:kernel                         *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:systemd/1                      *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:kernel                         *       sk=0 cb=0 groups=0x00000000
UNCONN      0      0              uevent:-1988769276                    *       sk=0 cb=0 groups=0x00000001
UNCONN      0      0              uevent:-18727511                      *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:systemd-logind/326             *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1461960585                    *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-18727511                      *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1461960585                    *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:systemd-logind/326             *       sk=0 cb=0 groups=0x00000002
UNCONN      0      0              uevent:-1988769276                    *       sk=0 cb=0 groups=0x00000001
UNCONN      0      0                genl:kernel                         *       sk=0 cb=0 groups=0x00000000
</pre>

**Comment by iatrou** [comment]
@avagin is the provided output what you were expecting? Anything more I can add?

**Comment by avagin** [comment]
I remember that we had some problems with audit sockets. Could you try to disable audit for this CT?

**Comment by avagin** [comment]
"lxc exec c1 -- ss -e -f netlink -a | grep audit" show show nothing

**Comment by avagin** [comment]
```
[  801.173871] audit: type=1400 audit(1536721328.602:38): apparmor="DENIED" operation="connect" namespace="root//lxd-c1_<var-lib-lxd>" profile="/sbin/dhclient" pid=2489 comm="dhclient" family="unix" sock_type="seqpacket" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@/crtools-pr-3477" peer="---"
```
