### ISSUE TITLE
Is CRIU integrated in OpenVZ?

### ISSUE THREAD

**Issue by phil294** [checkpoint-restore/criu#440]
I made this an issue because the documentation is highly confusing here and might need some adjustments.

- (+) https://criu.org/Integration and [virtuozzo](https://virtuozzo.com/live-migration-virtuozzo-7/) say that criu is part of virtuozzo 7. It also says the latest OpenVZ is "ready", with only "Older OpenVZ releases" using the old built-in CPT.
- (~) https://criu.org/OpenVZ says that OpenVZ "uses" criu.
It also says `not all features implemented` (opposite of "fully integrated").
- (-) https://openvz.org/Checkpointing_and_live_migration does not even talk of criu, even saying "Note: In *future* kernels, CPT is to be replaced by our sub-project CRIU"
- (+) https://criu.org/Comparison_to_other_CR_projects says that older versions didnt have it. "Legacy OpenVZ (RHEL4, RHEL5, RHEL6 based kernels) has in-kernel checkpoint/restore, sources can be found in kernel/cpt/." (https://src.openvz.org/projects/OVZL/repos/linux-2.6.16-openvz/browse/kernel/cpt)
And the newer versions do? Because there is no more cpt inside kernel source? https://src.openvz.org/projects/OVZ/repos/vzkernel/browse/kernel
- (-) https://openvz.org/CRIU/en says that criu is a "tool" one can "use" for checkpointing, not saying anything of integration. And, "This article is for Virtuozzo 7 only.", implying OpenVZ users can*not* "use" criu.
- https://criu.org/VNC talks of "creating an OpenVZ or LXC container with vzctl" and then checkpointing it, as if `criu dump --vzcontainer <CTID>` were an actual command.
- (+) https://openvz.org/Comparison says for "Live Migration" with OpenVZ 7: "Yes, CRIU for containers" (but not how)

So,
`vzctl chkpnt VEID --dump --dumpfile <path>`
Am I using criu here or not? If not, how can I checkpoint an OpenVZ  cointainer with criu like the VNC tutorial suggests?

Also, it is unclear why the download link for [OpenVZ](https://openvz.org/Quick_installation) talks of downloading [Virtuozzo](https://virtuozzo.com/products/virtuozzo/) which is obviously proprietary software. According to the comparison table, OpenVZ7 and Virtuozzo7 are two different things, yet installation guide treats them as one.
I am sure there are reasons for all of this. I have not even downloaded any of it. I simply wanted to share my experience with you people on how insanely confusing it is. Compare this to docker.
Sorry, the last part does not have anything to do with criu.

**Comment by 0x7f454c46** [comment]
`vzctl/prlctl suspend`, `vzctl/prlctl resume`, `prlctl migrate` - have fun with CRIU in vz.

**Comment by rst0git** [comment]
> Also, it is unclear why the download link for OpenVZ talks of downloading Virtuozzo which is obviously proprietary software. 

Perhaps this article could be useful https://virtuozzo.com/live-migration-virtuozzo-7/

**Comment by avagin** [comment]
CRIU is integrated in OpenVZ7 (based on rhel7).

There is some mess on openvz.org about Virtuozzo 7. OpenVZ 6 and older was a separate project with its own code base. OpenVZ7 is a part of Virtuozzo7 without some features (software-defined storage, HA, some optimizations). And we often call both projects as Virtuozzo 7.

**Comment by avagin** [comment]
Feel free to reopen this issue, if you have other questions.

**Comment by sergejbut** [comment]
Does OpenVZ support lazy migration?
If yes, can I enable/disable it?

**Comment by avagin** [comment]
> Does OpenVZ support lazy migration?

I am not sure about lazy migration, but it supports live-migration. If you use OpenVZ7, you should have the vzmigrate tool.

**Comment by Snorch** [comment]
@sergejbut, Hi.

Short answer: OpenVZ7/Virtuozzo7 supports live-migration, but not (yet) lazy-migration.

We plan to support lazy migration, but not sure if it would happen in near future. Currently we already have all the needed functionality for it and we even run zdtm tests to test basic lazy migration works. https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo-stable-lazy/job/vz7-u16/

But as you can see we have some intermittent fails with it:
```
*** Error in `../criu/criu': double free or corruption (!prev): 0x00000000019eb450 ***
```
Also I don't see lazy support in p.haul yet, so probably we would need to add it to p.haul first. @rst0git may correct me about it if I'm wrong.
