### ISSUE TITLE
ttyS0:  Can't dump file 0 of that type [20620] (chr 4:64)

### ISSUE THREAD

**Issue by 0x7f454c46** [checkpoint-restore/criu#441]
Just not to lose this issue:
```
[root@localhost criu]# ./criu/criu dump -t `pidof pypy` --shell-job
Warn  (criu/kerndat.c:805): Can't load /run/criu.kdat
Error (criu/uffd.c:231): uffd: Lazy pages are not available: Function not implemented
Error (criu/files-ext.c:96): Can't dump file 0 of that type [20620] (chr 4:64)
Error (criu/cr-dump.c:1439): Dump files (pid: 4131) failed with -1
Error (criu/cr-dump.c:1807): Dumping FAILED.
[root@localhost criu]# pidof pypy
4131
[root@localhost criu]# ls -lh /proc/4131/fd/
total 0
lrwx------. 1 root root 64 Jan 27 17:47 0 -> /dev/ttyS0
lrwx------. 1 root root 64 Jan 27 17:47 1 -> /dev/ttyS0
lrwx------. 1 root root 64 Jan 27 17:47 2 -> /dev/ttyS0
lrwx------. 1 root root 64 Jan 27 17:47 3 -> socket:[61481]
```
I think, will fix it myself, but anyway
Cc: @cyrillos

**Comment by cyrillos** [comment]
@0x7f454c46 thanks for report. Fix it please, Dima.

**Comment by l29ah** [comment]
I'm observing the same problem with a /dev/input node on criu-3.16.1:
```
Error (criu/files-ext.c:94): Can't dump file 3 of that type [20660] (chr 13:69)
```

**Comment by Snorch** [comment]
@l29ah, Hi.

In the original report, unsupported device was ttyS0(4:64), and criu/tty.c criu has their support implementation, so problem was likely some bug in tty support implementation.

In your case though you have virtual input device (13:69) https://www.kernel.org/doc/html/v4.12/input/uinput.html, which is a different problem. Criu AFAICS does not have any special code to support such devices, so it can be considered as unsupported.

Please fill separate issue about the lack of support of this device. Also you can try to c/r it by marking the problematic file "external" see this article for more info https://criu.org/Inheriting_FDs_on_restore, but that would only work if the creator of virtual device is outside of you dumped process tree. (Please post all the results in new issue)
