### ISSUE TITLE
CRIU error dumping failed 

### ISSUE THREAD

**Issue by ibrahimagha** [checkpoint-restore/criu#442]
hi guys,
I was trying to do live migration between 2 lxd hosts but I was not able to do it when I was launching Ubuntu 16 containers I switched to Ubuntu 14 containers and when it is an empty container I can do live migration after a try or two but when I am installing squid on it because I want it to work as a proxy for my back-end cloud the live migration gives me this error +1
sudo lxc move squid me:
error: Failed container creation:

https://192.168.2.233:8443: migration dump failed
(00.889609) Warn (criu/arch/x86/crtools.c:133): Will restore 8024 with interrupted system call
(00.900984) Warn (criu/arch/x86/crtools.c:133): Will restore 8025 with interrupted system call
(01.012850) Error (criu/sk-inet.c:106): Unsupported proto 1 for socket 11de2
(01.012860) Error (criu/cr-dump.c:1313): Dump files (pid: 13945) failed with -1
(01.072172) Error (criu/cr-dump.c:1628): Dumping FAILED.
https://192.168.56.1:8443: x509: certificate is valid for livetest-VirtualBox, not live-VirtualBox
any ideas ?
live migration works fine when it is a fresh container and nothing is installed on it,but after installing anything like Apache or squid it wont be able to do checkpoint and restore and always says socket has data to read, I am running the latest CRUI version

**Comment by adrianreber** [comment]
So, I just checked my squid VM and squid is opening a raw socket which CRIU, as far as I know, cannot handle. Can you configure squid to not use a raw socket and retry.

**Comment by ibrahimagha** [comment]
@adrianreber could you please tell me how to configure squid not to use raw socket ?

**Comment by adrianreber** [comment]
I actually do not know, but it seems to be the process called 'pinger' which can be disabled according to this: http://www.squid-cache.org/Doc/config/pinger_enable/

But I actually do not know much about configuring squid.

**Comment by ibrahimagha** [comment]
@adrianreber thank you for the help after disabling pinger the error changed as below :             
live@live-VirtualBox:~$ sudo lxc move squid me:
error: Failed container creation:
 - https://192.168.2.233:8443: migration restore failed
(00.040970) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming usr.lib.connman.scripts.dhclient-script.2 to :lxd-squid_<var-lib-lxd>:
(00.041014) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming usr.lib.NetworkManager.nm-dhcp-client.action.1 to :lxd-squid_<var-lib-lxd>:
(00.041017) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming sbin.dhclient.0 to :lxd-squid_<var-lib-lxd>:
(00.041035) Warn  (criu/apparmor.c:421): apparmor namespace /sys/kernel/security/apparmor/policy/namespaces/lxd-squid_<var-lib-lxd> already exists, restoring into it
(00.042249) Error (criu/apparmor.c:460): write AA policy failed: File exists
(00.042789) Error (criu/apparmor.c:479): failed to restore aa namespace, worker exited: 256
 - https://192.168.56.1:8443: x509: certificate is valid for livetest-VirtualBox, not live-VirtualBox

**Comment by ibrahimagha** [comment]
I also tried  sudo lxc exec squid /etc/init.d/apparmor teardown  even after tearing down still getting error
error: Failed container creation:
 - https://192.168.2.233:8443: migration dump failed
(00.616012) Warn  (criu/arch/x86/crtools.c:133): Will restore 15568 with interrupted system call
(00.889078) Warn  (criu/arch/x86/crtools.c:133): Will restore 15589 with interrupted system call
(00.959614) Warn  (criu/arch/x86/crtools.c:133): Will restore 15698 with interrupted system call
(00.959750) Warn  (criu/arch/x86/crtools.c:133): Will restore 15734 with interrupted system call
(00.963820) Warn  (criu/arch/x86/crtools.c:133): Will restore 15593 with interrupted system call
(01.110381) Warn  (criu/arch/x86/crtools.c:133): Will restore 15759 with interrupted system call
(01.111471) Warn  (criu/arch/x86/crtools.c:133): Will restore 15788 with interrupted system call
(01.180550) Warn  (criu/arch/x86/crtools.c:133): Will restore 15740 with interrupted system call
(01.276352) Warn  (criu/arch/x86/crtools.c:133): Will restore 15748 with interrupted system call
(01.276555) Warn  (criu/arch/x86/crtools.c:133): Will restore 15754 with interrupted system call
(02.285541) Error (criu/sk-inet.c:106): Unsupported proto 1 for socket 12de8
(02.285557) Error (criu/cr-dump.c:1313): Dump files (pid: 16786) failed with -1
(02.378774) Error (criu/cr-dump.c:1628): Dumping FAILED.
 - https://192.168.56.1:8443: x509: certificate is valid for livetest-VirtualBox, not live-VirtualBox

**Comment by adrianreber** [comment]
I have no experience with apparmor, and it is probably a bad idea to recommend the following,  but for debugging, maybe try to disable apparmor. At least try to run lxd without apparmor confinement to see if you can migrate your container.

**Comment by ibrahimagha** [comment]
@adrianreber even after disabling apparmor still having error saying write AA policy failed: PROTOCOL ERROR
I guess I need to open an other issue for that.
