### ISSUE TITLE
CRIU/apparmor error during container migration

### ISSUE THREAD

**Issue by ibrahimagha** [checkpoint-restore/criu#444]
hi guys,
I am trying to migreate containers between 2 lxd hosts, the container is hosting squid, but when I try to live migrate them it gives me this error
sudo lxc move squid me:
error: Failed container creation:
 - https://192.168.2.233:8443: migration restore failed
(00.038247) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming usr.lib.connman.scripts.dhclient-script.2 to 
(00.038278) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming usr.lib.NetworkManager.nm-dhcp-client.action.1 to 
(00.038281) Warn  (criu/apparmor.c:401): binary rewriting of apparmor policies not supported right now, not renaming sbin.dhclient.0 to 
(00.038300) Warn  (criu/apparmor.c:421): apparmor namespace /sys/kernel/security/apparmor/policy/namespaces/lxd-squid_<var-lib-lxd> already exists, restoring into it
(00.042309) Error (criu/apparmor.c:460): write AA policy failed: Protocol error
(00.042766) Error (criu/apparmor.c:479): failed to restore aa namespace, worker exited: 256
 - https://192.168.56.1:8443: x509: certificate is valid for livetest-VirtualBox, not live-VirtualBox

I tried to stop Apparmor in the container with those commands 
printf "mount fstype=nfs,\nmount fstype=nfs4," | lxc config set squid raw.apparmor -
lxc config set squid raw.lxc "lxc.aa_profile=unconfined"

but still shows the same error.
any ideas ?

**Comment by avagin** [comment]
Cc: @tych0

**Comment by avagin** [comment]
The upstream criu doesn't have criu/apparmor.c. I think Ubuntu applied this series: https://lists.openvz.org/pipermail/criu/2016-October/031854.html

**Comment by avagin** [comment]
@brauner, could you help us with this issue? Do you have non-upstream patches for criu?

**Comment by brauner** [comment]
@avagin, right afacit, @tych0 has those patches sitting in a tree somewhere. I'll take a closer look tomorrow.

**Comment by brauner** [comment]
So in order to support this properly we'd need @tych0's patches in CRIU but I don't know where he's hiding them. :)

**Comment by adrianreber** [comment]
Only one of the CRIU packages in Ubuntu comes with those patches;

https://packages.ubuntu.com/xenial-updates/criu

http://archive.ubuntu.com/ubuntu/pool/universe/c/criu/criu_2.6-1ubuntu1~ubuntu16.04.2.debian.tar.xz

For all newer Ubuntu releases CRIU comes without patches. It seems Ubuntu 17.10 and 18.04 will have an unpatched CRIU directly taken from Debian (according to the changelog).

**Comment by tych0** [comment]
https://github.com/tych0/criu/tree/apparmor-stacking-v4 maybe? Not sure.

**Comment by stgraber** [comment]
I believe @brauner is looking into this, at least we have some work on the LXD side to better handle CRIU apparmor namespaces.
