### ISSUE TITLE
CRIU 3.7 on Rasperry Pi 3: Can't dump

### ISSUE THREAD

**Issue by xaviermerino** [checkpoint-restore/criu#446]
Hello,

I have been trying to use CRIU to checkpoint the [Simple Loop](https://criu.org/Simple_loop) example in a Raspberry Pi 3 but the dump always fails. 

Here are the steps that I took to get to this point:

1. Recompile the Raspberry Pi kernel with the [features needed](https://criu.org/Linux_kernel) by CRIU. I followed the steps given by the RPi Foundation [here](https://www.raspberrypi.org/documentation/linux/kernel/building.md). 
2. Installed CRIU (version 3.7) from source. 
3. CRIU kernel check: `Looks good.` 
4. Run the [simple loop](https://criu.org/Simple_loop#Simplest_case) example dump.

The dump fails. Opening `dump.log` shows that: 
```
...
(00.021803) ========================================
(00.021824) Dumping task (pid: 4152)
(00.021843) ========================================
(00.021861) Obtaining task stat ... 
(00.022099) 
(00.022123) Collecting mappings (pid: 4152)
(00.022143) ----------------------------------------
(00.022833) Dumping path for -3 fd via self 8 [/bin/dash]
(00.023146) vma 35000 borrows vfi from previous 10000
(00.023240) vma 36000 borrows vfi from previous 35000
(00.023719) Dumping path for -3 fd via self 8 [/lib/arm-linux-gnueabihf/libc-2.24.so]
(00.024055) vma 76f04000 borrows vfi from previous 76dda000
(00.024134) vma 76f13000 borrows vfi from previous 76f04000
(00.024213) vma 76f15000 borrows vfi from previous 76f13000
(00.024468) Dumping path for -3 fd via self 8 [/usr/lib/arm-linux-gnueabihf/libarmmem.so]
(00.024575) vma 76f35000 borrows vfi from previous 76f30000
(00.024880) vma 76f44000 borrows vfi from previous 76f35000
(00.024961) vma 76f45000 borrows vfi from previous 76f44000
(00.025155) Dumping path for -3 fd via self 8 [/lib/arm-linux-gnueabihf/ld-2.24.so]
(00.025450) vma 76f77000 borrows vfi from previous 76f76000
(00.025793) Found VVAR area without support
(00.025842) Error (criu/cr-dump.c:1249): Collect mappings (pid: 4152) failed with -1
(00.026196) Unlock network
(00.026226) Unfreezing tasks into 1
(00.026248) 	Unseizing 4152 into 1
(00.026326) 	Unseizing 4452 into 1
(00.026365) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
I decided to check the output of `criu check --all`:
```
Warn  (criu/cr-check.c:680): Dirty tracking is OFF. Memory snapshot will not work.
Error (criu/cr-check.c:929): TCP_REPAIR can't be enabled for half-closed sockets
Warn  (criu/cr-check.c:1015): Loginuid restore is OFF.
Warn  (criu/cr-check.c:1061): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1037): UFFD is not supported
Error (criu/cr-check.c:1037): UFFD is not supported
Warn  (criu/cr-check.c:1029): CRIU built without CONFIG_COMPAT - can't C/R ia32
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```
After reading that I remembered the optional `CONFIG_MEM_SOFT_DIRTY=y` feature at the bottom of [CRIU's Linux kernel requirements](https://criu.org/Linux_kernel). When I was editing the kernel configuration via `menuconfig`, I figured I would just add that feature anyway, and attempted to set it to yes. It depended on `HAVE_ARCH_SOFT_DIRTY` which it was `=n` as defined at `arch/Kconfig:539` so in the end I could not enable it. 

What's causing the dump to fail? Is there something I can do about this? Also should I disable vDSO in case I get this to work?

Thanks

**Comment by rppt** [comment]
Please check if `CONFIG_PROC_PAGE_MONITOR` is enabled in your kernel configuration. It is required for getting information about dumpee memory layout.
ARM does not support soft-dirty feature therefore `HAVE_ARCH_SOFT_DIRTY=n` for Raspberry Pi.
As a side effect,  `CONFIG_MEM_SOFT_DIRTY=y` implicitly enables `CONFIG_PROC_PAGE_MONITOR` and it's possible it's missing from your kernel config.

**Comment by xaviermerino** [comment]
Oh alright. I checked and  `CONFIG_PROC_PAGE_MONITOR=y`. Do you know what else could be causing this? I am attaching the kernel config file.
[rpi_criu_config.txt](https://github.com/checkpoint-restore/criu/files/1761556/rpi_criu.txt)

**Comment by rppt** [comment]
Sorry, I've misread the dump log a bit.
The dump seems to fail because of VDSO. Can you try to disable `CONFIG_VDSO` in your kernel config and see if it helps?

cc @0x7f454c46

**Comment by 0x7f454c46** [comment]
Hey guys,

@rppt, thanks for Ccing,

Yes, there was somewhere instruction how-to CRIU on ARM32.. Not really sure, where it is now.
Anyway, for historical reasons, you need to disable CONFIG_VDSO in your kernel configuration to make it work. Unfortunately, ARM doesn't have a boot parameter like 'vdso=' on x86/sh/s390, so you need to recompile your kernel.

That's kinda hilarious because disabling CONFING_VDSO *never* made any sense for CRIU - the signal trampoline is actually placed on a [sigpage], not on the [vdso] page on ARM (which is not disabled with CONFIG_VDSO). But that stuff was made before me..

Anyway, I have in todo totally removing CONFIG_VDSO in CRIU, because for architectures we support having this config is kinda useless. Will move it upper in the list.

@xaviermerino, you may also want to use a kernel with [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=280e87e98c09b85b617c7b2752c8b504c4ea98f6), which is v4.13 and newer.

**Comment by xaviermerino** [comment]
@0x7f454c46 I set `CONFIG_VDSO=n` in the kernel. 
I attempted  `criu check --all` again. It complains and says: 
```
Warn  (criu/cr-check.c:680): Dirty tracking is OFF. Memory snapshot will not work.
Error (criu/cr-check.c:929): TCP_REPAIR can't be enabled for half-closed sockets
Warn  (criu/cr-check.c:1015): Loginuid restore is OFF.
Warn  (criu/cr-check.c:1061): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1037): UFFD is not supported
Error (criu/cr-check.c:1037): UFFD is not supported
Warn  (criu/cr-check.c:1029): CRIU built without CONFIG_COMPAT - can't C/R ia32
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```
This time however, I am able to dump the simple loop process and restore it. I am using the instructions for the shell job dump.  
```
pi@raspberrypi:~ $ sudo criu restore -vvvv -o restore.log --shell-job
Tue 27 Feb 21:09:56 UTC 2018
Tue 27 Feb 21:09:57 UTC 2018
Tue 27 Feb 21:09:58 UTC 2018
Tue 27 Feb 21:09:59 UTC 2018
Tue 27 Feb 21:10:00 UTC 2018
Tue 27 Feb 21:10:01 UTC 2018
Tue 27 Feb 21:10:02 UTC 2018
Tue 27 Feb 21:10:03 UTC 2018
Tue 27 Feb 21:10:04 UTC 2018
```
I am attaching the kernel config file with `CONFIG_VDSO=n` and all the added features for CRIU support [here](https://github.com/checkpoint-restore/criu/files/1764718/rpi_criu_no_vdso_config.txt).

I haven't tried using another kernel version. I have used the latest one provided by the Raspberry Pi foundation but maybe merging the CRIU submitted patches to that kernel will work. I am going to explore this route if time permits.

**Comment by 0x7f454c46** [comment]
@xaviermerino The complaints of `criu check --all` are OK.
They say, that you might miss some features, but C/R usually should work:
```
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```
I have in todo removing CONFIG_VDSO from criu, so it will work on ARM with vdso enabled..

**Comment by thesaadmemon** [comment]
Hello everyone,

I'm trying to compile the source code on Raspberry pi 4b+, 32-bit raspbian on Kernel 5.15.61-v7l+

I did recompile the kernel with CRIU-recommended configs enabled. 

Compilation Errors: 
Error (criu/sockets.c:209): sockets: Diag module missing (-2)
Error (criu/sockets.c:209): sockets: Diag module missing (-2)
Error (criu/sockets.c:209): sockets: Diag module missing (-2)
Error (criu/kerndat.c:508): Unexpected error from memfd_create("", MFD_HUGETLB): Function not implemented
Error (criu/kerndat.c:1577): kerndat_has_memfd_hugetlb failed when initializing kerndat.
Error (criu/crtools.c:260): Could not initialize kernel features detection.

Any help will be much appreciated

**Comment by rst0git** [comment]
> Error (criu/kerndat.c:508): Unexpected error from memfd_create("", MFD_HUGETLB): Function not implemented

This problem should be addressed in https://github.com/checkpoint-restore/criu/pull/1993.
