### ISSUE TITLE
Checkpoint/restore multiple processes simultaneously?

### ISSUE THREAD

**Issue by dav-ell** [checkpoint-restore/criu#448]
Is there a standard way of checkpointing and restoring two or more connected containers without interrupting their network connection? I've tried a couple ways and am having no luck.

First attempt:
1. Spawn two containers from a script by forking and execing, so that the script becomes an ancestor of both containers, and the containers are descendants of the script process in the process tree. Connect them.
2. Checkpoint the script's process.

This fails because CRIU requires all processes to be in the same PID namespace (as well as IPC and UTS namespaces, I later found out), and each container runs in a namespace of its own.

Second attempt:
1. Start two containers separately and connect them.
2. Checkpoint using a script that calls checkpoint on both of the containers in parallel.
3. Restore in parallel also.
4. Hope it works.

This checkpointed and restored each container without a problem, but naturally lost the connection when it restored. I assume it's because the containers didn't freeze/restore at exactly the same time, so there was time for one of the containers to realize the other was gone and the connection was broken.

Is there a preferred way to do this?

**Comment by avagin** [comment]
@dav-ell Could you give more details about the second case? How do you checkpoint and restore containers? Who gives ip addresses to containers? Are containers restored with the same ip addresses? Could you collect tcpdump for inter-container connections?

**Comment by dav-ell** [comment]
@avagin I run, checkpoint, and restore using runc 1.0.0-rc4+dev. CRIU version 3.7.  The second case, in more detail, is:

Container `a` is a server. Container `b` is a client. Both `a` and `b` have network namespaces disabled, so their IP address is the same as that of the host. After starting both with `sudo runc run`, `b` connects to `a` over a socket.

Imagine something like this for checkpoint:
```
# in parallel
runc checkpoint a ... --tcp-established
runc checkpoint b ... --tcp-established
```

Then on the restore:
```
# in parallel
runc restore a ... --tcp-established
runc restore b ... --tcp-established
```

Containers are restored without network namespaces also, so they have the same IP address as when they started.

The TCP dump of them running, checkpointed, and restored is also attached.

[tcpdump.log](https://github.com/checkpoint-restore/criu/files/1802720/tcpdump.log)

**Comment by adrianreber** [comment]
Looking at your tcpdump log there is 20 minutes between the checkpoint and the restore. This is too long for established connection being kept alive.

Not knowing  much about your containers I see an ACK at 15:52:16.398779 which seems to be the first packet after the restore. This ACK is answered by a RST because if an ACK comes 20 minutes too late  TCP connection are usually aborted (or the receiving side already closed the socket, not sure if that can be seen from the log). At least that is my interpretation.

Have you tried restoring immediately after checkpointing?

**Comment by dav-ell** [comment]
I tried restoring immediately after checkpointing and it worked. Here's another log, with the checkpoint and restore happening around 09:32:02 and 09:32:16, respectively.

[tcpdump.log](https://github.com/checkpoint-restore/criu/files/1802942/tcpdump.log)

So now I'm wondering... the difference between the checkpoint and restore is roughly 14 seconds. Is it working based on the fact that the timeout hasn't expired according to the system, or according to the length of time its been pinging the other side while it was disconnected?

Here's an example (which I'll test soon):
* `a` and `b` are running from time `t=0` with a socket timeout of 30 seconds.
* `b` is checkpointed at `t=5`
* `a` is checkpointed at `t=10`
* `a` is restored at `t=50`
* `b` is restored at `t=55`

Does the connection between `a` and `b` still work? Have they been disconnected for 50 seconds (`b` disconnects from`a` at `t=5` and only reconnects at `t=55`), or have they been disconnected for 10 seconds (`a` is pinging `b` for 5 seconds before it's checkpointed itself, then 5 seconds after it's restored)?

**Comment by adrianreber** [comment]
I do not really know, but I hope someone will correct me if I am wrong. But assuming that CRIU re-creates the sockets just as they were during checkpoint I would expect the timestamps to bet set to the same value they were during checkpoint which would mean they have been disconnected, in your example, for 50 seconds.

**Comment by dav-ell** [comment]
Thanks for the help so far, @adrianreber. It looks like you're right. I tested this with a longer delay between checkpoint and restore, ~1 min, and it timed out. The checkpoint/restore happens around 10:23:00 and 10:24:00.

[tcpdump.log](https://github.com/checkpoint-restore/criu/files/1803136/tcpdump.log)

So it seems like what you said is correct. If that's actually how it works, though, and CRIU just sets the socket timestamps to be the same as when they were checkpointed, wouldn't it be possible for CRIU to either set the timestamps to the current system time on restore, or provide a flag to do that, to then allow any set of connected containers to be checkpointed and restored, mainting connections, with an arbitrary period of time between the operation? The only restriction would be the amount of time the containers spend pinging each other, like the second case I described in my earlier comment. 

It seems like that might not require a whole lot of work, and provide a lot of new opportunities for CRIU as well.

**Comment by adrianreber** [comment]
For cases where both ends of the connection are checkpointed it sounds reasonable, not sure if it can be implemented. No idea what those timestamps are used for in addition in the network stack.

You could try to decode the network related dump files using crit (decode) and maybe even change the timestamps manually and create new dump files with crit (encode).

**Comment by dav-ell** [comment]
@adrianreber That's an awesome idea. Any clue which .img file to edit?

**Comment by adrianreber** [comment]
The TCP connections are in files.img.

**Comment by dav-ell** [comment]
This issue is solved, since I have indeed been able to checkpoint and restore with TCP connections still alive, and checkpointing simultaneously wasn't even required as long as the checkpoint/restore happened within the limits of the TCP timeout.

I'll close this issue and make another for further questions.
