### ISSUE TITLE
How to integrate criu pre-dump feature  with docker for Iterative Migration?

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#456]
Hi , in order to move container from h1 to h2, i used docker checkpoint command to freeze the container on source, copied its image files to destination and started the container with checkpoint image files. My question is that if we want to implement iterative migration using pre-dump option, is there some docker command i need to use or criu command because in earlier case, i didn't executed any criu commands but only docker commands were enough to migrate container from source to destination. Thanks

**Comment by adrianreber** [comment]
As far as I am aware there is no support for pre-copy (or post-copy) migration on the docker level. It is only available on the lower runc level. Either you can just use runc to control your containers or add the pre-copy support from runc also to docker.

**Comment by farooqte96** [comment]
Hi Thanks for an instant reply. I am checking your suggestion but can you give me some starting point to integrate runc pre-copy functionlity with docker. Is there some already implementation available? Otherwise  i would be left with only runc containers option to test container migration. Thanks

**Comment by rst0git** [comment]
Hi @farooqte96 if want to only test container migration then use [lxc](https://github.com/lxc/lxc) or [lxd](https://github.com/lxc/lxc). 
Recently @adrianreber added support for pre-copy [optimisation recently](https://github.com/lxc/lxd/pull/4072).  You can find more information [here](https://lisas.de/~adrian/?p=1294) .

**Comment by adrianreber** [comment]
I do not know of any existing work related to docker and pre-copy migration. I know that LXD supports pre-copy migration and I have done pre-copy container migration with runc like described here: https://rhelblog.redhat.com/2017/10/12/container-migration-around-the-world/

**Comment by farooqte96** [comment]
Thanks @adrianreber and @rst0git  for your assistance. I will check this for lxd and will get back if i have any issues with that. But one more thing to ask,  does lxd/runc work also the same for Ubuntu 16 because i am not using Red Hat Linux? Thanks

**Comment by rst0git** [comment]
@farooqte96 yes LXD is maintained by Canonical and it has very good support for Ubuntu (see https://linuxcontainers.org/lxd/getting-started-cli/#ubuntu-1604-lts)
