### ISSUE TITLE
Changing TCP connection sometimes causes "Error (criu/files.c:799): No file for fd 5 id 0x3c"

### ISSUE THREAD

**Issue by dav-ell** [checkpoint-restore/criu#459]
As in #454, I'm changing TCP connection information. I now have two connections: one between client A and a server S, one between client B and server S. I'm trying to swap client A and B while maintaining both of their connections to the server. I checkpoint all three hosts at the same time and restore them at the same time, as before.

This error shows up most times, but not all times. And sometimes if I wait long enough I can restore successfully, but TCP connections aren't kept. Here's the relevant restore log.

```
(00.234833)      1: vma 0x7ffdb88a4000 0x7ffdb88c5000
(00.234841)      1: vma 0x7ffdb898b000 0x7ffdb898e000
(00.234849)      1: vma 0x7ffdb898e000 0x7ffdb8990000
(00.234858)      1: vma 0xffffffffff600000 0xffffffffff601000
(00.234894)      1: Collect fdinfo pid=1 fd=0 id=0x37
(00.234906)      1: Collect fdinfo pid=1 fd=1 id=0x38
(00.234914)      1: Collect fdinfo pid=1 fd=2 id=0x39
(00.234922)      1: Collect fdinfo pid=1 fd=3 id=0x3a
(00.234932)      1: Collect fdinfo pid=1 fd=4 id=0x3b
(00.234951)      1: Collect fdinfo pid=1 fd=5 id=0x3c
(00.234961)      1: Error (criu/files.c:799): No file for fd 5 id 0x3c
(00.334935) mnt: Switching to new ns to clean ghosts
(00.351664) Error (criu/cr-restore.c:2174): Restoring FAILED.
```

[restore.log](https://github.com/checkpoint-restore/criu/files/1838808/restore.log)

This github issue isn't for the TCP connections failing to restore, I think I might know the reason for that. This issue is mostly just for fixing this strange error.

**Comment by dav-ell** [comment]
Is this maybe because the file descriptor for that socket was already in use from the previous client's connection? Could something like this help? 

https://github.com/checkpoint-restore/criu/blob/c21e09cfe2f226cd14058ef5c4b0cbf7421293d2/Documentation/criu.txt#L333

**Comment by dav-ell** [comment]
I also sometimes get `Unable to open fd=5 id=0x3c`:

```
(00.252262)      1: Restoring TCP connection
(00.252271)      1: Restoring TCP connection id 3c ino 4e1cda
(00.252328)      1: Error (criu/files.c:1202): Unable to open fd=5 id=0x3c
(00.377181) mnt: Switching to new ns to clean ghosts
(00.395327) Error (criu/cr-restore.c:2174): Restoring FAILED.
```

**Comment by avagin** [comment]
Could you reproduce the issue and attach dump.log, restore.log and images?

**Comment by dav-ell** [comment]
Here are the files, reproduced with a similar error (`Error (criu/files.c:1202): Unable to open fd=68 id=0x59`) by attempting to switch two containers, a client and a server, between two hosts in different networks. These are the files for the server.

[dump.log](https://github.com/checkpoint-restore/criu/files/1853818/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/1853820/restore.log)
[images.tar.gz](https://github.com/checkpoint-restore/criu/files/1853823/images.tar.gz)

**Comment by dav-ell** [comment]
CRIU version 3.7 on both the client and server side.

**Comment by dav-ell** [comment]
@avagin This appeared while working on #461, when I tried keeping only the INPUT iptables rules. It seemed reasonable that as long as both client and server had INPUT rules configured to drop packets that might interfere with their restore, then it'd be okay. It looks like maybe the OUTPUT rules are somehow important to the restore process for CRIU?

**Comment by dav-ell** [comment]
Several recent tests seem to indicate that in my system this issue is very closely associated with either iptables rules being incorrect, or tcp connection information in `files.img` being incorrect. As long as both of these are correctly maintained, this issue does not appear. If anyone finds something different, feel free to comment on this issue or reference it.

**Comment by dav-ell** [comment]
I encountered this issue again, unfortunately. It happened when I attempted to restore very quickly after checkpointing. iptables rules and files.img information was correct. After waiting a while (maybe 30 minutes, I didn't measure), it worked again. Is there some way to force whatever fd is occupied to be freed after checkpointing?

**Comment by avagin** [comment]
Pls, attach logs and images. criu should be executed with "-v 4".

**Comment by dav-ell** [comment]
@avagin Here the logs, executed _without_ `-v 4`. I'm using `runc checkpoint` and `runc restore`, do you know how to run with an equivalent of `-v 4`?

[dump.log](https://github.com/checkpoint-restore/criu/files/1880266/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/1880267/restore.log)

**Comment by adrianreber** [comment]
runc always sets log level to 4, so the log should be correct.

**Comment by avagin** [comment]
```
            "isk": {
                "id": 89,
                "ino": 34587922,
                "family": "INET6",
                "type": "STREAM",
                "proto": "TCP",
                "state": "ESTABLISHED",
                "src_port": 5672,
                "dst_port": 42692,
                "flags": "0x802",
                "backlog": 0,
                "src_addr": [
                    "::ffff:a00:6"
                ],
                "dst_addr": [
                    "::ffff:a477:ccae"
                ],
                "fown": {
                    "uid": 0,
                    "euid": 0,
                    "signum": 0,
                    "pid_type": 0,
                    "pid": 0
                },
                "opts": {
                    "so_sndbuf": 87040,
                    "so_rcvbuf": 374400,
                    "so_snd_tmo_sec": 0,
                    "so_snd_tmo_usec": 0,
                    "so_rcv_tmo_sec": 0,
                    "so_rcv_tmo_usec": 0,
                    "reuseaddr": true,
                    "so_priority": 0,
                    "so_rcvlowat": 1,
                    "so_mark": 0,
                    "so_passcred": false,
                    "so_passsec": false,
                    "so_dontroute": false,
                    "so_no_check": false,
                    "so_reuseport": false
                },
                "v6only": false,
                "ip_opts": {}
            }
        },
```

```
{
    "magic": "TCP_STREAM",
    "entries": [
        {
            "inq_len": 0,
            "inq_seq": 1670888816,
            "outq_len": 0,
            "outq_seq": 1609446165,
            "opt_mask": "0x7",
            "snd_wscale": 7,
            "mss_clamp": 1460,
            "rcv_wscale": 7,
            "timestamp": 47581819,
            "nodelay": true,
            "unsq_len": 0,
            "snd_wl1": 1670888816,
            "snd_wnd": 30336,
            "max_window": 30336,
            "rcv_wnd": 30080,
            "rcv_wup": 1670888816,
            "extra": {
                "outq": "",
                "inq": ""
            }
        }
    ]
}
```

**Comment by avagin** [comment]
I don't see debug messages from the soccr library. Are you sure that you use criu 3.7?

**Comment by dav-ell** [comment]
I checked and it gives:
```
$ sudo criu --version
Version: 3.7
```

I installed CRIU using:
```
wget http://download.openvz.org/criu/criu-3.7.tar.bz2 \
&& sudo tar -xvjf criu-3.7.tar.bz2 \
&& cd criu-3.7/ \
&& sudo make \
&& sudo make install
```

**Comment by 0x7f454c46** [comment]
Are you sure that runc calls your new criu?
I don't see the version string in log, which should be there from some recent times.

**Comment by avagin** [comment]
> I don't see the version string in log, which should be there from some recent times.

runc runs criu swrk, it may be a reason why we don't see a version.

**Comment by 0x7f454c46** [comment]
Oh, yeah, stupid me - forgot that in swrk version string is added only in criu-dev.
Sorry for the noise.

**Comment by avagin** [comment]
With this commit https://github.com/avagin/criu/commit/49760d1559ac0da48455f0baaa934e6d65594c35 we will see soccr log messages in a criu log file.

@dav-ell Could you compile criu from my repo and reproduce this issue again?
```
$ git clone https://github.com/avagin/criu -b log
$ cd criu
$ make
$ make install
```

**Comment by dav-ell** [comment]
@avagin I got to try out your commit today, but runc ran into a version problem restoring.

```
$ sudo runc restore ...
CRIU version 10300 must be 10502 or higher
```

My versions:
```
$ sudo runc --version
runc version 1.0.0-rc4
spec: 1.0.0
```

```
$ sudo criu --version
Version: 3.7
GitID: v1.2-4950-g49760d1
```

**Comment by adrianreber** [comment]
@dav-ell Are you sure runc is using the new CRIU version. What happens if you run:

```runc --debug --log /dev/stdout restore ...```

Maybe you need to tell runc with ```--criu /path/to/criu``` where CRIU is.

**Comment by dav-ell** [comment]
@avagin I get the same thing:

```
$ sudo runc --debug --log /dev/stdout --criu ~/soccr/criu/criu restore [] --bundle [] --image-path [] --work-path [] --tcp-established
ERRO[0000] CRIU version 10300 must be 10502 or higher
  
CRIU version 10300 must be 10502 or higher
```
I pulled your commit in the `soccr` folder of my home directory.

**Comment by dav-ell** [comment]
I copied your changes from that particular commit into my regular CRIU, rebuilt, and got the new log.

[restore-soccr.log](https://github.com/checkpoint-restore/criu/files/1947534/restore-soccr.log)

**Comment by dav-ell** [comment]
Note that it also appears that you can solve this issue by leaving `src_addr` the same and setting a secondary IP address on the host via:

```
sudo ip address add 192.168.1.xxx/32 dev eth0
```
