### ISSUE TITLE
Container is not stopping, CentOS 7.4

### ISSUE THREAD

**Issue by drgardner42** [checkpoint-restore/criu#463]
I am attempting to do the hello-world busybox example of docker checkpoint/restore with CRIU (https://criu.org/Docker).

My environment:

* CentOS 7.4
* Linux Kernel 4.15.13-1
* Docker version 17.12.1-ce
* CRIU 2.2

Here is the output from criu check --all:

    Warn (criu/cr-checl.c:705): Dirty tracking is OFF. Memory snapshot will not work.

____________

when I try to checkpoint the busybox, I get no failure output, and container does not stop. Is there somewhere I can go for additional information?

**Comment by adrianreber** [comment]
The kernel version does not sound like CentOS. Which CRIU version are you using?

The CRIU version in CentOS is for the original CentOS kernel and might not work if you replace the kernel.

The CRIU warning you are seeing is harmless as docker does not support pre-copy migration.

As this seems to be a docker problem, maybe it would make more sense to first open a docker ticket and if it is actually a CRIU error come back here?

**Comment by 0x7f454c46** [comment]
You can also put dump.log into issue.
I'm not sure how-to find one the Docker uses, heh

**Comment by drgardner42** [comment]
@adrianreber I am running a custom CentOS kernel. Saw lots of issues on the CRIU site about upgrading kernel to properly support CRIU, so went ahead and did the upgrade. I'll try a downgrade back to the CentOS 3.10 kernel and try the busybox.

**Comment by adrianreber** [comment]
@drgardner42 The CentOS kernel should support most of CRIU's feature.

**Comment by drgardner42** [comment]
Ok, I will get back shortly. Trying the 3.10 kernel now with CRIU 2.2.

**Comment by adrianreber** [comment]
CentOS 7.4 comes with criu 2.12.

**Comment by drgardner42** [comment]
Still not seeing the container correctly exit after checkpoint :(

> $ criu --version
> Version: 2.12
> 
> $ uname -r
> 3.10.0-514.el7.x86_64
> 
> $ docker --version
> Docker version 17.12.1-ce, build 7390fc6
> 
> $ sudo criu check --all
> Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
> Error (criu/cr-check.c:648): Kernel doesn't support PTRACE_O_SUSPEND_SECCOMP
> Error (criu/cr-check.c:692): Dumping seccomp filters not supported: Input/output error
> Error (criu/cr-check.c:919): cgroupns not supported. This is not fatal.
> Error (criu/cr-check.c:1021): The TCP_REPAIR_WINDOW option isn't supported.
> Error (criu/cr-check.c:965): TCP_REPAIR can't be enabled for half-closed sockets
> Error (criu/cr-check.c:852): autofs not supported.
> Looks good but some kernel features are missing
> which, depending on your process tree, may cause
> dump or restore failure.
> 
> $ docker run -d --security-opt seccomp:unconfined <image> /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 5; done'
> 
> $ docker ps
> CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS               NAMES
> 68b1df5a5c22        <image>                                   "/bin/sh -c 'i=0; wh…"   4 seconds ago      Up 2 seconds                           youthful_wiles
> 
> $ sudo docker checkpoint create youthful_wiles checkpoint1
> 
> $ docker ps
> CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS               NAMES
> 68b1df5a5c22        <image>                                   "/bin/sh -c 'i=0; wh…"   36 seconds ago      Up 35 seconds                           youthful_wiles

**Comment by drgardner42** [comment]
https://github.com/moby/moby/issues/35691
