### ISSUE TITLE
uns: send req error: Invalid argument

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#466]
Hello,
When I am restoring a libvirt-lxc container with enabled user namespace I am getting the following error:
```
(00.044416) Running setup-namespaces scripts
(00.044487)      1: cg: Move into 2
(00.044547)      1: cg:   `-> blkio//machine.slice/machine-lxc\x2d14659\x2dcontainer1.scope/tasks
(00.044557)      1: uns: calling userns_move (-1, 0)
(00.044648)      1: Error (criu/namespaces.c:1341): uns: send req error: Invalid argument
(00.044664)      1: Error (criu/cgroup.c:1119): cg: Can't move into blkio//machine.slice/machine-lxc\x2d14659\x2dcontainer1.scope/tasks (-1/-1): Invalid argument
(00.074163) Error (criu/mount.c:3210): mnt: Can't remove the directory /tmp/.criu.mntns.JvLvMx: No such file or directory
(00.074173) uns: calling exit_usernsd (-1, 1)
(00.074220) uns: daemon calls 0x45edc0 (14719, -1, 1)
(00.074243) uns: `- daemon exits w/ 0
(00.074807) uns: daemon stopped
(00.074815) Error (criu/cr-restore.c:2252): Restoring FAILED.
```

Any idea why [`sendmsg`](https://github.com/checkpoint-restore/criu/blob/3b3384352dd355407edd97a9d529b9bb27db87a7/criu/namespaces.c#L1290-L1293) might fail with `EINVAL`?

[dump.log](https://github.com/checkpoint-restore/criu/files/1878703/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/1878704/restore.log)
Note: If I disable the userns (don't use idmap) the restore is successful.

**Comment by avagin** [comment]
https://github.com/torvalds/linux/blob/master/block/blk-cgroup.c#L1202

**Comment by avagin** [comment]
could you collect strace for restore?
```
strace -s 256 -fo strace.log criu restore -v 4 ...
```

**Comment by rst0git** [comment]
Hi @avagin 
When I run 
```
strace -s 256 -fo strace.log /usr/sbin/criu restore \
--pidfile pidfile \
--tcp-established \
--file-locks \
--link-remap \
--manage-cgroups=full \
--ext-mount-map auto \
--enable-external-sharing \
--enable-external-masters \
--enable-fs hugetlbfs \
--enable-fs tracefs \
--images-dir /tmp/dump \
--log-file restore.log \
-v5 \
--ext-mount-map fuse:/proc/meminfo \
--ext-mount-map console:/dev/console \
--ext-mount-map tty1:/dev/tty1 \
--restore-detached \
--restore-sibling \
--inherit-fd fd[0]:tty[8800:2d] \
--root /home/rst/tmp/fedora-map
```
I am getting a different error
```
Error (criu/cr-restore.c:2055): Can't attach to init: Operation not permitted
```
[strace.log](https://github.com/checkpoint-restore/criu/files/1879158/strace.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/1879160/restore.log)

**Comment by rst0git** [comment]
Hm, the  `sendmsg` issue does not occur with `criu-dev`.

**Comment by avagin** [comment]
It is due to --restore-sibling. Could you remove --restore-sibling to collect strace?

**Comment by rst0git** [comment]
@avagin thanks, this the [strace.log](https://github.com/checkpoint-restore/criu/files/1880890/strace.log) from the above command without `--restore-sibling`.

**Comment by avagin** [comment]
2489  sendmsg(1048568, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\3601C\0\0\0\0\0", iov_len=8}, {iov_base="\0\0\0\0", iov_len=4}, {iov_base="blkio//machine.slice/machine-lxc\\x2d2421\\x2dcontainer1.scope/tasks\0", iov_len=67}], msg_iovlen=3, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=1, uid=65534, gid=65534}}], msg_controllen=32, msg_flags=0}, 0) = -1 EINVAL (Invalid argument)

**Comment by rst0git** [comment]
[](Yes, this error does not occur with criu from the `criu-dev` branch.
However, the restore still fails with ([restore.log](https://github.com/checkpoint-restore/criu/files/1879650/restore.log))
```
Error (criu/cr-restore.c:1729): mkdtemp failed crtools-proc.f8bPMJ: Permission denied
```
I have tried to get around this with 
```
--- a/criu/cr-restore.c
+++ b/criu/cr-restore.c
@@ -1720,7 +1720,10 @@ static void restore_pgid(void)
 static int mount_proc(void)
 {
        int fd, ret;
-       char proc_mountpoint[] = "crtools-proc.XXXXXX";
+       char proc_mountpoint[PATH_MAX];
+       char *root = opts.root ? : "/";
+       snprintf(proc_mountpoint, sizeof(proc_mountpoint),
+                "%s/crtools-proc.XXXXXX", root);
 
        if (root_ns_mask == 0)
                fd = ret = open("/proc", O_DIRECTORY);
```
Then am getting the following error ([restore1.log](https://github.com/checkpoint-restore/criu/files/1881285/restore1.log))
```
Fatal: can't open lock file /run/xtables.lock: Permission denied
```

**Comment by avagin** [comment]
https://github.com/avagin/criu/commits/cgroup contains three commits for the master branch, which have to solve the initial problem.

**Comment by avagin** [comment]
> Fatal: can't open lock file /run/xtables.lock: Permission denied
As a workaround, you can revert b2707bab02459678cd2b354d39cbdfd182968ee4

**Comment by rst0git** [comment]
The problem was that `ls -al /run/xtables.lock`
```
-rw------- 1 root root 0 Apr  5 10:47 /run/xtables.lock
```
I changed it with `sudo chmod 666 /run/xtables.lock`.
Now the restore failed with: ([restore2.log](https://github.com/checkpoint-restore/criu/files/1881427/restore2.log))

```
Error (criu/mount.c:2274): mnt: Can't mount at /tmp/.criu.mntns.kX9ZSY/9-0000000000/proc/meminfo: Operation not permitted
```

**Comment by rst0git** [comment]
@avagin thanks, I can confirm that the three commits in https://github.com/avagin/criu/commits/cgroup solve the initial problem.

**Comment by rst0git** [comment]
With strace the above error appears as
```
mount("/proc/meminfo", "/tmp/.criu.mntns.mb0xnU/9-0000000000/proc/meminfo", NULL, MS_BIND, NULL) = 0
mount(NULL, "/tmp/.criu.mntns.mb0xnU/9-0000000000/proc/meminfo", NULL, MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND|MS_RELATIME, NULL) = -1 EPERM (Operation not permitted)
```
I tested the same mount calls in bash 
```bash
$ sudo unshare -muinpUCrf bash
[root]# touch /tmp/test
[root]# mount -o bind /proc/meminfo /tmp/test
[root]# mount -o nosuid,nodev,remount,bind,relatime /proc/meminfo /tmp/test
mount: /tmp/test: mount point is not a directory.
[root]# umount /tmp/test
[root]# rm -f /tmp/test
```
And indeed `/proc/meminfo` is not a directory. For work around I tried
```diff
diff --git a/criu/mount.c b/criu/mount.c
index 47c65d51..ea882a93 100644
--- a/criu/mount.c
+++ b/criu/mount.c
@@ -2269,7 +2269,7 @@ do_bind:
        }
 
        mflags = mi->flags & (~MS_PROPAGATE);
-       if (!mi->bind || mflags != (mi->bind->flags & (~MS_PROPAGATE)))
+       if (S_ISDIR(st.st_mode) && (!mi->bind || mflags != (mi->bind->flags & (~MS_PROPAGATE))))
                if (mount(NULL, mi->mountpoint, NULL, MS_BIND | MS_REMOUNT | mflags, NULL)) {
                        pr_perror("Can't mount at %s", mi->mountpoint);
                        goto err;

```

**Comment by rst0git** [comment]
Now the restore fails with ([restore3.log](https://github.com/checkpoint-restore/criu/files/1883439/restore3.log))
```
tar: ./tty: Cannot mknod: Operation not permitted
tar: ./urandom: Cannot mknod: Operation not permitted
tar: ./random: Cannot mknod: Operation not permitted
tar: ./full: Cannot mknod: Operation not permitted
tar: ./zero: Cannot mknod: Operation not permitted
tar: ./null: Cannot mknod: Operation not permitted
tar: Exiting with failure status due to previous errors
(00.335757)      1: Error (criu/util.c:841): exited, status=2
```

**Comment by avagin** [comment]
How do you create /dev/tty, /dev/zero, etc files for containers?

**Comment by avagin** [comment]
@rst0git I think /dev/ should be an external mount in your case.

**Comment by rst0git** [comment]
>How do you create /dev/tty, /dev/zero, etc files for containers?

Prior container start, Libvirt creates a tmpfs and [populates character special files](https://github.com/libvirt/libvirt/blob/d4aaa1651bf45a6d0b5c3a889ad170e9e8ee66bf/src/lxc/lxc_controller.c#L1494-L1527) (`tty`, `urandom`, `random`, `full`, `null`, and `zero`). These files are chown()-ed to match the idmap configuration of the container.

I was wondering if it would be possible to call [`tar`](https://github.com/checkpoint-restore/criu/blob/b364f4fd52be125ddc6690452bec3336d77ad102/criu/filesystems.c#L451-L454) on restore with `cr_system_userns` instead of `cr_system` (similar to commit [8fd50f3](https://github.com/checkpoint-restore/criu/commit/8fd50f35b94b66f9378f7829e2a5d93e0d436440))?

In such case the tar flags `--preserve-permissions` and `--same-permissions` will ensure that extracted files will have correct permissions and ownership.

**Comment by avagin** [comment]
tar has --group-map and --user-map options, they can be useful for us here
