### ISSUE TITLE
sys/kernel/ns_last_pid sysctl is inaccessible

### ISSUE THREAD

**Issue by nlienard** [checkpoint-restore/criu#468]
Trying to use LXD and Live migration which is based on CRIU.

Version:

```
root@atxscw-hy005:~# uname -a
Linux atxscw-hy005 4.4.122-mainline-rev1 #1 SMP Sun Mar 18 10:44:19 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@atxscw-hy005:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
root@atxscw-hy005:~# dpkg -l |grep criu
ii  criu                           2.6-1ubuntu1~ubuntu16.04.2            amd64        checkpoint and restore in userspace
root@atxscw-hy005:~# uname -a
Linux atxscw-hy005 4.4.122-mainline-rev1 #1 SMP Sun Mar 18 10:44:19 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

when checking criu status:

```
root@atxscw-hy005:/var/log# criu check --all
Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
Error (criu/cr-check.c:141): sys/kernel/ns_last_pid sysctl is inaccessible: No such file or directory
Does not look good.
```

What could be the issue ? (the server is a VPS SCALEWAY VC1L).

**Comment by adrianreber** [comment]
This looks like a kernel without CONFIG_CHECKPOINT_RESTORE. Is there a kernel config file installed in /boot for that version. It could be that your provider replaced the default Ubuntu kernel with their own kernel without CONFIG_CHECKPOINT_RESTORE.

**Comment by brauner** [comment]
Yeah, the VPS might not have c/r support.

**Comment by nlienard** [comment]
I don't have /boot but i installed the kernel source for adding spl/zfs following https://github.com/scaleway/kernel-tools

root@atxscw-hy006:/usr/src/linux# pwd -P
/usr/src/linux-4.4.122
root@atxscw-hy006:/usr/src/linux# grep CONFIG_CHECKPOINT_RESTORE. .config
# CONFIG_CHECKPOINT_RESTORE is not set

**Comment by adrianreber** [comment]
This kernel does not support CRIU. You need another kernel with CONFIG_CHECKPOINT_RESTORE enabled.
