### ISSUE TITLE
UB in choose_service_fd_base, causing restore failures

### ISSUE THREAD

**Issue by rburny** [checkpoint-restore/criu#470]
In `choose_service_fd_base` method, CRIU uses the following logic (simplified) to determine where to map service fds:

```cpp
nr = max(nr, inh_fd_max);
nr += (SERVICE_FD_MAX - SERVICE_FD_MIN) * fdt_nr;
nr += 16; /* Safety pad */
// (1)
nr /= (1024 / sizeof(void *));
nr = 1 << (32 - __builtin_clz(nr));
nr *= (1024 / sizeof(void *));
```

If the checkpointed process was using a small number of fds, it is possible that at point `(1)`, `nr` is less then 128. In this case, it subsequently becomes 0, and `__builtin_clz(0)` is invoked - which per [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) is undefined behavior.
In practice, this sometimes causes  `choose_service_fd_base` to return 0 (which looks impossible from the code reading, but I guess anything can happen due to undefined behavior). That breaks all service fds, including logging ones, so we get restore failure without any error logs after this point.

I see two ways to fix it:
* add `nr = max(nr, 1)` before invoking `__builtin_clz`
* remove the last 3 lines - they don't seem to serve any purpose other than to make `nr` a round number

What do you think?

**Comment by avagin** [comment]
Cc: @tkhai

**Comment by tkhai** [comment]
Last 3 lines place nr at the right border of alignment, which makes kernel, when allocates fdtable. I did that, because this seems to give some additional safety, and, also, aligned numbers are useful to count service fds on debugging. Let's leave this as is.

After `nr = max(nr, 1)` the smallest allocated fdtable will contain 256 entries, so I think we should better do

                if (nr != 0)
                        nr = 1 << (32 - __builtin_clz(nr));
                else
                        nr = 1;

**Comment by rburny** [comment]
Sure. Are you going to submit this patch, or should I send it to the mailing list?

**Comment by tkhai** [comment]
This is good catch you did. You are welcome with the fix :)

**Comment by rburny** [comment]
OK, sent the patch here: https://lists.openvz.org/pipermail/criu/2018-April/040973.html

Also, I found a slightly simpler fix - just removed division/multiplication of `nr` by 128. The result is the same (we round the number to the power of 2 anyway), but UB is avoided, because `nr` now cannot be 0.

**Comment by tkhai** [comment]
@rburny, it's not a round up power of 2, it's round up power of 2 rounded to 128. This goes from kernel: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/file.c#n85

#include <limits.h>
int main(void)
{
        unsigned int i, was, nr;

        for (i = 0; i < INT_MAX; i++) {
                nr = i;
                nr /= (1024 / sizeof(void *));
                if (nr)
                        nr = 1 << (32 - __builtin_clz(nr));
                else
                        nr = 1;
                nr *= (1024 / sizeof(void *));

                printf("nr=%d, i=%d\n", nr, i);
                if (nr < i || (nr-1) & nr) {
                        printf("error\n");
                        exit(1);
                }
        }

        return 0;
}

nr=128, i=16
nr=128, i=17
nr=128, i=18
nr=128, i=19
nr=128, i=20
nr=128, i=21
nr=128, i=22
nr=128, i=23
nr=128, i=24
nr=128, i=25
nr=128, i=26
nr=128, i=27
nr=128, i=28
nr=128, i=29
nr=128, i=30
