### ISSUE TITLE
cannot checkpoint mysql container--criu failed: type NOTIFY errno 0

### ISSUE THREAD

**Issue by ZikeWang** [checkpoint-restore/criu#471]
I created a mysql container with the following command :
`docker run --name=sql -it -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql`

After performing some table creation operations in the container, I tryed to checkpoint the container and it failed
```
root# docker checkpoint  create --checkpoint-dir=/tmp sql checkpoint1
Error response from daemon: Cannot checkpoint container sql: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /tmp/b0939ab67eb1cf13e3fa309b0609d67549004ae68c5e473692cbbac4e4e67e4a/checkpoints/checkpoint1/criu.work/dump.log\n"
```

I have successfully migrated the looper container which is an example in CRIU official website between  
 two host machine before, but when I tryed mysql it's failed. 

Docker version : 17.06.0-ce ( Experimental : true )
CRIU version : 3.7
Linux kernel : 4.4.0-31-generic ( Ubuntu 14.04.1 amd64 )

I have tryed `criu check --all` 
```
Error (criu/cr-check.c:985): The TCP_REPAIR_WINDOW option isn't supported.
Error (criu/cr-check.c:929): TCP_REPAIR can't be enabled for half-closed sockets
Warn  (criu/cr-check.c:1061): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1050): Non-cooperative UFFD is not supported
Error (criu/cr-check.c:822): autofs not supported.
Warn  (criu/cr-check.c:1027): compat_cr is not supported. Requires kernel >= v4.12
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

Here is the main part of error logs in  `dump.log` mentioned above : 
```
(01.935590) mnt: Dumping mountpoints
(01.935653) mnt: 	79: 32:/ @ ./sys/firmware
(03.390572) mnt: 	78: 2e:/null @ ./proc/sched_debug
(03.390620) mnt: 	77: 2e:/null @ ./proc/timer_stats
(03.390634) mnt: 	76: 2e:/null @ ./proc/timer_list
(03.390647) mnt: 	75: 2e:/null @ ./proc/kcore
(03.390659) mnt: 	74: 2d:/sysrq-trigger @ ./proc/sysrq-trigger
(03.390674) mnt: 	73: 2d:/sys @ ./proc/sys
(03.390686) mnt: 	72: 2d:/irq @ ./proc/irq
(03.390698) mnt: 	71: 2d:/fs @ ./proc/fs
(03.390709) mnt: 	70: 2d:/bus @ ./proc/bus
(03.390720) mnt: 	69: 2d:/asound @ ./proc/asound
(03.390732) mnt: 	67: 2f:/0 @ ./dev/console
(03.390753) Error (criu/tty.c:2306): tty: Unable to find a master for /0
(03.391122) Unlock network
(03.391140) Running network-unlock scripts
(03.391148) 	RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(03.467726) Unfreezing tasks into 1
(03.472077) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

I have attached the `dump.log` .
[dump.log](https://github.com/checkpoint-restore/criu/files/1912311/dump.log)

**Comment by rst0git** [comment]
Hi @ZikeWang, The error you are getting is because the docker container has pseudo-tty associated with the container. See https://github.com/checkpoint-restore/criu/issues/76 and https://criu.org/Docker#TTY.

The work around (as mentioned [here](https://stackoverflow.com/a/37861934)) is to remove `-t` from your docker command.

**Comment by ZikeWang** [comment]
Thx @rst0git , after removing `-t` from the command I could checkpoint the container. When I tried to restore the frozen container using the checkpoint file, the container could restart but I couldn't connect to the mysql server.
```
docker start --checkpoint-dir=/tmp/e75abaac799fe66a84cd4770f5736f321ea202b888220959333f1ef3cc5d9c29/checkpoints --checkpoint=checkpoint1 sql
docker exec -it sql bash
mysql -u root -p
#Enter my password
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
I found that the `/var/run/mysqld/mysqld.sock ` is missing after Docker C/R operations. I don't know how to fix it.

**Comment by rst0git** [comment]
Hi @ZikeWang,
I was not able to reproduce your problem with:
- Docker version 18.04.0-ce, build 3d479c0 ( Experimental : true )
- CRIU Version: 3.7.

I followed these steps:
```
$ docker pull mysql
$ docker run --name=sql -i -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql
$ docker checkpoint  create --checkpoint-dir=/tmp sql checkpoint1
$ docker start --checkpoint-dir=/tmp/checkpoint1/ --checkpoint=checkpoint1 sql
$ docker exec -it sql bash
root@2f793182b9e2:/# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.21 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye
```

**Comment by ZikeWang** [comment]
Hi @rst0git , I updated my docker from 17.06.0-ce to 18.03.0-ce, CRIU was still version 3.7. 
I repeated your steps. After checkpointing the container, I used the command `docker ps -a` to check the container status, I found that the container was not frozen and still running, so the following `docker start` command didn't seem to make sense. Have you encountered similar problems? (PS : I encountered a problem that running container could not be frozen before, it was resolved after reducing the docker version )

**Comment by rst0git** [comment]
Yes, you are right!
I added `docker stop sql` after the checkpoint command, but I was still able to connect to the mysql server after restore.

However, I used Fedora 27 with kernel version `4.15.15-300.fc27.x86_64` and output of `criu check --all` is only `Looks good.`

Perhaps the problems you encounter might be because of the missing kernel features.

**Comment by ZikeWang** [comment]
Thx @rst0git, I found this issue moby/moby#35690, the same problem. 
I successfully restored the mysql  container from its checkpoint files and could access the database created before. When I tried to  create another clone container, I could start it from the checkpoint files but the database is missing. Maybe it lacks some key operations during the migration. What's more should I do to perform the complete migration？Thank you！

**Comment by ZikeWang** [comment]
Thx @rst0git , I found this issue moby/moby#35690, the same problem.
I successfully restored the mysql container from its checkpoint files and could access the database created before. When I tried to create another clone container, I could start it from the checkpoint files but the database is missing. Maybe it lacks some key operations during the migration. What else should I do to perform the complete migration？Thank you！

**Comment by avagin** [comment]
@ZikeWang pls, write a sequence of commands what you use to reproduce this issue. I will try to reproduce and understand what is going on there. Thanks.

**Comment by ZikeWang** [comment]
Hi @avagin , thank you for help.

- Docker version : 18.03.0-ce
- CRIU version : 3.7
- kernel version : 4.4.0-31-generic ( Ubuntu 14.04.1 amd64 )

I have reproduced the issue:
```
root# docker run --name sql1 -i -p  3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql
1595e8102840ca640f465b496318ef98bbd5f6867231a78d4018f066e88cbbfe
root# docker exec -it sql1 bash
root@1595e8102840:/# mysqladmin -u root -p create RUNOOB
Enter password:
root@1595e8102840:/# mysql -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.21 MySQL Community Server (GPL)
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights  reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input  statement.
mysql> use RUNOOB
Database changed
mysql> CREATE TABLE runoob_tbl(
    -> runoob_id INT NOT NULL AUTO_INCREMENT,
    -> runoob_title VARCHAR(100) NOT NULL,
    -> runoob_author VARCHAR(40) NOT NULL,
    -> submission_date DATE,
    -> PRIMARY KEY ( runoob_id )
    -> )ENGINE=InnoDB DEFAULT CHARSET=utf8;
Query OK, 0 rows affected (0.01 sec)
mysql> INSERT INTO runoob_tbl
    -> (runoob_title, runoob_author, submission_date)
    -> VALUES
    -> ("Mysql", "User", NOW());
Query OK, 1 row affected, 1 warning (0.02 sec)
mysql> select * from runoob_tbl;
+-----------+--------------+---------------+-----------------+
| runoob_id | runoob_title | runoob_author | submission_date |
+-----------+--------------+---------------+-----------------+
|         1 | Mysql        | User          | 2018-04-24      |
+-----------+--------------+---------------+-----------------+
1 row in set (0.00 sec)
mysql> exit
Bye
root@1595e8102840:/# exit
exit
root# docker checkpoint create  --checkpoint-dir=/tmp sql1 checkpoint1
checkpoint1
root# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                    NAMES
1595e8102840        mysql               "docker-entrypoint.s...   13  minutes ago      Up 13 minutes       0.0.0.0:3306->3306/tcp   sql1
root# docker stop sql1
sql1
root# docker create --name=sql2 -i -p  3307:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql
a5bff33b1d16c1a8bd02b59547896ccefdd16a2ca5e742a1fa2866d8bc6ff869
root# docker start  --checkpoint-dir=/tmp/checkpoint1/ --checkpoint=checkpoint1 sql2
Error response from daemon: custom checkpointdir is not supported
root# docker start checkpoint checkpoint1 sql2
Error response from daemon: No such container: checkpoint
Error response from daemon: No such container: checkpoint1
sql2
Error: failed to start containers: checkpoint, checkpoint1
root# docker start  --checkpoint-dir=/tmp/checkpoint1/ --checkpoint=checkpoint1 sql2
root# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                     PORTS                    NAMES
a5bff33b1d16        mysql               "docker-entrypoint.s...   2 minutes  ago       Up 11 seconds              0.0.0.0:3307->3306/tcp   sql2
1595e8102840        mysql               "docker-entrypoint.s...   17  minutes ago      Exited (0) 3 minutes ago                            sql1
root# docker exec -it sql2 bash
root@a5bff33b1d16:/# mysql -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.21 MySQL Community Server (GPL)
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights  reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
Type 'help;' or '\h' for help. Type '\c' to clear the current input  statement.
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0.00 sec)
mysql> use RUNOOB
ERROR 1049 (42000): Unknown database 'RUNOOB'
mysql> exit
Bye
root@a5bff33b1d16:/# exit
exit
```

My problems are : 
1. The database RUNOOB I created in container sql1 was missing in the clone container sql2 after Docker checkpoint/start operations. In my view, CRIU checkpoints and restores the state, I need to do something else to migrate the contents inside the container. Is it right? And what else should I do?
2. After checkpointing the sql1 container, the container was not frozen. Missing kernel features?
3.  When I tried to start the clone container, the option `checkpointdir` was not supported. But when I used the command without the option first, it was ok and the container started running. What's wrong?

Thanks you very much!!!

**Comment by avagin** [comment]
Your container  was not restored from images, it was just started by this command
```
root# docker start checkpoint checkpoint1 sql2
Error response from daemon: No such container: checkpoint
Error response from daemon: No such container: checkpoint1
sql2
Error: failed to start containers: checkpoint, checkpoint1
```

**Comment by ZikeWang** [comment]
Hi @avagin , thank you for your detailed explanation.
Another more question, what's wrong with `Error response from daemon: custom checkpointdir is not supported` ?

**Comment by avagin** [comment]
It is a docker issue https://github.com/moby/moby/issues/34601

**Comment by ZikeWang** [comment]
got it, thank you so much! @avagin
