### ISSUE TITLE
Unable to restore lxc container state while streaming a video

### ISSUE THREAD

**Issue by Meriem-IT** [checkpoint-restore/criu#472]
Hello, 
I am actually facing an issue in which I am not able to restore the state of the container that is streaming a video, when I try to restore it I get some criu errors that I have posted in log.txt file.
//commands used :
lxc-checkpoint -s -D /tmp/chechpoint -n testr 
lxc-checkpoint -r -D /tmp/chechpoint -n testr -o log.txt
//Environment verisons:
Version of lxc :2.0.0
Version of criu :3.6
kernel version [:4.4.0-112-generic]
//output of dump.log :
[dump.txt](https://github.com/checkpoint-restore/criu/files/1928675/dump.txt)
//output of restore.log :
[restore.txt](https://github.com/checkpoint-restore/criu/files/1928680/restore.txt)
//output of log.txt
[log.txt](https://github.com/checkpoint-restore/criu/files/1928697/log.txt)
I would really appreciate your help .

**Comment by 0x7f454c46** [comment]
Ugh, it looks like `F_SETOWN_EX` races with fork() of the process-owner, at a quick glance.
Maybe we should restore file's owner on the next stage? Not sure.
+Cc @tkhai, @avagin

**Comment by tkhai** [comment]
prepare_fds() is called, when all the tasks have already created. So, they can't race. But F_SETOWN_EX can be related to threads, which are restored after fds (they are the lastest). If that's so, we can't completely fix that without threads-related architecture solution. The only solution for current threads architecture is to ignore F_SETOWN_EX.
CC @xemul

**Comment by 0x7f454c46** [comment]
Oh, yeah, I meant thread, but have written `fork()`. Sorry for the confusion.
Note, that we also have the C/R case with opened `/proc/<tid>/` which doesn't work for the same reason.

**Comment by 0x7f454c46** [comment]
IIRC, @xemul has said on that that we either should introduce a second restorer (because of some magic with thread creds restore) or work on restorer-v2.

**Comment by tkhai** [comment]
>because of some magic with thread creds restore

Do you mean the magic needed in this issue, or more magic in more issues?

**Comment by avagin** [comment]
@0x7f454c46 @tkhai is it possible to create threads before restoring file descriptors?

**Comment by tkhai** [comment]
This is about creating threads at the same time as other processes. I don't know limitations now (maybe, there is something nearly sigreturn interfaces), but the problem is not in limitations, it's in rewriting huge bunch of generic code and n+1 architecture-dependent parts...

**Comment by 0x7f454c46** [comment]
Hmm, I somehow bound creation of threads with restoring creds - but I'm not sure now.
