### ISSUE TITLE
Error (criu/mount.c:3385): mnt: The root task has another root than mntns: /new_root

### ISSUE THREAD

**Issue by criutest** [checkpoint-restore/criu#474]
Hello 
I am looking for failure reason of “docker checkpoint create” at aarch64(tegra) board 

criu -V
Warn  (criu/kerndat.c:781): Stale /run/criu.kdat file
Warn  (criu/net.c:2728): Unable to get a socket network namespace
Warn  (criu/libnetlink.c:55): ERROR -95 reported by netlink
Error (criu/net.c:3036): Unable to create a veth pair: -95
Warn  (criu/net.c:3058): NSID isn't reported for network links
Error (criu/uffd.c:235): uffd: Lazy pages are not available: Function not implemented
Warn  (criu/net.c:2728): Unable to get a socket network namespace

criu check
Looks good.

tried to initiate simple example at https://criu.org/Docker
However docker checkpoint create looper checkpoint1 returns
Error response from daemon: Cannot checkpoint container looper: rpc error: code = Unknown desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/215b441b38afbf813f8a3201ef552712a71bd0b5778bb4432a7cc9f4f77a0be7/checkpoints/checkpoint8/criu.work/dump.log\n"

-> 
(00.156626) Error (criu/mount.c:3385): mnt: The root task has another root than mntns: /new_root
(00.156649) Error (criu/mount.c:158): mnt: Unable to get the root file descriptor of pid 3579
(00.156664) Error (criu/cr-dump.c:1249): Collect mappings (pid: 3579) failed with -1

iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'

kernel config.gz and dump.log are attached, Any advice related with this would be appreciated!! 

[config.gz](https://github.com/checkpoint-restore/criu/files/1932910/config.gz)
[dump.log](https://github.com/checkpoint-restore/criu/files/1932911/dump.log)

**Comment by avagin** [comment]
Could you show /proc/self/mountinfo from this host?

**Comment by criutest** [comment]
cat /proc/self/mountinfo Thanks in advance!!!

20 0 8:1 / / rw,noatime shared:1 - ext4 /dev/sda1 rw,data=ordered
21 20 0:4 / /proc rw,relatime shared:2 - proc proc rw
22 20 0:16 / /sys rw,nosuid,nodev,noexec,relatime shared:3 - sysfs sysfs rw
23 20 0:6 / /dev rw,relatime shared:7 - devtmpfs none rw,size=12561676k,nr_inodes=3140419,mode=755
17 23 0:18 / /dev/shm rw,nosuid,nodev shared:8 - tmpfs tmpfs rw,size=409600k
18 23 0:19 / /dev/pts rw,relatime shared:9 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
24 20 0:20 / /run rw,nosuid,nodev shared:10 - tmpfs tmpfs rw,size=81920k,mode=755
25 22 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:4 - tmpfs tmpfs ro,mode=755
26 25 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:5 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
27 22 0:23 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:6 - pstore pstore rw
28 25 0:24 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,cpu,cpuacct
29 25 0:25 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:12 - cgroup cgroup rw,cpuset
30 25 0:26 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,freezer
31 25 0:27 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,pids
32 25 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,blkio
33 25 0:29 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,memory
34 25 0:30 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,devices
35 25 0:31 / /sys/fs/cgroup/debug rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,debug
36 22 0:7 / /sys/kernel/debug rw,relatime shared:19 - debugfs debugfs rw
37 23 0:14 / /dev/mqueue rw,relatime shared:20 - mqueue mqueue rw
38 20 0:32 / /tmp rw shared:21 - tmpfs tmpfs rw,size=1048576k
39 21 0:33 / /proc/fs/nfsd rw,relatime shared:22 - nfsd nfsd rw
40 22 0:34 / /sys/fs/fuse/connections rw,relatime shared:23 - fusectl fusectl rw
41 22 0:15 / /sys/kernel/config rw,relatime shared:24 - configfs configfs rw
42 20 8:9 / /mnt/database ro,noexec,noatime shared:25 - ext4 /dev/sda9 ro,stripe=2,data=ordered
43 20 8:8 / /mnt/trace rw,noexec,noatime shared:26 - ext4 /dev/sda8 rw,block_validity,delalloc,barrier,user_xattr,acl
44 20 8:7 / /mnt/player rw,noexec,noatime shared:27 - ext4 /dev/sda7 rw,block_validity,delalloc,barrier,user_xattr,acl
45 20 8:6 / /backup rw,noexec,noatime shared:28 - ext4 /dev/sda6 rw,block_validity,delalloc,barrier,user_xattr,acl
46 20 8:5 / /var rw,noexec,noatime shared:29 - ext4 /dev/sda5 rw,data=ordered
47 20 8:5 /opt/data/persistency /Data/mnt-c rw,noexec,noatime shared:29 - ext4 /dev/sda5 rw,data=ordered
48 20 8:5 /opt/data/persistency /Data/mnt-wt rw,noexec,noatime shared:29 - ext4 /dev/sda5 rw,data=ordered
49 20 8:5 /opt/data/persistency_backup /Data/mnt-backup rw,noexec,noatime shared:29 - ext4 /dev/sda5 rw,data=ordered
50 46 8:5 /lib/docker/overlay2 /var/lib/docker/overlay2 rw,noexec,noatime - ext4 /dev/sda5 rw,data=ordered
51 50 0:35 / /var/lib/docker/overlay2/2837dbba5ea9cab7b1b56d5397c02e583ea51580305a8ad8fabf0262c6ad6579/merged rw,relatime - overlay overlay rw,lowerdir=/var/lib/docker/overlay2/l/MOOWQMRCFFPRUCYY6CIBXFLOJR:/var/lib/docker/overlay2/l/O5PNRCDBHVTDT2QWT3DOEX5SNN,upperdir=/var/lib/docker/overlay2/2837dbba5ea9cab7b1b56d5397c02e583ea51580305a8ad8fabf0262c6ad6579/diff,workdir=/var/lib/docker/overlay2/2837dbba5ea9cab7b1b56d5397c02e583ea51580305a8ad8fabf0262c6ad6579/work
55 46 0:36 / /var/lib/docker/containers/6388661efa40ca416baaab3af8b294a23c9e3832446afb24dc3ce22e9af7bb10/shm rw,nosuid,nodev,noexec,relatime shared:30 - tmpfs shm rw,size=65536k
116 24 0:3 net:[4026533454] /run/docker/netns/79f7a3a707e0 rw shared:31 - nsfs nsfs rw

**Comment by avagin** [comment]
And could you show /proc/pid/mountunfo for a container process? This file should be read from the host (not from a container).

**Comment by criutest** [comment]
Dear Andrew Vagin

Thanks so much for advice!
Please find attached logs

1.	host_proc_self_mountinfo.txt : host cat /proc/self/mountinfo
1.1.	docker run -d --name looper --security-opt seccomp:unconfined arm64v8/busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
2.	host_proc_pid_mountinfo.txt : host machine /cat/pid(8485)/mountinfo
2.1.	docker start --checkpoint checkpoint1 looper 
2.1.1.	dump8485.log : criu log
Error response from daemon: Cannot checkpoint container looper: rpc error: code = Unknown desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/li68071d4309c906325e0b3/checkpoints/checkpoint1/criu.work/dump.log\n"
2.1.2.	docker.txt : docker debug log 
3.	busybox_container_mountinfo.txt : another busybox container just for comparing mountinfo

just like above, host can read proc/pid/mountinfo file
and if I compare mountinfo with X64 ubuntu – difference is just noatime<->relatime
- Aarch64 : 20 0 8:1 / / rw,noatime shared:1 - ext4 /dev/sda1 rw,data=ordered (already change ro->rw : mount –o rw,remount /)
- X64 Ubuntu : 28 0 8:1 / / rw,relatime shared:1 - ext4 /dev/sda1 rw,errors=remount-ro,data=ordered

This is ambiguous to me whether my environment(kernel config?, mount?) is wrong or it could be some kinds of bug related with Docker…
Thanks!!!

Best Regards


[busybox_container_mountinfo.txt](https://github.com/checkpoint-restore/criu/files/1942543/busybox_container_mountinfo.txt)
[docker.txt](https://github.com/checkpoint-restore/criu/files/1942544/docker.txt)
[dump8485.txt](https://github.com/checkpoint-restore/criu/files/1942545/dump8485.txt)
[host_proc_pid_mountinfo.txt](https://github.com/checkpoint-restore/criu/files/1942546/host_proc_pid_mountinfo.txt)
[host_proc_self_mountinfo.txt](https://github.com/checkpoint-restore/criu/files/1942547/host_proc_self_mountinfo.txt)
