### ISSUE TITLE
Issue about restoring shared memory across difference instances

### ISSUE THREAD

**Issue by paizhang** [checkpoint-restore/criu#475]
Hi guys,

I checkpointed a container with some data in shared memory. And I migrated the checkpoint files to another Ubuntu instance and restored it. I can restored it successfully. But when I run another program within the restored container which will retrieve those data from shared memory. But it failed to retrieve the data in the shared memory. So I wonder whether CRIU support checkpoint and restore the process with some shared memory from one instance to another instance. 

Thank you and look forward to hearing some advice.

**Comment by avagin** [comment]
Do you use System V shared memory?
