### ISSUE TITLE
fsnotify: Can't open file handle for 0x000042:0x0000000006cf22: Stale file handle

### ISSUE THREAD

**Issue by karthiksjsu** [checkpoint-restore/criu#476]
Trying to create a checkpoint for the container which has opendaylight controller running inside it ...
criu throws an error 

root@Karthik:/home/karthik/dockers/check123/criu.work# cat dump.log | grep Error
(00.379158) Error (criu/fsnotify.c:215): fsnotify: Can't open file handle for 0x000042:0x0000000006cf22: Stale file handle
(00.385113) Error (criu/irmap.c:86): irmap: Can't stat /var/lib/polkit-1/localauthority: No such file or directory
(00.385235) Error (criu/irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.385241) Error (criu/fsnotify.c:285): fsnotify: 	Can't dump that handle
(00.385260) Error (criu/cr-dump.c:1313): Dump files (pid: 10372) failed with -1
(00.405355) Error (criu/cr-dump.c:1628): Dumping FAILED.

**Comment by karthiksjsu** [comment]
root@Karthik:/var/lib/polkit-1# ls
localauthority
root@Karthik:/var/lib/polkit-1# cd localauthority/
root@Karthik:/var/lib/polkit-1/localauthority# ls
10-vendor.d  20-org.d  30-site.d  50-local.d  90-mandatory.d
root@Karthik:/var/lib/polkit-1/localauthority#

**Comment by avagin** [comment]
@karthiksjsu Could you attach a dump log?
