### ISSUE TITLE
criu dump error during docker checkpoint

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#477]
Hi
I am trying to checkpoint a docker container but criu is giving error of "Dumping Failed" as shown in logs below. Does anyone know how to solve this issue? There is some systemd mount issue but i am not sure about it.  Thanks

root@edge1:~# docker checkpoint create docker-test docker-test
Error response from daemon: Cannot checkpoint container docker-test: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/dccb3460259a98400c020570c53b092fd16d138c8683867ef5bf42d85991f13a/checkpoints/docker-test/criu.work/dump.log\n"

Dump Logs:
**(00.084764) Error (criu/mount.c:746): mnt: 192:./sys/fs/cgroup/name=systemd doesn't have a proper root mount**
(00.084784) Unlock network
(00.084789) Running network-unlock scripts
(00.084794)     RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.100048) Unfreezing tasks into 1
(00.100155) Error (criu/cr-dump.c:1709): Dumping FAILED.

**Comment by farooqte96** [comment]
Thanks alot @avagin  for addressing the query. It occured for criu version 3.8 & Docker version 17.06.2-ee-6. I was using it on a vm, so linux kernel was also old so i removed that distribution, installed a new one with updated kernel and this error is gone.

**Comment by avagin** [comment]
You are welcome. Can we close this issue?
