### ISSUE TITLE
No need to unlock network in the remote node

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#478]
Hi,

I found that the restore stage costs too much time, following this page [Lazy_migration](https://criu.org/Lazy_migration).

In the lazy migration scenario, lock the network in local node is necessary, but there is no need to unlock the network in the remote node while no iptables rule need to be removed. Otherwise, we will see many error logs:

```
(00.027263) Unlock network
(00.027276) 	Running iptables [iptables -w -t filter -D INPUT --protocol tcp -m mark ! --mark 0xC114 --source 11.163.5.56 --sport 8080 --destination 10.101.192.162 --dport 65046 -j DROP]
iptables: Bad rule (does a matching rule exist in that chain?).
(00.037750) Error (criu/util.c:800): exited, status=1
(00.037772) Error (criu/netfilter.c:103): Iptables configuration failed
(00.037776) Unlocked 10.101.192.162:65046 - 11.163.5.56:8080 connection
(00.037786) 	Running iptables [iptables -w -t filter -D OUTPUT --protocol tcp -m mark ! --mark 0xC114 --source 10.101.192.162 --sport 65046 --destination 11.163.5.56 --dport 8080 -j DROP]
iptables: Bad rule (does a matching rule exist in that chain?).
```

I think this is a bug, any suggestion?

**Comment by avagin** [comment]
You try to migrate processes which have established tcp connections. If you want to migrate these connections, you need to migrate their source ip addresses too, and all iptables rules what have been added by criu. It will be easier, if you will run these processes in a container and migrate this container.

https://criu.org/TCP_connection

Could you describe a workload what you want to migrate?

**Comment by zhouxinyu** [comment]
@avagin thanks for your reply.

Yes, the process has some established TCP connections, the problem is that I can't do a dump if I don't specify the `--tcp-established` option, see the error log:

```
(00.019055) Error (criu/sk-inet.c:181): Connected TCP socket, consider using --tcp-established option.
(00.019060) ----------------------------------------
(00.019069) Error (criu/cr-dump.c:1352): Dump files (pid: 15892) failed with -1
```

Actually, I want to discard the established connections, so I used the `--tcp-close` option, but it doesn't work, the `--tcp-established` option is required.

And, the application is a jvm process, next step I will do some tests among docker, as you say, migrate a container is easier, I wonder that is the lazy migration supported in docker migration?

**Comment by zhouxinyu** [comment]
I will try this patch, thanks to all you guys.

**Comment by zhouxinyu** [comment]
@avagin 

I could dump only with --tcp-close, but it doesn't work when I restore the process in the remote node, error occurs:

```
(00.019404)  11721: 		Create fd for 17
(00.019415)  11721: 	Restore: family 2 type 1 proto 6 port 62410 state 7 src_addr 10.101.192.162
(00.019443)  11721: Error (criu/sk-inet.c:850): Can't bind inet socket (id 45): Cannot assign requested address
(00.019460)  11721: Error (criu/files.c:1192): Unable to open fd=18 id=0x2d
(00.019497) Error (criu/cr-restore.c:2252): Restoring FAILED.
```

**Comment by avagin** [comment]
```
diff --git a/criu/sk-inet.c b/criu/sk-inet.c
index 14a8e17c4..86846ebf4 100644
--- a/criu/sk-inet.c
+++ b/criu/sk-inet.c
@@ -119,7 +119,7 @@ static int can_dump_ipproto(int ino, int proto)
        return 1;
 }
 
-static int can_dump_inet_sk(const struct inet_sk_desc *sk)
+static int can_dump_inet_sk(struct inet_sk_desc *sk)
 {
        BUG_ON((sk->sd.family != AF_INET) && (sk->sd.family != AF_INET6));
 
@@ -149,6 +149,12 @@ static int can_dump_inet_sk(const struct inet_sk_desc *sk)
                return 0;
        }
 
+       if (opts.tcp_close) {
+               sk->state = TCP_CLOSE;
+               sk->dst_port = 0;
+               sk->src_port = 0;
+       }
+
        switch (sk->state) {
        case TCP_LISTEN:
                if (sk->rqlen != 0) {
```
What is about this patch?

**Comment by zhouxinyu** [comment]
It works, thanks.

BTW, is there any solution for the frequent PID mismatch error?

```
(00.098154)pie: 68233: Error (criu/pie/restorer.c:498): Thread pid mismatch 6>
```

**Comment by avagin** [comment]
> BTW, is there any solution for the frequent PID mismatch error(lazy migration)?

You can run your processes in a separate pid namespace to avoid this error.

**Comment by zhouxinyu** [comment]
Hi, 

```
sudo unshare -p sudo -u admin java -jar .....
```

I used the above command to start my process and then execute criu dump with --lazy-pages, but it doesn't work.

```
(00.062997) Unlock network
(00.063010) Unfreezing tasks into 1
(00.063013) 	Unseizing 101524 into 1
(00.063508) Error (criu/cr-dump.c:1709): Dumping FAILED.
```

**Comment by avagin** [comment]
Could you attached a process tree (ps axf) and a whole dump log? criu dump has to be executed with -v4.

**Comment by zhouxinyu** [comment]
The whole dump log: [restore.log](https://github.com/checkpoint-restore/criu/files/1964061/restore.log)

And the related process tree:

```
103369 ?        S      0:00 sudo unshare -p sudo -u admin /opt/usr/java/bin/java -jar Main.jar
103371 ?        S      0:00  \_ sudo -u admin /opt/usr/java/bin/java -jar Main.jar
103372 ?        Sl   1811:13      \_ /opt/usr/java/bin/java -jar Main.jar
```

**Comment by avagin** [comment]
The error is clear. I'm preparing a patch for it. I will post it here today.

**Comment by zhouxinyu** [comment]
Hi,

I used `sudo unshare -p -m --fork --mount-proc` to open a new namespace and resolved the mismatch issue, so I didn't try out the last one patch.

Thanks.
