### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by treaki** [checkpoint-restore/criu#481]
i am using debian 9.2 and trying to install criu to get lxc-checkpoint to work, everything until make install worked fine but when executing this:

```
make install
  GEN      crit.1
Makefile:47: recipe for target 'crit.1' failed
make[1]: *** [crit.1] Error 127
Makefile.install:32: recipe for target 'install-man' failed
make: *** [install-man] Error 2
```
whats wrong here, how to fix it?

thanks in advance

**Comment by rst0git** [comment]
Hi @treaki,
This error occurs because the installation of man pages has failed. Try to install the `xmlto` package.
```
apt-get install xmlto
```
