### ISSUE TITLE
Problem checkpointing lxc container "Error (criu/cgroup.c:620): cg: failed walking ... No such file or directory"

### ISSUE THREAD

**Issue by ehmm** [checkpoint-restore/criu#482]
Hi,
I'm using lxc 3.0 and criu 3.6 trying to checkpoint a container.
The checkpoint is failing with the above error.

More of the log:

`(00.060742) cg: Dumping cgroups for 3158
(00.060837) cg:  `- New css ID 2
(00.060843) cg:     `- [blkio] -> [/nested] [125]
(00.060845) cg:     `- [cpu,cpuacct] -> [/nested] [125]
(00.060848) cg:     `- [cpuset] -> [/nested] [125]
(00.060850) cg:     `- [devices] -> [/nested] [125]
(00.060852) cg:     `- [freezer] -> [/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194] [291]
(00.060854) cg:     `- [hugetlb] -> [/nested] [125]
(00.060856) cg:     `- [memory] -> [/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194] [291]
(00.060858) cg:     `- [name=systemd] -> [/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194] [291]
(00.060861) cg:     `- [name=zdtmtst] -> [/] [0]
(00.060863) cg:     `- [name=zdtmtst.defaultroot] -> [/] [0]
(00.060865) cg:     `- [net_cls,net_prio] -> [/nested] [125]
(00.060874) cg:     `- [perf_event] -> [/nested] [125]
(00.060882) cg:     `- [pids] -> [/nested] [125]
(00.060884) cg:     `- [rdma] -> [/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194] [41]
(00.078032) cg: adding cgroup /proc/self/fd/10/nested
(00.078076) cg: Dumping value 500 from /proc/self/fd/10/nested/blkio.weight
(00.078093) cg: Dumping value 0 from /proc/self/fd/10/nested/cgroup.clone_children
(00.078107) cg: Dumping value 0 from /proc/self/fd/10/nested/notify_on_release
(00.078121) cg: Dumping value  from /proc/self/fd/10/nested/cgroup.procs
(00.078134) cg: Dumping value  from /proc/self/fd/10/nested/tasks
(00.093997) cg: adding cgroup /proc/self/fd/10/nested
(00.094036) cg: Dumping value 2 from /proc/self/fd/10/nested/cpu.shares
(00.094052) cg: Dumping value 100000 from /proc/self/fd/10/nested/cpu.cfs_period_us
(00.094066) cg: Dumping value -1 from /proc/self/fd/10/nested/cpu.cfs_quota_us
(00.094075) cg: Couldn't open /proc/self/fd/10/nested/cpu.rt_period_us. This cgroup property may not exist on this kernel
(00.094082) cg: Couldn't open /proc/self/fd/10/nested/cpu.rt_runtime_us. This cgroup property may not exist on this kernel
(00.094098) cg: Dumping value 0 from /proc/self/fd/10/nested/cgroup.clone_children
(00.094120) cg: Dumping value 0 from /proc/self/fd/10/nested/notify_on_release
(00.094141) cg: Dumping value  from /proc/self/fd/10/nested/cgroup.procs
(00.094161) cg: Dumping value  from /proc/self/fd/10/nested/tasks
(00.094183) cg: Dumping value 0 from /proc/self/fd/10/nested/cgroup.clone_children
(00.094197) cg: Dumping value 0 from /proc/self/fd/10/nested/notify_on_release
(00.094209) cg: Dumping value  from /proc/self/fd/10/nested/cgroup.procs
(00.094232) cg: Dumping value  from /proc/self/fd/10/nested/tasks
(00.117981) cg: adding cgroup /proc/self/fd/10/nested
(00.118020) cg: Dumping value 0-1 from /proc/self/fd/10/nested/cpuset.cpus
(00.118036) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.mems
(00.118051) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.memory_migrate
(00.118065) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.cpu_exclusive
(00.118079) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.mem_exclusive
(00.118093) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.mem_hardwall
(00.118107) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.memory_spread_page
(00.118121) cg: Dumping value 0 from /proc/self/fd/10/nested/cpuset.memory_spread_slab
(00.118135) cg: Dumping value 1 from /proc/self/fd/10/nested/cpuset.sched_load_balance
(00.118149) cg: Dumping value -1 from /proc/self/fd/10/nested/cpuset.sched_relax_domain_level
(00.118163) cg: Dumping value 1 from /proc/self/fd/10/nested/cgroup.clone_children
(00.118177) cg: Dumping value 0 from /proc/self/fd/10/nested/notify_on_release
(00.118190) cg: Dumping value  from /proc/self/fd/10/nested/cgroup.procs
(00.118203) cg: Dumping value  from /proc/self/fd/10/nested/tasks
(00.133977) cg: adding cgroup /proc/self/fd/10/nested
(00.134015) cg: Dumping value a *:* rwm from /proc/self/fd/10/nested/devices.list
(00.134032) cg: Dumping value 0 from /proc/self/fd/10/nested/cgroup.clone_children
(00.134046) cg: Dumping value 0 from /proc/self/fd/10/nested/notify_on_release
(00.134059) cg: Dumping value  from /proc/self/fd/10/nested/cgroup.procs
(00.134084) cg: Dumping value  from /proc/self/fd/10/nested/tasks
(00.150073) Error (criu/cgroup.c:620): cg: failed walking /proc/self/fd/10/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 for empty cgroups: No such file or directory`

Now the scenario is a bit more complex as the lxc is running nested in a docker container hence the `nested` namespace.

The command line to criu was:
`/usr/local/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /tmp/bb -o /tmp/bb/dump.log --cgroup-root name=systemd:/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 --cgroup-root freezer:/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 --cgroup-root memory:/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 --cgroup-root rdma:/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 -vvvvvv --ext-mount-map /sys/fs/fuse/connections:sys/fs/fuse/connections --ext-mount-map /sys/kernel/debug:sys/kernel/debug --ext-mount-map /sys/kernel/security:sys/kernel/security --ext-mount-map /sys/fs/pstore:sys/fs/pstore -t 3158 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer//nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194 --ext-mount-map /dev/console:console --external tty[8800:bf] --force-irmap --leave-running`

And the pid 3158 is the /bin/init inside the lxc-container, 

As I don't really understand the error I was hoping with some help or pointer into how to debug this.

Thanks in advance,
EH

**Comment by avagin** [comment]
> (00.060843) cg: - [blkio] -> [/nested] [125] (00.060845) cg:- [cpu,cpuacct] -> [/nested] [125]

It looks like a bug that we see blkio and cpu,cpuacct together in this line

**Comment by avagin** [comment]
Could you show /proc/cgroups and /proc/pid/cgroups for the container init?

**Comment by avagin** [comment]
```
(00.060852) cg:     `- [freezer] -> [/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194] [291]
```

Paths for freezer, memory, systemd contains nested twice, it is probably a reason for this error.

**Comment by ehmm** [comment]
The /proc/PID/cgroups from the container host:
`14:name=zdtmtst.defaultroot:/
13:name=zdtmtst:/
12:pids:/nested
11:devices:/nested
10:hugetlb:/nested
9:rdma:/lxc/24f7a993-4cbf-11e8-ab0e-42010a3c0194
8:cpuset:/nested
7:blkio:/nested
6:memory:/nested/nested/lxc/24f7a993-4cbf-11e8-ab0e-42010a3c0194
5:freezer:/nested/nested/lxc/24f7a993-4cbf-11e8-ab0e-42010a3c0194
4:net_cls,net_prio:/nested
3:perf_event:/nested
2:cpu,cpuacct:/nested
1:name=systemd:/nested/nested/lxc/24f7a993-4cbf-11e8-ab0e-42010a3c0194`
and /proc/cgroups from the container host:
`#subsys_name    hierarchy       num_cgroups     enabled
cpuset  8       35      1
cpu     2       169     1
cpuacct 2       169     1
blkio   7       169     1
memory  6       393     1
devices 11      169     1
freezer 5       44      1
net_cls 4       35      1
perf_event      3       35      1
net_prio        4       35      1
hugetlb 10      35      1
pids    12      170     1
rdma    9       15      1`

I see what your saying that freezer/memory/systemd contain nested twice -- is this a bug with lxc?

**Comment by avagin** [comment]
> I see what your saying that freezer/memory/systemd contain nested twice -- is this a bug with lxc?
I don't know. If it is not a bug, you need to fix criu options
Now you have:
--cgroup-root memory:/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194
but it should be:
--cgroup-root memory:/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194

**Comment by ehmm** [comment]
@avagin I patched my LXC to allow using `--cgroup-root memory:/nested/nested/lxc/e007f72c-4c88-11e8-ab0e-42010a3c0194` as you said, now the checkpointing works, before closing the issue I'm having issues with the restore #499 -- they seem unrelated but just want to make sure before closing.
