### ISSUE TITLE
Unable to restore processes with vDSO unmapped

### ISSUE THREAD

**Issue by wno-git** [checkpoint-restore/criu#488]
Hello,

CRIU fails to restore applications that have unmapped the vDSO segment. One such
application is Valgrind. When the checkpoint is restored CRIU complains that the
vDSO segment is not found in the checkpoint image and will not restore.

Steps to reproduce:

```
$ valgrind --tool=none cat &
==26474== Nulgrind, the minimal Valgrind tool
==26474== Copyright (C) 2002-2017, and GNU GPL'd, by Nicholas Nethercote.
==26474== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==26474== Command: cat
==26474==

$ grep vvar /proc/$(pidof valgrind.bin)/smaps
7fff258df000-7fff258e2000 r--p 00000000 00:00 0                          [vvar]

$ grep vdso /proc/$(pidof valgrind.bin)/smaps
$ echo $?
1

# criu dump -j -t $(pidof valgrind.bin)

# criu restore -j
pie: 27729: Error (criu/pie/parasite-vdso.c:252): vdso: Can't find vDSO area >
pie: 27729: in image
pie: 27729: Error (criu/pie/restorer.c:1689): Restorer fail 27729
Error (criu/cr-restore.c:2252): Restoring FAILED.
```

By commenting out the call to vdso_proxify in criu/pie/restorer.c:1360 I'm able
to successfully restore the Valgrind process. However, the newly created process
has the vDSO mapped again which can be a problem for this kind of application
that has explicitly unmapped its vDSO.

```
# criu -V
Version: 3.8.1

$ valgrind --version
valgrind-3.13.0

$ uname -a
Linux devbox 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:    Debian
Description:       Debian GNU/Linux testing (buster)
Release:           testing
Codename:          buster
```

**Comment by avagin** [comment]
Cc: @cyrillos @0x7f454c46

**Comment by 0x7f454c46** [comment]
Ugh, that's mine.
I even have previously written zdtm/static/vdso02.c test to check that.
Looks like, something is wrong with the test, I'll look, thanks.
