### ISSUE TITLE
docker  start --checkpoint doesnt start container from a checkpoint image

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#492]
Hi
Docker checkpoint and restore works when performed on same host. But when a checkpointed container image from another host is copied to /checkpoint directory of newly created container. It doesnt start container from that checkpoint successfully and also doesn't show any error message.

Docker version: 17.06.2-ee-6
CRIU Version: 3.9

Container starts when checkpoint created on same host:
 
$docker run -d --name docker-beta -p 80:80 nginx
fe8ab896dfa50a05893657cf16e0ba1da5dbe0d571cea32b570eab1a5272f061
$docker checkpoint create docker-beta docker-beta
docker-beta
$ docker start --checkpoint docker-beta docker-beta
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
fe8ab896dfa5        nginx               "nginx -g 'daemon ..."   54 seconds ago      Up 2 seconds        0.0.0.0:80->80/tcp   docker-beta

Container doesn't start when checkpoint image is copied from remote host:

$docker create --name docker-beta -p 80:80 nginx
cd7a074ee923e579e992b46f84f7ed1e96a4c9c4a279741c2a275bf1e6f80461
$ sudo su
$scp -r /tmp/checkpoint1/ /var/lib/docker/containers/cd7a074ee923e579e992b46f84f7ed1e96a4c9c4a279741c2a275bf1e6f80461/checkpoints/
$docker start --checkpoint checkpoint1 docker-beta
$docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by avagin** [comment]
@kolyshkin

**Comment by farooqte96** [comment]
@avagin @kolyshkin @xemul 
Anybody knows how to fix this issue?

**Comment by rst0git** [comment]
Hi @farooqte96,
Would you be able to attach a log file with more information about the failure?
also what is you kernel version, linux distribution?

**Comment by farooqte96** [comment]
This issue went away itself and i don't know what was reason because i didn't get any errors. May be docker  had stopped working properly.
