### ISSUE TITLE
vz7 online container migration fails with Remote exception I/O operation on closed file

### ISSUE THREAD

**Issue by vaverin** [checkpoint-restore/criu#494]
https://forum.openvz.org/index.php?t=rview&goto=53303

[root@vz03 ~]# vzmigrate -vvv --online --require-realtime vz04 222
...
2018-05-23 10:30:10.732: Live migration stage started
2018-05-23 10:30:36.320: Io multiplexer aborted
2018-05-23 10:30:36.320: 2018-05-23 10:30:36.321: Phaul service failed to live migrate CT
2018-05-23 10:30:36.320: 2018-05-23 10:30:36.321: error [-73] : Phaul service failed to live migrate CT

[root@vz04 ~]# tail -20 /var/log/phaul-service.log
10:30:35.562: 817892: Waiting for images to unpack
10:30:35.813: 817892: Restoring from images
10:30:35.827: 817892: Starting vzctl restore
10:30:36.269: 817892:   > Restoring the Container ...
10:30:36.269: 817892:   > Mount image: /vz/private/222/root.hdd 
10:30:36.269: 817892:   > Container is mounted
10:30:36.269: 817892:   > Setting permissions for image=/vz/private/222/root.hdd
10:30:36.269: 817892:   > (00.000283) Error (criu/util.c:694): Can't read link of fd -404: No such file or directory
10:30:36.270: 817892:   > (00.000295) Error (criu/protobuf.c:77): Unexpected EOF on (null)
10:30:36.270: 817892:   > The restore log was saved in /vz/dump/222/rst-_cQGWZ-18.05.23-10.30/criu_restore.9.log
10:30:36.270: 817892:   > criu exited with rc=17

[root@vz04 ~]# tail -20 /vz/dump/222/rst-_cQGWZ-18.05.23-10.30/criu_restore.9.log
(00.000142) Version: 3.8 (gitid 0)
(00.000188) Running on vz04.boardreader.com Linux 3.10.0-693.21.1.vz7.47.4 #1 SMP Sat Apr 28 11:48:07 MSK 2018 x86_64
(00.000237) No inventory.img image
(00.000283) Error (criu/util.c:694): Can't read link of fd -404: No such file or directory
(00.000295) Error (criu/protobuf.c:77): Unexpected EOF on (null)

**Comment by mishaivinco** [comment]
criu_restore.9.log was already posted (see above). I attached additionally the whole /vz/dump/222/rst-_cQGWZ-18.05.23-10.30 dir contents.

[rst-_cQGWZ-18.05.23-10.30.tar.gz](https://github.com/checkpoint-restore/criu/files/2039155/rst-_cQGWZ-18.05.23-10.30.tar.gz)

**Comment by 0x7f454c46** [comment]
This one looks suspicious and might be the reason of the fail:
```
(02.037229) Error (criu/page-xfer.c:379): No parent image found, though parent directory is set: No such file or directory
```
Probably, it's a bug in criu integration. libvzctl or something?

**Comment by vaverin** [comment]
ok, reported as https://bugs.openvz.org/browse/OVZ-7030
