### ISSUE TITLE
Couldn't handle the renamed unix socket

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#497]
JVM will generate a unix socket to communicate with operations tools which path is:

```
/tmp/.java_pid$pid
```

But the steps to create the socket are a little complex to avoid exposing the not fully initialized socket:

1. Create the socket `/tmp/.java_pid$pid.tmp`(which has a suffix .tmp).
2. Unlink and bind on the above path.
3. Chmod the permissions of the socket to READ+WRITE.
4. Rename the socket from `/tmp/.java_pid$pid.tmp` to `/tmp/.java_pid$pid`

[Here](https://github.com/JetBrains/jdk8u_hotspot/blob/master/src/os/linux/vm/attachListener_linux.cpp#L172) is the source code.

And after we start a JVM we could see the bind socket and the created path:

![image](https://user-images.githubusercontent.com/3961183/40656835-42138a14-6378-11e8-84fb-f30927279bc4.png)

But when we dump the process, the criu will skip this unix socket because `/tmp/.java_pid$pid.tmp` is not found:

![image](https://user-images.githubusercontent.com/3961183/40656673-b6c9c5a4-6377-11e8-8ba6-aea030653bb2.png)

Any solution to handle this issue?

**Comment by avagin** [comment]
Cc: @cyrillos 

There is the SIOCUNIXFILE ioctl, which will be useful to fix this issue
https://github.com/torvalds/linux/commit/ba94f3088b792b16ea576a256a6030feddc87f24

**Comment by zhouxinyu** [comment]
Thanks, do we have a workaround solution on criu layer before upgrading the kernel?

**Comment by avagin** [comment]
We can scan a file system and compare file inode numbers.

It is not enough to update the kernel, we need to change criu to support this case.

**Comment by zhouxinyu** [comment]
Got it, thanks.
