### ISSUE TITLE
Uncoordinated Checkpoints

### ISSUE THREAD

**Issue by bethven** [checkpoint-restore/criu#498]
Hi,
I would like to know if with Criu you can run Uncoordinated Checkpoints with MPI applications. 
I need to do this and I do not know with what I can do it.
Thank you very much.

**Comment by adrianreber** [comment]
@bethven To better understand what you are trying to do it would be good to have more information.

Which MPI implementation are you using and maybe some additional information about your setup.

As far as I know, there is no special feature necessary to do uncoordinated checkpoints, coordinated checkpoints in an MPI environment are the difficult thing.

**Comment by bethven** [comment]
Thank you very much for your quick response, I need to make a Uncoordinated checkpoint to an MPI application, could be to any of the NAS applications, I am using MPICH, I have already used the DMTCP to do coordinated checkpoints, but I do not know what I should use to do Uncoordinated Checkpoint.
There is some library to do it? or I have to schedule a script for this? I thank you very much to indicate that I should look for it to be able to do it.
Regards.

**Comment by adrianreber** [comment]
Some years ago I worked on integrating CRIU into Open MPI and with Open MPI it was necessary to actually change the source code of Open MPI to get it working.

I have no knowledge about MPICH but I am pretty sure you cannot just remove DMTCP and use CRIU for checkpointing. This first requires to integrate CRIU into MPICH before you can continue. At least that is what I believe.

**Comment by bethven** [comment]
ok, thanks and with OpenMPI can I use Criu and do an uncoordinated checkpoint? Excuse my questions is that I am learning about this topic and what I need to do for my thesis

**Comment by adrianreber** [comment]
No, that code was removed many years ago and has not been maintained. You need to take the code base of one of the MPIs and integrate the CRIU support yourself.

Or you can reach out to the DMTCP community to see if they support what you need.

**Comment by adrianreber** [comment]
@bethven As this has been also discussed on the CRIU mailling list I am closing it here. See discussion at https://lists.openvz.org/pipermail/criu/2018-June/041778.html.
