### ISSUE TITLE
Restore failing in pie/restorer.c set capabilities

### ISSUE THREAD

**Issue by ehmm** [checkpoint-restore/criu#499]
Hello,
I'm trying to use criu (version 3.6  -- but tried new versions to) with lxc 3.0 to restore an image of Ubuntu 14.04 and keep getting the following error on restore:

```
(00.189574)pie: 1: Error (criu/pie/restorer.c:273): Unable to restore capabil>
(00.189574)pie: 1: ities: -1
```
crit decoding of core-1.img has the following section regarding the caps:
```
                "creds": {
                    "uid": 0,
                    "gid": 0,
                    "euid": 0,
                    "egid": 0,
                    "suid": 0,
                    "sgid": 0,
                    "fsuid": 0,
                    "fsgid": 0,
                    "cap_inh": [
                        4294967295,
                        63
                    ],
                    "cap_prm": [
                        4294967295,
                        63
                    ],
                    "cap_eff": [
                        4294967295,
                        63
                    ],
                    "cap_bnd": [
                        4261216255,
                        60
                    ],
                    "secbits": 0
                }
```

I'm trying to find a way of debugging this but am having a hard time understanding why this is happening.
Running on Kernel 4.13.0 Ubuntu -- also this same scenario used to work with the same versions of lxc/criu but a slightly older Ubuntu image.

Also adding the information that the LXC container is running with uid/gid shifting.

Any hints on helping debug or if you need more information regarding the test please let me know.

Thanks,
Eh

**Comment by rst0git** [comment]
Hi @ehmm,
Would you be attach `dump.log` file?

**Comment by ehmm** [comment]
[dump_.log](https://github.com/checkpoint-restore/criu/files/2066163/dump_.log)
Attached

**Comment by rst0git** [comment]
The dump log seems OK. Would you be able to attach `restore.log`?

**Comment by ehmm** [comment]
[restore_.log](https://github.com/checkpoint-restore/criu/files/2066376/restore_.log)
attached

**Comment by rst0git** [comment]
The restore fails with this error: 
```
(00.152743)pie: 1: restoring seccomp mode 0 for 1
(00.152776)pie: 1: Error (criu/pie/restorer.c:273): Unable to restore capabilities: -1
```
It occurs because the [sys_capset()](https://github.com/checkpoint-restore/criu/blob/a70b1c797bf237f19c9e05c5078b8a822b60b417/criu/pie/restorer.c#L271) call returns -1 (`-EPERM`).
I tracked down the error to [this](https://github.com/torvalds/linux/blob/ead751507de86d90fa250431e9990a8b881f713c/kernel/capability.c#L241) condition:
```C
/* may only affect current now */
if (pid != 0 && pid != task_pid_vnr(current))
	return -EPERM;
```
@avagin Do you have an idea what might be causing the error?

**Comment by 0x7f454c46** [comment]
+Cc: @cyrillos

**Comment by cyrillos** [comment]
We definitely setup `pid = 0` in header. Maybe worth to make strace output for restore procedure?

**Comment by cyrillos** [comment]
Actually I think the problem not in the chunk @rst0git pointed, but rather
```	ret = security_capset(new, current_cred(),
			      &effective, &inheritable, &permitted);
```
either due to LSM politics or something similar.

**Comment by ehmm** [comment]
I agree wit @cyrillos , also I seem to have found the difference between my working versions and my broken ones.
My host for running/building lxc/criu is a cloud Ubuntu 18.04 machine, it seems that the working one is a slightly older Ubuntu 18.04 image with small differences in glibc/gcc. Could this be relevant?
I have the exact differences but this does seem to be quite strange

**Comment by cyrillos** [comment]
Is there a chance to disable selinux/apparmor/lsm or whatever on the machine you're testing?
