### ISSUE TITLE
CRIU Restore unsupported mount Error

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#500]
Hi I am having criu restore issue on just one machine which is a vm from azure. Docker restore fails by pointing error of unsupported mount fs. It fails to mount  on /tmp/.criu.mntns with filesystem none. The log file of restore is as follows and mount information is also attached. Can you tell how to rectify this issue.

Logs:

(00.165894)      1: mnt: Start with 0:/tmp/.criu.mntns.xTfNSu
(00.165903)      1: mnt:        Mounting aufs @/tmp/.criu.mntns.xTfNSu/12-0000000000/ (0)
(00.165922)      1: mnt: 596:/tmp/.criu.mntns.xTfNSu/12-0000000000/ private 1 shared 0 slave 0
**(00.165937)      1: mnt:        Mounting unsupported @/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/resolv.conf (0)**
(00.165940)      1: mnt:        Bind /var/lib/docker/containers/ca34c28c482b0403ddc453646838a92830f1b80930673150cfa19413a9190c0b/resolv.conf to /tmp/.criu.mntns.xTfNSu/12-0000000000/etc/resolv.conf
(00.166012)      1: mnt: 615:/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/resolv.conf private 1 shared 0 slave 0
**(00.166029)      1: mnt:        Mounting unsupported @/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hostname (0)**
(00.166032)      1: mnt:        Bind /var/lib/docker/containers/ca34c28c482b0403ddc453646838a92830f1b80930673150cfa19413a9190c0b/hostname to /tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hostname
(00.166066)      1: mnt: 616:/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hostname private 1 shared 0 slave 0
**(00.166079)      1: mnt:        Mounting unsupported @/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hosts (0)**
(00.166083)      1: mnt:        Bind /var/lib/docker/containers/ca34c28c482b0403ddc453646838a92830f1b80930673150cfa19413a9190c0b/hosts to /tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hosts
(00.166111)      1: mnt: 617:/tmp/.criu.mntns.xTfNSu/12-0000000000/etc/hosts private 1 shared 0 slave 0
(00.166124)      1: mnt:        Mounting proc @/tmp/.criu.mntns.xTfNSu/12-0000000000/proc (0)
(00.166222)      1: mnt: 597:/tmp/.criu.mntns.xTfNSu/12-0000000000/proc private 1 shared 0 slave 0
(00.166234)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/sysrq-trigger
(00.166237)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/sys
(00.166239)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/irq
(00.166242)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/fs
(00.166245)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/bus
(00.166247)      1: mnt:                Bind private /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/asound
(00.166250)      1: mnt:        Mounting proc @/tmp/.criu.mntns.xTfNSu/12-0000000000/proc/asound (0)
(00.166255)      1: mnt:        Bind /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/asound to /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/asound
(00.166271)      1: Error (criu/mount.c:2267): mnt: Can't mount at /tmp/.criu.mntns.xTfNSu/12-0000000000/proc/asound: No such file or directory
(00.166278)      1: mnt: Start with 0:/tmp/.criu.mntns.xTfNSu
(00.169680) Error (criu/mount.c:3210): mnt: Can't remove the directory /tmp/.criu.mntns.xTfNSu: No such file or directory
(00.169690) Error (criu/cr-restore.c:2266): Restoring FAILED.

**mec@mec:~$ df**
Filesystem     1K-blocks    Used Available Use% Mounted on
udev              429860       0    429860   0% /dev
tmpfs              91924     680     91244   1% /run
/dev/sda1       30308240 3034760  27257096  11% /
tmpfs             459608       0    459608   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             459608       0    459608   0% /sys/fs/cgroup
/dev/sda15        106858    3416    103443   4% /boot/efi
/dev/sdb1        4061824   16380   3819400   1% /mnt
tmpfs              91920       0     91920   0% /run/user/1000
**none              459608       0    459608   0% /tmp/.criu.mntns.xTfNSu**

**Comment by ehmm** [comment]
I had the same issue with lxc containers, not sure if you are experiencing the same thing. Notice that the mounts that fails is a bind mount for a file.

crit decode the mountpoints-*.img files in the criu directory and look for the lines:
```
"source": "/etc/hostname/"
"source": "/etc/hosts/"
"source": "/etc/resolv.conf/"
```
(They are not together each one by itself) -- if they exist then you will notice there is a slash at the end of the path. Remove it and encode the file again using crit.
I wrote a quick script to do it between checkpointing and restore.

Also as you are using docker so these files were probably created by docker and there path might change look also at the lines for these mounts in the same json that you decoded and make sure the paths are right (the source key).

You can post here the crit decoded json and I will explain specifically

**Comment by farooqte96** [comment]
Thanks for addressing this issue. I have attached cgroup.json file. Can you check whats wrong with it.


[cgroup.tar.gz](https://github.com/checkpoint-restore/criu/files/2072445/cgroup.tar.gz)

**Comment by ehmm** [comment]
I need the mountpoints json not the cgroups one please

**Comment by farooqte96** [comment]
@ehmm kindly now check in my edited comment.

**Comment by avagin** [comment]
Where did you dump this container?

**Comment by avagin** [comment]
What is a linux destribution installed in the azure VM?

**Comment by farooqte96** [comment]
It's Ubuntu 17.10( 4.15 generic) but this issue also came when checked  on Ubuntu 16.

**Comment by avagin** [comment]
Could you show output for uname -a from this azure VM?

**Comment by farooqte96** [comment]
Yes :+1: this has helped and now that error is gone but still restore is going to failed due to  error at criu/pie/restorer.c:666): wrong aio.

(00.489045) pie: 6: vdso: Runtime vdso mismatches dumpee, generate proxy
(00.489049) pie: 6: vdso: jmp: 0x7fff41179000/0xa30 -> 0x2c000/0xa30 (index 0)
(00.489056) pie: 6: vdso: jmp: 0x7fff41179000/0xf40 -> 0x2c000/0xf30 (index 1)
(00.489060) pie: 6: vdso: jmp: 0x7fff41179000/0xd50 -> 0x2c000/0xd40 (index 2)
(00.489064) pie: 6: vdso: jmp: 0x7fff41179000/0xf20 -> 0x2c000/0xf10 (index 3)
**(00.489244) pie: 6: Error (criu/pie/restorer.c:666): wrong aio: tail=0x0 head=0x0 req=0x3e old_nr=0x7f new_nr=0x47f expect=0x7f
(00.489265) pie: 6: Error (criu/pie/restorer.c:1693): Restorer fail 6**

(00.490798) pie: 1:    `- skip pagemap
(00.490804) pie: 1: vdso: Parsing at 0x7fff41179000 0x7fff4117b000
(00.490808) pie: 1: vdso: PT_LOAD p_vaddr: 0x0
(00.490812) pie: 1: vdso: DT_HASH: 0x120
(00.490816) pie: 1: vdso: DT_STRTAB: 0x2b0
(00.490819) pie: 1: vdso: DT_SYMTAB: 0x1a8
(00.490823) pie: 1: vdso: DT_STRSZ: 0x5e
(00.490854) pie: 1: vdso: DT_SYMENT: 0x18
(00.490858) pie: 1: vdso: nbucket 0x3 nchain 0xb bucket 0x7fff41179128 chain 0x7fff41179134
(00.490864) pie: 1: vdso: image [vdso] 0x7fff41179000-0x7fff4117b000 [vvar] 0x7fff41176000-0x7fff41179000
(00.490868) pie: 1: vdso: Runtime vdso mismatches dumpee, generate proxy
(00.490872) pie: 1: vdso: jmp: 0x7fff41179000/0xa30 -> 0x2c000/0xa30 (index 0)
(00.490878) pie: 1: vdso: jmp: 0x7fff41179000/0xf40 -> 0x2c000/0xf30 (index 1)
(00.490882) pie: 1: vdso: jmp: 0x7fff41179000/0xd50 -> 0x2c000/0xd40 (index 2)
(00.490886) pie: 1: vdso: jmp: 0x7fff41179000/0xf20 -> 0x2c000/0xf10 (index 3)
(00.491147) pie: 1: Restoring scheduler params 0.0.0
(00.491171) pie: 1: 1: Restored
(00.597031) mnt: Switching to new ns to clean ghosts
**(00.617190) Error (criu/cr-restore.c:2266): Restoring FAILED.**

**Comment by farooqte96** [comment]
@avagin  can you further tell whats the issue now that restore is still going failed. Thanks

**Comment by avagin** [comment]
> (00.489244) pie: 6: Error (criu/pie/restorer.c:666): wrong aio: tail=0x0 head=0x0 req=0x3e old_nr=0x7f new_nr=0x47f expect=0x7f

@tkhai Kirill, maybe you will understand what is going one here.

**Comment by rst0git** [comment]
If I understand correctly, CRIU is trying to restore asynchronous I/O and it fails because the newly created aio_context (`new_nr`) has different number of io_events from the expected (`old_nr`).

**Comment by avagin** [comment]
@rst0git, the question here is what we can do with this.

**Comment by tkhai** [comment]
@avagin: Andrey, we need kernel support for this. The last time I submitted it the aio maintainer was not much interested in this. Maybe something has changed now.

**Comment by avagin** [comment]
@tkhai Are you talking about this patch https://lwn.net/Articles/725219/ ?

**Comment by tkhai** [comment]
@avagin, this patch is for other purpose. Hm, it seems I was going to send resize patch after the wait interface is accepted, but this never happened.
