### ISSUE TITLE
Video Streaming & TCP Connection Restore

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#501]
Is it possible with criu to checkpoint a streaming video and then restore it on other host from same point we checkpointed earlier. In addition, on CRIU main page it is mentioned that we can  C/R  active TCP connections. Does anybody have suggestion or working example for C&R any video file. Thanks

**Comment by adrianreber** [comment]
Not sure if you are talking about client or server side. What I did, some years ago, was to use nginx with the rtmp-module to migrate a server streaming a video. That worked without problems.

**Comment by farooqte96** [comment]
@adrianreber  It doesn't matter whether its server side or client. I just need to checkpoint and restore some video streaming container. At present, i have successfully restored simple nginx server, so if i need to do the same which you did earlier do i just need to build some custom image for that including some video file or it involves some other steps as well. Thanks

**Comment by adrianreber** [comment]
I was not using containers at the time I did it, but I had to install nginx-rtmp-module for the actual streaming. So that nginx module plus a video file could be enough to get what you want.

**Comment by avagin** [comment]
https://asciinema.org/a/15833

**Comment by avagin** [comment]
A tcp connection can be migrated to another host only if you move an ip address from the source to the destination host. Usually, people use containers to avoid this sort of issues.
