### ISSUE TITLE
Unable to dump program which uses unix domain socket

### ISSUE THREAD

**Issue by criutest** [checkpoint-restore/criu#505]
1. Problem 
all programs which use unix domain socket fails to make dump even though parameters were added according to guide
  - command : criu dump --tree 30610 -v4 -o dump.log --tcp-established --shell-job --ext-unix-sk
  - error : (00.403026) Error (criu/sk-unix.c:801): sk unix: Can't dump half of stream unix connection.
[dump.log](https://github.com/checkpoint-restore/criu/files/2080777/dump.log)

2. 	Environment (HW:Tegra/ARMv8)
2.1. 	netstat
It seems that program was launched properly according to netstat
[netstat.log](https://github.com/checkpoint-restore/criu/files/2080786/netstat.log)
2.2. CRIU check –all
Anyhow, check return below error

Warn  (criu/cr-check.c:680): Dirty tracking is OFF. Memory snapshot will not work.
**Error (criu/cr-check.c:929): TCP_REPAIR can't be enabled for half-closed sockets**
Warn  (criu/cr-check.c:1061): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1037): UFFD is not supported
Error (criu/cr-check.c:1037): UFFD is not supported
Warn  (criu/net.c:2770): Unable to get socket network namespace
Warn  (criu/cr-check.c:1029): CRIU built without CONFIG_COMPAT - can't C/R ia32
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

Does “TCP_REPAIR can't be enabled for half-closed sockets” related with above error? 
Do I need to enable specific kernel option or patch to fix those?

However this situation is similar with below links
https://criu.org/External_UNIX_socket
https://criu.org/TCP_connection
but --ext-unix-sk option was added. it would be enough to handle this issue? or 
need to add some more parameter?

Thanks!

**Comment by avagin** [comment]
Cc: @cyrillos

**Comment by cyrillos** [comment]
> `error : (00.403026) Error (criu/sk-unix.c:801): sk unix: Can't dump half of stream unix connection.`

You seem to have to describe the peer inside process tree via `--external unix[id]` on dump and `--external unix[id]:path` on restore. Sole `--ext-unix-sk` is not enough.

**Comment by avagin** [comment]
@criutest Could you give more details what are you dumping? Looks like you are dumping a process which has a connected stream unix socket, but an owner of another side of this connection isn't dumped.

You can use lsof and ss tools to get more information about this socket.
