### ISSUE TITLE
Pass options from docker cli to criu

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#506]
Hi,

I am testing the docker checkpoint/restore feature based on `Docker version 17.03.1-ce`, I need pass some options from docker cli to criu, like `--tcp-close` when restore the docker, any solutions?

**Comment by adrianreber** [comment]
Currently no solution. We recently continued the discussion how to handle configuration files for the RPC case: https://lists.openvz.org/pipermail/criu/2018-May/041211.html

As docker is using runc and runc is using CRIU via RPC, that would be the solution for you. I just need to find the time to rewrite the patches.

**Comment by zhouxinyu** [comment]
Thanks @adrianreber , I inserted the options in `cr_service.c#restore_using_req` method as a workaround solution, looking forward to your official solution~

**Comment by adrianreber** [comment]
Also see #278

**Comment by adrianreber** [comment]
This has been merged into the development branch : https://github.com/checkpoint-restore/criu/commit/d1439a67468d86e73b5df275dd352258fd8d5187

**Comment by adrianreber** [comment]
Available since CRIU 3.11. Needs https://github.com/opencontainers/runc/pull/1933 to be merged. CRIU parts are finished though.
