### ISSUE TITLE
docker start checkpoint failed

### ISSUE THREAD

**Issue by rowshan** [checkpoint-restore/criu#510]
Any idea about the error below how to solve it , thanks in advance
`$ docker start --checkpoint  checkpoint7 reqctr2  `

`Error response from daemon: failed to retrieve OCI runtime container pid: open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/be72ca2202dd37307568caff86e271ee1ab198419a58de92b7fa91bc9ba1b7d8/init.pid: no such file or directory: unknown
`

**Comment by rst0git** [comment]
The same issue seems to be reported here as well moby/moby#35691 (not fixed yet)

**Comment by rowshan** [comment]
@Prat041192 we need to track this issue for criu

**Comment by avagin** [comment]
> The same issue seems to be reported here: moby/moby#35691 (not fixed yet)

> @Prat041192 we need to track this issue for criu

Here is nothing wrong with CRIU. Docker was moved on to a new version of containerd and forgot to pass --empty-ns network to runc.
https://github.com/containerd/containerd/pull/2425

**Comment by Prat041192** [comment]
@avagin Currently we do have any solution to this problem. Right? 
Is there any work around that can be tried?

**Comment by avagin** [comment]
@Prat041192 I can try to build packages with all required fixes. Will it work for you?

**Comment by Prat041192** [comment]
That would be great, if possible. @avagin. Thanks in advance.

**Comment by iprimo** [comment]
Hi @avagin, Thanks for all your effort to resolve the Docker related issue. I appreciate if you could share that package with me too. Many thanks in advance.

**Comment by Prat041192** [comment]
Hey @avagin, Is the package you were talking about ready?

**Comment by avagin** [comment]
I have prepared a git repo with all fixes:
```
$ git clone https://github.com:avagin/docker-ce.git -t cr-20180728
```
If you use debian or ubuntu, you need to run "make dep"
```
$ make dep
```
If you use fedora or redhat, you need to run "make rpm"
```
$ make rpm
```

**Comment by Prat041192** [comment]
Thanks @avagin : I will try this and get back to you, if in case of any issue.

**Comment by thomashusa** [comment]
I had the same issue using my Linux distribution's version of docker (18.09.0), but it worked after I tired building docker/moby from git, so I think this may be fixed.

**Comment by xuchenCN** [comment]
@thomashusa Could you tell me which version are you built ? thanks :)

**Comment by avagin** [comment]
https://github.com/moby/moby/pull/37710
