### ISSUE TITLE
Does criu work well with ubuntu 18.04?

### ISSUE THREAD

**Issue by yufeixiong** [checkpoint-restore/criu#511]
CRIU doesn't work well with ubuntu 18.04.
It cannot restore  well.

signal 11 (SEGV) was caught by top, please
see http://www.debian.org/Bugs/Reporting

**Comment by adrianreber** [comment]
@yufeixiong can you provide more information? The version of CRIU, how you used it, log files, a more detailed error description.

**Comment by yufeixiong** [comment]
I think it may be the new release of ubuntu.
dumping is seccessful. When restoring, I get the following message: 
signal 11 (SEGV) was caught by top, please
see http://www.debian.org/Bugs/Reporting

ubuntu 18.04

**Comment by adrianreber** [comment]
Sorry, but you still did not provide any helpful information.

Please provide kernel version and criu version and logs of dump and restore. Also the commands you used to dump and restore the process.

**Comment by avagin** [comment]
What docker version do you use? C/R in Docker CE 18.05 is broken.
https://github.com/containerd/containerd/pull/2425
