### ISSUE TITLE
CRIU Restore failed due to bad restore size

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#515]
I followed  this example (https://technology.amis.nl/2018/04/08/first-steps-with-docker-checkpoint-to-create-and-restore-snapshots-of-running-containers/) to checkpoint and restore a node application. Checkpoint and restore works when done on same host but when restore is performed on remote host , restore failed with error mentioned below as bold. I have tried to ignore this error, but  still container doesn't get up from checkpoint. Any clue to get rid of this issue?

**source host:**
lab3: ~ $ docker run -d --name reqctr2 -e "GIT_URL=https://github.com/lucasjellema/microservices-choreography-kubernetes-workshop-june2017" -e "APP_PORT=8080" -p 8005:8080 -e "APP_HOME=part1"  -e "APP_STARTUP=requestCounter.js"   lucasjellema/node-app-runner
lab3: ~ $ docker checkpoint create reqctr2 checkpoint1
lab3: ~ $ docker start --checkpoint checkpoint1 reqctr2
lab3: ~ $ scp checkpoint1.tar.gz lab4:/tmp/

**Destination host:**
lab4: ~ $ docker create --name reqctr2 -e "GIT_URL=https://github.com/lucasjellema/microservices-choreography-kubernetes-workshop-june2017" -e "APP_PORT=8080" -p 8005:8080 -e "APP_HOME=part1"  -e "APP_STARTUP=requestCounter.js"   lucasjellema/node-app-runner
3b67c3a7d67bd904c5bc05fbfb9ee94956e0da7ce5f36e0e804d0cbe1f2af572
lab4: ~ $ sudo tar -zxf /tmp/checkpoint1.tar.gz -C /var/lib/docker/containers/3b67c3a7d67bd904c5bc05fbfb9ee94956e0da7ce5f36e0e804d0cbe1f2af572/checkpoints/
lab4: ~ $ docker start --checkpoint checkpoint1 reqctr2
Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/containers/3b67c3a7d67bd904c5bc05fbfb9ee94956e0da7ce5f36e0e804d0cbe1f2af572/checkpoints/checkpoint1/criu.work/restore-2018-06-20T10:29:14.082891257+03:00/restore.log

**Restore logs:**

**(00.331573)     71: Error (criu/files-reg.c:1673): File usr/local/bin/node has bad size 35443473 (expect 37318160)**
**(00.331580)     71: Error (criu/mem.c:1202): `- Can't open vma**
(00.331583)      1: Opening 0x007f6d00692000-0x007f6d00891000 0x00000000003000 (41) vma
(00.331587)      1: Opening 0x007f6d00891000-0x007f6d00892000 0x00000000002000 (41) vma
(00.331590)      1: Opening 0x007f6d00892000-0x007f6d00893000 0x00000000003000 (41) vma
(00.331593)      1: Opening 0x007f6d00893000-0x007f6d008b9000 0000000000000000 (20000041) vma
(00.331610)      1: Opening 0x007f6d008b9000-0x007f6d00ab8000 0x00000000026000 (41) vma
(00.331614)      1: Opening 0x007f6d00ab8000-0x007f6d00abc000 0x00000000025000 (41) vma
(00.331617)      1: Opening 0x007f6d00abc000-0x007f6d00abd000 0x00000000029000 (41) vma
(00.331619)      1: Opening 0x007f6d00abd000-0x007f6d00ae1000 0000000000000000 (20000041) vma
(00.331635)      1: Opening 0x007f6d00ae1000-0x007f6d00ce0000 0x00000000024000 (41) vma
(00.331639)      1: Opening 0x007f6d00ce0000-0x007f6d00ce1000 0x00000000023000 (41) vma
(00.331642)      1: Opening 0x007f6d00ce1000-0x007f6d00ce2000 0x00000000024000 (41) vma
(00.331644)      1: Opening 0x007f6d00ce2000-0x007f6d00d02000 0000000000000000 (20000041) vma
(00.331660)      1: Opening 0x007f6d00f02000-0x007f6d00f03000 0x00000000020000 (41) vma
(00.331664)      1: Opening 0x007f6d00f03000-0x007f6d00f04000 0x00000000021000 (41) vma
(00.331678)      1: Closing inherit fd 3 -> pipe:[564016]
(00.331683)      1: Closing inherit fd 4 -> pipe:[564017]
(00.331687)      1: Closing inherit fd 5 -> pipe:[564018]
(00.331724)      1: `- render 17 iovs (0x400000:4096...)
(00.331738)      1: Restore via sigreturn
(00.331902)      1: Error (criu/cr-restore.c:1387): 71 exited, status=1
(00.411718) mnt: Switching to new ns to clean ghosts
(00.439775) Error (criu/cr-restore.c:2266): Restoring FAILED.

Docker version: 17.06.2-ee-13
criu version: 3.9

**Comment by adrianreber** [comment]
The problem is that the files on disk for the program which is checkpointed and restored (usr/local/bin/node) differs in size:

```(00.331573) 71: Error (criu/files-reg.c:1673): File usr/local/bin/node has bad size 35443473 (expect 37318160)```

So the file is about 2MB smaller (I think) and the executables and libraries on disk have to be the exact same files (thus same size at least). If the files are differently the restored process will fail at some point when it tries to load information or functionality from disk which is not yet in memory.

So CRIU does a minimal check to avoid failures due to different executables and libraries by comparing the size. This check is not perfect but a good indication.

In your case the size is different which means that the binary (usr/local/bin/node) is different and even if the restore would work, your restored process will probably fail at some point.

**Comment by farooqte96** [comment]
@adrianreber Yes its due to binary difference but i have used the same image on destination as on source. Infact i used docker load < source_image.tar but still doesn't understand why there is difference.

**Comment by adrianreber** [comment]
If docker cannot provide you with two identical filesystems then this is a docker bug (from CRIU's point of view).

You could verify the files by entering each container and do 'ls' on it and 'md5sum'. If it is different then you need to figure out why it is different. Maybe one of the image layers is different. There is nothing CRIU can do about it at this point.

**Comment by farooqte96** [comment]
I have checked source and destination containers md5sum, it is found to be same.

lab3:~$ docker exec -it reqctr2 bash
root@404864dbb038:/code# ls
app  bootstrap.sh
root@404864dbb038:/code# md5sum bootstrap.sh
**6845fc88f5c3f3178a6a30fc1787d530  bootstrap.sh**

lab4: docker start --checkpoint reqctr2 reqctr2
lab4# docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                    NAMES
66ad9cbc613e        lucasjellema/node-app-runner   "/code/bootstrap.sh"   5 minutes ago       Up 21 seconds       0.0.0.0:8005->8080/tcp   reqctr2
lab4# docker exec -it reqctr2 bash
root@404864dbb038:/code# ls
app  bootstrap.sh
root@404864dbb038:/code# md5sum bootstrap.sh
**6845fc88f5c3f3178a6a30fc1787d530  bootstrap.sh**

**Comment by adrianreber** [comment]
You need to look at ```usr/local/bin/node```. That is the file CRIU is complaining about.

**Comment by farooqte96** [comment]
This issue was gone by rebuilding the image. so going to close this. Thanks for your support
