### ISSUE TITLE
CRIU Restore Can't bind inet socket back

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#516]
Hi 
I am trying to restore a 2048 service (https://gist.github.com/ondrejmo/6f7e7d0333098686c65d). It is successfully restored when i just start at source and checkpoint it without playing it. But if this game is played, then restore fails with following logs.

(00.303255)      1: Found fd 0 (id pipe:[67381]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.303256)      8:     Restore: family 2 type 1 proto 6 port 80 state 1 src_addr 172.17.0.3
(00.303268)      1: Inherit fd 0 moved to 3 to resolve clash
(00.303276)      1:             Create fd for 0
(00.303281)      1:             Send fd 0 to /crtools-fd-8
(00.303295)      8: Restoring TCP connection
(00.303300)      1:             Creating pipe pipe_id=0x10736 id=0x10
(00.303304)      8: Restoring TCP connection id 17 ino 10cba
(00.303308)      1: Found id pipe:[67382] (fd 1) in inherit fd list
(00.303315)      1: File pipe:[67382] will be restored from fd 4 dumped from inherit fd 1
(00.303331)      1: Found fd 1 (id pipe:[67382]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.303337)      1: Inherit fd 1 moved to 4 to resolve clash
(00.303342)      1:             Create fd for 1
(00.303347)      1:             Send fd 1 to /crtools-fd-8
(00.303354)      1:             Creating pipe pipe_id=0x10737 id=0x11
(**00.303355)      8: Error (soccr/soccr.c:497): Can't bind inet socket back: Cannot assign requested address**
(00.303360)      1: Found id pipe:[67383] (fd 2) in inherit fd list
(00.303368)      1: File pipe:[67383] will be restored from fd 5 dumped from inherit fd 2
(00.303380)      1: Found fd 2 (id pipe:[67383]) in inherit fd list (caller inherit_fd_resolve_clash)
(00.303385)      1: Inherit fd 2 moved to 5 to resolve clash
(00.303384)      8: Error (criu/files.c:1194): Unable to open fd=3 id=0x17
(00.303390)      1:             Create fd for 2

**Comment by adrianreber** [comment]
I am guessing, but if you are playing the game a TCP connection is open and the restored container has a different IP address. Can you check the IP addresses of the dumped and the restored container?

CRIU can only restore TCP connections if the IP address is the same.

**Comment by farooqte96** [comment]
yes IP addresses were different, now get it working. One more thing to ask that  right after playing it starts from zero state on destination. I started container with this command.

 docker run -d --name 2048 -p 2048:80/tcp -v `pwd`/2048/:/usr/share/nginx/html/ nginx:latest

so this volume tag persists the data but  this is not transferring state information to destination. Therefore when i restart game on destination, it starts from zero or state which is saved at this volume directory.

**Comment by adrianreber** [comment]
Not sure I understand what you are asking.

You are mounting a persistent volume in the container on the source system and not on the destination system?

**Comment by farooqte96** [comment]
Mounted same volume on both sides. After migration container starts from mounted volume from zero state instead of checkpointed state, so it shows that container start follows volume state as compared to checkpoint state.

**Comment by adrianreber** [comment]
This is difficult to answer without knowing if the application stores the state in memory or on disk (mounted persistent volume).

You really need to include more details in your reports. I can only guess. But this is either a docker or a problem of the application. This is unrelated to CRIU.

If you say, 'Mounted same volume on both sides', did you sync before restarting the container. What does it contain.

**Comment by farooqte96** [comment]
Yes this is not CRIU problem now and it looks that application is storing state  though a mounted volume from a directory /2048 on docker host  to container directory /usr/share/nginx/html/

**Comment by adrianreber** [comment]
But then it should be fixable by running rsync before starting the container for that directory from source to destination.

**Comment by adrianreber** [comment]
Can this be closed? Does it work now?

**Comment by farooqte96** [comment]
This didnt work for me. It has some issue with image files. I looked at those files but still game starts with persistent information from disk and i don't know where its storing that information. If you want to close the issue, you can.

**Comment by adrianreber** [comment]
Closing this now. If you find a solution please let us know.
