### ISSUE TITLE
Docker checkpoint size Limitation ?

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#518]
In previous issue(https://github.com/checkpoint-restore/criu/issues/491), we discussed that criu cannot checkpoint a container with large image size (around 670MB and checkpoint size greater than 4MB) but today i have checkpointed containers with  large image size (beyond 1GB with  checkpoited image file around 500MB)without making any modifications to original criu files .

Can anybody tell me whether it was criu limitation for just a specific type of image (johnson163/hermes) or error occured due to default behavior of criu. 

yx-lab3# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
rchdeeplearning/recognitionservice   latest              523caa0576be        7 months ago        1.68GB
yx-lab3# docker run -d --name object rchdeeplearning/recognitionservice
559fc2aa52d3f83df175bee22661732ba0d3ea6f1d8bb03116403ce3ad94c038
yx-lab3# docker checkpoint create object object
object
yx-lab3# cd /var/lib/docker/containers/559fc2aa52d3f83df175bee22661732ba0d3ea6f1d8bb03116403ce3ad94c038/checkpoints
yx-lab3# ls
object
yx-lab3# du -h object
504K    object/criu.work
**525M    object**

**Comment by 0x7f454c46** [comment]
As far as I glanced, in #491 you discussed limit for ghost files.
https://criu.org/Invisible_files

**Comment by farooqte96** [comment]
@0x7f454c46 yes i get ghost-file size limit increaed error in that case. But now i dont get these errors. I want to know what was the reason of that error because someone mentioned before that criu follows 4mb deafult limit for checkpoint but now i find that claim is not correct.

**Comment by avagin** [comment]
This limit is only for ghost files:
https://criu.org/Invisible_files

Usually, the major part of a checkpoint size is a memory content, but criu can dump or migrate memory iteratively without stopping processes. Ghost files can be dumped only when processes are frozen, so there is this limit, which helps us to control a process downtime.

**Comment by adrianreber** [comment]
@farooqte96: I am closing this as I would say that your questions are answered: ghost files size limit is something different than the memory size of a process to dump.

Just as an additional data point: I have dumped processes which were using 64GB without problems.
