### ISSUE TITLE
Checkpointing lxc container failed (do_dump: 1192 dump signaled with 11)

### ISSUE THREAD

**Issue by psinha01** [checkpoint-restore/criu#519]
* Distribution: Ubuntu (Artful)
 * Distribution version: 17.10
  * The output of
     * `criu --version`
Version: 3.5
GitID: v3.5-95-g62cc04df
     * `lxc-start --version`
2.1.0
     * `uname -a`
Linux o19 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   
I am trying to checkpoint/restore an lxc container. I am following the steps given on CRIU's [website](https://criu.org/LXC)
When I enter the command:
`sudo lxc-checkpoint -s -D /tmp/checkpoint -n u1
`
It shows the following error:
```
The configuration file contains legacy configuration keys.
Please update your configuration file!
lxc-checkpoint: u1: criu.c: do_dump: 1192 dump signaled with 11
lxc-checkpoint: u1: criu.c: do_dump: 1200 criu output: 
Checkpointing u1 failed.
```
In above error message, the complain about "legacy configuration keys" is because of the following update suggested by [CRIU](https://criu.org/LXC) in the container's config file:
```
cat | sudo tee -a /var/lib/lxc/u1/config << EOF
# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
EOF
```
I am wondering if the checkpointing fails because of LXC or CRIU. Does it have anything to do with lxc complaining about legacy configuration keys?

Here is the dmesg outpout:

`[ 3817.829241] lxc-checkpoint[18621]: segfault at 2390 ip 00007fb6a146446f sp 00007ffc4b59bd90 error 4 in liblxc.so.1.3.0[7fb6a1436000+aa000]`

Any help? Thank you.

**Comment by 0x7f454c46** [comment]
It looks more like lxc fail: `segfault in liblxc.so`
But I'm not sure about the reason.
Probably worth debugging.

**Comment by avagin** [comment]
Cc: @brauner

**Comment by adrianreber** [comment]
Closing. Thanks @brauner

**Comment by psinha01** [comment]
Thank you everyone.
