### ISSUE TITLE
Support C/R of selinux-managed tasks

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#52]
Pulled from criu.org/Todo

Selinux imposes more restrictions on the stuff we typically do. We're currently able to c/r seccomp-ed tasks (in strict mode), apparmor-controlled ones and have seccomp-filter work in progress.

**Comment by rst0git** [comment]
I think that this feature was implemented with https://github.com/checkpoint-restore/criu/pull/648, https://github.com/checkpoint-restore/criu/pull/657, https://github.com/checkpoint-restore/criu/pull/685.

**Comment by adrianreber** [comment]
Yes, this is done. Closing.
