### ISSUE TITLE
Regression since release 3.8

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#520]
Starting with release 3.8 I see errors in runc using CRIU with read-only root.

(00.098979) mnt: 	217: 3a:/ @ ./sys/fs/cgroup
(00.098981) mnt: Mount is not fully visible ./sys/fs/cgroup
(00.099005) mnt: 	mount has children ./sys/fs/cgroup
(00.099022) Error (criu/mount.c:1095): mnt: Can't create a temporary directory: Read-only file system
(00.099042) Error (criu/mount.c:1545): mnt: Unable to dump a file system for 217:./sys/fs/cgroup

If runc would upgrade their criu version in CI it would also fail there. Using CRIU 3.7 this error does not happen.

One workaround is to tell runc to mount /tmp as read-write tmpfs and then it works.

**Comment by avagin** [comment]
@adrianreber Could you bisect a commit where it was broken?

**Comment by adrianreber** [comment]
git bisect tells me

b6cfb1ce29485186de32ff5a30a56b471d5cb884 is the first bad commit

```
commit b6cfb1ce29485186de32ff5a30a56b471d5cb884
Author: Pavel Tikhomirov <ptikhomirov@virtuozzo.com>
Date:   Fri Dec 22 11:22:26 2017 +0300

    mount: make open_mountpoint handle overmouts properly```

**Comment by adrianreber** [comment]
I am using runc's test suite to trigger this error:

bats -t tests/integration/checkpoint.bats

This is, as always with my tests, on the CentOS/RHEL kernel. So there might also be something related to that kernel.

**Comment by avagin** [comment]
I think we need something like this https://github.com/avagin/criu/commit/b264318361d11cd90b0ee95c987c69128a852fa3

**Comment by Snorch** [comment]
>  I think we need something like this avagin/criu@b264318
I don't think so.

First, change in open_mountpoint actually does not change anything AFAICS, as if "!mnt_is_overmounted(pm)" is true we just get clean fd or go to err and "if (fd < 0) {" is never entered, if "!mnt_is_overmounted(pm)" is false then "if (fd < 0) {" check is always entered, we had the same with just "else".

Second, ns_open_mountpoint should return clean mount, nothing protects us from having mount pm with children in open_mountpoint's "else" path (mount can both have children an be overmounted).

Not yet sure how to fix it...

**Comment by Snorch** [comment]
Ok, I see what you mean, when last process exits mount ns all mounts in it are destroyed so if we have opened mount in it the mount will be cleaned. But isn't that racy? What if we will still have mounts when using these "nscleaned" mount?

**Comment by Snorch** [comment]
It is not, when last process exits mntns via setns we have:
SyS_setns->switch_task_namespaces->free_nsproxy->put_mnt_ns->umount_tree->drop_collected_mounts->umount_tree:

        /* Hide the mounts from mnt_mounts */
        list_for_each_entry(p, &tmp_list, mnt_list) {
                list_del_init(&p->mnt_child);
        }

That means mount loses children as at the same time we return back to right mntns. Will send a fixing patch.
