### ISSUE TITLE
Is it possible migrate an application inside a container to another container?

### ISSUE THREAD

**Issue by stevepp** [checkpoint-restore/criu#521]
Hi everyone,
I know about how to do live migration of a LXC and docker container using CRIU.  However, is it possible to migrate a single application from a LXC container to another one. I just want to migrate a process instead of the entire container.

I start with installing CRIU into each container. However, the CRIU compilation from source failed. Also, the CRIU version installed directly from Ubuntu package does not work at all. 

Does anyone have similar experience installing CRIU into a LXC container and use it to migrate a single process?

**Comment by adrianreber** [comment]
I would say this could work. I have not tried it myself, but it could work.

What kernel are you using? What is running inside the container? Which CRIU version is in the container? How does it fail?

**Comment by stevepp** [comment]
@adrianreber 
I managed to compile criu from source code. My host OS is Ubuntu 16.04 with kernel version 4.8.0-36. I use LXC to create a container running Ubuntu 16.04. Nothing essential runs insides the container for now. 

After cloning criu source from its git repository and compiling it, I tried to check whether it works. However, everything fails with the following message. When running "sudo criu check", I got the output:

Warn  (criu/kerndat.c:792): Can't load /run/criu.kdat
Error (criu/util.c:803): exited, status=1
Error (criu/util.c:803): exited, status=1
Warn  (criu/net.c:2770): Unable to get socket network namespace
Error (criu/tun.c:82): Unable to create tun: No such file or directory

I didn't see error output from the compilation process. Do you have any pointer why criu fails to work in the container?

**Comment by adrianreber** [comment]
Is your container running unprivileged? Not sure if CRIU can run in such a container.

**Comment by stevepp** [comment]
I am using privileged container actually.

**Comment by brauner** [comment]
Is this with LXC or LXD?

**Comment by stevepp** [comment]
Hi, this is with LXC. I am wondering if this is caused by the default security profiles configured by LXC.

**Comment by adrianreber** [comment]
Could you run 'criu check -v4'?

**Comment by stevepp** [comment]
Running 'criu check -v4' gives exactly the same output.

**Comment by stevepp** [comment]
I disabled the LXC security mechanisms such as apparmor and the error still exists. Besides, I found that my container does not have this file "/run/criu.kdat"

**Comment by brauner** [comment]
Can you set `lxc.cap.drop =` in the container's config.

**Comment by adrianreber** [comment]
/run/criu.kdat is created after the first successful CRIU run

**Comment by stevepp** [comment]
@brauner Just restarting the container will set the new capability configuration? No need to re-create the container?

**Comment by stevepp** [comment]
Instead of compiling from source, I tried to install CRIU into the LXC container directly from the Ubuntu software repository. After running "sudo criu check", I got the following error output:

Error (criu/cr-check.c:141): sys/kernel/ns_last_pid sysctl is inaccessible: Read-only file system
Does not look good.

It is complaining the file system is read only.

**Comment by adrianreber** [comment]
So this is probably one of LXC security features to make things in /proc read-only.

Before guessing more let's ask @avagin: Can this actually work? Using CRIU in a container?

**Comment by brauner** [comment]
So we usually mounts parts of `/proc` read-only for security reasons. In an unprivileged container you can safely set `lxc.mount.auto = proc:rw` but a privileged container should set at least `proc:mixed`.

**Comment by stevepp** [comment]
Thanks. I set the mount options in the container config file. Now "criu check" says "Looks good". However, the criu dump of a simple process still failed. Here is the log of running "criu dump". Any idea what may cause the problem here?

(00.000057) Probing sock diag modules
(00.000135) Done probing
(00.000445) Error (criu/util.c:652): exec failed: No such file or directory
(00.003153) Error (criu/util.c:666): exited, status=1
(00.003982) Error (criu/util.c:652): exec failed: No such file or directory
(00.004110) Error (criu/util.c:666): exited, status=1
(00.004124) ========================================
(00.004126) Dumping processes (pid: 250)
(00.004128) ========================================
(00.004191) Pagemap is fully functional
(00.004225) Found anon-shmem device at 5
(00.004231) Reset 322's dirty tracking
(00.004265)  ... done
(00.004295) Dirty track supported on kernel
sh: 1: iptables: not found
(00.005966) irmap: Searching irmap cache in work dir
(00.005984) No irmap-cache image
(00.005987) irmap: Searching irmap cache in parent
(00.005992) irmap: No irmap cache
(00.006100) cg-prop: Parsing controller "cpu"
(00.006110) cg-prop: 	Strategy "replace"
(00.006114) cg-prop: 	Property "cpu.shares"
(00.006117) cg-prop: 	Property "cpu.cfs_period_us"
(00.006119) cg-prop: 	Property "cpu.cfs_quota_us"
(00.006122) cg-prop: 	Property "cpu.rt_period_us"
(00.006124) cg-prop: 	Property "cpu.rt_runtime_us"
(00.006126) cg-prop: Parsing controller "memory"
(00.006129) cg-prop: 	Strategy "replace"
(00.006131) cg-prop: 	Property "memory.limit_in_bytes"
(00.006133) cg-prop: 	Property "memory.memsw.limit_in_bytes"
(00.006136) cg-prop: 	Property "memory.swappiness"
(00.006138) cg-prop: 	Property "memory.soft_limit_in_bytes"
(00.006140) cg-prop: 	Property "memory.move_charge_at_immigrate"
(00.006143) cg-prop: 	Property "memory.oom_control"
(00.006145) cg-prop: 	Property "memory.use_hierarchy"
(00.006147) cg-prop: 	Property "memory.kmem.limit_in_bytes"
(00.006149) cg-prop: 	Property "memory.kmem.tcp.limit_in_bytes"
(00.006152) cg-prop: Parsing controller "cpuset"
(00.006154) cg-prop: 	Strategy "replace"
(00.006157) cg-prop: 	Property "cpuset.cpus"
(00.006159) cg-prop: 	Property "cpuset.mems"
(00.006161) cg-prop: 	Property "cpuset.memory_migrate"
(00.006163) cg-prop: 	Property "cpuset.cpu_exclusive"
(00.006165) cg-prop: 	Property "cpuset.mem_exclusive"
(00.006168) cg-prop: 	Property "cpuset.mem_hardwall"
(00.006170) cg-prop: 	Property "cpuset.memory_spread_page"
(00.006172) cg-prop: 	Property "cpuset.memory_spread_slab"
(00.006175) cg-prop: 	Property "cpuset.sched_load_balance"
(00.006177) cg-prop: 	Property "cpuset.sched_relax_domain_level"
(00.006179) cg-prop: Parsing controller "blkio"
(00.006181) cg-prop: 	Strategy "replace"
(00.006184) cg-prop: 	Property "blkio.weight"
(00.006186) cg-prop: Parsing controller "freezer"
(00.006188) cg-prop: 	Strategy "replace"
(00.006191) cg-prop: Parsing controller "perf_event"
(00.006193) cg-prop: 	Strategy "replace"
(00.006196) cg-prop: Parsing controller "net_cls"
(00.006198) cg-prop: 	Strategy "replace"
(00.006200) cg-prop: 	Property "net_cls.classid"
(00.006203) cg-prop: Parsing controller "net_prio"
(00.006205) cg-prop: 	Strategy "replace"
(00.006207) cg-prop: 	Property "net_prio.ifpriomap"
(00.006210) cg-prop: Parsing controller "pids"
(00.006212) cg-prop: 	Strategy "replace"
(00.006214) cg-prop: 	Property "pids.max"
(00.006216) cg-prop: Parsing controller "devices"
(00.006219) cg-prop: 	Strategy "replace"
(00.006221) cg-prop: 	Property "devices.list"
(00.006262) Perparing image inventory (version 1)
(00.006284) Add pid ns 1 pid 322
(00.006295) Add net ns 2 pid 322
(00.006301) Add ipc ns 3 pid 322
(00.006306) Add uts ns 4 pid 322
(00.006311) Add mnt ns 5 pid 322
(00.006319) Add user ns 6 pid 322
(00.006327) Add cgroup ns 7 pid 322
(00.006329) cg: Dumping cgroups for 322
(00.006351) cg: Set 1 is criu one
(00.006457) Error (criu/ptrace.c:64): suspending seccomp failed: Operation not permitted
(00.006470) Unlock network
(00.006473) Unfreezing tasks into 1
(00.006476) Error (criu/ptrace.c:54): Unable to detach from 250: No such process
(00.006487) Error (criu/cr-dump.c:1628): Dumping FAILED.

**Comment by avagin** [comment]
Could you run "cat /proc/self//status" in a container and show output?

**Comment by stevepp** [comment]
Turns out it is caused by seccomp. As a workaround I disabled seccomp and now it can checkpoint/restore simple shell jobs. I will test other more realistic server applications to see whether it still works.
