### ISSUE TITLE
page-server problem

### ISSUE THREAD

**Issue by yufeixiong** [checkpoint-restore/criu#522]
I run command` ./criu page-server -D d/ps/ -o ps.log -v4 --port 1234` on dest, and command `criu dump -t <pid> -D d/dump/ -o dmp.log --page-server --address dest_ip --port 1234 --shell-job` on src.
I merge the checkpoint files. however, it only works on src, failed on dest.Why?
linux : ubuntu 18.04
criu : 3.9
here follows the rst.log on dest:
(00.000060) Version: 3.9 (gitid v3.9)
(00.000085) Running on linux Linux 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64
(00.000939) cpu: fpu:1 fxsr:1 xsave:1
(00.000980) kernel pid_max=131072
(00.000983) Reading image tree
(00.001010) Add mnt ns 5 pid 12432
(00.001015) Add net ns 2 pid 12432
(00.001024) pstree pid_max=12596
(00.001028) Migrating process tree (GID 12432->12436 SID 11971->1989)
(00.001031) Will restore in 0 namespaces
(00.001032) NS mask to use 0
(00.001051) Collecting 37/54 (flags 2)
(00.001066) Collected [bin/bash] ID 0x1
(00.001070) Collected [usr/lib/locale/locale-archive] ID 0x2
(00.001072) Collected [lib/x86_64-linux-gnu/libc-2.27.so] ID 0x3
(00.001075) Collected [lib/x86_64-linux-gnu/libdl-2.27.so] ID 0x4
(00.001077) Collected [lib/x86_64-linux-gnu/libtinfo.so.5.9] ID 0x5
(00.001079) Collected [lib/x86_64-linux-gnu/ld-2.27.so] ID 0x6
(00.001083) Collected [usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache] ID 0x7
(00.001085) Collected [dev/pts/1] ID 0x9
(00.001088) Collected [home/alan/tt.sh] ID 0xa
(00.001091) Collected [home/alan] ID 0xb
(00.001093) Collected [.] ID 0xc
(00.001095) Collected [bin/sleep] ID 0xd
(00.001098)  `- ... done
(00.001099) Collecting 43/59 (flags 0)
(00.001103) No remap-fpath.img image
(00.001104)  `- ... done
(00.001122) No cgroup.img image
(00.001128) Running pre-restore scripts
(00.001156) No mountpoints-5.img image
(00.001158) mnt: Reading mountpoint images (id 5 pid 12432)
(00.001203) Forking task with 12432 pid (flags 0x0)
(00.010236) PID: real 12432 virt 12432
(00.010488)  12432: cg: Cgroups 1 inherited from parent
(00.010557)  12432: Calling restore_sid() for init
(00.010613)  12432: Collecting 41/37 (flags 2)
(00.010846)  12432: tty: Collected tty ID 0x8 (pts)
(00.010865)  12432:  `- ... done
(00.010869)  12432: Collecting 42/51 (flags 0)
(00.010888)  12432: No tty-data.img image
(00.010892)  12432:  `- ... done
(00.010894)  12432: Restoring namespaces 12432 flags 0x0
(00.010907)  12432: Preparing info about shared resources
(00.010931)  12432: No seccomp.img image
(00.010941)  12432: Collecting 45/38 (flags 0)
(00.010953)  12432: No filelocks.img image
(00.010955)  12432:  `- ... done
(00.010957)  12432: Collecting 39/27 (flags 0)
(00.010962)  12432: No pipes-data.img image
(00.010965)  12432:  `- ... done
(00.010967)  12432: Collecting 40/27 (flags 0)
(00.010972)  12432: No fifo-data.img image
(00.010974)  12432:  `- ... done
(00.010976)  12432: Collecting 38/60 (flags 0)
(00.010981)  12432: No sk-queues.img image
(00.010983)  12432:  `- ... done
(00.011017)  12432: Found 29 VMAs in image
(00.011020)  12432: vma 0x5585d5a5b000 0x5585d5b5f000
(00.011022)  12432: vma 0x5585d5d5e000 0x5585d5d62000
(00.011024)  12432: vma 0x5585d5d62000 0x5585d5d6b000
(00.011025)  12432: vma 0x5585d5d6b000 0x5585d5d75000
(00.011027)  12432: vma 0x5585d6a38000 0x5585d6a59000
(00.011029)  12432: vma 0x7f35b35bd000 0x7f35b3f8c000
(00.011030)  12432: vma 0x7f35b3f8c000 0x7f35b4173000
(00.011032)  12432: vma 0x7f35b4173000 0x7f35b4373000
(00.011033)  12432: vma 0x7f35b4373000 0x7f35b4377000
(00.011035)  12432: vma 0x7f35b4377000 0x7f35b4379000
(00.011036)  12432: vma 0x7f35b4379000 0x7f35b437d000
(00.011038)  12432: vma 0x7f35b437d000 0x7f35b4380000
(00.011039)  12432: vma 0x7f35b4380000 0x7f35b457f000
(00.011041)  12432: vma 0x7f35b457f000 0x7f35b4580000
(00.011042)  12432: vma 0x7f35b4580000 0x7f35b4581000
(00.011044)  12432: vma 0x7f35b4581000 0x7f35b45a6000
(00.011046)  12432: vma 0x7f35b45a6000 0x7f35b47a6000
(00.011048)  12432: vma 0x7f35b47a6000 0x7f35b47aa000
(00.011051)  12432: vma 0x7f35b47aa000 0x7f35b47ab000
(00.011053)  12432: vma 0x7f35b47ab000 0x7f35b47d2000
(00.011070)  12432: vma 0x7f35b49b8000 0x7f35b49bd000
(00.011075)  12432: vma 0x7f35b49cb000 0x7f35b49d2000
(00.011076)  12432: vma 0x7f35b49d2000 0x7f35b49d3000
(00.011078)  12432: vma 0x7f35b49d3000 0x7f35b49d4000
(00.011080)  12432: vma 0x7f35b49d4000 0x7f35b49d5000
(00.011081)  12432: vma 0x7fff7a500000 0x7fff7a521000
(00.011086)  12432: vma 0x7fff7a56f000 0x7fff7a572000
(00.011088)  12432: vma 0x7fff7a572000 0x7fff7a574000
(00.011097)  12432: vma 0xffffffffff600000 0xffffffffff601000
(00.011110)  12432: Collect fdinfo pid=12432 fd=0 id=0x8
(00.011114)  12432: Collect fdinfo pid=12432 fd=1 id=0x8
(00.011116)  12432: Collect fdinfo pid=12432 fd=2 id=0x8
(00.011117)  12432: Collect fdinfo pid=12432 fd=255 id=0xa
(00.011150)  12432: Found 19 VMAs in image
(00.011154)  12432: vma 0x55f45a193000 0x55f45a19a000
(00.011156)  12432: vma 0x55f45a39a000 0x55f45a39b000
(00.011159)  12432: vma 0x55f45a39b000 0x55f45a39c000
(00.011162)  12432: vma 0x55f45adb7000 0x55f45add8000
(00.011163)  12432: vma 0x7fdbccd5c000 0x7fdbcd72b000
(00.011165)  12432: vma 0x7fdbcd72b000 0x7fdbcd912000
(00.011167)  12432: vma 0x7fdbcd912000 0x7fdbcdb12000
(00.011168)  12432: vma 0x7fdbcdb12000 0x7fdbcdb16000
(00.011170)  12432: vma 0x7fdbcdb16000 0x7fdbcdb18000
(00.011171)  12432: vma 0x7fdbcdb18000 0x7fdbcdb1c000
(00.011173)  12432: vma 0x7fdbcdb1c000 0x7fdbcdb43000
(00.011175)  12432: vma 0x7fdbcdd2c000 0x7fdbcdd2e000
(00.011176)  12432: vma 0x7fdbcdd43000 0x7fdbcdd44000
(00.011178)  12432: vma 0x7fdbcdd44000 0x7fdbcdd45000
(00.011179)  12432: vma 0x7fdbcdd45000 0x7fdbcdd46000
(00.011181)  12432: vma 0x7ffeaaad5000 0x7ffeaaaf6000
(00.011182)  12432: vma 0x7ffeaab01000 0x7ffeaab04000
(00.011215)  12432: vma 0x7ffeaab04000 0x7ffeaab06000
(00.011219)  12432: vma 0xffffffffff600000 0xffffffffff601000
(00.011230)  12432: Collect fdinfo pid=12596 fd=0 id=0x8
(00.011232)  12432: Collect fdinfo pid=12596 fd=1 id=0x8
(00.011234)  12432: Collect fdinfo pid=12596 fd=2 id=0x8
(00.012456)  12432: Preparing SCMs
(00.012477)  12432: tty: Unpaired slave 1
(00.012480)  12432: tty: ctl tty leader 0x8
(00.012482)  12432: tty: Inherit terminal for id 0x8
(00.012484)  12432: tty: head driver pts id 0x8 index 1 (master 0 sid 11971 pgrp 12432 inherit 1)
(00.012487)  12432: tty: Found orphan slave fake leader (0x8)
(00.012489)  12432: File descs:
(00.012490)  12432:  `- type 1 ID 0x1
(00.012492)  12432:  `- type 1 ID 0x2
(00.012494)  12432:  `- type 1 ID 0x3
(00.012497)  12432:  `- type 1 ID 0x4
(00.012499)  12432:  `- type 1 ID 0x5
(00.012502)  12432:  `- type 1 ID 0x6
(00.012504)  12432:  `- type 1 ID 0x7
(00.012505)  12432:  `- type 11 ID 0x8
(00.012507)  12432:    `- FD 0 pid 12432
(00.012509)  12432:    `- FD 1 pid 12432
(00.012510)  12432:    `- FD 2 pid 12432
(00.012512)  12432:    `- FD 0 pid 12596
(00.012513)  12432:    `- FD 1 pid 12596
(00.012515)  12432:    `- FD 2 pid 12596
(00.012517)  12432:  `- type 1 ID 0x9
(00.012520)  12432:  `- type 1 ID 0xa
(00.012522)  12432:    `- FD 255 pid 12432
(00.012525)  12432:  `- type 1 ID 0xb
(00.012527)  12432:  `- type 1 ID 0xc
(00.012529)  12432:  `- type 1 ID 0xd
(00.014752)  12432: Opened local page read 1 (parent 0)
(00.014762)  12432: Enqueue page-read
(00.014764)  12432: Enqueue page-read
(00.014766)  12432: Enqueue page-read
(00.014767)  12432: Enqueue page-read
(00.014769)  12432: Enqueue page-read
(00.014770)  12432: Enqueue page-read
(00.014772)  12432: Enqueue page-read
(00.014773)  12432: Enqueue page-read
(00.014774)  12432: Enqueue page-read
(00.014776)  12432: Enqueue page-read
(00.014777)  12432: Enqueue page-read
(00.014778)  12432: Enqueue page-read
(00.014780)  12432: Enqueue page-read
(00.014781)  12432: Enqueue page-read
(00.014783)  12432: Enqueue page-read
(00.014784)  12432: Enqueue page-read
(00.014785)  12432: Enqueue page-read
(00.014787)  12432: Enqueue page-read
(00.014788)  12432: Enqueue page-read
(00.014789)  12432: Enqueue page-read
(00.014791)  12432: Enqueue page-read
(00.014794)  12432: nr_restored_pages: 71
(00.014796)  12432: nr_shared_pages:   0
(00.014797)  12432: nr_dropped_pages:   0
(00.014799)  12432: nr_lazy:           0
(00.014806)  12432: Shrunk premap area to 0x7f37fcec8000(0)
(00.014809)  12432: Restore on-core sigactions for 12432
(00.014841)  12432: Restoring children in alien sessions:
(00.014843)  12432: Restoring children in our session:
(00.014883)  12432: Forking task with 12596 pid (flags 0x0)
(00.015073)  12432: Restoring 12432 to 12436 pgid
(00.015125)  12432: PID: real 12596 virt 12596
(00.015163)  12596: cg: Cgroups 1 inherited from parent
(00.015222)  12596: Opened local page read 2 (parent 0)
(00.015231)  12596: Enqueue page-read
(00.015235)  12596: Enqueue page-read
(00.015236)  12596: Enqueue page-read
(00.015238)  12596: Enqueue page-read
(00.015239)  12596: Enqueue page-read
(00.015241)  12596: Enqueue page-read
(00.015242)  12596: Enqueue page-read
(00.015243)  12596: Enqueue page-read
(00.015245)  12596: Enqueue page-read
(00.015246)  12596: Enqueue page-read
(00.015248)  12596: Enqueue page-read
(00.015249)  12596: Enqueue page-read
(00.015251)  12596: Enqueue page-read
(00.015252)  12596: Enqueue page-read
(00.015257)  12596: nr_restored_pages: 25
(00.015259)  12596: nr_shared_pages:   0
(00.015260)  12596: nr_dropped_pages:   0
(00.015262)  12596: nr_lazy:           0
(00.015266)  12596: Shrunk premap area to 0x7f37fd40b000(0)
(00.015268)  12596: Restore on-core sigactions for 12596
(00.015281)  12596: Restoring children in alien sessions:
(00.015285)  12596: Restoring children in our session:
(00.015291)  12596: Restoring 12596 to 12436 pgid
(00.015310)  12432: Restoring resources
(00.015322)  12432: Opening fdinfo-s
(00.015326)  12432: tty: open driver pts id 0x8 index 1 (master 0 sid 11971 pgrp 12432 inherit 1)
(00.015338)  12432: tty: Migrated slave peer 0x8 -> to fd 0
(00.015350)  12432: tty: Restore inherited group 12436
(00.015354)  12432: 		Create fd for 0
(00.015356)  12432: 			Going to dup 0 into 1
(00.015358)  12432: 			Going to dup 0 into 2
(00.015361)  12432: 		Send fd 0 to /crtools-fd-12596
(00.015369)  12432: 		Send fd 0 to /crtools-fd-12596
(00.015372)  12432: 		Send fd 0 to /crtools-fd-12596
(00.015375)  12432: 	Receive fd for 1
(00.015377)  12432: 	Receive fd for 2
(00.015400)  12432: Error (criu/files-reg.c:1721): Can't open file home/alan/tt.sh on restore: No such file or directory
(00.015404)  12432: Error (criu/files-reg.c:1657): Can't open file home/alan/tt.sh: No such file or directory
(00.015406)  12432: Error (criu/files.c:1194): Unable to open fd=255 id=0xa
(00.015797) Error (criu/cr-restore.c:1387): 12432 exited, status=1
(00.015817) Error (criu/cr-restore.c:2266): Restoring FAILED.

**Comment by LiuChangFreeman** [comment]
`home/alan/tt.sh`
Is the file available on the desc?
