### ISSUE TITLE
python-ipaddress address required for CRIT as of version 3.10

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#526]
After upgrading from 3.9 to 3.10, CRIT complained about being unable to import ipaddress. Installing the python-ipaddress package fixed the issue. I then looked at the installation wiki and I saw that python-ipaddress is listed as required for zdtm.py, which I believe is the test suite. The wiki should probably be updated, as this package seems to be generally required to use CRIT now.

It would probably also be helpful to list new package dependencies in the release notes for people who are upgrading, as they don't be looking at the installation wiki.

**Comment by adrianreber** [comment]
For 3.10 we started to support python2 and python3 and python2-ipaddr, which is listed as dependency for, does not exist for python3. But python2-ipaddress is a module that exists for python2 and also part of python3 without requiring additional modules.

I have updated the wiki to mention python-ipaddress for CRIT: https://criu.org/Installation

Pinging @xemul to update the release notes.

**Comment by rst0git** [comment]
:+1: Looks good to me

**Comment by adrianreber** [comment]
I updated the release page for 3.10
