### ISSUE TITLE
criu dump failed for /dev/fb0

### ISSUE THREAD

**Issue by fransjp84** [checkpoint-restore/criu#527]
Hello I'm trying to use criu on my custom embedded (arm) project.
I'm able to dump and restore simple loop example and now I'm trying to dump my real example and I got failed with following error:

>(00.071189) Dumping path for -3 fd via self 8 [/dev/shm/shm_tmp/fusion.0.5]
>(00.082202) Error (criu/proc_parse.c:553): Can't handle non-regular mapping on 4582's map 86aaa000
>(00.082264) Error (criu/cr-dump.c:1219): Collect mappings (pid: 4582) failed with -1

when I check the process map, this is what I got:

`
86aaa000-86ab4000 rw-s 86aaa000 fe:01 1691       /dev/fb/0
`

`
86ab4000-8a67f000 rw-s 86ab4000 fe:01 1691       /dev/fb/0
`
Could you help me on this issue? Thanks

**Comment by fransjp84** [comment]
Hello, Thanks for the reply, I dont exactly know the detail but I believe it is frame buffer where our SoC uses it to draw things to screen / or maybe it is SoC GPU device.

Based on the info you provided to me, does it means all UI based application that uses gpu to draw cant be dumped?

Thanks a lot

**Comment by adrianreber** [comment]
It is not possible to dump applications using the GPU, as CRIU does not know how to extract the state of the GPU, which CRIU needs for the restore. If your application is writing to a VNC session it is possible (https://criu.org/VNC). CRIU also offers the possibility to write plugins: https://criu.org/Plugins

So if you know how to get the state of the GPU dumped you could solve your problem with a CRIU plugin.

**Comment by fransjp84** [comment]
okay then, Thanks a lot for your help and info
