### ISSUE TITLE
fatal: it is not a git repository (or no parent at the mounted point/)

### ISSUE THREAD

**Issue by bethven** [checkpoint-restore/criu#528]
Hello,
I'm trying to install CRIU, but when I type "make" I get the following error:

fatal: it is not a git repository (or no parent at the mounted point /)
Stopping at the file system boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not established)

Should I install another program?
I installed "protobuf" but I still have the same error.

Thank you very much.
Regards,
Beth

**Comment by adrianreber** [comment]
I also get the first message if building from the tarball:

```
fatal: Not a git repository (or any of the parent directories): .git
```

It sounds fatal, but it is harmless. CRIU is looking for git to see if it is a development build or not.

I never saw ```Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).```, but mounting a tmpfs and extracting CRIU at the top of the tmpfs I get the same error.

The build still continues. Are there any more messages from the build system?

Can you paste the complete output of your shell?

**Comment by adrianreber** [comment]
You are missing many CRIU requirements. Please have a look at: https://criu.org/Installation

**Comment by rst0git** [comment]
Hi @bethven 
Adrian is right that you are missing many CRIU dependencies. I find it easier to just copy/paste the install command from the [Dockerfiles](https://github.com/checkpoint-restore/criu/tree/master/scripts/build) that are used for testing. This should install all requirements needed to compile and install CRIU.
```
# CentOS
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install -y \
	ccache \
	findutils \
	gcc \
	git \
	iproute \
	iptables \
	libaio-devel \
	libasan \
	libcap-devel \
	libnet-devel \
	libnl3-devel \
	make \
	procps-ng \
	protobuf-c-devel \
	protobuf-devel \
	protobuf-python \
	python \
	python-ipaddress \
	python2-future \
	python2-junit_xml \
	python-yaml \
	python-six \
	tar \
	which \
	e2fsprogs \
	python2-pip \
       asciidoc xmlto

# Fedora
dnf install -y \
	ccache \
	findutils \
	gcc \
	git \
	iproute \
	iptables \
	libaio-devel \
	libasan \
	libcap-devel \
	libnet-devel \
	libnl3-devel \
	make \
	procps-ng \
	protobuf-c-devel \
	protobuf-devel \
	python2-protobuf \
	python2 \
	python-ipaddress \
	python-yaml \
	python3-pip \
	python2-future \
	python3-PyYAML \
	python3-future \
	python3-protobuf \
	python3-junit_xml \
	tar \
	which \
	e2fsprogs \
	asciidoc xmlto

# Ubuntu
apt-get update && apt-get install -y \
	ccache \
	libnet-dev \
	libnl-route-3-dev \
	gcc \
	bsdmainutils \
	build-essential \
	git-core \
	iptables \
	libaio-dev \
	libcap-dev \
	libnl-3-dev \
	libprotobuf-c0-dev \
	libprotobuf-dev \
	libselinux-dev \
	pkg-config \
	protobuf-c-compiler \
	protobuf-compiler \
	python-minimal \
	python-future
```

**Comment by bethven** [comment]
Hello, thank you very much, with this that you have recommended me now, it seems that if I could install everything I needed for CRIU, because before I had already installed some programs but I still had problems and did not pass the make.
Well I will start taking my first steps with CRIU to see how it works. Again, thank you very much everyone.
Best regards.
