### ISSUE TITLE
Support FUSE mountpoints

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#53]
Pulled from criu.org/Todo

When dumping mountpoints we explicitly check the filesystem mounted. The thing is -- not all filesystems can be just ignored on dump. E.g. FUSE mount involves a user-space daemon that is responsible for the files tree contents. If we just kill one on dump we might not be able to restore it. Need to special-care one.

**Comment by tswift242** [comment]
@xemul Any updates on this enhancement? We would like to be able to C/R FUSE mounts. Has any progress been made in this space?

**Comment by xemul** [comment]
@tswift242 , well, yes and no. We've implemented NFS mountpoints C/R which is very close to how this should be done for FUSE. The problems are a) it has been done in Virtuozzo criu branch and hasn't been pushed upstream b) FUSE needs more coding.

I would say this particular feature right now is out of direct scope for Virtuozzo, so I wouldn't count on Virtuozzo developers to implement it in the nearest future (submitting NFS patches upstream is another story, that can :) be done). What's your use-case for CRIU and FUSE? Maybe we can find the ways to make it happen.

**Comment by mihalicyn** [comment]
see also https://bugs.openvz.org/browse/OVZ-7283

**Comment by mihalicyn** [comment]
https://lore.kernel.org/linux-fsdevel/20230220193754.470330-1-aleksandr.mikhalitsyn@canonical.com/T/#t
