### ISSUE TITLE
Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)

### ISSUE THREAD

**Issue by ncpe20012003** [checkpoint-restore/criu#530]
When I issue a "criu check" on Ubuntu 16.04 running kernel Linux 4.4.0-1062-aws I get the warning in the subject. I've tried to do live migrations and stateful snapshots of LXCs and get similar error. How do I resolve this?

**Comment by adrianreber** [comment]
This warning is unrelated to your live migration failures. Please provide full logs of the error message you are seeing.

**Comment by upc-distribution** [comment]
Hello adrianreber,
May I ask you 
I am using criu 3.14 and docker 19.03.13 for checkpoint and restore my programs. Its working well but unfortunately, when I try to checkpoint and restore my program, it is not check pointing the program state and it always start from the beginning step when resume my container. But, it didn't show any errors. Is it relate as I am checking my kernel version? Previous, I didn't notice which version that I used but now is 4.4.0-190-generic Ubuntu16.04. Please suggest me. Do I need to downgrade or upgrade the kernel? Thank you very much.

**Comment by adrianreber** [comment]
@upc-distribution Please do not use tickets unrelated to your problem. Just open a new ticket. It sounds like you might be using one of the tools in a wrong way.

I am closing this as the original topic is over two years old.
