### ISSUE TITLE
Can't join the target namespace if the PID number is bigger than 65535

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#532]
Hi,

I found criu will treat the PID number as a file path when using join-ns feature if the number is bigger than 65535:

https://github.com/checkpoint-restore/criu/blob/aeeec2165a153b0c4885f5dd3ad26792822a8a9c/criu/namespaces.c#L78
```
if ((errno == ERANGE) || (endptr == str)
			|| (*endptr != '\0')
			|| (val < 0) || (val > 65535)) {
		str = NULL;
		return -1;
	}
```

Is it necessary to have this limitation?

**Comment by avagin** [comment]
Cc:  @xemul

**Comment by xemul** [comment]
Sorry for just noticing this :)

This is not a "limitation", this is an attempt to distinguish /proc/<pid> path from anything else (e.g. ip tool's bindmounts). And looking at the code I'd say it's quite buggy :(
