### ISSUE TITLE
Is there a way to make 'criu check --extra' provide more info?

### ISSUE THREAD

**Issue by bburnett6** [checkpoint-restore/criu#533]
I'm trying to get criu set up for use by our unprivileged users on our cluster and believe that I don't have the kernel set up properly. When I run `criu check` I receive the expected 'looks good' but am still unable to dump as an unprivileged user. When I run `criu check --extra` I get 
> Looks good but some kernel features are missing
> which, depending on your process tree, may cause
> dump or restore failure.

Is there a way to get a list of all of the kernel configs that I am missing? I have checked the list at https://criu.org/Linux_kernel and loaded all of the required modules. Also as a note, I do not have all of the configs set to 'CONFIG_NAME=y' instead some are set to 'm' and I am simply loading them in with `modprobe`. Do they need to be set to 'y'?

Thanks in advance!

**Comment by avagin** [comment]
CRIU doesn't work when it is executed from an unprivileged user. There are operations which require capabilities. For example, it is impossible to open /proc/self/map_files/ links without CAP_SYS_ADMIN:
https://github.com/torvalds/linux/blob/master/fs/proc/base.c#L2026

**Comment by avagin** [comment]
https://criu.org/Linux_kernel

**Comment by bburnett6** [comment]
Alright, that answers that. Thanks for the reply!
