### ISSUE TITLE
CRIU Cuda support

### ISSUE THREAD

**Issue by montekki** [checkpoint-restore/criu#534]
Any plans for supporting C/R for cuda applications?

**Comment by adrianreber** [comment]
No. Also see #527. There is no way to extract the state of the program on the GPU. If there would be a theoretical way to extract the state from the GPU then there would be a theoretical possibility to implement something like this.

With CRIU plugins it could be possible with a lot of help from the hardware vendor, but right now I would say it is not possible.

**Comment by montekki** [comment]
also, there's this https://www.nvidia.com/en-us/design-visualization/solutions/vgpu-migration/

**Comment by montekki** [comment]
I might need to start working on in in near future, yes.

**Comment by pavanagrawal123** [comment]
@montekki I was wondering if you were ever able to get started on this? Do you have any other information that you can share that can hopefully make this possible?

**Comment by Muks14x** [comment]
Hi, just wanted to ask if there have been any updates on this?

**Comment by avagin** [comment]
No updates. We are still looking for volunteers who will implement this.

**Comment by AHEADer** [comment]
In the Eurosys 20, a paper named "Balancing Efficiency and Fairness in Heterogeneous GPU Clusters for Deep Learning" said they implemented this by using CRIU.

**Comment by rst0git** [comment]
@AHEADer thank you for sharing this.
[(2020) Balancing efficiency and fairness in heterogeneous GPU clusters for deep learning](https://github.com/checkpoint-restore/criu/files/5395205/2020.Balancing.efficiency.and.fairness.in.heterogeneous.GPU.clusters.for.deep.learning.pdf)

**Comment by adrianreber** [comment]
Indeed, thanks for pointing out that paper.

I just had a look and they write that they do not checkpoint the GPU part only the CPU part.

Seems to be an unmodified CRIU without any GPU support.

**Comment by AHEADer** [comment]
> Indeed, thanks for pointing out that paper.
> 
> I just had a look and they write that they do not checkpoint the GPU part only the CPU part.
> 
> Seems to be an unmodified CRIU without any GPU support.

So does it mean if we somehow copy the GPU memory & status back then we can resume it by recomputing based on some checkpointed status?

**Comment by adrianreber** [comment]
> > Indeed, thanks for pointing out that paper.
> > 
> > I just had a look and they write that they do not checkpoint the GPU part only the CPU part.
> > 
> > Seems to be an unmodified CRIU without any GPU support.
> 
> So does it mean if we somehow copy the GPU memory & status back then we can resume it by recomputing based on some checkpointed status?

You should read the paper. They write that they use some kind of proxy to decouple the CPU process from the GPU process.

As long as you are able to close the connection to the GPU before checkpointing it should be doable, but the application needs to be checkpoint aware.

**Comment by AHEADer** [comment]
> > > Indeed, thanks for pointing out that paper.
> > > I just had a look and they write that they do not checkpoint the GPU part only the CPU part.
> > > Seems to be an unmodified CRIU without any GPU support.
> > 
> > 
> > So does it mean if we somehow copy the GPU memory & status back then we can resume it by recomputing based on some checkpointed status?
> 
> You should read the paper. They write that they use some kind of proxy to decouple the CPU process from the GPU process.
> 
> As long as you are able to close the connection to the GPU before checkpointing it should be doable, but the application needs to be checkpoint aware.

Many thanks for your reply. Now I understand what they do now. It's better to have a try following their ways.

**Comment by LuYilei** [comment]
Does 

> they

Do you have any updates?

**Comment by LuYilei** [comment]
> 

Do you have any updates?

**Comment by andronat** [comment]
JFYI there is also some more recent research on this topic here: [2020 CRAC: Checkpoint-Restart Architecture for CUDA with Streams and UVM](https://www.ccs.neu.edu/home/gene/papers/sc20.pdf).

BTW, I don't think this issue should be closed.

**Comment by adrianreber** [comment]
> BTW, I don't think this issue should be closed.

You are right. The issue has the correct label to not be closed automatically, but it seems it didn't work as expected. Let's see if it works better now.

**Comment by rst0git** [comment]
The following paper from 2022 describes in more detail the "device proxy" approach proposed in Balancing Efficiency and Fairness in Heterogeneous GPU Clusters for Deep Learning mentioned above:
[Singularity: Planet-Scale, Preemptible and Elastic Scheduling of AI Workloads](https://arxiv.org/pdf/2202.07848.pdf)

**Comment by jsun-m** [comment]
> 

Are there any open-source resources on this project or do we have to implement it from scratch ourselves

**Comment by jsun-m** [comment]
> The following paper from 2022 describes in more detail the "device proxy" approach proposed in Balancing Efficiency and Fairness in Heterogeneous GPU Clusters for Deep Learning mentioned above: [Singularity: Planet-Scale, Preemptible and Elastic Scheduling of AI Workloads](https://arxiv.org/pdf/2202.07848.pdf)

Are there any open-source resources on this project or do we have to implement it from scratch ourselves

**Comment by rst0git** [comment]
> Are there any open-source resources on this project or do we have to implement it from scratch ourselves

I am not aware of open-source resources on this project. However, there are a few patents related to this work.
- [Scheduler for planet-scale computing system](https://patents.google.com/patent/US20220318052A1/en)
- [Planet-scale, fully managed artificial intelligence infrastructure service](https://patents.google.com/patent/US20220318674A1/en)
- [Transparent pre-emption and migration for planet-scale computer](https://patents.google.com/patent/US20220308917A1/en)
- [Artificial intelligence workload migration for planet-scale artificial intelligence infrastructure service](https://patents.google.com/patent/US20220311832A1/en)

**Comment by 0x2b3bfa0** [comment]
https://www.youtube.com/watch?v=Rk3nTUfRZmo&t=578s

**Comment by adrianreber** [comment]
> > _[…] something that will help make that possible is our work with our hardware partners, AMD and NVIDIA, which helped implementing CRIU, or Checkpoint/Restore in Usermode for their GPUs._ [(What runs ChatGPT? Inside Microsoft’s AI supercomputer | Featuring Mark Russinovich | YouTube, minute 9:39)](https://www.youtube.com/watch?v=Rk3nTUfRZmo&t=578s)

It is not really clear if they actually implemented CRIU support for Nvidia GPUs or if they are just using the device proxy which was discussed here. If there is real CRIU support, I am not aware of any discussions with upstream CRIU.

**Comment by Sharathmk99** [comment]
Hey @adrianreber, I’m also interested in GPU checkpoint. Can you share any details on how device proxy can be used? Thanks

**Comment by adrianreber** [comment]
> Hey @adrianreber, I’m also interested in GPU checkpoint. Can you share any details on how device proxy can be used? Thanks

https://github.com/checkpoint-restore/criu/issues/534#issuecomment-1438561823

**Comment by Sharathmk99** [comment]
Thank you for pointing to the link. I did read that Microsoft paper. 
Any plans to add support to CRIU itself? Thanks

**Comment by adrianreber** [comment]
> Any plans to add support to CRIU itself?

Support for what? Nvidia GPUs can only be supported if nvidia steps up and implements CRIU support as AMD did.

**Comment by Sharathmk99** [comment]
Got it. Thank you

**Comment by lllukehuang** [comment]
Hello, in a paper from NVIDIA [GPU snapshot: checkpoint offloading for GPU-dense systems] (https://dl.acm.org/doi/pdf/10.1145/3330345.3330361), I noticed that NVIDIA GPUs appear to implement GPU snapshot preservation through hardware. I'm not a expert on this but I'm wondering whether this work can be integrated into CRIU :)

**Comment by lllukehuang** [comment]
Hello, in a paper from NVIDIA [GPU snapshot: checkpoint offloading for GPU-dense systems] (https://dl.acm.org/doi/pdf/10.1145/3330345.3330361), I noticed that NVIDIA GPUs appear to implement GPU snapshot preservation through hardware. I'm not a expert on this but I'm wondering whether this work can be integrated into CRIU :)

**Comment by rst0git** [comment]
>  I noticed that NVIDIA GPUs appear to implement GPU snapshot preservation through hardware.

This paper proposes hardware and driver components for checkpointing, but these are not implemented in real hardware, only simulated.

**Comment by adrianreber** [comment]
From @aidan-gibson as mentioned in #2369:

> https://arxiv.org/pdf/2103.04916.pdf
>
> They extended CRIU to OpenGL and suspended / restored Autodesk Maya. No code published tho ):

and my answer:

> Thanks. The following also seems to be from memverge. Unfortunately memverge does not really talk to upstream CRIU about their work. This sounds slightly related to:
>
> - https://www.nvidia.com/gtc/posters/#/session/1705106137731001cNAN
> -  ![gtc24-web-poster-1920x1080_P63184_1709928723357001pVZQ](https://github.com/checkpoint-restore/criu/assets/8724298/2604655e-e406-44d7-b3f9-d566af9f0062)
> - [DCCDCCS_1_P63184_Bernie Wu_web_1710777201737001ioQN.pdf](https://github.com/checkpoint-restore/criu/files/14734930/DCCDCCS_1_P63184_Bernie.Wu_web_1710777201737001ioQN.pdf)
> - https://youtu.be/p-zNA1AN37M

I am also adding this video from Microsoft to the list of existing work with nvidia GPUs:

- https://youtu.be/Rk3nTUfRZmo?t=585

That seems to mention CRIU and GPUs.

**Comment by edenbuaa** [comment]
any update?  @edenbuaa

**Comment by rst0git** [comment]
NVIDIA have released CUDA checkpoint and restore utility that can be combined with CRIU:
https://github.com/NVIDIA/cuda-checkpoint
