### ISSUE TITLE
Checkpoint error

### ISSUE THREAD

**Issue by aidagha** [checkpoint-restore/criu#535]
Can someone help me with this error, please?

`cid checkpointname
Error response from daemon: Cannot checkpoint container 722ba39346ebb83e6a59bbdf17445715e2826f7b924814d7b15d976242449d8f: docker-runc did not terminate sucessfully: CRIU version check failed: exec: "criu": executable file not found in $PATH path= /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/722ba39346ebb83e6a59bbdf17445715e2826f7b924814d7b15d976242449d8f/criu-dump.log: unknown
`

**Comment by avagin** [comment]
> CRIU version check failed: exec: "criu": executable file not found in $PATH

Maybe you forgot to install criu? Could you try to execute "criu -V" from a terminal?

**Comment by aidagit** [comment]
I tried to install criu using the provided instructions. I get:

`-bash: criu: command not found
`
I am doing this on mac.

**Comment by adrianreber** [comment]
CRIU is Linux only. Please try it on Linux.

**Comment by avagin** [comment]
https://github.com/docker/for-mac/issues/1059#issuecomment-408985367

**Comment by avagin** [comment]
@adrianreber I think there is docker-for-mac. In this case, Docker is running on a Linux virtual machine.
https://www.docker.com/docker-mac

**Comment by aidagit** [comment]
I used this image to install criu on mac but I guess it's not working. 
[https://github.com/boucher/criu-for-mac](url)

**Comment by ianfrantz** [comment]
This is Linux only.  You can get this in an error message if you actually shutdown the MobyLinuxVM on Windows 10. 
`
$ docker checkpoint create MSSQL19 cp
docker checkpoint create is only supported on a Docker daemon running on linux, but the Docker daemon is running on`

If this feature is like the Hyper-V checkpoint this is going to be cool!! I have two Docker projects on my github. Find me on LinkedIn folks, I post all my work there. :]
