### ISSUE TITLE
Question about checkpointing a container using CRIU

### ISSUE THREAD

**Issue by aidagha** [checkpoint-restore/criu#536]
Hello! I was wondering if it is possible to checkpoint a container on a VM or a machine using CRIU and then move it to another VM or machine and start the checkpoint on the destination machine and run it from the saved state? Do I need any other tools or is it possible with just CRIU and commands like `docker checkpoint` and `docker start --checkpoint`?

**Comment by rppt** [comment]
Hi,

Yes it is possible, that's what CRIU is about ;-)
You need to have CRIU installed and then `docker checkpoint` and `docker start --checkpoint` would be enough.

**Comment by avagin** [comment]
JFYI: Right now, docker checkpoint is broken: https://github.com/checkpoint-restore/criu/issues/510

You can follow my instructions in https://github.com/checkpoint-restore/criu/issues/510#issuecomment-408650607 to build docker with all required fixes.
