### ISSUE TITLE
CRIU Page Server Integration with Docker

### ISSUE THREAD

**Issue by farooqte96** [checkpoint-restore/criu#539]
Hi

Does anyone know that whether Docker at current supports this feature i.e. page-server for fast CRIU memory dumping? If yes how can we use this feature?

Thanks

**Comment by adrianreber** [comment]
So runc has support to use a page-server, but I am not aware that docker actually uses it. If you want to migrate container only on the runc level it should be possible (theoretically).

I have never tested it though, so not sure if it actually works.

**Comment by farooqte96** [comment]
Thanks @adrianreber  I just wanted to confirm if somebody has done it on Docker, because generally i see many features of CRIU are available for testing only for runc or lxc, but  not with Docker.

**Comment by adrianreber** [comment]
Not many people are working on getting CRIU features up the container stack and we probably have to make sure they work on lower levels first before they can be used in higher levels.
