### ISSUE TITLE
criu doesn't rewrite cgroup root for comounted controllers (e.g. cpu,cpuacct)

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#544]
It seems that certain OSes comount some cgroup controllers (see cgroup doc: http://man7.org/linux/man-pages/man7/cgroups.7.html). For example, on all of the Ubuntu 16.04 and Debian 8 machines I've checked, the cpu and cpuacct controllers are comounted and show as a single cpu,cpuacct controller under /sys/fs/cgroup (along with symlinks for cpu and cpuacct to this combined directory). I see the same thing with the net_cls and net_prio controllers. Certain OSes don't seem to do this, such as Ubuntu 14.04.

When I do C/R via criu and docker on a machine which comounts cgroup controllers, the comounted controllers are not restored properly by criu. Specifically, the cgroup roots are not rewritten, and so the old cgroup paths (containing the old containerId) are used. Attached is an example restore.log.

On lines 24-32, you'll see that only 9 cgroup roots were rewritten even though there are 11 controllers. Just below that you'll see that all cgroup dirs already exist, except for cpu,cpuacct and net_cls,net_prio, which criu creates using the original cgroup root. On lines 173-183, you'll again see that the old cgroup roots are used for these 2 comounted controllers while the new cgroup roots are used for the 9 others. Finally on lines 902-921 you'll see the old cgroup property values restored for the old cgroup roots.

Besides the fact that these cgroups are not being restored correctly for the new container process(es), this has also sometimes caused the restore operation to fail for me, as it looks like there is a race between something cleaning up the old cgroup path (for which a container no longer exists) and criu trying to access that path (after having created that path).

I'm using criu 3.10 and docker 17.03.2.

Repro steps:

1) Use a machine which has the cpu and cpuacct controllers comounted, or do this yourself: mount -t cgroup -o cpu,cpuacct none /sys/fs/cgroup/cpu,cpuacct
2) docker run -d --name test busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 3; done'
3) docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints test test
4) docker rm test
5) docker create --name test busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 3; done'
6) docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test test
7) Examine the criu restore log as well as the cgroupfs

[restore.txt](https://github.com/checkpoint-restore/criu/files/2315601/restore.txt)

**Comment by tswift242** [comment]
ping @xemul @avagin

**Comment by avagin** [comment]
@tswift242 could you try out this fix https://github.com/avagin/runc/commit/bc75ee4d27ffac98f03743d9206924115a07f568

**Comment by tswift242** [comment]
@avagin Thanks for looking at this. I'll give it a try although I've never built or run runc before. If I need help I'll let you know.

**Comment by tswift242** [comment]
@avagin I'm having trouble testing the fix, probably because of my inexperience with runc. I've built runc and have created and started a busybox container based on the instructions in the runc repo's top level README. However, running runc checkpoint is giving me the criu error "Can't lookup mount=.. for fd=... path=...". Can you help advise me? What's the easiest way to test this? I believe I have to use runc directly as I think C/R is still broken in docker master. What is your workflow for testing C/R with runc?

**Comment by adrianreber** [comment]
@tswift242: I am using runc very often to test checkpoint restore and it always works.
For my tests it is important to have redirect stdout and stdin.

My commands are like this:
```
$ runc run rhel7-httpd -d -b /runc/containers/rhel7-httpd/ &> /dev/null  < /dev/null
$ runc checkpoint rhel7-httpd
$ runc restore -d  rhel7-httpd
```

**Comment by avagin** [comment]
@tswift242 you can compile runc and bind-mount it into docker-runc
```
$ mount --bind runc /usr/bin/docker-runc
```

then just do your tests with docker

**Comment by tswift242** [comment]
@adrianreber @avagin Thanks for the help. The stdin/out redirect fixed the first error I was getting, and then I also needed to edit config.json to make sure certain things like the cgroup mount weren't readonly. After doing that, I got C/R to work with runc.

@avagin It looks like your patch fixes the issue. Attached is the restore log for a busybox container which was restored using a runc build with your patch.
[restore.txt](https://github.com/checkpoint-restore/criu/files/2435560/restore.txt)

**Comment by tswift242** [comment]
@avagin can this fix be pushed to runc?

**Comment by avagin** [comment]
It is on my todo list...

**Comment by avagin** [comment]
@tswift242 I'm thinking that it may be better to fix this issue in criu. In this case, we will be able to deliver this bugfix to users much faster.  Could you try out this patch https://github.com/avagin/criu/commit/3fb1a8aa773ecc03a42edcd5deeee6288d2377c5?

**Comment by tswift242** [comment]
@avagin Yea moving the fix to criu should definitely get the fix to users sooner which would be awesome. Seems like the way to go.

I tried your patch but it didn't seem to fix the issue. The comounted controllers still seem to use the old roots.

**Comment by avagin** [comment]
@tswift242 Thank you for testing. I uploaded a new version https://github.com/avagin/criu/tree/issues/544. In this case, I've checked it myself that it works as expected.

**Comment by tswift242** [comment]
@avagin Yep, the latest patch fixes the issue. Thanks!

**Comment by tswift242** [comment]
@avagin While playing around with a criu build containing your fix for this issue, I believe I've found a regression in criu since version 3.10. When I use docker's C/R feature to checkpoint and restore a basic busybox container, the restored container exits right after the restore finishes with exit code 139, indicating a sigsegv was received. The restore itself is successful, so there's nothing in the restore log. However, I see this in /var/log/syslog:

sleep[2260] bad frame in rt_sigreturn frame:00007f12d0f19000 ip:4abec1 sp:7ffcde4fe898 orax:ffffffffffffffff in sleep[400000+106000].

I actually see 2 occurrences of this. Based on the timestamps, it seems that first one occurs right around when the checkpoint is taken, and the 2nd one is right after the restore completes. I think this is a criu issue and a regression since criu 3.10, as when I revert back to criu 3.10, this issue doesn't reproduce. https://github.com/avagin/criu/commits/issues/544 contains not only the fix for this issue but also a bunch of commits from criu's dev branch since 3.10. I'm guessing one of them is the culprits.

Reproduction steps:

1) docker run -d --name test busybox sleep 1000000
2) docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints test test_cp
3) docker rm test
4) docker create --name test busybox sleep 1000000 && docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test_cp test

I found this link from 2 years ago which contains the exact error I'm seeing and mentions a kernel change which may have impacted criu: https://www.openwall.com/lists/kernel-hardening/2016/03/31/14. Not sure if that's relevant here.

Based on how simple the repro steps are, this seems like a major regression. Can you or someone else please take a look. I can file a new issue if desired for better tracking.
