### ISSUE TITLE
Docker checkpoint failed

### ISSUE THREAD

**Issue by yufeifly** [checkpoint-restore/criu#546]
Hi, I followed  the instructions on https://criu.org/Docker.
After command "docker checkpoint create looper checkpoint1", everything seemed to be fine.
![default](https://user-images.githubusercontent.com/20283879/44624583-862fda80-a924-11e8-9bc8-eafdd16db48b.png)
However, I ran "docker  logs looper ", the log still growed. However it was supposed to stop.
What was the problem?
 ---------------------------------------------------
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     true
-----------------------------------------------
criu : 3.10
-----------------------------------------------
ubuntu 18.04

**Comment by avagin** [comment]
https://github.com/moby/moby/pull/37360
