### ISSUE TITLE
Fail to checkpoint with a bind mount '/tmp/bad/'

### ISSUE THREAD

**Issue by Ace-Tang** [checkpoint-restore/criu#547]
Hi, I find that if a bind mount source path has a '/' at last like '/tmp/bad/' passed to criu, the dump will fail, error:
```
(00.014197) Error (criu/mount.c:698): mnt: 367:./tmp/bad doesn't have a proper root mount
```
The complete bind mount config is 
```
{
            "destination": "/tmp/bad/",
            "options": [
                "rbind"
            ],
            "source": "/var/lib/pouch/volume/9abd3949c0364ab6fdfe9b1fefb1b43753bb7bafeb465fba0fafa26861e52fd0",
            "type": "bind"
}
```
I have fix it by clean all file path before it passed to criu, I just wonder is it a bug?

here is criu version
```
$ criu -V
Version: 2.6
```

**Comment by adrianreber** [comment]
Version 2.6 is rather old. Can you try it with 3.10?

**Comment by adrianreber** [comment]
Just curious, what is your problem with 3.10?

But if you have a patch, please submit it to the mailing list: https://criu.org/How_to_submit_patches

**Comment by avagin** [comment]
> I have fix it by clean all file path before it passed to criu, I just wonder is it a bug?

Yes, it is. It can be fixed in criu or in runc:

http://man7.org/linux/man-pages/man3/realpath.3.html
https://golang.org/pkg/path/filepath/#Clean

**Comment by Ace-Tang** [comment]
@avagin , I could try that,  but since I am not put into many time for this, I am sorry not found the problem in criu, seems that record mountpoint have do the path clean, but other oparations not.
I can try that in runc !
