### ISSUE TITLE
[Question] Incremental checkpointing restore with --track-mem

### ISSUE THREAD

**Issue by juancampa** [checkpoint-restore/criu#550]
I know `--track-mem` can be used when dumping but is it possible to also use it when restoring? The idea is that if I dump a process that was previously restored I get an incremental dump (i.e. faster, smaller size)

In other words, the incremental example in the documentation shows this:
 - Dump 1 (leave running)
 - Dump 2 (this one is incremental)

But what I'm after is:
 - Dump 1 (kill process)
 - Restore from 1 (use `--track-mem` here?)
 - Dump 2 (have this one be incremental based on 1)
 
Not exactly sure if this is possible with the way CRIU currently works.

Thanks for the help!

**Comment by rst0git** [comment]
Hi @juancampa, I am not sure I understand your question.

The `--track-mem` option enables CRIU to identify memory pages that have been modified by the application. It makes use of the [soft-dirty bit](https://lwn.net/Articles/546966/) concept.

When you specify `--track-mem` CRIU does `echo 4 > /proc/$PID/clear_refs`.
This clears the soft dirty and the writable bits from all PTEs (page table entries) the of process `$PID`. Then every time when the process modifies a memory page the soft dirty will be set.

When performing the next dump iteration, with `--track-mem`, only those memory pages which have the soft dirty bit set will be copied into the checkpoint, all other (unchanged) memory pages will be ignored.

This technique is used to implement pre-copy memory migration.

**Comment by adrianreber** [comment]
@juancampa I think #401 is a similar discussion.

**Comment by rppt** [comment]
Duplicate of #401

**Comment by juancampa** [comment]
Closing in favor of #401
