### ISSUE TITLE
Is memory tracking supposed to be disabled while using page server?

### ISSUE THREAD

**Issue by psinha01** [checkpoint-restore/criu#553]
CRIU's iterative migration (both: iterative dumps and iterative pre-dumps) using memory tracking works fine. But when I use iterative migration (either iterative dumps or iterative pre-dumps with a final dump) with a page server, then the memory tracking doesn't work. I wonder what could be the reason for this functionality. Can you please explain? Thanks.
Here is what i am using:
**Case 1 (where memory tracking works):**
```
sudo criu pre-dump -D /home/o19/pgserver/d1 --shell-job --leave-running --track-mem -t 5859
sudo criu pre-dump -D /home/o19/pgserver/d2 --shell-job --leave-running --track-mem --prev-images-dir ../d1/ -t 5859
```
I can see pages.img file's size to be comparatively very small for second iteration than for first iteration.

**Case 2 (using page server; when memory tracking doesn't work):**
**Iteration 1**
Destination:
`sudo criu page-server -D /home/o19/pgserver/d1 -o ps.log -v4 --port 22222`
Source:

```
sudo criu pre-dump --tree 6182 --images-dir d1 --shell-job --track-mem --leave-running -o dmp.log --page-server --address 10.128.19.2 --port 22222 --display-stats
```
**Iteration 2**
Destination:
`sudo criu page-server -D /home/o19/pgserver/d2 -o ps.log -v4 --port 22222
`
Source
```
sudo criu pre-dump --tree 6182 --images-dir d2 --prev-images-dir ../d1 --shell-job --track-mem --leave-running -o dmp.log --page-server --address 10.128.19.2 --port 22222 --display-stats
```

Pages.img file for both iteration is exactly same.

**Comment by adrianreber** [comment]
I have not used the page-server in a long-time, but I just did some tests and it works if you tell the page-server to use a prev-images-dir:

1. page-server run : ```criu page-server -D /tmp/1  -v4 --port 22222```
2. page-server run : ```criu page-server -D /tmp/4  -v4 --port 22222 --prev-images-dir ../1```

The output looks correct:

```
#️  ls -lh /tmp/1
-rw-r--r--  1 root root 1.1K Sep 11 06:59 pagemap-15989.img
-rw-r--r--  1 root root 101M Sep 11 06:59 pages-65537.img
#️  ls -lh /tmp/4
-rw-r--r--  1 root root 281 Sep 11 07:00 pagemap-15989.img
-rw-r--r--  1 root root 24K Sep 11 07:00 pages-65537.img
lrwxrwxrwx  1 root root   4 Sep 11 07:00 parent -> ../1
```

**Comment by psinha01** [comment]
Thank you so much. I thought prev-images-dir was only for the source side where we are iterative checkpointing.
