### ISSUE TITLE
Does migration (either live or non-live) work for a process that uses active TCP sockets?

### ISSUE THREAD

**Issue by psinha01** [checkpoint-restore/criu#555]
Hi,

My goal is to make migration (either live or non-live) work for a process which has active TCP sockets. For the purpose of testing, I am using simple echo server and client code tcp-howto.c provided on [CRIU's website](https://criu.org/Simple_TCP_pair).

What I have observed (and it works nicely) is I can checkpoint the process using --tcp-established and restore it successfully. On restoration, I can see that the connections are re-establlished. The only catch is that it works as long as the checkpointed process is restored on the **same machine**. As soon as I try to restore the process on another machine, i.e. by moving the checkpointed image files to another machine and restore the process on this new destination machine, the restoration fails. I understand that it is due to binding to wrong IP address as destination machine has a different IP address than the source machine and the process was using source's IP address when it was checkpointed.

But I am not sure if my understanding is right, as @adrianreber wrote in this [article](https://rhelblog.redhat.com/2016/09/26/from-checkpointrestore-to-container-migration/): 

> Many other applications have been successfully migrated and an important feature is that any established TCP network connections are (also) **migrated** with CRIU

However, [CRIU's Change IP address](https://criu.org/Change_IP_address) says we should use containers to migrate process to deal with different IP addresses.

So, I also tried to use the container and run the tcp-howto process in it. Then checkpoint the whole container and restore it on same machine (not even on another machine). Since I have not been able to checkpoint LXC container (issue #552), I moved to Docker containers. Checkpointing and restoration works fine for Docker. The only issue is the tcp-howto process is not restored. I guess it is not even checkpointed as I don't see any pages.img file for that process id.

**Question**
Does it mean a process having active TCP sockets cannot be migrated (either live or non-live) and restored on a machine other than source machine? Is it an issue/bug or has it not been implemented yet?
Kindly help. Thank you for bearing with my questions. I really appreciate it.

**Comment by adrianreber** [comment]
Yes, it is possible to live migrate processes with established TCP connections from one system to another.

I hope that answers your question. The important part is, that for established TCP connections, the IP address has to be the same. Usually I use an additional IP address which I move between the involved systems. Container or not makes no difference. The idea behind using containers is that it should make it easier for you. But then the restored container needs to have the same IP address.

**Comment by psinha01** [comment]
Yes, it was helpful and thank you for suggestion to move IP address. I will close the issue as it seems issue is with container setup. Thanks for all the help.
