### ISSUE TITLE
Question about ZDTM test

### ISSUE THREAD

**Issue by bethven** [checkpoint-restore/criu#560]
Hello, I would like to know if with the ZDTM Test of Criu I can use it to test my executions, I have read about it, but I still do not understand how it works.
I can use the ZDTM Test in my executions ?, that is, if I have an mpi app and checkpoint and restart can I see the I / O trace of each PID?
I understand that ZDTM has to see traces, because I executed the small example that they explain. What I want to know if this test can be applied to my executions to see its traces?
Because using the tool strace when analyzing the trace I see that it is incomplete since the sizes for example of the "write" do not come close to the size of the image files, besides that the PID is different, I do not see the PID that I should see.
That is why I would like to know if the ZDTM can help me do what I need.
Thank you very much.
Greetings.

**Comment by adrianreber** [comment]
Not sure what you mean if you say 'ZDTM has to see traces' and which traces you are looking for.

ZDTM starts a tests, checkpoints the tests, greps through the logfiles for errors, restores the test and greps through the logfile for errors. It also watches the return results of CRIU and the test cases.

**Comment by bethven** [comment]
hello, what I mean is if with "ZDTM and --sat (Generate CRIU strace-s for sat tool (restore is fake, images are kept))"
When I run an app with checkpoint and restore, if I can see the operations: open, close, write and read? that are generated when doing a checkpoint and a restore to my mpi app.
Thank you

**Comment by adrianreber** [comment]
So if I understand it correctly you want to run CRIU under the control of strace, right?

Can you give an example of what you see and what you expect to see?

**Comment by rst0git** [comment]
Hi @bethven

If I understand correctly you would like to see the open, close, write, read, etc. syscalls performed by CRIU when doing checkpoint and restore because you want to observe the I/O behaviour.

If this is the case, then you can try the following: 
```
strace -T -ttt -o strace.log <CRIU command>
```

For example:
```
strace -T -ttt -o dump-strace.log ./criu dump -t <PID> -D /tmp/checkpoint_01 --ext-unix-sk --ghost 500M --shell-job --tcp-established -v4 -o dump.log

strace -T -ttt -o restore-strace.log ./criu restore -D /tmp/checkpoint_01 --shell-job --tcp-established -v4 -o restore.log
```

This [article](http://www.admin-magazine.com/HPC/Articles/HPC-Storage-I-O-Profiling) explains well how to profile the I/O pattern of an application.

**Comment by bethven** [comment]
Thank you @adrianreber and @rst0git,  
I have already used strace to draw the checkpoint and restart, but it is not giving me the complete information, that is, observing the log file "dump.log" I see that the processes that execute the checkpoint are not doing the "write" operation shown in the trace file, since it changes the PID number.
That is, when I ran the app and the criu dump, and I did a "ps xaf" to know which PID I was going to checkpoint for, these were the PIDs:
Father mpirun process: PID 5225
Process child 1: PID 5227
Process child 1: PID 5228
Process child 1: PID 5229
Process son 1: PID 5230
When analyzing the strace trace file, these PIDs do not appear. So I checked the log file and there I saw it change it:
In the log file it says the following:
“Seizing 5225's 5226 thread”
“Seizing 5227's 5232 thread”
“Seizing 5228's 5233 thread”
“Seizing 5229's 5231 thread”
“Seizing 5230's 5234 thread”
But the strace is not trace the thread. I used:
strace -fF -tt -e trace=open,close,read,write -o /tmp/checkpoint_01/ckpttraza01.txt ./criu dump -t <PID> -D /tmp/checkpoint_01 --ext-unix-sk --ghost 500M --shell-job --tcp-established -v4 -o dump.log
(whit  -ff  follow forks with output into separate files)

And the -ff is to see the children, but it does not show them 
The threads and sizes appear in the log file but I do not know if they are "write" or "read".
![captura de pantalla de 2018-09-28 19-34-59](https://user-images.githubusercontent.com/38592479/46224114-a86aad00-c355-11e8-92c7-8c25021bf361.png)


I need to analyze the I / O behavior of the checkpoint and restart of CRIU. I expect to see is the amount of writes and read and the sizes of each of these write and read and this should be similar to the size of the images generated by CRIU.

I already did it with the dmtcp and I was able to analyze this behavior. But with CRIU I could not.
Thank you very much.

**Comment by avagin** [comment]
@bethven I don't understand which process you want to trace. Do you want to trace criu processes? Do you want to trace processes when they are being dumped and restored?

If you want to trace criu processes, you can use strace. But if you want to trace processes when they are being dumped, you can't use strace, because criu and strace use the ptrace kernel interface, which doesn't support multiple tracers. A good news is that you can use "perf trace" in this case.

**Comment by bethven** [comment]
@avagin Hi, Thank you very much, I will try with perf trace, I did not know it.
