### ISSUE TITLE
Checkpointing inside a docker container failed

### ISSUE THREAD

**Issue by junjieshen** [checkpoint-restore/criu#563]
Hello,

I was trying to run criu inside a docker container. However I got the following errors when checkpoint a process inside the container. Please note that the first few warnings also appeared when I did `sudo criu check`, which printed `Looks good` in the end.

```
Warn (criu/kerndat.c:792): Can't load /run/criu.kdat
Warn (criu/net.c:2780): Unable to get socket network namespace
Warn (criu/net.c:2780): Unable to get tun network namespace
Warn (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Warn (criu/net.c:2780): Unable to get socket network namespace
Warn (criu/kerndat.c:832): Can't keep kdat cache on non-tempfs
Warn (criu/image.c:133): Failed to open parent directory
Warn  (compel/arch/x86/src/lib/infect.c:273): Will restore 8714 with interrupted system call
Error (soccr/soccr.c:87): Can't turn TCP repair mode ON: Operation not permitted
Error (criu/cr-dump.c:1344): Dump files (pid: 8714) failed with -1
Error (criu/cr-dump.c:1724): Dumping FAILED
```

After some digging and searching, it seems the problem is because of missing some required capabilities which docker has disabled. So I added `--cap-add all` to the container `docker run`, but the problem still exists. The script I used for checkpointing is as follows:

```sudo criu dump -t ${pid} --images-dir ${img_dir} -vvv -o dump.log --tcp-established && echo OK```

The target process requires TCP connection and has been ran for a few minutes.

The docker version is `18.06.1-ce`, and criu version is `3.10`.

Thanks!
Junjie

**Comment by adrianreber** [comment]
Do you get the same error messages with `--cap-add all`? Can you run CRIU with `-v4` and post the log?

**Comment by avagin** [comment]
We run criu tests in docker containers. Here is a command what we use:

docker run --env-file docker.env --rm -it --privileged -v /lib/modules:/lib/modules --tmpfs /run criu-alpine scripts/travis/travis-tests

https://travis-ci.org/checkpoint-restore/criu/jobs/440479369

**Comment by matclab** [comment]
For info, running `criu check -v4` within a `--cap-add all` alpine docker image gives:
```
 criu check -v4
(00.000003) Version: 3.13 (gitid v3.13)
(00.000015) Running on 870404e040a3 Linux 5.2.13-arch1-1-ARCH #1 SMP PREEMPT Fri Sep 6 17:52:33 UTC 2019 x86_64
(00.000026) File /run/criu.kdat does not exist
(00.000051) sockets: Probing sock diag modules
(00.000099) sockets: Done probing
(00.001514) Pagemap is fully functional
(00.001571) Found anon-shmem device at 5
(00.001586) Reset 14's dirty tracking
(00.001608)  ... done
(00.001642) Dirty tracking support is OFF
(00.001718) Found task size of 7ffffffff000
(00.003323) Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
(00.004242) Restoring netdev veth idx 10
(00.004522) Dumping netns links
(00.004548)     LD: Got link 1, type 772
(00.004556)     LD: Got link 10, type 1
(00.005072) Error (criu/uffd.c:264): uffd: Lazy pages are not available: Operation not permitted
(00.005080) Error (criu/kerndat.c:885): Lazy pages are not available
(00.005108) Found mmap_min_addr 0x10000
(00.005121) files stat: fs/nr_open 1073741816
```

**Comment by chris13524** [comment]
I haven't been able to checkpoint inside a Docker container without running the container with `--privileged` first. Is there any way to do this without it running as privileged?

**Comment by adrianreber** [comment]
> Is there any way to do this without it running as privileged?

@chris13524 : no
