### ISSUE TITLE
Error: Snapshot dump failed:  mount, fsnotify

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#565]
To start live migration using LXD my experimental setup is as follows:

Physical machine OS: Ubuntu 16.04
lxc --version 3.0.1
lxd --version 3.0.1
criu --version: 3.9
kernel --version: 4.15.0-29-generic
After successful installation of container named 'c1' i run the following command to save the current states of the container to disk:

 sudo lxc snapshot c1 checkpoint-2 --stateful
`Error: snapshot dump failed
(00.143435) Error (criu/mount.c:1065): mnt: The file system 0x37 0x37 (0x40) btrfs ./ is inaccessible
(00.143441) 
![e1](https://user-images.githubusercontent.com/40225508/47293721-90224100-d628-11e8-8fe4-7ed16fcf89f2.png)
Error (criu/fsnotify.c:215): fsnotify: Can't open mount for s_dev 37, continue
(00.143445) Warn  (criu/fsnotify.c:289): fsnotify: 	Handle 0x37:0x109 cannot be opened
(00.157752) Error (criu/irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.157756) Error (criu/fsnotify.c:292): fsnotify: 	Can't dump that handle
(00.157791) Error (criu/cr-dump.c:1352): Dump files (pid: 19102) failed with -1
(00.173783) Error (criu/cr-dump.c:1706): Dumping FAILED.
`
Any help is greatly appreciated. Solution can be mail at
Email: adityaform@gmail.com
Screenshot attachment is:
![e1](https://user-images.githubusercontent.com/40225508/47293741-a29c7a80-d628-11e8-82ac-2b355ccfd229.png)

**Comment by avagin** [comment]
https://patchwork.kernel.org/patch/2825842/

**Comment by adityacloud1** [comment]
Sir thanks for the response, but still problem is not resolved

**Comment by adityacloud1** [comment]
Problem gets resolved

**Comment by debe** [comment]
So what is the solution on this? The patch above is from 2013, isn't it already merged into current kernels?
I've the same problem on a 4.17 kernel.

**Comment by adityacloud1** [comment]
Dear sir,
In my experimental test-bed case, dump problem is solved by disabling app-armor security feature.

`service apparmor stop
service apparmor teardown`

**Comment by adrianreber** [comment]
The mentioned patch does not seem to be merged in the kernel. If you try another storage backend than btrfs it will probably work.
