### ISSUE TITLE
Error: Failed container creation: Container migration beween two LXD Servers

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#566]
Respected all,
_Greeting of the Day !!!._ I am trying to live migrate container ‘c1’ between 2 LXD servers, with apparmor security feature disabled and experimental setup is:

Physical machine OS: Ubuntu 16.04
lxc --version 3.0.1 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.0.1 (installed from source)
criu --version: 3.10 (installed from source)
kernel --version: 4.15.0-29-generic

Container’s snapshot is created successfully with remote LXD server named as **‘adityacloud,’.** But when I try to live migrate container ‘c1’ using _**lxc move**_ command it gives me following error

`Error: Failed container creation:
 - https://[fd42:b6c9:aaf0:2f4b::1]:8443: Unknown configuration key: image.architecture
 - https://172.16.13.120:8443: Unknown configuration key: image.description
 - https://10.250.213.1:8443: Unknown configuration key: image.os
`
I will post the required information to troubleshoot this error. 

Any help is greatly appreciated.

**Comment by adrianreber** [comment]
At this point this sounds like a LXD error. No criu related errors so far.

**Comment by adityacloud1** [comment]
Thanks sir, for yours valuable response.

**Comment by adityacloud1** [comment]
Problem gets resolved
