### ISSUE TITLE
How to use scripts/criu-ns through RPC ?

### ISSUE THREAD

**Issue by lovemyliwu** [checkpoint-restore/criu#568]
> https://criu.org/CR_in_namespace
is it possible in RPC?

**Comment by lovemyliwu** [comment]
try to solve pid mismatch error when restore

**Comment by adrianreber** [comment]
But then you you just need to run the process in a PID namespace when you start it the first time. Doesn't that work for you?

**Comment by lovemyliwu** [comment]
yes, manually run script work like a charm, but question is our code need auto run restore through RPC :smile:  Thank you answer my question, now the only approach is PID HOLDING.
