### ISSUE TITLE
Restoring checkpoint with network namespace and VETH pair

### ISSUE THREAD

**Issue by planetA** [checkpoint-restore/criu#569]
Hello,

I'm trying to checkpoint/restore a process running inside a network namespace with VETH pair. I also use CRIU in RPC mode, to save the checkpoint.

It seems that saving a checkpoint works OK, but when I try to restore it, I get an error from netlink.

I link the log for [dumping](https://gist.github.com/planetA/b9cfd3b9861fee1c19ea765e6dd8286b#file-dump-log) and for [restoring](https://gist.github.com/planetA/b9cfd3b9861fee1c19ea765e6dd8286b#file-restore-log).

Dumping log has mentioning of veth once:

> (00.093831) Dumping netns links
> (00.093870) Dumping netns links
> (00.093878)     LD: Got link 1, type 772
> (00.093879) The peer link is in the -1 netns with the 1 index
> (00.094140) net/ipv6/conf/lo/stable_secret nr 200
> (00.094180)     LD: Got link 202, type 1
> (00.094188) The peer link is in the 0 netns with the 203 index
> (00.094189) Warn  (criu/net.c:450): The vpeer0 veth is in an external netns
> (00.094190) Found ll addr (ea:../6) for vpeer0

Restoring log reports the error this way:

> (00.006565) Running setup-namespaces scripts
> (00.006569)     RPC
> (00.006789)      1: cg: Cgroups 1 inherited from parent
> (00.006797)      1: Calling restore_sid() for init
> (00.006800)      1: Restoring 1 to 1 sid
> (00.006825)      1: Mount procfs in crtools-proc.Sh5jE0
> (00.022944)      1: Collecting 41/37 (flags 2)
> (00.022985)      1: tty: Collected tty ID 0x49 (pts)
> (00.022997)      1:  `- ... done
> (00.022998)      1: Collecting 42/51 (flags 0)
> (00.023001)      1: No tty-data.img image
> (00.023003)      1:  `- ... done
> (00.023004)      1: Restoring namespaces 1 flags 0x64000000
> (00.028552)      1: kernel/hostname nr 5
> (00.028594)      1: kernel/domainname nr 6
> (00.029824)      1: Try to restore a link 9:202:vpeer0(38.522622)      1: Restoring link vpeer0 type 2
> (38.523815)      1: Restoring netdev vpeer0 idx 202
> (38.523822)      1: Restore ll addr (ea:../6) for device
> (38.523867)      1: Warn  (criu/libnetlink.c:55): ERROR -16 reported by netlink
> (39.617131)      1: Error (criu/net.c:1578): Can't restore link: -16
> (42.657983)      1: Error (criu/util.c:1488): Can't wait or bad status: errno=0, status=65280
> (42.658474) Error (criu/cr-restore.c:2266): Restoring FAILED. 

When I restore i specify additionally parameter "external = veth[vpeer0]:veth0@br0". Vpeer0 is inside the namespace, veth0 is outside and connected to bridge br0.

Could you help me to identify the root cause for the problem with restoring?

**Comment by adrianreber** [comment]
I just did the same for a demo for last week's Open Source Summit:

https://asciinema.org/a/EsrabPHxK3oG33hcUaAzmkL03

But with CLI mode and not RPC. There is always the chance that RPC behaves differently or wrong.

But did you try it with CLI mode? It is interesting to see that you are trying to checkpoint a singularity container. I tried that maybe a year ago and it failed.

Can you run your test with CLI mode? I can try to run my setup (from the demo) with RPC mode to see if it shows the same error, if that would help you?

Maybe the complete set of parameters you are sending to CRIU via RPC would also be good to know.

**Comment by planetA** [comment]
The problem resolved easier than I thought -- I updated to the current master and the error went away. Thank you for the response anyway.
