### ISSUE TITLE
Restored process receives fatal sigsegv soon after restore when using build from latest master commit

### ISSUE THREAD

**Issue by tswift242** [checkpoint-restore/criu#570]
Copied from https://github.com/checkpoint-restore/criu/issues/544#issuecomment-434441076

I believe I've found a regression in criu since version 3.10. When I use docker's C/R feature with a criu build from the latest master commit to checkpoint and restore a basic busybox container, the restored container exits right after the restore finishes with exit code 139, indicating a sigsegv was received. The restore itself is successful, so there's nothing in the restore log. However, I see this in /var/log/syslog:

sleep[2260] bad frame in rt_sigreturn frame:00007f12d0f19000 ip:4abec1 sp:7ffcde4fe898 orax:ffffffffffffffff in sleep[400000+106000].

I actually see 2 occurrences of this. Based on the timestamps, it seems that first one occurs right around when the checkpoint is taken, and the 2nd one is right after the restore completes. I think this is a criu issue and a regression since criu 3.10, as when I revert back to criu 3.10, this issue doesn't reproduce. From my experimentation, it looks like this regression was introduced in between commits e319aaa0cf489488d7796b6abea7f88a21d6e07f and faa8bae6f214d504bd08324a4d684734a88001f2.

Reproduction steps:

1) docker run -d --name test busybox sleep 1000000
2) docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints test test_cp
3) docker rm test
4) docker create --name test busybox sleep 1000000 && docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test_cp test

I'm running on Ubuntu 16.04 with kernel 4.4.0-1070-aws. Architecture is x86_64.

However, this issue does NOT reproduce on an Ubuntu 14.04 instance running kernel 4.14.78 with x86_64 architecture. So it looks like kernel version may matter. In both cases, these instances are running on AWS EC2 and so are VMs using the Xen hypervisor.

I found this link from 2 years ago which contains the exact error I'm seeing and mentions a kernel change which may have impacted criu: https://www.openwall.com/lists/kernel-hardening/2016/03/31/14. Not sure if that's relevant here.

Attached is a zip of a checkpoint which reproduces this issue
[test_cp.zip](https://github.com/checkpoint-restore/criu/files/2531457/test_cp.zip)

EDIT: I've narrowed it down further. Looks like the issue was introduced between commits dd4c0c6b22d3e3ede23cff9ac43786f5f00948ec and 9166f90e5813b06d96296416215de5f3beeb67b7. I'm unable to narrow it down more; it looks like these several commits are part of the same patch set as when I use a build from one of the middle commits the dump fails.

**Comment by cyrillos** [comment]
I'll take a look once time permit

**Comment by avagin** [comment]
I can't reproduce this issue. I used a t2.micro ubuntu 16.04 instance.

```
root@ip-172-31-47-73:/home/ubuntu/criu# docker run -d --name test busybox sleep 1000000
a32151c33cd86a06d32c85ddbfe2fc49722ad54be593d3661b20c9bc19311c4e
root@ip-172-31-47-73:/home/ubuntu/criu# docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints test test_cp
Error response from daemon: Cannot checkpoint container test: rpc error: code = 6 desc = mkdir /var/lib/docker/checkpoints/test_cp: file exists
root@ip-172-31-47-73:/home/ubuntu/criu# rm -rf /var/lib/docker/checkpoints/test_cp
root@ip-172-31-47-73:/home/ubuntu/criu# docker checkpoint create --checkpoint-dir /var/lib/docker/checkpoints test test_cp
test_cp
root@ip-172-31-47-73:/home/ubuntu/criu# docker rm test
test
root@ip-172-31-47-73:/home/ubuntu/criu# docker create --name test busybox sleep 1000000 && docker start --checkpoint-dir /var/lib/docker/checkpoints --checkpoint test_cp test
31365ff50b85a4651a509a21fe6a0d233caef38152661569740e566b23ccf20f
root@ip-172-31-47-73:/home/ubuntu/criu# echo $?
0
root@ip-172-31-47-73:/home/ubuntu/criu# ps axf | grep "sleep 100" -B 5
 5904 ?        Ssl    0:00 /usr/bin/dockerd -H fd://
 5911 ?        Ssl    0:00  \_ docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
 6619 ?        Sl     0:00      \_ docker-containerd-shim 31365ff50b85a4651a509a21fe6a0d233caef38152661569740e566b23ccf20f /var/run/docker/libcontainerd/31365ff50b85a4651a509a21fe6a0d233caef38152661569740e566b23ccf20f docker-runc
 6635 ?        Ss     0:00          \_ sleep 1000000
root@ip-172-31-47-73:/home/ubuntu/criu# uname -a
Linux ip-172-31-47-73 4.4.0-1070-aws #80-Ubuntu SMP Thu Oct 4 13:56:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ip-172-31-47-73:/home/ubuntu/criu# cat /proc/cpuinfo  | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single kaiser fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
```

**Comment by avagin** [comment]
@tswift242 Could you try to run a zdtm test?
python test/zdtm.py run -t zdtm/static/env00

What amazon instance do you use?
Could you show /proc/cpuinfo for it?

**Comment by cyrillos** [comment]
@avagin Andrew, I don't remember if I send you a fix https://src.openvz.org/projects/OVZ/repos/criu/commits/1920fe488456e663ac8000eb675b91c938051d1e

**Comment by cyrillos** [comment]
But it may trigger if only we're restoring from old images.

**Comment by cyrillos** [comment]
And can't cause SIGSEGV. From the commits @tswift242 mentioned I dont see what can cause SIGSEGV.

**Comment by tswift242** [comment]
@avagin @cyrillos You're right; looks like this is hardware specific. This issue reproduces for me on a t3 EC2 instance but NOT on a t2, using the same AMI. I've attached the contents of /proc/cpuinfo for both the t3 and t2. The t3 cpus are newer and have some extra flags, including some that seem like they could be related to the commits I mentioned above, such as "xsavec".
[cpuinfo_t2.txt](https://github.com/checkpoint-restore/criu/files/2549716/cpuinfo_t2.txt)
[cpuinfo_t3.txt](https://github.com/checkpoint-restore/criu/files/2549717/cpuinfo_t3.txt)

**Comment by tswift242** [comment]
@avagin It looks like it's a combination of specific hardware and kernel versions that reproduce the issue when using a criu build from after commit dd4c0c6b22d3e3ede23cff9ac43786f5f00948ec (e.g. criu 3.11).

Attached is the output of /proc/cpuinfo from the same t3.2xlarge instance type, but launched with an AMI that has kernel 4.15 instead of 4.4. Notice the cpu flags are different than in cpuinfo_t3.txt. With the 4.15 kernel, the issue does not reproduce.
[cpuinfo_t3_kernel_4-15.txt](https://github.com/checkpoint-restore/criu/files/2566651/cpuinfo_t3_kernel_4-15.txt)

So as a summary:
t3 instance + Ubuntu 16.04.5 + GA ubuntu kernel (4.4.x): issue reproduces
t3 instance + Ubuntu 16.04.5 + HWE ubuntu kernel (4.15.x): issue does NOT reproduce
t2 instance + Ubuntu 16.04.5 + GA ubuntu kernel: issue does NOT reproduce

If I use a criu buiild from dd4c0c6b22d3e3ede23cff9ac43786f5f00948ec or earlier (e.g. criu 3.10), the segv does not reproduce in any of the above 3 scenarios.

**Comment by avagin** [comment]
This cpu supports the compacted format of xstate and criu uses it to fill sigframe. The 4.4 kernel can't handle this format and this can be a reason why a process is segfaulted. I am not sure about this. @cyrillos  should know more about this.

**Comment by avagin** [comment]
Cc: @0x7f454c46

**Comment by cyrillos** [comment]
Well, the userspace API always use standard form, while kernel internally can use compacted one. Inside criu we always operate with standard format as well while trying to detect compacted form for debug reason. Still if I remember correctly there were various fixes for kernel code. Thus if it works for kernel-4.15 series I would suggest to simply stick with it.

**Comment by tswift242** [comment]
@avagin @cyrillos Thanks for the info. I may be able to stick with kernel 4.15.x but as an fyi the 4.4 kernel + newer cpu combination may not be all that uncommon across different users. Kernel 4.4 is the default for cloud Ubuntu 16.04 images, and while I haven't confirmed this I'm guessing the issue reproduces for many (if not all) of the newer EC2 instance types. So instances like r5 and m5 in addition to t3. Is there a way to detect if the kernel can handle a particular xstate format?

**Comment by cyrillos** [comment]
I'll try to figure out more. I suspect there might be a case where we provide more modern xsave frame which kernel doesn't know about. This is a problem actually, I suspect it might indeed lead to sigsegv. The only option to handle such situation is to parse cpuinfo kernel provides :-(

**Comment by cyrillos** [comment]
t3 machine has cpu with PKU feature, which we of course fetch and try to restore, but 4.4 kernel series doesn't handle it well. I think it is the reason of problem. Could you try kernel 4.5 somehow?

**Comment by avagin** [comment]
I found that zdtm/static/env00 passes with the next patch on the 4.4 kernel. Now we need to explain this behavior.

```

diff --git a/criu/arch/x86/crtools.c b/criu/arch/x86/crtools.c
index ee016da..95f0eb2 100644
--- a/criu/arch/x86/crtools.c
+++ b/criu/arch/x86/crtools.c
@@ -125,7 +125,6 @@ int save_task_regs(void *x, user_regs_struct_t *regs, user_fpregs_struct_t *fpre
                assign_xsave(XFEATURE_OPMASK,   xsave, opmask_reg,      extended_state_area);
                assign_xsave(XFEATURE_ZMM_Hi256,xsave, zmm_upper,       extended_state_area);
                assign_xsave(XFEATURE_Hi16_ZMM, xsave, hi16_zmm,        extended_state_area);
-               assign_xsave(XFEATURE_PKRU,     xsave, pkru,            extended_state_area);
        }
 
 #undef assign_reg
@@ -491,7 +490,6 @@ int restore_fpu(struct rt_sigframe *sigframe, CoreEntry *core)
                        assign_xsave(XFEATURE_OPMASK,   xsave, opmask_reg,      extended_state_area);
                        assign_xsave(XFEATURE_ZMM_Hi256,xsave, zmm_upper,       extended_state_area);
                        assign_xsave(XFEATURE_Hi16_ZMM, xsave, hi16_zmm,        extended_state_area);
-                       assign_xsave(XFEATURE_PKRU,     xsave, pkru,            extended_state_area);
                }
 
                x->xsave_hdr.xstate_bv  = xstate_bv;
```

**Comment by avagin** [comment]
commit c8df40098451ba18a43f22b563c9129182353158
Author: Dave Hansen dave.hansen@linux.intel.com
Date: Fri Feb 12 13:02:04 2016 -0800

x86/fpu, x86/mm/pkeys: Add PKRU xsave fields and data structures

[avagin@laptop linux]$ git describe c8df40098451ba18a43f22b563c9129182353158
v4.5-rc4-78-gc8df40098451
[avagin@laptop linux]$ git describe c8df40098451ba18a43f22b563c9129182353158v4.5-rc4-78-gc8df40098451
--

**Comment by cyrillos** [comment]
I already pointed, that we're using bare metal features from cpuid, but seems the kernel is too old for such processors.

**Comment by 0x7f454c46** [comment]
Maybe detect it by the size returned with NT_X86_XSTATE?

**Comment by cyrillos** [comment]
> Maybe detect it by the size returned with NT_X86_XSTATE?
Features may have same size but different meaning. The only reliable way to find what exactly kernel supports is to parse `/proc/cpuinfo`, which I really don't want to do. Because `/proc/cpuinfo` has never been an ABI. As an option I think of adding an ability for user to disable some of features via command line.

**Comment by cyrillos** [comment]
The case where criu is too modern for a kernel :-)

**Comment by 0x7f454c46** [comment]
Unfortunately, `X86_FEATURE_PKU` is not printed in cpuinfo.
In a long-term it might be more desirable either add it there or print features on some procfs knob, not only in init dmesg:
```
Oct 17 02:53:22 kernel: x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Oct 17 02:53:22 kernel: x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Oct 17 02:53:22 kernel: x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
Oct 17 02:53:22 kernel: x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
Oct 17 02:53:22 kernel: x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
Oct 17 02:53:22 kernel: x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
Oct 17 02:53:22 kernel: x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
Oct 17 02:53:22 kernel: x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
Oct 17 02:53:22 kernel: x86/fpu: Enabled xstate features 0x1f, context size is 960 bytes, using 'compacted' format.
```

**Comment by 0x7f454c46** [comment]
The other way non-requiring a kernel patch (valid for older kernels) - would be a kdat test, which would assign some magic constants to extended states and check which are provided by Linux. Shouldn't be too hard.

FWIW, I also don't see a pkru zdtm test - it might not work now too ;)

**Comment by cyrillos** [comment]
> FWIW, I also don't see a pkru zdtm test - it might not work now too ;)
All features more modern than plain AVX (ie ymm registers) were not tested simply because I don't have this kind of hardware.

**Comment by cyrillos** [comment]
And also I wonder how libc happen to work on such machines. Last timer we were investigating xsave bug (due to frame size change) together with @avagin , we saw that libc has been using similar code to us -- they call for xsave with all bits set, ie they didn't rely on what kernel is supporting but rather fetching frame size from cpu directly.
