### ISSUE TITLE
Contaier migration with LXD Build from source got stuck at " sending write barrier "

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#571]
Respected all,
Greeting of the Day !!!. I am trying to live migrate container ‘c2’ between two LXD servers,and experimental setup is:

Physical machine OS: Ubuntu 16.04
lxc --version 3.0.1 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.0.1 (installed from source)
criu --version: 3.10 (installed from source)
kernel --version: 4.15.0-29-generic

When I run command to migrate container, in starting seconds data is transferred then it got stuck at source server with the message
`Transferring container: checkpoint-2: 24.53MB (24.53MB/s)`

Screenshot for `lxc info is`

![lxc info c2](https://user-images.githubusercontent.com/40225508/47843082-8ea10780-dde4-11e8-8a77-8fe69052b38a.png)

A screenshot for c2 snapshot migrated at remote server is:
![c2 stopped](https://user-images.githubusercontent.com/40225508/47842980-3ec24080-dde4-11e8-9563-925d31354c06.png)

 A screenshot of lxd --debug is:
![lxd deubg](https://user-images.githubusercontent.com/40225508/47842992-4681e500-dde4-11e8-9686-01f31de989a9.png)

I looked for the error message `The other side does support pre-copy `
', but did not get any solution.

**Comment by rst0git** [comment]
Hi @adityacloud1 

The message `The other side does support pre-copy` is not an error. It indicates that the LXD has support [`pre-copy`](https://en.wikipedia.org/wiki/Live_migration#Pre-copy_memory_migration) optimisation.

From the information here I think that the issue might be in LXD rather than CRIU.
Could you please create an LXD issue including [log files](https://stgraber.org/2017/02/27/lxd-2-0-debugging-and-contributing-to-lxd-1212/)?

**Comment by adityacloud1** [comment]
Respected sir,
lxd.log is not located anywhere, but log messages of /var/log/lxd/c2# gedit lxc.log are:
`lxc 20181101154157.771 TRACE    lxc_commands - commands.c:lxc_cmd_rsp_recv:136 - Command "get_state" received response
lxc 20181101154157.771 DEBUG    lxc_commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc 20181101154157.771 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:584 - Container "c2" is in "RUNNING" state
lxc 20181101154157.837 TRACE    lxc_commands - commands.c:lxc_cmd_rsp_recv:136 - Command "get_state" received response
lxc 20181101154157.837 DEBUG    lxc_commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc 20181101154157.838 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:584 - Container "c2" is in "RUNNING" state
lxc 20181101154157.852 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type u nsid 0 hostid 165536 range 65536
lxc 20181101154157.852 INFO     lxc_confile - confile.c:set_config_idmaps:1666 - Read uid map: type g nsid 0 hostid 165536 range 65536
lxc 20181101154157.852 TRACE    lxc_commands - commands.c:lxc_cmd_rsp_recv:136 - Command "get_state" received response
lxc 20181101154157.852 DEBUG    lxc_commands - commands.c:lxc_cmd_rsp_recv:160 - Response data length for command "get_state" is 0
lxc 20181101154157.852 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:584 - Container "c2" is in "RUNNING" state`

2. lxd --verbose
![lxd --verbose](https://user-images.githubusercontent.com/40225508/47862594-80baa900-de1b-11e8-83f9-420246604359.png)

**Comment by adityacloud1** [comment]
Respected all,

Any comment please !!

**Comment by adityacloud1** [comment]
Respected all,
Any update to sort-out above stated issue.

**Comment by adrianreber** [comment]
This does not look like a CRIU problem. Unfortunately not much we can do here for you. I would recommend talking to LXD about this. Closing for now. Please re-open if you have CRIU error logs.

**Comment by adityacloud1** [comment]
Thanks a lot sir for yours response
