### ISSUE TITLE
aarch64 build: libcompel.so.1.0: undefined symbol: __page_size

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/criu#572]
This was reported privately on my G+ by Alexey Shabalin, he says that since 3.10 the build on aarch64 is broken:

> Verifying ELF objects in /usr/src/tmp/crtools-buildroot (arch=normal,fhs=normal,lfs=relaxed,lint=relaxed,rpath=normal,stack=normal,textrel=normal,unresolved=normal)
> verify-elf: ERROR: ./usr/lib64/libcompel.so.1.0: undefined symbol: __page_size
> error: Bad exit status from /usr/src/tmp/rpm-tmp.20687 (%install)

(the above is taken from http://git.altlinux.org/tasks/216063/build/100/aarch64/log).

It looks like the relevant change was introduced by commit ffa1a03c8f11. Obviously I can't repro this on x86_64.

//cc @0x7f454c46

**Comment by shaba** [comment]
Hi. I think  commit https://github.com/checkpoint-restore/criu/commit/2d965008d367455e792e0938dd13656a85dabf14 more relevant for this issue.
May be:
1)  delete
unsigned __page_size = 0;
unsigned __page_shift = 0;
in aarch64/crtools.c and ppc64/crtools.c
2) delete "extern" from 
  extern unsigned __page_size;
  extern unsigned __page_shift;
in aarch64/asm/page.h and ppc64/asm/page.h

**Comment by 0x7f454c46** [comment]
Hey,

Was on a vacation the last week.
@shaba, could you try this patch? https://github.com/0x7f454c46/criu/commit/f804846d2d6be3f4a1a45d7ab38b6b2f01a541ab
@adrianreber, could you try it on your setup with long pages, to make sure it doesn't break?

At this moment I don't have suitable env to check it, but Travis-CI aarch64/ppc64 build is passing, so it has chances to work properly.

Thanks,
Dima

**Comment by shaba** [comment]
I was try build v3.11 with this patch and have another error:
verify-elf: ERROR: ./usr/lib64/libcompel.so.1.0: undefined symbol: opts
for both arch - x86_64 and aarch64.

Please see:
http://git.altlinux.org/tasks/216063/build/200/aarch64/log
http://git.altlinux.org/tasks/216063/build/200/x86_64/log

**Comment by 0x7f454c46** [comment]
@shaba, hmm, what if those two patches on a top of the previous?
https://github.com/0x7f454c46/criu/commits/__page_size-compel

**Comment by adrianreber** [comment]
I actually tried to build 3.11 on aarch64 on Centos 7 and all active Fedora branches and there are now problems during the build. But the RPMs I am building are not running the verify-elf step. Would be interesting to know what actually happens during verify-elf? Maybe also something for CRIU CI.

**Comment by shaba** [comment]
> @shaba, hmm, what if those two patches on a top of the previous?
> https://github.com/0x7f454c46/criu/commits/__page_size-compel

v3.10 with patch was build successfully.

**Comment by kolyshkin** [comment]
This should be fixed by https://patchwork.criu.org/series/3204/
