### ISSUE TITLE
Dumping Failed when "efi" in /sys/firmware

### ISSUE THREAD

**Issue by phenix317** [checkpoint-restore/criu#574]
Hello,

It seems that we have found another problem during the dump part of the live migration, dump failed and the error showed in the log is:

Error (criu/mount.c:643): mnt: FS mnt ./sys/firmware/efi/efivars dev 0x1a root / unsupported id 110 

The Hosting Machine information:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
kernel version: 4.4.0-62-generic (i tried with 4.13 same error)

############################################################################CRIU: Version: 3.11

############################################################################
LXC: 

2.0.9

The dump log: 
[dump.log](https://github.com/checkpoint-restore/criu/files/2591832/dump.log)

BR,

**Comment by cyrillos** [comment]
This is due to lack of support this FS in criu. I think you should try to point criu to consider such mount as external one https://criu.org/External_bind_mounts
cc: @avagin

**Comment by adrianreber** [comment]
If CRIU does not handle it automatically this requires code changes to https://github.com/lxc/lxc/blob/master/src/lxc/criu.c

**Comment by cyrillos** [comment]
actually efivars is a special fs type. I'll take a look.
