### ISSUE TITLE
runc restore with host network disables networking

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#577]
Running runc restore on a container with host networking leaves a iptables DROP rules active after restore, blocking all network traffic. The corresponding unlock is not run.

This seems to be related to locking in cr-restore.c:
```
        if (opts.empty_ns & CLONE_NEWNET) {
                /*
                 * Local TCP connections were locked by network_lock_internal()
                 * on dump and normally should have been C/R-ed by respectively
                 * dump_iptables() and restore_iptables() in net.c. However in
                 * the '--empty-ns net' mode no iptables C/R is done and we
                 * need to return these rules by hands.
                 */
                ret = network_lock_internal();
                if (ret)
                        goto out_kill;
        }
```

and unlocking in net.c
```
        if (root_ns_mask & CLONE_NEWNET) {
                run_scripts(ACT_NET_UNLOCK);
                network_unlock_internal();
        }
```

Both steps (lock and unlock) are wrapped with an `if`, but with different conditions.

As I am calling it from runc it could also be that runc sets empty_ns incorrectly.

In the tests I have done runc sets opts.empty_ns to 40000000 which matches CLONE_NEWNET. So the lock works. Not clear yet if runc maybe just should not set it to that value.

Should CRIU lock and unlock or should CRIU skip lock as well as unlock when the container is running in the host network namespace?

**Comment by adrianreber** [comment]
@avagin any ideas?

**Comment by avagin** [comment]
network_unlock_internal() should be called only if a network namespace is restored. Could you try this patch:

```
diff --git a/criu/cr-restore.c b/criu/cr-restore.c
index 39a6d994..13b0350d 100644
--- a/criu/cr-restore.c
+++ b/criu/cr-restore.c
@@ -2143,7 +2143,7 @@ static int restore_root_task(struct pstree_item *init)
                        goto out_kill;
        }
 
-       if (opts.empty_ns & CLONE_NEWNET) {
+       if (root_ns_mask & opts.empty_ns & CLONE_NEWNET) {
                /*
                 * Local TCP connections were locked by network_lock_internal()
                 * on dump and normally should have been C/R-ed by respectively
```

**Comment by adrianreber** [comment]
@avagin with that patch CRIU does not run iptables-restore at all during checkpoint and restore. Works for me.

**Comment by avagin** [comment]
This was broken in this commit:
```
commit cde33dcb06394e1654018045ac78244fa95af4d2
Date:   Tue Nov 15 17:08:00 2016 +0300

    empty-ns: Don't C/R iptables too (v2)
```

**Comment by avagin** [comment]
@adrianreber can we close this issue?

**Comment by adrianreber** [comment]
Yes, just verified it once more, it is fixed.
