### ISSUE TITLE
How to use CRIU with MPI?

### ISSUE THREAD

**Issue by cherieLi** [checkpoint-restore/criu#580]
When I try to set a CRIU checkpoint for a MPI program, there are errors like these:
Warn  (criu/arch/x86/crtools.c:133): Will restore 25766 with interrupted system call
Warn  (criu/arch/x86/crtools.c:133): Will restore 25767 with interrupted system call
Error (criu/files-reg.c:660): Can't dump ghost file /dev/shm/mpich_shar_tmpd1Mvam of 8522576 size, increase limit
Error (criu/cr-dump.c:1210): Collect mappings (pid: 25768) failed with -1
Error (criu/cr-dump.c:1628): Dumping FAILED.
I don't know how to solve this problem. Can you give me a example about the use with a MPI program? Thank you very much~

**Comment by rst0git** [comment]
Hi @cherieLi the error here is `Can't dump ghost file .. of 8522576 size`.

Try to use `--ghost-limit` on dump (e.g. `criu dump --ghost-limit 100M ...`)

You can find more information about this option in https://criu.org/Invisible_files

BTW: Which version of CRIU is this?

**Comment by cherieLi** [comment]
@rst0git  I have solved it by using --ghost-limit on dump.   I really appreciate it.  The version of CRIU is 2.6.

**Comment by cherieLi** [comment]
@adrianreber No other problems. Of course, close it.

**Comment by adrianreber** [comment]
@cherieLi cool, let us know if there are any other problems.
