### ISSUE TITLE
[Question] What memory pages' types does CRIU dump when checkpointing a process?

### ISSUE THREAD

**Issue by ramikhateeb** [checkpoint-restore/criu#583]
I'm trying to study CRIU tool (Behavior & Source code) to use it in my research study. But I've got confused about two points:

1. Does CRIU dump all memory pages regardless of their type? Does it dump file mappings and the read-only ones?
2. Does CRIU use a kind of compression to reduce the resulting image files size? because I noticed a considerable reduction of the images size compared to the summation of memory pages' sizes.

**Comment by rst0git** [comment]
Hi @ramiissat it is great to see that you have an interest in CRIU. A good starting point for your study are the following wiki pages:
* https://criu.org/Checkpoint/Restore
* https://criu.org/What_cannot_be_checkpointed
* https://criu.org/Memory_dumping_and_restoring
* https://criu.org/Memory_dumps
* https://criu.org/Images
* https://criu.org/Invisible_files 
... and most of the pages in the category [_Under the hood_](https://criu.org/Category:Under_the_hood).

With regards to your questions:
>Does CRIU dump all memory pages regardless of their type?

For a process to be restored successfully (e.g. on a different machine) the checkpoint must contain all memory pages that are used by the process.

>Does it dump file mappings and the read-only ones?

I think the answer you are looking for is in https://criu.org/Shared_memory

>Does CRIU use a kind of compression to reduce the resulting image files size?

No, but this could/should be implemented in the future.

**Comment by ramiissat** [comment]
Thank you @rst0git , I've already checked out the links you have mentioned, but I'll give them another review in case I missed something, then return back to this thread. Thanks.

**Comment by avagin** [comment]
> Does CRIU dump all memory pages regardless of their type? Does it dump file mappings and the read-only ones?

CRIU dumps non-zero pages of private and shared anonymous mappings, dirty pages of private file mappings.

> Does CRIU use a kind of compression to reduce the resulting image files size? because I noticed a considerable reduction of the images size compared to the summation of memory pages' sizes.

How do you calculate the summation of memory pages' sizes.  Do you analize /proc/*/smaps?

**Comment by mcopik** [comment]
@avagin @rst0git I'm trying to understand the memory dumping process of criu and I have similar question. I wanted to ask on the mailing list but it seems to be a place for regular development work. I hope this is a right place to ask this question.

1. To summarize:
- for file mapping, CRIU will dump dirty pages of private mapping. Shared pages and private clean pages re ignored. Questions:  what's the rationale behind skipping shared dirty mappings? If the process is restored later, there's no guarantee that the contents of pagecache didn't change.
- for anonymous pages, non-zero private and shared pages are dumped
- this applies only to physically existing pages (marked as Referenced in `smaps`).
2. If there is a page marked in `smaps` as Referenced and classifies as dumpable but it does not show up in CRIU's pagemap, then it was a zero page. Is there any other reason why a page was skipped?

My motivation: I'm trying to understand memory sharing behavior and CRIU works very well for that. However, I want to know how many pages are zero as well.

**Comment by mcopik** [comment]
Following up on my previous comment, I found that I have trouble understanding the CRIU dumping process. In this example, I see in `pmaps` and `smaps` output, taken right before dumping the process, that the out of 5 pages allocated for file mapping for the application, two pages are marked as anonymous and dirty and dumped but one of private clean pages is still dumped: page  `0x56275cb3e000`. Do you know what might be the reason?

```
56275cb3d000-56275cb3e000 r--p 00000000 08:02 548481                   test_app.exe
Size:                  4 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   4 kB
Pss:                   4 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         4 kB
Private_Dirty:         0 kB
Referenced:            4 kB
Anonymous:             0 kB
VmFlags: rd mr mw me dw sd 
56275cb3e000-56275cb3f000 r-xp 00001000 08:02 548481                    test_app.exe
Size:                  4 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   4 kB
Pss:                   4 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         4 kB
Private_Dirty:         0 kB
Referenced:            4 kB
Anonymous:             0 kB
VmFlags: rd ex mr mw me dw sd 
56275cb3f000-56275cb40000 r--p 00002000 08:02 548481                     test_app.exe
Size:                  4 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   4 kB
Pss:                   4 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         4 kB
Private_Dirty:         0 kB
Referenced:            4 kB
Anonymous:             0 kB
VmFlags: rd mr mw me dw sd 
56275cb40000-56275cb41000 r--p 00002000 08:02 548481                     test_app.exe
Size:                  4 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   4 kB
Pss:                   4 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         4 kB
Referenced:            4 kB
Anonymous:             4 kB
VmFlags: rd mr mw me dw ac sd 
56275cb41000-56275cb42000 rw-p 00003000 08:02 548481                     test_app.exe
Size:                  4 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:                   4 kB
Pss:                   4 kB
Shared_Clean:          0 kB
Shared_Dirty:          0 kB
Private_Clean:         0 kB
Private_Dirty:         4 kB
Referenced:            4 kB
Anonymous:             4 kB
VmFlags: rd wr mr mw me dw ac sd 
```

**Comment by avagin** [comment]
> 1. To summarize:
> 
> * for file mapping, CRIU will dump dirty pages of private mapping. Shared pages and private clean pages are ignored. (edited) If I understand correctly, shared file-maped pages are out of the control of the process and managed by kernel's pagecache. Therefore, the only pages that CRIU has to dump are private file mappings. Is it correct?

yes, it is

> * for anonymous pages, non-zero private and shared pages are dumped no matter if they are clean or dirty?

What do you mean when you are saying  " clean or dirty" in term of anonymous pages?

> * this applies only to physically existing pages (marked as Referenced in `smaps`).

Probably, you are right. We read /proc/PID/pagemap to understand which pages have to be dumped.

> 
> 1. If there is a page marked in `smaps` as Referenced and classified as dumpable but it does not show up in CRIU's pagemap, then it was a zero page. Is there any other reason why a page was skipped?

I don't remember any other reasons.

> 
> My motivation: I'm trying to understand memory sharing behavior and CRIU works very well for that. However, I want to know how many pages are zero as well.

In criu, zero_page means that it has not been touched ( the kernel has not mapped a physical page).
https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/mem.c#L87

If a process writes zero-s into a page, criu will dump it.
