### ISSUE TITLE
[Question] tun issues while restoring

### ISSUE THREAD

**Issue by marekzmyslowski** [checkpoint-restore/criu#585]
Hello,
When I'm doing the dump, on my PC there is an OpenVPN interface /dev/net/tun. Later, I'm trying to restore inside docker container where this interface doesn't exist. Of course the "--privileged" option for docker run solves that issue but I was wondering if there is a different way so I don't need to use it (no to dump tun, create manually)?

Regards
Marek

**Comment by adrianreber** [comment]
Are you checkpointing OpenVPN outside of a container and then restoring into a container? To successfully dump tun device you need to have a network namespace. How is the initial tun device created?

**Comment by marekzmyslowski** [comment]
>Are you checkpointing OpenVPN outside of a container and then restoring into a container?

Yes
>How is the initial tun device created?

It was created by the Open VPN. I didn't do anything manually.

`Warn  (criu/net.c:2840): Unable to get socket network namespace
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Error (criu/net.c:3131): Unable create a network namespace: Operation not permitted`

**Comment by marekzmyslowski** [comment]
BTW I'm not checkpointing OpenVPN. I'm checkpointing simple shell application.

**Comment by adrianreber** [comment]
So, what has the shell script to do with OpenVPN. I do not really understand what you are trying to do.

**Comment by marekzmyslowski** [comment]
So on my regular Ubuntu system I have a simple app (few line of C code that do only print). To create checkpoint:
1. Run the application and stop it in the middle with SIGSTOP
2. Do the snapshot with 
`criu dump --manage-cgroups --shell-job -s -D /work/test  -t 1234`

Then I'm trying to restore the job inside docker container
1. Run the docker
`docker run --rm -it   -v /work/:/work/ ubu`
2. Restore the application
`root@f7c5068fa5b7:/work# criu restore --shell-job --manage-cgroups -d -D /work/test
Error (criu/util.c:816): exited, status=3
Error (criu/util.c:816): exited, status=3
Warn  (criu/net.c:2840): Unable to get socket network namespace
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Operation not permitted
Error (criu/net.c:3131): Unable create a network namespace: Operation not permitted
Warn  (criu/net.c:3177): NSID isn't reported for network links
Error (criu/uffd.c:264): uffd: Lazy pages are not available: Operation not permitted
Error (criu/kerndat.c:927): Lazy pages are not available
`

If I use the "--privileged" option for docker there is no problem. I'm not sure but what I read the tun interface/device (/dev/net/tun) can cause the problem with restore.

Regards
Marek

**Comment by adrianreber** [comment]
Not really sure what `--privileged` does, but it sounds like you are missing privileges to create the necessary network namespace properties. Maybe using CRIU with:
```
  -J|--join-ns NS:{PID|NS_FILE}[,OPTIONS]
			Join existing namespace and restore process in it.
			Namespace can be specified as either pid or file path.
			OPTIONS can be used to specify parameters for userns:
			    user:PID,UID,GID
```
could work. To join the existing network namespace. You could also run `criu check` to see if CRIU thinks the privileges in the container are actually enough. But, as mentioned, not sure what is missing when running without `--privileged`.

**Comment by rst0git** [comment]
The `--privileged` flag gives all capabilities to the container.
@marekzmyslowski if you don't want to use this flag, you can play around with the docker's `--cap-add` option to enable only the required capabilities.

**Comment by marekzmyslowski** [comment]
@rst0git I did experiments and they show that it is not the same (in the first case the app was restored):
marian@:/work$ docker run --rm -it  --privileged  -v /work/:/work/ ubu
root@80b7deda6635:/work# criu restore -d -D /work/checkpoints/test1 --shell-job
Warn  (criu/net.c:2867): Unable to get tun network namespace
Warn  (criu/kerndat.c:881): Can't keep kdat cache on non-tempfs                                                                                                                                                                                          
root@80b7deda6635:/work# ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD                                                                                                                                                                           
4 S root         1     0  0  80   0 -  4627 wait   14:16 pts/0    00:00:00 /bin/bash                                                                                                                                                                     
5 T root        98     1  0  80   0 -  1094 signal 14:16 pts/0    00:00:00 /work/example/test1                                                                                                                                                    
0 R root        99     1  0  80   0 -  8600 -      14:16 pts/0    00:00:00 ps -elf                                                                                                                                                                       
- - -                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
marian@:/work$ docker run --rm -it  --cap-add ALL  -v /work/:/work/ ubu
root@7c000e7de9db:/work# criu restore -d -D /work/checkpoints/test1 --shell-job
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory                                                                                                                                                                              
Error (criu/uffd.c:263): uffd: Lazy pages are not available: Operation not permitted                                                                                                                                                                     
Error (criu/kerndat.c:927): Lazy pages are not available                                                                                                                                                                                                 
root@7c000e7de9db:/work# ps -elf
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN  STIME TTY          TIME CMD                                                                                                                                                                           
4 S root         1     0  0  80   0 -  4627 wait   14:16 pts/0    00:00:00 /bin/bash                                                                                                                                                                     
0 R root        23     1  0  80   0 -  8600 -      14:16 pts/0    00:00:00 ps -elf                                                                                                                                                                       

Regards
Marek

**Comment by marekzmyslowski** [comment]
@rst0git  It helped but it is not a solution.
After a reading a lot and few experiments I decided that I'm not able to run this without privileged mode.
Thank you for your help @rst0git  @adrianreber . I have another question but I think new thread will be better.
