### ISSUE TITLE
Modify resources restore-time using CRIT daemon

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#59]
Sometimes it might make sense to tune the objects from images on restore. E.g. change the IP address of sockets from task above or fix file paths to be "chroot-ed". The best solution seems to be in launching CRIT in daemon mode, telling it what images and how to modify and teaching CRIU to "filter" the pb objects read from images through this daemon. 

Pulled from criu.org/Todo

**Comment by k-artem** [comment]
Also will be good if we'll have a possibility(using this idea) to change PID's  for a avoiding this problem http://criu.org/When_C/R_fails.

**Comment by avagin** [comment]
It's already possible. It's maybe inconvenient, but it works.
```
./crit decode -i pstree.img | sed "s/\"pid\": 32486/\"pid\": 9999/" | ./crit encode > pstree.img.new
mv pstree.img.new pstree.img
```

**Comment by xemul** [comment]
Changing pids is not possible, sorry guys. Glibc caches the result of getpid() call and uses it widely. If the _actual_ pid changes, then thing can get broken inside glibc with weird diagnostics.
