### ISSUE TITLE
Cannot checkpoint container: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0". Error in dump.log is : Can't turn TCP repair mode ON: Operation not permitted.

### ISSUE THREAD

**Issue by wangzhao123456** [checkpoint-restore/criu#592]
Hi, everyone
I run firefox browser in container using VNC server, and the display of firefox browser is visited through VNC client. I can successfully checkpoint/restore the contianer using "docker checkpoint create" command and "docker start --checkpoint" command.
But I found some strange phenomena.
When I open VNC client to visit firefox browser, I can't checkpoint the container. The error is :Cannot checkpoint container: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0"
Error in dump.log is : Can't turn TCP repair mode ON: Operation not permitted.
When I close VNC client, I can't checkpoint the container either at the first several attempts, but after enough times of attempts(may be 10 times),  I successfully checkpoint my container. I check the error log, the main difference between the failed "dump.log" and the success "dump.log" is that the failed "dump.log" contains "Can't turn TCP repair mode ON: Operation not permitted" error. And I run docker checkpoint/restore command as root user.
I create the container using the follow command:
# docker run --name firefox-vnc -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -d -p 5900:5900 --net=host --privileged devopsil/vnc-firefox

The system environment is shown as follows and the failed "dump.log" and success "dump.log" is attached in the end.

# uname -a 
Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:13 2017
 OS/Arch:      linux/amd64
 Experimental: true

# docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 5
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 983.9MiB
Name: ubuntu
ID: GTKY:QTFV:SROI:BAMP:HX3E:IOWU:MWGB:3RMW:PS27:2V7I:JZSI:DOAG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
WARNING: No swam limit support

# docker -version
Docker version 17.06.0-ce, build 02c1d87

# criu -version
Version: 3.11
GitID: v3.11-94-g574c4b4

# sudo criu check
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:791): sockets: The current kernel doesn't support ipv4 raw_diag module
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:834): sockets: The current kernel doesn't support ipv6 raw_diag module
Looks good.

# sudo criu check --all
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:791): sockets: The current kernel doesn't support ipv4 raw_diag module
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:834): sockets: The current kernel doesn't support ipv6 raw_diag module
Error (criu/cr-check.c:984): The TCP_REPAIR_WINDOW option isn't supported.
Error (criu/cr-check.c:928): TCP_REPAIR can't be enabled for half-closed sockets
Warn  (criu/cr-check.c:1060): Do not have API to map vDSO - will use mremap() to restore vDSO
Error (criu/cr-check.c:1049): Non-cooperative UFFD is not supported
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:791): sockets: The current kernel doesn't support ipv4 raw_diag module
Error (criu/libnetlink.c:27): ERROR -2 reported by netlink (No such file or directory)
Warn  (criu/sockets.c:834): sockets: The current kernel doesn't support ipv6 raw_diag module
Error (criu/cr-check.c:821): autofs not supported.
Warn  (criu/cr-check.c:1026): compat_cr is not supported. Requires kernel >= v4.12
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.

Thanks in advance for your help!

[failed dump.log](https://github.com/checkpoint-restore/criu/files/2730339/failed.dump.log)
[success dump.log](https://github.com/checkpoint-restore/criu/files/2730340/success.dump.log)

**Comment by wangzhao123456** [comment]
> Hi @wangzhao123456
> 
> > Error (criu/cr-check.c:984): The TCP_REPAIR_WINDOW option isn't supported.
> > Error (criu/cr-check.c:928): TCP_REPAIR can't be enabled for half-closed sockets
> 
> > Kernel Version: 4.4.0-31-generic
> > Operating System: Ubuntu 14.04.5 LTS
> 
> I think the problem is that your kernel does not have several patches that implement TCP repair mode.
> Would it be possible for you to upgrade the kernel?

Thanks, I will try   ^_^

**Comment by avagin** [comment]
The success dump doesn't contain tcp connections.
```
$ grep "Dumping TCP connection" ~/Downloads/failed.dump.log 
(00.356584) tcp: Dumping TCP connection
$ grep "Dumping TCP connection" ~/Downloads/success.dump.log 
$ echo $?
1
```

**Comment by wangzhao123456** [comment]
> Hi @wangzhao123456
> 
> > Error (criu/cr-check.c:984): The TCP_REPAIR_WINDOW option isn't supported.
> > Error (criu/cr-check.c:928): TCP_REPAIR can't be enabled for half-closed sockets
> 
> > Kernel Version: 4.4.0-31-generic
> > Operating System: Ubuntu 14.04.5 LTS
> 
> I think the problem is that your kernel does not have several patches that implement TCP repair mode.
> Would it be possible for you to upgrade the kernel?

Thanks for your help. I upgraded my kernel to V4.12, and the above problem has gone. I can successfully checkpoint and restore my firefox browser container when I open the VNC client. I also tried to upgrade my kernel to V4.9, but the problem still exists.

**Comment by wangzhao123456** [comment]
> The success dump doesn't contain tcp connections.
> 
> ```
> $ grep "Dumping TCP connection" ~/Downloads/failed.dump.log 
> (00.356584) tcp: Dumping TCP connection
> $ grep "Dumping TCP connection" ~/Downloads/success.dump.log 
> $ echo $?
> 1
> ```

Thanks. I upgraded my kernel to V4.12, and the above problem has gone. I can successfully checkpoint and restore my firefox browser container when I open the VNC client.

**Comment by avagin** [comment]
@wangzhao123456 can we close this issue?

**Comment by wangzhao123456** [comment]
> @wangzhao123456 can we close this issue?
yes, I will.
