### ISSUE TITLE
Restore of bash exits with unexpected I/O error

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#593]
I noticed an interesting bug. When restoring `bash` with `--shell-job` it exits unexpectedly.

For example:
1. Open bash:
```bash
$ bash
```
2. Then in another terminal, we create a checkpoint with `--shell-job`
```bash
$ sudo criu dump -t 32122 -D /tmp/test -j -o dump.log -v4
```
3. Run `criu restore` and hit `Enter` twice:
```bash
$ sudo criu restore -D /tmp/test/ -j -o restore.log -v4

$ exit
```
**Result:** Suddenly `bash` exits
**Expected result:** `bash` should continue to work.

Using `strace`, I noticed that the reason for the exit is:
```
1217 32122 read(0, 0x7fff336edecf, 1)        = -1 EIO (Input/output error)           
1218 32122 ioctl(0, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
```
and from the man page of read(2):
```
I/O error.  This will happen for example when the process is
in a background process group, tries to read from its
controlling terminal, and either it is ignoring or blocking
SIGTTIN or its process group is orphaned.  It may also occur
when there is a low-level I/O error while reading from a disk
or tape.  A further possible cause of EIO on networked
filesystems is when an advisory lock had been taken out on the
file descriptor and this lock has been lost.  See the Lost
locks section of fcntl(2) for further details.
```
[restore-strace.log](https://github.com/checkpoint-restore/criu/files/2735208/restore-strace.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/2735209/restore.log)
[dump.log](https://github.com/checkpoint-restore/criu/files/2735210/dump.log)

**Comment by avagin** [comment]
Cc: @cyrillos

**Comment by cyrillos** [comment]
Thanks, will try to find a time slot today to read more precisely.

**Comment by cyrillos** [comment]
Strictly speaking the restore procedure didn't went well
```
(00.021720) Running post-restore scripts
(00.021756) Unlock network
(00.021837) Error (criu/cr-restore.c:1817): Can't attach to 32122: Operation not permitted
(00.021926) pie: 32122: seccomp: mode 0 on tid 32122
(00.022261) Error (criu/cr-restore.c:1873): Can't interrupt the 32122 task: No such process
(00.022287) Restore finished successfully. Resuming tasks.
(00.022330) Running pre-resume scripts
(00.022382) Error (criu/cr-restore.c:1957): Unable to execute 32122: No such process
```
Note we don't have proper tty group inheritance. It simply impossible to do at the moment so I expect that some of `-j` option won't work as expected.

Do you checkpoint some test or own custom program?

**Comment by rst0git** [comment]
> Do you checkpoint some test or own custom program?

I checkpoint/restore-ed `/usr/bin/bash` with `-j`.
@cyrillos Can you reproduce the error?

**Comment by cyrillos** [comment]
```[cyrill@uranus criu] sudo ./criu/criu restore -v4 -o restore.log -j -D .git-ignore/d/

bash: child setpgid (23089 to 23084): Operation not permitted
bash: child setpgid (23090 to 23084): Operation not permitted
bash: child setpgid (23091 to 23084): Operation not permitted
bash: child setpgid (23092 to 23084): Operation not permitted
bash: child setpgid (23093 to 23084): Operation not permitted
bash: child setpgid (23094 to 23084): Operation not permitted
```
The restore passed but then bash itself started to complain. You know, `-j` is very fragile option I would rather dropped it at all.

**Comment by cyrillos** [comment]
To be precise -- I think the option `-j` had a meaning early time where we've been supporting only a very few resources. Currently we should rather poke users to run processes inside namespaces (via vzctl,docker,lxc or anything else) instead of manipulating resources on host namespace (and -j option was exactly for that).

**Comment by rst0git** [comment]
I noticed that when we start a shell it becomes a group leader (pid=pgid) but not a session leader.
However, CRIU does not restore the original `pgid` but inherits the group ID of the parent process. Thus, before restore `pid`=`pgid` but after restore `pid`!=`pgid`.
