### ISSUE TITLE
add a new process to the container during restore a container?

### ISSUE THREAD

**Issue by coderkaka** [checkpoint-restore/criu#594]
Hello, I want to do someting interesting , but I'm in trouble now. My question is how I can add a new process to the container during restore a container? may be with cr_system? But where should I modify the CRIU source code?

**Comment by rst0git** [comment]
Hi @coderkaka 

> how I can add a new process to the container during restore a container?

Would [`--exec-cmd`](https://criu.org/Tree_after_restore#Doing_execv.28.29_in_CRIU) or [`--action-script`](https://criu.org/Action_scripts) work for you?

**Comment by avagin** [comment]
@coderkaka could you describe with more details what you need to do?

**Comment by coderkaka** [comment]
@rst0git Thank you for the reply, but it doesn't.

**Comment by coderkaka** [comment]
@avagin I'm doing some research with CRIU. Now I don't need to add a new process, but load some code into the address space of the process to be restored while restoring the process.
Howere,  I find the code I load will be unmaped . I guess this work is done in the function  `unmap_old_vmas` . Is there a convenient way to protect the code I load? Maybe I can add the vmas to `premmapped_addr`,I have no idea about what `premmapped` stands for. Could you please explain it for me?

**Comment by rst0git** [comment]
> I have no idea about what premmapped means. Could you please explain it for me?

A private vma is mapped in a temporary place and the address is saved in vma->shmid. The vma-s are mapped before forking children and then they are remapped to corrected places in `restorer.c`.

**Comment by coderkaka** [comment]
@rst0git Well, I got it.  Besides, I want to dump a device which has  states in kernel. The usage of the device is as follows：
`	struct mei_connect_client_data data;
	fd = open(MEI_DEVICE);

	data.d.in_client_uuid = AMTHI_UUID;

	ioctl(fd, IOCTL_MEI_CONNECT_CLIENT, &data);

	printf("Ver=%d, MaxLen=%ld\n",
			data.d.in_client_uuid.protocol_version,
			data.d.in_client_uuid.max_msg_length);

	[...]

	write(fd, amthi_req_data, amthi_req_data_len);

	[...]

	read(fd, &amthi_res_data, amthi_res_data_len);

	[...]
	close(fd);`

The code means we have to connect  to the device before `read/write` it. When I try to write a plugin to dump the device, I find it is difficult. Because the file descriptor is stateful .

**Comment by avagin** [comment]
How do you SGX code?
