### ISSUE TITLE
Having issues dumping on Google Kubernetes Engine pod (cannot dump /dev/pts/<N> and /<N> tty files)

### ISSUE THREAD

**Issue by gukjoon** [checkpoint-restore/criu#595]
Dockerfile: 
https://gist.github.com/gukjoon/4879f3ccae00c64e1513034fbf5c0578

```bash
criu check # returns fine
python
criu dump -t <pid> --shell-job
```

This works fine locally. Running on Google Kubernetes engine, fails with error:

```
Error (criu/files-reg.c:1123): Can't lookup mount=25 for fd=0 path=/dev/pts/1
```

Only difference I find is `lsof` on GKE returns
```
COMMAND PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
python         32   root     0u   CHR  136,1      0t0       4 /dev/pts/1
python         32   root     1u   CHR  136,1      0t0       4 /dev/pts/1
python         32   root     2u   CHR  136,1      0t0       4 /dev/pts/1
```
(note device id 136,1)
whereas locally:
```
python   25 root    0u   CHR  136,0      0t0       3 /dev/pts/0
python   25 root    1u   CHR  136,0      0t0       3 /dev/pts/0
python   25 root    2u   CHR  136,0      0t0       3 /dev/pts/0
```
(device id 136, 0)

Let me know if further info would be helpful

**Comment by gukjoon** [comment]
Full logs here:
https://gist.github.com/gukjoon/6c876bf4de5ca0e4105e404e0b26cde1

**Comment by adrianreber** [comment]
CRIU 2.8 is rather old. Could you try CRIU 3.11 instead?

**Comment by gukjoon** [comment]
Yes great point. Just tried. Here's the new log (verbosity2 at the bottom):
https://gist.github.com/gukjoon/2138a6b566ea03480b4ad3651a6b8f66

**Comment by adrianreber** [comment]
That looks like the same error. Cannot say much more here. I am sure somebody else will have an idea.

**Comment by gukjoon** [comment]
I've had success dumping using
`criu dump -t 90 --external 'tty[8801:14]' --shell-job`
with the following warnings:
```
Warn  (criu/net.c:2840): Unable to get tun network namespace
Error (criu/uffd.c:264): uffd: Lazy pages are not available: Function not implemented
Warn  (criu/kerndat.c:881): Can't keep kdat cache on non-tempfs
Warn  (criu/image.c:134): Failed to open parent directory
```

But when I restore
`criu restore --inherit-fd 'fd[1]:tty[8801:14]' --shell-job --deprecated -v4`

I get error:
```
(00.185480)    157: Error (criu/tty.c:1461): tty: No task found with sid 8
```

Will continue to investigate.

**Comment by rst0git** [comment]
@gukjoon Would it be possible to start your application with `setsid` and avoid the use of `--shell-job`?

**Comment by gukjoon** [comment]
👍 well that totally worked out seamlessly. Thanks @rst0git ! Closing...
