### ISSUE TITLE
Can't dump unix socket in container env

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#597]
It seems that criu can't fetch the right ino of unix socket in container env.

![image](https://user-images.githubusercontent.com/3961183/51578240-cdcc8980-1ef7-11e9-8968-2a6543192ccd.png)

The first ino 0x72c04f7 matches the resulut of `ls -i /tmp/.java_pid108`, while the second ino 0x653c1335 doesn't match.

Collecting info of this listen unix socket:

![image](https://user-images.githubusercontent.com/3961183/51578319-1c7a2380-1ef8-11e9-8f55-952e41905e74.png)

PS: The result is expected if the process doesn't reside in a docker container.

Any response is appreciated.

**Comment by adrianreber** [comment]
Can you post more information about what you are doing? How are you starting the container, what is in the container, how are you checkpointing the container. CRIU version, docker version, kernel version. Complete CRIU logs.

**Comment by zhouxinyu** [comment]
Of course:

## Version info
1. Docer version: 17.06.2-ce
2. Kernel version: 4.9.79
3. CRIU version: 3.9(3.11 also has this issue)

## steps

1. docker run -d  xxx-application, this container contains a java application.
2. Execute jstack command in container, and then jvm will bind a socket at /tmp/.java_pid..
2. docker checkpoint create --checkpoint-dir=......, create a checkpoint.

Complete criu log attached.

**Comment by zhouxinyu** [comment]
@adrianreber 

```
How do you execute the jstack command in the container?
```
1. Enter the container: docker exec -it xxx bash
2. Execute jstack: $JAVA_HOME/bin/jstack -l java_pid

```
Can you show us a process tree of the processes in the container?
```

pstree is simple:

![image](https://user-images.githubusercontent.com/3961183/51597563-7c8fba80-1f36-11e9-9f71-0b51e1f659ee.png)

**Comment by adrianreber** [comment]
What I am interested is if the jstack command is running under the same parent process as the other processes from the container.  I think this is the problem, that CRIU will not checkpoint the jstack process as it is started by `docker exec`. I guess `start.sh` is the container entrypoint. Can you start jstack as part of the `start.sh` process. Then jstack should also be a child process from the container process tree and checkpointed by CRIU.

**Comment by zhouxinyu** [comment]
Hi @adrianreber , the jstack command will exit, it's a tool command, rpc call based on unix socket. Java process will bind the unix socket triggered by the first jstack command.

And the socket /tmp/.java_pid108 belongs to the java process, not the exited jstack tool.

**Comment by zhouxinyu** [comment]
And I think the possible reason is that ino mismatch in container env, see the [related code](https://github.com/checkpoint-restore/criu/blob/93043916cdf4d42bb9cc81a3404e803945a5e1e8/criu/sk-unix.c#L627).

![image](https://user-images.githubusercontent.com/3961183/51604106-b799ea00-1f46-11e9-9789-1f856f9299da.png)

**Comment by rst0git** [comment]
@zhouxinyu Could upload the log file from version 3.11? I think this might be related to this recent change https://github.com/checkpoint-restore/criu/commit/787409df9da2292c16d106d0e319b42313a3d147.

> (01.867907) Dumping finished successfully

What happens when you try to restore the container?

**Comment by zhouxinyu** [comment]
@rst0git I found this commit will affect 3.9~3.11, so I tried 3.8.1, this issue happens again...

```
What happens when you try to restore the container?
```
In the `files.img`, this LISTEN socket is marked with `deleted`, so the path `/tmp/.java_pid108` is unlinked(or deleted?) when restoring the container, although the socket will be bind to the kernel.

Any rpc request to this unix socket will be failed.

**Comment by avagin** [comment]
What storage driver do you use in Docker?

CRIU checks that a socket inode number matches a file inode number. If it doesn't, it may mean that another socket was bound to the same name.

In this issue, we need understand why a file inode isn't equal to the inode which is reported by the kernel for this socket:
https://github.com/torvalds/linux/blob/master/net/unix/diag.c#L28

**Comment by zhouxinyu** [comment]
@avagin OverlayFS.

The same test without Docker doesn't have this issue, so it means that there is only one socket bound to the path.

Is it possible that OverlayFS or mnt namespace led to this issue?

**Comment by zhouxinyu** [comment]
ping @avagin , do you have any thought of this issue?

**Comment by zhouxinyu** [comment]
Consider this socket is bind to /tmp dir, I ran the docker container with -v(/tmp:/tmp), the issue disappeared, so I think the root cause may be the overlay fs.

**Comment by avagin** [comment]
@zhouxinyu it looks like  https://github.com/avagin/linux-task-diag/commit/d5440676990f5f8711af8cddeae1bfbb62d70f7e. It is good that you found a workaround for this issue.

**Comment by zhouxinyu** [comment]
@avagin But it's not a good workaround solution, it's difficult to enumerate all the potential directories which will be used to bind Unix socket.

And as the above issue you mentioned, it seems that there are other fd related issues on overlayfs except unix socket ?
