### ISSUE TITLE
Support NFS mountpoints

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#60]
NFS mount points from inside container cannot be easily restored. The thing is -- if we want to restore opened file we will go ahead and [call](http://criu.org/How_hard_is_it_to_open_a_file) the open system call. If the file in question resides on NFS, the latter might need to go to network to check whether the file actually exists and set up the handle. But if the networking is still not restored this operation would fail and we'll have to fail the whole restore. In order to untie this chicken-and-egg problem we may go in two directions.

**Comment by ihorman** [comment]
Hello Pavel
Any news on that feature request? The issue with NFS mount points is very painfull still, many customers would be happy to have that problem solved.

**Comment by mihalicyn** [comment]
Hello @ihorman 

I have two news for you - as usual, one is bad, another one is good :)
Good. NFS already implemented by @skinsbursky 
And patchset here https://patchwork.criu.org/series/137/
You could try to rebase this patchset onto the current version of CRIU.
Bad. NFS design is very complex. To implement the migration of NFS mount points in CRIU, an additional interesting thing was developed and used - it is called SPFS (Stub-Proxy File System https://github.com/skinsbursky/spfs). The bad news is - we need to integrate the SPFS filesystem with every container system that we want to use separately. For example, if you want to migrate Docker containers with NFS mount inside then you need to make friendship between CRIU, SPFS, and Docker, if you want to use, for instance, LXC - also. You need to make bridges between CRIU, SPFS, and LXC.

I've plans to port this great patchset to CRIU, and, maybe, I will take LXC as an example.
Please, write, if you want to work on that. We could keep in contact and help you with that. ;)

Regards, Alex
