### ISSUE TITLE
Trying to checkpoint/restore from a Singularity container

### ISSUE THREAD

**Issue by Skizal** [checkpoint-restore/criu#600]
Hello, 

I'm trying to get CRIU working on Singularity containers. I was testing if i could checkpoint an script running in a shell inside a container and restore it, from outside the container. I get this error at restore:

```
(00.029858)   2117: mnt: 	Mounting overlay @/tmp/.criu.mntns.v0tAIg/8-0000000000/ (0)
(00.038252)   2117: mnt: Start with 0:/tmp/.criu.mntns.v0tAIg
(00.068846) Error (criu/mount.c:3270): mnt: Can't remove the directory /tmp/.criu.mntns.v0tAIg: Device or resource busy
(00.068873) Error (criu/cr-restore.c:2294): Restoring FAILED.
```

The commands i've used to dump and restore are:
```
sudo criu dump -o dump.log -v4 -t 8342 --external mnt[/etc/group]:/etc/group --external mnt[/etc/passwd]:/etc/passwd --external mnt[/etc/resolv.conf]:/etc/resolv.conf --external mnt[/var/tmp]:/var/tmp --external mnt[/tmp]:/tmp --external mnt[/home/skizal]:/home/skizal --external mnt[/proc/sys/fs/binfmt_misc]:/proc/sys/fs/binfmt_misc --external mnt[/proc]:/proc --external mnt[/.singularity.d/actions]:/.singularity.d/actions --external mnt[/etc/hosts]:/etc/hosts --external mnt[/etc/localtime]:/etc/localtime --external mnt[/dev/mqueue]:/dev/mqueue --external mnt[/dev/hugepages]:/dev/hugepages --external mnt[/dev/shm]:/dev/shm --external mnt[/dev/pts]:/dev/pts --external mnt[/dev]:/dev --shell-job
```

```
sudo criu restore -o restore.log -v4 -d --root /usr/local/var/singularity/mnt/session/final --external mnt[/etc/group]:/usr/local/var/singularity/mnt/session/final/etc --external mnt[/etc/passwd]:/usr/local/var/singularity/mnt/session/rootfs/etc --external mnt[/etc/resolv.conf]:/usr/local/var/singularity/mnt/session/final/etc --external mnt[/var/tmp]:/usr/local/var/singularity/mnt/session/final/var --external mnt[/tmp]:/usr/local/var/singularity/mnt/session/final --external mnt[/home/skizal]:/usr/local/var/singularity/mnt/session/final/home --external mnt[/proc/sys/fs/binfmt_misc]:/usr/local/var/singularity/mnt/session/final/proc/sys/fs --external mnt[/proc]:/usr/local/var/singularity/mnt/session/final --external mnt[/.singularity.d/actions]:/usr/local/var/singularity/mnt/session/final --external mnt[/etc/hosts]:/usr/local/var/singularity/mnt/session/final/etc --external mnt[/etc/localtime]:/usr/local/var/singularity/mnt/session/final/etc --external mnt[/dev/mqueue]:/usr/local/var/singularity/mnt/session/final/dev --external mnt[/dev/hugepages]:/usr/local/var/singularity/mnt/session/final/dev --external mnt[/dev/shm]:/usr/local/var/singularity/mnt/session/final/dev --external mnt[/dev/pts]:/usr/local/var/singularity/mnt/session/final/dev --external mnt[/dev]:/usr/local/var/singularity/mnt/session/final --shell-job
```

It may be an error with the external mounting or the root path selection. I'm new to both CRIU and Singularity so, if you could give me some glimpse about what's happening would be really good.

I also attach dump and restore logs for more detail.

[dump.log](https://github.com/checkpoint-restore/criu/files/2793854/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/2793855/restore.log)

Thanks!

**Comment by avagin** [comment]
Could you run "criu restore" under strace and attach a strace log:
sudo strace -o strace.log -s 256 -f criu restore ....

**Comment by Skizal** [comment]
Here it is.
[strace.log](https://github.com/checkpoint-restore/criu/files/2797726/strace.log)

**Comment by rst0git** [comment]
```
criu restore -o restore.log -v4 -d --root /usr/local/var/singularity/mnt/session/final ...
```
```
mount("/usr/local/var/singularity/mnt/session/final", "/tmp/.criu.mntns.Xgduog/8-0000000000/", NULL, MS_BIND|MS_REC, NULL) = -1 ENOENT
```
Does the path `/usr/local/var/singularity/mnt/session/final` exist on the host before `criu restore` is being called?

**Comment by rst0git** [comment]
Also see [this comment](https://github.com/lxc/lxc/blob/007ef61a740f5134dde364e9a7d8a65d48a5480f/src/lxc/criu.c#L1018-L1039) in LXC

**Comment by Skizal** [comment]
It exists only inside another mount namespace which is master of the mount namespace of the container. I created the directory to check if i got different results. I got the same final error but it tried some things before.

[dump.log](https://github.com/checkpoint-restore/criu/files/2798047/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/2798048/restore.log)
[strace.log](https://github.com/checkpoint-restore/criu/files/2798049/strace.log)

**Comment by Skizal** [comment]
Thank you for the answers, i was able to solve this and similar errors i got. I've recreated the directory hierarchy existing inside the container to do it. I reached a point where i get these errors.
```
 Opening 0x00000000400000-0x000000004ef000 0000000000000000 (41) vma
(00.128144)   2311: Error (criu/files-reg.c:1716): File bin/bash has bad size 1113504 (expect 1017016)
(00.128174)   2311: Error (criu/mem.c:1279): `- Can't open vma
```
The first one regarding the bin/bash size i suppose it's because i need the right file copied there but for the one about vma i don't know what it is.

[dump.log](https://github.com/checkpoint-restore/criu/files/2809713/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/2809716/restore.log)
[strace.log](https://github.com/checkpoint-restore/criu/files/2809718/strace.log)

**Comment by adrianreber** [comment]
The error `Can't open vma` is follow-up error from the file size error. Make sure the binaries have the same size (and are actually the same binary).

**Comment by Skizal** [comment]
I've been able to restore the script and get it running from the state it was dumped. Although, the mounts of the process are different. I was wondering if there were any options, at dump or restore, which could help at getting it right.
Info from proc/$pid/mounts, before and after:
```
overlay / overlay ro,nodev,relatime,lowerdir=/usr/local/var/singularity/mnt/session/overlay-lowerdir:/usr/local/var/singularity/mnt/session/rootfs 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=8140752k,nr_inodes=2035188,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
/dev/sda1 /etc/localtime ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/hosts ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /.singularity.d/actions ext4 ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
proc /proc proc rw,nosuid,nodev,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=39,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=259 0 0
sysfs /sys sysfs rw,nosuid,nodev,relatime 0 0
/dev/sda2 /home/skizal ext4 rw,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /tmp ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /var/tmp ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
tmpfs /etc/resolv.conf tmpfs rw,nosuid,relatime,size=16384k,uid=1000,gid=1000 0 0
tmpfs /etc/passwd tmpfs rw,nosuid,relatime,size=16384k,uid=1000,gid=1000 0 0
tmpfs /etc/group tmpfs rw,nosuid,relatime,size=16384k,uid=1000,gid=1000 0 0
```
```
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/localtime ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/hosts ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /.singularity.d/actions ext4 ro,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /home/skizal ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /var/tmp ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/resolv.conf ext4 rw,nosuid,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/passwd ext4 rw,nosuid,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /etc/group ext4 rw,nosuid,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /dev ext4 rw,nosuid,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /dev/pts ext4 rw,nosuid,noexec,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /dev/shm ext4 rw,nosuid,nodev,errors=remount-ro,data=ordered 0 0
/dev/sda1 /dev/hugepages ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /dev/mqueue ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /proc ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
/dev/sda1 /proc/sys/fs/binfmt_misc ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
sysfs /sys sysfs rw,nosuid,nodev,relatime 0 0
/dev/sda1 /tmp ext4 rw,nosuid,nodev,relatime,errors=remount-ro,data=ordered 0 0
```
Also, the process was placed in a different mount namespace. I thought that it would use the namespace where it belonged before.

**Comment by adrianreber** [comment]
> Also, the process was placed in a different mount namespace. I thought that it would use the namespace where it belonged before.

No, CRIU does not remember which namespaces you used. Especially if you think about migration it makes not really sense. But there are a few ways to tell CRIU to use existing namespaces.

We have support to join an existing network namespace (see https://github.com/checkpoint-restore/criu/blob/criu-dev/test/others/netns_ext/run.sh). There is also `--join-ns`, which you try.

Another option is to use `nsenter` to join an existing namespace before restoring your container.

**Comment by Skizal** [comment]
The original issue is solved now so i close the case. Thanks for the information.

**Comment by avagin** [comment]
>> Also, the process was placed in a different mount namespace. I thought that it would use the namespace where it belonged before.

>No, CRIU does not remember which namespaces you used. Especially if you think about migration it makes not really sense. But there are a few ways to tell CRIU to use existing namespaces.

@Skizal CRIU can dump and restore a mount namespace and you can look in the runc code how it works. It doesn't work in you case, because you probably run "criu dump" in a target mount namespace. CRIU dumps a mount namespace, only if a target process has a mount namespace which is different than the current one.
