### ISSUE TITLE
Can't make pipe for page-pipe: Too many open files

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#601]
When trying to pre-dump an application which has allocated 1GiB of memory CRIU fails with
```
Error (criu/page-pipe.c:118): page-pipe: Can't make pipe for page-pipe: Too many open files
```
(Note that `criu dump` is successful in this case)

The reason for this issue is because CRIU creates too many pipe()s that are used to store the memory of the process, and every pipe creates two fds, thus we soon reach the limit of `RLIMIT_NOFILE`. I noticed that during pre-dump the buffer size of each pipe is gradually increased:
```C
unsigned long new_size = ppb->pipe_size << 1;
```
Until the following condition
```C
if (new_size > PIPE_MAX_SIZE)
	return 1;
```
However, it seems much more efficient to set the buffer size of a pipe to `PIPE_MAX_SIZE` at the beginning, rather then growing it. Indeed, the following change solves the issue for 1GiB but of course the same issue occurs again for 2 GiB:
```diff
diff --git a/criu/page-pipe.c b/criu/page-pipe.c
index c32b89332..02a3bfec8 100644
--- a/criu/page-pipe.c
+++ b/criu/page-pipe.c
@@ -64,24 +64,6 @@ static inline int ppb_resize_pipe(struct page_pipe_buf *ppb)
 	return 0;
 }
 
-static struct page_pipe_buf *pp_prev_ppb(struct page_pipe *pp,
-					 unsigned int ppb_flags)
-{
-	int type = 0;
-
-	/* don't allow to reuse a pipe in the PP_CHUNK_MODE mode */
-	if (pp->flags & PP_CHUNK_MODE)
-		return NULL;
-
-	if (list_empty(&pp->bufs))
-		return NULL;
-
-	if (ppb_flags & PPB_LAZY && opts.lazy_pages)
-		type = 1;
-
-	return pp->prev[type];
-}
-
 static void pp_update_prev_ppb(struct page_pipe *pp, struct page_pipe_buf *ppb,
 			       unsigned int ppb_flags)
 {
@@ -96,7 +78,6 @@ static void pp_update_prev_ppb(struct page_pipe *pp, struct page_pipe_buf *ppb,
 static struct page_pipe_buf *ppb_alloc(struct page_pipe *pp,
 				       unsigned int ppb_flags)
 {
-	struct page_pipe_buf *prev = pp_prev_ppb(pp, ppb_flags);
 	struct page_pipe_buf *ppb;
 
 	ppb = xmalloc(sizeof(*ppb));
@@ -106,24 +87,22 @@ static struct page_pipe_buf *ppb_alloc(struct page_pipe *pp,
 
 	ppb->pipe_off = 0;
 
-	if (prev && ppb_resize_pipe(prev) == 0) {
-		/* The previous pipe isn't full and we can continue to use it. */
-		ppb->p[0] = prev->p[0];
-		ppb->p[1] = prev->p[1];
-		ppb->pipe_off = prev->pages_in + prev->pipe_off;
-		ppb->pipe_size = prev->pipe_size;
-	} else {
-		if (pipe(ppb->p)) {
-			xfree(ppb);
-			pr_perror("Can't make pipe for page-pipe");
-			return NULL;
-		}
-		cnt_add(CNT_PAGE_PIPES, 1);
+	if (pipe(ppb->p)) {
+		xfree(ppb);
+		pr_perror("Can't make pipe for page-pipe");
+		return NULL;
+	}
+	cnt_add(CNT_PAGE_PIPES, 1);
 
-		ppb->pipe_size = fcntl(ppb->p[0], F_GETPIPE_SZ, 0) / PAGE_SIZE;
-		pp->nr_pipes++;
+	if (fcntl(ppb->p[0], F_SETPIPE_SZ, PIPE_MAX_SIZE * PAGE_SIZE) < 0) {
+		xfree(ppb);
+		pr_perror("Can't allocate pipe");
+		return NULL;
 	}
 
+	ppb->pipe_size = PIPE_MAX_SIZE;
+	pp->nr_pipes++;
+
 	list_add_tail(&ppb->l, &pp->bufs);
 
 	pp_update_prev_ppb(pp, ppb, ppb_flags);
```
The error could be reproduced by performing `criu pre-dump` of the following application
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main() {
    char *p;
    long long size = 1024 * 1024 * 1024 * sizeof(char);
    p = calloc(1, size);
    if(!p)
        exit(-1);

    while(1)
        sleep(1);

    return 0;
}
```

**Comment by rst0git** [comment]
Thanks Mike, I was just experimenting. For a solution I am thinking about using a child process that reads from the pipe-s, and if `pipe()` fails with `EMFILE` we just have to wait.

**Comment by rppt** [comment]
For pre-dump @xemul  suggested to use sys_process_vm_read(): 
https://criu.org/Google_Summer_of_Code_Ideas#Optimize_the_pre-dump_algorithm

**Comment by rst0git** [comment]
@rpp I was wondering what needs to be done for the patch series in https://lkml.org/lkml/2018/1/9/32 to be merged upstream?

**Comment by rppt** [comment]
more users that would like to see this feature in the kernel.

**Comment by avagin** [comment]
> Thanks Mike, I was just experimenting. For a solution I am thinking about using a child process that reads from the pipe-s, and if pipe() fails with EMFILE we just have to wait.

We can't wait there, because processes are stopped at this moment. criu pre-dump should not stop processes for a long time, otherwise it would not be a live-migration.

**Comment by avagin** [comment]
> For pre-dump @xemul suggested to use sys_process_vm_read():
> https://criu.org/Google_Summer_of_Code_Ideas#Optimize_the_pre-dump_algorithm

Another way to fix this is to support splicing pages from pipe to a process address space without copping them.

**Comment by rst0git** [comment]
Currently, both syscalls `process_vm_readv()` and `process_vm_writev()` have unused **flags** argument, which must be set to 0.

From the [commit message](https://lwn.net/Articles/415600/), it seems like this argument was intended to be used as follows:

> We don't need to keep a copy of the data from the source. I haven't implemented this, but I think this interface could in the future do all this through the use of the flags - eg could specify the math operation and type and the kernel rather than just copying the data would apply the specified operation between the source and destination and store it in the destination.

Maybe, instead of introducing a new syscall, we could try to extend `process_vm_readv()` with support for a flag that allows to read memory from remote process in a copy-on-write manner?

Then, instead of splicing the memory pages into pipes, CRIU could create a "copy" of memory regions from the address space of a target process.

**Comment by rst0git** [comment]
391c19553e4a7fc0f839554cb0a58f84cd2a6fb5
