### ISSUE TITLE
Error transferring container data: with Ubuntu 18.04 ZFS Storage

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#603]
Respected all,
Greeting of the Day !!!. I am trying to live migrate container ‘c3 launch with (Ubuntu 16.04)’ between two LXD servers, with apparmor security feature disabled and experimental setup is:

Physical machine OS: Ubuntu 18.04
lxc --version 3.9 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.9 (installed from source)
criu --version: 3.11 (installed from source)
kernel --version: 4.15.0-29-generic
ZFS LXD storage 
When, I tried to migrate c3 from source to destination using `lxd move` it always gives error:

`Error: Failed container creation:                           
 - https://[fd42:341c:ac01:5afc::1]:8443: Error transferring container data: Unable to connect to: [fd42:341c:ac01:5afc::1]:8443
 - https://172.16.13.120:8443: Error transferring container data: migration pre-dump failed
(00.000045) Warn  (criu/log.c:203): The early log isn't empty
(00.000419) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.000435) Error (criu/seize.c:152): zombie found while seizing
(00.100633) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.100678) Error (criu/seize.c:152): zombie found while seizing
(00.200878) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.200925) Error (criu/seize.c:152): zombie found while seizing
(00.301096) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.301128) Error (criu/seize.c:152): zombie found while seizing
(00.401287) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.401316) Error (criu/seize.c:152): zombie found while seizing
(00.501479) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.501508) Error (criu/seize.c:152): zombie found while seizing
(00.601678) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.601709) Error (criu/seize.c:152): zombie found while seizing
(00.701902) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.701946) Error (criu/seize.c:152): zombie found while seizing
(00.802105) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.802134) Error (criu/seize.c:152): zombie found while seizing
(00.902291) Warn  (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
(00.902319) Error (criu/seize.c:152): zombie found while seizing
`, 

I tried with fresh installation of Ubuntu 18.04, but still same error is encountered.
[lxc.log](https://github.com/checkpoint-restore/criu/files/2825725/lxc.log)

**Comment by avagin** [comment]
> (00.000419) Warn (compel/src/lib/infect.c:125): Unable to interrupt task: 16415 (Operation not permitted)
Could you try to disable apparmor?

**Comment by avagin** [comment]
Cc: @brauner

**Comment by brauner** [comment]
Would the zombie process leave criu unable to inject the parasite code? Looks like it at least.

**Comment by avagin** [comment]
We read a process list from a container freezer cgroup. We expect to find a zombie process there, but it should disappear in a short period of time. It is why we try to do this a few times.

https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/seize.c#L152

**Comment by avagin** [comment]
@adityacloud1 could you reproduce this issue again and then get more information about a process which can't be interrupted. I would like to see /proc/pid/status for this process. And can you try to run strace -p PID -s 256 -f for this process?

**Comment by JatinSuthar07** [comment]
sudo lxc snapshot uub5 suub1 --stateful
Error: snapshot dump failed
(00.000122) Warn  (criu/log.c:203): The early log isn't empty
(00.010563) Warn  (criu/image.c:137): Failed to open parent directory
(00.013501) Error (criu/mount.c:1087): mnt: The file system 0x34 0x34 (0x41) btrfs ./ is inaccessible
(00.013506) Error (criu/fsnotify.c:212): fsnotify: Can't open mount for s_dev 34, continue
(00.013509) Warn  (criu/fsnotify.c:288): fsnotify: 	Handle 0x34:0x1f8 cannot be opened
(00.023836) Error (criu/irmap.c:86): irmap: Can't stat /no-such-path: No such file or directory
(00.023840) Error (criu/fsnotify.c:291): fsnotify: 	Can't dump that handle
(00.023875) Error (criu/cr-dump.c:1345): Dump files (pid: 2426) failed with -1
(00.026703) Error (criu/cr-dump.c:1753): Dumping FAILED.

**Comment by JatinSuthar07** [comment]
using Ubuntu:18.04
