### ISSUE TITLE
checkpointing a runc container fails

### ISSUE THREAD

**Issue by ashu-mehra** [checkpoint-restore/criu#619]
I am not able to checkpoint a runc container. I am not sure if I missed something.
I have built runc and criu from latest sources.

Steps performed:
```
# runc create sample
# runc start sample
```
At this point I can see container running and try to checkpoint it.
```
# runc --debug --log=runc1.log --criu=/home/ashu/data/criu/criu/criu checkpoint sample
criu failed: type NOTIFY errno 0
log file: /run/runc/sample/criu.work/dump.log
```

`dump.log` indicates following error:
```
(00.253208) Dumping opened files (pid: 11071)
(00.253211) ----------------------------------------
(00.253233) Sent msg to daemon 71 0 0
pie: 1: __fetched msg: 71 0 0
pie: 1: __sent ack msg: 71 71 0
pie: 1: Daemon waits for command
(00.253283) Wait for ack 71 on daemon socket
(00.253288) Fetched ack: 71 71 0
(00.253359) 11071 fdinfo 0: pos:                0 flags:           102002/0
(00.253388) tty: Dumping tty 17 with id 0x2
(00.253408) Error (criu/files-reg.c:1332): Can't lookup mount=25 for fd=0 path=/dev/pts/0
(00.253417) ----------------------------------------
(00.253665) Error (criu/cr-dump.c:1345): Dump files (pid: 11071) failed with -1
```

Attaching the relevant log files:
[dump.log](https://github.com/checkpoint-restore/criu/files/2873194/dump.log)
[runc1.log](https://github.com/checkpoint-restore/criu/files/2873195/runc1.log)

criu level:
```
$ ./criu -V
Version: 3.11
GitID: v3.11-167-gf42468d8
```
kernel level:
```
$ uname -a
Linux ashu-KVM 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I am running Ubuntu 18.04.1 KVM based VM.

**Comment by adrianreber** [comment]
I usually solve this by starting the container like this:

`runc run container-name -d -b /path/to/bundle-directory &> /dev/null  < /dev/null`

**Comment by ashu-mehra** [comment]
That worked. I am able to restore it as well. Thanks for the command!

**Comment by adrianreber** [comment]
Perfect, I am closing this. Please re-open if there are any other problems.

**Comment by ashu-mehra** [comment]
Just for the record, I am jotting down another issue I faced earlier, but is not happening now.
When checkpointing a runc container I got the following error message:
```
(00.012123) Error (criu/mount.c:951): mnt: Mount 1658 ./sys/fs/fuse/connections (master_id: 32 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
(00.012134) Unlock network
(00.012138) Unfreezing tasks into 1
(00.012152) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
Log file is:
[dump.log](https://github.com/checkpoint-restore/criu/files/2874309/dump.log)

I got this issue resolved by adding `AutoExtMnt` to `true` in the protobuf message sent by runc.
```
diff --git a/libcontainer/container_linux.go b/libcontainer/container_linux.go
index ef443f6f..c388fdca 100644
--- a/libcontainer/container_linux.go
+++ b/libcontainer/container_linux.go
@@ -964,6 +964,7 @@ func (c *linuxContainer) Checkpoint(criuOpts *CriuOpts) error {
                OrphanPtsMaster: proto.Bool(true),
                AutoDedup:       proto.Bool(criuOpts.AutoDedup),
                LazyPages:       proto.Bool(criuOpts.LazyPages),
+               AutoExtMnt:      proto.Bool(true),
        }
 
        c.handleCriuConfigurationFile(&rpcOpts)
```
However, after I rebooted my VM, I am not seeing this issue again even when running without the above mentioned change.
So for now I am not too keen to pursue it further. If it happens again, I will raise a new issue.

**Comment by adrianreber** [comment]
We had a discussion in runc about `AutoExtMnt` in this ticket: https://github.com/opencontainers/runc/pull/1968

It would be interesting how you got the mount `/sys/fs/fuse/connections` in your container. Did you use fuse from inside the container or was the external `/sys`fs` mounted inside the container. This would require knowledge about how you configured your container and what you did inside your container.

Anyway, if you see it again, please open another ticket. Or just make sure to unmount the fuse mountpoint before checkpointing the container :wink:
