### ISSUE TITLE
How to catch exit code of restored process

### ISSUE THREAD

**Issue by hamann** [checkpoint-restore/criu#623]
Is there a way to get access to the exit code of the restored process?
What we basically like to do is to run a script, within the script restore the process and wait for it to exit and react on its exit code. I tried different variants as outlined in https://criu.org/Tree_after_restore but couldn't manage it with `wait` or `trap f SIGCHLD`

**Comment by adrianreber** [comment]
Could you provide an example of what you are trying to do?

**Comment by hamann** [comment]
Sure.

Let's say we have a task which exits after 60 seconds with exit code 7

```
$ cat loop.sh
#!/bin/bash
sleep 60
exit 7
```

and dump it
```
$ cat dump.sh
#!/bin/bash
set -ex
setsid ./loop.sh < /dev/null &> loop.log &
pid=$(pgrep -f loop.sh)
criu dump -t $pid -o dump.log
```

then restore it in another script and wait for it to exit

```
$  cat restore.sh
#!/bin/bash
 restore() {
   criu restore -d -S -o restore.log
 }
 restore
 pid=$(pgrep -f loop.sh)
 wait $pid 
```

restore.sh then fails with

```
./restore.sh
Warn  (criu/kerndat.c:765): Can't load /run/criu.kdat
Warn  (criu/kerndat.c:805): Can't keep kdat cache on non-tempfs
./restore.sh: line 10: wait: pid 78 is not a child of this shell
```

I thought that with `--restore-sibling` the caller script `restore.sh` would then be the parent of the restored process, but apparently not in this context. Is there maybe another way to achive something like this?

**Comment by rst0git** [comment]
@hamann can try with `--exec-cmd`?
Example:
```
setsid ./child </dev/null &>/dev/null
pid=`pidof child`
sudo criu dump -D /tmp/test/ -t $pid
sudo criu restore -D /tmp/test/ --exec-cmd -- `pwd`/my_waiter $pid
```
```C
/* my_waiter.c */
#include <sys/wait.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    pid_t cpid, w;
    int status;

    cpid = atoi(argv[1]);

    do {
	w = waitpid(cpid, &status, WUNTRACED | WCONTINUED);
	if (w == -1) {
	    perror("waitpid");
	    exit(EXIT_FAILURE);
	}

	if (WIFEXITED(status))
	    printf("exited, status=%d\n", WEXITSTATUS(status));
	else if (WIFSIGNALED(status))
	    printf("killed by signal %d\n", WTERMSIG(status));
	else if (WIFSTOPPED(status))
	    printf("stopped by signal %d\n", WSTOPSIG(status));
	else if (WIFCONTINUED(status))
	    printf("continued\n");

    } while (!WIFEXITED(status) && !WIFSIGNALED(status));
    exit(EXIT_SUCCESS);
}
```

```C
/* child.c */
#include <stdlib.h>
#include <unistd.h>

int main()
{
    int i = 10;
    while (i > 0) {
	i--;
	sleep(1);
    }
    exit(3);
}
```

**Comment by 0x7f454c46** [comment]
@hamann Probably, you would like to run criu restore with `--shell-job`.

**Comment by hamann** [comment]
@0x7f454c46 yes, I tried that already, but `wait` then just exits with `137`

```sh
#!/bin/bash
set -x

SHELL_JOB=" --shell-job"
SCRIPT="loop.sh"

dump() {
  setsid ./$SCRIPT < /dev/null &> "${SCRIPT}.log" &
  sleep 5
  local pid=$(pgrep -f "$SCRIPT")
  criu dump -t "$pid" -o dump.log $SHELL_JOB
}

restore() {
  criu restore -d -S -o restore.log $SHELL_JOB
}

cat << EOF > "$SCRIPT"
#!/bin/bash
sleep 20
exit 7
EOF
chmod +x "$SCRIPT"

pkill -f "$SCRIPT" || true
dump
sleep 3
restore
pid=$(pgrep -f $SCRIPT)

wait "$pid"
echo "Exited with $?"
```

```
root@7a3afa133293:criu-test# ./restore.sh
+ SHELL_JOB=' --shell-job'
+ SCRIPT=loop.sh
+ cat
+ chmod +x loop.sh
+ pkill -f loop.sh
+ true
+ dump
+ sleep 5
+ setsid ./loop.sh
++ pgrep -f loop.sh
+ pid=104
+ criu dump -t 104 -o dump.log --shell-job
Warn  (criu/kerndat.c:765): Can't load /run/criu.kdat
Warn  (criu/kerndat.c:805): Can't keep kdat cache on non-tempfs
./restore.sh: line 7:   104 Killed                  setsid ./$SCRIPT < /dev/null &> "${SCRIPT}.log"
+ sleep 3
+ restore
+ criu restore -d -S -o restore.log --shell-job
Warn  (criu/kerndat.c:765): Can't load /run/criu.kdat
Warn  (criu/kerndat.c:805): Can't keep kdat cache on non-tempfs
++ pgrep -f loop.sh
+ pid=104
+ wait 104
+ echo 'Exited with 137'
Exited with 137
```

**Comment by 0x7f454c46** [comment]
@hamann As far as I remember, bash's builtin `wait` in case of a process was killed by a signal returns status as `128 + signr`[1]. So, signr == (137-128) == 9 is SIGKILL. I guess, it's from CRIU that terminates your script on the dump.
Basically, what I think happens, at this moment in your script:
```
dump
sleep 3
```
you get a zombie child process, which status you read from `wait` after you restore original application.
You could try to change your script to `wait` for this zombie after criu dumps your application, apriori restoring it.

**Comment by 0x7f454c46** [comment]
[1]: https://www.gnu.org/software/bash/manual/html_node/Signals.html

**Comment by hamann** [comment]
@0x7f454c46 We could solve it by adjusting the code from @rst0git to exit with the same exit code as the child, that has the benefit that also `criu restore` exits with that exit code. Thank's a lot!
