### ISSUE TITLE
Error dumping in a LXC container (cgroup.c:592): cg: Couldn't mount blkio: Permission denied

### ISSUE THREAD

**Issue by gepatto1** [checkpoint-restore/criu#639]
Hi ,
I am running a Ubuntu 16.04 container with the LXC v2.0.8.  In the container, I have criu 2.6 installed from apt.  When I try to dump the tcp-howto client, an error occurs when trying to dump the core. Here is are the log entries near the error:
pie: 212: Daemon waits for command
(00.026441) Fetched ack: 17 17 0
(00.026465) cg: Dumping cgroups for 212
(00.026577) cg:  `- New css ID 2
(00.026587) cg:     `- [blkio] -> [/] [0]
(00.026592) cg:     `- [cpu,cpuacct] -> [/] [0]
(00.026597) cg:     `- [cpuset] -> [/] [0]
(00.026602) cg:     `- [devices] -> [/system.slice/system-container\x2dgetty.sl$
(00.026606) cg:     `- [freezer] -> [/] [0]
(00.026611) cg:     `- [hugetlb] -> [/] [0]
(00.026615) cg:     `- [memory] -> [/] [0]
(00.026619) cg:     `- [name=systemd] -> [/system.slice/system-container\x2dget$
(00.026624) cg:     `- [net_cls,net_prio] -> [/] [0]
(00.026628) cg:     `- [perf_event] -> [/] [0]
(00.026633) cg:     `- [pids] -> [/] [0]
(00.026841) Error (criu/cgroup.c:592): cg: couldn't mount blkio: Permission denied
 (00.026901) ----------------------------------------
(00.026908) Error (criu/cr-dump.c:1342): Dump core (pid: 212) failed with -1

Any ideas of what is causing the permission problem?
Thanks,
Dan

**Comment by rst0git** [comment]
> I have criu 2.6 installed from apt.

This is a very old version of CRIU. Would it be possible to update it?
https://criu.org/Installation

**Comment by gepatto1** [comment]
Yes, I will update to v3.11 and try again

Thanks,
Dan

**Comment by gepatto1** [comment]
I compiled criu 3.11 and have the same error. Here is the error from the dump log:

(00.029701) Error (criu/cgroup.c:600): cg: couldn't mount blkio: Permission denied
(00.029773) ----------------------------------------
(00.029783) Error (criu/cr-dump.c:1386): Dump core (pid: 9716) failed with -1

**Comment by rst0git** [comment]
> (00.029701) Error (criu/cgroup.c:600): cg: couldn't mount blkio: Permission denied

Does the error persist if enable nesting of cgroups for that container?
https://help.ubuntu.com/lts/serverguide/lxc.html.fr#lxc-nesting

**Comment by gepatto1** [comment]
The dump works now, I have in the container config
lxc.mount.auto = proc:rw cgroup
lxc.aa_profile = lxc-container-default-with-nesting

However, the restore does not. This is the error when restoring the tcp client:
cg: Preparing cgroups yard (cgroups restore mode 0x4)
Error (criu/util.c:1132): Unable to mark yard as private: Permission denied

Thank you,
Dan

**Comment by rst0git** [comment]
The error message:
```
Error (criu/util.c:1132): Unable to mark yard as private: Permission denied
```
occurs because `mount("none", path, NULL, MS_PRIVATE, NULL)` fails with `EACCES`.

Could you try with `lxc.aa_profile=unconfined`?

**Comment by gepatto1** [comment]
Restore works with  lxc.aa_profile=unconfined in the container config.  I can run the tcp client demo in a container and the dump and restore work! Thank you very much for your help!    
Dan
