### ISSUE TITLE
Is it safe to not dump child processes?

### ISSUE THREAD

**Issue by ayoungdahl** [checkpoint-restore/criu#645]
This is a CRIU design decision question rather than an issue.  I'm asking here because i'm not sure where else to pose this sort of question.

Question:  When CRIU checkpoints a process it checkpoints not only the specified pid, but also all child pids.  Typically this is what would be wanted.  However, suppose we knew that the child pids were not of interest in a restore is there are reason we would be unable to restore the only the parent pid?  I realize, of course, that our group would need to mod the CRIU code.  But aside from that is there a reason why restoring only a parent would create restore issues?

**Comment by rst0git** [comment]
>  However, suppose we knew that the child pids were not of interest in a restore is there are reason we would be unable to restore the only the parent pid?

Actually, you can use the CRIT tool to achieve this. It allows you to modify the image files generated by CRIU. In particular, you should modify the `pstree.img` file by removing the processes you do want to be restored.

Example:
```sh
crit decode -i pstree.img -o pstree.json
vim pstree.json
crit encode -o pstree.img -i pstree.json
```
In addition, you can use `--leave-running` or `--leave-stopped` to control the state in which the processes are being left after checkpoint (i.e. if you wish CRIU not to send `SIGKILL`).

**Comment by ayoungdahl** [comment]
Fantastic!  This is helpful information.  We've made use of the --leave-running flag. CRIT is something I was vaguely aware of but hadn't looked into yet.  I will look into CRIT.  Mostly I wanted to be sure that restoring only part of a process tree wasn't a problematic idea.  Thanks for your response.
