### ISSUE TITLE
Restoration failed Error Bad mode

### ISSUE THREAD

**Issue by gepatto1** [checkpoint-restore/criu#650]
I am using criu ver 3.11 inside Ubuntu 16.06 container hosted by LXC ver 2.0.8. I would like to run the example tcp-howto, dump the process, and then scp the files in the img-dir to another LXC and restore the tcp-howto process. The dump and restore work when run on each LXC.  I tar the img-dir folder and files and scp the tar.gz to the other LXC and uncompress it. When I run the restore as root these error statements appear in the rst,log file

 565: Opened local page read 1 (parent 0)
 565: Error (criu/files-reg.c:1680): File home/user1/tcp-howto has bad mode 0100755 (expect 0100775)
 565: Error (criu/mem.c:768): Can't fixup VMA's fd
 Error (criu/cr-restore.c:1424):  565 killed by signal 9: Killed
Error (criu/cr-restore.c:2300): Restoring FAILED.

I am using this command to run the dump on c1:
# criu dump --tree <pid> --images-dir img-dir/ -v4 -o dump.log --shell-job --tcp-established
and this command to run the restore on c2:
# criu resore --images-dir img-dir/ -v4 -o rst.log --shell-job --tcp-established

Is this method of performing restoring a process supported?
Thank you,
Dan

**Comment by adrianreber** [comment]
That is the important line:
```
565: Error (criu/files-reg.c:1680): File home/user1/tcp-howto has bad mode 0100755 (expect 0100775)
```

Make sure the binary is the same on both involved systems. `chmod 775 /home/user1/tcp-howto` could be a solution.

**Comment by gepatto1** [comment]
Thank you - the permissions for tcp-howto were different on the 2 hosts. Once they were identical, the error did not occur.
