### ISSUE TITLE
Live migration using LXC and CRIU with openvswitch

### ISSUE THREAD

**Issue by haha150** [checkpoint-restore/criu#651]
I am trying to use openvswitch instead of the lxdbr0 that LXC provides and i am able to do so but i cannot live migrate a container attached to the openvswitch on the source to another remote LXD host. The two machines are exactly the same and both run openvswitch with the same name of the switch etc. So when i do "lxc move c1 remote2:", i get the error that the restore fails because it cannot attach the vethXXXX interface to the openvswitch at the destionation. Am i doing something wrong? It provides that the error is from CRIU that it cant attach it, is this is a bug?

Ref: https://github.com/lxc/lxd/issues/5568

**Comment by adrianreber** [comment]
I added a question to the original error report to understand it better. CRIU has no lxdbr0 hard coded anywhere, so there must be some reason in the combination of LXD, LXC and CRIU that lxdbr0 appears.
