### ISSUE TITLE
docker-test travis tesst cases fails

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#653]
It seems the docker-test travis run uses some docker commands which do not exist anymore (maybe?). Do we want to remove this test or can it be easily fixed?

**Comment by avagin** [comment]
It has to be fixed.

**Comment by avagin** [comment]
@adrianreber could you be more detailed what you mean? I looked at last runs and didn't find there any problems. For example:
https://github.com/checkpoint-restore/criu/issues/653

**Comment by rst0git** [comment]
One thing I noticed is that we use a deprecated `--security-opt` format but I'm not sure if this would cause the test to fail. We should change `seccomp:unconfined` to `seccomp=unconfined`  in `scripts/travis/docker-test.sh`.

**Comment by adrianreber** [comment]
Hmm, just saw a failure and lots of error messages, but looking at your link there are also lot of error messages. It seems that is how the test should work. Should have looked closer at the script.

**Comment by avagin** [comment]
> Hmm, just saw a failure and lots of error messages, but looking at your link there are also lot of error messages. It seems that is how the test should work. Should have looked closer at the script.

These errors are intentional. This how we check that a container is not running after the checkpoint operation:
https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/travis/docker-test.sh#L54
