### ISSUE TITLE
Tips for my university project

### ISSUE THREAD

**Issue by emanuelebevegni** [checkpoint-restore/criu#656]
Hi everyone!
Im making a university project with criu but im kinda new to the linux and criu world. Times ago i already asked here on github some advice on criu but now i need your help for improve my work. The university asked me to improve my work and try to stop FireFox with google map open in specific coordinate e re-open it on another pc in the status when i stopped it. I already read something from ur paper but i dont undestand a lot about that, for sure is lack of knowledge from me about many fields. For now i can only stop a simple programm in local and re-start from different shell ( i follow ur paper and example about that ). I hope u could help me in this project. 

this is the link about my last issues maybe it can help u https://github.com/checkpoint-restore/criu/issues/541#issuecomment-414610280

Thanks to everyone!

**Comment by xemul** [comment]
Hi,

We have a long-long-pending request to have this feature implemented :) However, implementing it seems to be quite a huuge task. I've tried to summarize the problems we see in this article: https://criu.org/X_applications .

**Comment by rst0git** [comment]
@emanuelebevegni Migrating a container that is running x11vnc server could be an alternative approach
https://github.com/x11vnc/docker-desktop
https://github.com/fcwu/docker-ubuntu-vnc-desktop

**Comment by emanuelebevegni** [comment]
@rst0git right now im working on fedora, i will read or the papar i give it to me and i have to discuss with my professor about that because its all new for me and if it is not a big task to do. I will update u as soon as i can. Thx a lot

**Comment by rst0git** [comment]
@emanuelebevegni This is a simple checkpoint/restore demo of Firefox
https://www.youtube.com/watch?v=kjhuzSl6JYc

**Comment by emanuelebevegni** [comment]
@rst0git thx for the video, i have a appointment today with my professor and i will show everything to him so we can decide how to proceed. Thank you for all the help.
