### ISSUE TITLE
lxc checkpoint container failed

### ISSUE THREAD

**Issue by ram619** [checkpoint-restore/criu#670]
Error message

lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    criu - criu.c:do_dump:1328 - dump failed with 1
lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    criu - criu.c:do_dump:1342 - criu output: Will skip in-flight TCP connections

lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    lxc_checkpoint - tools/lxc_checkpoint.c:checkpoint:200 - Checkpointing example-ubuntu failed

---------------------------
Debug Output

lxc-checkpoint example-ubuntu 20190412122350.811 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_init_pid" is 0
lxc-checkpoint example-ubuntu 20190412122350.812 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_state" is 0
lxc-checkpoint example-ubuntu 20190412122350.812 DEBUG    commands - commands.c:lxc_cmd_get_state:585 - Container "example-ubuntu" is in "RUNNING" state
lxc-checkpoint example-ubuntu 20190412122350.812 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_state" is 0
lxc-checkpoint example-ubuntu 20190412122350.812 DEBUG    commands - commands.c:lxc_cmd_get_state:585 - Container "example-ubuntu" is in "RUNNING" state
lxc-checkpoint example-ubuntu 20190412122350.816 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_init_pid" is 0
lxc-checkpoint example-ubuntu 20190412122350.819 DEBUG    commands - commands.c:lxc_cmd_rsp_recv:165 - Response data length for command "get_init_pid" is 0
lxc-checkpoint example-ubuntu 20190412122350.819 INFO     criu - criu.c:exec_criu:639 - execing: /usr/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /root/checkpoint -o /root/checkpoint/dump.log --cgroup-root :/lxc/example-ubuntu --cgroup-root name=systemd:/lxc/example-ubuntu --cgroup-root cpu,cpuacct:/lxc/example-ubuntu --cgroup-root devices:/lxc/example-ubuntu --cgroup-root rdma:/lxc/example-ubuntu --cgroup-root pids:/lxc/example-ubuntu --cgroup-root memory:/lxc/example-ubuntu --cgroup-root freezer:/lxc/example-ubuntu --cgroup-root perf_event:/lxc/example-ubuntu --cgroup-root net_cls,net_prio:/lxc/example-ubuntu --cgroup-root cpuset:/lxc/example-ubuntu --cgroup-root hugetlb:/lxc/example-ubuntu --cgroup-root blkio:/lxc/example-ubuntu -vvvvvv --ext-mount-map /sys/fs/fuse/connections:sys/fs/fuse/connections --ext-mount-map /sys/kernel/debug:sys/kernel/debug --ext-mount-map /sys/kernel/security:sys/kernel/security --ext-mount-map /sys/fs/pstore:sys/fs/pstore -t 4857 --skip-in-flight --freeze-cgroup /sys/fs/cgroup/freezer///lxc/example-ubuntu --ext-mount-map /dev/console:console --external tty[8802:15] --force-irmap --leave-running 
lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    criu - criu.c:do_dump:1328 - dump failed with 1
lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    criu - criu.c:do_dump:1342 - criu output: Will skip in-flight TCP connections

lxc-checkpoint example-ubuntu 20190412122351.870 ERROR    lxc_checkpoint - tools/lxc_checkpoint.c:checkpoint:200 - Checkpointing example-ubuntu failed

------------------------------
lxc version
Client version: 3.0.3
Server version: 3.0.3

-------------------------------------

lxc info

 driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-47-generic
  server: lxd
  server_pid: 1332
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: ram-VirtualBox
  project: ""

-------------------------------------------
uname -a
Linux ram-VirtualBox 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adrianreber** [comment]
We need to see the content from CRIU's log file: `dump.log` Can you provide that file?

**Comment by ram619** [comment]
Please help me with the command. I am not sure how to generate that.
Thanks

**Comment by adrianreber** [comment]
According to the output of LXC/LXD it should be at `/root/checkpoint/dump.log`

**Comment by ram619** [comment]
[dump.log](https://github.com/checkpoint-restore/criu/files/3073637/dump.log)

**Comment by adrianreber** [comment]
```
(01.038146) mnt: 	1147: 45:/ @ ./dev/shm
(01.043008) mnt: 	1146: 44:/3 @ ./dev/lxc/tty4
(01.043163) Error (criu/tty.c:2306): tty: Unable to find a master for /3
```
Not sure what `/dev/lxc/tty4` is. Maybe @brauner has an idea.

**Comment by adrianreber** [comment]
After a short chat with @brauner he said that /dev/lxc/tty4 are LXC TTY FDs for running getty. I am not sure what is necessary for CRIU to correctly handle those TTYs. According to the debug output from LXC it seems to call CRIU with `--external tty[8802:15]`, not sure if that is related. Or if something changed in LXC. Maybe someone else has an idea.
