### ISSUE TITLE
Restore fails to restore connection to nfqueue

### ISSUE THREAD

**Issue by aalsudais** [checkpoint-restore/criu#674]
Hello,

I'm running snort in a docker container, which connects to an nfqueue queue on the host network (configured with iptables) to process network packets.
Checkpointing the container seems to work fine. However, when I restore the container, it fails to connect to the queue (cat /proc/net/netfilter/nfnetlink_queue returns nothing). After restoring the container, snort is not able to see any packets.
The same behavior happens when I checkpoint/restore snort that runs as a standalone process.

This is how I created the checkpoint:
`docker checkpoint create snort s0`

And this is how I restored:
`docker start --checkpoint s0 snort`

CRIU info:
`
Version: 3.11
GitID: v3.11-203-ge86c2e9
`

Docker info:
`Docker version 18.09.0, build 4d60db4`

Contents of the fdinfo image file:
```
{
    "magic": "FDINFO", 
    "entries": [
        {
            "id": 30, 
            "flags": 0, 
            "type": "REG", 
            "fd": 0
        }, 
        {
            "id": 31, 
            "flags": 0, 
            "type": "PIPE", 
            "fd": 1
        }, 
        {
            "id": 32, 
            "flags": 0, 
            "type": "PIPE", 
            "fd": 2
        }, 
        {
            "id": 33, 
            "flags": 0, 
            "type": "NETLINKSK", 
            "fd": 3
        }, 
        {
            "id": 34, 
            "flags": 0, 
            "type": "INETSK", 
            "fd": 4
        }, 
        {
            "id": 35, 
            "flags": 0, 
            "type": "REG", 
            "fd": 5
        }
    ]
}
```

**Comment by adrianreber** [comment]
I know nothing about snort or nfqueue, but I guess that snort configures those queues when it starts up. You probably have to set up the queues yourself or add support to CRIU to dump and restore nfqueues.

**Comment by aalsudais** [comment]
Thanks Adrian, 
I just wanted to make sure that I didn't miss something. I'll try to work around this and will probably fork CRIU as I also want to work on adding support for DPDK (though not sure yet how).
