### ISSUE TITLE
criu-coredump failed reporting 'no reg-files.img file'

### ISSUE THREAD

**Issue by dubukuangye** [checkpoint-restore/criu#679]
I am generating coredump from images using criu-coredump. But it failed with error

> No such file or directory: '/tmp/20190418/reg-files.img'

My system configuration is as follows:
CentOS Linux release 7.1.1503 (Core)
CRIU 3.11

The following are the commands that I issued to create the problem.
criu dump -t 14455 --tcp-established --shell-job -vvvv -o dump.log && echo OK
criu restore -d -vvv --tcp-established --shell-job -o restore.log && echo OK

It seems there is no `reg_files.img` any more.
> reg_files.img was merged into files.img

**Comment by adrianreber** [comment]
> It seems there is no `reg_files.img` any more.

Without looking at it, this could be true. criu-coredump has also not been ported to python 3 as far as I know. Is fixing criu-coredump something you would be willing to help? This is probably also something which needs to be included into our CI testing.

**Comment by dubukuangye** [comment]
Of course I would like to help. Here is the code:

```diff
Signed-off-by: guoqd <dubukuangye@sina.com>
---
 coredump/criu_coredump/coredump.py | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/coredump/criu_coredump/coredump.py b/coredump/criu_coredump/coredump.py
index 963e8c6..51ae6b6 100644
--- a/coredump/criu_coredump/coredump.py
+++ b/coredump/criu_coredump/coredump.py
@@ -163,7 +163,8 @@ class coredump_generator:
                        self.mms[pid]           = self._img_open_and_strip("mm", True, pid)
                        self.pagemaps[pid]      = self._img_open_and_strip("pagemap", False, pid)

-               self.reg_files  = self._img_open_and_strip("reg-files", False)
+               files           = self._img_open_and_strip("reg-files", False)
+               self.reg_files  = [ x["reg"] for x in files if x["type"]=="REG" ]

                for pid in self.pstree:
                        self.coredumps[pid] = self._gen_coredump(pid)
```

Now I am in trouble with sending patch using `git send-email` ~_~ And I will fix it!

**Comment by avagin** [comment]
> Now I am in trouble with sending patch using git send-email _ And I will fix it!

You can create a github pull-request.
