### ISSUE TITLE
Ability to ignore file-size checks on restore

### ISSUE THREAD

**Issue by krafczyk** [checkpoint-restore/criu#68]
After I've used `screen -ls` to create the /run/screen directory, I get the following set of errors when trying to restore my screen session.

```
  2941: Warn  (sk-unix.c:1229): sk unix: Can't unlink stale socket 0xda53 peer 0 (name /run/screens/S-matthew/2941.Analysis1 dir -)
  2941: Error (files-reg.c:1067): File run/utmp has bad size 1536 (expect 2688)
Error (cr-restore.c:1236): 2941 killed by signal 9
Error (cr-restore.c:1933): Restoring FAILED.
```

Again, I'm not sure whether criu can do anything about this, but I'm hoping for an expert opinion here.

I should mention, that criu can infact be 'tricked' into skipping past this, by opening the same number of screen sessions that you had open when you dumped the screen, before attempting to restore the screen. It seems the content of these screens doesn't matter.

After I open these screens I'm confronted with these error messages:

```
  2941: Error (tty.c:524): tty: Unable to open dev/ptmx with specified index 0
  2941: Error (tty.c:910): tty: Can't open 6 (index 0): Bad file descriptor
Error (cr-restore.c:1236): 2941 killed by signal 9
Error (cr-restore.c:1933): Restoring FAILED.
```

**Comment by xemul** [comment]
This file, /run/utmp, what is it? And why does it have the wrong size at restore time? Does anybody else writing into it?

**Comment by krafczyk** [comment]
I didn't know what it was either, so a google search turns up: https://en.wikipedia.org/wiki/Utmp

It seems that any login/logout can change utmp.

Is it possible to convince criu to ignore that /run/utmp has the wrong size?

**Comment by xemul** [comment]
We don't have such an option in API, but you can edit the reg-files.img file with crit and remove the 'size' field. Not a nice way, since you have to decode, then encode the file back, but still allows to move forward w/o patching criu.

API changes are possible, I'm OK if someone sends a patch doing this :)

**Comment by dav-ell** [comment]
> We don't have such an option in API, but you can edit the reg-files.img file with crit and remove the 'size' field.

Is this still called `reg-files.img`? Are there restrictions on when it is created?

**Comment by avagin** [comment]
@dav-ell reg_files.img was merged into files.img
