### ISSUE TITLE
capabilities required to restore a process

### ISSUE THREAD

**Issue by ashu-mehra** [checkpoint-restore/criu#684]
I understand we need certain capabilities when using criu in a docker container.
Easiest approach is to use `--privileged` option which grants all the capabilities. But it is not advisable to use this option in production environments. My use-case is to be able to restore a process from a checkpoint in a docker container without using `--privileged` option. For creating the checkpoint I can use `--privileged` option for now.
I want to know if there is any minimal set of capabilities to be granted to docker container which would allow me to restore the process.

After some experiments I am now using `--cap-add SYS_ADMIN --cap-add NET_ADMIN --security-opt apparmor=unconfined` options for starting the docker container, and then remounting `/proc` as read-write.
After this, when I try to restore I get following error:
```
(00.250351) pie: 14: Error (criu/pie/restorer.c:297): Unable to restore capabilities: -1
(00.250394) pie: 81: Error (criu/pie/restorer.c:297): Unable to restore capabilities: -1
(00.250452) Restore finished successfully. Resuming tasks.
(00.250540) pie: 14: Error (criu/pie/restorer.c:1745): BUG at criu/pie/restorer.c:1745
(00.250547) pie: 81: Error (criu/pie/restorer.c:1745): BUG at criu/pie/restorer.c:1745
(00.250658) Error (compel/src/lib/infect.c:1440): Task 14 is in unexpected state: b7f
(00.250677) Error (compel/src/lib/infect.c:1448): Task stopped with 11: Segmentation fault
```
Log files:
[dump.log](https://github.com/checkpoint-restore/criu/files/3116884/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/3116887/restore.log)

Any help is appreciated!

**Comment by ashu-mehra** [comment]
Forgot to mention that when docker container is started with `--cap-add SYS_ADMIN --cap-add NET_ADMIN --security-opt apparmor=unconfined` options, criu check returns following:
```
# /home/ashu/work/criu/criu/criu check
Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
Warn  (criu/kerndat.c:881): Can't keep kdat cache on non-tempfs
Looks good.
```

I guess the error related to `tun` is not really fatal.
My criu level is head of `criu-dev` branch.

**Comment by adrianreber** [comment]
One of the last steps during restore is to restore the capabilities. It seems your are missing the capability to set capabilities. It seems `criu check` does not check if it can change capabilities. Not sure which capability is needed, maybe `CAP_SETPCAP`.

**Comment by rst0git** [comment]
Running the test suite and recording the required capabilities (with [capable](https://github.com/iovisor/bcc/blob/master/tools/capable.py)) results in the following set:

CAP_DAC_OVERRIDE
CAP_CHOWN
CAP_SETPCAP
CAP_SETGID
CAP_AUDIT_CONTROL
CAP_DAC_READ_SEARCH
CAP_NET_ADMIN
CAP_SYS_ADMIN
CAP_SYS_CHROOT
CAP_SYS_PTRACE
CAP_FOWNER
CAP_KILL
CAP_FSETID
CAP_SYS_RESOURCE
CAP_SETUID

**Comment by ashu-mehra** [comment]
@rst0git @adrianreber thanks for responding and for providing the link to that `capable` tool.

Just a bit more background as to what I am trying to do:
1. Checkpoint a process P in a docker container X.
2. Commit the container to create new image, say X1. 
3. Now start a new container using image X1.
4. Restore the process P in the new container.

Now in step 1 I started the docker container with `privileged` option and checkpointed the process.
In step 4, even if I start the new container with the capabilities as mentioned in above [comment](https://github.com/checkpoint-restore/criu/issues/684#issuecomment-486882692) by @rst0git I get the same errors during restore as mentioned in first comment.
However, if the containers used for checkpoint and restore (in step 1 and 4 respectively) are started with same capabilities set, then the restore operation succeeds.

It looks like during checkpoint we store the process capabilities and try to match then during restore, is that correct?

**Comment by rst0git** [comment]
Capabilities are stored in the `core-%u.img` file. You can view (or edit) its content with the `crit` tool.

The error `Unable to restore capabilities: -1` (in the first comment) shows that `capset()` has failed. According to the man page `capset(2)` the reason for the error is likely to be:

> EPERM  An attempt was made to add a capability to the Permitted set, or to set a capability in the Effective or Inheritable sets that is not in the Permitted set.

**Comment by avagin** [comment]
@ashu-mehra you can start a container without --privileged and then call docker exec --privileged criu ...

**Comment by ashu-mehra** [comment]
> start a container without --privileged and then call docker exec --privileged criu ..

@avagin sorry for responding late. For my use-case this would work when I am trying to checkpoint but not during restore. But it looks like the set of capabilities provided by @rst0git should work for now.
I am closing this issue as there is nothing more to be done here. 
Agani, thanks for the help!
