### ISSUE TITLE
restore error on remote node

### ISSUE THREAD

**Issue by weiwang999** [checkpoint-restore/criu#687]
when I restore on the same node, it works while on another node, it fails  the error is as following: 
sudo criu restore -j
Error (criu/cgroup.c:1704): cg: 	Can't mount controller dir .criu.cgyard.fVGJqJ/rdma: No such file or directory

is there anyone who knows the root cause?

**Comment by adrianreber** [comment]
It seems one system has a RDMA cgroup the other does not.

Can you show us the cgroups on both systems?

Maybe you could use `--manage-cgroups none` (or `props`) to ignore the cgroups.

**Comment by weiwang999** [comment]
yes, only one node has a RDMA cgroup. 
could you pls give me a solution of how to ignore this RDMA cgroup?
I can not upgrade my kernel on the node that doesn't have a RDMA cgroup

**Comment by adrianreber** [comment]
Have a look at `--manage-cgroups` in the documentation.

**Comment by weiwang999** [comment]
sudo criu restore -j --manage-cgroups none
Error: excessive parameter for command restore
there is an error

**Comment by weiwang999** [comment]
it doesn't work
sunsky@sunsky:/popcorn/miniz/aarch64$ sudo criu restore --manage-cgroups=none -j
Error (criu/cgroup.c:1704): cg: 	Can't mount controller dir .criu.cgyard.cBua1q/rdma: No such file or directory

**Comment by 0x7f454c46** [comment]
@weiwang999 could you try with this test patch?
https://github.com/0x7f454c46/criu/commit/f7fae62ec2120fc69b84733f4b51ee88f2904f84 (`--manage-cgroups ignore`)

**Comment by weiwang999** [comment]
after fixing the problem with RDMA cgroup, the restoring error still exits 
 sudo criu restore -j
Warn  (criu/net.c:2840): Unable to get tun network namespace
  7363: Error (criu/files-reg.c:1680): File popcorn/miniz has bad mode 040775 (expect 040755)
  7363: Error (criu/files.c:1348): Can't open cwd
Error (criu/cr-restore.c:1421): 7363 exited, status=1
Error (criu/cr-restore.c:2300): Restoring FAILED.

**Comment by 0x7f454c46** [comment]
@weiwang999 a file on your filesystem has different permission - CRIU doesn't migrate your files, rather you/your container engine should bother with copying files to a destination as they were on a checkpoint.

**Comment by weiwang999** [comment]
I fail to understand what this means. all of them is root permission.

**Comment by 0x7f454c46** [comment]
it has `rwx (7)` for group, while criu expect `rx (5)` for group

**Comment by weiwang999** [comment]
thanks, after changing the permission. it works.
but there is a new error 
popcorn-miniz: failed to open: Permission denied

its permission is 775, so it should be not denied. it is weird
-rwxrwxr-x 1 sunsky sunsky  9066190 Apr 30 16:45 popcorn-miniz

**Comment by 0x7f454c46** [comment]
@weiwang999 it looks as the message is printed by your program, is it? Probably, another file that it tries to open has different permissions on the destination system?

**Comment by weiwang999** [comment]
yes. 
in node A :  ./popcorn 1.txt 
-rw-rw-r-- 1 helios helios       14 Apr 30 16:43 1.txt
-rwxrwxr-x 1 helios helios   Apr 30 16:43 popcorn-miniz
then I used criu to checkpoint it and restored it on node B
-rw-rw-r-- 1 sunsky sunsky       14 Apr 30 16:45 1.txt
-rwxrwxr-x 1 sunsky sunsky   Apr 30 16:45 popcorn-miniz

**Comment by 0x7f454c46** [comment]
@weiwang999 a different user? (check UID)

**Comment by weiwang999** [comment]
yes. because on another node to restore it

**Comment by 0x7f454c46** [comment]
so, CRIU restores your applicaton with original UID - either add a user with the same uid on destination, or edit UID in images with CRIT tool.

**Comment by weiwang999** [comment]
Can I use root on both sides?

**Comment by 0x7f454c46** [comment]
If you want to.
Another way is also changing permission for 1.txt to 777 on both source and destination [apriori checkpoint] - than any UID will be able to open it.

**Comment by weiwang999** [comment]
thanks.
I used root and then it's done

**Comment by weiwang999** [comment]
changing permission for 1.txt to 777 on both source and destination [apriori checkpoint] - than any UID will be able to open it
this way is ineffective and using root is the only solution to it.

**Comment by adrianreber** [comment]
This sounds solved. I am closing this. Please reopen if necessary,
