### ISSUE TITLE
Cannot use pivot_root for system running on ramfs

### ISSUE THREAD

**Issue by eliams** [checkpoint-restore/criu#70]
Hi,

I am using docker experimental with native C/R:
criu: Version: 1.7 GitID: v1.7-45-g0516001
docker:version 1.9.0-dev, build 2919249, experimental

I am working on custom system created using buildroot and the restore part fail:
http://pastebin.com/ATV5xJ6B

This happen because my system is running on ram and pivot_root can not
be used for ramfs but as far as I understood the same thing can be done using
mount and chroot right ?

The call to pivot_root is done here: https://github.com/xemul/criu/blob/master/mount.c#L2239

From what I understand from reading the source code, we are restoring
the root task of the container (pid 1), the restore process clone it self so
the clone process can become the root task.
The calltrace is:
  cr_restore_tasks
  -> restore_root_task
    -> for_with_pid
      -> clone

After cloning, the clone starts it execution restore_task_with_pid and the calltrace
to the call of pivo_root is:
  restore_task_with_pid
  -> prepare_namespace
    -> prepare_mnt_ns
      -> cr_pivot_root
        -> pivot_root

pivot_root manpage says:
pivot_root() moves the root filesystem of the calling process to the directory
put_old and makes new_root the new root filesystem of the calling process.

So instead of the call to pivot_root I tried do this:

```
mount("/", put_root, NULL, MS_MOVE, NULL);
chroot(".");
chdir("/");
```

does this seem logic ?
However the call to mount fail with the error: Too many levels of symbolic links.

Can someone explain why are we doing this: https://github.com/xemul/criu/blob/master/mount.c#L2229
I understand the use of MS_BIND flag when calling mount but I dont get the purpose/behavior when
the source and target are the same.

Thanks !

**Comment by xemul** [comment]
Cc @avagin

**Comment by avagin** [comment]
Do you ask about this line https://github.com/xemul/criu/blob/master/mount.c#L2254 ?

It's required for calling pivot_root frome a new user namespaces:
https://github.com/torvalds/linux/commit/5ff9d8a65ce80efb509ce4e8051394e9ed2cd942

**Comment by eliams** [comment]
@avagin Thanks for the answer !

To make the restoration to work, instead of calling  cr_pivot_root here (https://github.com/xemul/criu/blob/master/mount.c#L2853), I do:
```
mount("/", put_root, NULL, MS_MOVE, NULL);
chroot(".");
chdir("/");
```
However the mountpoint clones does no get removed like it does when using pivot_root and umounting the old_root afterwards.

What do you think of falling back to using ms_move (assuming unwanted cloned mountpoints get removed) if pivot_root fails or if a flag ramdisk is specified ?

**Comment by avagin** [comment]
@eliams I don't get the idea. moun("/", put_root, NULL, MS_MOVE, NULL) should fail, because it doesn't have a parent. pivot_root fails by the same reason.
https://github.com/torvalds/linux/blob/master/fs/namespace.c#L2265

**Comment by eliams** [comment]
I meant ``` mount(".", "/", NULL, MS_MOVE, NULL); ```, sorry for that.

**Comment by avagin** [comment]
In this case, I think it's ok. Could you send a patch into the criu mail list?

**Comment by eliams** [comment]
sure.

2015-10-26 12:56 GMT+01:00 Andrew Vagin <notifications@github.com>:
