### ISSUE TITLE
time measure unit

### ISSUE THREAD

**Issue by weiwang999** [checkpoint-restore/criu#702]
I wonder if the frozen_time:282043 refers to 282043ms or S?
"freezing_time": 4228, 
                "frozen_time": 282043, 
                "memdump_time": 2792, 
                "memwrite_time": 2435, 
                "pages_scanned": 9306, 
                "pages_skipped_parent": 0, 
                "pages_written": 1135, 
                "irmap_resolve": 0, 
                "pages_lazy": 0, 
                "page_pipes": 7, 
                "page_pipe_bufs": 7
sunsky@sunsky:/popcorn/brdw/aarch64$ crit show  stats-restore 
{
    "magic": "STATS", 
    "entries": [
        {
            "restore": {
                "pages_compared": 0, 
                "pages_skipped_cow": 0, 
                "forking_time": 1, 
                "restore_time": 18762, 
                "pages_restored": 1134
            }
        }
    ]
}

**Comment by avagin** [comment]
pr_msg("Frozen time: %d us\n", stats->dump->frozen_time);
https://github.com/checkpoint-restore/criu/blob/criu-dev/criu/stats.c#L111

**Comment by avagin** [comment]
microseconds
