### ISSUE TITLE
listing the stack pointer register 'sp' in a clobber list is deprecated

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#705]
https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Extended-Asm.html
> Another restriction is that the clobber list should not contain the stack pointer register. This is because the compiler requires the value of the stack pointer to be the same after an asm statement as it was on entry to the statement. However, previous versions of GCC did not enforce this rule and allowed the stack pointer to appear in the list, with unclear semantics. This behavior is deprecated and listing the stack pointer may become an error in future versions of GCC.

```
In file included from criu/include/restore.h:6,
                 from criu/cr-restore.c:91:
criu/cr-restore.c: In function 'sigreturn_restore':
criu/arch/aarch64/include/asm/restore.h:10:2: error: listing the stack pointer register 'sp' in a clobber list is deprecated [-Werror=deprecated]
   10 |  asm volatile(      \
      |  ^~~
criu/cr-restore.c:3585:2: note: in expansion of macro 'JUMP_TO_RESTORER_BLOB'
 3585 |  JUMP_TO_RESTORER_BLOB(new_sp, restore_task_exec_start, task_args);
      |  ^~~~~~~~~~~~~~~~~~~~~
criu/arch/aarch64/include/asm/restore.h:10:2: note: the value of the stack pointer after an 'asm' statement must be the same as it was before the statement
   10 |  asm volatile(      \
      |  ^~~
criu/cr-restore.c:3585:2: note: in expansion of macro 'JUMP_TO_RESTORER_BLOB'
 3585 |  JUMP_TO_RESTORER_BLOB(new_sp, restore_task_exec_start, task_args);
      |  ^~~~~~~~~~~~~~~~~~~~~
  CC       criu/crtools.o
cc1: all warnings being treated as errors
make[2]: *** [/criu/scripts/nmk/scripts/build.mk:119: criu/cr-restore.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [criu/Makefile:76: criu/built-in.o] Error 2
```

**Comment by avagin** [comment]
Cc: @0x7f454c46 @cyrillos

**Comment by cyrillos** [comment]
Heh, actually because we setup new `sp` in this code we've put it into the clobber list to tell the compiler sp is clobbered and eliminate potential problems. I don't mind moving it out of the list though.

**Comment by rst0git** [comment]
What about `JUMP_TO_RESTORER_BLOB`?
> the compiler requires the value of the stack pointer to be the same after an asm statement as it was on entry to the statement.

**Comment by rst0git** [comment]
This change was introduced with https://github.com/gcc-mirror/gcc/commit/7675b21555c and https://github.com/gcc-mirror/gcc/commit/9d1cdb749a1. It looks like it is safe to simply dropping sp from the clobber list.

For `JUMP_TO_RESTORER_BLOB`, Jeff Law suggested (in his [commit message](https://github.com/checkpoint-restore/criu/commit/901f5d48ec6ef485ea889a4a97011a12f4c3808e)) that while setting the stack pointer is pedantically correct, it actually has no real effect and can just be dropped to avoid the error from gcc.

**Comment by rst0git** [comment]
Sorry for the noise. @cyrillos is right, simply moving `sp` out of the clobber list resolves the build issue.
