### ISSUE TITLE
RFE: Replace detect_pid_reuse() check from using task's creation time to keeping pidfd on pre-dump

### ISSUE THREAD

**Issue by 0x7f454c46** [checkpoint-restore/criu#717]
It's a raw arguable idea, but we might want to use pidfd instead of /proc/<pid>/stat creation time.

**Comment by adrianreber** [comment]
Sounds like a good idea!

**Comment by avagin** [comment]
Cc: @Snorch

**Comment by rppt** [comment]
Sounds like a Plumbers topic ;-)

**Comment by Snorch** [comment]
It sounds a good idea for me as with pidfd way the detection should be more reliable, no inaccuracy because of low time precision.

**Comment by ZeyadYasser** [comment]
I was looking into this issue and starting to understand how pre-dumps work, but now I am blocked by a problem and need pointers on where to look or suggestions.
How to keep the same pidfd opened through iterative pre-dumps until the process is dumped?
If I get the pidfd of a process during pre-dump, this file descriptor will be closed when the pre-dump stage finishes, re-opening the pidfd on the next pre-dump or dump might open the pidfd of another process that reused that PID.

**Comment by adrianreber** [comment]
I think you are right, @ZeyadYasser. Looking at the code of `detect_pid_reuse()` it does not seem possible to use pidfd. If I understand `detect_pid_reuse()` correctly it takes the start time out of the parent image and compares it with the start time of the the current pre-dump run.

pidfd would only be helpful if we can transfer the pidfd FD from one pre-dump run to another. Maybe using a socket, but usually the parent pre-dump run will have exited and possibly a long time ago. I also see no way of easily transferring  the pidfd FD from one pre-dump process to another.

**Comment by Snorch** [comment]
> detect_pid_reuse() correctly it takes the start time out of the parent image and compares it with the start time of the the current pre-dump run.

@adrianreber , No =) It takes current start time of the process and compares it with the previous pre-dump time. If process lives long enough to be in previous pre-dump we understand that there were no pid-reuse.

> How to keep the same pidfd opened through iterative pre-dumps until the process is dumped?

@ZeyadYasser , When you do iterative migration there is always some process which lives all the time (p.haul likely) and controlls the migration. You should just transfer pidfd to this process at the end of pre-dump and take descriptor from this process at the begining of next pre-dump.

**Comment by ZeyadYasser** [comment]
@Snorch Could we add pidfd based pid reuse detection to P.Haul directly [here](https://github.com/checkpoint-restore/go-criu/blob/master/phaul/client.go#L55) instead of passing the the pidfds back and forth between CRIU and P.Haul to do the same thing? since it already controls the migration flow from start to finish. please correct me if I am wrong.

**Comment by ZeyadYasser** [comment]
> @Snorch Could we add pidfd based pid reuse detection to P.Haul directly [here](https://github.com/checkpoint-restore/go-criu/blob/master/phaul/client.go#L55) before each pre-dump instead of passing the the pidfds back and forth between CRIU and P.Haul to do the same thing? since it already controls the migration flow from start to finish. please correct me if I am wrong.

@Snorch Do you think this approach https://github.com/checkpoint-restore/go-criu/pull/35 increases the reliability of pid reuse detection? I mentioned a short coming of my approach in the PR which could make it not suitable in rare cases.

Your feedback would be highly appreciated.

**Comment by Snorch** [comment]
@ZeyadYasser I've commented to the PR. I don't think it will work like this. The pid-reuse-detection is a security feature which should be closely integrated into criu (criu should see which pids are reused and which are not), p.haul can be a fd storage for criu's pidfds but probably nothing more, I'd rather put main logic to criu.
