### ISSUE TITLE
Dump exponentially slower on multi-core setup

### ISSUE THREAD

**Issue by haha150** [checkpoint-restore/criu#720]
Hi,

So, i have tested out CRIU a bit now and have stumbled upon a weird problem. I use CRIU with LXD and whenever i create a stateful snapshot of a container (or perform live migration) on a machine that has 2 CPU cores or more, it takes much longer to execute than on a setup that has 1 CPU core. I also tried to limit the container to only have one CPU core and also CPU pinned one to ensure that only one is used but it does not help.

So i am wondering, why does CRIU dump and live migration perform poorly on machines running more than 2 Cores but is "OK" on a machine with 1 CPU core?

Example:
lxc launch images:alpine/edge c1
lxc snapshot c1 s1 --stateful

**Comment by avagin** [comment]
Could you attach logs for both cases?
