### ISSUE TITLE
seccomp: Strict mode restore

### ISSUE THREAD

**Issue by 0x7f454c46** [checkpoint-restore/criu#722]
I believe we're not restoring correctly for `strict` mode.
I see the following on trace for `zdtm/static/seccomp_strict` test:
```
[pid    37] prctl(PR_SET_SECCOMP, SECCOMP_MODE_STRICT <unfinished ...>
[pid    36] gettid( <unfinished ...>
[pid    37] <... prctl resumed>)        = 0
[pid    36] <... gettid resumed>)       = 36
[pid    37] gettimeofday( <unfinished ...>
[pid    36] write(127, "(00.079664) pie: 36: seccomp: mo"..., 47(00.079664) pie: 36: seccomp: mode 0 on tid 36
) = 47
[pid    36] prctl(PR_SET_SECUREBITS, SECBIT_NO_SETUID_FIXUP <unfinished ...>
[pid    37] <... gettimeofday resumed> <unfinished ...>) = ?
[pid    36] <... prctl resumed>)        = 0
[pid    36] setresuid(0, 0, 0)          = 0
[pid    36] setfsuid(0)                 = 0
[pid    36] setfsuid(-1)                = 0
[pid    37] +++ killed by SIGKILL +++
```
Though, I haven't checked why the test still passes (working on a different issue).

`man prctl` has the following:

> With  arg2  set to SECCOMP_MODE_STRICT, the only system calls that the thread is permitted to make are read(2), write(2), _exit(2) (but not exit_group(2)), and sigreturn(2).  Other system calls result in the delivery of a SIGKILL signal.  Strict secure computing mode is useful for number-crunching applications that may need to execute untrusted byte code, perhaps obtained by reading from a pipe or socket.  This operation is available only if the kernel is configured with CONFIG_SECCOMP enabled.

As far as I can see, currently we are not only doing sys_gettimeofday() in the restorer, but also restoring a whole bunch of stuff after
```
if (restore_seccomp(args->t))
```

This issue with strict mode looks quite hard to solve with current criu restore process: we're not only using sys_gettimeofday() for restorer (which is minor) - we synchronize with sys_futex(), we need to sys_close() fds and furthermore, we need to sys_unmap() restorer's blob in the end. All that is prohibited in strict mode as per my scanty understanding.

**Comment by rst0git** [comment]
> This issue with strict mode looks quite hard to solve with current criu restore process: we're not only using sys_gettimeofday() for restorer (which is minor) - we synchronize with sys_futex(), we need to sys_close() fds and furthermore, we need to sys_unmap() restorer's blob in the end. All that is prohibited in strict mode as per my scanty understanding.

Isn't that issue resolved with [this patch](https://lkml.org/lkml/2015/6/13/115)?

**Comment by 0x7f454c46** [comment]
@rst0git sounds like it should and I see it in source on cr-restore - so probably, it should work..
But what I've seen on the trace - the child gets killed on sys_gettimeofday() from restorer, which shouldn't happen. There is off cause a chance that I've screwed up something on the test..
I may look into this after finishing what I was cooking.

**Comment by avagin** [comment]
@0x7f454c46 have you seen this?
```
                        /*
                         * Suspend seccomp if necessary. We need to do this because
                         * although seccomp is restored at the very end of the
                         * restorer blob (and the final sigreturn is ok), here we're
                         * doing an munmap in the process, which may be blocked by
                         * seccomp and cause the task to be killed.
                         */
                        if (rsti(item)->has_seccomp && ptrace_suspend_seccomp(pid) < 0)
                                pr_err("failed to suspend seccomp, restore will probably fail...\n");
```

**Comment by 0x7f454c46** [comment]
@avagin Yes, as I pointed in the previous message - it seems like it should work..
But what I saw on a trace - is that the restored child was killed on sys_gettimeofday().
Which is also a little mystery to me - how the test passed afterwards.
I might have screwed up something on the testing - need to dig further a bit later.

**Comment by 0x7f454c46** [comment]
Ok, figured it out: as suspected, I hecked up testing by using `--sat` for zdtm.py.
Which in result doesn't let criu to use `PTRACE_SUSPEND_SECCOMP`, resulting in SIGKILL for a restoree.
Wasn't aware of the details and suspected that something might go wrong "under cover" of test.
