### ISSUE TITLE
Trouble with dumping a already restored process tree again. (criu-ns.py)

### ISSUE THREAD

**Issue by tjalo** [checkpoint-restore/criu#726]
Hi everybody,

I have some trouble dumping a process tree again after restoring it to a different pid namespace with the criu-ns.py script. I'm using version 3.12.

My workflow:
I'm directly working on a Debian (no container) and have a multi threaded process started by systemd with 'normal' user rights. Now I dump the process using:

`sudo criu-ns.py dump --tree <PID_OF_PROCESS> --shell-job --tcp-established -vvv --log-file dump.txt --ext-unix-sk`

and it works fine. E.g.: the PID of the process was 659.

I **restart** Linux and restore the process with

`sudo criu-ns.py restore --shell-job --log-file restore.txt -vvv --restore-detached --tcp-established --pidfile pid.txt`

This also seems to work fine.
The process is restored with a 'new' pid (e.g.: 699) where the old one can be found in the namespace (`cat /proc/699/status | grep NSpid` => '_NSpid: 699 659_').
When I try to dump the process again with:

`sudo criu-ns.py dump --tree 699 --shell-job --tcp-established -vvv --log-file dump.txt --ext-unix-sk`

the dump fails with the expected message: '_Replace pid 699 with 659_'.
So I tried to dump the process with the origin pid:

`sudo criu-ns.py dump --tree 659 --shell-job --tcp-established -vvv --log-file dump.txt --ext-unix-sk`

which fails with:

_Traceback (most recent call last):
  File "/usr/sbin/criu-ns.py", line 251, in <module>
    res = wrap_dump()
  File "/usr/sbin/criu-ns.py", line 208, in wrap_dump
    set_pidns(pid, pid_idx)
  File "/usr/sbin/criu-ns.py", line 148, in set_pidns
    ns_fd = os.open('/proc/%s/ns/pid' % tpid, os.O_RDONLY)
OSError: [Errno 2] No such file or directory: '/proc/659/ns/pid_

This also seems to be correct because there is no process with pid 659 in /proc/ anymore.

How can I achieve to dump the restored process tree again? Any suggestions?

Regards, Thomas

**Comment by rst0git** [comment]
One way to do this could be:
1. Checkpoint your application: `criu dump -t $PID ...`
2. Create a new PID namespace: `unshare --fork --pid --mount-proc bash`
3. Restore your application inside this new PID namespace: `criu restore ...`

In a different terminal:

4. Get the new PID of your application: `pgerp <Application Name>`
5. Enter its namespace: `nsenter -a -t $NEW_PID bash`
6. Checkpoint your application from within the namespace: `criu dump -t $PID ...`

Or you can use runc, podman, docker, etc. instead.

**Comment by tjalo** [comment]
Thanks for the advise.
I'll test it later on.
