### ISSUE TITLE
Docker live migration - Restoring TCP connections

### ISSUE THREAD

**Issue by adibrastegarnia** [checkpoint-restore/criu#736]
Hi, 

I would like to know if Docker live migration uses CRIU supports restoring TCP connections? Is there any working example that I can try? 

Thanks,
Adib

**Comment by adrianreber** [comment]
If the runc version provided by docker is new enough you could use https://criu.org/Configuration_files to tell CRIU to always use `--tcp-established`.

If you want to try Podman (https://criu.org/Podman) you can tell Podman to use `--tcp-established` directly. See Podman's test suite for an example: https://github.com/containers/libpod/blob/master/test/e2e/checkpoint_test.go#L223

https://github.com/containers/libpod/blob/master/docs/podman-container-checkpoint.1.md

**Comment by adibrastegarnia** [comment]
@adrianreber 

Thanks for your response. I will take a look at those resources and I will ask my questions if I have any.

**Comment by adrianreber** [comment]
@adibrastegarnia let us also know if you find a solution that works for you 😉

**Comment by plaoil** [comment]
@adrianreber What are the version requirements for runc

**Comment by adrianreber** [comment]
You need at least https://github.com/opencontainers/runc/commit/e157963054e1be28bcd6612f15df1ea561c62571

Also see
 * https://github.com/checkpoint-restore/criu/issues/554
 * https://github.com/checkpoint-restore/criu/issues/599
