### ISSUE TITLE
want CRIU_VERSION_NUMBER in header

### ISSUE THREAD

**Issue by mrtc0** [checkpoint-restore/criu#738]
I want like `CRIU_VERSION_NUMBER` in criu.h.

For example, in the case of https://github.com/checkpoint-restore/criu/commit/9ede9253f5d04e7ade626ece8b96bb66bf6dc938, binding like mruby-criu can be changed with backward compatibility.

**Comment by adrianreber** [comment]
I was not aware that there exists a ruby binding for CRIU. Good to know. You probably mean this one:
https://github.com/matsumotory/mruby-criu

Do you need a define for the ruby CRIU bindings or would a function also work?

**Comment by mrtc0** [comment]
I want `define` for the ruby CRIU bindings.
I want to use this macro for conditional branching with ifdef.
For example,

```c
#if CRIU_VERSION < 1.1
  criu_set_service_comm();
#endif
```
So, Binding can support with new versions, with compatibility.

**Comment by rst0git** [comment]
@mrtc0 would that work for you?
```diff
diff --git a/lib/Makefile b/lib/Makefile
index 67c50b95a..e64fd713f 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -54,6 +54,7 @@ install: lib-c lib-a lib-py crit/crit lib/c/criu.pc.in
        $(Q) install -m 755 lib/c/$(CRIU_A) $(DESTDIR)$(LIBDIR)/$(CRIU_A)
        $(Q) mkdir -p $(DESTDIR)$(INCLUDEDIR)/criu/
        $(Q) install -m 644 $(UAPI_HEADERS) $(DESTDIR)$(INCLUDEDIR)/criu/
+       $(Q) cat criu/include/version.h >> $(DESTDIR)$(INCLUDEDIR)/criu/criu.h
        $(E) "  INSTALL " pkgconfig/criu.pc
        $(Q) mkdir -p $(DESTDIR)$(LIBDIR)/pkgconfig
        $(Q) sed -e 's,@version@,$(CRIU_VERSION),' -e 's,@libdir@,$(LIBDIR),' -e 's,@includedir@,$(dir $(INCLUDEDIR)/criu/),' lib/c/criu.pc.in > lib/c/criu.pc
```

Or perhaps we could simply install the `version.h` file in `/usr/include/criu/`?

**Comment by mrtc0** [comment]
Both sound good.
