### ISSUE TITLE
About the time to write image file to disk.

### ISSUE THREAD

**Issue by JinuJeong** [checkpoint-restore/criu#741]
I injected code to criu which measure dump execution time because wanted to looking how long it takes. But the criu execution time and the time actually written to the disk were different when used docker command "docker checkpoint". 

When size of container memory is 4GB, criu execution time is 5 seconds. But When checked at the terminal, it took 30 seconds to write the image file after it was created. Is there another action after the criu is over? Or is it a system delay issue?

**Comment by adrianreber** [comment]
Using docker introduces multiple layers between your command and the CRIU binary. Which can take time, especially as most layers are exec()ing the layer below. If you look at stats-dump from the docker checkpoint you should see how long CRIU actually takes.

For you to have numbers to compare I did the following with Podman:
```
# podman run -d quay.io/adrianreber/wildfly-hello
c58f25b9a9aaf3d2f6d5f771deb3350468a11649c643e72e0ffed41e742ade7d
# time podman container checkpoint -k -l  
c58f25b9a9aaf3d2f6d5f771deb3350468a11649c643e72e0ffed41e742ade7d

real	0m0.904s
user	0m0.131s
sys	0m0.246s

# crit show /var/lib/containers/storage/overlay-containers/c58f25b9a9aaf3d2f6d5f771deb3350468a11649c643e72e0ffed41e742ade7d/userdata/stats-dump 
{
    "magic": "STATS",
    "entries": [
        {
            "dump": {
                "freezing_time": 113553,
                "frozen_time": 571427,
                "memdump_time": 252514,
                "memwrite_time": 189972,
                "pages_scanned": 304276,
                "pages_skipped_parent": 0,
                "pages_written": 28531,
                "irmap_resolve": 0,
                "pages_lazy": 0,
                "page_pipes": 16,
                "page_pipe_bufs": 16
            }
        }
    ]
}
```

Which gives me about 0.4 seconds to dump and write the memory of my test process (330MB) and a bit more than 0.9 seconds total going through all Podman's layers (Podman, runc, criu) to write additional checkpoint data (besides CRIU's images) out to disk and tear down the container.

Hope that helps, you probably have to instrument all layers involved to get accurate measurements about what requires how much time. So it can be pretty fast but measuring each involved layer is probably necessary to have a correct answer.

Restore seems to be a bit faster:
```
#️ time podman container restore -k -l  
c58f25b9a9aaf3d2f6d5f771deb3350468a11649c643e72e0ffed41e742ade7d

real	0m0.455s
user	0m0.066s
sys	0m0.090s
```

**Comment by rst0git** [comment]
As Adrian already mentioned, [Docker's architecture](https://docs.docker.com/engine/docker-overview/) is complex and the interaction between different components has significant overhead. In general, checkpoint/restore with Podman or LXC should be faster than Docker because they have lass layers involved.

**Comment by avagin** [comment]
Cc: @kolyshkin
