### ISSUE TITLE
ppc64le: FAIL selinux00.c:79: Wrong SELinux context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0 expected unconfined_u:unconfined_r:unconfined_dbusd_t:s0

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#744]
https://ci.openvz.org/job/CRIU/job/CRIU-ppc64le/job/criu-dev/4523/console

```
======================== Run zdtm/static/selinux00 in h ========================
Start test
./selinux00 --pidfile=selinux00.pid --outfile=selinux00.out
Running zdtm/static/selinux00.hook(--post-start)
Running zdtm/static/selinux00.hook(--pre-dump)
Run criu dump
Running zdtm/static/selinux00.hook(--pre-restore)
Run criu restore
Running zdtm/static/selinux00.hook(--post-restore)
Send the 15 signal to  38
############### Test zdtm/static/selinux00 FAIL at result check ################
Test output: ================================
19:14:50.171:    38: FAIL: selinux00.c:79: Wrong SELinux context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0 expected unconfined_u:unconfined_r:unconfined_dbusd_t:s0
 (errno = 0 (Success))
```

**Comment by adrianreber** [comment]
Is this a new test failure or does this happen for already for a longer time? Is this ppc64le only?

**Comment by avagin** [comment]
The ppc64le worker was out-of-service for a few months, so I think it isn't a new failure. I see it only on ppc64le.

**Comment by avagin** [comment]
[root@criu ~]# uname -a
Linux criu.novalocal 5.1.16-200.fc29.ppc64le #1 SMP Wed Jul 3 14:50:09 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
[root@criu ~]# cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-5.1.16-200.fc29.ppc64le root=UUID=e310499a-7ae9-46e6-aeeb-e9babe31e019 ro no_timer_check console=tty1 console=ttyS0,115200n8 rhgb quiet console=hvc1 LANG=en_US.UTF-8
[root@criu ~]# cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
[root@criu ~]# cat /etc/selinux/config 

# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=enforcing
# SELINUXTYPE= can take one of these three values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are protected. 
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

**Comment by adrianreber** [comment]
Thanks for that additional information. I just tried it on a x86_64 Fedora 29 and there it still works.

I selected the context pretty randomly, but I thought dbus will be available on all systems. At least the label.

Can you check with what context dbus is running:
```
# ps axZ | grep dbus
system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 554 ? Ssl   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
```
I will start a ppc64le VM to test tomorrow.

**Comment by adrianreber** [comment]
The fix is actually pretty easy: `dnf install libselinux-devel`. CRIU's selinux support is automatically added if libselinux-devel is installed. The tests are only verifying that SELinux is actually enabled and not looking if a certain package (or header) is installed. Should the tests verify that CRIU knows how to correctly handle SELinux or can you just install the package on the jenkins systems?

**Comment by rst0git** [comment]
`libselinux-devel` is a dependency and IMHO it should be installed in a test environment where SElinux is being used.

@adrianreber what do you think about adding a message that could indicate a similar issue in the future?
```diff
diff --git a/Makefile.config b/Makefile.config
index 6f7324069..7b9cb3257 100644
--- a/Makefile.config
+++ b/Makefile.config
@@ -13,6 +13,8 @@ endif
 ifeq ($(call pkg-config-check,libselinux),y)
         LIBS_FEATURES  += -lselinux
         FEATURE_DEFINES        += -DCONFIG_HAS_SELINUX
+else
+        $(info Note: Building without SElinux support)
 endif
 
 ifeq ($(NO_GNUTLS)x$(call pkg-config-check,gnutls),xy)

```

**Comment by 0x7f454c46** [comment]
I'm actually thinking that it might be better to convert all build-time messages about optional features into the output of `criu check`. Currently, it reports only run-time features of the kernel, but we may state "compiled without XXX support".
Not that I'll stop this merging, but I'm just starting to feel a bit annoyed about unwanted build-time messages :)

**Comment by 0x7f454c46** [comment]
And some people may get criu with a package manager - and might want to know why this `XXX` doesn't work

**Comment by 0x7f454c46** [comment]
And on the top of that - we would be able to add `feature: selinux-compiled` or something into `selinux00.desc`.

**Comment by rst0git** [comment]
@0x7f454c46 this sounds like a good idea.
