### ISSUE TITLE
live migrate container restore failed

### ISSUE THREAD

**Issue by changuoqiang** [checkpoint-restore/criu#764]
try live migrate container between hosts, rise error as below:

"Error: Failed container creation: Error transferring container data: migration restore failed
(00.000083) Warn  (criu/log.c:203): The early log isn't empty
(00.084564) Warn  (criu/cr-restore.c:1265): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.661074)      1: Error (criu/fsnotify.c:524): fsnotify: Unable to open /sys/fs/cgroup/unified/system.slice/cgroup.events: No such file or directory
(00.661096)      1: Error (criu/files.c:1196): Unable to open fd=6 id=0x28
(00.797136) Error (criu/cr-restore.c:2293): Restoring FAILED."

lxc info:
...
 driver: lxc
  driver_version: 3.0.4
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features: {}
  kernel_version: 4.19.0-5-amd64
  lxc_features: {}
  project: ""
  server: lxd
  server_clustered: false
  server_name: vmin
  server_pid: 1477
  server_version: 3.0.4
  storage: zfs
  storage_version: 0.7.13-1~bpo10+1

uname -a:
Linux vmin 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

[migration_restore_2019-08-14T11:14:44+08:00.log](https://github.com/checkpoint-restore/criu/files/3499940/migration_restore_2019-08-14T11.14.44%2B08.00.log)

**Comment by adrianreber** [comment]
The `unified` directory in the path of the error message indicates that this seems to be a system with cgroupv2. Not sure if CRIU already supports cgroupv2, I am not aware of any development in that direction.

**Comment by rst0git** [comment]
@adrianreber It seems like cgroupsv2 support might be required for CRIU to work on Fedora 31 https://github.com/opencontainers/runc/pull/2113

**Comment by adrianreber** [comment]
@rst0git Thanks for pointing that out. There is also a question to add CRIU support to crun https://github.com/containers/crun/issues/71 also related to cgroup v2 (as far as I understand it).
