### ISSUE TITLE
criu restore failed, but restore.log shows Restore finished successfully

### ISSUE THREAD

**Issue by xiaochutan123l** [checkpoint-restore/criu#765]
Hello, i'm  doing my student thesis, which let me to checkpoint and restore a container, which contains a python program,and it will send udp packets to another computer. Instead of using docker checkpoint +docker start, i must use criu dump + criu restore, in order to reduce the downtime.

the criu dump is always succeed, but the strange thing is: restore.log says it was successful, but what i see is that after criu restore the python program is running, but there is no running container.

**Comment by xiaochutan123l** [comment]
here are the dump.log, restore.log and the bash script

**Comment by xiaochutan123l** [comment]
here are the dump and restore log file, and bash script

**Comment by xiaochutan123l** [comment]
file:///home/tan/Documents/test7/restore.log
file:///home/tan/Documents/test7/bashfile_dumpN.txt
file:///home/tan/Documents/test7/dump.log

**Comment by xiaochutan123l** [comment]
[bashfile_dumpN.txt](https://github.com/checkpoint-restore/criu/files/3507185/bashfile_dumpN.txt)
[dump.log](https://github.com/checkpoint-restore/criu/files/3507186/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/3507187/restore.log)
here are the bash script and dump.log, restore.log

**Comment by xiaochutan123l** [comment]
and here are the docker and criu version:
 docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: true

 criu --version
Version: 2.6

$ cat /etc/issue
Ubuntu 16.04.3 LTS

**Comment by xiaochutan123l** [comment]
before criu dump:
root      2897  0.0  0.0  62104  4444 pts/20   S+   22:43   0:00 sudo ./bashfile_dumpN.sh
root      2906  0.0  0.0  19608  3348 pts/20   S+   22:43   0:00 /bin/bash ./bashfile_dumpN.sh
root      2907  0.5  0.2 366180 17144 pts/20   Sl+  22:43   0:00 docker run --network=host --name=udp-check xiaochutan123/udp-check
root      2926  0.0  0.0 283396  2856 ?        Sl   22:43   0:00 docker-containerd-shim 02372d911021cb2dbabcfe436394056fb4997013c5e9296c348b8f3f4655747c /var/run/docker/libcontainerd/02372d911021cb2dbabcfe436394056fb4997013c5e9296c348b8f3f4655747c docker-runc
root      2943  3.5  0.1  41096  8796 ?        Ss   22:43   0:00 python -u udp_sender.py
tan       2981  0.0  0.0  44432  3572 pts/21   R+   22:43   0:00 ps aux

after criu restore:
root      2897  0.0  0.0  62104  4444 pts/20   S+   22:43   0:00 sudo ./bashfile_dumpN.sh
root      2906  0.0  0.0  19640  3372 pts/20   S+   22:43   0:00 /bin/bash ./bashfile_dumpN.sh
root      3101  0.0  0.0  14360   668 pts/20   S+   22:43   0:00 sleep 8
root      3107  2.0  0.0  41100  4320 ?        Ss   22:43   0:00 python -u udp_sender.py
tan       3138  0.0  0.0  44432  3628 pts/21   R+   22:43   0:00 ps aux

you can see that only the python program is running after restoring, but no running container.
can someone tell me why is it so strange and how to fix it? thanks a lot.

**Comment by adrianreber** [comment]
I am confused why you think that this should work. On restore you are not setting up the container so how should it be running.

You are taking the PID of your python program, so how should it still be running after docker's control after restore.

Not having looked at the logs in details but I would expect that CRIU restores all namespaces correctly, so probably the restored process will be running with the same namespace isolation as under docker's control, but if you do not start the restored process under docker's control or if you do not restore or re-setup docker, no docker will be running.

So my main question is why do you expect docker to be running after restore? You are only operating on the python process.

Or another question how do you define that a process is running in a container?

How I understand it you expect that the restored process is running under docker's control, that cannot work how you do it. There is something conceptually wrong with how you do it.

But if you are only looking to use pre-copy and post-copy in combination with a container you could use runc to start and stop containers. runc supports pre-copy and post-copy migration.
This way you do not need to do all the container setup and management yourself. runc would all do it.  I have done something like this at: https://www.redhat.com/en/blog/container-migration-around-world

**Comment by rst0git** [comment]
> Instead of using docker checkpoint +docker start, i must use criu dump + criu restore, in order to reduce the downtime.

If I understand correctly, you want to avoid using `docker checkpoint` and `docker start`, and instead use `criu dump` and `criu restore` directly to reduce the downtime.

You should be able to achieve this by performing the `dump` and `restore` inside the container, otherwise (as Adrian already mentioned) docker will not know about the existence of the restored container.

Alternatively, if you want, you can try the new feature of [Podman](https://criu.org/Podman#Container_Live_Migration) (i.e. `--export`/`--import`) and compare that to `docker checkpoint`/`docker start`.

**Comment by xiaochutan123l** [comment]
> I am confused why you think that this should work. On restore you are not setting up the container so how should it be running.
> 
> You are taking the PID of your python program, so how should it still be running after docker's control after restore.
> 
> Not having looked at the logs in details but I would expect that CRIU restores all namespaces correctly, so probably the restored process will be running with the same namespace isolation as under docker's control, but if you do not start the restored process under docker's control or if you do not restore or re-setup docker, no docker will be running.
> 
> So my main question is why do you expect docker to be running after restore? You are only operating on the python process.
> 
> Or another question how do you define that a process is running in a container?
> 
> How I understand it you expect that the restored process is running under docker's control, that cannot work how you do it. There is something conceptually wrong with how you do it.
> 
> But if you are only looking to use pre-copy and post-copy in combination with a container you could use runc to start and stop containers. runc supports pre-copy and post-copy migration.
> This way you do not need to do all the container setup and management yourself. runc would all do it. I have done something like this at: https://www.redhat.com/en/blog/container-migration-around-world

i think i understand it now, after restoring only python program running is correct, because i didn't wake up docker. 
i will try runc and thank you so much.

**Comment by xiaochutan123l** [comment]
> > Instead of using docker checkpoint +docker start, i must use criu dump + criu restore, in order to reduce the downtime.
> 
> If I understand correctly, you want to avoid using `docker checkpoint` and `docker start`, and instead use `criu dump` and `criu restore` directly to reduce the downtime.
> 
> You should be able to achieve this by performing the `dump` and `restore` inside the container, otherwise (as Adrian already mentioned) docker will not know about the existence of the restored container.
> 
> Alternatively, if you want, you can use the `checkpoint`/`restore` commands of [`runc`](https://github.com/opencontainers/runc) directly or try the new feature of [Podman](https://criu.org/Podman#Container_Live_Migration) (i.e. `--export`/`--import`) and compare that to `docker checkpoint`/`docker start`.

yes, that's what i mean. I just followed my supervisors advice to use criu dump + criu restore, i thought it would work. i can try both runc and Podman and find the fast one. thanks a lot.

**Comment by xiaochutan123l** [comment]
> I am confused why you think that this should work. On restore you are not setting up the container so how should it be running.
> 
> You are taking the PID of your python program, so how should it still be running after docker's control after restore.
> 
> Not having looked at the logs in details but I would expect that CRIU restores all namespaces correctly, so probably the restored process will be running with the same namespace isolation as under docker's control, but if you do not start the restored process under docker's control or if you do not restore or re-setup docker, no docker will be running.
> 
> So my main question is why do you expect docker to be running after restore? You are only operating on the python process.
> 
> Or another question how do you define that a process is running in a container?
> 
> How I understand it you expect that the restored process is running under docker's control, that cannot work how you do it. There is something conceptually wrong with how you do it.
> 
> But if you are only looking to use pre-copy and post-copy in combination with a container you could use runc to start and stop containers. runc supports pre-copy and post-copy migration.
> This way you do not need to do all the container setup and management yourself. runc would all do it. I have done something like this at: https://www.redhat.com/en/blog/container-migration-around-world

i saw there are some examples using criu dump + criu restore to checkpoint and restore a container, are they dumping the pid of docker?
e.g. [https://criu.org/Docker_External](url)

**Comment by xiaochutan123l** [comment]
> > > Instead of using docker checkpoint +docker start, i must use criu dump + criu restore, in order to reduce the downtime.
> > 
> > 
> > If I understand correctly, you want to avoid using `docker checkpoint` and `docker start`, and instead use `criu dump` and `criu restore` directly to reduce the downtime.
> > You should be able to achieve this by performing the `dump` and `restore` inside the container, otherwise (as Adrian already mentioned) docker will not know about the existence of the restored container.
> > Alternatively, if you want, you can use the `checkpoint`/`restore` commands of [`runc`](https://github.com/opencontainers/runc) directly or try the new feature of [Podman](https://criu.org/Podman#Container_Live_Migration) (i.e. `--export`/`--import`) and compare that to `docker checkpoint`/`docker start`.
> 
> yes, that's what i mean. I just followed my supervisors advice to use criu dump + criu restore, i thought it would work. i can try both runc and Podman and find the fast one. thanks a lot.

btw can you tell me how can i perform dump and restore inside the container?

**Comment by rst0git** [comment]
> btw can you tell me how can i perform dump and restore inside the container?

One way to do this is to have CRIU installed in the container and run the container as `privileged`.

For example: https://gist.github.com/rst0git/eea73821ef927c04d49fe2f4ba035e02

**Comment by xiaochutan123l** [comment]
> btw can you tell me how can i perform dump and restore inside the container?
> 
> One way to do this is to have CRIU installed in the container and run the container as privileged.
> For example: https://gist.github.com/rst0git/eea73821ef927c04d49fe2f4ba035e02


Great! thanks for that.
