### ISSUE TITLE
Large memory dump aborted: [Error (compel/src/lib/infect.c:1352): BUG at compel/src/lib/infect.c:1352]

### ISSUE THREAD

**Issue by kevinrichardgreen** [checkpoint-restore/criu#766]
I'm trying to checkpoint a rather large memory job (500GB+) and I'm coming across the error in the title, which leads to an abort.

Ubuntu 18.04: 
`4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`criu --version` (installed via `apt`)
```Version: 3.6```

`criu check --all`
```Warn  (criu/cr-check.c:1029): CRIU built without CONFIG_COMPAT - can't C/R ia32
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

Dump command:
```criu dump -t 31941 -j -D /storage/1/kgreen/Fe_4 -v3 -o dump.log```

We have been able to successfully dump and restore using this program and combination of command arguments before, but with jobs of size about 100GB. The dump file for this attempt is attached at the bottom.

From perusing the dump file myself, it seems like the issue comes up when dumping the file descriptors (Note: I do not have a great understanding of kernel or criu). I would appreciate any insight into what could actually be going wrong here.

[dump.log](https://github.com/checkpoint-restore/criu/files/3510566/dump.log)

**Comment by 0x7f454c46** [comment]
It seems to be parasite_dump_pages_seized().
So it seems that rather than due to memory, it's about the number of VMAs:
```
unsigned long dump_pages_args_size(struct vm_area_list *vmas)
{
	/* In the worst case I need one iovec for each page */
	return sizeof(struct parasite_dump_pages_args) +
		vmas->nr * sizeof(struct parasite_vma_entry) +
		(vmas->nr_priv_pages + 1) * sizeof(struct iovec);
}
```
I remember @avagin already hit this for many mappings, but can't find the issue straight-away..
I guess we could go either way of:
- Dumping VMAs in a couple of iterations
- Allowing parasite to be bigger (or introducing dynamic "allocation" by ftruncating memfd)

Regardless of the chosen way, I believe we also have a separate issue - BUGON()s.
It might be a summer project or something, but we need to reduce the amount of BUG*().
I believe, we want to have fallbacks instead. We definitely need to make sure that the dumpee is cured and left in the same state as before something unexpected happened in CRIU.
I'll open a separate issue, so this one could be just about VMAs limit.

**Comment by avagin** [comment]
commit 07da7b0f427ddeb4dd9311e5d1e8680094bd8f7e
Date:   Fri Aug 10 17:53:01 2018 +0300

    compel -- Use unsigned long for arguments
    
    When checkpointing applications with really big memory slab
    (like in our vz7 test with 920G of memory) the int type get
    cutted, we should use long int instead, just like we do in
    other code pieces.
    
    Otherwise get
    
     | pie: 756: Daemon waits for command
     | (01.193097) Wait for ack 12 on daemon socket
     | (01.193112) Fetched ack: 12 12 0
     | (01.193164) 988065 fdinfo 0: pos:                0 flags:           100002/0
     | (01.193201) fdinfo: type: 0xb flags: 0100002/0 pos:        0 fd: 0
     | (01.193279) 988065 fdinfo 1: pos:                0 flags:           100002/0
     | (01.193307) fdinfo: type: 0xb flags: 0100002/0 pos:        0 fd: 1
     | (01.193341) 988065 fdinfo 2: pos:                0 flags:           100002/0
     | (01.193365) fdinfo: type: 0xb flags: 0100002/0 pos:        0 fd: 2
     | (01.193375) ----------------------------------------
     | (01.193405) Error (criu/parasite-syscall.c:243): BUG at criu/parasite-syscall.c:243
     | pie: 756: Error (criu/pie/parasite.c:676): Trimmed message received (1>

**Comment by avagin** [comment]
commit 787dd695b323e4b4ba3aa2349c39f58bcf0fcae7
Date:   Fri Aug 10 17:58:11 2018 +0300

    pagemap: Use ssize_t type in read_local_page
    
    Integer is too small for big memory slabs.

**Comment by avagin** [comment]
Cc: @cyrillos

**Comment by avagin** [comment]
We have a few fixes for big processes which have been commited after v3.6. Could you try to compile criu from the master branch and reproduce this issue?

**Comment by kevinrichardgreen** [comment]
Ok, I'll try master and let you know how that works.

**Comment by kevinrichardgreen** [comment]
Using master fixes the issue. I can checkpoint and restore the job.
