### ISSUE TITLE
Does criu support MPICH?

### ISSUE THREAD

**Issue by SkysunPrincess** [checkpoint-restore/criu#768]
I saw on this page（https://criu.org/Comparison_to_other_CR_projects） that CRIU does not support MPI, but the last time the page was modified is in 2015, so I want to know if it is supported now.
Thank you

**Comment by SkysunPrincess** [comment]
And --external unix[id]:path can be used or its also in plan?
Looking forward to your reply

**Comment by rst0git** [comment]
From [Evaluating Distributed MPI Checkpoint and Restore using Docker Containers and CRIU](https://github.com/checkpoint-restore/criu/files/3532947/2019_Evaluating_Distributed_Mpi_Checkpoint_And_Restore_Using_Docker_Containers_And_Criu.pdf):

> In this study, we investigate to which extent current container technology can pause or checkpoint an MPI program. We use the experimental Checkpoint/Restore feature of Docker based on CRIU and the NAS Parallel Benchmark. Our results show that Docker indeed can checkpoint and restore NPB benchmarks in many situations. This is surprising since the documentation for CRIU clearly states that it does not support distributed (parallel) checkpointing.

**Comment by adrianreber** [comment]
Six years ago CRIU support was added to Open MPI, but it has been removed from newer branches:

https://github.com/open-mpi/ompi/tree/v3.0.x/opal/mca/crs/criu

So it is not that CRIU does not support MPI, it is more that MPI does not implement checkpoint/restore using CRIU.

**Comment by planetA** [comment]
@rst0git The paper does not mention it, but I assume they relied on TCP for communication, not on Infiniband. Am I right?

**Comment by rst0git** [comment]
@planetA Infiniband is certainly not mentioned in the evaluation setup:

> All experiments were performed on nodes equipped with a single 4-core, 3.2 GHz Intel i5-3470 Ivy Bridge processor equipped with 8 GB of DDR3 RAM. All nodes ran CentOS 7.3 with kernel 4.10.2-1. The CPUpower governor was configured in performance mode and Intel turbo boost was turned off. This was done to ensure that no power saving or frequency scaling features would affect the experiments...

and I think you are right to assume that they relied on TCP for communication.
