### ISSUE TITLE
why pr_info(..) can not output before socket connected

### ISSUE THREAD

**Issue by sunny868** [checkpoint-restore/criu#782]
int  compel/plugins/std/infect.c 
int __used __parasite_entry parasite_service(unsigned int cmd, void *args)
{
	pr_info("Parasite cmd %d/%x process\n", cmd, cmd);
	if (cmd == PARASITE_CMD_INIT_DAEMON)
		return parasite_init_daemon(args);

	return parasite_trap_cmd(cmd, args);
}

pr_info("Parasite cmd %d/%x process\n", cmd, cmd);  can not output to console

**Comment by sunny868** [comment]
thanks for you timely reply . but I want to know why the pr_info() can not be called before the log file descriptor is set?
dumpee process console fd (stdout/stderr) is closed ?

**Comment by 0x7f454c46** [comment]
@sunny868 dumpee fds can point anywhere - CRIU shouldn't play with them (and it doesn't)

**Comment by sunny868** [comment]
"dumpee fds can point anywhere" ? why?

**Comment by sunny868** [comment]
now I am making arch MIPS support . so I try to write some str into console before socket be setted.
char* str = "hello world\n';
   __asm__(
	"li	v0,5001\n\t"      //sys_write syscall ID
	"li	a0,0\n\t"         //stdout fd
	"move	a1,%0\n\t"       // str 
	"li  a2,12\n\t"        //str length
	"syscall      \n\t"
	::"r"(str)
	:"v0","a0","a1","a2");

but ,there is nothing in console.

**Comment by sunny868** [comment]
now I am making arch MIPS support . so I try to write some str into console before socket be setted.

 char* str = "hello world\n';
__asm__(
"li v0,5001\n\t" //sys_write syscall ID
"li a0,0\n\t" //stdout fd
"move a1,%0\n\t" // str
"li a2,12\n\t" //str length
"syscall \n\t"
::"r"(str)
:"v0","a0","a1","a2");

but ,there is nothing in console.

**Comment by sunny868** [comment]
I have try to set logfd to STDOUT_FILENO. but nothing output in console.Dima is right, dumpee fds can point anywhere. I just want to the reason ,why dumpee fds have been changed to point to anywhere ?   dumper just use ptrace(..) to pause dumpee process,then place parasite code into some place (mmap) and go on the dumpee process. so I think parasite code running in dumpee process,then dumpee precess fds be not changed, parasite code also can use fds of dumpee. 
who can give a explanation. thanks very much!

**Comment by 0x7f454c46** [comment]
You likely don't want to print anything into dumpee fds. I.e, you're dumping grep process from:
`grep ':)' 2>/dev/null | wc -l`
If you write anything into stderr, it'll vaporize. If you write anything into stdout - it'll go into pipe.
On more extreme examples it could have been `/etc/passwd` :)
Of course, you can check apriori where is destination for fds, but there is no point - you want the output of parasite to go into logs, not on some random tty.
