### ISSUE TITLE
Error while dumping parent process "Can't dump half of stream unix connection"

### ISSUE THREAD

**Issue by EmadAlamoudi** [checkpoint-restore/criu#796]
Hi! I'm new to CRIU and I'm sorry if my question sounds easy, but I'm really struggling to solve this issue.  I would really appreciate any help. 

I'm using CRIU to dump a python process that is a parent for another process. I'm using the following command:
`sudo criu dump -t 3930 -D checkpoint/ -j -v4 -x --ext-unix-sk`

However, I  get the following error: 

```(00.781546) Obtaining task auvx ...
(00.781672) Dumping task cwd id 0x125 root id 0x126
(00.781789) Dumping file-locks
(00.781795) 
(00.781798) Dumping pstree (pid: 3930)
(00.781803) ----------------------------------------
(00.781808) Process: 3930(3930)
(00.781841) Process: 3946(3946)
(00.781846) ----------------------------------------
(00.781879) cg: All tasks in criu's cgroups. Nothing to dump.
(00.781883) sk unix: Dumping external sockets
(00.781938) sk unix: 	Dumping extern: ino 0xdedc7 peer_ino 0xdf038 family    1 type    1 state  1 name 
(00.781948) sk unix: 	Dumped extern: id 0x128 ino 0xdedc7 peer 0 type 2 state 10 name 21 bytes
(00.781956) sk unix: 	Ext stream not supported: ino 0xdedc7 peer_ino 0xdf038 family    1 type    1 state  1 name 
(00.781962) Error (criu/sk-unix.c:725): sk unix: Can't dump half of stream unix connection.
(00.790899) Unlock network
(00.790915) Unfreezing tasks into 1
(00.790918) 	Unseizing 3930 into 1
(00.790925) 	Unseizing 3946 into 1
(00.790934) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
When looking at the process tree, it looks like this:

``` PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 6535 root       20   0  482M 53404 26044 S  0.0  0.3  0:01.32 ├─ python3 /usr/lib/software-properties/software-properties-dbus
 6568 root       20   0  482M 53404 26044 S  0.0  0.3  0:00.00 │  ├─ python3 /usr/lib/software-properties/software-properties-dbus
 6567 root       20   0  482M 53404 26044 S  0.0  0.3  0:00.95 │  └─ python3 /usr/lib/software-properties/software-properties-dbus
 3930 eeee       20   0 1011M  220M 88620 S  0.6  1.4  0:03.22 │  │  │  └─ python3 pppp.py
 3946 eeee       20   0 40652 11328  5740 S  0.0  0.1  0:00.04 │  │  │     └─ /usr/bin/python3 -c from sss.eee import main;main(8)
 1125 root       20   0  189M 19936 11992 S  0.0  0.1  0:00.08 ├─ /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
 1182 root       20   0  189M 19936 11992 S  0.0  0.1  0:00.00 │  └─ /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
  979 root       20   0  173M 17416  9452 S  0.0  0.1  0:00.10 ├─ /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
 1197 root       20   0  173M 17416  9452 S  0.0  0.1  0:00.00 │  └─ /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
```

before using the -x flag I was having this error:

```
(00.393737) cg: Writing CG image
(00.393850) sk unix: Dumping external sockets
(00.393911) sk unix: 	Dumping extern: ino 0x26dbb peer_ino 0x271a6 family    1 type    1 state  1 name /var/run/dbus/system_bus_socket
(00.393944) sk unix: 	Dumped extern: id 0x97 ino 0x26dbb peer 0 type 2 state 10 name 32 bytes
(00.393950) sk unix: 	Ext stream not supported: ino 0x26dbb peer_ino 0x271a6 family    1 type    1 state  1 name /var/run/dbus/system_bus_socket
(00.393975) Error (criu/sk-unix.c:725): sk unix: Can't dump half of stream unix connection.
(00.394535) Unlock network
(00.394626) Unfreezing tasks into 1
(00.394633) 	Unseizing 6535 into 1
(00.394693) Error (criu/cr-dump.c:1709): Dumping FAILED.
```
I  have looked into https://criu.org/External_UNIX_socket and tried multiple `--external unix[id]` but without success. Any suggestions?

Thanks in advance,

**Comment by up0617** [comment]
Hi, I got this Issue. 

In my Case, I run a Process with
```
cvlc --loop ../SampleVideo_1280x720_20mb.mp4 --sout "udp://ip:port"
```
than checkpoint with 
```
criu dump -v4 -t $Target--shell-job -D images --ext-unix-sk
```
and got error
```
(00.103730) unix: Dumping external sockets
(00.103740) unix: 	Dumping extern: ino 319108 peer_ino 320165 family    1 type    1 state  1 name /run/user/1000/pulse/native
(00.103746) unix: 	Dumped extern: id 0xee ino 319108 peer 0 type 2 state 10 name 28 bytes
(00.103750) unix: 	Ext stream not supported: ino 319108 peer_ino 320165 family    1 type    1 state  1 name /run/user/1000/pulse/native
(00.103753) Error (criu/sk-unix.c:815): unix: Can't dump half of stream unix connection.
```
So, I get another harf by
```
lsof +E -aUc vlc
#result
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
pulseaudi  1884 damon   23u  unix 0xffff9204e032e400      0t0 319108 /run/user/1000/pulse/native type=STREAM ->INO=320165 12536,vlc,6u
vlc       12536  root    6u  unix 0xffff9204e0329c00      0t0 320165 type=STREAM ->INO=319108 1884,pulseaudi,23u
```
Then I can see NODE 320165 and 319108  linked(?)
Also Above Dump log shows "Dumping extern: ino 319108 peer_ino 320165". 

So I ran below cmd and it succeeds.
```
criu dump -v4 -t 12536 --shell-job -D images --ext-unix-sk --external unix[320165]
```

**Comment by Ghw2066** [comment]
> Hi, I got this Issue.
> 
> In my Case, I run a Process with
> 
> ```
> cvlc --loop ../SampleVideo_1280x720_20mb.mp4 --sout "udp://ip:port"
> ```
> 
> than checkpoint with
> 
> ```
> criu dump -v4 -t $Target --shell-job -D images --ext-unix-sk
> ```
> 
> and got error
> 
> ```
> (00.103730) unix: Dumping external sockets
> (00.103740) unix: 	Dumping extern: ino 319108 peer_ino 320165 family    1 type    1 state  1 name /run/user/1000/pulse/native
> (00.103746) unix: 	Dumped extern: id 0xee ino 319108 peer 0 type 2 state 10 name 28 bytes
> (00.103750) unix: 	Ext stream not supported: ino 319108 peer_ino 320165 family    1 type    1 state  1 name /run/user/1000/pulse/native
> (00.103753) Error (criu/sk-unix.c:815): unix: Can't dump half of stream unix connection.
> ```
> 
> So, I get another harf by
> 
> ```
> lsof +E -aUc vlc
> #result
> COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
> pulseaudi  1884 damon   23u  unix 0xffff9204e032e400      0t0 319108 /run/user/1000/pulse/native type=STREAM ->INO=320165 12536,vlc,6u
> vlc       12536  root    6u  unix 0xffff9204e0329c00      0t0 320165 type=STREAM ->INO=319108 1884,pulseaudi,23u
> ```
> 
> Then I can see NODE 320165 and 319108 linked(?)
> Also Above Dump log shows "Dumping extern: ino 319108 peer_ino 320165".
> 
> So I ran below cmd and it succeeds.
> 
> ```
> criu dump -v4 -t 12536 --shell-job -D images --ext-unix-sk --external unix[320165]
> ```

Thanks for your solution! This solved my problem when I tried to dump sshd service and its children process. But when I try to restore it, criu restore failed and what I expect to see is ssh connection can be resumed.
restore failed message:
```
Error (criu/sk-inet.c:992): inet: Can't bind inet socket (id 39): Address already in use
(00.021894)   4225: Parsed ffff87f68000-ffff88251000 vma
(00.021916)   4225: Parsed ffff87f68000-ffff882a2000 vma
(00.021919)   4225: Parsed ffff87f68000-ffff882be000 vma
(00.021921)   1714: Parsed aaaac4cfb000-aaaac4e2a000 vma
(00.021922)   4225: Parsed ffff87f68000-ffff882c2000 vma
(00.021924)   5376: Error (criu/files.c:1196): Unable to open fd=4 id=0x27
```
The command I used is ：
```
criu restore -v4 -o restore.log --pidfile restore.pid --ext-unix-sk --tcp-established -j -d --inherit-fd fd[4]:socket:[2960837]
```
Could u pls give a hint that how to correctly restore process with unix socket?

**Comment by up0617** [comment]
can you run 
```
sudo lsof -i -P -n | grep LISTEN
```
than may the sshd service come up with new pid. 
I don't know how sshd works but it may be automatically restart when suddenly closed.
