### ISSUE TITLE
in-place sync instead of --prev-images-dir

### ISSUE THREAD

**Issue by riaqn** [checkpoint-restore/criu#797]
Currently we have incremental dump with `--prev-images-dir`, which could become very slow as the levels stack up (consider if I perform a incremental dump for the same application every hour, and in a month there will be 720 symlinks pointing to the previous ones).

Instead I suggest we get something like in-place sync. That should allow me to repeatedly dump into the same directory, keeping the images up-to-date with the applications. Together with `--track-mem` it could be made very efficient.

**Comment by rst0git** [comment]
@riaqn would *in-place sync* be more efficient than just running `criu dump --leave-running` ?

**Comment by riaqn** [comment]
@rst0git Could you elaborate?

**Comment by rst0git** [comment]
Instead of performing incremental dump you can do a full dump every hour and keep only the latest checkpoint.

**Comment by riaqn** [comment]
I guess my point is that I hope to use `--track-mem` to accelerate the dumping process, such that each time, only the pages that are changed since last dump are dumped.
