### ISSUE TITLE
Impossible to restore any process due to PID increment rates.

### ISSUE THREAD

**Issue by pthfdr-42** [checkpoint-restore/criu#807]
How to reproduce:
1. Dump a process with lots of RAM usage and many threads (like ZPAQ).
2. Reboot.
3. When trying to restore, it fails with "Pid $PID do not match expected $PID".

The `unshare` method does not apply since it does not cover shell jobs.
The problem is that many thing in the OS creates new processes frequently and take up the PID desired.
They create new processes every few seconds, and they are too important (or simply impossible) to kill.
For example, "systemd-udevd" now frequently ends and spawns child processes after an update.
BTRFS also frequently creates kernel threads.
Even worse, CRIU now set the starting point of new PIDs to the restored process' PID, so no matter how many times you try, it will always fail because the next few PIDs are quickly taken.
I think that a workaround is to create empty threads in advance so the PIDs won't be taken during restoration, but I am not sure.

This is a fundamental problem. You tried to restore processes to their original PIDs, which is impossible in reality.

**Comment by rst0git** [comment]
@adrianreber presented a solution for this problem in [LPC this year](https://linuxplumbersconf.org/event/4/contributions/472/attachments/224/397/2019-criu-and-the-pid-dance.pdf).

**Comment by pthfdr-42** [comment]
...which means that you have to patch and recompile the kernel, and once you do, more things will break.
Seriously, is it not possible to restore processes *without* using their original PIDs?

**Comment by rst0git** [comment]
> The unshare method does not apply since it does not cover shell jobs.

@pthfdr-42 have you tried the [`criu-ns`](https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/criu-ns) script?
```
# ./criu-ns restore --shell-job ...
```

**Comment by pthfdr-42** [comment]
The wiki says that shell jobs are not supported.

**Comment by rst0git** [comment]
Thank you for pointing it out. I just updated the [wiki page](https://criu.org/CR_in_namespace#Limitations).

**Comment by adrianreber** [comment]
> Seriously, is it not possible to restore processes _without_ using their original PIDs?

No. Not keeping the PID could break restored processes in multiple ways in regards to parent child relations. But restoring into a new PID namespace should be a solution.

**Comment by pthfdr-42** [comment]
...which will still have limitations.
As I have said in the first post, is it possible to create dummy processes *before* restoration? I found that the system usually create kernel processes *during* restoration (which may be very long).

**Comment by pthfdr-42** [comment]
It looks like that `criu-ns` fails when dumping the process again. It fails with "Error (criu/cr-dump.c:1327): A session leader of PID(PID) is outside of its PID namespace".
