### ISSUE TITLE
Criu APIs (Error reported in dump.log file)

### ISSUE THREAD

**Issue by IjazAhmed** [checkpoint-restore/criu#808]
I am a novice user of criu APIs, and indeed looking for a detailed help. I am writing my experience in details, that might help the other novice users in future.

I am using Ubuntu "Linux 4.15.0-64-generic x86_64" kernal. When I executed the shell script (run.sh) given at url https://github.com/xemul/criu/blob/master/test/others/libcriu/run.sh. I got an error "error while loading shared libraries: libcriu.so.2". The main reason for this error was that the shell script (run.sh) create a symbolic link (ln) with the name libcriu.so.1, however the criu APIs used the link with name "libcriu.so.2". I changed the shell script line "ln -s ../../../../criu/lib/c/libcriu.so libcriu.so.1" with "ln -s ../../../../criu/lib/c/libcriu.so libcriu.so.2", and IT WORKS FINE FOR ME.

However, now I face another problem when I run the script. Lets, talk about only one program "test_self.c", given at https://github.com/xemul/criu/blob/master/test/others/libcriu/test_self.c
When the program runs, I get the following errors. 

"(00.000048) Version: 3.12 (gitid v3.12-175-g3953b333)
(00.000079) Running on cb19ea91e530 Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64
(00.000091) File /run/criu.kdat does not exist
(00.000123) sockets: Probing sock diag modules
(00.000198) sockets: Done probing
(00.005449) Error (criu/util.c:632): exited, status=3
(00.005547) Pagemap is fully functional
(00.005624) Found anon-shmem device at 5
(00.005648) Reset 255's dirty tracking
(00.005728)  ... done
(00.005788) Dirty track supported on kernel
(00.005882) Found task size of 7ffffffff000
(00.011271) Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
(00.083991) Restoring netdev veth idx 10
(00.084615) Dumping netns links
(00.084690)     LD: Got link 1, type 772
(00.084699)     LD: Got link 10, type 1
(00.085257) Error (criu/uffd.c:264): uffd: Lazy pages are not available: Operation not permitted
(00.085278) Error (criu/kerndat.c:927): Lazy pages are not available
(00.085318) Found mmap_min_addr 0x10000
(00.085348) files stat: fs/file-max 13143392, fs/nr_open 1048576".

There are three main errors, that I am facing.
(a) File /run/criu.kdat does not exist
(b) Error (criu/tun.c:85): tun: Unable to create tun: No such file or directory
(c) Error (criu/uffd.c:264): uffd: Lazy pages are not available: Operation not permitted

NOTE: I am using the docker image with full permission by using the command 
"sudo docker run --rm --cap-add=ALL -it".

It would be kind of you, if you may please educate me to fix these errors.

Regards
Ijaz

**Comment by rst0git** [comment]
The libcriu failure was resolved in https://github.com/checkpoint-restore/criu/pull/783

You need to add `--privileged` option in your `docker run` command.

**Comment by IjazAhmed** [comment]
Thank you for advice. 
I have already added the privileged option in the docker run command. Please have a look at the command "sudo docker run --rm --cap-add=ALL -it mydocker::2019-09-24", or I am missing something in the command.
I am equally new to docker technology as well. :)

**Comment by IjazAhmed** [comment]
I tried the run command with --privileged, and it worked. The command is 
"sudo docker run --rm --privileged=true -it mydocker::2019-09-24".

The issue is SOLVED.
Thanks.
