### ISSUE TITLE
Understanding Dump & Restore Process of CRIU

### ISSUE THREAD

**Issue by IjazAhmed** [checkpoint-restore/criu#810]
![Criu-memory-wflow](https://user-images.githubusercontent.com/1769347/65934276-95e6f000-e44f-11e9-8337-165f480c95aa.png)

The Restore process of the criu suggests that it uses the .img files created by Dump process. Now, suppose I want to modify the value of a specific register before restoring the process. So
 
(a) does that mean I have to modify the .img file created by dump process - so that while restoring the process criu may use the modified .img file to reflect the modified state of the dumped process. 

(b) If point (a) holds, then there are many .img files, so I do not which one may contain the specific information about registers. Can you guide me about some documentation that may provide details about the .img files structure created by Dump() function.

(c) and if point (a) does not hold, then what are the options available to modify the value of a register after dumping the process.

Regards
Ijaz

**Comment by adrianreber** [comment]
@IjazAhmed You can use crit (https://criu.org/CRIT) to decode image files, change them and encode them again. Documentation for the image files is best taken from git. For x86_64 the register image file definition is in https://github.com/checkpoint-restore/criu/blob/criu-dev/images/core-x86.proto

**Comment by IjazAhmed** [comment]
@adrianreber: Thank you, the crit tool is working amazingly. :)
