### ISSUE TITLE
Two Questions regarding .img files (crui & crit).

### ISSUE THREAD

**Issue by IjazAhmed** [checkpoint-restore/criu#812]
**First Questions:**
The first question is related with the crit https://criu.org/CRIT utility. The crit command 
"./crit decode -i abc.img --pretty" successfully decodes all of the attached .img files except image "pages-1.img". 

<img width="622" alt="Screen Shot 2019-10-02 at 6 22 30 PM" src="https://user-images.githubusercontent.com/1769347/66033649-a6c45e00-e542-11e9-886e-2394a1007712.png">

What is the reason for this? When I executed command 
"./crit decode -i  pages-1.img --pretty". I got the following error "unknown magic" (error snapshot attached).

<img width="466" alt="Screen Shot 2019-10-02 at 6 34 06 PM" src="https://user-images.githubusercontent.com/1769347/66033937-3cf88400-e543-11e9-9d7c-09fc592a3007.png">

How can I decode the "pages-1.img" file?

**Question No:2**
Before using the criu dump() function, I have a code like this
int x=10;
criu_dump();
Now which .img file contain information about the variable x, and its value. I suppose, it is pages-1.img. Kindly guide. 

I am really thankful to the august community of criu who is already helping me a lot to understand the criu.

Regards
Ijaz

**Comment by adrianreber** [comment]
> How can I decode the "pages-1.img" file?

Not at all. That file just contains the memory pages. Its content is described using other image files. I think pagemap or mm is describing the content of pages-*.img. Something like "this pages-*.img offset belongs at following memory address of the restored process".

> Now which .img file contain information about the variable x, and its value. I suppose, it is pages-1.img. Kindly guide.

That could be either in a register or in the memory. Depending on how the compiler optimizes it might also be a constant and somewhere else. Easier example might be to malloc() a page and write a pattern to that malloc'd page. This is something you should see in pages-*.img.

**Comment by IjazAhmed** [comment]
I decoded the mm-539.img and found the below information.

<img width="385" alt="Screen Shot 2019-10-03 at 2 23 11 AM" src="https://user-images.githubusercontent.com/1769347/66066633-d98f4600-e584-11e9-8f65-17e294df468e.png">

 Do you think that I might get the value of program variable in the region 
"mm_start_data": "0x562ea37b4d18", 
 "mm_end_data": "0x562ea37b5010",

May be I will write a c program to get information from this region, and then modify the region according to my requirements. What is your opinion about it?

Regards
Ijaz

**Comment by rst0git** [comment]
Hello Ijaz,

When CRIU performs dump or pre-dump it first opens both `pagemap` and `pages`, then writes a set of protocol buffer entries in `pagemap`. Each entry contains an address (_`vaddr`_) and a number of pages (_`nr_pages`_). The actual content of the memory pages represented by the pagemap entry is written (without encoding) into the `pages` file.

Therefore, you can print the address of your variable, decode the `pagemap` file, compute the location of the pointer inside the `pages` file and modify it.

Or, you can use a string instead of an integer, and  `sed` will do the modification for you.

For instance:

```C
#include <stdio.h>

void main(void)
{
        char s[] = "foo";
        printf("%s\n", s);
        getchar();
        printf("%s\n", s);
}
```

```sh
$ gcc test.c -o test && ./test
foo
Killed
```

```sh
$ criu dump -t `pidof test` -j
$ mv pages-1.img pages-1.img.back
$ sed "s/foo/bar/g" pages-1.img.back > pages-1.img   # Replace "foo" with "bar"
$ criu restore -j

bar
```
