### ISSUE TITLE
Docker checkpoint: ip6tables-restore failed

### ISSUE THREAD

**Issue by planetA** [checkpoint-restore/criu#813]
Hello,

I'm trying to make a checkpoint of a docker container using `docker checkpoint`.

Here is how I run the container:

```
docker run --network none --name test  --rm -it alpine \
  sh -c 'while true ; do echo Hi ; sleep 5 ; done'
```

And here is how I try to create a checkpoint:

```
docker checkpoint create --checkpoint-dir $HOME/dump test rdma-checkpoint
```

But I get an error message:

> Error response from daemon: Cannot checkpoint container test: runc did not terminate sucessfully: criu failed: type NOTIFY errno 0 path= /run/containerd/io.containerd.runtime.v1.linux/moby/019130b51766df33f151a882fd760835f2f967d633d7bf2bb8e4667afd62eacb/criu-dump.log: unknown

Checking the logs points to erroneous following part ([full log](https://gist.github.com/planetA/fe91bee44f345e8683471629a7c05aec#file-criu-dump-log))

> (00.256953) Running network-lock scripts
> (00.256970)     RPC 
> ip6tables-restore v1.8.2 (nf_tables):  
> line 1: CHAIN_ADD failed (No such file or directory): chain INPUT 
> line 1: CHAIN_ADD failed (No such file or directory): chain FORWARD 
> line 1: CHAIN_ADD failed (No such file or directory): chain OUTPUT 
> line 2: CHAIN_USER_ADD failed (No such file or directory): chain CRIU 
> line 3: RULE_INSERT failed (No such file or directory): rule in chain INPUT 
> line 4: RULE_INSERT failed (No such file or directory): rule in chain OUTPUT 
> line 5: RULE_APPEND failed (No such file or directory): rule in chain CRIU 
> line 6: RULE_APPEND failed (No such file or directory): rule in chain CRIU 
> (00.315971) Error (criu/util.c:632): exited, status=4 
> (00.316056) Error (criu/net.c:2645): Locking network failed: iptables-restore returned -1. This may be connected to disabled CONFIG_NETFILTER_XT_MARK kernel build config option.
> (00.316156) Unlock network
> (00.316177) Running network-unlock scripts
> (00.316194)     RPC
> ip6tables-restore: line 3 failed 
> (00.380101) Error (criu/util.c:632): exited, status=1
> (00.380292) Unfreezing tasks into 1
> (00.380315)     Unseizing 6735 into 1
> (00.382673)     Unseizing 8218 into 1
> (00.382758) Error (criu/cr-dump.c:1752): Dumping FAILED.     

I also tried to change default parameters:

```
$ cat /etc/criu/default.conf 
tcp-established
shell-job
verbosity=4
```

The config file seems to be read, but verbosity parameter does not change the log content.

I use HEAD of criu-dev branch (1f4d583b)

System info ([full kernel config](https://gist.github.com/planetA/fe91bee44f345e8683471629a7c05aec#file-config-5-2-0)):

```
$ cat /boot/config-$(uname -r) | grep CONFIG_NETFILTER_XT_MARK
CONFIG_NETFILTER_XT_MARK=m
$ lsmod | awk '{print $1 }' | grep ip6table_filter
ip6table_filter
$ uname -a
Linux debian 5.2.0+ #32 SMP Thu Aug 15 10:01:24 EDT 2019 x86_64 GNU/Linux
$ docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:29 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:28:05 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
$ sudo criu --version
Version: 3.12
GitID: v3.12-294-gc21f941c8
$ sudo criu check --all 2>&1 | tail -n 1
(00.042233) Looks good
```

I would be grateful, if you help me to find the root cause of the problem.

**Comment by rst0git** [comment]
@planetA I was not able to reproduce the issue on Fedora 30 with `5.2.15-200.fc30.x86_64` kernel and Docker version 19.03.2, build 6a30dfc. One difference I noticed was:
```
$ iptables --version
iptables v1.8.2 (legacy)
```

**Comment by adrianreber** [comment]
@rst0git On RHEL8 I have no problems with nf_tables based iptables, but I think there are some upstream patches necessary to make  nf_tables iptables work.

@planetA You should try iptables 1.8.3 (or legacy based iptables).

**Comment by planetA** [comment]
@rst0git I have the same (I used update-alternatives):

```
$ sudo iptables --version
iptables v1.8.2 (legacy)
```

**Comment by rst0git** [comment]
```
$ cat /etc/criu/default.conf 
tcp-established
shell-job
verbosity=4
```
FYI you need to use `/etc/criu/runc.conf` to change the default parameters.
https://www.criu.org/Docker#Passing_additional_options

**Comment by planetA** [comment]
I forgot to mention that the whole setup runs in a VM. But I don't think it is important.

**Comment by planetA** [comment]
I found a "fix" after I changed CONFIG_NETFILTER_XT_MARK from "m" to "y" in the config (and other corresponding options), checkpoint worked.

**Comment by avagin** [comment]
Why is this module not autoloaded? I mean usually when we run iptables, it loads all required modules.

**Comment by planetA** [comment]
I don't know why it was not autoloaded, but I manually loaded the module anyway. Can docker do some magic that unloads the module during restore?
