### ISSUE TITLE
build error in MacBook

### ISSUE THREAD

**Issue by sunny868** [checkpoint-restore/criu#818]
now I make criu in MacBook ,then have some errors like this:

Note: Building without ia32 C/R, missed ia32 support in gcc
      That may be related to missing gcc-multilib in your
      distribution or you may have Debian with buggy toolchain
      (issue https://github.com/xemul/criu/issues/315)
  GEN      .gitid
  GEN      criu/include/version.h
grep: images/google/protobuf/descriptor.proto: No such file or directory
  DEP      images/macvlan.pb-c.d
In file included from images/macvlan.pb-c.c:9:0:
images/macvlan.pb-c.h:7:35: fatal error: protobuf-c/protobuf-c.h: No such file or directory
 #include <protobuf-c/protobuf-c.h>

I have brew install protobuf-c and gcc version is 6.5.0

**Comment by adrianreber** [comment]
Do you have the protobuf-c compiler installed. It is called protoc-c on my system.

**Comment by avagin** [comment]
CRIU doesn't support the MacOS. If you want to use criu for docker container, you can build it in a container too. Here are examples of dockerfile-s: https://github.com/checkpoint-restore/criu/tree/criu-dev/scripts/build
