### ISSUE TITLE
Error to dump software

### ISSUE THREAD

**Issue by hildogjr** [checkpoint-restore/criu#821]
I am built and installed CRIU into a Ubuntu 16.04 machine. I trying to dump a process like the video tutorial and I am getting a "Error (compel/src/lib/infect.c:342): Unable to detach from 18596: No such process".
The full log is attached.
[CRIU-error-log.txt](https://github.com/checkpoint-restore/criu/files/3725559/CRIU-error-log.txt)

**Comment by adrianreber** [comment]
Lot's of operations not permitted. Are you running in a container?

**Comment by hildogjr** [comment]
Yes. This test is in a virtual(box) machine that I use before some some tests in the host.
Are those error due the virtualization restriction?

**Comment by avagin** [comment]
> Are those error due the virtualization restriction?

No, they are not. In most cases, criu has to be run with root privileges.

**Comment by hildogjr** [comment]
I tried with `sudo` now and got "Unseizing 2412 into 1".
[CRIU-error-log-sudo.txt](https://github.com/checkpoint-restore/criu/files/3726505/CRIU-error-log-sudo.txt)

With `sudo` I was able to reproduce the "C print example". Let me now if additional debug may help.

**Comment by avagin** [comment]
You need to look at the first error in a log file
```
(00.516118) Error (criu/cr-dump.c:430): Task 2412 with SysVIPC shmem map @7efd9e54f000 doesn't live in IPC ns
```

**Comment by avagin** [comment]
Could you describe what are you dumping?

**Comment by rst0git** [comment]
> Dumping path for 52 fd via self 57 [/home/h/.wine/drive_c/users/h/Local Settings/Temporary Internet Files/Content.IE5/index.dat]

I assume that you are trying to checkpoint a GUI application running with wine. Please read more about this use case in https://criu.org/VNC

**Comment by hildogjr** [comment]
Exactly. It is a GUI application running using Wine.
I will try to reproduce second the VNC example and after report here.
