### ISSUE TITLE
service: reconsider default permissions for an unix socket.

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/criu#822]
Currently the `service` command of CRIU creates a Unix socket that enables *any* user to checkpoint/restore *any* process. This is mainly as a consequence of https://github.com/checkpoint-restore/criu/commit/6c22bfe2 and, in general, is not very good idea in terms of security.
```C
/* change service socket permissions, so anyone can connect to it */
if (chmod(server_addr.sun_path, 0666)) {
	pr_perror("Can't change permissions of the service socket");
	goto err;
}
```
Simply changing `0666` to `0600` will address the security concern, however, does it make sense to use `criu service` if only privileged users would be allowed to connect?

**Comment by xemul** [comment]
Well, the permissions on the socket can be 666, if the root needs to hide the socket from someone it can tune the directory (with socket) access rights.

The plan with the service was to allow non-root checkpoint and restore. So far the non-root _dump_ works on most of the crucial stuff (there's even a test in zdtm/ that checks what can be dumped without root privileges). The non-root restore still doesn't work, there are two obstacles: fork_with_pid needs CAP_SYS_ADMIN (maybe in userns) and prctl SET_MM_EXE does need it too. So the service was to address this issue, but apparently doesn't work well enough.

**Comment by rst0git** [comment]
> So the service was to address this issue, but apparently doesn't work well enough.

I looked into the git history (https://github.com/checkpoint-restore/criu/commit/2e15e4da, https://github.com/checkpoint-restore/criu/commit/91389f87, https://github.com/checkpoint-restore/criu/commit/547d9bf9) and the description in [Self dump](https://criu.org/Self_dump) and [RPC](https://criu.org/RPC) pages but I could not find out why this approach didn't work?

**Comment by xemul** [comment]
It technically did, but had several issues. The non-security-related issue is -- restored tree becomes the child of the service process (or reparented to init) while it's highly likely that restorer wants to have the restored subtree as its child.

The rest are all about security.
- It's very inflexible in configuring who may use the service.
- If you ask service to dump some process, then it will dump it for you even if you're not allowed to ptrace/kill it.
- If you ask service to write logs into some file, then this file is just open()-ed for writing, thus if you specify some root-only (or other restricted) file, then criu service will just hack the system for you :)

**Comment by rst0git** [comment]
It seems like feature is used by CloudLinux:
https://docs.cloudlinux.com/cloudlinux_os_components/#lsapi-criu-socket-path
https://www.cloudlinux.com/cloudlinux-os-blog/entry/beta-criu-lve-updated-1-6
