### ISSUE TITLE
Docker - restore ignores the previous state

### ISSUE THREAD

**Issue by sergejbut** [checkpoint-restore/criu#823]
Hey,

I followed Docker checkpoint/restore (https://criu.org/Docker), and after restore the container started counting from 0 and not from the expected, checkpointed state.

Is it a problem with my setup, some version, or ...?

**uname -a**
Linux vm1-pc 5.2.21-1-MANJARO #1 SMP PREEMPT Sat Oct 12 11:09:56 UTC 2019 x86_64 GNU/Linux

**criu check**
Error (criu/uffd.c:263): uffd: Lazy pages are not available: Function not implemented
Looks good.

**docker version**
Client:
 Version:           19.03.3-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        a872fc2f86
 Built:             Wed Oct  9 02:28:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.3-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       a872fc2f86
  Built:            Wed Oct  9 02:28:23 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by avagin** [comment]
I don't see any problem with our travis test:
https://travis-ci.org/avagin/criu/jobs/599005396
https://github.com/checkpoint-restore/criu/blob/criu-dev/scripts/travis/docker-test.sh

Could you compare your commands with commands that are executed in this test?

**Comment by sergejbut** [comment]
Tried today with Ubuntu 18.04.1 -> works
With Manjaro -> don't

I will just use Ubuntu. Thx for the quick response
