### ISSUE TITLE
Docker - No restore.log file after unsuccessful restore (+questions for my thesis)

### ISSUE THREAD

**Issue by sergejbut** [checkpoint-restore/criu#826]
I try to live migrate a mysql container from host A to Host B. (simple example with the counter works perfectly)

**docker** version 19.03.4, build 9013bf583a
**criu**: Installed: 3.13-2ppa1.18.04
18.04.1-Ubuntu

Steps:

1) A: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:8
2) B: docker create --name some-mysql mysql:8
3) A: docker checkpoint create some-mysql check1
3) transfer check1 to host B
4) B: docker start --checkpoint check1 some-mysql
  -> Error response from daemon: OCI runtime restore failed: criu failed: type NOTIFY errno 0
log file: /var/lib/containerd/io.containerd.runtime.v1.linux/moby/09d57d8d4a4df4ee7753339a9db8023107d5f7ae8e2d66e5ed866155f05b9ea2/restore.log: unknown

But there is no restore.log under the given directory and I don't know why it doesn't work :/

**_For my thesis_**:
I try out some more complex examples to live migrate a docker container
- a database
- a backend with many requests
- maybe video streaming

Is it possible for 1 person with little experience in linux to do this stuff, or is it too much and I should pick another topic?

**Comment by adrianreber** [comment]
@sergejbut It seems you are not migrating the file-system of your mysql container. You could try Podman (https://criu.org/Podman) which includes the file-system changes in its checkpoint.

The database is making changes to the file-system of the container and if you do not migrate that also the migration can fail. Try it with Podman and let us know if that works better.



> Is it possible for 1 person with little experience in linux to do this stuff, or is it too much and I should pick another topic?

That has all been done before and should be doable.

**Comment by rst0git** [comment]
@sergejbut How do you `transfer check1 to host B`?

**Comment by sergejbut** [comment]
> @sergejbut It seems you are not migrating the file-system of your mysql container. You could try Podman (https://criu.org/Podman) which includes the file-system changes in its checkpoint.

**podman ps -a**
CONTAINER ID  IMAGE                      COMMAND  CREATED         STATUS             PORTS  NAMES
92ef7cd16356  docker.io/library/mysql:8  mysqld   20 minutes ago  Up 20 minutes ago         some-mysql

**sudo podman container checkpoint 92ef7cd16356** 
Error: no container with name or ID 92ef7cd16356 found: no such container
-> I tried with the long ID and with container name. Same result

So with Docker it's not possible to live migrate the database?

**Comment by adrianreber** [comment]
Are you running the container as root or as non-root? To migrate podman containers you have to start the container as root and checkpoint it as root. As your `podman ps` command is not prefixed by `sudo` it seems you are running the databases rootless as your local user. If you want to migrate a container you have start it as root.

> So with Docker it's not possible to live migrate the database?

If you migrate the file-system it is possible.

**Comment by sergejbut** [comment]
@rst0git I create a tar a send it with scp to other host

sudo tar -zcf /tmp/ -C /var/lib/docker/containers/${container_id}/checkpoints/ ${checkpoint_name}/
ssh -t ${migration_host} "sudo tar -zxf /tmp/ -C /var/lib/docker/containers/${remote_container_id}/checkpoints/"

**Comment by sergejbut** [comment]
> If you migrate the file-system it is possible. Podman does it all for you automatically.
So `docker commit` and then on other host create from this new image? Is it because I pass environment variables to the container and thats why it can't be restored?

> Are you running the container as root or as non-root?
Oh. Tried with root: Cannot export checkpoints of containers with named volumes or dependencies
Without the export flag it works.

**Comment by adrianreber** [comment]
@sergejbut Following works for me:

```
$ mkdir /tmp/data
$ podman  run --name some-mysql -v /tmp/data:/var/lib/mysql:z -e MYSQL_ROOT_PASSWORD=root -d mysql:8
$ podman container checkpoint -l -e /tmp/cp.tar.gz
$ podman rm -fa
$ podman container restore -i /tmp/cp.tar.gz
```

To migrate this container you would need to copy `/tmp/data` to the destination system and `/tmp/cp.tar.gz`.

**Comment by sergejbut** [comment]
@adrianreber Thank you very much Adrian, this example really helped me. Did not tested it with podman, but I understood, that the mounted directories should also be transferred to destination. Adapted it to Docker -> successfully migrated a MySQL container, finally! :) Later I will test the same things with podman. 

Before your example I thought, that the data that MySQL produces is IN the container and gets checkpointed with the help of CRIU. But in reality the data is on the host system (_docker inspect <container_id>_, and look for the _Mounts_ block). Even if I don't specify a volume, it has a directory on the host system, where it stores the data. Damn, that was not clear to me. I hope this will help other people to understand it and not to struggle like I did.

But if I transfer the data on my own and so on, create and start the container exact the same like it was on the source. For this specific example with DB, the migration would work without CRIU, or? Maybe I miss something...

**Comment by rst0git** [comment]
> But if I transfer the data on my own and so on, create and start the container exact the same like it was on the source. For this specific example with DB, the migration would work without CRIU, or? Maybe I miss something...

CRIU is checkpointing and resuming a group of processes (container), which enables *live* migration and allows to preserve the state of long-running computational tasks. The start-up time of workloads with small amount of in-memory state could be negligible, and therefore restarting them on another host would not introduce a significant down-time or overhead.
