### ISSUE TITLE
how to build criu  in MacBook?

### ISSUE THREAD

**Issue by sunny868** [checkpoint-restore/criu#836]
now.I have git clone criu code to my MacBook.then do make ,there are many error.I not know to build in MacBook. 

it is ok when I make in ubuntu .

**Comment by adrianreber** [comment]
CRIU is Linux only. It cannot work natively on a MacBook.

**Comment by avagin** [comment]
You can build it in a Docker container. Here are examples of dockerfile-s: https://github.com/checkpoint-restore/criu/tree/criu-dev/scripts/build.
