### ISSUE TITLE
checkpointing podman container failed. 

### ISSUE THREAD

**Issue by omegazyadav** [checkpoint-restore/criu#839]
Recently I have upgraded the system from fedora30 to fedora31 and tried to checkpoint a simple shell script given in the criu podman page. Previously on fedora 30 it was working but now on fedora31 I am getting same message again and again. 
Console Output: 

[root@pc omega]# podman container checkpoint looper
Error: failed to checkpoint container 7afe15d6edf29434e9feff317ef2bfe3dafad3d333043991c71e43f6c555a845: Configured runtime does not support checkpoint/restore.  

I tried to reconfigure the runc and CNI plugin but I don't know if it is going to work. 
Any help/suggestion appreciated! 

Regards,
omega

**Comment by adrianreber** [comment]
Yes, this is known. With the switch to cgroupsv2 Fedora is now using crun instead of runc and crun still needs to support checkpoint/restore: https://github.com/containers/crun/issues/71

You can tell the Fedora 31 to use cgroupv1 with `systemd.unified_cgroup_hierarchy=0` (see https://fedoraproject.org/wiki/Changes/CGroupsV2) and then tell Podman to use runc again and it should work.

**Comment by omegazyadav** [comment]
changed to cgroupv1 and made configuration to use runc container runtime now another issue is coming out. 

Console output: 

[root@pc runc]# podman run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
Error: container_linux.go:346: starting container process caused "seccomp: config provided but seccomp not supported": OCI runtime error.

previously I built runc container with seccomp option while defining make. 
How can we resolve this issue?

**Comment by adrianreber** [comment]
Right now this is completely CRIU unrelated, but from the error message it seems that your version of runc does not know how to handle seccomp. Can you install Fedora's version of runc and make sure Podman uses it.

**Comment by omegazyadav** [comment]
Slightly deviated from the CRIU perspective but I will figure it out, thanks for the information!
