### ISSUE TITLE
criu restore finished,but dumpee process not be running.what can I do to debug ?

### ISSUE THREAD

**Issue by sunny868** [checkpoint-restore/criu#851]
first .I run "criu dump  -D dir -j -t 24263 " to dump a running process. then dir has next file.

core-24263.img	fs-24263.img   mm-24263.img	  pstree.img	 tty-info.img
fdinfo-2.img	ids-24263.img  pagemap-24263.img  stats-dump
files.img	inventory.img  pages-1.img	  stats-restore

then I run "criu restore dir -j" .there seem all is ok. but 24263 not go on running . in cr-restore.c 
	if (!opts.restore_detach && !opts.exec_cmd){
	    wait(NULL);
	}
 wait(NULL) is not waiting but return.
what can I do to debug next?

**Comment by sunny868** [comment]
I change wait(NULL) to 
	if (!opts.restore_detach && !opts.exec_cmd){
	    int status = -1;
	    int ret = wait(&status);
	    pr_debug("-------wait ret=%d status=%d\n",ret,WEXITSTATUS(status));
	}
then stdout is :
-------wait ret=24263 status=0

**Comment by sunny868** [comment]
I change wait(NULL) to
     if (!opts.restore_detach && !opts.exec_cmd){
            int status = -1;
            int ret = wait(&status);
           pr_debug("-------wait ret=%d status=%d\n",ret,WEXITSTATUS(status));
   }

then output terminal is :
     -------wait ret=24263 status=0

**Comment by rst0git** [comment]
> then I run "criu restore dir -j" 

It should be `criu restore -D dir -j`

@sunny868 you can use `-v4` to set the logging level to dubug and `-o` to specify an output file, for example:
```
criu dump -v4 -o dump.log ...
criu restore -v4 -o restore.log ...
```
