### ISSUE TITLE
podman CI test failure

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#854]
This is mainly for tracking. The problem is already understood and fixes are on their way.

The podman test in CRIU's CI started to fail because a newer version of conmon was pulled in. With this version of conmon Podman restore currently fails. Fixes are already in review:

https://github.com/containers/conmon/issues/85
https://github.com/containers/libpod/pull/4521

**Comment by rst0git** [comment]
https://github.com/checkpoint-restore/criu/pull/891 has been merged, I think we can close this issue.
