### ISSUE TITLE
how to push code (support MIPS arch) to v3.6

### ISSUE THREAD

**Issue by sunny868** [checkpoint-restore/criu#868]
I have finish arch MIPS support base criu v3.6.so now criu can running on MIPS 。
I want to git push my code .how can I do? Do I must merge my code to newlast code before push?or support patch file ?

**Comment by mihalicyn** [comment]
@sunny868 

If you want to use GitHub PRs:
1. Create fork
2. Clone forked repo
3. Create new branch `git checkout -b criu-mips-support`
4. Make your changes
5. Test your changes
6. Push to your repo `git push --set-upstream origin criu-mips-support`
7. Make PR from Github web-interface from branch criu-mips-support onto criu-dev
8. Wait for review :)

If you want to use mailing lists
https://criu.org/How_to_submit_patches

**Comment by cyrillos** [comment]
exactly

**Comment by sunny868** [comment]
$  git push --set-upstream origin criu-mips-support
remote: Permission to checkpoint-restore/criu.git denied to sunny868.
fatal: unable to access 'https://github.com/checkpoint-restore/criu.git/': The requested URL returned error: 403

**Comment by sunny868** [comment]
I don't have permission yet . so Now what can I do ?
$ git push --set-upstream origin criu-mips-support
remote: Permission to checkpoint-restore/criu.git denied to sunny868.
fatal: unable to access 'https://github.com/checkpoint-restore/criu.git/': The requested URL returned error: 403

**Comment by mihalicyn** [comment]
@sunny868 you need to fork criu repo to your github accout, then clone you fork repository. (Or change remote by using `git remote` https://help.github.com/en/github/using-git/changing-a-remotes-url)
Of course, you can't push branches to checkpoint-restore/criu directly. ;)

**Comment by sunny868** [comment]
ok.thank you very much
