### ISSUE TITLE
Can criu still be used as an external tool to migrate docker containers?

### ISSUE THREAD

**Issue by RELOAD22** [checkpoint-restore/criu#872]
I know docker has its own way to migrate containers. (docker checkpoint and restore)
But criu has many more powerful features such as Iterative migration、Disk-less migration、Page server ... How do I apply these powerful features to docker?
 It seems that criu/contrib/docker_cr.sh is no longer working and won't work on newer versions of docker.

**Comment by adrianreber** [comment]
I have not heard from anyone trying to checkpoint containers without the container engine in the last months. There was a report about singularity a few weeks ago here, but as selecting all the right command-line options gets complicated most people are using the container engine commands (docker, lxc, podman).

You could try to use `runc` directly as many of the features you are looking for can be used with `runc`. Unfortunately no one has ported the features from `runc` to the level above (docker, podman).

If you search our bug tracker for singularity you should be able to see what was necessary to checkpoint singularity containers.
