### ISSUE TITLE
criu doesn't work

### ISSUE THREAD

**Issue by farso92** [checkpoint-restore/criu#873]
hi everybody, i installed criu inside lxc container (i tried ubuntu/debian) and the istallation goes well but when i run "criu check" i got this error:
`Error (criu/util.c:610): exited, status=1
Error (criu/util.c:610): exited, status=1
Error (criu/tun.c:85): tun: Unable to create tun: Operation not permitted
Error (criu/cr-check.c:146): sys/kernel/ns_last_pid sysctl is inaccessible: Read-only file system
Does not look good.
`
please somebody help me

**Comment by adrianreber** [comment]
Running in a LXC container usually means unprivileged. CRIU needs full access to the kernel. Try to run it outside of the container.

**Comment by farso92** [comment]
outside on my ubuntu it works...but is it not possible to dare privileges to lxc?

**Comment by farso92** [comment]
i can try also with other containers such as docker or runC if it can be better

**Comment by adrianreber** [comment]
If you give your container enough privileges CRIU should work. But that is more about that specific container engine than CRIU.

**Comment by adrianreber** [comment]
Closing as you seemed to continue the discussion in #874.
