### ISSUE TITLE
webserver checkpoint error 

### ISSUE THREAD

**Issue by farso92** [checkpoint-restore/criu#875]
hi i created a webserver with nginx inside docker. This webserver has a video, my idea is create a checkpoint during video playback, migrate the webserver and start in the new server from that point.
I can migrate the server without any errors if the video is not playing but if it is running i have an error (even if i pause it the error is still here). The error is this:
`Error response from daemon: Cannot checkpoint container webserver1: runc did not terminate sucessfully: criu failed: type DUMP errno 56 path= /run/containerd/io.containerd.runtime.v1.linux/moby/e758c68c71fcf24089f4c300cf7a4dc8cd264ad8b670da31bce4129658d634c3/criu-dump.log: unknown`
and the log says:
`{"level":"error","msg":"container is paused","time":"2019-12-11T09:27:54+01:00"}
{"level":"error","msg":"criu failed: type DUMP errno 56\nlog file: /var/lib/containerd/io.containerd.runtime.v1.linux/moby/e758c68c71fcf24089f4c300cf7a4dc8cd264ad8b670da31bce4129658d634c3/criu-work/dump.log","time":"2019-12-11T09:27:54+01:00"}`
my docker version is:
`Docker version 19.03.5, build 633a0ea838`
my runc version is:
`commit: 5e6369538477c62b0f3a112f49d65e222cda1614
spec: 1.0.1-dev`
my criu version is:
`Version: 3.13`
my Ubuntu version is:
`Ubuntu 18.04.3 LTS`
my kernel is:
`5.0.0-23-generic`

thanks

**Comment by adrianreber** [comment]
Can you provide the dump.log which is mentioned in the error message.

**Comment by farso92** [comment]
i think that i had some zombies process...i removed and reinstalled docker and the error disappeared

**Comment by adrianreber** [comment]
Cool. Closing this now.
