### ISSUE TITLE
Dump error with runc

### ISSUE THREAD

**Issue by farso92** [checkpoint-restore/criu#876]
i m running a busybox container with runc. i want make a checkpoint but when i run

`criu dump -D /tmp/criu_img -v4 -j -t 9360`

i got this error:
```
(00.008406) Error (criu/mount.c:947): mnt: Mount 1098 ./sys/fs/cgroup/devices (master_id: 25 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
(00.008421) Unlock network
(00.008426) Running network-unlock scripts
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.011608) Unfreezing tasks into 1
(00.011620) 	Unseizing 9360 into 1
(00.011646) Error (criu/cr-dump.c:1743): Dumping FAILED.
```

**Comment by adrianreber** [comment]
Why aren't you using runc's `checkpoint` command?

**Comment by farso92** [comment]
because i have an other error and i wanted try a lower dump...if i run
`runc checkpoint test1`
i got this
```
ERRO[0000] container is not destroyed                   
ERRO[0000] criu failed: type NOTIFY errno 0
```

**Comment by farso92** [comment]
with this dump log
```
unix: Dumping external sockets
(00.219625) Error (criu/tty.c:2314): tty: ctty inheritance detected sid/pgrp 1, no PTY peer with sid/pgrp needed
(00.220010) Unlock network
(00.220016) Running network-unlock scripts
(00.220019) 	RPC
iptables-restore: invalid option -- 'w'
ip6tables-restore: invalid option -- 'w'
(00.223416) Unfreezing tasks into 1
(00.223433) 	Unseizing 9360 into 1
(00.223449) 	Unseizing 9549 into 1
(00.223458) 	Unseizing 9595 into 1
(00.223495) Error (criu/cr-dump.c:1743): Dumping FAILED
```

**Comment by adrianreber** [comment]
Can you try to start the container like this: `runc run rhel7-httpd -d -b /runc/containers/rhel7-httpd/ &> /dev/null  < /dev/null`

Replacing the container name and the bundle path with your settings. With this command-line I can dump runc containers.

**Comment by farso92** [comment]
i run that command...no errors but no container created...if i don't use `&> /dev/null < /dev/null` the container Is created but same error

**Comment by adrianreber** [comment]
Can you please copy and paste all commands and all error messages to make sure we are talking about the same things.

**Comment by farso92** [comment]
i start with the run
```
cd /containers/test1
runc run test1
```
it starts the shell, i run a service (a simple counter)
``sh looper.sh``
now in an other terminal i try to create the checkpoint
``runc checkpoint test1``
and i get the error:
```
ERRO[0000] container is not destroyed                   
ERRO[0000] criu failed: type NOTIFY errno 0
log file: /run/runc/test1/criu.work/dump.log 
criu failed: type NOTIFY errno 0
log file: /run/runc/test1/criu.work/dump.log
```
so i tried to make checkpoint with dump service of criu running:
``criu dump -D /tmp/criu_img -v4 -j -t 9360``
but i get the error in the first message
if i try to use:
``runc run test1 -d -b /runc/containers/test1/ &> /dev/null < /dev/null``
runc doesn't create the container (there isn't in runc list) but i haven't errors
thank you for the patience

**Comment by adrianreber** [comment]
Running an interactive command using exec is not possible to checkpoint and restore, because the process running via `runc exec` is not a child process of the container. You have to add the command you want to run to config.json.

**Comment by farso92** [comment]
i love you...you are the best!!!!!! Thank you so much!!!!!! I can close the issue

**Comment by ashwani29** [comment]
@adrianreber what do u mean by this `You have to add the command you want to run to config.json.`  I'm running a simple bash script which is incrementing a value in an infinite loop and printing on the screen and getting the same error as above. 
and what should I do?
