### ISSUE TITLE
[Docker] Failure after restoring a hadoop cluster inside a single container

### ISSUE THREAD

**Issue by zhuguoliang** [checkpoint-restore/criu#877]
Hello,

I hope that this is the appropriate place to open this issue. I am trying to checkpoint and restore a simple hadoop cluster running in a single docker.
Here is what I do:
1. create a hadoop cluster inside docker on host A
2. checkpoint A and export disk image of A
3. transfer both checkpoint and docker image of the container on host A to host B
4. on host B I bring up the image with checkpoint using  following command:
docker start  --checkpoint=xxxxx yyyyyy 
5. step 4 works and we can see the container is up, than docker exec -it zzzz bash
6. in bash: run hadoop example map reduce, oooooops, failure.....

Kernel version: 4.15.0-1056-aws
CRIU version: 3.12 GitID: v3.12-175-g3953b333
Docker version: Docker version 19.03.2, containerd 1.2.6 runc 1.0.0-rc8 

Hadoop map reduce produces UnknownHostException error.
log:  https://gist.github.com/a67afbba9621f6cb5b926beefd13559e.git
 
Please let me know if you need any more information.

Thank you for the help,
Guoliang Zhu

**Comment by zhuguoliang** [comment]
The hadoop cluster is bring up by using existing docker repo sequenceiq/hadoop-docker:2.7.0. 
just do docker pull and execute with "sudo  docker run -it sequenceiq/hadoop-docker:2.7.0"

**Comment by adrianreber** [comment]
Can you run the `hostname` command before and after the checkpoint. If I do that with Podman I get the same hostname:
```
# podman exec -l hostname
4e8ab2cbb04b
# podman container checkpoint -l --export=/tmp/chkpt.tar.gz
# podman rm -fa
# podman container restore  --import=/tmp/chkpt.tar.gz
# podman exec -l hostname
```
Not sure if docker assigns a new hostname after restore.

**Comment by zhuguoliang** [comment]
@adrianreber Hi the hostname is unchanged, from hostA, suppose the container id is "**abcd**" then on hostB the hostname also prints "**abcd**" , also I find that abcd is equal to the container ID.

**Comment by adrianreber** [comment]
Good. I actually was expecting that to be true as the UTS namespace should be handled by CRIU and not by docker, good.

Could you provide a list of all commands exactly like you run them, because I know nothing about hadoop. If I want to recreate this I would need to see all commands you are running. Please provide all the shell input and output.

If you restore the container on the same host, does it work?

**Comment by zhuguoliang** [comment]
Hi, Mr Adrian, I found that everything works on the same host, but after export/import image from host A to host B, some simple command seems to be lost, such as jps, which works on host A but stops working with "bash: jps: command not found", is it possible that some soft/hard file link is lost ?

**Comment by zhuguoliang** [comment]
# Step 1 on host A

sudo docker pull sequenceiq/hadoop-docker:2.7.0

sudo docker run -it sequenceiq/hadoop-docker:2.7.0 

sudo docker exec -it xxx bash

## in bash:

bash: cd /usr/local/hadoop

bash: bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.0.jar grep input output 'dfs[a-z.]+'

### on host A again:

sudo docker checkpoint create xxx zzz; where xxx is container ID, zzz is checkpoint id 
sudo docker export -o mytar.tar xxx; where xxx is container ID

# Step 2 copy mytar.tar and checkpoint dir of container xxx to host B

# Step 3 on host B

sudo docker import mytar.tar; this will import the image with id yyy
sudo docker create -it yyy bash ; this will output uuu as new container id

/# copy checkpoint to /var/lib/docker/containers/yyy/checkpoints/

sudo docker start —checkpoint=zzz uuu

**Comment by zhuguoliang** [comment]
@adrianreber please feel free to tell me if further detail is needed

**Comment by adrianreber** [comment]
Using Podman I can get it to work by changing one of the files in the container after restore:
```
# podman run -it -d sequenceiq/hadoop-docker:2.7.0
# podman exec -itl bash
bash-4.1# cd /usr/local/hadoop
bash-4.1# bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.0.jar grep input output 'dfs[a-z.]+'
# podman container checkpoint --tcp-established -l --export=/tmp/1.tar.gz
# scp /tmp/1.tar.gz rhel08:/tmp
# ssh rhel08
# podman container restore --tcp-established -i /tmp/1.tar.gz 
# podman exec -itl bash -c 'sed -e "s/localhost/`hostname`/g" -i /usr/local/hadoop/etc/hadoop/core-site.xml'
# podman exec -itl bash
bash-4.1# cd /usr/local/hadoop
bash-4.1# bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-2.7.0.jar grep input output 'dfs[a-z.]+'
```

So something in the container tries to be clever and overwrites `/usr/local/hadoop/etc/hadoop/core-site.xml` and replaces the hostname with localhost. As the process is not listening on `localhost` but on the actual IP address this fails.

When the container is initially started `/usr/local/hadoop/etc/hadoop/core-site.xml` still points to the hostname. `localhost` appears after the restore.

**Comment by zhuguoliang** [comment]
@adrianreber bravo, I 'll try it out on docker

**Comment by zhuguoliang** [comment]
@adrianreber I use podman and everything works fine, but while running map reduce job, it produces:
https://gist.github.com/dbd2a8882baa28a7ab1806a5e44ea46e.git

**Comment by adrianreber** [comment]
It sounds like it works now. Can we closed this ticket?
