### ISSUE TITLE
Update Makefile.version in criu-dev to match master

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#895]
Running `criu--version` in `criu-dev` still returns 3.12. Would be nice to have criu-dev report the correct version.

**Comment by 0x7f454c46** [comment]
I believe, it should be updated by rebase of `criu-dev`.
I'll leave it up to Andrei as long as it's not urgent for you.

**Comment by avagin** [comment]
Yes, we need to rebase criu-dev on master. @adrianreber if you have time, you can try to do this.

**Comment by adrianreber** [comment]
Fixed with #919
