### ISSUE TITLE
Jenkins: FAIL: netns-nft.c:51: Can't get nft table

### ISSUE THREAD

**Issue by 0x7f454c46** [checkpoint-restore/criu#898]
On virtuozzo job https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo/job/criu-dev/5991/
```
======================= Run zdtm/static/netns-nft in ns ========================
Start test
Test is SUID
./netns-nft --pidfile=netns-nft.pid --outfile=netns-nft.out --filename=netns-nft.test
Run criu dump
Run criu restore
Send the 15 signal to  93
Wait for zdtm/static/netns-nft(93) to die for 0.100000
############### Test zdtm/static/netns-nft FAIL at result check ################
Test output: ================================
Error: Could not process rule: Table 'netns-nft-zdtm-test' does not exist
list table inet netns-nft-zdtm-test
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:07:44.408:     4: FAIL: netns-nft.c:51: Can't get nft table (errno = 11 (Resource temporarily unavailable))

 <<< ================================
```
@mihalicyn, please look when time permits.

**Comment by mihalicyn** [comment]
@0x7f454c46 I think problem is, that CRIU was built without support of nftables. But netns-nft test runs when `nft` utility is present on host. And we got this error. Which OS works on test server? On Ubuntu 18.04 and CentOS 7 libnftables is not present.

**Comment by mihalicyn** [comment]
I've checked logs.
https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo/job/criu-dev/5991/consoleFull
```
Makefile.config:39: Warn: you have no libnftables installed
Makefile.config:40: Warn: Building without nftables support
```

**Comment by 0x7f454c46** [comment]
+Cc @Snorch, when you have time, could you install `libnftables-dev` on the dut?
Thanks

**Comment by Snorch** [comment]
Will try to fix it tomorrow, hope I can get access to the node. Thanks!

**Comment by Snorch** [comment]
https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo/job/criu-dev/6002/

Skipped the netns-nft test as we don't have a libnftables package on VZ7 yet.

**Comment by 0x7f454c46** [comment]
@Snorch thanks!
