### ISSUE TITLE
Is criu now supporting OpenGL?

### ISSUE THREAD

**Issue by ghostplant** [checkpoint-restore/criu#901]
Is criu now supporting OpenGL?

**Comment by adrianreber** [comment]
> Is criu now supporting OpenGL?

Could you provide more details what exactly you are looking for? If you are talking about hardware accelerated OpenGL then it will probably not work as CRIU has no way to get and restore the state of the hardware device used for acceleration.

**Comment by ghostplant** [comment]
@adrianreber OK, I mean checkpointing a standard OpenGL application. BTW, how about checkpointing a CUDA application?

**Comment by adrianreber** [comment]
> OK, I mean checkpointing a standard OpenGL application.

Not knowing much about OpenGL, but a non-hardware-acclerated OpenGL application should be no problem.

> BTW, how about checkpointing a CUDA application?

The same as above. You need to have a way to get the state of the hardware out of the hardware. As long as there is no interface and no one implements the necessary CRIU code it cannot work. Usually it is not possible to get the hardware state of an accelerator. Somebody, however, has mentioned some time ago that there are debugger interfaces which might be able to provide the necessary information. So far nobody has done the work to integrate it in CRIU. If this is something you are familiar with we are happy to accept patches.

**Comment by ghostplant** [comment]
Thanks!

**Comment by ghostplant** [comment]
@adrianreber Currently, my running program is mapping with `/dev/nvidiactl` so criu is unable to checkpoint this program due to this device mapping.
However, if I don't care to recover the hardware states, I just want to checkpoint and restore all other states. Is it possible?

**Comment by adrianreber** [comment]
If you do a `close()` on `/dev/nvidiactl` it might work.

**Comment by theyueli** [comment]
hi @adrianreber , we had a similar use case, and met the same problem regarding the device. Could you elaborate on the suggestion regarding `close()` on the device?

**Comment by adrianreber** [comment]
@theyueli I have never used CUDA, but if your question is about CUDA, at some point your program must somehow connect to the GPU. If you want to checkpoint this program you need to make sure to close the connection to the GPU before running CRIU. Does that help?
