### ISSUE TITLE
CRIU restore shouldn't always set SOCKET SND&RCV buffer size.

### ISSUE THREAD

**Issue by jungan** [checkpoint-restore/criu#912]
When an application doesn't specifically set ```SO_SNDBUF``` or ```SO_RCVBUF``` for its socket. The kernel can actually automatically adjust the buffer size internally. On the other hand, if application has set ```SO_SNDBUF``` and/or ```SO_RCVBUF```(criu actually use ```SO_SNDBUFFORCE``` and ```SO_RCVBUFFROCE```, it's same thing here), the kernel won't do auto adjustment any more(By masking ```sk_userlocks```), unfortunately, kernel doesn't expose API to get ```sk_userlocks```, CRIU basically don't know if the application has set the buffer size or not.

It did cause some performance problems when use CRIU to restore a TCP server, before dump/restore, the TCP server listening socket is using default snd&recv buffer size. When it accepted a new connection request, the "new socket" inherited the characteristic of the "listening socket" and when there is a large network traffic passing through, the buffer size can be automatically expand to a larger number.

But after CRIU dump/restore, the "listening socket" will be set to a specify snd&recv buffer size and "newly accepted socket" also inherited that, then kernel won't automatically adjust the buffer size even there is a heavy traffic load, and significantly impact the performance, a lot of EAGAIN error caused by full tcp send buffer.

Any one has an idea how to elegantly solve this problem?

**Comment by rst0git** [comment]
CRIU actually sets the snd&recv buffer size twice - once in `restore_prepare_socket()`, where it sets the sizes of buffers to maximum to prevent blocking, and then in `restore_socket_opts()` where the original buffer size values are restored.

IMHO an elegant solution would be to checkpoint and restore `sk_userlocks`, however, as you mentioned, the kernel doesn't expose the necessary APIs.

A simple work-around could be to use the `--tcp-close` option of CRIU during restore and expect the application to reopen TCP sockets.
