### ISSUE TITLE
arm: Remove stack pointer from clobber list?

### ISSUE THREAD

**Issue by carnil** [checkpoint-restore/criu#913]
Hi

Building `criu` (in this case based on 3.13) in Debian on armhf fails to build, similarly as already reported for ppc64el and s390x by @adrianreber.

I think the solution would look similar here, but explictly filling as issue.

The build log can be fetched here:
https://buildd.debian.org/status/fetch.php?pkg=criu&arch=armhf&ver=3.13-4&stamp=1579242990&raw=0

**Comment by adrianreber** [comment]
Just tried to fix this, but CRIU does not seem to work on Fedora 31 armhfp with gcc 9.

I can get it to compile but it fails with: `Error (criu/vdso.c:615): vdso: Failed to fill self vdso symtable`

Any ideas what is necessary to get CRIU working on armhfp?
