### ISSUE TITLE
CRIU doesn't c/r TCP_NODELAY for "listening sockets"

### ISSUE THREAD

**Issue by jungan** [checkpoint-restore/criu#920]
I saw that CRIU does c/r ```TCP_NODELAY``` for **established tcp connections** but not for **listenning socket**, the problem here is the new socket created by ```accept``` inherited the socket option flags from **listening socket**. I think it changed socket behavior after CRIU restore. I have a simple fix for this but would like to check if I missed sth before I submit the PR. Thanks!!

**Comment by rst0git** [comment]
@jungan Feel free to open a PR, and it would be good if you add a test case (ideally the test should fail before your fix is applied).
> CRIU does c/r `TCP_NODELAY` for established tcp connections but not for listenning socket, the problem here is the new socket created by accept inherited the socket option flags from listening socket.

This is a good description of **why** the fix is needed, and you should include it in the commit message.
