### ISSUE TITLE
criu dump fails on TCP dump

### ISSUE THREAD

**Issue by digitalix** [checkpoint-restore/criu#931]
I'm trying to dump an FFmpeg process where both input and output are using TCP.

I'm running everything within a docker container on macOS using the command below:
`docker run -it --privileged --security-opt seccomp:unconfined --security-opt apparmor=unconfined --cap-add all  myimage:latest`

At first, it works perfectly but as I'm dumping and restoring at some point the dump fails even though it worked 10 seconds ago. As I'm testing it I repeat dump and restore every 10 seconds.
Here is a part from dump.log.

> (00.056312) sockets: Searching for socket 0x29c30 family 2
(00.056329) sockets: No filter for socket
(00.056332) inet: Dumping inet socket at 3
(00.056337) inet: 	Dumping: ino  0x29c30 family AF_INET    type SOCK_STREAM    port    33472 state TCP_CLOSE_WAIT   src_addr 127.0.0.1
(00.056344) inet: 	Dumped: family AF_INET    type SOCK_STREAM    proto IPPROTO_TCP      port 33472 state 0                src_addr 127.0.0.1
(00.056349) tcp: Dumping TCP connection
(00.056352) tcp: 	Turning repair on for socket 29c30
(00.056362) 	Running iptables [iptables -w -t filter -I INPUT --protocol tcp -m mark ! --mark 0xC114 --source 127.0.0.1 --sport 8000 --destination 127.0.0.1 --dport 33472 -j DROP]
(00.058652) Locked 127.0.0.1:33472 - 127.0.0.1:8000 connection
(00.058683) 	Running iptables [iptables -w -t filter -I OUTPUT --protocol tcp -m mark ! --mark 0xC114 --source 127.0.0.1 --sport 33472 --destination 127.0.0.1 --dport 8000 -j DROP]
(00.061097) Locked 127.0.0.1:8000 - 127.0.0.1:33472 connection
(00.061129) Error (soccr/soccr.c:87): Can't turn TCP repair mode ON: Operation not permitted
(00.061142) 	Running iptables [iptables -w -t filter -D INPUT --protocol tcp -m mark ! --mark 0xC114 --source 127.0.0.1 --sport 8000 --destination 127.0.0.1 --dport 33472 -j DROP]
(00.063453) Unlocked 127.0.0.1:33472 - 127.0.0.1:8000 connection
(00.063492) 	Running iptables [iptables -w -t filter -D OUTPUT --protocol tcp -m mark ! --mark 0xC114 --source 127.0.0.1 --sport 33472 --destination 127.0.0.1 --dport 8000 -j DROP]
(00.066000) Unlocked 127.0.0.1:8000 - 127.0.0.1:33472 connection
(00.066061) ----------------------------------------
(00.066103) Error (criu/cr-dump.c:1345): Dump files (pid: 77) failed with -1

The command I'm using to dump looks like this `criu dump -t 77 --tcp-established --file-locks -vvvv -o dump.log` and to restore I use this `criu restore --tcp-established --file-locks -vvv  -o restore.log`.

**Comment by rst0git** [comment]
> (00.056337) inet: Dumping: ino 0x29c30 family AF_INET type SOCK_STREAM port 33472 state TCP_CLOSE_WAIT src_addr 127.0.0.1

> (00.061129) Error (soccr/soccr.c:87): Can't turn TCP repair mode ON: Operation not permitted

It looks like CRIU fails to set `TCP_REPAIR` on a socket in `TCP_CLOSE_WAIT` state. This requires `CAP_NET_ADMIN` and commit https://github.com/torvalds/linux/commit/319b0534b9588124cdc7128e121f3f85daaab556.

> I'm running everything within a docker container on macOS

What is your kernel version, and what is the output of `criu check --all`?

**Comment by digitalix** [comment]
@rst0git 
> It looks like CRIU fails to set TCP_REPAIR on a socket in TCP_CLOSE_WAIT state. This requires CAP_NET_ADMIN and commit torvalds/linux@319b053.
So why does it work for most of the time? As I said; I'm dumping and restoring the same process every 10 seconds.

> What is your kernel version (i.e. uname -a inside the container), and what is the output of criu check --all?

`Linux 9ea142d0930f 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux`

```Warn  (criu/net.c:2910): Unable to get socket network namespace
Warn  (criu/net.c:2910): Unable to get tun network namespace
Warn  (criu/sk-unix.c:229): unix: Unable to open a socket file: Bad address
Error (criu/uffd.c:264): uffd: Lazy pages are not available: Function not implemented
Warn  (criu/net.c:2910): Unable to get socket network namespace
Warn  (criu/kerndat.c:839): Can't keep kdat cache on non-tempfs
Warn  (criu/cr-check.c:850): Dirty tracking is OFF. Memory snapshot will not work.
Error (criu/cr-check.c:1099): TCP_REPAIR can't be enabled for half-closed sockets
Error (criu/cr-check.c:1207): UFFD is not supported
Error (criu/cr-check.c:1207): UFFD is not supported
Error (criu/cr-check.c:1033): failed to mount autofs: No such device
Warn  (criu/cr-check.c:1197): compat_cr is not supported. Requires kernel >= v4.12
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

Is there a way for me to detect if a socket is in `TCP_CLOSE_WAIT`?

**Comment by rst0git** [comment]
> Error (criu/cr-check.c:1099): TCP_REPAIR can't be enabled for half-closed sockets

The error occurred because the kernel version does not have the commit mentioned earlier. Upgrading [Docker Desktop](https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2200) should solve the issue.

> There is nothing about TCP, so would that mean I should be good?

Yes, the same error should not reproduce on the k8s cluster.

**Comment by digitalix** [comment]
Great.

I've upgraded my docker, and the error from `criu check` is gone. I don't have time to test it but hopefully, this solves my problem.

Thanks!
