### ISSUE TITLE
criu failed: type NOTIFY errno 0 when migrate docker to different node

### ISSUE THREAD

**Issue by RELOAD22** [checkpoint-restore/criu#949]
I create a docker container
`docker run -d --name looper --security-opt seccomp:unconfined busybox  /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
and create a checkpoint from it:
`docker checkpoint create looper checkpoint1`
I copy the checkpoint1 to another node, then i create a new container on it
`docker create -d --name looper --security-opt seccomp:unconfined busybox  /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`
and i restore the container with checkpoint1:
`docker start --checkpoint=checkpoint1 looper`

the error message is:
`Error response from daemon: OCI runtime restore failed: criu failed: type NOTIFY errno 0
log file: /var/lib/containerd/io.containerd.runtime.v1.linux/moby/ad9b5e95fa5a67603bdf692606ebd07bc69b176cb4d95c910be0debe356c4cf4/restore.log: unknown`

src node:
criu version:`Version: 3.12`
linux version:`3.10.0-957.el7.x86_64`
dst node:
criu version:`Version: 3.12`
linux version:`3.10.0-862.el7.x86_64`

**Comment by adrianreber** [comment]
Can you share the CRIU log file `restore.log`?

Is this the CRIU version directly from CentOS or from somewhere else?

**Comment by RELOAD22** [comment]
I can't find `restore.log` .
the directory `/var/lib/containerd/io.containerd.runtime.v1.linux/moby/ad9b5e95fa5a67603bdf692606ebd07bc69b176cb4d95c910be0debe356c4cf4/` is not exist because restore failed.
I use command `criu --version` to get criu version

**Comment by adrianreber** [comment]
Can you try it with Podman to see if you get the same error message:
```
# yum install -y podman
# podman run --rm -d --name looper --security-opt seccomp=unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
# podman container checkpoint -l -e /tmp/1.tar.gz
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
# scp /tmp/1.tar.gz second-host:
# podman container restore -i /tmp/1.tar.gz 
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
```

**Comment by RELOAD22** [comment]
criu failed when i exec `podman container checkpoint -l -e /tmp/1.tar.gz`
```
ERRO[0000] container is not destroyed                   
ERRO[0000] criu failed: type NOTIFY errno 0
log file: /var/lib/containers/storage/overlay-containers/3ff037bd62b83494219351faddbba0f998d1786b337df50aee301523eee0b086/userdata/dump.log 
criu failed: type NOTIFY errno 0
```
[dump.log](https://github.com/checkpoint-restore/criu/files/4193652/dump.log)

**Comment by adrianreber** [comment]
Try `setenforce 0`. Podman and CRIU and SELinux only work correctly on Fedora 30 and RHEL 8. Maybe that also helps for Docker.

**Comment by RELOAD22** [comment]
I tried following the steps above and it seemed that a similar problem appeared
```
Error: failed to restore container 3ff037bd62b83494219351faddbba0f998d1786b337df50aee301523eee0b086: time="2020-02-13T01:22:44+08:00" level=error msg="criu failed: type NOTIFY errno 0\nlog file: /var/lib/containers/storage/overlay-containers/3ff037bd62b83494219351faddbba0f998d1786b337df50aee301523eee0b086/userdata/restore.log"
criu failed: type NOTIFY errno 0
log file: /var/lib/containers/storage/overlay-containers/3ff037bd62b83494219351faddbba0f998d1786b337df50aee301523eee0b086/userdata/restore.log
: OCI runtime error
```
Same as last time, no corresponding restore.log file is generated

**Comment by adrianreber** [comment]
Okay, try starting the container without `--rm`, to avoid deletion of the container after it ends. Failing a restore also means the container is finished and it will be deleted.
```
# podman run -d --name looper --security-opt seccomp=unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
# podman container checkpoint -l -e /tmp/1.tar.gz
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
# scp /tmp/1.tar.gz second-host:
# podman container restore -k -i /tmp/1.tar.gz 
1d8027e956ae054520bde75f4eb20db8d37593254c71408327ddb5628f4e4104
```
Do the restore with `-k` to make sure all files are kept after restore.

**Comment by RELOAD22** [comment]
I can get restore.log this time, but I still can't understand why it failed.
[restore.log](https://github.com/checkpoint-restore/criu/files/4194517/restore.log)

**Comment by RELOAD22** [comment]
I searched in issues and found a similar problem. 
`modprobe snd-dummy` this has helped and now the error is gone
I really appreciate your help. But I don't understand why asound make criu failed. I think it has nothing to do with criu.  
I saw a sentence saying“For criu, it is just one of mount points, which was dumped and has to be restored.” I don't quite understand the meaning of this sentence. Which mount points need to be dumped? Why criu needs to ensure that these mount points are successfully mounted?

**Comment by RELOAD22** [comment]
There is another problem. I need to migrate docker container but docker start will not generate restore.log if it fails. Is there any way I can get the restore.log for this process? Without it, it would be difficult to debug...

**Comment by adrianreber** [comment]
Does it work now with Podman or not?

> For criu, it is just one of mount points, which was dumped and has to be restored.

CRIU tries to restore everything as it used to be. If there is something mounted, CRIU will try to mount the same device at the same place. If it does not exist (because of a missing module), CRIU cannot mount it and will fail.

**Comment by RELOAD22** [comment]
Yes, it works now. After executing `modprobe snd-dummy`， both podman and dokcer are able to restore.

**Comment by adrianreber** [comment]
> Yes, it works now. After executing `modprobe snd-dummy`， both podman and dokcer are able to restore.

Cool. Perfect!

**Comment by RELOAD22** [comment]
`docker start` will not generate restore.log if it fails. 
Is there any way I can get the restore.log for this process? 
Without it, it would be difficult to debug...

**Comment by adrianreber** [comment]
That sounds like a docker problem and not a CRIU problem. Please talk to docker if there is something not working as you expect it to.
