### ISSUE TITLE
Don't have tty to inherit session from, aborting when migrate docker to different node

### ISSUE THREAD

**Issue by RELOAD22** [checkpoint-restore/criu#952]
I create a docker container
`docker run -dit --name apache-app --security-opt seccomp:unconfined  -p 8080:80 httpd:2.4`
and create a checkpoint from it. 
I copy the checkpoint to another node, but failed to restore it

[Enable checkpoint/restore of containers with TTY](https://github.com/moby/moby/pull/38405)
If I restore on the same node, it will be successful. But it will fail on different nodes.
the error message is:
```
Error response from daemon: OCI runtime restore failed: bad file descriptor: unknown
2020-02-16 11:43:20,072 - root - ERROR - Error: docker create failed
```
restore.log:
[criu.log](https://github.com/checkpoint-restore/criu/files/4209334/criu.log)

`
(00.216424)      9:     Receive fd for 0
(00.216426)      9:     Receive fd for 1
(00.216429)      9:     Receive fd for 2
(00.216432)      9:     Receive fd for 3
(00.216435)      9:     Receive fd for 4
(00.216437)      9:     Receive fd for 5
(00.216440)      9:     Receive fd for 6
(00.216544)      1: Client exited unexpectedly
(00.216551)      1: Error (criu/tty.c:1017): tty: Don't have tty to inherit session from, aborting
(00.216555)      1: Error (criu/files.c:1196): Unable to open fd=0 id=0x24
(00.217681) mnt: Switching to new ns to clean ghosts
(00.217822) Error (criu/cr-restore.c:2293): Restoring FAILED.
(00.217851) Error (criu/cr-service.c:111): Can't send response: Broken pipe
(00.217856) Error (criu/cr-service.c:722): Can't send response: Broken pipe
`
src node:
criu version:Version: 3.12
linux version:3.10.0-957.el7.x86_64
dst node:
criu version:Version: 3.12
linux version:3.10.0-862.el7.x86_64

**Comment by zzyyrr** [comment]
Hi, I got the same issue, do you have any solutions? Thanks!
