### ISSUE TITLE
Drop existing TCP connections

### ISSUE THREAD

**Issue by anujkumar-df** [checkpoint-restore/criu#953]
Hi, I am trying to migrate Linux processes from one EC2 instance to another. In the process of doing so, I cut off the TCP connections via the security groups, but I have to let the on-going sessions drain.

Is there a way to drop those active connections so they don't make it to the dumped image, so I can start the processes without the same IP address restriction?

**Comment by adrianreber** [comment]
CRIU has the option `--tcp-close`. Have you tried that? That sounds like what you need.

**Comment by anujkumar-df** [comment]
From what I have understood, it can only be used during the restore process, isn't it?

**Comment by adrianreber** [comment]
Yes the state of the sockets would still be checkpointed, but if they are ignored during restore, the result should be same, right?

**Comment by rst0git** [comment]
@anujkumar-df I think it is important to note that by using `--tcp-close` you may encounter data loss -- when a packet has been received and ACK-ed but its data payload has not yet been read by the process, by discarding the buffered data of a tcp socket neither the sender nor the receiver would know about it.

**Comment by anujkumar-df** [comment]
@rst0git It's my assumption that clients would implement some sort of retry mechanism to re-initiate the connection. I stop accepting the new incoming connections and start the dump process after a while (assuming that the established TCP connections have emptied their output buffer). Do you think this will still break something somewhere?

**Comment by rst0git** [comment]
It really depends on the use case. Another approach could be to use a load balancer and redirect incoming packets to a different server instance during checkpoint/restore. Or perform a checkpoint using `--leave-running`, and once the server has been successfully restored stop the original instance.

You can also check the content of `tcp-stream-XXXXXX.img` with the `crit` tool to find out if any buffer data has been included.

**Comment by anujkumar-df** [comment]
> Yes the state of the sockets would still be checkpointed, but if they are ignored during restore, the result should be same, right?

I have seen if TCP stream data makes to the dumped image, then restoration fails, even with --tcp-close flag.

**Comment by shubham95** [comment]
> It really depends on the use case. Another approach could be to use a load balancer and redirect incoming packets to a different server instance during checkpoint/restore. Or perform a checkpoint using `--leave-running`, and once the server has been successfully restored stop the original instance.
> 
Process P1 is checkpointed and restored as P2
In --leave-running states after restoring how state of both process will be same.
The restored process P2 will always lags compared to P1 
I didn't get idea of --leave-running.
Can you clarify :)

**Comment by anujkumar-df** [comment]
@shubham95 One use-case can be if you want to horizontally scale an in-memory database behind a load balancer, but building cache is an expensive operation.

**Comment by rst0git** [comment]
> I didn't get idea of --leave-running.
Can you clarify :)

P1 and P2 can be in a different state after restore. As @anujkumar-df mentioned, this enables horizontal scaling. For example, https://asciinema.org/a/es8bzehh0WRjlkl2SZiLGjxKz

**Comment by anujkumar-df** [comment]
Closing the issue. It's by the design of TCP.
