### ISSUE TITLE
fail on tcp restore

### ISSUE THREAD

**Issue by digitalix** [checkpoint-restore/criu#954]
I'm having a weird issue while trying to restore a process.

Here are the cmd that I use:
`criu dump -t 1956 --tcp-established --shell-job --file-locks -vvv --images-dir /tmp/dump -o /tmp/dump/dump.log`
`criu restore --tcp-established --file-locks -vvv --images-dir /tmp/dump -o /tmp/dump/restore.log`

These commands are executed by my app every few minutes, and it works like this:
1. Run some process
2. Wait for 5 minutes
3. Dump & Copy (images, and filesystem)
4. Restore
5. Go back to point 2

This works, but when I stop my app and then start it again using the last dump it fails to restore. How is that possible that the restore fails even though it worked before using the exact copy?

Here are the logs:
restore.log: https://pastebin.com/AsvzreQD
dump.log: https://pastebin.com/mLKhjTvc

Based on my understanding it fails when trying to restore a TCP socket.
Does anyone know what to do?

Thanks.

**Comment by anujkumar-df** [comment]
Are you restoring on the same host or a different host?

**Comment by digitalix** [comment]
> Are you restoring on the same host or a different host?

I'm doing everything in a docker container, using the latest version.
At first, I was trying to restore it in a different container, but it didn't work. So I tried to restore it in the same container but it still fails.

**Comment by avagin** [comment]
@digitalix why did you close this issue?

**Comment by digitalix** [comment]
Well, I wasn't sure what to do with this issue.

So far I managed to determine that the cause behind it is fuse. Without mounting a drive via fuse the same thing works perfectly. However, I need fuse in my project so it was a big deal breaker but then I tested it on my k8s cluster and everything seems fine. At this point, I'm not sure whether this is something caused by docker or criu.

**Comment by avagin** [comment]
I know why you get this error. TCP connections can be restored only if their traffic is blocked between dump and restore. In your case, "criu dump" on the third step adds iptables rules to block traffic for dumped tcp connections and "criu restore" on the fourth step drops these rules (after restoring connections). So when you stop your app and call "criu restore" again there are no iptables rules and this is why you get this error.

**Comment by digitalix** [comment]
> I know why you get this error. TCP connections can be restored only if their traffic is blocked between dump and restore. In your case, "criu dump" on the third step adds iptables rules to block traffic for dumped tcp connections and "criu restore" on the fourth step drops these rules (after restoring connections). So when you stop your app and call "criu restore" again there are no iptables rules and this is why you get this error.

Do you know how to solve it then? and are you sure that's the reason? It happens only when I mount remote storage like S3 or GCS using fuse. Without fuse, I'm able to restore it on a new host.

**Comment by avagin** [comment]
I'm sure that this is the reason of this error:
(00.044753)   1956: Error (soccr/soccr.c:831): Can't restore 2 queue data (-1), want (825:3383228:825): Broken pipe

**Comment by avagin** [comment]
As for how to fix this, I need more information about your enviroment.

* Do you dump a docker container or one process?
* Where fuse is mounted and how dumped processes are using it. cat /proc/pid/mountinfo, lsof -p pid, erc will be useful.
* Do you understand how a dumped process uses these tcp connections? You must understand that if you stop a processes and restores it from a snapshot, tcp connections will be restored but they will be broken due to inconsistency of states with remote sides.
