### ISSUE TITLE
CRIU restore hangs

### ISSUE THREAD

**Issue by anujkumar-df** [checkpoint-restore/criu#955]
Hi fellas.
While restoring, criu hangs. The following is the attached log: https://gist.github.com/anujkumar-df/34901c97389137832420525bdbd5258b
Please let me know how can I find about the problem.

**Comment by rst0git** [comment]
Hi @anujkumar-df, could you please provide more information about the process that you are restoring and how to reproduce this issue?

**Comment by avagin** [comment]
could you show output for crit show pstree.img?

**Comment by anujkumar-df** [comment]
I was not able to reproduce the problem, closing.
