### ISSUE TITLE
CRIU not initiating on shutdown of node for docker container

### ISSUE THREAD

**Issue by sushil11th** [checkpoint-restore/criu#956]
Trying to automatically do docker checkpoint when the system goes down, not working so far.

**Comment by adrianreber** [comment]
Can you provide a lot more information about how you are trying to do this?

**Comment by sushil11th** [comment]
I am trying to execute the **docker checkpoint** option whenever there is any termination/restart/stop activity started to save the application state and migrate it to another node and start the app there. Is it possible? or any way around?

**Comment by adrianreber** [comment]
I am sorry, but you really have to provide much more details. You are saying:

>  not working so far.

What error do you get? Do not just describe the error, you have to give us the command you were using. The exact error message, log files. Which Linux distribution are you using? Which version of docker? Which version of CRIU?

> I am trying to execute the docker checkpoint option whenever there is any termination/restart/stop activity started to save the application state and migrate it to another node and start the app there. 

How? What do you mean by "termination/restart/stop activity"? Which part tries to handle this signal? How do you control your containers? With which commands? What do you mean by migration?

You really need to include much more details.

I can answer, however, this question:

> Is it possible?

Yes

**Comment by sushil11th** [comment]
Amazon ECS and Amazon Linux 2 AMI
CRIU version 3.5
Docker version:

**Comment by adrianreber** [comment]
My recommendation would be to use Podman (and maybe even CentOS 8). See https://criu.org/Podman for the checkpoint/restore support (especially the migration support). Podman has the possibility to generate systemd unit file to start and stop containers. These systemd unit files could be adapted to run checkpoint on shutdown and restore on startup, this way a checkpoint could be written and transferred automatically to another node. Having worked on the CRIU checkpoint/restore implementation I am biased, but the implementation to export a checkpoint to be able to easily transfer it to another system was one of my goals.

Podman is part of CentOS 8 and the Podman version in CentOS 8.1 (1.6.4) should have everything you need. Not sure if Amazon Linux includes Podman. As far as I know it is based on CentOS/RHEL so it could already be part of Amazon Linux.

**Comment by sushil11th** [comment]
Thanks a lot, @adrianreber , closing the issue now.
