### ISSUE TITLE
 criu restore is successful, but the program crashed

### ISSUE THREAD

**Issue by RELOAD22** [checkpoint-restore/criu#972]
I checkpointed and restored a java program.
It seems that restore is successful, but the program crashes after running for a while：
`   987 Aborted                 (core dumped) $JAVA -Xmx2g -jar $GATK -T BaseRecalibrator -R $REFERENCE -I /mnt/xfs/wgs-data/output/normal_realigned2.bam -knownSites $dbsnp -knownSites $phase1_1000G -o /mnt/xfs/wgs-data/output/bqsr2.table &> /dev/null`
Under normal execution(without C/R), I'm sure that the program will not error.

[dump.log](https://github.com/checkpoint-restore/criu/files/4273579/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/4273582/restore.log)
And here is the error message generated. This seems to be a divide by zero exception.
[hs_err_pid987.log](https://github.com/checkpoint-restore/criu/files/4273583/hs_err_pid987.log)
What could be causing this exception? Both dump.log and restore.log show that everything is ok. The program did not crash immediately after recovery, on the contrary, it crashed at the end.

criu version: Version: 2.6
kernel version: Linux b8680175445c 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adrianreber** [comment]
Why CRIU 2.6? Why not a much newer version? Also, this seems to be a RHEL/CentOS  kernel. That requires a special patch (https://git.centos.org/rpms/criu/blob/c7/f/SOURCES/aio-fix.patch). You need to take CRIU from RHEL/CentOS.

**Comment by RELOAD22** [comment]
Does it mean that I should download the source code and use this patch instead of installing directly with yum？ 
Actually, I encountered this problem when using docker checkpoint and start. I want to dump and restore a container, there is a java program inside the container. The result is like what I said above. So I installed criu in the container for testing and got the same results.
The version of criu on the outside host is 3.12.  release version is :`CentOS Linux release 7.7.1908 (Core)` kernel version: `Linux k8s03 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by adrianreber** [comment]
> Does it mean that I should download the source code and use this patch instead of installing directly with yum？

No the version from CentOS should work. You wrote that you are using CRIU 2.6. That was never part of CentOS 7, that was why I was mentioning the patch. If you use CRIU via yum, you do not need the patch.

Please provide the logs from the docker failure with CRIU installed via yum from CentOS.

**Comment by RELOAD22** [comment]
In fact, docker checkpoint and start both succeeded. But the program crashed after running for a few minutes.  I'm sure that the program will not error without C/R.
I was just curious why the restore was successful, but the program crashed with an exception after a few minutes. What are the possible causes of this phenomenon？

**Comment by adrianreber** [comment]
> I was just curious why the restore was successful, but the program crashed with an exception after a few minutes. What are the possible causes of this phenomenon?

Unfortunately I have no idea. Could be a lot of things. Not sure anybody here has enough JVM knowledge to give you a good answer. Maybe someone who understands the JVM better would understand what is going wrong. It would be important to mention that this crash is related to checkpointing and restoring.

**Comment by RELOAD22** [comment]
I really appreciate your patience and help. I will keep trying to find out the cause of the crash.

**Comment by chflood** [comment]
You are crashing while trying to parse org.broadinstitute.gatk.utils.MathUtils::log10Factorial (24 bytes).  Can you verify that the class file for this library is the same at both checkpoint and restore time?

**Comment by adrianreber** [comment]
Thanks @chflood!

@RELOAD22 Can you please list all the steps you are doing to migrate your container. How do you make sure that all changes to the filesystem are also on the destination of the migration?

**Comment by mihalicyn** [comment]
> I was just curious why the restore was successful, but the program crashed with an exception after a few minutes. What are the possible causes of this phenomenon？

There are many cases where it could come on.
Recently, we fixed very close issue:
https://github.com/checkpoint-restore/criu/pull/908
But as I can see you have used CRIU from CentOS repos. CentOS has an old version of GCC (~4.6), looks like old versions of GCC not cause problem described in PR #908 

But anyway, you can try to compile the latest version of CRIU (from criu-dev) "by hands" and test with it.

**Comment by mihalicyn** [comment]
@RELOAD22 Hm... another interesting question is: have you reproduced that crashes several times? And always you get the same call stacks from JVM or not? Could you provide several crash logs from JVM?

**Comment by chflood** [comment]
Another thought is that I've set up a library that allows you to call out to criu from inside java.  This way you can ensure that the checkpointing happens from a quiescent place.  The restore is going to be easier if the compiler and the gc are stopped at a happy place.  

There's a prototype here:  https://github.com/chflood/CRIUForJava that should give you an idea of how to do this, but it's still a bit rough.  I'm working on making it easier to use.

**Comment by mihalicyn** [comment]
Upd: I think it makes sense to try to checkpoint your container with `--leave-running` option. To distinguish restore problems with checkpoint-time problems.
