### ISSUE TITLE
CRIU package for Ubuntu 19.10 (Eoan Ermine)

### ISSUE THREAD

**Issue by cevich** [checkpoint-restore/criu#973]
I looked on both listed repositories listed on the wiki-

https://launchpad.net/ubuntu/+source/criu
https://launchpad.net/~criu/+archive/ubuntu/ppa

Is is possible to build/publish packages for the latest Ubuntu Release?

**Comment by adrianreber** [comment]
@cevich I can do that, no problem. I am planing to add additional architectures to the PPA and a new CRIU release is currently being prepared.

Would you rather have it 'today' or in one or two weeks? If you need it today, I can just rebuild the current package, but if you can wait, I can do all changes in combination with the next release. I can do either, whatever works best for you.

**Comment by cevich** [comment]
Both please :smile:  My goal on the libpod side is to keep one latest-and-greatest set of tests on Ubuntu running.  I'm pretty slow on the 19.10 train though.  Next is a new LTS release, ya?  Given a 19.10 package, I'm in no rush for the next CRIU version, if you want to hold off until LTS ships.  Thanks again.

**Comment by adrianreber** [comment]
There is now a CRIU package for 19.10. I was not able to test it correctly and I switched it to python3. It builds and it probably works, but let me know if I broke something.

**Comment by cevich** [comment]
Thanks. Okay, testing now.

**Comment by dirkpetersen** [comment]
I wonder if you could also build a criu package with python3 support for Ubuntu 18.04 which is the current LTS release. We are not allowing python2 on newly installed systems any more.

**Comment by adrianreber** [comment]
@dirkpetersen I think your request makes sense and I should have switched to python3 much earlier for 18.04. Not sure I should do it, however? Maybe with an upcoming update to 3.14 it would make sense, but just replacing the current 3.13 with a newer build with Python 3. Not sure everyone would be happy about such a change.
