### ISSUE TITLE
Podman not dealing with open files when working with criu?

### ISSUE THREAD

**Issue by zhuguoliang** [checkpoint-restore/criu#975]
During restore of mysql, I went into a file mismatch which says:

> Error (criu/files-reg.c:1702): File var/log/mysql/error.log has bad size 780247 (expect 804911) 
(The while log is pasted at https://gist.github.com/8714ea05a4cd38f74e1faddb73eb293d.git)

In criu issues #948, https://github.com/checkpoint-restore/criu/issues/948 

I assume that podman will keep all open files for processes, but why is the file /var/log/mysql/error.log not in consistent state?

**Comment by rst0git** [comment]
Hi @zhuguoliang, could you try starting the container with `--tmpfs /var/log/mysql`?

**Comment by adrianreber** [comment]
In addition to what @rst0git said, can you share the command-line you are using to checkpoint and restore the container? And the podman version?

**Comment by zhuguoliang** [comment]
> Hi @zhuguoliang, could you try starting the container with `--tmpfs /var/log/mysql`?

I think it works, however, for now I  am trying to figure out a way to do this in podman closure.







> In addition to what @rst0git said, can you share the command-line you are using to checkpoint and restore the container? And the podman version?

I did as suggested in https://github.com/checkpoint-restore/criu/issues/877 and added --tmpfs /run to ease tarball compress problem.

**Comment by adrianreber** [comment]
> >   Hi @zhuguoliang, could you try starting the container with --tmpfs /var/log/mysql?

> I think it works, however, for now I am trying to figure out a way to do this in podman closure.

Sorry, but I do not understand what you mean here. Does it work with`--tmpfs`? What is unclear now or not working?

**Comment by zhuguoliang** [comment]
> > > Hi @zhuguoliang, could you try starting the container with --tmpfs /var/log/mysql?
> 
> > I think it works, however, for now I am trying to figure out a way to do this in podman closure.
> 
> Sorry, but I do not understand what you mean here. Does it work with`--tmpfs`? What is unclear now or not working?

Hi, I mean if in the future, directory like /var/log/mysql will no longer needs tmpfs mount. Because if I want to build platform for CaaS, I cannot be sure that every container follows certain rules defined by podman.

**Comment by adrianreber** [comment]
Podman should handle all changed files correctly in the container. At least in the latest version. Which version are you using? With the latest version `--tmpfs` should not be necessary? As always it would be really helpful if you list all the commands you are using as well as the versions of the software packages you are using.

**Comment by rst0git** [comment]
I can confirm that Podman handles file changes made in the container's root file system. As Adrian mentioned, knowing what versions of software packages are being used is helpful because this feature has been recently introduced.

@zhuguoliang From the log file you provided, I can see that you are using CentOS (Linux 4.18.0-147.5.1.el8_1.x86_64) and CRIU version 3.12. It is likely that you have Podman 1.6.4 installed. There are several checkpoint/restore related commits, such as https://github.com/containers/libpod/pull/4643, that are available in more recent versions of Podman.

**Comment by zhuguoliang** [comment]
Hi, my podman version with mainline  is 9e2e4d7615311b38b1e553af32a5666888ef3c96. I made minor dependency modification which might not affect the restore process.

**Comment by adrianreber** [comment]
As long as you are not listing all commands you are using for us to reproduce we unfortunately cannot help you. From my point of view this should be working.

**Comment by zhuguoliang** [comment]
@adrianreber Hi, the problem is that the experimental container is an internal container which I have no right to expose, I will reopen when I find a public container for us to discuss. Closing for now...

**Comment by adrianreber** [comment]
@zhuguoliang Sounds good. Let us know if you have something for us to reproduce your errors, because we would like to fix it if something is not working as we think it should.
