### ISSUE TITLE
Can't build on RPi Zero; selected processor does not support `dmb ish' in ARM mode

### ISSUE THREAD

**Issue by daviel** [checkpoint-restore/criu#976]
Hello,

I have tried to compile criu on the raspberry pi zero with raspbian (buster). 

It fails with the following message:

ote: Building without GnuTLS support
Makefile.config:39: Warn: you have no libnftables installed
Makefile.config:40: Warn: Building without nftables support
make[1]: Nothing to be done for 'all'.
make[1]: 'images/built-in.o' is up to date.
make[1]: 'compel/plugins/std.lib.a' is up to date.
make[1]: 'compel/plugins/fds.lib.a' is up to date.
make[1]: 'compel/libcompel.a' is up to date.
make[1]: 'compel/compel-host-bin' is up to date.
make[1]: Nothing to be done for 'all'.
make[1]: 'soccr/libsoccr.a' is up to date.
  DEP      criu/arch/arm/bitops.d
  CC       criu/arch/arm/bitops.o
criu/arch/arm/bitops.S: Assembler messages:
criu/arch/arm/bitops.S:13: Error: selected processor does not support `dmb ish' in ARM mode
criu/arch/arm/bitops.S:20: Error: selected processor does not support `dmb ish' in ARM mode
make[2]: *** [/home/pi/criu/scripts/nmk/scripts/build.mk:119: criu/arch/arm/bitops.o] Error 1
make[1]: *** [criu/Makefile:49: criu/arch/arm/crtools.built-in.o] Error 2
make: *** [Makefile:241: criu] Error 2

Kernel: Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
Architecture:        armv6l
Byte Order:          Little Endian
Vendor ID:           ARM
Model name:          ARM1176

Is criu compatible with the armv6 at all? I have checked the file mentioned on top but I am not very experienced regarindg assembler. I am very thankful for every help let me know if I have to provide additional information. :)

**Comment by rppt** [comment]
`dmb ish` is armv7 instruction indeed, in armv6 the same functionality can be achieved with `mcr     p15, 0, r0, c7, c10, 5`.

> Is criu compatible with the armv6 at all?

there is not much platform depended code in CRIU, so it should be after a few fixes like this one :)

**Comment by daviel** [comment]
> `dmb ish` is armv7 instruction indeed, in armv6 the same functionality can be achieved with `mcr p15, 0, r0, c7, c10, 5`.
> 
> > Is criu compatible with the armv6 at all?
> 
> there is not much platform depended code in CRIU, so it should be after a few fixes like this one :)

Thank you this worked but now I encounter another problem.

  CC       criu/pie/restorer.o
/tmp/cc1Wh7cj.s: Assembler messages:
/tmp/cc1Wh7cj.s:6804: Error: invalid constant (1b3) after fixup
make[2]: *** [/home/pi/criu/scripts/nmk/scripts/build.mk:119: criu/pie/restorer.o] Error 1
make[1]: *** [criu/Makefile:59: pie] Error 2
make: *** [Makefile:241: criu] Error 2

In the restorer.c is a assembler call:

`extern void cr_restore_rt (void) asm ("__cr_restore_rt")
                        __attribute__ ((visibility ("hidden")));`

which points to compel/arch/arm/plugins/std/syscalls/syscall-common.S

```
#include "common/asm/linkage.h"

@ We use the register R8 unlike libc that uses R12.
@ This avoids corruption of the register by the stub
@ for the syscall sys_munmap() when syscalls are hooked
@ by ptrace(). However we have to make sure that
@ the compiler doesn't use the register on the route
@ between parasite_service() and sys_munmap().

syscall_common:
        ldr     r7, [r7]
        add     r8, sp, #24
        ldm     r8, {r4, r5, r6}
        svc     0x00000000
        pop     {r4, r5, r6, r7, r8, pc}


.macro syscall name, nr
        .nr_\name :
                .long \nr

        ENTRY(\name)
                push    {r4, r5, r6, r7, r8, lr}
                adr             r7, .nr_\name
                b               syscall_common
        END(\name)
.endm


ENTRY(__cr_restore_rt)
        adr     r7, .nr_sys_rt_sigreturn
        ldr     r7, [r7]
        svc     #0
END(__cr_restore_rt)
```

Any idea how to solve this? I really need to get some assembler knowledge in the future... :)

**Comment by rppt** [comment]
ARM limits the ranges that could be used as immediate values in assembly operations.
If I'm not much mistaken, `adr r7, .nr_\name` and `adr r7, .nr_sys_rt_sigreturn`  could be replaced by `mov r7, .nr_\name` and `mov r7, .nr_sys_rt_sigreturn`

**Comment by daviel** [comment]
> ARM limits the ranges that could be used as immediate values in assembly operations.
> If I'm not much mistaken, `adr r7, .nr_\name` and `adr r7, .nr_sys_rt_sigreturn` could be replaced by `mov r7, .nr_\name` and `mov r7, .nr_sys_rt_sigreturn`

Still no success. Doing this leads to:

- `mov r7,OFFSET .nr_sys_cacheflush'
compel/arch/arm/plugins/std/syscalls/syscalls.S:106: Error: immediate expression requires a # prefix -- `mov r7,OFFSET .nr_sys_ppoll'
compel/arch/arm/plugins/std/syscalls/syscalls.S:107: Error: immediate expression requires a # prefix -- `mov r7,OFFSET .nr_sys_fsopen'
compel/arch/arm/plugins/std/syscalls/syscalls.S:108: Error: immediate expression requires a # prefix -- `mov r7,OFFSET .nr_sys_fsconfig'
compel/arch/arm/plugins/std/syscalls/syscalls.S:109: Error: immediate expression requires a # prefix -- `mov r7,OFFSET .nr_sys_fsmount'
compel/arch/arm/plugins/std/syscalls/syscalls.S:110: Error: immediate expression requires a # prefix -- `mov r7,OFFSET .nr_sys_clone3'
and so on...

Thank you for your help by the way. :) 

I see that the mov command needs an offset in the memory to work but I don't know how to figure it out in assembler...

**Comment by rppt** [comment]
Maybe you could use `ldr` instead of `mov` there

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0041c/Babbfdih.html

**Comment by daviel** [comment]
> Maybe you could use `ldr` instead of `mov` there
> 
> http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0041c/Babbfdih.html

still no sucess:

make[2]: Nothing to be done for 'all'.
  CC       criu/pie/restorer.o
/tmp/ccZobTi2.s: Assembler messages:
/tmp/ccZobTi2.s:6804: Error: invalid constant (1b3) after fixup
make[2]: *** [/home/pi/criu/scripts/nmk/scripts/build.mk:119: criu/pie/restorer.o] Error 1
make[1]: *** [criu/Makefile:59: pie] Error 2
make: *** [Makefile:241: criu] Error 2

**Comment by daviel** [comment]
Anybody with an idea on how to fix this? I would appreciate every help.
