### ISSUE TITLE
Same CID when starting from checkpoint

### ISSUE THREAD

**Issue by thebeancounter** [checkpoint-restore/criu#985]
We are using CRIU with docker, to checkpoint and start a container, how can we get different CID after the start from checkpoint instead of getting the old CID? 

Thanks

**Comment by avagin** [comment]
What is CID? Do you mean container ID?

**Comment by adrianreber** [comment]
If you are actually talking about the container ID, you could try Podman: https://criu.org/Podman

With Podman you can restore from a checkpoint with a new name (`--name`) which will result in a new container ID.
