### ISSUE TITLE
restore using --image-dir not working

### ISSUE THREAD

**Issue by efluder** [checkpoint-restore/criu#987]
Just starting using CRIU and tried the Simple Loop example. C/R works fine if I do not specify the images-dir option. Checkpoints fine (at least without error) if I specify one but will not restore giving several (3) prctl errors.  
Poked around the wiiki and with google, nothing turned up.
What am I doing wrong?

OS is Centos7 and we used the rpm to install version 3.9:
Commands:
criu dump -t 171155 -vvv -o dump.log -D /hpc/users/fludee01/TEST_PGMS/checkpoint/serial/chkpnt/1

criu restore -d -vvv -o restore.log --images-dir /hpc/users/fludee01/TEST_PGMS/checkpoint/serial/chkpnt/1

**Comment by adrianreber** [comment]
So `--images-dir` is a very common option and I have never seen it fail.

Can you provide the complete restore.log of `criu -v4` of a failure you are seeing?

**Comment by efluder** [comment]
[restore.log](https://github.com/checkpoint-restore/criu/files/4344797/restore.log)
[dump.log](https://github.com/checkpoint-restore/criu/files/4344798/dump.log)

Figured you might want to see the dump log as well.

**Comment by adrianreber** [comment]
Did you really want to close this ticket?

And you say you do not get this error when you do not use `--images-dir`?

Can you provide the logs of the failure with the Simple Loop example?

Latest CentOS7 has CRIU 3.12, any chance you can use that?

I am not familiar with the `prctl` code. @avagin who would be the right person to help out here.

**Comment by adrianreber** [comment]
Looking at the CentOS7 3.9 source code of CRIU the following lines should be responsible for the error:
```
(1474)   ret |= sys_prctl_safe(PR_SET_MM, PR_SET_MM_START_BRK,   (long)args->mm.mm_start_brk, 0);
                ...
(1476)   ret |= sys_prctl_safe(PR_SET_MM, PR_SET_MM_ARG_START,   (long)args->mm.mm_arg_start, 0);
               ...
(1478)   ret |= sys_prctl_safe(PR_SET_MM, PR_SET_MM_ENV_START,   (long)args->mm.mm_env_start, 0);
```

**Comment by efluder** [comment]
Ooops! must have hit the wrong button. Sorry.
I'll rerun it with the example simple loop and send the results.
Yes it does work perfectly when I do not specify the image directory.
I'll give a go at building the 3.12 version. Do you know if there is a centos rpm yet?

**Comment by adrianreber** [comment]
> I'll give a go at building the 3.12 version. Do you know if there is a centos rpm yet?

Latest CentOS7 has 3.12. That's why I mentioned that version: https://ftp-stud.hs-esslingen.de/Mirrors/centos/7/os/x86_64/Packages/criu-3.12-2.el7.x86_64.rpm (for example, but also on every other CentOS mirror).

**Comment by efluder** [comment]
Same problem with the example simple loop
[dump.log](https://github.com/checkpoint-restore/criu/files/4344972/dump.log)
[restore.log](https://github.com/checkpoint-restore/criu/files/4344973/restore.log)

**Comment by efluder** [comment]
3.12 works like a champ.
Thanks, Adrian
I'll close this for real now.

Gene
